### ISSUE TITLE
Wildcard path support

### ISSUE THREAD

**Issue by soffes** [getsentry/sentry-cli#1]
It would be great if you could do `*.dSYM` when uploading dSYM files. If you are working with an app that has framework dependencies, you may have several that need to get uploaded.

**Comment by soffes** [comment]
I suppose a directory path would instead if that's easier.

**Comment by dcramer** [comment]
Yeah maybe we can just point to a die and recursively upload all dsyms?

If APIs don't already support it, we can always make it smart enough to only upload ones that aren't available remotely yet.

**Comment by soffes** [comment]
Sounds good to me!

**Comment by mitsuhiko** [comment]
It already uploads recursively but i suppose it would be good if it supports more than one path. The tool already does not upload what's already on there.

**Comment by mitsuhiko** [comment]
Multiple paths are supported now.
