### ISSUE TITLE
INSTALL_PATH not used

### ISSUE THREAD

**Issue by OliverJAsh** [getsentry/sentry-cli#10]
It is possible to set an `INSTALL_PATH`, however this is ignored and the file is always downloaded to `/usr/local/bin/sentry-cli`.

I expect this to install to a dir called `temp`

```
curl -sL https://getsentry.com/get-cli/ | INSTALL_DIR=temp bash
```

**Comment by faergeek** [comment]
I would be glad to make a PR, but I have no idea where installation script leaves :-(

**Comment by mitsuhiko** [comment]
This should be fixed.

**Comment by faergeek** [comment]
@mitsuhiko Nope. Or it's not on https://sentry.io/get-cli/ yet?

```bash
trap cleanup EXIT
curl -SL --progress-bar "$DOWNLOAD_URL" > "$TEMP_FILE"
chmod 0755 "$TEMP_FILE"
if ! mv "$TEMP_FILE" /usr/local/bin/sentry-cli 2> /dev/null; then
  sudo -k mv "$TEMP_FILE" /usr/local/bin/sentry-cli
fi

echo 'Done!'
``

**Comment by faergeek** [comment]
There's literal `/usr/local/bin/sentry-cli` usage

**Comment by mitsuhiko** [comment]
Yeah, it will go out with the next deploy.

**Comment by faergeek** [comment]
Cool, thanks! 👍
