### ISSUE TITLE
Progress Bar breaking npm install

### ISSUE THREAD

**Issue by mdgozza** [getsentry/sentry-cli#1007]
### Environment

How do you use Sentry?
We used Sentry SaaS (sentry.io)

Which SDK and version?
Version 1.68.0

### Steps to Reproduce

1. Have machine ssl traffic intercepted by Enterprise Security Platform Netskope.
2. Attempt to npm install @senty/cli

### Expected Result

npm package should install successfully and download the proper binary.

### Actual Result

It would appear that netskope intercepting https traffic is causing a loss of the http header `content-length`. This setting is not configurable in netskope.

When `content-length` is missing, it causes the `total` variable to become `NaN`
https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js#L176

Later on in the code, when the progress bar tick method is called, a breaking error is thrown from `node-progress`
https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js#L184

```
/Users/marcellog/projects/sentry-cli/node_modules/progress/lib/node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (/Users/marcellog/projects/sentry-cli/node_modules/progress/lib/node-progress.js:160:14)
    at ProgressBar.tick (/Users/marcellog/projects/sentry-cli/node_modules/progress/lib/node-progress.js:97:8)
    at PassThrough.<anonymous> (/Users/marcellog/projects/sentry-cli/scripts/install.js:184:54)
    at PassThrough.emit (events.js:388:22)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at PassThrough.Readable.push (internal/streams/readable.js:223:10)
    at PassThrough.Transform.push (internal/streams/transform.js:166:32)
    at PassThrough.afterTransform (internal/streams/transform.js:101:10)
    at PassThrough._transform (internal/streams/passthrough.js:46:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.68.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.68.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcellog/.npm/_logs/2021-08-11T19_40_09_626Z-debug.log
```

The code base does provide a env var configuration to disable the progress bar
https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js#L34
and I can confirm that when disabling the progress bar, the install works perfectly fine.

I was hoping we could maybe just prevent that code from throwing breaking errors, maybe by simply wrapping the progress bar tick in a try catch?

**Comment by kamilogorek** [comment]
Hey @mdgozza, thanks for both, the detailed issue and the PR. I introduced a slightly different but generalized solution in this PR https://github.com/getsentry/sentry-cli/pull/1011 which will fix it.

**Comment by mdgozza** [comment]
Hi @kamilogorek ,

Thanks for addressing this! Your PR is great. I Really appreciate your help 🥳
