### ISSUE TITLE
Properties file not uploaded

### ISSUE THREAD

**Issue by pnemonic78** [getsentry/sentry-cli#102]
The file `build/intermediates/assets/release/sentry-debug-meta.properties` is not uploaded to sentry.io by `./sdk/node_modules/.bin/sentry-cli` 1.18.0 (macosx)

Log:
```
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
```

**Comment by mitsuhiko** [comment]
Properties files are not uploaded. Why would you expect the properties file to be uploaded?

**Comment by MaTriXy** [comment]
We need the properties to be loaded to Sentry as it's the way Sentry knows the UUID and resolves the Mapping per version. 
As written [here](https://docs.sentry.io/learn/cli/proguard/)
