### ISSUE TITLE
Assets for 1.69.0 appear to be corrupted

### ISSUE THREAD

**Issue by Nuru** [getsentry/sentry-cli#1037]
Downloads of version 1.69.0 of [sentry-cli-Darwin-x86_64](https://github.com/getsentry/sentry-cli/releases/download/1.69.0/sentry-cli-Darwin-x86_64) and [sentry-cli-Linux-x86_64](https://github.com/getsentry/sentry-cli/releases/download/1.69.0/sentry-cli-Linux-x86_64) both produce binaries that give the error 
```
cannot execute binary file: Exec format error
```

I have not tried other release assets for this release, but I suspect there was a build problem that corrupted most if not all of them.

**Comment by wuxushun** [comment]
same error

**Comment by FeSeason** [comment]
same error

**Comment by liuxsen** [comment]
when do you fix it？

**Comment by HazAT** [comment]
@liuxsen this should be fixed with the most recent release 1.69.1 please try and report back
Thanks

**Comment by marandaneto** [comment]
> @liuxsen this should be fixed with the most recent release 1.69.1 please try and report back Thanks

also broken

**Comment by HazAT** [comment]
Sorry, we found the issue and it's fixed now. Also for 1.69.0 and 1.69.1
