### ISSUE TITLE
Info.plist preprocessors

### ISSUE THREAD

**Issue by kesha-antonov** [getsentry/sentry-cli#106]
Hello! 

I use preprocessors in Info.plist. sentry-cli cannot parse that file if I use them:
```
#ifdef DEBUG
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
#else
<dict/>
#endif
```

Can you fix it?

Thanks!

**Comment by mitsuhiko** [comment]
@kesha-antonov that is kinda tricky to deal with. Which step in particular does it fall over? We might have to provide an alternative where Info.plist files are not used and data is provided explicitly.

**Comment by kesha-antonov** [comment]
Thanks! @mitsuhiko
