### ISSUE TITLE
Mac homebrew sentry-cli installation fails with Xcode 13.1

### ISSUE THREAD

**Issue by JetForMe** [getsentry/sentry-cli#1060]
I'm trying to install `sentry-cli`, and despite following the instructions issued (I updated to the latest macOS 11.6.1, and already had Xcode 13.1 installed, but when I rebooted, it offered to install new tools, so I did). I still get the same error. I do not believe my command line tools are outdated, and the message telling me to install Xcode 13.0 is suspect.

```
$ brew install getsentry/tools/sentry-cli
==> Downloading https://downloads.sentry-cdn.com/sentry-cli/1.70.1/sentry-cli-Darwin-universal
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/131256f7e9127e5b45916e00040f1ba9325667cef7e58b425779b454dee30d55--sentry-cli-Darwin-universal
==> Installing sentry-cli from getsentry/tools
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.0.
```

**Comment by surferjeff** [comment]
I see the same error for `brew install hashicorp/tap/terraform`

**Comment by kamilogorek** [comment]
A whole formula for downloading sentry-cli can be found here - https://github.com/getsentry/homebrew-tools/blob/master/Formula/sentry-cli.rb
It's a simple CDN fetch, and there is no any special logic in it besides choosing a platform, which leads me to believe that it is not an issue with sentry-cli, but rather with a specific osx/brew setup.
