### ISSUE TITLE
npx @sentry/cli fails in Docker

### ISSUE THREAD

**Issue by riha** [getsentry/sentry-cli#1063]
### Environment

- Docker version 20.10.5, build 55c4c88
- node:16

A workaround it of course to use curl to bash. But I'd feel safer using npm an a fixed version ... 🥸

### Steps to Reproduce

`docker run node:16 @sentry/cli --version`

### Expected Result

Seeing the version from the @sentry/cli tool in the Docker container.

### Actual Result

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/@sentry/cli'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by kamilogorek** [comment]
Default command for docker node images is `node`, not `npx`, thus it cannot find the module. Use this instead:

```
docker run node:16 npx @sentry/cli --version
```

![image](https://user-images.githubusercontent.com/1523305/140081649-90364b66-1ba1-485f-b0e0-41c0cecb0c0f.png)
