### ISSUE TITLE
sentry-cli project slug setting is impossible to find

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry-cli#1064]
### Environment

How do you use Sentry?
Self hosted v 10.

Which SDK and version?

Sentry-cli 1.71

e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. Try to upload sourcemaps.
2. you get an error "Project slug required"
3. You try to add `--help` to the command. No options are presented.
4. You try `sentry-cli releases --help` 
5. There is nothing about how to add the project info
6. Google and you'll find an issue about this suggesting you add `--project` just after releases but before the subcommand.

### Expected Result
1. The errormessage should suggest where to add the project slug, either as an env file or where in the command.
2. sentry-cli releases --help should also document the --project option.

### Actual Result

I've spent 30 minutes trying to find out how to set the project cli option.

**Comment by kamilogorek** [comment]
It's all right there in our docs: https://docs.sentry.io/product/cli/configuration/

https://docs.sentry.io/product/cli/configuration/#sentry-cli-working-with-projects
https://docs.sentry.io/product/cli/configuration/#explicit-options

**Comment by tarjei** [comment]
@kamilogorek  you misunderstood me.  My expectation was that when I did `sentry-cli releases --help` I would get the option to set the project slug.

**Comment by kamilogorek** [comment]
Ah, excuse me. Fixed in https://github.com/getsentry/sentry-cli/pull/1065

**Comment by tarjei** [comment]
That was quick, kudos!
