### ISSUE TITLE
Unsupported git config

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cli#1068]
### Environment

sentry-cli 1.66.0

in `.git/config`:
```
[extensions]
        worktreeConfig = true
```

### Steps to Reproduce

1. `sentry-cli releases set-commits app.spectre@3.0.4+44 --commit "Spectre / Spectre iOS@build/43-public..HEAD"`

### Expected Result

The release has commits associated to it.

### Actual Result

```
error: unsupported extension name extensions.worktreeconfig; class=Repository (6)
```

**Comment by kamilogorek** [comment]
I just verified it locally and cannot reproduce this issue:

osx version 12.0.1
git version 2.34.1
sentry-cli version 1.66.0 (tested on 1.71.0 as well)

**Comment by lhunath** [comment]
```
$ SENTRY_LOG_LEVEL=trace sentry-cli --log-level trace releases set-commits app.spectre@3.0.4+44 --commit "Spectre / Spectre iOS@build/43-public..HEAD"
error: unsupported extension name extensions.worktreeconfig; class=Repository (6)
$ sentry-cli -V
sentry-cli 1.71.0
```

**Comment by kamilogorek** [comment]
@lhunath I just realized that I broke logging with the `1.71.0` release, debug log should be working in the latest :3

It appears that we will be able to fix it soon, once https://github.com/rust-lang/git2-rs/pull/791 is released.
