### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by erfansahaf** [getsentry/sentry-cli#1069]
### Environment

How do you use Sentry?
self-hosted/on-premise (21.2.0)

Angular SDK 5.27.4

### Steps to Reproduce

Running following commands:

```
sentry-cli --log-level debug --url $SENTRY_URL releases -o $SENTRY_ORG new -p $SENTRY_PROJECT $ANGULAR_RELEASE_VERSION
sentry-cli --log-level debug --url $SENTRY_URL releases -o $SENTRY_ORG -p $SENTRY_PROJECT files $ANGULAR_RELEASE_VERSION \upload-sourcemaps --url-prefix "~/" --rewrite --validate $PREFIX
```

### Expected Result

Upload bundled files without error.

### Actual Result

Some errors appear that says it cannot validate certificate:

```
> Bundled 95 files for upload
error: API request failed
  caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)
  DEBUG   2021-11-08 13:38:27.961803844 +00:00 client close; no transport to shut down  (from sentry)
  DEBUG   2021-11-08 13:38:27.961836029 +00:00 skipping update nagger because session is not attended
```

### Other Info

We are using Let's Encrypt for our SSL.

The error only happens in the CI/CD process. The image that is used for CI/CD container is `node:12.18.3-buster-slim`. Sentry-cli is installed in the Dockerfile with `RUN npm install @sentry/cli -g --unsafe-perm` command.

I have also tried putting the `http.verify_ssl` in the `/root/.sentryclirc`, but it didn't work.

**Comment by mitsuhiko** [comment]
It looks like your docker container does not have the necessary SSL certificates installed. Since this is a debian container you can resolve this issue by installing the necessary package:

```
RUN apt-get update
RUN apt-get install ca-certificates
```
