### ISSUE TITLE
Error while uploading sourcemaps

### ISSUE THREAD

**Issue by psachs21** [getsentry/sentry-cli#107]
I'm trying to upload sourcemaps for a project built with webpack like so:

```bash
sentry-cli releases -o org -p project files 0.1 upload-sourcemaps .
```

And it errors out with this: `error: stream did not contain valid UTF-8`

I examined the soucemaps and they are UTF-8 (or us-ascii)

Not sure which file is causing this. --log-level TRACE doesn't provide any information on which file is causing the issue.

**Comment by mitsuhiko** [comment]
@psachs21 any chance you could mail me the stuff you have? armin@sentry.io

**Comment by psachs21** [comment]
@mitsuhiko unfortunately, it's a closed source project so I can't just send around the code. I was hoping for some hints to solve the issue.

**Comment by mitsuhiko** [comment]
Can you run it with `export RUST_BACKTRACE=1` and then run it again? It should spit out a traceback.

**Comment by psachs21** [comment]
```
Some(stack backtrace:
   0:        0x100d06efe - backtrace::backtrace::trace::h4e764436d0e1e22f
   1:        0x100d0708c - backtrace::capture::Backtrace::new::hd56ee9bd670116be
   2:        0x100d01f36 - error_chain::make_backtrace::hc9c5ac99be322085
   3:        0x100d01fed - _$LT$error_chain..State$u20$as$u20$core..default..Default$GT$::default::h08e396566289bdfa
   4:        0x100ba8dfb - sentry_cli::utils::sourcemaps::SourceMapProcessor::flush_pending_sources::h23cf2950fb8c566f
   5:        0x100bafc43 - sentry_cli::utils::sourcemaps::SourceMapProcessor::upload::h74a91d9da22f1406
   6:        0x100b57c50 - sentry_cli::commands::releases::execute_files_upload_sourcemaps::hdca6925293b9c84c
   7:        0x100b5deab - sentry_cli::commands::releases::execute::h7ee917335d4fcb05
   8:        0x100b8a168 - sentry_cli::commands::execute::hf4390a913b4655a3
   9:        0x100a8cb54 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8deb23c69a30c526
  10:        0x100ddff2a - __rust_maybe_catch_panic
  11:        0x100ad3bef - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h93f174968875a467
  12:        0x100ddc105 - std::sys::imp::thread::Thread::new::thread_start::h993b7e5cb7871f66
  13:     0x7fffa89b293a - _pthread_body
  14:     0x7fffa89b2886 - _pthread_start)
```

**Comment by mitsuhiko** [comment]
Thanks, I will investigate.

**Comment by psachs21** [comment]
So i narrowed the issue down to some specific files that we host. They are a particularly large set of files (yfiles and fusioncharts) which I don't really care about uploading sourcemaps for. Unfortunately, they are not open source projects so i can't upload their source in order to expose the issue. Not sure which part of them is causing this issue. If i could exclude those directories from the upload command, that would help.

**Comment by mitsuhiko** [comment]
You can pass multiple paths to the upload command so if those files are in separate folders you should be able to exclude them by only listing the ones that you care about. Does that help?

**Comment by psachs21** [comment]
Not ideal given the current setup, which is a flat list of assets with those directories at the same level.

```
app.js
app.js.map
...
yfiles/
fusioncharts/
...
```

Workable but not ideal. Will need to build something around it.

**Comment by mitsuhiko** [comment]
We can look into adding a way to exclude based in an ignore file or
something similar.

**Comment by psachs21** [comment]
I would think the ideal solution would be to catch these exceptions, put a log out saying skipping file X due to an error, and then continue. I might not even need the file upload option for my uses but I was experimenting with sentry locally so that's the only way i figured i could get sourcemaps working.

**Comment by mitsuhiko** [comment]
I changed it now that it does not error. In fact it will now also perform charset detection to still detect minified files more accurately (hopefully).

**Comment by psachs21** [comment]
Awesome. I look forward to giving it a shot.
