### ISSUE TITLE
Checksum of https://downloads.sentry-cdn.com/sentry-cli/1.53.0/sentry-cli-Linux-x86_64 has changed

### ISSUE THREAD

**Issue by gkranis** [getsentry/sentry-cli#1078]
### Overview
We pin the checksum of the `sentry-cli` binary in our playbooks. We noticed that it changed today. I'm reporting it in case this reflects a security issue. In the meantime we have switched from
`https://downloads.sentry-cdn.com/sentry-cli/1.53.0/sentry-cli-Linux-x86_64` to `https://github.com/getsentry/sentry-cli/releases/download/1.53.0/sentry-cli-Linux-x86_64` which still returns the expected checksum

### Steps to Reproduce

1. `curl https://downloads.sentry-cdn.com/sentry-cli/1.53.0/sentry-cli-Linux-x86_64`
2. `sha256sum sentry-cli-Linux-x86_64`

### Expected Result

`b6b00850c9cac9f521e3158524e183c5cad09fe8b252a9be2d72107cae14e778` which is the checksum that this binary used to have and also the checksum that https://github.com/getsentry/sentry-cli/releases/download/1.53.0/sentry-cli-Linux-x86_64 still has

### Actual Result
`893ae8696cd029a1f3fca6ea3c854a8aa621bdee235770440a33df9237f63c0b`

**Comment by mitsuhiko** [comment]
These are in fact the same file, but the file you are getting from the CDN is gzip encoded:

```http
$ curl -i https://downloads.sentry-cdn.com/sentry-cli/1.53.0/sentry-cli-Linux-x86_64
HTTP/2 200
expires: Wed, 22 Dec 2021 07:39:33 GMT
last-modified: Mon, 18 May 2020 17:35:24 GMT
etag: "1d46152e797cee032dfe3bc7fe65d18a"
content-type: application/octet-stream
content-encoding: gzip
cache-control: public, max-age=2592000
accept-ranges: bytes
age: 20301
date: Mon, 22 Nov 2021 13:17:55 GMT
vary: Accept-Encoding
access-control-allow-origin: *
server: Fastly
strict-transport-security: max-age=31536000; includeSubDomains
content-length: 6180918
```

If you download that file with wget for instance the file will be decoded automatically from gzip. I am however surprised that this behavior changed and will do some investigations.

In any case after decompressing the files are the same:

```
mitsuhiko at cheetah in /tmp/cli
$ curl -L https://downloads.sentry-cdn.com/sentry-cli/1.53.0/sentry-cli-Linux-x86_64 > sentry-cli-Linux-x86_64.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6036k  100 6036k    0     0  17.8M      0 --:--:-- --:--:-- --:--:-- 18.1M

mitsuhiko at cheetah in /tmp/cli
$ shasum -a256 sentry-cli-Linux-x86_64.gz
893ae8696cd029a1f3fca6ea3c854a8aa621bdee235770440a33df9237f63c0b  sentry-cli-Linux-x86_64.gz

mitsuhiko at cheetah in /tmp/cli
$ gunzip sentry-cli-Linux-x86_64.gz

mitsuhiko at cheetah in /tmp/cli
$ shasum -a256 sentry-cli-Linux-x86_64
b6b00850c9cac9f521e3158524e183c5cad09fe8b252a9be2d72107cae14e778  sentry-cli-Linux-x86_64
```

**Comment by mitsuhiko** [comment]
I cannot reproduce this behavior on new releases which again are being returned uncompressed. I am assuming at one point in 2020 files were uploaded differently. Going to close this as invalid for now since I believe this behavior is acceptable on old releases.
