### ISSUE TITLE
Proguard map file not recognized

### ISSUE THREAD

**Issue by simonkeliuotis** [getsentry/sentry-cli#108]
Proguard map file is indicated as unusable (Usable: no (missing line information)) while using 'sentry-cli difutil check [path-to-file]' command, similar message was shown while trying to upload this file to Sentry (proguard mapping '[path-to-file]' was ignored because it does not contain any line information.). The map file looks correct, I was able to retrace / deobfuscate errors.

**Comment by mitsuhiko** [comment]
We only support proguard files that have line information included. You will need to add this to your proguard config:

```
-keepattributes LineNumberTable,SourceFile
```

**Comment by simonkeliuotis** [comment]
@mitsuhiko thanks, that fixed the problem, but now, I get another error: `http error: generic error (400)` Why this error is being thrown?

**Comment by mitsuhiko** [comment]
My guess is you are using self hosted sentry. The current release version
does not yet support proguard I think. The master version does

**Comment by simonkeliuotis** [comment]
Currently I'm using sentry official hosting services

**Comment by mitsuhiko** [comment]
Hi,

Can you run with --log-level=debug and paste the output?

**Comment by simonkeliuotis** [comment]
`> compressing mappings
> uploading mappings
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/org-name/project-name/files/dsyms/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api sending form data
[INFO] sentry_cli::api > POST /api/0/projects/org-name/project-name/files/dsyms/ HTTP/1.1
[INFO] sentry_cli::api > Host: sentry.io
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.18.0
[INFO] sentry_cli::api > Authorization: Bearer ***
[INFO] sentry_cli::api > Content-Length: 19723
[INFO] sentry_cli::api > Content-Type: multipart/form-data; boundary=------------------------c79d18aed1f2e5ba
[INFO] sentry_cli::api < HTTP/1.1 201 CREATED
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Wed, 16 Aug 2017 15:25:13 GMT
[INFO] sentry_cli::api < Content-Type: application/json
[INFO] sentry_cli::api < Content-Length: 2
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: GET, POST, HEAD, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-c401c6a4
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 201
[INFO] sentry_cli::api body: []
> Uploaded a total of 0 new mapping files
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/org-name/project-name/files/dsyms/associate/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api sending JSON data (145 bytes)
[INFO] sentry_cli::api > POST /api/0/projects/org-name/project-name/files/dsyms/associate/ HTTP/1.1
[INFO] sentry_cli::api > Host: sentry.io
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.18.0
[INFO] sentry_cli::api > Authorization: Bearer ***
[INFO] sentry_cli::api > Content-Type: application/json
[INFO] sentry_cli::api > Content-Length: 145
[INFO] sentry_cli::api < HTTP/1.1 400 BAD REQUEST
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Wed, 16 Aug 2017 15:25:13 GMT
[INFO] sentry_cli::api < Content-Type: application/json
[INFO] sentry_cli::api < Content-Length: 38
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: POST, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-c9683d4c
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 400
[INFO] sentry_cli::api body: {"build": ["This field is required."]}
error: http error: generic error (400)`
