### ISSUE TITLE
Permission denied when running Sentry CLI from NPM Workspaces

### ISSUE THREAD

**Issue by GasimGasimzada** [getsentry/sentry-cli#1081]
### Environment

- Ubuntu 20

How do you use Sentry?

The error happens before the values are even sent to Sentry.

Which SDK and version?

- JS CLI 1.71.0 (using `npx sentry-cli`)
- Webpack Plugin v1.18.3

### Steps to Reproduce

- Setup a minimum configuration in project's (not global) `.sentryclirc` that defines project, url, and org
- Store SENTRY_AUTH_TOKEN in environmental variables
- Run `npx sentry-cli info`

### Expected Result

Configuration information shown

### Actual Result

I keep getting ["Failed to load .sentryclirc file from the home folder.](https://github.com/getsentry/sentry-cli/blob/b2e72518d7dfc4330c8b411e80bf59088483e3fc/src/config.rs#L465) followed by the assertion thrown: [Config not bound yet](https://github.com/getsentry/sentry-cli/blob/master/src/config.rs#L85).

I am not familiar with Rust and due to the fact that it does not show the path that it tries to access, I don't know where this is happening. I found the following [line](https://github.com/getsentry/sentry-cli/blob/b2e72518d7dfc4330c8b411e80bf59088483e3fc/src/config.rs#L427), which looks like it it trying to find `$HOME/.sentryclirc` (https://docs.rs/dirs/2.0.2/dirs/fn.home_dir.html) so, I checked the $HOME variable and it points to user's home directory. I even created an empty `.sentryclirc` file there just to be sure but no luck. This only happened after I migrated my JS repo to monorepo.

**Comment by kamilogorek** [comment]
I was not able to reproduce this issue locally. Can you run `SENTRY_LOG_LEVEL=debug npx sentry-cli info` command and provide the log output? (make sure to bump your sentry-cli to `1.72.0` as we fixed logging there)

**Comment by kamilogorek** [comment]
Closing the issue due to it being inactive.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
