### ISSUE TITLE
Allow usage of project_id except only slug

### ISSUE THREAD

**Issue by fliespl** [getsentry/sentry-cli#1083]
Currently different parts of sentry ecosystem either expect project_id or project_slug to work correctly.

I.e. DSN only allows project_id and sentry-cli allows only project_slug.

Since project unique is a subject to change within sentry dashboard, it would be best if one could enter project_id as cli argument as opposed to only project slug.

That would make it:
- more reliable (id won't change), 
- easier/safer for deployments (same id used for both sentry DSN setup and sentry-cli releases part) - more error-prone, 
- more consistent within sentry ecosystem.

**Comment by kamilogorek** [comment]
It would all have to be changed in the API of Sentry itself, which is slug-based, so sorry, but currently it's a no-go in the CLI.
