### ISSUE TITLE
React Native, Gradle, Android - Debug & Info Log Level from android.app/buil.gradle prints same output

### ISSUE THREAD

**Issue by majirosstefan** [getsentry/sentry-cli#1084]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
  "@sentry/react-native": "^3.2.4",

### Steps to Reproduce

1. Set logging level in android/app/build.gradle

```
 project.ext.sentryCli = [
    logLevel: "debug"
]

```

2. Set logging level in android/app/build.gradle

```
 project.ext.sentryCli = [
    logLevel: "info"
]

```

### Expected Result
I would expect that the build output would be different (e.g. logging level set to debug would print more information on what's going on).

### Actual Result
The outputs are the same.

```
Uploading sourcemaps for release com.myapp@1.0.0+31 distribution 31
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: orgName
> Project: projectName
> Release: com.myapp@1.0.0+31
> Dist: 31

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
```

So, what is the purpose of setting a logging level if the output is the same, please?

**Comment by kamilogorek** [comment]
Your gradle log should print what arguments were used to invoke the CLI, can you verify what's printed in both cases?

https://github.com/getsentry/sentry-react-native/blob/4fd13137fe71984d1166c33198076da9db28f158/sentry.gradle#L132
