### ISSUE TITLE
Sentry CLI Plugin ENOENT error with `npm ci --ignore-scripts`

### ISSUE THREAD

**Issue by PsyGik** [getsentry/sentry-cli#1085]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
e.g: JavaScript (latest `@sentry/nextjs`)

### Steps to Reproduce

1. Setup Sentry for Next.js project
2. CI starts the build with `npm ci --ignore-scripts`
3. Run `npm build`
4. Sentry fails with the below error.

```
Run `npm audit` for details.
❯ npm run build

> try-sentry-nextjs@0.1.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

Sentry CLI Plugin: spawn /Users/ddd/Development/Reviews/try-sentry-nextjs-review/node_modules/@sentry/cli/sentry-cli ENOENT


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/ddd/Development/Reviews/try-sentry-nextjs-review/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (/Users/ddd/Development/Reviews/try-sentry-nextjs-review/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/Users/ddd/Development/Reviews/try-sentry-nextjs-review/node_modules/next/dist/build/index.js:77:25)
```

### Expected Result

Sentry should not be executing stuff in CI environments.

### Actual Result

Sentry executes stuff in CI environments.

--- 
Related: https://github.com/getsentry/sentry-cli/issues/915

**Comment by gerbyzation** [comment]
Running into this issue as well after bootstrapping a next project with `@sentry/wizard`

**Comment by lobsterkatie** [comment]
Hi, @PsyGik. Sorry you're running into this.

I've left a comment on [the issue you linked](https://github.com/getsentry/sentry-cli/issues/915), about a potential long-term fix, but in the short term, I've added a check to make sure the `sentry-cli` binary exists before we try to use it.
