### ISSUE TITLE
After the @sentry project is used to build, the css resource reports cross domain problems and fetch errors? Ask the great God for advice, thank you.

### ISSUE THREAD

**Issue by zh17625375207** [getsentry/sentry-cli#1086]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

Failed to load resource: net::ERR_FAILED

Uncaught (in promise) TypeError: Failed to fetch

![image](https://user-images.githubusercontent.com/40682261/145520604-e7c0085e-9acf-4311-b8b0-78284e98a3b5.png)

![image](https://user-images.githubusercontent.com/40682261/145519842-8501a9f0-60cc-4eff-8d51-a22a5cf05185.png)
### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by sl0thentr0py** [comment]
Hi @zh17625375207, please refer to our documentation here
https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracingorigins
