### ISSUE TITLE
Check Environment Variables Of Xcode

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cli#1087]
When uploading the dSYMs with a [run script phase of Xcode](https://docs.sentry.io/platforms/apple/dsym/#uploading-symbols-with-sentry-cli) you need to provide 
```
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
```
in the input files section. According to @armcknight, sentry-cli could read that via environment variables and as well as the `$DWARF_DSYM_FOLDER_PATH` we pass to sentry-cli. Therefore, we could remove the input files section and maybe also simplify our [script](https://docs.sentry.io/platforms/apple/dsym/#uploading-symbols-with-sentry-cli) a bit.

After doing this, we also need to update the [docs](https://docs.sentry.io/platforms/apple/dsym/#uploading-symbols-with-sentry-cli).

**Comment by philipphofmann** [comment]
One way to see all the environment variables of Xcode
* Create an empty Xcode project for iOS
* Add a Run Script Phase with `exit 1`
* Check the build error

**Comment by kamilogorek** [comment]
As we discussed, I believe this is not something that we can implement on the cli-side, as it's xcode configuration for when to run script, not anything related to the upload itself.

**Comment by armcknight** [comment]
I’m not sure what was discussed offline, but maybe there’s some misunderstanding. Xcode already forwarded the values of these environment variables to the process if it’s invoked in a RSBP. Therefore there’s no need to deference them and pass them as arguments/envvars/inputfiles, and the check in the if test could be done in the cli tool’s logic.

**Comment by kamilogorek** [comment]
To clarify, are we talking about Input Files part of xcode setup?

**Comment by armcknight** [comment]
Ah actually just the Input Files for this.

**Comment by kamilogorek** [comment]
After doing a few checks, here's my conclusion:

- Removing `DWARF_DSYM_FOLDER_PATH` from `upload-dif` command is not something we should really do, as this command is quite generic, handling multiple types of debug files, and with the current implementation, it's quite obvious where those files come from. This script is a copy-paste anyway, so I'd prefer to keep it more explicit.

- Input files are not used anywhere in the cli nor in the symbolic crate, it's only used to determine when all required files have been processed, and when script can be executed. Thus there's nothing to be changed here tbh.

If I'm missing something, let me know :)
