### ISSUE TITLE
CodePush: Failed to upload AppCenter deployment history

### ISSUE THREAD

**Issue by icecapp** [getsentry/sentry-cli#1098]
I have the following script in place to upload CodePush source maps to Sentry
```bash
CODEPUSH_DIST=$(appcenter codepush deployment history $APP_ENV -a $FULL_APP_NAME --output json | jq '.[-1][0]' -r)
RELEASE_NAME="$BUNDLE_ID"@"$APP_BINARY_VERSION"+codepush:"$CODEPUSH_DIST"

echo "CODEPUSH_DIST: " $CODEPUSH_DIST
echo "RELEASE_NAME: " $RELEASE_NAME

sentry-cli react-native appcenter \
  "$APP_NAME" "$PLATFORM" "./build/$PLATFORM/CodePush" \
  --deployment "$APP_ENV" \
  --release-name "$RELEASE_NAME" \
  --dist "$CODEPUSH_DIST" \
  --org "$ORGANIZATION_ID" \
  --project "$APP_NAME"
```
The result is
```bash
CODEPUSH_DIST:  v11
RELEASE_NAME:  com.myappco.myapp.staging@1.0+codepush:v11
> Fetching latest AppCenter deployment info
error: Failed to load AppCenter deployment history
  caused by: 
```
So the `RELEASE_NAME` and `CODEPUSH_DIST` are both there.

Why is `sentry-cli` `Fetching latest AppCenter deployment info again` ?

**Comment by icecapp** [comment]
And why is it failing ? Why is there no cause? 
```
error: Failed to load AppCenter deployment history
  caused by: 
  ```

**Comment by kamilogorek** [comment]
Can you run this your upload script again, but with `SENTRY_LOG_LEVEL=debug` env variable set? This should give us more detailed logs.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
