### ISSUE TITLE
error: http error: [1] Unsupported protocol

### ISSUE THREAD

**Issue by swisstofu** [getsentry/sentry-cli#11]
Hello, 

I'm using a compiled version of `sentry-cli` on a fedora 24, and i'm getting an error 

```
error: http error: [1] Unsupported protocol
```

Any idea ? 

thanks

**Comment by mitsuhiko** [comment]
I'm not really sure what causes this. Can you run it with `--log-level=debug`?

**Comment by mitsuhiko** [comment]
I am going to close this.
