### ISSUE TITLE
yarn install Building fresh packages but not end

### ISSUE THREAD

**Issue by nbili** [getsentry/sentry-cli#1100]
### Environment

node version 14

### Steps to Reproduce

`yarn add @sentry/cli`

![image](https://user-images.githubusercontent.com/22109673/149727029-c2bf8a83-d84f-40d8-8f8c-c8ebeaa472d3.png)

### Expected Result

it was installed , need to end.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by kamilogorek** [comment]
I cannot reproduce it locally.

```sh
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ yarn add @sentry/cli
```

This will use GitHubs release to fetch the binary. Can you give it a try?

**Comment by nbili** [comment]
Thank you for your reply. @kamilogorek 

I change the `.npmrc` set `sentrycli_cdnurl` to fetch other mirrors, it look good for me.
