### ISSUE TITLE
Always use configured url for chunk upload requests

### ISSUE THREAD

**Issue by niklaswa** [getsentry/sentry-cli#1109]
When trying to upload a lot of data to a self hosted sentry instance, the POST request gets quite large.
Our sentry instance is behind a proxy service (Cloudflare) which only allows a maximum of 100 MB of POST data.

I thought I could just use our internal IP + port of our sentry instance without going through CF/reverse proxies, but apparently when the script makes the chunk-upload request it gets the external/public URL as a reference and uses it for the following chunk upload requests.

Maybe it would be possible to allow force using the given url in the configuration.
But I suppose, that would have to be changed in the [sentry-cli](https://github.com/getsentry/sentry-cli/blob/f5fe115813c61ee388023bd11f2ac67e00c4b873/src/api.rs#L2335) itself, but as it's only really an issue in this project, I created it here - just close it, if it's in the wrong place.

**Comment by kamilogorek** [comment]
When `chunk-upload` returns a relative `url` configuration, it will use `url` option (dart option mentioned above) as it's prefix. Thus to fix that, you should be able to modify your self-hosted instance config, namely `system.upload-url-prefix` option, to an empty prefix, and use `--url` to select which host the request should go to.

Note that this change has been introduced in October last year, so you may need to update your on-premise instance https://github.com/getsentry/sentry/pull/29347

See discussions:
https://github.com/getsentry/sentry-cli/issues/839
https://github.com/getsentry/sentry-cli/pull/862
