### ISSUE TITLE
sentry-cli difutil bundle-sources .\ -> error: Access is denied. (os error 5)

### ISSUE THREAD

**Issue by tjenssen** [getsentry/sentry-cli#1116]
under Windows I can not create the bundle-sources

sentry-cli difutil bundle-sources .\

  DEBUG   2022-02-04 20:06:29.366460100 +00:00 sentry-cli version: 1.72.1, platform: "windows", architecture: "i686"
  INFO    2022-02-04 20:06:29.384171400 +00:00 sentry-cli was invoked with the following command line: "sentry-cli" "difutil" "bundle-sources" ".\\"
error: Access is denied. (os error 5)
  INFO    2022-02-04 20:06:29.416026 +00:00 Skipping update nagger update check

any idea what it could be?

**Comment by tjenssen** [comment]
sorry - not sure why I tried dir instead of a file

**Comment by miguelflores1993** [comment]
> sentry-cli difutil bundle-sources .\

What I do not understand is what type of file I have to select, the documentation is not very clear, the first time I do this type of configuration and it is costing me a lot
