### ISSUE TITLE
Sentry crashing without proper debug information when . xcodeproj is not valid

### ISSUE THREAD

**Issue by grzegorzkrukowski** [getsentry/sentry-cli#1126]
### Environment

How do you use Sentry?
Sentry CLI - directly pushed to GIT repository. I am running it on GitHub workers - tried both macOS and Linux - both failing

Which SDK and version?
sentry-cli 1.73.0

### Steps to Reproduce

I lately changed our CLI setup to keep `Package.resolved` files in the repository for caching purposes. 
This makes my repository have empty `.xcodeproj` that just has `Package.resolved` in it - no more files from typical xcodeproj exists there.

With that state - SentryCLI is failing, differently for different environments:
- macOS - crashing with `thread 'unnamed' panicked at 'Command `xcodebuild -list -json -project`
- ubuntu - crashing with `error: No such file or directory (os error 2)`

### Expected Result

I would expect Sentry to just ignore discovering InfoPlist file in that case - maybe with a warning, but not crashing.
If that's expected behavior - the errors should be more readable - especially for Ubuntu - took me half a day to figure out what's actually happening there.
Also would be nice to just have a flag to skip this auto-discovery if it cannot be silently skipped without errors.

### Actual Result

Sentry failed to upload my pre-generated dSYMs.

**Comment by kamilogorek** [comment]
Can you run the command with `SENTRY_LOG_LEVEL=debug` and provide the log please?

**Comment by grzegorzkrukowski** [comment]
Hey @kamilogorek - here you go - I had to hide all private stuff with ***
It's really easy to reproduce by just creating a `.xcodeproj` and deleting everything beside `Package.resolved` in it.

```
  DEBUG   2022-02-28 13:34:22.762848 +01:00 sentry-cli version: 1.73.0, platform: "darwin", architecture: "x86_64"
  INFO    2022-02-28 13:34:22.763676 +01:00 sentry-cli was invoked with the following command line: "sentry-cli" "--auth-token" "*****************" "upload-dif" "dSYMs" "--org" "*******" "--project" "******" "--log-level=debug"
  INFO    2022-02-28 13:34:22.764024 +01:00 Issuing a command for Organization: ******** Project: *******
thread 'unnamed' panicked at 'Command `xcodebuild -list -json -project *****.xcodeproj` failed to produce a valid JSON output.': src/utils/xcode.rs:120

   0: backtrace::backtrace::trace

Abort trap: 6
```
