### ISSUE TITLE
Unify where ProgressBar and Logging are written

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-cli#1130]
### Environment

We're using sentry-cli to upload symbols as part of the build process in the sentry-unity SDK. I've noticed that when SENTRY_LOG_LEVEL env var is configured, some logs are written to stderr, even though they're just INFO level as an example. From a quick look, I assume this line is responsible: https://github.com/getsentry/sentry-cli/blob/4fde3280b4a7231733c42040747eda75d790c35b/src/utils/logging.rs#L75-L79

[This is the place](https://github.com/getsentry/sentry-unity/pull/607/files#diff-33dd65bbdffe8c1099e276c49804112fa0c7cba38eeec03787b7112b583f17cbR116) where we got it captured in stderr. Note: currently the log level environment var is not set there in the PR to avoid showing "WARNING: INFO" kind of logs to the user.

### Steps to Reproduce

1. set SENTRY_LOG_LEVEL=info, 
3. run the CLI, redirecting stdout and stderr to different streams.

### Expected Result

I'd expect non-error logs to be printed to `stdout`

### Actual Result

INFO logs end up in stderr

---------
edit: added missing link to the code where this is hit

**Comment by kamilogorek** [comment]
The problem now is two-fold. The default in the `indicatif` lib is `stderr`, but we basically override it - https://github.com/getsentry/sentry-cli/blob/4fde3280b4a7231733c42040747eda75d790c35b/src/utils/progress.rs#L93-L101 however, we still call `ProgressBar::new_spinner` and `ProgressBar::new` in some places without redirecting it to a single descriptor, making it not consistent. It's all over the place now.

I'll let myself change the title of this issue to be more generic. Thanks for reporting.

**Comment by vaind** [comment]
> `2.0.0-beta.0` has been released, give it a try and let me know if your issue has been resolved 🎉

Created an issue to do that: https://github.com/getsentry/sentry-unity/issues/674
