### ISSUE TITLE
Huge commit info cause cli set-commit 502

### ISSUE THREAD

**Issue by shaodahong** [getsentry/sentry-cli#1131]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
self-hosted

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

Refactor about six hundred files and commit, when use `npx sentry-cli set-commit $version --auto` report 502 bad gatway

### Expected Result

What you thought would happen.

set commit success

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

![image](https://user-images.githubusercontent.com/14831261/156535885-671029b9-6e17-44d5-baad-4f774be1ccc0.png)

**Comment by kamilogorek** [comment]
Can you provide full debug log using `SENTRY_LOG_LEVEL=debug`?
The first thing you can try is setting `http.keepalive=false` in your configuration file, see: https://docs.sentry.io/product/cli/configuration/#configuration-values

**Comment by kamilogorek** [comment]
Can you provide full debug log using `SENTRY_LOG_LEVEL=debug`?
The first thing you can try is setting `http.keepalive=false` in your configuration file, see: https://docs.sentry.io/product/cli/configuration/#configuration-values

If that wont help, please post on https://github.com/getsentry/self-hosted as this is issue with the server configuration, no the CLI itself. Thanks!
