### ISSUE TITLE
Sentry-cli   npm  version is 1.73.2，but the release version is  1.73.1;

### ISSUE THREAD

**Issue by guibwl** [getsentry/sentry-cli#1135]
HI!
Sentry-cli   npm  version is 1.73.2， but the release version is  1.73.1;

Can anyone sync?

It makes an error caused when downloading from the mirror;

**Comment by Gitby-Leo** [comment]
Lock old version
```
"resolutions": {
    "@sentry/cli": "1.73.1"
}

**Comment by kamilogorek** [comment]
Our CI timed out on GH artifacts upload, sorry for the inconvenience. Fixed.
