### ISSUE TITLE
Sentry sentry_upload_dif runs forever

### ISSUE THREAD

**Issue by romansorochak** [getsentry/sentry-cli#1138]
### Environment

- `GitHub Actions` (Current runner version: '2.288.1')
- `macOS  11.6.4`
- `Xcode 13.2.1`
- `fastlane 2.204.3`
- `fastlane-plugin-sentry (1.11.1)` (also tried with previous version `1.11.0`)
- `sentry-cli 1.73.2`

### Steps to Reproduce

Run  command `sentry_upload_dif` after creation of build and uploading to TestFlight.

```ruby
sentry_upload_dif(
      auth_token: "#{ENV["SENTRY_AUTH_TOKEN"]}",
      org_slug: "#{ENV["SENTRY_ORG_SLUG"]}",
      project_slug: "#{ENV["SENTRY_PROJECT_SLUG"]}"
)
```

### Expected Result

It should not run forever.

### Actual Result

It freezes. And when workflow reach 1 hour `GitHub Actions` cancels the workflow. (time out)

<img width="1190" alt="Screenshot 2022-03-08 at 22 39 38" src="https://user-images.githubusercontent.com/7702356/157321065-0003309a-192a-4a86-8d7c-b3bfd211b388.png">

**Comment by bruno-garcia** [comment]
Moving to the Sentry CLI repo since the fastlane plugin is just a wrapper, and through the logs we can see it gets to the point where it invokes sentry-cli

@kamilogorek said:

> The only change related to this was update to symbolic in 1.73.0. If that's possible, they can lock to 1.72.2 and see if the issue persists.

**Comment by romansorochak** [comment]
@bruno-garcia @kamilogorek  Thanks for advice
Though previously I was trying with `sentry-cli 1.72.2` as well. The result was the same - time out.

<img width="1068" alt="Screenshot 2022-03-09 at 22 44 51" src="https://user-images.githubusercontent.com/7702356/157532840-09360294-279c-4259-b900-691a7019431b.png">

**Comment by kamilogorek** [comment]
Can you run the action with `SENTRY_LOG_LEVEL=debug` variable set and provide the logs?

**Comment by romansorochak** [comment]
@kamilogorek Hi
1. `SENTRY_LOG_LEVEL=debug` didn't change anything to me. It still didn't do anything after "Prepared debug information files for upload". (same as on screenshot above)

2. Though today I found that the issue was magically resolved. Not sure the reason but noticed few updates.
    1. day before it used `sentry-cli 1.74.1 installed!` & `fastlane 2.204.3 ` - issue appeared
    2. today it used newer version of sentry-cli & fastlane and it worked just fine !  
    `sentry-cli 1.74.2 installed!` & `Updating fastlane from 2.204.3 to 2.205.0` - issue resolved

**Comment by kamilogorek** [comment]
There was no changes affecting this feature between `1.74.1` and `1.74.2`, but glad it works!
I'll let myself close this issue, but please report back if it breaks again. Thanks!
