### ISSUE TITLE
API requests are not following HTTP302 redirects

### ISSUE THREAD

**Issue by kubijo** [getsentry/sentry-cli#1139]
### Environment

self-hosted/on-premise @ 22.1.0

Which SDK and version?
@sentry/cli: 1.73.2
nodejs: v16.13.1

### Steps to Reproduce

Note: I have redacted some information like returned json payload in the successful case, projects list & the real backend origin... however the idea & relevant info should be, I believe, intact.

The problem is that when I run the binary manually (either through the path returned by `yarn bin sentry-cli` or through `yarn run sentry-cli`) I'm getting what I need.

However, I need to run this programmatically because I need to upload source maps after webpack compilation completes.

The command below is a basis for connection testing routine used before webpack compilation starts so that I can validate sentry connection details in the compilation ENV as soon as possible.

#### When running the binary directly in my bash session
<pre>
<font color="#06989A"><b>pool/web-ui</b></font> <font color="#CC0000"><b>❯</b></font> /opt/dev/braiins/pool/web-ui/.yarn/unplugged/@sentry-cli-npm-1.73.2-cc2f072cf0/node_modules/@sentry/cli/sentry-cli projects list
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.010599970 +01:00 sentry-cli version: 1.73.2, platform: &quot;linux&quot;, architecture: &quot;x86_64&quot;
<span style="background-color:#06989A"><font color="#000000">  INFO   </font></span> 2022-03-09 23:14:24.010770434 +01:00 sentry-cli was invoked with the following command line: &quot;/opt/dev/braiins/pool/web-ui/.yarn/unplugged/@sentry-cli-npm-1.73.2-cc2f072cf0/node_modules/@sentry/cli/sentry-cli&quot; &quot;projects&quot; &quot;list&quot;
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.011745605 +01:00 request GET https://host.zone/api/0/organizations/braiins/projects/?cursor=
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.011834628 +01:00 using token authentication
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.011890054 +01:00 retry number 0, max retries: 0
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074444039 +01:00 &gt; GET /api/0/organizations/braiins/projects/?cursor= HTTP/1.1
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074475956 +01:00 &gt; Host: host.zone
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074487049 +01:00 &gt; Accept: */*
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074496671 +01:00 &gt; Connection: TE
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074507949 +01:00 &gt; TE: gzip
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.074530133 +01:00 &gt; User-Agent: sentry-cli/1.73.2
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.075059347 +01:00 &gt; Authorization: Bearer 4249615e***
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193780068 +01:00 &lt; HTTP/1.1 200 OK
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193853113 +01:00 &lt; Server: nginx
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193888338 +01:00 &lt; Date: Wed, 09 Mar 2022 22:14:24 GMT
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193924584 +01:00 &lt; Content-Type: application/json
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193957496 +01:00 &lt; Content-Length: 5279
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.193989830 +01:00 &lt; Link: &lt;http://host.zone/api/0/organizations/braiins/projects/?&amp;cursor=100:-1:1&gt;; rel=&quot;previous&quot;; results=&quot;false&quot;; cursor=&quot;100:-1:1&quot;, &lt;http://host.zone/api/0/organizations/braiins/projects/?&amp;cursor=100:1:0&gt;; rel=&quot;next&quot;; results=&quot;false&quot;; cursor=&quot;100:1:0&quot;
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194026293 +01:00 &lt; Allow: GET, HEAD, OPTIONS
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194055251 +01:00 &lt; Access-Control-Allow-Methods: GET, HEAD, OPTIONS
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194099544 +01:00 &lt; Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194131914 +01:00 &lt; Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194162147 +01:00 &lt; Access-Control-Allow-Origin: *
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194191054 +01:00 &lt; X-Sentry-Rate-Limit-Remaining: 619
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194220616 +01:00 &lt; X-Sentry-Rate-Limit-Limit: 620
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194250624 +01:00 &lt; X-Sentry-Rate-Limit-Reset: 1646864065
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194281041 +01:00 &lt; Vary: Accept-Language, Cookie
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194311472 +01:00 &lt; Content-Language: en
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194341051 +01:00 &lt; X-Frame-Options: deny
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194370260 +01:00 &lt; X-Content-Type-Options: nosniff
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194399649 +01:00 &lt; X-XSS-Protection: 1; mode=block
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.194460280 +01:00 response status: 200
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:24.195633979 +01:00 body: [{…redacted…}]
+----+---------------+-----------------+--------------+
| ID | Slug          | Team            | Name         |
+----+---------------+-----------------+--------------+
| 1  | internal      | Sentry          | Internal     |
| …and other projects…                                |
+----+---------------+-----------------+--------------+
</pre>

#### When running through bash script

Note: I get the same in nodejs with either of `execa[Sync]` / `subprocess.execFile[Sync]`

<pre>
<font color="#06989A"><b>pool/web-ui</b></font> <font color="#CC0000"><b>❯</b></font> shared/dev/sentry/assertConnection &quot;${SENTRY_DSN}&quot; &quot;http://host.zone&quot; 4
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.479761679 +01:00 sentry-cli version: 1.73.2, platform: &quot;linux&quot;, architecture: &quot;x86_64&quot;
<span style="background-color:#06989A"><font color="#000000">  INFO   </font></span> 2022-03-09 23:14:33.479802906 +01:00 sentry-cli was invoked with the following command line: &quot;/opt/dev/braiins/pool/web-ui/.yarn/unplugged/@sentry-cli-npm-1.73.2-cc2f072cf0/node_modules/@sentry/cli/sentry-cli&quot; &quot;projects&quot; &quot;list&quot;
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.480007790 +01:00 request GET http://host.zone/api/0/organizations/braiins/projects/?cursor=
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.480020122 +01:00 using token authentication
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.480026442 +01:00 retry number 0, max retries: 0
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501056255 +01:00 &gt; GET /api/0/organizations/braiins/projects/?cursor= HTTP/1.1
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501090426 +01:00 &gt; Host: host.zone
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501104349 +01:00 &gt; Accept: */*
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501116583 +01:00 &gt; Connection: TE
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501130517 +01:00 &gt; TE: gzip
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501144724 +01:00 &gt; User-Agent: sentry-cli/1.73.2
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.501838970 +01:00 &gt; Authorization: Bearer 4249615e***
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508177910 +01:00 &lt; HTTP/1.1 302 Found
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508219011 +01:00 &lt; Cache-Control: no-cache
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508236392 +01:00 &lt; Content-length: 0
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508253790 +01:00 &lt; Location: https://host.zone/api/0/organizations/braiins/projects/?cursor=
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508338620 +01:00 response status: 302
<span style="background-color:#C4A000"><font color="#000000">  DEBUG  </font></span> 2022-03-09 23:14:33.508369493 +01:00 body: 
<font color="#CC0000">error:</font> not a JSON response
</pre>

Here is the content of the `assertConnection` file.
I though, that this might work out given what I observed and I'd run this script with prepared arguments from nodejs.

```bash
#!/usr/bin/env bash

# Will throw when connection to sentry instance declared
# in env variables cannot be established by sentry-cli or when returned
# list of projects does not include one declared in env variable.

set -e

DIR_HERE=$(realpath "$(dirname "$0")")
DIR_WEBUI="$(realpath "$DIR_HERE"/../..)/"
function fail {
    printf >&2 "%s: ERROR: %s\n" "$SELF" "$*"
    exit 1
}
function succeed {
    printf >&2 "%s: INFO: %s\n" "$SELF" "$*"
    exit 0
}

DSN=${1}
ORIGIN=${2}
PROJECT_ID=${3}

[[ -z "${DSN}" ]] && fail '"DSN" missing!'
[[ -z "${ORIGIN}" ]] && fail '"ORIGIN" missing!'
[[ -z "${PROJECT_ID}" ]] && fail '"PROJECT_ID" missing!'

cd "${DIR_WEBUI}"

export SENTRY_ORG="braiins"
export SENTRY_URL="${ORIGIN}"

$(yarn bin sentry-cli) projects list
```

**Comment by kubijo** [comment]
Further investigation lead to thinking that a possible solution might be to allow us users to force the [`follow_location`](https://github.com/getsentry/sentry-cli/blob/32fe9a286f29a9ec10ee1cdc84d78013d927f082/src/api.rs#L1653) flag by either CLI flag (preferably) or at least an environment variable … properties file is mostly just annoying to add for a single purpose

**Comment by kubijo** [comment]
The problem was confirmed to be one of CLI not following http → https redirects…

**Comment by kubijo** [comment]
That was a typo on my side, but it doesn't seem to me like something that should break the whole process… although YMMV of course

**Comment by kamilogorek** [comment]
Oh, ok. So the original issue is resolved, and currently this should be renamed to add the behavior of following redirects?

**Comment by kubijo** [comment]
Yes, I think that makes sense (I didn't originaly see that the issue is with redirects not being followed, but now that it's confirmed…)

**Comment by kamilogorek** [comment]
Now I remember why we decided not to implement 302 redirects for every request. It's mostly due to the fact, that some upload configuration is coming directly from the Sentry server, and it may possibly mask other configuration issues.

We had a similar issue here: https://github.com/getsentry/sentry-cli/issues/936#issuecomment-814742129

I'll let myself close the issue, as we've never had a report of it being a problem that cannot be fixed in one way or another. If it will become more relevant again, I'd prefer someone to create a new issue and I will happily see what we can do about it.

Cheers!
