### ISSUE TITLE
Roadmap: sentry-cli V2

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-cli#1143]
### Roadmap:

The goal for next major release of sentry-cli is to ensure that certain legacy implementations are removed to ensure we benefit from all security updates, along with removing unused implementations. Everything listed here is not dependent on a major release, but it is considered with the road map. This major will also provide improved CLI UX for many users who may want to interact with Sentry through CLI. Also improved testing and capturing errors within sentry-cli so we can better proactively prevent bad releases and react to errors in the wild.

- ✅  Drop support for Node pre v12 and modernize JS codebase
  - node used to fetch binary of cli - risk of not getting any security updates
  - jest, node fetch, et al require at least v12
- ✅  Update all Rust dependencies
  - sentry-cli ~6 years ago - many dependencies were never updated and some are deprecated, updating them
- ✅  Update to clap v3 to resolve all CLI-UX issues (FUNT-64)
  - ✅  Fix dreaded: "Cannot run 'releases files' with release name starting with 'list...'"
  - ✅  Fix dreaded: "Make organization slug and other necessary options position independent"
- ✅  Migrate from `failure` to `anyhow` crate, as sentry dropped support for `failure` in version 0.22
  - packages in rust for error reporting - failure is no longer supported
  - `anyhow` will allow us to capture errors in cli 
- ✅  Reevaluate all `SENTRY_` and other env variables for install script and cli itself
~- Update JS API for the CLI~ (not required with current breaking changes set)
~- Update sentry-webpack-plugin to use new API~ (not required with current breaking changes set)
- Update documentation for sentry-cli (this might be problematic due to missing "choose version dropdown" and some breaking changes)

### Implement proposed API changes 
  - ✅  Remove difutil id subcommand
  - ✅  Remove react-native codepush subcommand
  - ✅  Remove react-native-gradle and react-native-xcode commands
  - ✅  Remove upload-dsym command (legacy artifact upload for native)
  - ✅  Remove monitors command (experiment never used)
    - still in UI - hidden behind feature flag
  - ✅  Remove bash-hook command (migrate it into a separate repository)
  - #1164  (create, update, delete - listing is already implemented) 
  - #1165 (read, delete - or make it a subcommand for projects) 
  - #1112 (make it an alias for release files upload-sourcemaps and extend with sourcemaps related features like verify or resolve) 
    - all docs and tool reliant on this api - see last point of roadmap - 
    - if all else fails workaround is document gap
  - #1167 (create, read, update, delete) 
  - #1168 (blocked by missing features in sentry-rust) 
    - given some file, send evelope with DSN - rust cannot create an envelope
    - possibly to add it in sentry-rust but not timeline commitment, also not blocking v2
  - ✅  Write integration tests infrastructure using trycmd

### Implement proposed improvements
_not dependent on any major release_

  - ✅  List commits for a release
  - Provide binary for FreeBSD
  - ✅  Support multiple custom headers (value add for on-prem customers with own or 3rd party proxies)
  - ✅  API requests are not following HTTP302 redirects
  - ✅  Rewrite ancient logging mechanism, as its not unified, noisy and difficult to control by users
  - ✅  Add --append option for setting release references
  - ✅  setCommits with auto option should accept an environment parameter
  - ✅  Check all TODO/FIX/FIXME/NOTE
  - ✅  Rework VCS test to not rely on CI cloning all commits
  - ✅  Change `custom_header` to `header` and `CUSTOM_HEADER` to `SENTRY_HEADER`

**Comment by armenzg** [comment]
I'm looking into removing [SENTRY_CLI_NO_EXIT_TRAP](https://github.com/getsentry/sentry-cli/pull/1050) since it didn't do what I had expected it to do. Would it worked if we drop it as part of v2? or should I go ahead now? (Only 1 other dev on Github is using it and it might be by mistake).

**Comment by kamilogorek** [comment]
@armenzg whole bash-hook will be dropped in favor of https://github.com/getsentry/sentry-cli-bash-hook/ if we even decide to leave at all.

v2-dev commit: https://github.com/getsentry/sentry-cli/commit/96466cf30a71f7bd6495f2980c5f773d656fa685

**Comment by armenzg** [comment]
I should have read your initial comment more closely! Nvm me :)
