### ISSUE TITLE
Error code 1 when installing with npm > 6

### ISSUE THREAD

**Issue by shapeshifta78** [getsentry/sentry-cli#1150]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
@sentry/react 6.16.1 and @sentry/webpack-plugin 1.18.3

### Steps to Reproduce

I upgraded npm to version 7 and node to version 14. When I try to run `npm install` even with no package-lock I get an error code 1.

### Expected Result

Installlation passes.

### Actual Result

npm ERR! code 1
npm ERR! path /home/***/Projects/***/node_modules/@sentry/cli
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js

**Comment by shapeshifta78** [comment]
I tried adding it to package.json, but I cannot install it globally in our build system. Does that answer your question? I also cleaned the npm cache.

**Comment by kamilogorek** [comment]
Did you also try to use `—unsafe-perm` when installing deps? Global installation should not be necessary, but this sometimes help in itself due to different permissions setups.

**Comment by shapeshifta78** [comment]
I just ran ` npm install @sentry/cli --save --legacy-peer-deps --unsafe-perm` and got the same error :\

**Comment by kamilogorek** [comment]
Can you run the same command with `--verbose` flag and provide the log output? If it errors, there should be also a path to the log file where it stored everything.

Another thing we can try is for you to `git clone https://github.com/getsentry/sentry-cli.git` and after cd'ing `npm install`. If that succeeds, then it's the problem of running the script itself within other packages, not the script itself. 

Does `npm` perform the cleanup after this error happens? Or do you have `node_modules/@sentry/cli` directory present? If so, you can go there and try running `npm run install` or `node ./scripts/install.js` directly.

**Comment by kamilogorek** [comment]
I also have a one suspicion about how `npm` runs, which will be approached here: https://github.com/getsentry/sentry-cli/pull/1151

**Comment by shapeshifta78** [comment]
After lots of trying and reinstalling/cleaning different node versions via snap, I thought maybe the snap packet is the issue as the problem happened as well with other packages, e.g. child processes failing.

I installed node again via https://deb.nodesource.com/setup_16.x and then everything worked like before. Sorry for thinking sentry-cli is the one to blame. I wonder what the problem with the snap package is... 

Anyway, thanks a lot for you time and help. I was amazed how fast you responded! Case close :)

**Comment by kamilogorek** [comment]
Thanks for the write-up, it will be really useful for the future reference! Cheers.
