### ISSUE TITLE
pdb unsupported file error

### ISSUE THREAD

**Issue by sapsari** [getsentry/sentry-cli#1158]
Trying to upload my pdb files, have two, one is being uploaded the other one is not. Getting unsupported file error

Dll/pdb files are C# .Net standard 2.0 with Visual Studio 17.1.1
Attached dll & pdb files

C:\Users\SARI\Downloads>sentry-cli-Windows-x86_64.exe difutil check "D:\Develop\Pattern Maker\Source\AsyncToolWindow\bin\Release\PatternMaker.pdb" --log-level=debug
  INFO    2022-03-18 11:15:33.560184700 +03:00 Loaded config from C:\Users\SARI\.sentryclirc
  DEBUG   2022-03-18 11:15:33.562055500 +03:00 sentry-cli version: 1.73.2, platform: "windows", architecture: "x86_64"
  INFO    2022-03-18 11:15:33.563215 +03:00 sentry-cli was invoked with the following command line: "sentry-cli-Windows-x86_64.exe" "difutil" "check" "D:\\Develop\\Pattern Maker\\Source\\AsyncToolWindow\\bin\\Release\\PatternMaker.pdb" "--log-level=debug"
error: Unsupported file
  INFO    2022-03-18 11:15:33.566595600 +03:00 Skipping update nagger update check

[Release.zip](https://github.com/getsentry/sentry-cli/files/8302829/Release.zip)

**Comment by Swatinem** [comment]
We indeed do not support C# .NET pdb files; only "normal" C++ ones.
