### ISSUE TITLE
Problems using codepush

### ISSUE THREAD

**Issue by nerdmed** [getsentry/sentry-cli#117]
Hey guys i needed to restore my computer from a backup and now my sentry-cli command is just not working. It was before. The error is not really helpful. Any suggestions would be really appreciated!

```bash
sentry-cli --auth-token MYVERYLONGTOKEN react-native codepush my-app ios build/ios \
    --deployment Staging \
    --org flowkey \
    --project my-sentry-project
> Fetching latest code-push package info
error: Could not open Info.plist file
  caused by: No such file or directory (os error 2)
```

sentry-cli 1.19.1
node: v8.4.0

**Comment by nerdmed** [comment]
I have reverted my version to v1.16.0 this one works just fine!

**Comment by peteroid** [comment]
I got the same issue. Reverting the sentry-cli-binary to v0.18.0 worked for me.

Error happened on:
- sentry-cli: 0.19.1
- react-native: 0.46.4
- node: 8.5.0
- macOS: 10.12.6

**Comment by mitsuhiko** [comment]
This is fixed with next release.

**Comment by nerdmed** [comment]
@mitsuhiko can you share the version number with us? And when do you expect it?

**Comment by mitsuhiko** [comment]
Will be in 1.20

**Comment by mitsuhiko** [comment]
It's out now.

**Comment by HazAT** [comment]
Hey, please update to the latest version `1.20` and see https://docs.sentry.io/clients/react-native/codepush/ how to use it.
