### ISSUE TITLE
Unable to install using Brew

### ISSUE THREAD

**Issue by squarefrog** [getsentry/sentry-cli#1177]
### Environment

How do you use Sentry?
Via command line on macOS 12.3. Using Homebrew 3.4.5

Which SDK and version?
N/A

### Steps to Reproduce

```
❯ brew install sentry-cli
```

### Expected Result

The latest production cli client would be installed.

### Actual Result

Brew attempts, and fails, to install a pre-release version.

```
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

sentry-cli 1.74.2 is already installed but outdated (so it will be upgraded).
==> Downloading https://downloads.sentry-cdn.com/sentry-cli/2.0.0-beta.0/sentry-cli-Darwin-universal
Already downloaded: /Users/paulwilliamson/Library/Caches/Homebrew/downloads/c94e526ae1e761c1a3e28f564ce947a046b2cd0ea2a4d29a32d38cf7a4c81b75--2.0.0-beta.0
==> Upgrading getsentry/tools/sentry-cli
  1.74.2 -> 2.0.0-beta.0

Error: An exception occurred within a child process:
  TypeError: no implicit conversion of nil into String
```

Happens on both our CI server running Big Sur 11.6.1, and my local machine running Monterey 12.3

**Comment by kamilogorek** [comment]
Sorry for the disturbance, should be fixed now. It was first major bump in over 5 years, and I wasn't aware brew will pick it up :3

**Comment by squarefrog** [comment]
Great, thanks for the quick fix!
