### ISSUE TITLE
Update docs - Windows

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cli#118]
Windows build needs x86
Microsoft Visual Studio C++ 2015 redistributable 
https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685

We should add this to the docs.

**Comment by mitsuhiko** [comment]
Going to close this as we're now also making 64bit windows builds which do not have this issue.

**Comment by ThatBean** [comment]
Still get this error using [Windows-x86_64(1.26.1)](https://github.com/getsentry/sentry-cli/releases/download/1.26.1/sentry-cli-Windows-x86_64.exe) on a Windows10 Pro 1709 x64 machine.

In my case, I still need to install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587) to make it work.

The error message I get before I installed *Visual C++ 2015*:

```
$ ./sentry-cli.exe --version
  .../sentry-cli.exe: 
    error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: 
      cannot open shared object file: No such file or directory
```
