### ISSUE TITLE
Mapping file not visible into dashboard, after getting response 200 from Sentry cli

### ISSUE THREAD

**Issue by sargamV01** [getsentry/sentry-cli#1180]
### Environment

How do you use Sentry?
Sentry Cli -1.74.3

### Steps to Reproduce
Use sentry Cli to upload the mapping file into dashboard.
I am getting success response while uploading the mapping file from sentry, but file not visible into dashboard.
Logs
body: [{“id”:“203496968”,“uuid”:“123e4567-e89b-12d3-a456-426614174002”,“debugId”:“123e4567-e89b-12d3-a456-426614174002”,“codeId”:null,“cpuName”:“any”,“objectName”:“proguard-mapping”,“symbolType”:“proguard”,“headers”:{“Content-Type”:“text/x-proguard+plain”},“size”:6442617,“sha1”:“86f8d1642fa872ac5a0292891190c6f7d1a0a80d”,“dateCreated”:“2022-04-08T06:50:21.267090Z”,“data”:{“features”:[“mapping”]}}]

Uploaded a total of 1 new mapping files
Newly uploaded debug symbols:
123e4567-e89b-12d3-a456-426614174002
DEBUG 2022-04-08 12:20:21.446819 +05:30 request POST https://sentry.io/api/0/projects/android-payu/payu-c7/reprocessing/
DEBUG 2022-04-08 12:20:21.446850 +05:30 using token authentication
DEBUG 2022-04-08 12:20:21.446868 +05:30 retry number 0, max retries: 0
DEBUG 2022-04-08 12:20:21.447097 +05:30 > POST /api/0/projects/android-payu/payu-c7/reprocessing/ HTTP/1.1
DEBUG 2022-04-08 12:20:21.447198 +05:30 > Host: [sentry.io](http://sentry.io/)
DEBUG 2022-04-08 12:20:21.447225 +05:30 > Accept: /
DEBUG 2022-04-08 12:20:21.447244 +05:30 > Connection: TE
DEBUG 2022-04-08 12:20:21.447341 +05:30 > TE: gzip
DEBUG 2022-04-08 12:20:21.447363 +05:30 > User-Agent: sentry-cli/1.74.3
DEBUG 2022-04-08 12:20:21.447433 +05:30 > Authorization: Bearer e3061b1e***
DEBUG 2022-04-08 12:20:21.447473 +05:30 > Content-Length: 0
DEBUG 2022-04-08 12:20:21.762110 +05:30 < HTTP/1.1 200 OK
DEBUG 2022-04-08 12:20:21.762177 +05:30 < Server: nginx
DEBUG 2022-04-08 12:20:21.762200 +05:30 < Date: Fri, 08 Apr 2022 06:50:21 GMT
DEBUG 2022-04-08 12:20:21.762222 +05:30 < Content-Length: 0
DEBUG 2022-04-08 12:20:21.762244 +05:30 < Connection: keep-alive
DEBUG 2022-04-08 12:20:21.762262 +05:30 < allow: POST, OPTIONS
DEBUG 2022-04-08 12:20:21.762279 +05:30 < access-control-allow-methods: POST, OPTIONS
DEBUG 2022-04-08 12:20:21.762302 +05:30 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
DEBUG 2022-04-08 12:20:21.762321 +05:30 < access-control-expose-headers: X-Sentry-Error, Retry-After
DEBUG 2022-04-08 12:20:21.762343 +05:30 < access-control-allow-origin: *
DEBUG 2022-04-08 12:20:21.762371 +05:30 < x-sentry-rate-limit-remaining: 418
DEBUG 2022-04-08 12:20:21.762404 +05:30 < x-sentry-rate-limit-limit: 420
DEBUG 2022-04-08 12:20:21.762434 +05:30 < x-sentry-rate-limit-reset: 1649400622
DEBUG 2022-04-08 12:20:21.762462 +05:30 < x-sentry-rate-limit-concurrentremaining: 299
DEBUG 2022-04-08 12:20:21.762489 +05:30 < x-sentry-rate-limit-concurrentlimit: 300
DEBUG 2022-04-08 12:20:21.762505 +05:30 < vary: Accept-Language, Cookie
DEBUG 2022-04-08 12:20:21.762521 +05:30 < content-language: en
DEBUG 2022-04-08 12:20:21.762540 +05:30 < x-frame-options: deny
DEBUG 2022-04-08 12:20:21.762557 +05:30 < x-content-type-options: nosniff
DEBUG 2022-04-08 12:20:21.762572 +05:30 < x-xss-protection: 1; mode=block
DEBUG 2022-04-08 12:20:21.762590 +05:30 < x-envoy-attempt-count: 1
DEBUG 2022-04-08 12:20:21.762617 +05:30 < x-envoy-upstream-service-time: 48
DEBUG 2022-04-08 12:20:21.762646 +05:30 < x-served-by: getsentry-web-default-production-764cc59bf8-ppgl5
DEBUG 2022-04-08 12:20:21.762658 +05:30 < x-served-by: lb-8
DEBUG 2022-04-08 12:20:21.762668 +05:30 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
DEBUG 2022-04-08 12:20:21.762705 +05:30 response status: 200
DEBUG 2022-04-08 12:20:21.762735 +05:30 body:

### Expected Result
mapping file should visible into the CLI dashboard.

### Actual Result
Mapping file not visible.

**Comment by kamilogorek** [comment]
Can you confirm that this is still an issue? Mapping files can take a few minutes to be processed.
