### ISSUE TITLE
InvalidExpressionError on /api/0/projects/{organization_slug}/{project_slug}/events/

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry-cli#1184]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
sentry-cli/1.74.3

### Steps to Reproduce

N/A -- This error was reported in Sentry and the user-agent value in some of the events pointed to `sentry-cli/1.74.3`

### Expected Result

CLI shouldn't be sending a request with a negative cursor offset.

### Actual Result

The cursor was sent as `0:-1:1` which triggered an InvalidExpressionError on the server. See [here](https://sentry.io/organizations/sentry/issues/3183471586/events/40298a6a01f94689b5270d8e222b1949/?project=1).

The DnD team has added a backlog item to catch the error and validate it earlier instead of throwing a 500 error, but I wanted to flag this for visibility in case there is something actionable on the CLI side to prevent a negative offset. Some of the events are also triggered by the frontend which requires some investigation on our side.

**Comment by kamilogorek** [comment]
Every pagination query is implemented via a generic `Pagination` struct that extracts its values from `link` header of a given request. Eg. initial request to list all projects will look like that:

```
link: <https://sentry.io/api/0/organizations/kamil-test/projects/?&cursor=100:-1:1>; rel="previous"; results="false"; cursor="100:-1:1", <https://sentry.io/api/0/organizations/kamil-test/projects/?&cursor=100:1:0>; rel="next"; results="false"; cursor="100:1:0"
```

Listing of events has been added here https://github.com/getsentry/sentry-cli/pull/1047 and it probably triggered this issue during testing, which means that there might be a discrepancy between how cursors are handled for events and other listings.

Currently, we support listings for:

```
/projects/<org>/<project>/releases/<release>/files/?cursor={}
/organizations/<org>/releases/<release>/files/?cursor={}
/organizations/<org>/projects/?cursor={}
/organizations/<org>/repos/?cursor={}
```

This newly added endpoint, was in fact: 
```
/projects/<org>/<project>/events/?cursor={}
```

**Comment by kamilogorek** [comment]
This issue is not relevant to the CLI anymore right now, as PR introducing this issue has not been merged.
