### ISSUE TITLE
Flag -p (--project) disappeared from new releases CLI

### ISSUE THREAD

**Issue by fuegoio** [getsentry/sentry-cli#1186]
### Environment

_How do you use Sentry?_ Sentry SaaS (sentry.io).
_Which SDK and version?_ Sentry CLI 2.0

### Steps to Reproduce

We were running the folowing command in our CI:

```
sentry-cli releases new -p PROJECT_1 -p PROJECT_2 $CIRCLE_SHA1
```

### Expected Result

Normally the `-p` should not have changed between the versions of the CLI and should be the minified version of `--project`.

### Actual Result

It fails because `-p` is not understood, you have to replace it with `--project`.

**Comment by kamilogorek** [comment]
It does exist, but for some reason, `clap` is thinking that `-p` is the name of your new release, not the flag. 

```
sentry-cli releases new $CIRCLE_SHA1 -p PROJECT_1 -p PROJECT_2
```

and

```
sentry-cli releases -p PROJECT_1 -p PROJECT_2 new $CIRCLE_SHA1
```

work just fine.

I'll see what's up with that.

**Comment by Lonli-Lokli** [comment]
@kamilogorek So the easiest fix as of now is to use `--project` instead of `-p`, right?

I think a lot of applications are now affected

**Comment by kamilogorek** [comment]
Fix is coming :)

**Comment by Lonli-Lokli** [comment]
I also noticed one more failing command, which was not mentioned as breaking change in changelog for 2.0
```
sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps $DIST_DIR -x .js -x .map --validate --verbose --rewrite --strip-common-prefix

error: Found argument '--verbose' which wasn't expected, or isn't valid in this context
	Did you mean '--version'?
	If you tried to supply `--verbose` as a value rather than a flag, use `-- --verbose`
```

**Comment by kamilogorek** [comment]
@Lonli-Lokli it was mentioned, as this flag had no effect:

https://github.com/getsentry/sentry-cli/blob/master/CHANGELOG.md#removed-apis

> ref: Remove deprecated and hidden flags from commands (remove listed flags usage) (breaking)
> releases upload-sourcemaps --verbose

**Comment by ss098** [comment]
The problem still exists in the Docker image (tag 2.0.0, e16824fcbfb3).

I think the latest version needs to be rebuilt.

**Comment by kamilogorek** [comment]
Yes, release is in progress. Please be patient.

**Comment by kamilogorek** [comment]
`2.0.1` with fixed hyphenated names has been published.
