### ISSUE TITLE
add support to get lower version https://sentry.io/get-cli/

### ISSUE THREAD

**Issue by zxccvvv** [getsentry/sentry-cli#1188]
Hi Sentry Team,

i need some way to accessing [v1.74.3](https://sentry.io/get-cli/) because my other team already setup supported CI for that version,
is there a way to achieve it? since https://sentry.io/get-cli/ would auto install v2.0.0 and it is give me an error while running task in CircleCI

**Comment by JasonIamAUnixAdmin** [comment]
Hey Sentry CLI team you keep closing issues around this problem there by reducing visibility that you are working on the fix. You should probably have a top level issue open that links to all the bug reports coming your way. 

Lots of folks can't deploy right now, more visibility to the problem and the fix being worked on and or pulling 2.0.0 out of circulation might be nice

**Comment by zxccvvv** [comment]
Hi @kamilogorek , i still got an error while running CircleCI.
i need to deploy this update ASAP, could you help me to access lower of version 1.74.3?
i just deployed one hour before v2.0.0 coming out, and everything work.

<img width="875" alt="Screen Shot 2022-04-12 at 21 27 05" src="https://user-images.githubusercontent.com/19633881/162985220-449b2173-7fdc-44d4-af80-d7cd59c38db1.png">

**Comment by kamilogorek** [comment]
You can safely remove `--ignore-empty` flag from the cli call. It has no use, and is listed in the breaking changelog:

https://github.com/getsentry/sentry-cli/blob/master/CHANGELOG.md#200

**Comment by zxccvvv** [comment]
> You can safely remove --ignore-empty flag from the cli call. It has no use, and is listed in the breaking changelog

so i need to change `config.yml` script in all my other's project. i can't do that right now, since it would takes time

is there no option like accessing https://sentry.io/get-cli/1.74.3 to get bash script?

**Comment by kamilogorek** [comment]
@zxccvvv everything should be working back again, thanks for your patience.
