### ISSUE TITLE
The subcommand 'upload-dsym' wasn't recognized

### ISSUE THREAD

**Issue by Max-Job** [getsentry/sentry-cli#1190]
> [14:48:17]: ------------------------------
> [14:48:17]: --- Step: default_platform ---
> [14:48:17]: ------------------------------
> [14:48:17]: Driving the lane 'ios symbols' 🚀
> [14:48:17]: --------------------------------
> [14:48:17]: --- Step: sentry_upload_dsym ---
> [14:48:17]: --------------------------------
> [14:48:17]: sentry-cli 2.0.1 installed!
> [14:48:18]: Starting sentry-cli...
> [14:48:18]: error: The subcommand 'upload-dsym' wasn't recognized
> [14:48:18]: If you believe you received this message in error, try re-running with 'sentry-cli -- upload-dsym'
> 

something seems to have broken in the last two releases. Everything was working fine this morning.

**Comment by Max-Job** [comment]
I tried to build my iOS app in a bitrise, but I got this error. I saw you changed upload-dsym to debug-files upload, but I can't found guide how and where I should apply it

**Comment by GLJeffery** [comment]
This also breaks the fastlane command `sentry_upload_dsym` I believe

**Comment by GLJeffery** [comment]
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_sentry.rb

**Comment by mokagio** [comment]
See also https://github.com/getsentry/sentry-fastlane-plugin/pull/119

**Comment by kamilogorek** [comment]
@zxccvvv everything should be working back again in `2.0.2`, thanks for your patience.
