### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by ShaneMcNamara** [getsentry/sentry-cli#1191]
My builds are failing because @sentry/cli is throwing a TypeError when I try to install the package.

### Environment

Happens on multiple Bitbucket Pipelines and my local Mac OS

### Steps to Reproduce

1. Run `npm install @sentry/cli` 

### Expected Result

Package is installed

### Actual Result

`
info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.0.1/sentry-cli-Darwin-universal
TypeError: Right-hand side of 'instanceof' is not an object
npm WARN notsup Unsupported engine for node-fetch@3.2.3: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: node-fetch@3.2.3
npm WARN notsup Unsupported engine for fetch-blob@3.1.5: wanted: {"node":"^12.20 || >= 14.13"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fetch-blob@3.1.5
npm WARN notsup Unsupported engine for formdata-polyfill@4.0.10: wanted: {"node":">=12.20.0"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: formdata-polyfill@4.0.10
npm WARN sentry-test@1.0.0 No description
npm WARN sentry-test@1.0.0 No repository field.
`

**Comment by gmathieu** [comment]
I ran into the same thing today. Had to pin version to `yarn add @sentry/cli@1.74.3`

**Comment by kamilogorek** [comment]
@zxccvvv everything should be working back again in `2.0.2`, thanks for your patience.

**Comment by ShaneMcNamara** [comment]
@kamilogorek  - I am getting a different error now:

`
info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.0.2/sentry-cli-Darwin-universal
Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/2.0.2/sentry-cli-Darwin-universal.
Error message: Not supported
Error code: undefined
`
