### ISSUE TITLE
HTTP 504 when trying to add new a release

### ISSUE THREAD

**Issue by YaseminAkyuz** [getsentry/sentry-cli#1195]
I'm using sentry-cli 2.0.0 I'm running the following command:
sentry-cli releases "my release version here" -p "my project"

I'm getting this result:

error: API request failed
  caused by: sentry reported an error: gateway timeout (http status: 504)

**Comment by smeubank** [comment]
could this be related to the same issue which was resolved here?

 https://github.com/getsentry/sentry-cli/pull/1187

**Comment by kamilogorek** [comment]
504 is a connection issue, it is not related to the cli functionality per-se.
