### ISSUE TITLE
.sentryclirc ignored

### ISSUE THREAD

**Issue by umerkk** [getsentry/sentry-cli#1211]
### Environment

How do you use Sentry?
on-prem CI runner.
"@sentry/cli": "^1.74.4",

Which SDK and version?
    "@sentry/electron": "^3.0.2",
    "@sentry/integrations": "^6.17.0",
    "@sentry/node": "^6.17.0",

### Steps to Reproduce

I have installed sentryycli through NPM to be used in our CI runner.
I am invoking the sentrycli inside a bash script that looks something like 
`
./node_modules/.bin/sentry-cli releases new "$HUB_VERSION"
`
and I do have a .sentryclirc file at the root of my project that has 

[defaults]
project=hub-dev
org=myOrg

although when the bash script is executed, it does not read the project & org info from the .sentryclirc and spills out an error to provide this info in-line.

any thoughts on whats going wrong here?

**Comment by kamilogorek** [comment]
You can run the command with `--log-level=debug` or `SENTRY_LOG_LEVEL=debug` and it should print out if and what config was attempted to initialize.
