### ISSUE TITLE
npm latest tag points to 1.7.4 instead of 2.0.4

### ISSUE THREAD

**Issue by urbany** [getsentry/sentry-cli#1224]
Hi, just noticed NPM latest tag is wrong. May be a bug in your release script.

![Screenshot 2022-04-29 at 09 31 53](https://user-images.githubusercontent.com/50884/165910901-cd023ce3-3892-478d-86d1-e0e37ae2ef71.png)

**Comment by kamilogorek** [comment]
Fixed it, thank you 🙇
