### ISSUE TITLE
Homebrew installs 1.74.4 instead of 2.0.4

### ISSUE THREAD

**Issue by vincentisambart** [getsentry/sentry-cli#1229]
### Steps to Reproduce

1. On a Mac with Homebrew installed, run `brew install getsentry/tools/sentry-cli`
2. Even though the latest version is 2.0.4, 1.74.4 gets installed.

### Expected Result

Version 2.0.4 gets installed.

### Actual Result

Version 1.74.4 got installed.

Looking at the Homebrew formula history, it seems you released 2.0.4 and 1.74.4 the same day, with 1.74.4 being released last and overriding 2.0.4: https://github.com/getsentry/homebrew-tools/commits/master/Formula

**Comment by kamilogorek** [comment]
Great catch, thanks. We need to update our Brew releasing workflow.
