### ISSUE TITLE
install failed on ubuntu

### ISSUE THREAD

**Issue by djereg** [getsentry/sentry-cli#123]
```
$ sudo npm i -g sentry-cli-binary
/usr/local/bin/sentry-cli -> /usr/local/lib/node_modules/sentry-cli-binary/bin/sentry-cli

> sentry-cli-binary@1.20.0 install /usr/local/lib/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

{ Error: EACCES: permission denied, open '/usr/local/lib/node_modules/sentry-cli-binary/bin/../sentry-cli'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/sentry-cli-binary/bin/../sentry-cli' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.20.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/djereg/.npm/_logs/2017-09-27T23_22_35_788Z-debug.log
```

```
uname -a
Linux he...es 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
node --version
v8.6.0
```

```
npm --version
5.4.2
```

The same command (`sudo npm i -g sentry-cli-binary`) failed on Mac OS Sierra, but succeeded on Windows 10.

Tried back to `1.13`, all failed with same error.

**Comment by jan-auer** [comment]
Looks like this might be a generally known issue of installing packages globally with the aptitude npm installation. Could you please have a look at [this document](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and see if it fixes your issue?

**Comment by aldanor** [comment]
Same here, and the link mentioned by @jan-auer doesn't help.

**Comment by jan-auer** [comment]
Just noticed that @djereg ran `sudo npm install`. To be clear, npm is not intended to be run with `sudo`. Once the permissions are fixed or the node modules folder has been changed as described in the link above, run `npm install -g sentry-cli-binary` **without sudo** and it will work.

**Comment by aldanor** [comment]
With permissions fixed as described above, it still doesn't work.

**Comment by HazAT** [comment]
Just to provide an alternative to `npm install -g`.
If you want to install `sentry-cli` globally you can install it with this command

`curl -sL https://sentry.io/get-cli/ | bash`

**Comment by jan-auer** [comment]
@aldanor Could you please try with:

```bash
sudo npm install -g sentry-cli-binary --unsafe-perm=true
```
