### ISSUE TITLE
Question - Usage of sentry-cli on MacOS

### ISSUE THREAD

**Issue by arijith96** [getsentry/sentry-cli#1230]
Hi Team,

I would like to know how I could go about using the release executable to upload my debug informations. 
I was able to do so with the Windows versions (.exe) directly on the terminal, but I am not able to do the same with the MacOS downloaded file.

`sentry-cli-Darwin-x86_64  --auth-token XXX upload-dif --include-sources -o ORG -p PROJ path/to/files`

**Comment by kamilogorek** [comment]
Hey, that should work just fine. Assuming you want to upload debug files, not the entire executable, we don't need that for processing. What's the exact problem? And what's the language/environment?

**Comment by arijith96** [comment]
My bad, it was a problem on my end. Closing the issue. Thanks!

**Comment by kamilogorek** [comment]
Good timing haha. I just wanted to post this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1523305/167568628-14c9da1e-c54f-4235-9c48-ac2c3e45d656.png">

Then this should pop up:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/1523305/167568416-d6d3d0c5-97ea-465e-8799-532373c497d4.png">

You need to go to `System Preferences > Security & Privacy > Allow Anyway`

<img width="606" alt="image" src="https://user-images.githubusercontent.com/1523305/167568477-4a325028-a2dc-4eb3-8c4f-3bf11db82a79.png">

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1523305/167568607-49f988c5-9ddb-44b0-b732-58fc6d3de24b.png">

**Comment by arijith96** [comment]
Hahha, good to know. Thanks again, could help someone else :)
