### ISSUE TITLE
Sentry CLI Plugin: Command failed: API request failed

### ISSUE THREAD

**Issue by bonesoul** [getsentry/sentry-cli#1232]
### Environment

SaaS (https://sentry.io/)

### Version

22.4.0

### Steps to Reproduce

> Sentry CLI Plugin: Command failed: /home/runner/work/vizesizgezi.com/vizesizgezi.com/frontend/node_modules/@sentry/cli/sentry-cli releases new xyz
> error: API request failed
>   caused by: [28] Timeout was reached (Failed to connect to sentry.io port 443 after 129444 ms: Operation timed out)

### Expected Result

api request completed

### Actual Result

api request fails

**Comment by kamilogorek** [comment]
This was caused by the outage of the whole https://sentry.io. Nothing to fix from the CLI perspective.

As for "Anyone have a workaround until the API server is up and running again?" - https://stackoverflow.com/questions/17830326/ignoring-specific-errors-in-a-shell-script

**Comment by mbrueggemann** [comment]
For anyone stumbling upon this issue when using any webpack project:

See the errorHandler property here which allows you to set the errors to warning only making your build succeed even though the api is not reachable
https://github.com/getsentry/sentry-webpack-plugin#options

**Comment by jordanmnunez** [comment]
> For anyone stumbling upon this issue when using any webpack project:
> 
> See the errorHandler property here which allows you to set the errors to warning only making your build succeed even though the api is not reachable https://github.com/getsentry/sentry-webpack-plugin#options
Thank you @mbrueggemann !

If you came here looking for a fix with `@sentry/next-js` you will want to use `unstable_sentryWebpackPluginOptions`. Make sure you are using sentry v8.

```ts
export default withSentryConfig(nextConfig, {

  // Do not block on sentry errors
  unstable_sentryWebpackPluginOptions: {
    errorHandler: (err) => {
      console.warn(`Sentry CLI Plugin Error: ${err.message}`);
    },
  },
});
```

Note: this will swallow all sentry errors. My goal is to narrow this err down to a 500 code but there is no documentation on the shape of an HTTP requests error. So I am waiting for this to happen again so I can inspect the error type in logs.
