### ISSUE TITLE
Versions `1.74` & `2.04` sentry-cli does not work

### ISSUE THREAD

**Issue by ugwuanye** [getsentry/sentry-cli#1234]
### Environment

How do you use Sentry?
self-hosted/on-premise 21.3

Which SDK and version?
sentry-cli `1.74` & `2.04`

### Steps to Reproduce
* export the `DSN`
* send message `sentry-cli send-event -m "hello"`

### Expected Result
* View log on sentry gui

What you thought would happen.
* Does not work in versions `1.74.0` & `2.0.4.`
* Works withh version `1.62.0`

### Actual Result
* Does not work in versions `1.74.0` & `2.0.4.`
* Works withh version `1.62.0`

What actually happened. Maybe a screenshot/recording? Maybe some logs?
* return message says its dispatched, however logs does not appear in sentry gui

**Comment by kamilogorek** [comment]
Do you export `DSN` or `SENTRY_DSN`? I just verified it, and I can see a message coming through.
You can also set `SENTRY_LOG_LEVEL=debug` or `--log-level=debug` to see the request itself.
