### ISSUE TITLE
iOS debug information files produced via flutter build ipa not able to be uploaded to Sentry

### ISSUE THREAD

**Issue by btrautmann** [getsentry/sentry-cli#1244]
### Environment

How do you use Sentry? **Sentry SaaS**

Which SDK and version? **Sentry 2.0.4**

### Steps to Reproduce

1. Install `sentry-cli`
2. Run `flutter build ipa --split-debug-info=<symbols-path> --target=<target> --flavor=<flavor> --export-options-plist=<path> --release -v` (note: I included the target/flavor flags as our project has them defined but it's very possible they're not necessary to reproduce.)
3. This produces `<path/to/project>/<symbols-path>/app.ios-arm64.symbols`
4. `cd` to `<path/to/project>/<symbols-path>` and run `sentry-cli upload-dif --auth-token=<auth-token> --org=<org> --project=<project> --log-level=debug app.ios-arm64.symbols`
5. Following output results:
```console
  DEBUG   2022-05-25 09:32:25.385015 -04:00 searching location app.ios-arm64.symbols
  DEBUG   2022-05-25 09:32:25.385193 -04:00 trying to process app.ios-arm64.symbols
  DEBUG   2022-05-25 09:32:25.385496 -04:00 trying to parse dif app.ios-arm64.symbols
  DEBUG   2022-05-25 09:32:25.388097 -04:00 finished location 
> Found 0 debug information files
> No debug information files found
```

### Expected Result

`.symbols` files should be recognized as they are for Android and uploaded.

### Actual Result

It seems `.symbols` files for iOS are not recognized/correctly parsed and uploaded.

### Misc

`flutter doctor -v` output:
```console
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.10.4 at /Users/brandontrautmann/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (9 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

**Comment by kamilogorek** [comment]
Hey @btrautmann, this is currently a know limitation that we note in our docs - https://docs.sentry.io/platforms/flutter/upload-debug/#when-to-upload

Please follow issues listed below for future updates:
https://github.com/dart-lang/sdk/issues/43612
https://github.com/dart-lang/sdk/issues/43274
https://github.com/getsentry/sentry-dart/issues/444
