### ISSUE TITLE
`upload-dif` generates a lot of persistent garbage in %TMP% on Windows

### ISSUE THREAD

**Issue by jorgenpt** [getsentry/sentry-cli#1250]
### Environment

How do you use Sentry? Sentry SaaS

Which SDK and version? Unreal integration, sentry-cli 1.74.3

### Steps to Reproduce

Every build we do

```bat
sentry-cli.exe upload-dif --include-sources --org <org> --project <project> <Project>\Binaries\Win64
sentry-cli.exe upload-dif  --org <org> --project <project> Engine\Binaries\Win64 
```

### Expected Result

`sentry-cli.exe` does not consume a monotonically increasing amount of disk space

### Actual Result

In the week since I configured a custom `%TMP%` env var before we run `sentry-cli.exe`, one of our builders has generated ~25GB of chaff in 5343 files. The files are all named like UUIDv4 files (e.g. `0a35d3da-e4c7-48cb-88c4-54d6cb5be1ae`) without an extension, and range from 700kb to 11mb.

Based on the filenames, I'm guessing these are built using [fs::TempFile](/getsentry/sentry-cli/blob/4ac17f363ab4b8d8140079a7b23767dd0b080555/src/utils/fs.rs#L51), but it does have a `Drop` implementation that seems to try to clean up. 

Our `sentry-cli.exe` invocations do not error out.

**Comment by kamilogorek** [comment]
I tried to reproduce this issue locally on Windows VM, however unfortunately with no luck.
Would you want to try and debug it locally, and see if it will give us some hints?

The only thing we need to update is https://github.com/getsentry/sentry-cli/blob/4ac17f363ab4b8d8140079a7b23767dd0b080555/src/utils/fs.rs#L90-L94

```patch
impl Drop for TempFile {
    fn drop(&mut self) {
-        fs::remove_file(&self.path).ok();
+        if let Err(e) = fs::remove_file(&self.path) {
+            println!("Failed to remove {}: {:?}", &self.path.display(), e)
+        }
    }
}
```

Then recompile and run with `./target/debug/sentry-cli.exe -include-sources --org <org> --project <project> <Project>\Binaries\Win64` or `cargo run upload-dif --include-sources --org <org> --project <project> <Project>\Binaries\Win64`

**Comment by jorgenpt** [comment]
@kamilogorek, seems like it is failing due to access denied on these files -- is something still keeping one open?

```log
11:53:17  C:\jenkins\workspace\ProjectClient_Win64_main>Tools\Binaries\sentry-cli\Win64\sentry-cli.exe upload-dif --include-sources --org <org> --project <project>Project\Saved\StagedBuilds\WindowsClient\project\binaries\win64 
11:53:16  Creating folder: C:\SymTemp
11:53:27  > Found 6 debug information files
11:56:18  > Resolved source code for 1 debug information file
12:00:39  > Prepared debug information files for upload
12:03:46  > Uploaded 3 missing debug information files
12:03:46  > File upload complete:
12:03:46  
12:03:46    PENDING 540e1166-ce99-4673-825f-607750e0244b-1 (ProjectClient.pdb; x86_64 sources)
12:03:46    PENDING 540e1166-ce99-4673-825f-607750e0244b-1 (ProjectClient.pdb; x86_64 debug companion)
12:03:46    PENDING 540e1166-ce99-4673-825f-607750e0244b-1 (ProjectClient.exe; x86_64 executable)
12:03:46  Failed to remove C:\SymTemp\5ca9c2b0-7275-4d4e-ac62-66f467c4da80: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

**Comment by kamilogorek** [comment]
I asked around and there's a chance that windows is not cleaning those files up correctly due to not setting correct destructor flags for temp files.

Could you try to apply this patch to your local repo and try again? https://gist.github.com/kamilogorek/61a8f0870e980c020d5e569bbe3f886b

**Comment by jorgenpt** [comment]
@kamilogorek, reading the docs on [`FILE_FLAG_DELETE_ON_CLOSE`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea), it says "The file is to be deleted immediately after all of its handles are closed, which includes the specified handle and any other open or duplicated handles." -- which doesn't seem like it would work with the way `TempFile` is used? It looks like the code relies on being able to open, write, close, then re-open, and re-read the path on disk? Most of the handles returned by `open` are closed pretty shortly after opening them, and it doesn't look like the code ever keeps two open handles to the same file.

**Comment by jorgenpt** [comment]
Ah, after thinking about this for a little bit, I think I understand what's happening. In some cases, the `TempFile` is being dropped before the `File` that `TempFile::open` returns, since their lifetimes are not linked. On *nix, the OS is happy to `unlink(2)` a file that has open handles and will take care of it. I think one solution here is that we open the file with `FILE_SHARE_DELETE` and then in `Drop` we don't delete the file, but simply open a handle with `FILE_FLAG_DELETE_ON_CLOSE` and then immediately close the handle. That *should* mark the file for delete after the *other* open file handles are closed. (Another solution would be to store the file handle inside the `TempFile` so that the file handle can't be dropped earlier, and just returning a `fs::File` reference whose lifetime is the same as `self`, but I suspect that wouldn't work since I expect many of the APIs used want to consume the `File` rather than borrow it.)

I'm going to try that locally and see, I'll send a pull request if it works out!

**Comment by jorgenpt** [comment]
Turns out it's not that simple -- evidently `FILE_SHARE_DELETE` is used by default by Rust, so this *should* work. Here was my naive test to try to reproduce it:


```rs

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tempfile_goes_away() -> io::Result<()> {
        let tempfile = TempFile::create()?;
        let path = tempfile.path().to_owned();
        assert!(
            path.exists(),
            "{} should exist after creating Tempfile",
            path.display()
        );

        drop(tempfile);
        assert!(!path.exists(), "File didn't get deleted");

        Ok(())
    }

    #[test]
    fn tempfile_goes_away_with_longer_living_handle() -> io::Result<()> {
        let tempfile = TempFile::create()?;
        let path = tempfile.path().to_owned();
        assert!(
            path.exists(),
            "{} should exist after creating Tempfile",
            path.display()
        );

        let handle = tempfile.open()?;
        drop(tempfile);
        assert!(path.exists(), "{} should still be around", path.display());

        drop(handle);
        assert!(!path.exists(), "{} didn't get deleted", path.display());

        Ok(())
    }
}
```

Surprisingly, `tempfile_goes_away_with_longer_living_handle` fails because the file *is* deleted (the second assert triggers, not the third). I also tried using `ByteView::open(&path)`, but it similarly did not make the delete not work.

Any idea what else could be causing this to happen? It sounds like somehow we're using `TempFile::path` to open a handle to the file using some mechanism that *doesn't* use `FILE_SHARE_DELETE`, rather than `TempFile::open` being used.

**Comment by jorgenpt** [comment]
No matter the specific cause, having `drop` use an `open` call that has `.custom_flags(FILE_FLAG_DELETE_ON_CLOSE)` and then immediately dropping that file handle seems to correctly delete the files on Windows. 

I'd love to understand what's causing it to fail **sometimes** -- then I can write a test case to verify the fix, so let me know if you have any thoughts.

Either way I don't expect the new approach to have any novel issues, so I'm running this new `Drop` impl on our build servers and I'll send a pull request in a couple of days if the results are good.

**Comment by jorgenpt** [comment]
@kamilogorek, I didn't have any epiphanies about what could be having an open handle that would prevent it, but the change seems to work robustly in our case, so I've submitted a pull request :)

**Comment by kamilogorek** [comment]
I wonder if there's anything specific to your local system and/or CI that causes this issue? I pulled your tests from https://github.com/getsentry/sentry-cli/pull/1256 and I cannot reproduce it on Win11 locally, the temp is correctly purged after temp files are dropped 🤔

**Comment by kamilogorek** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/1523305/175019436-6ba88cd8-ebab-42bd-9840-a4ff8602dd94.png">

(`tmp` used above is configured to be a `%TMP%`, and compiled binary is what we have in master now, without your PR change)

**Comment by jorgenpt** [comment]
Sorry, I only mentioned this in one of the commits and not in the pull request as a whole:

I wasn't able to isolate the failing case into a specific test case, but in local tests of `upload-dif` this successfully fixes the bug. 

Like I mentioned above, I wasn't able to figure out what specific behavior was causing it to fail to delete the handle with the old method.

**Comment by kamilogorek** [comment]
Got it. Can you try https://github.com/getsentry/sentry-cli/pull/1259 yourself and see if that fixes it as well? I think we can contain this custom flags logic inside the `open` and it should behave the same as your PR.

**Comment by jorgenpt** [comment]
I don't think it does, since putting that logic inside `open` means that at *any* point if we close the last handle to the file it'll get deleted. This means that:

1. The old behavior of `TempFile::create` creating the file no longer works (since it immediately closes the last handle, which deletes it)
2. Calling `TempFile::size()` will also delete the file if you don't have another handle to it
3. Trying to re-`open` the file after the last handle is closed will get you an empty file

I believe that approach would only work if `TempFile::create` kept its handle alive until `drop`.

The tests in my PR do not pass with your change, and this snippet will fail:

```rs
use std::io::Write;

let tempfile = TempFile::create()?;
let path = tempfile.path().to_owned();
tempfile.open()?.write!(file, "Hello world")?;

assert!(
    path.exists(),
    "{} should exist after writing to it",
    path.display()
);
```

**Comment by kamilogorek** [comment]
Makes perfect sense. Will merge PR with your approach then. Thanks for helping debug the issue and providing a working fix.
