### ISSUE TITLE
could not determine a source map reference

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cli#1253]
```
error:
  ~/index.android.bundle (sourcemap at index.android.bundle.map)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/index.android.bundle.)
      - 
```
      
[index.android.bundle.zip](https://github.com/getsentry/sentry-cli/files/8940222/index.android.bundle.zip)
[index.android.bundle.map.zip](https://github.com/getsentry/sentry-cli/files/8940225/index.android.bundle.map.zip)

```
sentry-cli releases files $release upload-sourcemaps --dist $dist --strip-prefix /Users/$myuser/MyProject --bundle android/app/build/generated/assets/react/release/index.android.bundle --bundle-sourcemap android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
```

**Comment by kamilogorek** [comment]
Could repro it locally, and agreed that @marandaneto will ping me when this reappears.

**Comment by fahmitech** [comment]
Hello, I'm facing the similar issues, are there any workaround for this? or even better a fix.
