### ISSUE TITLE
`sentry-cli` Throws Error When Using Yarn PnP

### ISSUE THREAD

**Issue by louisscruz** [getsentry/sentry-cli#1257]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`@sentry/cli` – have reproduced on versions `1.74.4`, `2.1.0`, `2.2.0`. 

### Steps to Reproduce

1. Sentry was functioning perfectly well via the `SentryWebpackPlugin`.
2. We migrated our codebase to make use of [Yarn PnP](https://yarnpkg.com/features/pnp).
3. Webpack builds and the plugin makes use of `@sentry/cli` to perform the release in CI.

### Expected Result

There should not be an error thrown.

### Actual Result

After switching to PnP, we receive the following error after the Webpack build is complete:

```
ERROR in Sentry CLI Plugin: Command failed: /code/.yarn/unplugged/@sentry-cli-npm-1.74.4-2ea938c985/node_modules/@sentry/cli/sentry-cli releases new 010540d3587c7dcce6e6182906b928b87162509c
/code/.yarn/unplugged/@sentry-cli-npm-1.74.4-2ea938c985/node_modules/@sentry/cli/sentry-cli: 1: /code/.yarn/unplugged/@sentry-cli-npm-1.74.4-2ea938c985/node_modules/@sentry/cli/sentry-cli: ���������@�W8�����: not found
/code/.yarn/unplugged/@sentry-cli-npm-1.74.4-2ea938c985/node_modules/@sentry/cli/sentry-cli: 1: /code/.yarn/unplugged/@sentry-cli-npm-1.74.4-2ea938c985/node_modules/@sentry/cli/sentry-cli: Syntax error: "&" unexpected

webpack 5.72.1 compiled with 1 error and 2 warnings in 38318 ms
```

The configuration we have in place for the plugin is exactly the same as it was before the move to PnP.

```ts
new SentryWebpackPlugin({
  include: 'dist/',
  ignore: ['node_modules', 'webpack.config.ts', 'tsclib'],
  configFile: '.sentryclirc',
  urlPrefix: '~/our-prefix/',
  release: sentryRelease,
  silent: true,
  rewrite: false,
  dryRun: false,
  setCommits: {
    auto: true,
  },
});
```

`sentryRelease` is a string of the given commit, in this case `010540d3587c7dcce6e6182906b928b87162509c`.

So far I've tried:

* Making use of an absolute path for the `.sentryclirc`.
* Upgrading to the latest version of `@sentry/cli`.
* Reproducing locally – no luck on this yet. So far we've only seen this in CI.

**Comment by kamilogorek** [comment]
> ���������������@�W8�����������: not found

This would make me think, that maybe there is a problem with fetching incorrect binary. Or maybe binary is fetched as a part of CI, then its cached, and reused but on different env? It's quite hard to tell tbh without being able to reproduce it.
Maybe this is somewhat related? https://github.com/getsentry/sentry-cli/issues/900#issuecomment-774108357

**Comment by kamilogorek** [comment]
Closing the issue as a part of repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
