### ISSUE TITLE
Ignore directories flag

### ISSUE THREAD

**Issue by kamilogorek** [getsentry/sentry-cli#126]
Given `sentry-cli releases files <release> upload-sourcemaps .` I want to be able to specify directories that should be ignored during traversal.

eg.

```
sentry-cli releases files a4mg732d upload-sourcemaps . --ignore-dir 'node_modules,some_other_dir'
```

**Comment by iEchoic** [comment]
+1, right now my output directory has node_modules folder and some other asset folders that it is looking through that make it too slow to use

**Comment by jan-auer** [comment]
Will be available with the next release.

**Comment by tmm1** [comment]
Could this be expanded to upload-dif
