### ISSUE TITLE
explain sourcemaps crash

### ISSUE THREAD

**Issue by tiguchi** [getsentry/sentry-cli#1264]
### Environment

- Sentry SaaS (sentry.io)
- @sentry/nextjs 7.3.0

### Steps to Reproduce

I'm trying to troubleshoot problems with deobfuscating stacktraces. When I run the `sentry-cli sourcemaps explain` command then I get to see the following output and something that looks like a crash message:

```
❯ pnpm sentry-cli sourcemaps explain --org <my org> --project <project slug> <event ID>
✔ Fetched data for event: <...>
✔ Event has release name: 1.0
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
⚠ Exception is already source mapped and resolves to:

thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/commands/sourcemaps/explain.rs:312

   0: backtrace::backtrace::trace
```

I assume that "panicked" bit is not part of the explanation and a sentry-cli crash instead?

### Expected Result

I expect to see what the exception's source map resolves to :smile:

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/commit/255209d4928620e5f512385f49195a7f5660377f
Will release it tomorrow :)
