### ISSUE TITLE
"error: memory map length overflows usize" when uploading DIF files

### ISSUE THREAD

**Issue by highlyunavailable** [getsentry/sentry-cli#1267]
### Environment

How do you use Sentry?
Sentry.io

Which SDK and version?
Unreal SDK, 0.0.1
sentry-cli 2.2.0

### Steps to Reproduce

1. Run `sentry-cli.exe upload-dif --org %SENTRY_ORG% --project %SENTRY_PROJECT% UnrealOutPutDir\WindowsClient`

### Expected Result

The sentry CLI uploads all my debug information files without error, or I can easily exclude content files from the search.

### Actual Result

![image](https://user-images.githubusercontent.com/6266125/176726480-1d47c409-d4ac-4558-a305-4338e262f1da.png)

Apparently the CLI attempts to check a MP4 file to see if it's code and crashes. The mp4 file is only 7.33 MB.

**Comment by kamilogorek** [comment]
Can you verify what build of the cli are you using? As its slightly more complicated on Windows, you can either upload the binary here or use any of the methods described here https://superuser.com/questions/272338/what-is-the-equivalent-to-the-linux-file-command-for-windows

**Comment by highlyunavailable** [comment]
This appears to be fixed in 2.3.0.

However, to answer your question: it's the 64-bit Windows version, `sentry-cli 2.2.0`.

Here's the [full log](https://github.com/getsentry/sentry-cli/files/9030997/Sentry.Crash.txt).
