### ISSUE TITLE
Skipping debug file since it exceeds 2.00GB: myfile.dll.pdb (2.12GB)

### ISSUE THREAD

**Issue by 9989836** [getsentry/sentry-cli#1268]
### Environment
How do you use Sentry?

I use sentry-cli upload a large pdb file .   I need this file. How can I operate it ？ 
eg:  sentry-cli upload-dif -o sentry -p windows-test-debug chrome.dll.pdb --log-level=debug --wait

Which SDK and version?
sentry-cli-Windows-x86_64.exe

### Actual Result

  DEBUG   2022-07-04 10:41:57.998857700 +08:00 searching location chrome.dll.pdb
  DEBUG   2022-07-04 10:41:58.004665 +08:00 trying to process chrome.dll.pdb
  DEBUG   2022-07-04 10:41:58.005583400 +08:00 trying to parse dif chrome.dll.pdb
  WARN    2022-07-04 10:41:58.231910700 +08:00 Skipping debug file since it exceeds 2.00GB: chrome.dll.pdb (2.12GB)
  DEBUG   2022-07-04 10:41:58.232340300 +08:00 skipping chrome.dll.pdb because of size
  DEBUG   2022-07-04 10:41:58.287589100 +08:00 finished location

**Comment by kamilogorek** [comment]
2GB is the hard limit that we have on uploaded debug symbols. There are 2 ways in case you need to upload and use something larger than that:

- use an external symbol server - https://docs.sentry.io/platforms/apple/guides/macos/data-management/debug-files/symbol-servers/ (recommended way)
- host your own instance of Sentry, that allows you to override this setting if your infrastructure allows that

Cheers!

**Comment by 9989836** [comment]
@kamilogorek  

**host your own instance of Sentry, that allows you to override this setting if your infrastructure allows that**

I have run my own instance of Sentry , and  override this setting  “system.maximum-file-size” to 4G 
but ，An error occurred when assemble file 。

**the error log** 
-   DEBUG   2022-07-07 16:42:36.915150 +08:00 > POST /api/0/projects/sentry/windows-test-debug/files/difs/assemble/ HTTP/1.1
-   DEBUG   2022-07-07 16:42:37.094642800 +08:00 body: {"0740c40a153a1bae6061a9227ae9aff19fce2d6f":{"state":"error","detail":"File exceeds maximum size","missingChunks":[]}}
- > File processing complete:
-     ERROR chrome.dll.pdb
-         File exceeds maximum size

**In the sentry source code, files.py** 

def get_max_file_size(organization):
    """Returns the maximum allowed debug file size for this organization."""
    if features.has("organizations:large-debug-files", organization):
        return MAX_FILE_SIZE
    else:
        return options.get("system.maximum-file-size")

How do I override the “"organizations:large-debug-files"  configuration？ 

thank your very much !!!

**Comment by kamilogorek** [comment]
> How do I override the “"organizations:large-debug-files" configuration？

You do that in https://github.com/getsentry/sentry/blob/1eac3ffb9d3d010d993eb4c23349f0764a6ec423/src/sentry/conf/server.py
see: https://github.com/getsentry/sentry/blob/d85aa324df61284c828a4e948e6009c293712734/src/sentry/features/__init__.py#L11-L51

**Comment by bruno-garcia** [comment]
The new limit is 4 GB: 
* https://github.com/getsentry/sentry/issues/86896
