### ISSUE TITLE
On Windows, `--url-prefix` can't be surrounded by quotes.

### ISSUE THREAD

**Issue by haoxi911** [getsentry/sentry-cli#1274]
### Environment

How do you use Sentry? **On Windows with Electron app**
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?) **sentry.io**

Which SDK and version?
**@sentry/electron version 3.0.7**

### Steps to Reproduce

It seems sentry-cli doesn't like the quote in `--url-prefix`, I have the following command:
```
npx sentry-cli releases files __RELEASE__ upload-sourcemaps ./packages/main/dist --url-prefix '~/packages/main/dist'
```

When I look at the uploaded artifacts in sentry.io, I got the following screenshot (please notice the quotes):
![image](https://user-images.githubusercontent.com/12502170/178104425-b622f4bf-55c8-4cee-b139-dfbef0b164e6.png)

### Expected Result

Quotes should be removed from the artifact names

### Actual Result

Sourcemap was not resolved as file paths are not match. Removing quotes from above command resolves the issues on Windows, but causes issue on macOS. The document currently uses quotes, see [here](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#using-sentry-cli).

**Comment by kamilogorek** [comment]
I tried to reproduce this on Windows using `v1` and `v2` with no luck, works just fine in every configuration.

As for "Removing quotes from above command resolves the issues on Windows, but causes issue on macOS.", I assume you are talking about `~` being expanded. This is done by your shell, not the CLI itself. You can try to use double-quotes instead and see of that help for your windows issue, if not, you can also give `--url-prefix=~/something` a go, it won't expand `~` and should work just fine on both envs.

**Comment by haoxi911** [comment]
@kamilogorek Thank you for the hints. I can confirm `--url-prefix=~/something` fixed the issue on both platforms.
