### ISSUE TITLE
difutil bundle-sources can't find sources associated with PDB file

### ISSUE THREAD

**Issue by mitchhentges** [getsentry/sentry-cli#1280]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Rust, `sentry=0.27`

### Steps to Reproduce

1. `cargo build --release`
2. `sentry-cli difutil bundle-sources .\target\release\comms.pdb`

### Expected Result

I thought that I'd get a single "bundle" file with all my source information in it.

### Actual Result

The output was:
```
skipped .\target\release\comms.pdb (no files found)
```
No "bundle" file was created.

-----

FWIW, the "no files found" error _isn't_ because the `comms.pdb` file doesn't exist: if I do `sentry-cli difutil bundle-sources .\non-existant-file.pdb`, I get:
```
C:\dev\comms> sentry-cli difutil bundle-sources .\non-existant-file.pdb
error: The system cannot find the file specified. (os error 2)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by mitchhentges** [comment]
Sure thing:
* [`comms.pdb`](https://www.fuzzlesoft.ca/comms.pdb)
* [`comms.zip`, containing the full source tree, with most generated files pruned](https://www.fuzzlesoft.ca/comms.zip)

**Comment by mitchhentges** [comment]
My mistake: I was using [`split-debuginfo: "packed"`](https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo), and I thought that that was enough to have a full-fledged `.pdb` file.

However, to generate a `.pdb` file with enough information for `sentry-cli difutil bundle-sources`, I need to _also_ have [`debug: true`](https://doc.rust-lang.org/cargo/reference/profiles.html#debug) (in which case the size of the `.exe` remains small, but the information packed into the `.pdb` increases dramatically).

Thanks for the fast response, and sorry for the noise :)

**Comment by kamilogorek** [comment]
No worries, thanks for letting me know!
