### ISSUE TITLE
 No way to pass 'dist' when uploading files

### ISSUE THREAD

**Issue by stephanedupont** [getsentry/sentry-cli#1285]
When using sentry-cli to create a release and upload the source map files, I can't find a way to set the 'dist' parameter.

```
...> .\node_modules\.bin\sentry-cli releases files 0.0.1 --dist 1234 --org=... --project=... upload-sourcemaps ./build/0.0.1/static/js
error: Found argument '--dist' which wasn't expected, or isn't valid in this context
```

How can I pass the 'dist' field when uploading files so they are assigned to the correct 'dist'?

**Comment by kamilogorek** [comment]
If you are using latest major version (v2), use `sourcemaps` command directly, as it fixed flags positioning issue:

```
sentry-cli sourcemaps upload ./build/0.0.1/static/js --release=0.0.1 --dist 1234 --org=... --project=...
```

With the `releases` API (which is there for backwards compact. only, it should be:

```
sentry-cli releases files 0.0.1 --org=... --project=... upload-sourcemaps ./build/0.0.1/static/js --dist 1234
```
