### ISSUE TITLE
Explicit error message in sentry-cli react-native appcenter

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/sentry-cli#1299]
Following this comment https://github.com/getsentry/sentry-react-native/issues/2372#issuecomment-1192714931, it is not visible when the token does not gives enough access right, instead we have:

```
  INFO    2022-07-22 16:18:01.164673529 +00:00 Loaded config from /home/circleci/.sentryclirc
  DEBUG   2022-07-22 16:18:01.165184249 +00:00 sentry-cli version: 1.74.4, platform: "linux", architecture: "x86_64"
  INFO    2022-07-22 16:18:01.165190173 +00:00 sentry-cli was invoked with the following command line: "/home/circleci/pass-culture/node_modules/@sentry/cli/sentry-cli" "react-native" "appcenter" "pass-Culture/passculture-testing-android" "android" "./build/CodePush" "--deployment" "CodePush" "--dist" "10197003-android" "--release-name" "1.197.3-+codepush:v2972"
  INFO    2022-07-22 16:18:01.165959311 +00:00 Issuing a command for Organization: sentry Project: application-native
> Fetching latest AppCenter deployment info
error: Failed to load AppCenter deployment history
  caused by: 
  DEBUG   2022-07-22 16:18:02.180226467 +00:00 skipping update nagger because session is not attended
```

I propose to improve the error message (actually there is just a failure, without error description other than `failed to load appcenter deployment history`) if the token doesn't have enough access right to fullfill the `sentry-cli react-native appcenter` command.

If the API reject the request with `401 UNAUTHORIZED`, it should says a more explicit error message.

I tested with an integration token, then with my personal token, the integration token created by our ops was failing.

**Comment by kamilogorek** [comment]
As I already mentioned in one of the old issues you commented on (https://github.com/getsentry/sentry-cli/issues/881), this behavior already exists - https://github.com/getsentry/sentry-cli/commit/bb570876b61ec72fbe4ed32bfb2a0b32882e789b

It's [sentry-react-native](https://github.com/getsentry/sentry-react-native) that needs to update to v2 of the CLI to get the update.

Cheers

**Comment by kopax-polyconseil** [comment]
Got it

We do not use webpack-plugin/react-native for our react-native app, I don't think webpack is related to react-native, so I didn't got your comment.

Also, the log I posted are with `SENTRY_LOG_LEVEL=debug`.

**Comment by kamilogorek** [comment]
You are using outdated cli version, see

>   DEBUG   2022-07-22 16:18:01.165184249 +00:00 sentry-cli version: 1.74.4, platform: "linux", architecture: "x86_64"

**Comment by kopax-polyconseil** [comment]
Yes, I just checked and I can see that we don't have sentry-cli in our package.json, it is because we also have webpack-plugin that it is in the context, which now make sens with your comment.

Since we already use the latest version of webpack-plugin, I will force the latest version fo sentry-cli in our package.json and try again

**Comment by kopax-polyconseil** [comment]
@kamilogorek do you know if `appcenter codepush deployment history` can work with an integration token ? Because after upgrading the cli, the error says I should be a logged in user, but within the CI, this is not what we want and our integration token doesn't work with `appcenter codepush deployment history`.

**Comment by kamilogorek** [comment]
Appcenter CLI requires a regular token in order to work, and we cannot work around that - https://docs.microsoft.com/en-us/appcenter/cli/#logging-in

Note that instead of logging in manually, you should be configuring your CI to expose `APPCENTER_ACCESS_TOKEN` env variable instead.

**Comment by kopax-polyconseil** [comment]
Hmm, are you sure it is the appcenter cli ? I thought it was the sentry-cli (sentry-cli as a  `sentry-cli react-native appcenter` command), because changing the sentry token was enough for building within the CI. I am double checking on my end. Thanks for those valuable informations

**Comment by kamilogorek** [comment]
If the error is coming from `error: Failed to load AppCenter deployment history` command, then yes, that's the problem with the appcenter cli, see here https://github.com/getsentry/sentry-cli/blob/11211794c24606a0853260533446643b0cdb4dc4/src/utils/appcenter.rs#L102-L135

**Comment by kopax-polyconseil** [comment]
Thanks again for this confirmation.

The weird thing is that in Circle-CI, I am able to run the command manually `appcenter codepush deployment history -a pass-Culture/passculture-staging-ios CodePush` if I `export APPCENTER_ACCESS_TOKEN` when running the `appcenter-cli` command, but when I do it through the `sentry-cli` command that run the `appcenter-cli`, then it will fail.

It seems the subprocess does not pass the `env`, and the only way is to have this env set globally, which is not possible for us as we have many environment (testing/staging/production x 2 (iOS+Android), so many `APPCENTER_ACCESS_TOKEN`.

Is there another way to work around ? Otherwise, it should be considered to be able to pass it to the `sentry-cli`.

**Comment by kopax-polyconseil** [comment]
This is gold. After re-reading the documentation, I can see that the documentation write about it, but that last warning didn't look like it was my error with the old version of @sentry/cli, now it all make sens. Thanks a lot @kamilogorek !!
