### ISSUE TITLE
invalid dsn: missing secret

### ISSUE THREAD

**Issue by itajaja** [getsentry/sentry-cli#13]
Why do I receive that error when trying to do anything? I am setting the API KEY from env var, shouldn't that be enough?

**Comment by dcramer** [comment]
@itajaja the error is pretty clear. Your DSN needs to be set, and needs to contain the secret. I'm not clear why this is entirely (I have little context into the sentry-cli implementation), but this is different than the API key.

**Comment by itajaja** [comment]
I updated sentry to 0.19, and it got fixed. Maybe if you don't have context or insights into sentry-cli, you shouldn't just close issues, but let other people answer?

**Comment by dcramer** [comment]
@itajaja i have context into the error, given that I've written 90% of Sentry :)
