### ISSUE TITLE
Found argument '--org' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by singhayush1403** [getsentry/sentry-cli#1314]
Hi, I am trying to upload my DYSM files to Sentry. I was using the sentry-cli to upload the files using the following command:

`sentry-cli --auth-token $SENTRY_ACCESS_TOKEN upload-dif --org $SENTRY_ORGANIZATION_NAME --project $SENTRY_PROJECT_NAME $dsymPath`

But the upload fails with the following error:
`Found argument '--org' which wasn't expected, or isn't valid in this context`

I followed the documentation and it had the same order of flags as written above

**Comment by kamilogorek** [comment]
Just verified and everything works as expected. There's a chance that you are using old v1 version of the CLI, in this case, please update to the latest one.
