### ISSUE TITLE
Fails on Windows 11 with missing dll VCRUNTIME140.dll

### ISSUE THREAD

**Issue by defunctzombie** [getsentry/sentry-cli#1319]
### Environment

Windows 11 (x64)
Node v18

@sentry/cli 2.5.2

### Steps to Reproduce

Install @sentry/cli 2.5.2 on a fresh install of Windows 11 (x64) with nodejs v18 installed. The package fails to finish installing because it fails to run the cli to get the version and verify the install completed.

If you try to run the CLI manually from explorer you get a missing DLL error.

Both yarn and npm fail in the same way. Probably because the cli.exe file cannot run due to the missing DLL.

### Expected Result

The package installs without error.

**Comment by defunctzombie** [comment]
Worth noting I got here because I use the `@sentry/webpack-plugin` which depends on `@sentry/cli`. I don't actually depend on `@sentry/cli` or use it directly.

The `@sentry/webpack-plugin` still depends on an older version of `@sentry/cli` which also fails with the same DLL error. I was able to separately reproduce the error without `@sentry/webpack-plugin` by trying to install the latest version of `@sentry/cli` on its own.

**Comment by defunctzombie** [comment]
As a workaround I installed Visual c++ Redistribution package 2015-2022. This includes the DLL. I think it would be nice if the DLL shipped without having to install this redistribution package since that's a non-obvious step which required some googling and potentially unclear direction for the end user.

**Comment by kamilogorek** [comment]
Thanks for pointing that out, added appropriate readme note, as it's preferred over statically linking whole MSVC dll.
