### ISSUE TITLE
Allow opt-out from release artifact deduplication via checksum

### ISSUE THREAD

**Issue by joebeachjoebeach** [getsentry/sentry-cli#1322]
When upgrading `@sentry/cli` from `2.3.1` to `2.4.0` (and higher), my organization ran into an issue. Our sourcemap uploads began failing with `429` status codes, indicating that we were exceeding our request quota. After doing some digging, I've determined that the feature to [use checksums to dedupe uploaded release artifacts](https://github.com/getsentry/sentry-cli/pull/1275) is ultimately responsible for this. For every artifact we upload, the CLI is now issuing an extra API request for the deduplication attempt. Our request count is effectively doubled, and we're now exceeding the quota. This means we're unable to adopt any `@sentry/cli` version beyond `2.3.1` at the moment.

Would it be possible to make that deduplication attempt configurable so that it could be opted out of?

**Comment by kamilogorek** [comment]
> Would it be possible to make that deduplication attempt configurable so that it could be opted out of?

Done :)
