### ISSUE TITLE
Add CLI argument to provide `sentry.properties` file

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-cli#1327]
It would useful in some situations to not have to set an environment variable `SENTRY_PROPERTIES`, but instead provide the path as an argument to the CLI directly. This would also improve clarity because the path would then be automatically printed as part of the arguments (such log already exists with an  `info` level).

**Comment by szokeasaurusrex** [comment]
Closing, since this has no upvotes from the external community. If anyone would like to see this implemented, please open a new issue
