### ISSUE TITLE
Support sending full logfiles somehow

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry-cli#1330]
# Problem Statement

We're using `sentry-cli` in the self-hosted installer (which is written in bash). The installer generates a voluminous logfile that we'd luuuuv to send to our Sentry instance, but the only way we're finding to do that right now is to use breadcrumbs which limits to the last 100 lines.

# Solution Brainstorm

Our thought was to add attachment support to `sentry-cli` so we can send the full logfiles as attachments.

**Comment by ethanhs** [comment]
Ah looks like we can use `send-envelope` to achieve what we want.
