### ISSUE TITLE
Allow specifying location of .sentryclirc

### ISSUE THREAD

**Issue by chrisspen** [getsentry/sentry-cli#1331]
The [docs](https://docs.sentry.io/product/cli/configuration/#configuration-file) state that the default path to the sentry configuration file (.sentryclirc) is `~/.sentryclirc`.

Placing this file in the user's home directory, with no way to change it, create problems if you have more than one project using Sentry. Specifically, it prevents you from using Sentry on more than one project, unless you're willing to abandon the configuration file altogether and pass all your project parameters directly on the command line.

Please provide an option to specify this path on the command line, or check for it in the current working directory. This would make Sentry much easier to use in a multi-project environment.

**Comment by kamilogorek** [comment]
> Please provide an option (...) or check for it in the current working directory.

This is how it already works.

> The config file is looked for upwards from the current path and defaults from ~/.sentryclirc are always loaded.

If you place `.sentryclirc` in your projects directory, it will be picked up.
