### ISSUE TITLE
Sending envelope fails with ▶ character in payload

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/sentry-cli#1335]
### Environment

v2.5.2
arm64

### Steps to Reproduce
Attempt to send an envelope with an attachment with ▶ included in payload seems to fail with error logs that don't look right.
```
{"event_id":"12c2d058d58442709aa2eca08bf20986","dsn":"..."}
{"type":"event"}
{"message":"message","level":"error"}
{"type":"attachment","length":2,"content_type":"text/plain","filename":"install_log.txt"}
▶

```
fails

```
{"event_id":"12c2d058d58442709aa2eca08bf20986","dsn":"..."}
{"type":"event"}
{"message":"message","level":"error"}
{"type":"attachment","length":2,"content_type":"text/plain","filename":"install_log.txt"}
a

```
works
### Expected Result

envelope should be dispatched successfully

### Actual Result

`sentry-cli was invoked with the following command line: "sentry-cli" "send-envelope" "/tmp/sentry-envelope-file" "--log-level=debug"
error: missing newline after header or payload`

**Comment by hubertdeng123** [comment]
might have something to do with the size of ▶ in bytes compared to other characters? not sure

**Comment by mbrevda** [comment]
where are you setting the length?

**Comment by kamilogorek** [comment]
In envelopes item headers (line 4 in examples above)

**Comment by mbrevda** [comment]
oh, I see. Thanks!
