### ISSUE TITLE
Frameworks/libswiftos.dylib.cstemp: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by MoNTE48** [getsentry/sentry-cli#1340]
### Environment

macOS Ventura (beta)
Xcode 14.0 and 14.0.1
sentry-cli 2.5.2 and 2.6.0

### Steps to Reproduce

1. Product
2. Archive
3. NOT PROFIT!!

### Expected Result

Well, I expected it to work, but after upgrading to Xcode 14.0 the automatic debug symbols sending broke down.

### Actual Result

```
DEBUG   2022-09-26 17:30:34.227911 +02:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
DEBUG   2022-09-26 17:30:34.228019 +02:00 response status: 200
DEBUG   2022-09-26 17:30:34.228103 +02:00 body: {"url":"https://sentry.io/api/0/organizations/xxx/chunk-upload/","chunkSize":8388608,"chunksPerRequest":64,"maxFileSize":2147483648,"maxRequestSize":33554432,"concurrency":8,"hashAlgorithm":"sha1","compression":["gzip"],"accept":["debug_files","release_files","pdbs","sources","bcsymbolmaps","il2cpp"]}
error: IO error for operation on /Users/admin/Library/Developer/Xcode/DerivedData/xxx-dhskadogyfqtadeyktjbrloflnrc/Build/Intermediates.noindex/ArchiveIntermediates/xxx/BuildProductsPath/Release-iphoneos/xxx/Frameworks/libswiftos.dylib.cstemp: No such file or directory (os error 2)
  caused by: No such file or directory (os error 2)
```

**Comment by kamilogorek** [comment]
It looks like some caches were preserved prior to upgrade, and its just getting confused.
Can you try to clean the build directory and retry?
Its either via regular menu or `Command + Shift + Option + K`

**Comment by MoNTE48** [comment]
@kamilogorek, yeah, that's the first thing I tried and nothing changed...

**Comment by kamilogorek** [comment]
There's still in your project holding reference onto this file. There's not much I can do here tbh.

**Comment by MoNTE48** [comment]
Wouldn't it be better to add a flag to ignore a missing file?
