### ISSUE TITLE
Error when using upload-dsym in an Xcode Archive Post-action

### ISSUE THREAD

**Issue by iccir** [getsentry/sentry-cli#135]
When trying to use `upload-dsym` in my Xcode Archive Post-action script, I kept getting a `Could not open Info.plist file` error.

After some spelunking, it looks like sentry-cli uses the `INFOPLIST_FILE` environment variable (a relative path from `PROJECT_DIR`). This works fine if the current working directory is `PROJECT_DIR` when running sentry-cli.

This is not the case for an Xcode Archive Post-action script, however. I had to manually change to `PROJECT_DIR` before running `sentry-cli`:

```
pushd "${PROJECT_DIR}" > /dev/null

`sentry-cli --auth-token MyToken upload-dsym --org MyOrg --project MyProject "${ARCHIVE_PATH}"`

popd > /dev/null
```

Should sentry-cli do this automatically?

**Comment by mitsuhiko** [comment]
Yeah, we should fix that. Is the intended logic to always join it with `PROJECT_DIR`?

**Comment by iccir** [comment]
Thanks @mitsuhiko! Sorry, I just saw your comment - I believe joining with `PROJECT_DIR` is correct.
