### ISSUE TITLE
upload-dif should take a list of files (or a file with a list of files) to upload

### ISSUE THREAD

**Issue by donallfg** [getsentry/sentry-cli#1353]
Hi!

My build system outputs a manifest of files that it generates, which may not be the same as all of the binary/debug files in the directory, e.g. if I have a folder
```
foo
    a.exe
    a.pdb
    b.exe
````

We may have only built a.exe/a.pdb (and need symbols for them) and not want to upload b.exe

We can manually call `upload-dif -o <...> -p <...> foo/a.exe` and so on, but we started to hit 429 rate limits when doing so. 

Would it be possible to add an option like `--manifest list.txt` which contains the list of files to upload, so that we can get the benefit of whatever rate limiting/control the `upload-dif` command has, while controlling the files that are uploaded!

**Comment by kamilogorek** [comment]
Dif uploading commands accept arbitrary number of paths, so you can already achieve that with simple shell scripting.

For example, given the content of your `list.txt` is new-line separated list of files:

```sh
cat list.txt | paste -sd " " - | xargs sentry-cli upload-dif --log-level debug
```

This will produce:

```sh
  DEBUG   2022-10-11 14:24:46.325523 +02:00 searching location a.exe
  DEBUG   2022-10-11 14:24:46.325619 +02:00 finished location
  DEBUG   2022-10-11 14:24:46.325651 +02:00 searching location a.pdb
  DEBUG   2022-10-11 14:24:46.325678 +02:00 finished location
  DEBUG   2022-10-11 14:24:46.325701 +02:00 searching location b.exe
  DEBUG   2022-10-11 14:24:46.325724 +02:00 finished location
> Found 1 debug information file
```

**Comment by donallfg** [comment]
Oh amazing, thanks for the response! I didn't see it in the docs, but this works just fine for me. Thanks for the very quick resolution.
