### ISSUE TITLE
Keeps getting sentry/cli error when create android release version

### ISSUE THREAD

**Issue by faalihnst** [getsentry/sentry-cli#1359]
### Environment

@sentry/cli: 1.74.5
react-native: 0.62.2

### Steps to Reproduce

Running yarn android:build
or run-android --variant-release

### Expected Result
Create release variant

### Actual Result

Error cannot upload sentry
<img width="1208" alt="Screen Shot 2022-10-14 at 11 01 22" src="https://user-images.githubusercontent.com/32351768/195760651-778cbd68-d610-4c4d-a4ea-e0f7c6ef1e2b.png">

**Comment by kamilogorek** [comment]
Not sure how you run the cli (directly or via some sort of plugin), but adding `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` env should tell us more details what file its trying to look for.
