### ISSUE TITLE
Info.plist variables are not resolved properly

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cli#138]
When I upload dSYMs, I see them as related to $(PRODUCT_NAME) ($(PRODUCT_BUNDLE_IDENTIFIER)) in Sentry. It does manage to get the correct version/build however.

https://github.com/getsentry/fastlane-plugin-sentry/issues/31

**Comment by mitsuhiko** [comment]
I believe this is fixed in master. Going to close this.
