### ISSUE TITLE
[send-event] `server_name` field is absent in 1.71+

### ISSUE THREAD

**Issue by bengentil** [getsentry/sentry-cli#1382]
### Environment

Tried on many versions between 1.52.3 -> 2.8.1,
the first bad version is 1.71.0

I ran also a git bisect and the regression appears in b2e72518d7dfc4330c8b411e80bf59088483e3fc

### Steps to Reproduce

sentry-cli send-event -m test

### Expected Result

The event should have a `server_name` field with the hostname of the machine sending the event.

### Actual Result

No `server_name` field

**Comment by bengentil** [comment]
From what I understand the `sentry` lib got a major rework between 0.18.1 and 0.23.0
and the new cargo declaration didn't include the necessary feature to automatically include the `server_name`

```diff
-sentry = { version = "0.18.0", default-features = false, features = ["with_client_implementation", "with_curl_transport", "with_panic", "with_failure", "with_log", "with_device_info", "with_rust_info", "with_debug_to_log"] }
+sentry = { version = "0.23.0", default-features = false, features = ["curl"] }
```

Knowing the `server_name` field is added by the default contexts integration (https://github.com/getsentry/sentry-rust/blob/master/sentry-contexts/src/integration.rs) I propose to enable the `contexts` feature.

From my tests, I see that adding the `contexts` features adds the following fiels to all events:
```json
"server_name":"ben.localdomain","environment":"production","contexts":{"device":{"type":"device","arch":"x86_64"},"os":{"type":"os","name":"Linux","version":"6.0.5-200.fc36.x86_64","kernel_version":"#1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022"},"rust":{"type":"runtime","name":"rustc","version":"1.63.0","channel":"stable"}}
```

**Comment by kamilogorek** [comment]
Ah, good find! It is indeed a default in `sentry-rust`, but we disable defaults here to use `curl` transport instead. Thanks for the fix.
