### ISSUE TITLE
error: API request failed  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

### ISSUE THREAD

**Issue by koantoni** [getsentry/sentry-cli#1388]
I just created a new Token with all the appropriate rights _(event:admin, event:read, member:read, org:read, project:read, project:releases, team:read, event:write, org:admin, member:admin, alerts:read, org:integrations, team:write, project:write, project:admin, team:admin, alerts:write, member:write, org:write)_ and i still receive the error message:

sentry-cli --auth-token $SENTRY_AUTH_TOKEN upload-dif -org myorg --project $SENTRY_PROJECT_NAME ./symbols_path.zip

error: API request failed
caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

Could you please check and advise? Thanks

**Comment by kamilogorek** [comment]
Is it on-premise instance or Saas? If former, what version?
Can you also provide debug logs of the call? Either `SENTRY_LOG_LEVEL=debug` or `--log-level=debug`

**Comment by koantoni** [comment]
Hi @kamilogorek thanks for your fast response. 
It is Saas, sentry-cli 2.8.1 version
DEBUG   2022-11-07 12:12:11.699771180 +00:00 skipping update nagger because session is not attended

**Comment by kamilogorek** [comment]
@koantoni please take a look at https://github.com/getsentry/sentry-dart-plugin/issues/68#issuecomment-1305257316 and see if that's not the case for you.
