### ISSUE TITLE
macOS: cannot resolve sentry-cdn.com: Unknown host

### ISSUE THREAD

**Issue by muuvmuuv** [getsentry/sentry-cli#1390]
### Environment

macOS with M1

### Steps to Reproduce

1. `ping -c 1 sentry-cdn.com`

### Expected Result

Pingable for download and to access sentry.io/login... It seems some macOS Firewall blocks Sentry. I have Filevault and Firewall disabled so idk where this is coming from. iOS on the same network works, Windows as well.

### Actual Result

```
ping: cannot resolve sentry-cdn.com: Unknown host
```

**Comment by kamilogorek** [comment]
Thanks for the report. In the meantime, you can use github mirror instead:

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```
