### ISSUE TITLE
sourcemap explain not working as expected

### ISSUE THREAD

**Issue by Gmentsik** [getsentry/sentry-cli#1394]
### Environment

sentry: Sentry 22.10.0 ad40640 (self hosted)
sentry-cli: 2.8.1
sentry-npm: 
    "@sentry/integrations": "7.18.0",
    "@sentry/node": "7.18.0",

### Steps to Reproduce

1. Bundle, Minify and build bundle.js, including bundle.js.map with sourcesContent: true
2. Upload with sentry-cli correct release
3. throw error in app
4. sentry-cli sourcemap explain outputs correctly mapped stack-trace
5. stack trace on web-ui still shows bundle.js lines
6. event release version is correct, also issue grouping set to include bundle.js +app

### Expected Result

Sourcemap explain to also fail and explain why the web-ui isn't showing the stack trace

### Actual Result

```
✔ Fetched data for event: 0298582011e34aaea0374b6a96e95186
✔ Event has release name: v3.24.1-a
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✔ Artifact ~/bundle.js found.
✔ Release artifact distribution matched. Event: [none], Artifact: [none]
✔ Successfully fetched ~/bundle.js file metadata from the server.
✔ Found source map location: bundle.js.map
✔ Resolved source map url: ~/bundle.js.map
✔ Artifact ~/bundle.js.map found.
✔ Release artifact distribution matched. Event: [none], Artifact: [none]
✔ Successfully fetched ~/bundle.js.map file from the server.
✔ Sourcemap position resolves to:

        this._teleService.startListening()
          .catch(
            (error) => this._logger.error(new Error('Error listening for tele)));
        moment.locale(locale);
✔ Source Maps should be working fine. Have you tried turning it off and on again?
```

![image](https://user-images.githubusercontent.com/11612884/201330651-85841622-bd1a-4caf-8cf9-504f49c27403.png)

**Comment by kamilogorek** [comment]
Can you show a full page screenshot as well as json payload of the event?

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1523305/201339952-7fa68c1e-edf5-4c4d-b71f-39f38ec71907.png">

An artifact list with the file date would be helpful as well, eg: 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1523305/201339887-c0169b94-0e96-4308-999f-0c6f1495c09e.png">

**Comment by kamilogorek** [comment]
Everything looks fine, so it either has to be a timing issue (thus my questiona bout specific artifacts upload time - you need to hover over to get a tooltip), or some on-premise configuration.

**Comment by Gmentsik** [comment]
Here is with the hover:
(both are the same)
![image](https://user-images.githubusercontent.com/11612884/201351386-f83db471-a67d-406f-947c-c827ccadea32.png)

My on-premise config is just the sentry hosted repo + docker-compose up, there is no extra config I have done, but I will double check.

Is matching done per event basis or per issue basis? So eg. if there is already an issue for that event where sentry couldn't map, will it try again for the next event? I hope so because otherwise fingerprinting would be done on the unmapped bundle.js. 

I have a special fingerprinting function in my app, will this lead sentry to not applying the sourcemaps?

Thanks for taking the time to review my issue.

**Comment by Gmentsik** [comment]
So I ran the upload-sourcemaps command with the --validate flag, which gives me a bunch of warnings:

```
Source Map Upload Report
  Minified Scripts
    ~/bundle.js (sourcemap at bundle.js.map)
  Source Maps
    ~/bundle.js.map
      - warning: missing sourcecode (../../../external/npm/node_modules/rxjs/src/internal/util/isFunction.ts)
      - warning: missing sourcecode (../../../external/npm/node_modules/rxjs/src/internal/config.ts)
      - warning: missing sourcecode (../../../external/npm/node_modules/rxjs/src/internal/util/hostReportError.ts)
      - warning: missing sourcecode (../../../external/npm/node_modules/rxjs/src/internal/Observer.ts)
      - ...
´´´

all these file a from external libs I actually don't need in my sourcemaps, will these warnings prevent sentry to show me the sourcemaps that are there or fail on the first not found sourcecode?

**Comment by kamilogorek** [comment]
> I have a special fingerprinting function in my app, will this lead sentry to not applying the sourcemaps?

No, it should not affect it in any way.

> Is matching done per event basis or per issue basis? 

Per event.

> is there any additional logging I can check anywhere across all the services?

You can observe docker logs. Maybe you are running it without the Relay? See: https://github.com/getsentry/sentry-cli/issues/1370#issuecomment-1309050895 for similar issue

> all these file a from external libs I actually don't need in my sourcemaps, will these warnings prevent sentry to show me the sourcemaps that are there or fail on the first not found sourcecode?

You can safely ignore `node_modules` warnings, they are irrelevant here.
