### ISSUE TITLE
v 2.8.0 release names not getting evaluated when uploading

### ISSUE THREAD

**Issue by ajstokar** [getsentry/sentry-cli#1395]
### Environment

sentry-cli 2.8.0

### Steps to Reproduce

Since upgrading to sentry-cli 2.8.0, the release names are not getting evaluated when we upload new releases.  We have not added any customization to release names and this was previously working correctly on older versions.

### Expected Result

Release names would be evaluated correctly when uploaded during a release build.

### Actual Result

Release names include `$(MARKETING_VERSION)` and `$(PRODUCT_BUNDLE_IDENTIFIER)` as is, without getting evaluated.  Our frontend app is using the following for Sentry.init.

```
Sentry.init({
                    dsn: Config.sentryDsn,
                    environment: Config.environment,
                    dist: DeviceInfo.getBuildNumber(),
                    release: `${DeviceInfo.getBundleId()}-${DeviceInfo.getVersion()}`,
                });
```

However, the release that is created by the automatic sourcemaps upload script (not custom) is not evaluating the environment variables and leaving them as is.  See the below screenshot of the two releases, one is correct without sourcemaps, the other is incorrect but does include sourcemaps.

<img width="1491" alt="Screen Shot 2022-11-11 at 10 30 28 AM" src="https://user-images.githubusercontent.com/1800186/201372860-aa8e11b2-af27-483d-a5d0-138370ea766c.png">

**Comment by kamilogorek** [comment]
Can you run your build with `SENTRY_LOG_LEVEL=debug` or `--log-level=debug`? It will give us more details on the upload and how plist file is read.

**Comment by krystofwoldrich** [comment]
This might be related
- https://github.com/getsentry/sentry-react-native/issues/2581
