### ISSUE TITLE
v1.22.0 broke curl CLI installation on Ubuntu

### ISSUE THREAD

**Issue by dakur** [getsentry/sentry-cli#140]
When I run `curl -sL https://sentry.io/get-cli/ | bash`, it ends up with: `bash: line 4: SENTRY_DOWNLOAD_binary_1.22.0.tgz=https://github.com/getsentry/sentry-cli/releases/download/1.22.0/sentry-cli-binary-1.22.0.tgz: No such file or directory`

If I just try to run following command in my terminal, it writes the same error.
```bash
SENTRY_DOWNLOAD_binary_1.22.0.tgz=https://github.com/getsentry/sentry-cli/releases/download/1.22.0/sentry-cli-binary-1.22.0.tgz
```
When I removed dots from env variable name, it works:
```bash
SENTRY_DOWNLOAD_binary_1_22_0_tgz=https://github.com/getsentry/sentry-cli/releases/download/1.22.0/sentry-cli-binary-1.22.0.tgz
```

**Comment by spoonscen** [comment]
Work around we started using until this is fixed.
```
curl -sL https://sentry.io/get-cli/ | sed -e 's/SENTRY_DOWNLOAD_binary_1.22.0.tgz/SENTRY_DOWNLOAD_binary_1_22_0_tgz/g' | bash
```

**Comment by jan-auer** [comment]
It should work again, but I can only verify in 30 minutes

**Comment by dakur** [comment]
Yes, it works now, thank you very much!

**Comment by jan-auer** [comment]
Actually, we still need to fix this permanently, otherwise it's going to happen again on the next release. I'll keep this issue open in the meanwhile. 

Thanks for reporting and sorry for the inconvenience!

**Comment by dakur** [comment]
Aha, ok. :-)
