### ISSUE TITLE
JS API to access the ambient options the CLI would pick up

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-cli#1413]
It would be very nice in the sentry bundler plugins to have a method for getting all the ambient options that the CLI would pick up in a certain scenario. Like:

- .sentryclirc
- environment variables

We could start off by having a command that outputs all options to stdout and the JS API simply parses that output.

**Comment by kamilogorek** [comment]
You mean `sentry-cli info --config-status-json`? 👀

**Comment by lforst** [comment]
I should RTFM :D
