### ISSUE TITLE
Flag for discarding sentry cache

### ISSUE THREAD

**Issue by Kushagra-ag** [getsentry/sentry-cli#1420]
We have a react SSR setup (react v17.0.2) with typescript. Build tool - Webpack
We are using sentry-cli version 1.74.5 and github actions as our CI tool.

While running 'yarn install' in the docker image, whenever sentry uses cached binary, the following error is frequently observed -
`Error: Unexpected sentry-cli version "", expected "1.74.5"`

It is also noticed that whenever a cached binary is **NOT** used, things go smoothly without any errors.

Hence this issue, to provide a flag to override this cache behaviour

**Comment by Kushagra-ag** [comment]
@kamilogorek Tagging you since you were part of some similar issue - https://github.com/getsentry/sentry-cli/issues/671

**Comment by kamilogorek** [comment]
Can you provide a whole log for this? If it's there, it should be used. The problem most likely is not the fact of using cache, but rather feeding docker image with incorrect architecture: https://github.com/getsentry/sentry-cli/issues/1317

**Comment by Kushagra-ag** [comment]
@kamilogorek 
Here's the installation logs (yarn install on docker) of a failed run - https://pastebin.com/6ek4M4qF
( The error is a bit different in this case than the one provided in the description of this issue )

Note: I even tried to remove the cached binary before yarn install but that too didn't work

**Comment by kamilogorek** [comment]
Can you also provide your dockerfile by any chance?
Does this fail when running the image locally as well?

**Comment by Kushagra-ag** [comment]
@kamilogorek this issue also occurs when the `yarn install` step is run in github CI as well (not inside docker)
I can only share a part of the dockerfile until the command that is causing this error

```
FROM c.rzp.io/proxy_dockerhub/library/node:14-alpine

EXPOSE <port_number>


RUN apk add --no-cache ca-certificates aws-cli && mkdir <directory> && chown -R node:node <directory>

WORKDIR <directory>


COPY --chown=node:node .npmrc package.json yarn.lock ./


RUN --mount=type=secret,id=<github_token> \
    export <github_token> && \
    # Removing the sentry cache because the cached binary used to fail the GH workflows
    rm -rf /root/.npm/sentry-cli && \
    yarn install --frozen-lockfile --prod && yarn cache clean
```

**Comment by kamilogorek** [comment]
There are so many things that can be the cause here that tbh without a concrete reproduction it's just too hard to tell.

Looking at logs, you are using react-native SDK, which depends on the cli itself. I checked https://github.com/getsentry/sentry-react-native/releases and there are very few breaking change for alpha v5 release, but it also includes a v2 of the CLI itself. I winder if you could try to bump the version and see if that would resolve the issue.
v2 of cli is the only one actively maintained so there could be something in the meantime that fixed this issue already.

**Comment by Kushagra-ag** [comment]
You are talking about [5.0.0-alpha.10](https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0-alpha.10) right?
@saurabhdaware @divyanshu013 @snitin315 what do you folks think should we upgrade sentry to v5 since it includes v2 of sentry/cli which is actively maintained

**Comment by Kushagra-ag** [comment]
Will evaluate this approach internally @kamilogorek

**Comment by saurabhdaware** [comment]
So we upgraded the CLI and we saw one instance of the following error so far which seems close to #1317 like you mentioned above. I can check that thread and can try out few things if it is happening often.

```sh
#10 229.6 info sentry-cli Using cached binary: /root/.npm/sentry-cli/cfa322-sentry-cli-Linux-x86-64
#10 229.6 Error: spawn Unknown system error -8
#10 229.6 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I lack context of sentry-cli so this might be silly but I was wondering if we have to exit the process incase of failure in downloading. Can we not treat it as a warning while downloading and fail during execution if something is not present?

I saw there is `SENTRYCLI_SKIP_DOWNLOAD` flag that skips download so basically treating the errors the same way?

**Comment by kamilogorek** [comment]
@saurabhdaware 

```
#10 229.6 Error: spawn Unknown system error -8
```

This one is thrown by the npm when architecture of the binary is not the one that should be used. What most likely happened is that sentry-cli binary was copied over from your host machine to docker container, which is using different arch.

See discussion here https://github.com/getsentry/sentry-cli/issues/1317
