### ISSUE TITLE
Creating bundle sources with difutil not working for xcarchive

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cli#1425]
### Environment

MacBook Pro 2,8 GHz Quad-Core Intel Core i7
macOS 13.0.1 (22A400)

### Steps to Reproduce

1. Download [xcarchive](https://drive.google.com/file/d/1AS6qmBvxBw4x_wOvoj1umnfTHTakLlhk/view?usp=share_link)
2. Unzip
3. `sentry-cli difutil bundle-sources /iOS-Swift\ 03.01.23,\ 08.09.xcarchive`

### Expected Result

`sentry-cli` should create bundle sources as it does with `upload-dif --include-sources`

```bash
sentry-cli upload-dif --org sentry-sdks --project sentry-cocoa --include-sources /iOS-Swift\ 03.01.23,\ 08.09.xcarchive

> Found 119 debug information files
> Resolved source code for 3 debug information files
> Prepared debug information files for upload
...
```

### Actual Result

```bash
error: Unsupported file
```

**Comment by philipphofmann** [comment]
@kamilogorek, it works, though, when you do it with `upload-dif --include-sources`. I don't know how `--include-sources` handles that.

**Comment by kamilogorek** [comment]
It's because `upload-dif` is walking the whole project directory and its processing _all_ debug files.
`bundle-source` is meant to be used for an exact, single debug file.

**Comment by kahest** [comment]
@philipphofmann is this essential for our current initiatives (support source context & drive source context adoption)? If it is, let's prioritize this and make sure we tackle it. cc @brustolin

**Comment by philipphofmann** [comment]
> It's because `upload-dif` is walking the whole project directory and its processing _all_ debug files. `bundle-source` is meant to be used for an exact, single debug file.

Sorry, I didn't follow up on this one. I guess users should use `upload-dif` for source context to work and not `bundle-source`, as pointed out by @kamilogorek in https://github.com/getsentry/sentry-cli/issues/1425#issuecomment-1371027490. After reading the statement of @kamilogorek, I think we should actually close this. Do you agree @kamilogorek?

**Comment by kamilogorek** [comment]
I believe we can do so, as it works as designed.
