### ISSUE TITLE
Source Map - Not considering applicationIdSuffix

### ISSUE THREAD

**Issue by renatoagds** [getsentry/sentry-cli#143]
To detail more the problem, I have 3 differents build types in my gradle (`debug`, `staging` and `release`), and two of them has `applicationIdSuffix` (`.staging` and `.debug`), which change the name of the application for `com.org.product.staging` or `com.org.product.staging`.

When I create a new release using `sentry-cli` and upload the files, following this guide:

https://docs.sentry.io/clients/react-native/codepush/ 

The code that parse my gradle, isn't considering the `applicationIdSuffix`:

https://github.com/getsentry/sentry-cli/blob/bade2bc24496f11375faf25280e753e25194ca16/src/utils/releases.rs#L24-L55

So, in my code, when I set the sentry version from code push, it is different from the version in sentry.

**Comment by mitsuhiko** [comment]
Hi. Sadly for codepush we cannot know the correct bundle id in those cases. The problem is that we don't know if you push a release for debug or release. In this case you will need to explicitly provide the `--bundle-id` on the command line:

```
sentry-cli react-native codepush --bundle-id com.org.product.staging YourApp ios ./build
```

**Comment by renatoagds** [comment]
@mitsuhiko thanks! I'll use `bundle-id` flag for that.
