### ISSUE TITLE
Upload DSYMS in background notification annoying

### ISSUE THREAD

**Issue by stherold** [getsentry/sentry-cli#1437]
Is there a way to disable these notifications?

**Comment by kamilogorek** [comment]
Sure there is. It's right there in the docs :) - https://docs.sentry.io/product/cli/configuration/

```
(ui.show_notifications):
If this is set to false some operating system notifications are disabled. This currently primarily affects xcode builds which will not show notifications for background builds.
```

**Comment by stherold** [comment]
And one last question. How do I specify that for sentry CLI? I tried as custom header but that did not work and there is no direct option in the help of the CLI tool. Also exporting it as environment variable did not do the trick... Can you please provide a small example call to sentry-cli?

**Comment by kamilogorek** [comment]
Create `.sentryclirc` file in the root of your project with the content:

```
[ui]
show_notifications=false
```

There is no direct flag that control this behavior.
