### ISSUE TITLE
Give better context to IO errors

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-cli#144]
Currently IO errors (such as the one in #142) are not well reported to the user. We never annotate the filename we attempt to reference. We should properly contextualize all IO access so users are less likely to be presented with useless error messages.

**Comment by marcomorain** [comment]
@mitsuhiko I guess if this line here would add the path and some information about `SENTRY_PROPERTIES` it would be easier to see what's up. 

https://github.com/getsentry/sentry-cli/blob/190679014e59f2f20e4e34a9e781ff5c87a6316b/src/config.rs#L347

Maybe something like:

> Error loading file at '[path]' specified in `SENTRY_PROPERTIES` environment variable: [underlying error]
