### ISSUE TITLE
thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:87

### ISSUE THREAD

**Issue by meotimdihia** [getsentry/sentry-cli#1446]
### Environment
Vercel or Github Actions Ubuntu 20.02, yarn, node 16

### Steps to Reproduce
I am trying to upgrade to @sentry/nextjs 7.34
Run Install `yarn` is failed on GitHub Actions or Vercel. This is the error: 
```
➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.74.6/sentry-cli-Linux-x86_64
  ➤ YN0000: │ sharp@npm:0.31.3 STDOUT sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-linux-x64.tar.br
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR info Checksum validation passed. 
  ➤ YN0000: │ sharp@npm:0.31.3 STDOUT sharp: Integrity check passed for linux-x64
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR Error: Command failed: /home/runner/work/comick/comick/node_modules/@sentry/cli/sentry-cli --version
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR error: 7:89 expecting "[Some('='), Some(':')]" but found EOF.
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:87
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR 
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR    0: backtrace::backtrace::trace
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR 
  ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR 
```
### Actual Result
![image](https://user-images.githubusercontent.com/300961/215556978-fdcb90ab-610d-4986-ac01-cf1e2e7c36c4.png)

**Comment by kamilogorek** [comment]
> ➤ YN0000: │ @sentry/cli@npm:1.74.6 STDERR error: 7:89 expecting "[Some('='), Some(':')]" but found EOF.

It looks like your config file is incorrect. Be it `.sentryclirc` or `sentry.properties`. Or you pass it explicitly during `sentry-cli` call, but file is empty.

**Comment by meotimdihia** [comment]
@kamilogorek thanks, I have found the problem. 
Like as you said, my `.sentryclirc` is incorrect.
