### ISSUE TITLE
Could not retrieve event even though it is in dash

### ISSUE THREAD

**Issue by jbaxleyiii** [getsentry/sentry-cli#1453]
### Environment

Running `sentry-cli 2.12.0`. We are using hosted sentry but do have SSO turned on in case that has an impact

### Steps to Reproduce

1. `sentry-cli login` to get a token
2. find an event in the dash
3. `sentry sourcemaps explain <event> --org <org> --project <project> --auth-token <token from step 1>

### Expected Result

It would return the issue with sourcemaps

### Actual Result

```
✖ Could not retrieve event 8fd6f57561d84d2c9ab3a1fdd1e30eea
ℹ Make sure that event ID you used is valid.
```

Trace output
```
  DEBUG   2023-02-01 17:48:56.562452 -05:00 request GET https://sentry.io/api/0/projects/<org>/<projgect>/events/<event_id>/json/
  DEBUG   2023-02-01 17:48:56.562458 -05:00 using token authentication
  DEBUG   2023-02-01 17:48:56.562464 -05:00 retry number 0, max retries: 0
  DEBUG   2023-02-01 17:48:57.071076 -05:00 > GET /api/0/projects/<org>/<projgect>/events/<event_id>/json/ HTTP/1.1
  DEBUG   2023-02-01 17:48:57.071150 -05:00 > Host: sentry.io
  DEBUG   2023-02-01 17:48:57.071157 -05:00 > Accept: */*
  DEBUG   2023-02-01 17:48:57.071163 -05:00 > Connection: TE
  DEBUG   2023-02-01 17:48:57.071168 -05:00 > TE: gzip
  DEBUG   2023-02-01 17:48:57.071174 -05:00 > User-Agent: sentry-cli/2.12.0
  DEBUG   2023-02-01 17:48:57.071794 -05:00 > Authorization: Bearer d6f7dbf7***
  DEBUG   2023-02-01 17:48:57.183613 -05:00 < HTTP/1.1 404 Not Found
```

**Comment by kamilogorek** [comment]
Just to double-check, you are using event ID, not an issue ID?

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1523305/216266677-9bb26aaa-77de-4b6f-b934-7b719e9088f3.png">

If so, can you provide a shareable link to the event itself? Its in the upper-right corner:
<img width="113" alt="image" src="https://user-images.githubusercontent.com/1523305/216266847-fb6c64e5-7630-4ada-ab21-2927ac49347e.png">

If not, as some people prefer not to do that publicly, feel free to send me an email with the details to kamil@sentry.io
