### ISSUE TITLE
Better error message when `react-native-xcode.sh` not found.

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-cli#1454]
This is an error message that users will get if `react-native-xcode.sh` is not found. The reason might be a wrong patch by `wizard` or an incompatible `react-native` version (the script was renamed/removed etc.).

```bash
DEBUG   2023-01-27 13:09:33.314330 -08:00 sentry-cli version: 1.74.4, platform: "darwin", architecture: "arm64"
INFO    2023-01-27 13:09:33.315723 -08:00 sentry-cli was invoked with the following command line: "/Users/aaron.craig/dev/FashionNovaApp/node_modules/@sentry/cli/sentry-cli" "react-native" "xcode" "REACT_NATIVE_XCODE=../node_modules/react-native/scripts/react-native-xcode.sh"
error: No such file or directory (os error 2)
```

Expected message content would be what happened and path/s `cli` tried.
```
Script `react-native-xcode.sh` not found.
Expected path "REACT_NATIVE_XCODE=../node_modules/react-native/scripts/react-native-xcode.sh"
```

Related issues:
- https://github.com/getsentry/sentry-react-native/issues/2722
- https://github.com/getsentry/sentry-wizard/issues/232

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-cli/blob/55eddec97249e492f1796d186d45e0dded7712fe/src/commands/react_native/xcode.rs#L141
https://github.com/getsentry/sentry-cli/blob/55eddec97249e492f1796d186d45e0dded7712fe/src/commands/react_native/xcode.rs#L219

Here are 2 places this is called. You can do `.spawn().map_err(|err| err.context(anyhow::format_err!("something something explained")))?` to change that. PRs welcome :)
