### ISSUE TITLE
error: An organization slug is required (provide with --org)

### ISSUE THREAD

**Issue by Seol827** [getsentry/sentry-cli#1459]
### Environment
@sentry/nextjs : 7.27.0

when I tried build the project (for ci/cd deploy), I found that error as follow.
`Sentry CLI Plugin: Command failed: /usr/app/node_modules/@sentry/cli/sentry-cli.exe releases new [~]
error: An organization slug is required (provide with --org)`

How can I fix it?

**Comment by Seol827** [comment]
I've edited sentry.server.config.ts && sentry.client.config.ts as follow.
`Sentry.init({ 
  release: 'my-project-name@2.3.12',
})`
But the error is same.
reply, please.

**Comment by kamilogorek** [comment]
Here are the docs on how to correctly setup cli config - https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-sentry-cli

**Comment by Seol827** [comment]
@kamilogorek I add a more issue. check that please!
#1461
