### ISSUE TITLE
caused by: sentry reported an error: Invalid token (http status: 401)

### ISSUE THREAD

**Issue by Seol827** [getsentry/sentry-cli#1461]
### Environment
@sentry/nextjs : 7.27.0
@sentry/cli : 2.12.0

#### on-premise
---
First of all, Thanks for your reply yesterday.
I checked the docs and applied @sentry/cli (npm install), sentry.properties, .sentryclirc.
But I found some errors.
Please check my content is correct or not.

##### sentry.properties
```
defaults.url=https://~    (how can I confirm the url? I just applied a domain url of project.)
defaults.org=~               (I applied the Organization Slug via Organization Settings page.)
defaults.project=~         (the project name)
```

##### .sentryclirc
```
[auth]
token=~ 
```
I applied the token via Auth Tokens page. I created the token as follow.
![capt](https://user-images.githubusercontent.com/83569413/217125373-6c52e176-70e2-47af-8ef1-f5b8ee30a3a4.png)

![capt2](https://user-images.githubusercontent.com/83569413/217128238-959347b6-e8e3-4bcf-9047-ad7970bb8347.png)

I got the errors such as "API request failed, caused by: sentry reported an error: Invalid token (http status: 401)" (when I applied defaults.url=https://sentry.io/")

or "not a JSON response". (when I applied defaults.url as a domain url my project)

please check as soon as possible.
Thanks.

**Comment by kamilogorek** [comment]
Remove `sentry.properties` entirely and put everything into one config file, as we read just one of them.

Inside `.sentryclirc`

```
[defaults]
org=<org-slug>
project=<project-slug>

[auth]
token=<your-token-from-screen>
```

If that wont work, do `export SENTRY_LOG_LEVEL=debug` and run the command again, providing the logs here (remove all sensitive data).

**Comment by Seol827** [comment]
@kamilogorek I can't understand do `export SENTRY_LOG_LEVEL=debug`. how can I attach the command? in the file? or just command in the Visual Studio Code?

**Comment by kamilogorek** [comment]
There's no such project as `wev-charger-web`, please verify your config and if problem persist, ask on our discord channel, as github is not our support channel. Thanks!
