### ISSUE TITLE
macOS build artifacts missing extension

### ISSUE THREAD

**Issue by TomasHubelbauer** [getsentry/sentry-cli#1462]
### Environment

macOS Ventura 13.1

### Steps to Reproduce

1. Go to https://github.com/getsentry/sentry-cli/releases/latest
2. Download `sentry-cli-Darwin-arm64`
3. Run the downloaded binary

### Expected Result

Either it is an `.app` bundle and I can just run it or it is a `.dmg` image and I can mount it and move the app to Applications and run it or it is a `.pkg` and I can install via the installer application and then run it. I am sure there are more way binaries are distributed on macOS but these are the ones I am familiar with.

### Actual Result

I double-click the downloaded binary to run it and it opens in Text Edit. Rename to `.app` to no avail.

### Additional Context

The documentation mentions the downloaded file needs to be renamed to `sentry-cli` and presumably added to `PATH`? I find the docs aren't too clear on that.
https://docs.sentry.io/product/cli/installation/#manual-download

**Comment by kamilogorek** [comment]
This is a binary executable, not an Apple Disk Image or Application Bundle. You run it using your shell, not the OS UI.
If you have trouble installing it manually, please use one of the available automatic processes instead.

**Comment by TomasHubelbauer** [comment]
I ended up using Homebrew but it would be great if the documentation on the Manual Download method included more instructions on how to use that.
