### ISSUE TITLE
CLI Command to inject `debug_id` for source maps

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-cli#1467]
We want to make source map lookup easier for our users and in the Sentry backend. To accomplish this we want to send debug IDs that point to a particular uploaded source map along with every frame of a stack trace.

The high-level idea is to inject some code into every bundle with `sentry-cli` that sets a key on a global object mapping from a stack trace to a `debug_id`. The corresponding source map of that bundle also needs to be given a `debug_id` field holding the same value. I won't go into specifics about how the code snippet works and how the SDK picks it up because it is not relevant to this task but some more information can be found [here](https://www.notion.so/sentry/Debug-IDs-for-Source-Maps-Brainstorming-66601f1cd5f646a399f9b46fa0dfa3a5) and here: https://github.com/getsentry/sentry-javascript/pull/7068

### What needs to be done in `sentry-cli`?

Basically, we just need to port [this script](https://github.com/getsentry/sentry-sourcemap-debug-id-cli/blob/main/index.js) from JS to `sentry-cli` with a separate command (suggestion: `sentry-cli sourcemaps inject [paths...]`).

High-level overview of what that script does:

- Gets a list of all files that matches `paths` (recursively)
- Filters that list for `.js` files
- Reads each JS file
- Looks for a `//# sentryDebugId =` comment
- If found, ignores a file and emit a warning, that the file was already processed before
- Looks for a `//# sourceMappingURL=` comment
- If it is not found, ignores the file and emit a warning, that it is missing a source mapping url
- Look for the source map file behind the `sourceMappingURL` comment
- If it is not found, ignores the file and emit a warning that the corresponding source map couldn't be found
- Generates a random UUID
- Appends the [code snippet](https://github.com/getsentry/sentry-sourcemap-debug-id-cli/blob/860ecb36c25dfe72bb38c86588c6c999cd9aaf2c/index.js#LL19) mentioned above to the JS file and substitute `__SENTRY_DEBUG_ID__` with the generated UUID
- Appends a comment "`\n//# sentryDebugId=__SENTRY_DEBUG_ID__`" to the JS file and substitute `__SENTRY_DEBUG_ID__` with the generated UUID
- Reads and parses the corresponding source map.
- Adds a field `debugId` to the source map JSON and writes it back to disk.
- Done.

**Comment by loewenheim** [comment]
Do you have a set of JS files and sourcemaps I could use to test this?

**Comment by kamilogorek** [comment]
If anything, I'd recommend to use `x_debug_id` or similar inside the sourcemap itself, as this is the format that Facebook and Bloomberg already use to extend it.

**Comment by lforst** [comment]
> If anything, I'd recommend to use `x_debug_id` or similar inside the sourcemap itself, as this is the format that Facebook and Bloomberg already use to extend it.

Good point. We should probably scope it to Sentry somehow. Maybe `sentryDebugId`?

**Comment by lforst** [comment]
The reason why I went with camel case originally was because the other fields inside source maps are camel case but if there is precedent of third parties doing snake case let's do that! I don't have strong opinions here.

**Comment by lforst** [comment]
Resoved by https://github.com/getsentry/sentry-cli/pull/1469
