### ISSUE TITLE
Hard limit on debug file size of 2GB 

### ISSUE THREAD

**Issue by ericriff** [getsentry/sentry-cli#1470]
Hi all, 

Recently our sentry integration broke down because one of our libraries grew in size past 2GB mark. When we upload the debug symbols to sentry (the whole .so file) we get
```
  WARN    2023-02-13 18:07:25.991766272 +00:00 Skipping debug file since it exceeds 2.00GB: libfoo.so (2.19GB)
```

Is this limit somehow configurable? I looked into the docs and didn't find a way of doing so.
If not, what are my options? Should we host our own symbol server? We have a paid license. 

Thanks, Eric.

**Comment by kamilogorek** [comment]
Hey, 2GB is the hard limit that we have on uploaded debug symbols. There are 2 ways in case you need to upload and use something larger than that:

- use an external symbol server - https://docs.sentry.io/platforms/apple/guides/macos/data-management/debug-files/symbol-servers/ (recommended way)
- host your own instance of Sentry, which allows you to override this setting if your infrastructure allows that

**Comment by ericriff** [comment]
Thanks for the quick response.

I was looking into the external symbols server, I'm wondering if there is a guide on how to set one up. This is very new to me.

**Comment by ericriff** [comment]
I also tried spiting the .so in two, one file with the debug info and one stripped. By doing that I get 2 files below the 2GB mark. Is that a valid option?
```
$ objcopy --only-keep-debug --compress-debug-sections=zlib libfoo.so libfoo.so.debug
$ strip --strip-debug --strip-unneeded libfoo.so
```
It looks like sentry still has everything it would need `> symtab, debug, unwind`
```
$ sentry-cli difutil check libfoo.so.debug 
Debug Info File Check
  Type: elf debug companion
  Contained debug identifiers:
    > Debug ID: cf961cf4-dfc0-a90b-e1fb-c61f1252ac12
      Code ID:  f41c96cfc0df0ba9e1fbc61f1252ac12c5dbb463
      Arch:     x86_64
  Contained debug information:
    > symtab, debug
  Usable: yes

$ sentry-cli difutil check libfoo.so      
Debug Info File Check
  Type: elf library
  Contained debug identifiers:
    > Debug ID: cf961cf4-dfc0-a90b-e1fb-c61f1252ac12
      Code ID:  f41c96cfc0df0ba9e1fbc61f1252ac12c5dbb463
      Arch:     x86_64
  Contained debug information:
    > symtab, unwind
  Usable: yes

```

**Comment by kamilogorek** [comment]
>  Is that a valid option?

Yes, that should work as well.

> I was looking into the external symbols server, I'm wondering if there is a guide on how to set one up. This is very new to me.

https://docs.sentry.io/platforms/android/data-management/debug-files/symbol-servers/#custom-repositories

**Comment by Edstub207** [comment]
Hello @kamilogorek I appreciate this is a stale issue, is there any way to override the Sentry 2GB CLI Limit on the Sentry as a service version? Having numerous issues with the symbol server connection to Sentry (Via GCP), the cli works, when we're below 2GB, but we're failing to compress enough to be below 2GB, is there any potential of the limit being increased to 3GB?

For reference, this is on a Unreal Engine 5 project, in which cases most PDB's for the Development configuration come in at around 2.5GB.

**Comment by loewenheim** [comment]
@kamilogorek isn't with Sentry anymore, but I've raised the question.

**Comment by loewenheim** [comment]
@Edstub207 Raising the limit is unfortunately not in the cards. Maybe we can assist you with the symbol server problems you're having?

**Comment by Edstub207** [comment]
> @Edstub207 Raising the limit is unfortunately not in the cards. Maybe we can assist you with the symbol server problems you're having?

@loewenheim  Thanks for confirming - We've been having discussions with the Sentry Team, however, sadly, we haven't had many updates or solutions for our problems so far. 

I believe today we found a potential fix for the large PDB size, it's not ideal, but based on the above we'll have to do it. 

Thanks for the quick assistance though :)

**Comment by loewenheim** [comment]
My pleasure!
