### ISSUE TITLE
React Native monorepo (lerna) - Source code was not found

### ISSUE THREAD

**Issue by madstechpros** [getsentry/sentry-cli#1473]
### Environment
"react": "16.13.1"
"react-native": "0.64.2"
"@sentry/react-native": "4.14.0"

sentry-cli 2.11.0
### Steps to Reproduce
I have an app in Production with a release and a dist. When an issue is captured it looks like this:

![sentry-issue-view](https://user-images.githubusercontent.com/83356122/218749143-c708b343-94c5-473c-beeb-ed783279cef9.png)

It says that source code was not found and that sentry is unable to minify code due to lack of source maps. However, looking at at the release (2.5.1) artifacts
![image](https://user-images.githubusercontent.com/83356122/218749519-442cce8b-31d1-412c-8d6b-997f90ccbaab.png)

I see the artifacts and they have the correct release version as well as dist (82)

If I use the cli and run the command "sentry-cli sourcemaps explain <event id>"
I do see the function which fails, but it's a javascript function (not made by us) and no stack trace.

I use the following commands to upload bundles
```
lerna run android:sentry --scope @linework/reactnative --stream
sentry-cli releases -p mobile -o linework-inc new $SENTRY_RELEASE
sentry-cli releases -p <projectName> -o <orgName> files $SENTRY_RELEASE upload-sourcemaps --dist $SENTRY_DIST ./app/reactnative/index.android.bundle ./app/reactnative/index.android.bundle.map --url-prefix "~"
```

The command "lerna run android:sentry --scope @linework/reactnative --stream" triggers the command below in "app/reactnative/package.json"

```
react-native bundle --dev false --platform android --entry-file app/reactnative/index.js --reset-cache --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map
```

The project structure
root/
      | -> app/
          | -> reactnative/ <- RN project which has "flib" and "slib" as dependencies
          | -> flib/ <- typescript project with logic
          | -> slib/ <- typescript project wit logic

### Expected Result

That I should be able to see stack trace (un-minified code) and that sentry can find source code

### Actual Result

Can't see un-minified code and sentry does not find source code.

### Notes
I have tried adding "app:///" as prefix, but it does not work
I have tried not adding a prefix, and it does not work

**Comment by kamilogorek** [comment]
Is this a self-hosted instance, or Sentry.io? Not sure about the timing here, but the event says its 1 day old, while artifacts were uploaded few minutes ago. Maybe this is the case? We do not do reprocessing for JS.

**Comment by madstechpros** [comment]
We are using sentry.io and yes the artifacts were uploaded after the code was pushed to the play store. However, the code is the same. And maybe it is the case, I'm not sure. I will keep an eye on it and see if new events have the same issue

**Comment by madstechpros** [comment]
@kamilogorek your assumption was correct. New issues are not giving the same error and I have stack trace
