### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by Gao-Hongxiang** [getsentry/sentry-cli#1479]
### Steps to Reproduce

```js
npm install @sentry/cli -g
```

### Expected Result

```js
Error message: request to https://downloads.sentry-cdn.com/sentry-cli/2.12.0/sentry-cli-Windows-x86_64.exe failed, reason: read ECONNRESET
```

**Comment by kamilogorek** [comment]
Should be fixed now. Sorry for the inconvenience.

**Comment by csonchen** [comment]
https://github.com/getsentry/sentry-cli/releases/download/

**Comment by kamilogorek** [comment]
Which is correct, as it's CDN base URL. It'll end up as `https://github.com/getsentry/sentry-cli/releases/download/2.12.0/sentry-cli-Windows-x86_64.exe` when used within the script.
