### ISSUE TITLE
Docker image latest has been set to sentry-cli v1

### ISSUE THREAD

**Issue by ronan-fitzgerald-zoe** [getsentry/sentry-cli#1481]
### Environment

This isn't affecting an environment - although one that has cached an old version of the image would remain unaffected until TTLs expire.

### Steps to Reproduce

1. Run `docker run -it getsentry/sentry-cli:latest sentry-cli --version`

### Expected Result

A v2 release, e.g 2.12.0

### Actual Result

Version 1.75.0.

From https://hub.docker.com/r/getsentry/sentry-cli/tags you get:

![image](https://user-images.githubusercontent.com/87645327/219355412-cd17aa72-a614-4a82-bc23-9773907fa46a.png)

Here's what I'm seeing on the command line:

```shell
$ docker run -it getsentry/sentry-cli:2 sentry-cli --version
sentry-cli 2.12.0

$ docker run -it getsentry/sentry-cli:1 sentry-cli --version
sentry-cli 1.75.0

$ docker run -it getsentry/sentry-cli:latest sentry-cli --version
sentry-cli 1.75.0
```

**Comment by jma-amboss** [comment]
I am having same issue

**Comment by kamilogorek** [comment]
Working on it. Should be done within hour or so, sorry for the inconvinience.

**Comment by kamilogorek** [comment]
Fixed :)
