### ISSUE TITLE
Wrapper for common CLI scripts

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-cli#1483]
### Background
We see customers often running the same script, as noted in this [blog post](https://dev.to/whatever/uploading-source-maps-for-angular-1jg2)

```version=$(grep -Eo '[0-9]\.[0-9]\.[0-9]+' app.version.ts)

sentry-cli releases new -p test-sentry-angular "$version"
sentry-cli releases set-commits --auto "$version"
sentry-cli releases files "$version" upload docs/ --ext js 
sentry-cli releases files "$version" upload-sourcemaps docs/ --ext map
sentry-cli releases new "$version" --finalize

# Remove all .js.map files
for file in $(find ./docs -type f -name '*.js.map');
do
    echo "Removing $file";
    rm $file;
done```

### Proposal
Might it make sense to have a kind of wrapper around this where they just need to provide the correct config and argument and there is a one liner to take care of the rest?

**Comment by kamilogorek** [comment]
It's not obvious what they actually want to achieve with those commands, as its not explained in the blogpost.

The only command one need to run in order for sourcemaps to work is `sentry-cli sourcemaps upload docs/`, everything else is redundant.

**Comment by lforst** [comment]
Don't you need to create a release before uploading?

**Comment by Lms24** [comment]
Then I think we should explain this better in the docs because I was under the impression that I need to create a release as well.

**Comment by kamilogorek** [comment]
> Don't you need to create a release before uploading?

Nope. https://github.com/getsentry/sentry-cli/blob/1aa01d35b5362ffa8118450b870ede9ab3d063d5/src/commands/sourcemaps/upload.rs#L325-L342

**Comment by lforst** [comment]
Thanks @kamilogorek for clarifying! :)
