### ISSUE TITLE
Upload Sourcemaps not working for multiple project in same release

### ISSUE THREAD

**Issue by cre8** [getsentry/sentry-cli#1492]
### Environment

```
"@sentry/cli": "^2.7.0",
```

### Steps to Reproduce

I have an NX project where I got two angular applications and two nestjs applications. Each of them has a task like:
```
    "sentry-release": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "npm run sentry-cli -- releases new $(npm --silent run sentry-cli releases propose-version) -o trustcerts -p trust-signer-frontend --auth-token={args.SENTRY_AUTH_TOKEN}",
          "npm run sentry-cli -- releases set-commits --auto $(npm --silent run sentry-cli releases propose-version) -o trustcerts -p trust-signer-frontend --auth-token={args.SENTRY_AUTH_TOKEN}",
          "npm run sentry-cli -- releases files $(npm --silent run sentry-cli releases propose-version) upload-sourcemaps dist/apps/trust-signer -o trustcerts -p trust-signer-frontend --auth-token={args.SENTRY_AUTH_TOKEN}",
          "npm run sentry-cli -- releases finalize $(npm --silent run sentry-cli releases propose-version) -o trustcerts -p trust-signer-frontend --auth-token={args.SENTRY_AUTH_TOKEN}"
        ],
        "parallel": false
      }
    },
```
with a different project and sourmap path. In the ci job I see that each job runs successfully like
```
> sentry-cli releases files 8bc8d35a2e3dba03426b19dc0aa04db34304beda upload-sourcemaps dist/apps/trust-signer-backend -o trustcerts -p trust-singer-backend --auth-token=***

> Found 2 release files
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: trustcerts
> Project: trust-singer-backend
> Release: 8bc8d35a2e3dba03426b19dc0aa04db34304beda
> Dist: None

Source Map Upload Report
  Scripts
    ~/main.js
  Source Maps
    ~/main.js.map

> trustsuite@0.0.0 sentry-cli
> sentry-cli releases finalize 8bc8d35a2e3dba03426b19dc0aa04db34304beda -o trustcerts -p trust-singer-backend --auth-token=***

Finalized release 8bc8d35a2e3dba03426b19dc0aa04db34304beda
```

### Expected Result

When I upload the source files with a reference to a project I assume that each project has its dedicated source maps in one release (so source maps from two projects are not mixed together)

### Actual Result

But in the end I get all files together in one:
![image](https://user-images.githubusercontent.com/4020915/221367632-7a083d5f-e3e9-45b4-9f9f-46d3d934c32a.png)

So all souremaps are merged or overwritten in one folder. And it is not possible for sentry to get the correct map files.

As a workaround I would add a prefix to each release like the project, so I get a unique release identifier for each job. But this will increase the amount of releases and has no easy mapping between the commit hash and the release id.

**Comment by kamilogorek** [comment]
That's quite odd, it should be indeed assigned to the specific project. Can you run the CI with `SENTRY_LOG_LEVEL=debug` env? It should give you logs with all the requests sent to Sentry, and it should tell us the whole store.

**Comment by cre8** [comment]
@kamilogorek could you find and specific in the logs?

**Comment by kamilogorek** [comment]
Sorry for the bot, I missed the issue. I see there are plenty of 208 responses from the server, and wonder if this is due to the fact that you use the same release name for every project (which shouldn't be the issue as they _are_ indeed scoped).
There should be a clear separation organization -> project -> release -> files.
I'm leaving for longer break Today so wont be able to help much right now, but we're doing some work around how source maps work now, so will try to get back to this once I'm back.

**Comment by cre8** [comment]
@szokeasaurusrex I haven't looked at this again because we changed our handling. Since I cannot give more information for this, this issue can be closed.
