### ISSUE TITLE
Problem to Notify Sentry a new realease from gitlab pipeline

### ISSUE THREAD

**Issue by maxi-89** [getsentry/sentry-cli#1499]
### Environment

Django app, Sentry cli 1.71.0

### Steps to Reproduce

this is my pipeline job
sentry-release-production:
  stage: release
  image: rxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/sentry-cli:latest
  script:
    - apt-get update && apt-get install -y ca-certificates
    - rm /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
    - update-ca-certificates -f
    - export APP_RELEASE="[production]-${CI_COMMIT_TAG}"
    - export FROM_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)))
    - export TO_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags))
    - sentry-cli --version
    - sentry-cli releases set-commits --commit "j<heremyorg>/<heremyproyect>@$FROM_GIT..$TO_GIT" "$APP_RELEASE"
    - sentry-cli releases --org $SENTRY_ORG deploys "$APP_RELEASE" new -e production
  only:
    - tags

### Expected Result

this is the track of the error when i run this job

error: An organization slug is required (provide with --org)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

ty, for help me

**Comment by kamilogorek** [comment]
Error says it all really. You need to provide org for all commands in one way or another. 

https://docs.sentry.io/product/cli/configuration/#sentry-cli-working-with-projects

or via `--org` flag everywhere.
