### ISSUE TITLE
error: http error: generic error (413)

### ISSUE THREAD

**Issue by fabware** [getsentry/sentry-cli#15]
upload with latest sentry-cli, encounter this:

DebugSymbols/SentrySwift.framework.dSYM/Contents/Resources/DWARF/SentrySwift
error: http error: generic error (413)

the files aren't large, I believe.

**Comment by mitsuhiko** [comment]
@fabware does this still occur?

**Comment by mitsuhiko** [comment]
Going to close because of lack of activity.

**Comment by kharmabum** [comment]
@mitsuhiko currently getting this on every upload attempt.

**Comment by mitsuhiko** [comment]
Can you run it with `--log-level=debug` and paste what it says?

**Comment by artnez** [comment]
I'm getting this too, but it's intermittent.

**Comment by mitsuhiko** [comment]
@artnez can you run with debug logs and paste what you get?

**Comment by artnez** [comment]
@mitsuhiko I tried running it a few times (ensuring unique files are uploaded each time) and it didn't repro. We switched to another solution in the meantime.

When it did occur (without debug logs) we saw this at around 10:30am PDT:

```
  3027cfbcf777e2effa4147ae53dce0328051e5c6  (217195 bytes)
 -> ~/14.8b0a846.js.map [sourcemap]
error: http error: generic error (413)
```

**Comment by mitsuhiko** [comment]
We have had these reports before but I never was able to reproduce it. Without debug logs this will be impossible to figure out sadly. I did try a few months back when it was originally reported but I cannot reproduce this at all.

**Comment by benvinegar** [comment]
Other related reports from the forums:

* https://forum.sentry.io/t/cannot-upload-ios-dsym-file-error-413-entity-too-large/707
* https://forum.sentry.io/t/413-error-when-uploading-bundle-js-map/297

**Comment by mitsuhiko** [comment]
The first link is unrelated. That was the dsym upload endpoint which has been corrected.

**Comment by artnez** [comment]
I still haven't been able to reproduce. I'll just have our deploy script run sentry-cli with the debug log level at all times :) Will let you know next time it happens.

Current random guess: A misconfigured server in the cluster.

**Comment by mattrobenolt** [comment]
> Current random guess: A misconfigured server in the cluster.

Trust me, this was a first guess. :)
