### ISSUE TITLE
Sourcemap URL mapping comment should be at the bottom

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry-cli#1505]
### Problem
Historically, browsers always look at the bottom of the minified code for the comment.

### Acceptance Criteria
Put it at the bottom ;)

**Comment by kamilogorek** [comment]
It is already the case for `DebugID` and `sourceMappingUrl`is generated by 3rd party tools (compilers, transpilers), so we don't control that:

ref: https://github.com/getsentry/sentry-cli/blob/f8dfc402ab4711a421160e5fc74e39b0c4d17ed2/src/commands/sourcemaps/inject.rs#L89-L107

**Comment by Jesse-Box** [comment]
We found in our testing that wasn't the case

cc: @mitsuhiko

**Comment by kamilogorek** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1523305/223704115-3239383e-70f0-4668-8809-4a7b32a86e34.png">

**Comment by loewenheim** [comment]
The problem is that the comment may be at the bottom when we look at the file, but then we append something else. We should inject our stuff immediately before the comment.

**Comment by kamilogorek** [comment]
Ohhhhhh, now I get it! https://github.com/getsentry/sentry-cli/pull/1511
