### ISSUE TITLE
Debug ID Bundles should be named by commit SHA

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry-cli#1509]
### Problem
Debug Id / UUID don't have any significance for debugging source map issues

### Acceptance Criteria
- if available, the bundle is named by the SHA of git commit
- If not available, it defaults to debug id

**Comment by ale-cota** [comment]
@lforst is this something we still need to do?

**Comment by lforst** [comment]
I don't know.

It is not something that we _need_ to do. But I am also not sure if it is something that we _want_ to do.

**Comment by lforst** [comment]
I don't think we can do this because not every project uses git or has a unique identifier. That was part of the issue with release name.
