### ISSUE TITLE
Uploding debug symbols with source context in XCode raises error: 'sentry-cli - error: unexpected argument '--include_sources' found'

### ISSUE THREAD

**Issue by kiddden** [getsentry/sentry-cli#1512]
### Environment
- sentry-cli 2.14.4
- XCode 14.1

### Problem
I'm using Run Script to upload debug symbols for my XCode project and want to enable [source context feature](https://docs.sentry.io/platforms/apple/guides/ios/data-management/debug-files/source-context/). According to the [documentation](https://docs.sentry.io/platforms/apple/guides/ios/dsym/) I'm adding '--include_sources' argument to my script, however, it raises a couple of errors when building my project: 
> sentry-cli - error: unexpected argument '--include_sources' found

> Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

### My script:
```
if which sentry-cli >/dev/null; then
export SENTRY_URL=
export SENTRY_ORG=
export SENTRY_PROJECT=
export SENTRY_AUTH_TOKEN=
ERROR=$(sentry-cli upload-dif --include_sources "$DWARF_DSYM_FOLDER_PATH" --force-foreground 2>&1 >/dev/null)
if [ ! $? -eq 0 ]; then
echo "error: sentry-cli - $ERROR"
fi
else
echo "error: sentry-cli not installed, download from https://github.com/getsentry/sentry-cli/releases"
fi
```

Does anyone have an idea why it happens or how to fix this?
Please note that everything works perfectly fine without adding '--include_sources' argument.

**Comment by kamilogorek** [comment]
Updated docs - https://github.com/getsentry/sentry-docs/pull/6449
