### ISSUE TITLE
`sentry-cli bash-hook` should support tags and context

### ISSUE THREAD

**Issue by ckdake** [getsentry/sentry-cli#1514]
When using other client libraries, e.g. the Ruby one, we can initialize Sentry locally settings tags/context so that we can group/report in the Sentry UI using them. e.g.:

```ruby
tenant="example"

Sentry.set_tags(tenant: tenant)
Sentry.set_context("tenant", {tenant: tenant})
```

This works great for the rails app, and we'd like to do something similar for our backend jobs using a different framework. It's straightforward enough to use sentry-cli there, e.g.:

```bash
if [[ -v SENTRY_DSN ]]; then
    echo "INFO: SENTRY_DSN is set, so we can use it to catch errors"
    eval "$(sentry-cli bash-hook)"
fi
```

But every event from every tenant is grouped into the same single BashError event in Sentry. It would be much better to be able to split these up for tenant, I'd expect this to work something like:

```bash
TENANT=example

if [[ -v SENTRY_DSN ]]; then
    echo "INFO: SENTRY_DSN is set, so we can use it to catch errors"
    eval "$(sentry-cli bash-hook --tags tenant=$TENANT --context tenant={tenant: $TENANT})"
fi
```

**Comment by ckdake** [comment]
I'd still like this to be considered. Thanks.

**Comment by kamilogorek** [comment]
There has been an attempt implementing this but wasnt taken through the finish line - https://github.com/getsentry/sentry-cli/pull/1398
If anyone wants to pick this up from there, should be rather straightforward to proceed :)
