### ISSUE TITLE
Cannot Run Sentry CLI with zx

### ISSUE THREAD

**Issue by chakravarthi-bb** [getsentry/sentry-cli#1515]
### Environment

What version are you running? Etc.

cli version: latest
environment: https://github.com/google/zx

### Steps to Reproduce

1. `sentry-cli releases --org xyz --project abc files my-app@2.8.7+codepush-staging@10 upload-sourcemaps --dist 10 --strip-prefix <root-path> ./build/CodePush/index.android.bundle ./build/CodePush/index.android.bundle.map`

### Expected Result

It should be able to read files

### Actual Result

bin/bash: No such file or directory

**Comment by kamilogorek** [comment]
Can you provide your whole `zx` script for reproduction?

**Comment by chakravarthi-bb** [comment]
Sorry the issue with zx
