### ISSUE TITLE
Sentry CLI Plugin: Command failed:

### ISSUE THREAD

**Issue by VijayYukthi** [getsentry/sentry-cli#1517]
I got the below error recently I have tried all the methods nothing works:

changed authToken to token in webpack file nothing works
ERROR in Sentry CLI Plugin: Command failed: D:\XXX\YYY\node_modules\@sentry\cli\sentry-cli.exe releases new APP@1.12.4
    error: API request failed
      caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

Any help is really appreciated

**Comment by bulkinav** [comment]
@VijayYukthi can you also check this related issue? - https://github.com/getsentry/sentry-cli/issues/1417

**Comment by kamilogorek** [comment]
Call `sentry-cli info --auth-token=<TOKEN>` and see what permissions are available to you.
