### ISSUE TITLE
error: your platform and architecture (Linux-x86_64) is unsupported.

### ISSUE THREAD

**Issue by AntonShuvaev** [getsentry/sentry-cli#1520]
During GitHub Actions workflow execution, the following error occurred:
`error: your platform and architecture (Linux-x86_64) is unsupported.`

After re-running the workflow, the error disappeared. I run it many times before and it worked fine.

I'm using `ubuntu-latest` as a runner and installing sentry-cli with the command: `curl -sL https://sentry.io/get-cli/ | bash`.

**Comment by kamilogorek** [comment]
Nothing major changed to the installation script in a long time - https://github.com/getsentry/getsentry/blob/master/getsentry/web/cli.py

We return this error in non-2XX responses, so most likely our CDN just had a small hiccup.

```
if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
  echo "error: your platform and architecture (${PLATFORM}-${ARCH}) is unsupported."
  exit 1
fi
```

There's no action here tbh, as it was most likely just a fluke. Let me know if it keeps happening, will reopen the issue then. Thanks.
