### ISSUE TITLE
Bug with sentry-cli@2.15.0 and the sourcemaps injection feature (#1504)

### ISSUE THREAD

**Issue by P1X3L** [getsentry/sentry-cli#1524]
### Environment

sentry-cli 2.15.0

### Steps to Reproduce

1. Our Circleci workflow is broken when trying to launch the following command with `sentry-cli@2.15.0` :

`sentry-cli releases files $CIRCLE_SHA1 upload-sourcemaps dist/ --url-prefix 'path_to_url_prefix'`

### Expected Result

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/319863/225403428-43800c37-5670-4647-8968-6093705922c6.png">

### Actual Result

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/319863/225403239-8390f6ce-3878-4913-9fb0-db0ee858ebdb.png">

We fixed the problem by forcing circle to use `sentry-cli@2.14.4`

**Comment by Sam-Hoult** [comment]
![image](https://user-images.githubusercontent.com/1436841/225410065-2ed9b43d-3327-4ff1-9e5a-97f8f4bffaf1.png)
Deployment broken (AWS CodeBuild) due to `2.15.0`

**Comment by Neneil94** [comment]
Had the same issue during my deplyoment jobs. I've set the version back to `2.14.4` and it worked.

This happened with `2.15.0`:
```shell
sentry-cli releases files $BRANCH upload-sourcemaps ./build/static/js/ --url-prefix '~/static/js'
> Found 12 release files
> Analyzing 12 sources
> Analyzing completed in 0.041s
> Injecting debug ids
Modified: The following source files have been modified to have debug ids
 [...]

Modified: The following sourcemap files have been modified to have debug ids
 [...]

> Rewriting sources
error: bad json: trailing characters at line 1 column 12653

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```
