### ISSUE TITLE
Crons: Add attachments support to CLI

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry-cli#1544]
We've recently enabled attachment support for a Crons check-in. We can now enable support in our CLI, to automatically upload it's output to Sentry.

**Comment by szokeasaurusrex** [comment]
@gaprl, to clarify, we should upload the output from the cronjob as an attachment? Should we do this always, or should we only do it when the user opts-in via a CLI flag?

**Comment by szokeasaurusrex** [comment]
@gaprl, gonna close this issue for now, since I am lacking necessary context here (see comment above). Please reopen with the requested information if this is still relevant
