### ISSUE TITLE
Vercel Enoent error pnpm

### ISSUE THREAD

**Issue by andylacko** [getsentry/sentry-cli#1580]
### Environment

Vercel with sentry integration
node 18.13 (Vercel)
**@sentry/cli** `12.17.2`
*@sentry/vite-plugin* `0.6.0`**
**pnpm**

### Steps to Reproduce

1. config vitePlugin

```typescript
    viteSentry({
      sourceMaps: {
        include: ['./dist/assets'],
        urlPrefix: '~/assets',
      },
      authToken: process.env.SENTRY_AUTH_TOKEN,
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,
      setCommits: {
        // repo: 'intellcre/intellcre',
        // commit: process.env.VERCEL_GIT_COMMIT_SHA,
        auto: true,
      },
      deploy: {
        env: process.env.MODE,
      },
    }),
```

2. deploy vercel

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/7139923/232452334-8685f461-b28f-4e20-a416-57561b6f98e3.png">

### Expected Result

work

### Actual Result

ENOENT, maybe every 2nd time, for now just pressing redeploy couple times

**Comment by kamilogorek** [comment]
Error in the logs explains it all. Your CI is most likely run for every possible deploy, which then gets squashed/rebased on master and your commits history is getting out of sync. You can use the flag above to ignore the error or reconfigure your CI to only trigger our plugin and perform a release during the actual production/staging deploy.
