### ISSUE TITLE
Backport sourcemap fix to v1

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1585]
[This fix](https://github.com/getsentry/rust-sourcemap/pull/61) in `sourcemap` fixes a problem with angular sourcemaps. It was included in version 2.14.4 of `sentry-cli`. Since the webpack plugin still uses version 1.x, it would be useful to backport this fix to version 1.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/1586
