### ISSUE TITLE
Create a release by copying an existing one (including its source maps)

### ISSUE THREAD

**Issue by antonpodolsky** [getsentry/sentry-cli#1589]
- We create a new Sentry release when our PR builds run and we upload source maps.
    - The version we use for the Sentry release name in this case is a hash of the build content.
- After merging a PR we want to be able to create a new release during the master build run by copying an existing one (which was created during the PR), including its source maps.
    - The version we use for the Sentry release name in this case is a semver.

Please advise if this is already possible (couldn't find anything in the docs), or if it's something that you can consider as a new feature.

**Comment by kamilogorek** [comment]
Unfortunately, it is not possible currently, as they're a lot of things happening in the backend during the release creation, which makes simple cloning non-trivial.
If you use the same release name, with the same artifact build, they will be deduped, however, in your case of changing the release name, it'll upload everything again.

> or if it's something that you can consider as a new feature.

We are currently working on a completely new way to handle sources and source maps, and hopefully in the near future, you'll be able to just point Sentry to any external server, where we'll read the artifacts based on their unique hash, not the release name. This way you'll be able to reuse the same artifacts for as many releases as you'll want :)
