### ISSUE TITLE
Wrong Created Date for new Releases via sentry-cli inside Docker container

### ISSUE THREAD

**Issue by teodorpatras** [getsentry/sentry-cli#1590]
### Set-up

I have a React app which I am building inside of a Docker container:

```
FROM node:16 AS builder

WORKDIR /app

RUN npm install -g @sentry/cli

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ ./.yarn/

RUN yarn install --immutable

COPY . ./

RUN ./bin/build.sh
```

redacted `build.sh`:

```
yarn build

sentry-cli releases new "0.3.0"
sentry-cli releases set-commits "0.3.0" --auto --ignore-missing
sentry-cli releases files "0.3.0" upload-sourcemaps ./build/
sentry-cli releases finalize "0.3.0"
```

### Expected Result

I would expect the new release to be available in the Sentry Dashboard under `https://<org>.sentry.io/releases/0.3.0/?project=<project-id>` with the correct `Created` date.

### Actual Result

Instead I see the build `Created` date with a random value:
![Screenshot 2023-04-25 at 18 30 14](https://user-images.githubusercontent.com/5859487/234327417-42178d3b-af67-4bed-90bd-41eaf00b0462.png)

Building it again with a new version (`0.6.0`) yields another random date:
![Screenshot 2023-04-25 at 18 32 41](https://user-images.githubusercontent.com/5859487/234328234-62476b48-1125-4c97-a8a9-aff51d9808f6.png)

Please tell me if I am missing some dependencies from my Docker container that might affect the created at date of the release.

**Comment by kamilogorek** [comment]
I just verified it and cannot reproduce this issue.

You can add `export SENTRY_LOG_LEVEL=debug` to your `build.sh` file and then run `docker build` with `--no-cache --progress=plain` flags to get all live logs printed. This way you should be able to see what calls CLI made, and one of them should include the dates, eg.

```
#9 1.178   DEBUG   2023-04-27 14:00:15.724965127 +00:00 body: {"id":713378953,"version":"0.3.0","status":"open","shortVersion":"0.3.0","versionInfo":{"package":null,"version":{"raw":"0.3.0"},"description":"0.3.0","buildHash":null},"ref":null,"url":null,"dateReleased":"2023-04-27T13:58:55.282422Z","dateCreated":"2023-04-27T13:57:36.600502Z", (...)
```
