### ISSUE TITLE
Uploading multiple source maps keeps only the last ones

### ISSUE THREAD

**Issue by floriangosse** [getsentry/sentry-cli#1591]
### Environment

* Node.js: v16
* Sentry CLI: v2.17.4

### Steps to Reproduce

* Upload source maps from multiple locations
* Inspect release artifacts -> first upload files are missing

The code snippet I'm using and which causes the problem.

```ts
await cli.releases.uploadSourceMaps(release, {
    include: [
        // Server files
        {
            paths: ['build'],
            urlPrefix: '~/server',
            stripPrefix: ['../../']
        },

        // Browser files
        {
            paths: ['public'],
            urlPrefix: '~/browser',
            stripPrefix: ['webpack://blabla/']
        }
    ],
    ignore: [],
    rewrite: true,
    urlPrefix: '~/'
});
```

### Expected Result

Have all sourcemaps of each upload available in the release.

### Actual Result

Only the last upload sourcemaps are added to the release.

**Comment by floriangosse** [comment]
Right, I can see both bundles.

I had the problem that the source maps weren't used in errors but that might be due to a misconfiguration on my side and because the release view doesn't display the total amount of artifacts but only of the last one.

**Comment by kamilogorek** [comment]
If you can share a link to unresolved event, I might take a look. A shareable one will suffice (there's a 'share' button on event page).

**Comment by rodolfoBee** [comment]
I was able to reproduce it using sentry-cli v2.18.1. According to other affected user, this behaviour can be reproduced on any release past 2.16.0. 

I created a simple script that sends an event.

Created release1 and uploaded the files:
![Screenshot 2023-05-24 at 09 20 16](https://github.com/getsentry/sentry-cli/assets/64906376/e42ee720-8227-4949-885c-028396d59ba3)

The event was correctly source mapped: https://dev-curumas.sentry.io/issues/4204369745/events/c2cb20d62c574d02bef347027a57f41c/

After that, I created a new release2 and uploaded the files to it. You will notice the screenshots below that release2 has 2 files, and release1 doesn't have any files anymore:
Release2:
![Screenshot 2023-05-24 at 09 21 07](https://github.com/getsentry/sentry-cli/assets/64906376/73da5414-d41c-401d-80e4-f75f7a6455ce)

Release1:
![Screenshot 2023-05-24 at 09 21 20](https://github.com/getsentry/sentry-cli/assets/64906376/0d41641e-00f8-47b1-9ca1-d11264ab7163)

After sending the same event, marked with release1 it is not source mapped: 
https://dev-curumas.sentry.io/issues/4204380918/events/3c7b23e24617474dab73477bd76cc56d/

**Comment by iambriccardo** [comment]
Hi @rodolfoBee, thanks for writing us!

The reasoning for why this is happening is that we run de-duplication server side for bundles with the same id. The rationale for this is that we want to avoid people uploading the same bundle multiple times, as the bundle id is deterministic and based on its content (we assume that after each release the content should change).

In the case of release/dist pairs it would make sense to technically allow binding the same bundle id for different release/dist pairs. I would like to know if this specific case is important for you.

Have a great day!

**Comment by iambriccardo** [comment]
The reasoning for why this is happening is that we run de-duplication server side for bundles with the same id. The rationale for this is that we want to avoid people uploading the same bundle multiple times, as the bundle id is deterministic and based on its content (we assume that after each release the content should change).

In the case of release/dist pairs it would make sense to technically allow binding the same bundle id for different release/dist pairs. I would like to know if this specific case is important for you.

Have a great day!

**Comment by rodolfoBee** [comment]
We have one use case where this is an issue:

From one release to another, there were only changes and additions to non Javascript files, but that also require a new deployment. From the cli view, the files uploaded to both releases are the same (it even logs the same bundle ID).

If Sentry gets events from the older release, they will not be source mapped.

**Comment by dreid** [comment]
In our specific use case every trunk build represents a potential release, but there may be an arbitrary number of trunk builds between deployments, and even when a particular trunk commit does get released there will be a period of time where only the previous deployment/release is active, and then where both an old and a new deployment/release are active.

**Comment by iambriccardo** [comment]
We are currently working internally on a new de-duplication mechanism that would effectively allow a single bundle, identified by its `bundle_id` to be bound to multiple different releases. So, if you upload the bundle with release 1.0 and then upload the same bundle with release 2.0, Sentry will bind both release to this bundle. Would this behavior be better?
