### ISSUE TITLE
sourcemaps explain: Point users towards debug ids

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1594]
See https://github.com/getsentry/sentry-cli/issues/1718.

**Comment by loewenheim** [comment]
We should do #1601 first.

**Comment by lforst** [comment]
Update here: We will likely deprecate the `sentry-cli sourcemaps explain` command since we are gonna have the source maps debugger modal which is gonna be equally powerful and we don't want to maintain two systems.

**Comment by mredigonda** [comment]
Hello @lforst!

Just came here after seeing the `sentry-cli sourcemaps explain` is indeed deprecated now, is that new "source maps debugger modal" already available? How can I use it?

Thanks!

**Comment by szokeasaurusrex** [comment]
@mredigonda The sourcemaps debugger modal is automatically available in the Sentry web interface when you are viewing an issue with missing or incorrectly uploaded sourcemaps

Since the debugger modal is now available, and since `sourcemaps explain` is now deprecated, I will close this issue
