### ISSUE TITLE
Docker latest tag has been reverted to 1.75.1

### ISSUE THREAD

**Issue by TiuSh** [getsentry/sentry-cli#1596]
### Environment

`getsentry/sentry-cli:latest`

### Steps to Reproduce

```
$ docker run --rm --pull always getsentry/sentry-cli:latest --version
```

### Expected Result

```
sentry-cli 2.17.4
```

### Actual Result

```
sentry-cli 1.75.1
```

**Comment by robbytx** [comment]
@kamilogorek it looks like your changes pushed to the 1.x branch were released and responsible for this state.

**Comment by kamilogorek** [comment]
Ugh, that's annoying. Sorry for that, v2 release is coming as we speak, which will fix that.

**Comment by kamilogorek** [comment]
All fixed.
