### ISSUE TITLE
Checksum validation failed on sentry-cli-Windows-x86_64.exe for version 1.75.1

### ISSUE THREAD

**Issue by sdb-dev** [getsentry/sentry-cli#1597]
### Environment
Windows and MacOS build agents failing with same issue.

### Steps to Reproduce
Just try to install the package in any fresh place,
`yarn add @sentry/cli@1.75.1`

The install fails due to a checksum fail on the file.
Relevant error from the logs:

```
Error: Checksum validation for sentry-cli-Windows-x86_64.exe failed.
Expected: 30ce70753891c3d755969b4e7d4fa9974f99082c05395c4a4bde082b58dbca08
Received: 3e247e031ce64037bfdd370c6b4e34a13791b478b9f9b87eaabc20e864084870
```

**Comment by w3liang** [comment]
I am having the same error, this version was published 5 hours ago, maybe the expected checksum wasn't updated?

**Comment by tuanhai2712** [comment]
> Hi thanks for reporting! We're aware of this and investigating. At this time, it seems to be a checksum mismatch as the binary seems to work when skipping the checksum check. To work around this you can set the `SENTRYCLI_SKIP_CHECKSUM_VALIDATION=1` environment variable and run `yarn add @sentry/cli` again.

How to  set `SENTRYCLI_SKIP_CHECKSUM_VALIDATION=1`  I'm using windows 11

**Comment by Lms24** [comment]
>How to set SENTRYCLI_SKIP_CHECKSUM_VALIDATION=1 I'm using windows 11

@tuanhai2712 for example like this:

```powershell
$Env:SENTRYCLI_SKIP_CHECKSUM_VALIDATION = 1
```

**Comment by nathanwaters** [comment]
@Lms24 you guys might want to look at what's happened with the version numbers: https://github.com/getsentry/sentry-cli/releases

**Comment by HazAT** [comment]
@nathanwaters Are you talking about that 1.x release are about 2.x?
I don't see an issue, the 2.x is marked as latest

**Comment by Lms24** [comment]
Hi folks, we just released 1.75.2 with now matching checksums. Installing the CLI, the Webpack plugin or SDKs using the webpack plugin (e.g. NextJS, Gatsby) should work now on Windows again.

**Comment by kamilogorek** [comment]
@nathanwaters the version numbers are correct. It was due to a partial release to GCS, which we pull our binaries from, and then we "finalized" the release for npm, but it was recompiled 🥲

**Comment by liudonghua123** [comment]
I have the same problems when install the dependences of https://github.com/toeverything/AFFiNE, after I check the code, I use `set SENTRYCLI_SKIP_CHECKSUM_VALIDATION=1` to skip the checksum validation.

I also noticed the version of download sentry-cli is `1.75.1` which maybe broken on the `checksums.txt`.

https://github.com/getsentry/sentry-cli/blob/92d058a47a852ca12ff8c2ec37000e96efaaa64d/scripts/install.js#L292-L294

And another question, I could not find the `checksums.txt` based on the code belows.

https://github.com/getsentry/sentry-cli/blob/92d058a47a852ca12ff8c2ec37000e96efaaa64d/scripts/install.js#L153-L187

**Comment by Lms24** [comment]
> I also noticed the version of download sentry-cli is 1.75.1 which maybe broken on the checksums.txt.

@liudonghua123 yes that was indeed the case for 1.75.1 but 1.75.2 should resolve this issue. Are you saying that npm still downloads 1.75.1 instead? I took a quick look at your repo and it seems like you're installing the CLI via the webpack plugin via the NextJS SDK. The plugin in its latest version requires `^1.75.1` so afaict, npm should actually take `1.75.2`.  

Have you tried cleaning caches/removing `node_modules` and reinstalling?

**Comment by liudonghua123** [comment]
> > I also noticed the version of download sentry-cli is 1.75.1 which maybe broken on the checksums.txt.
> 
> @liudonghua123 yes that was indeed the case for 1.75.1 but 1.75.2 should resolve this issue. Are you saying that npm still downloads 1.75.1 instead? I took a quick look at your repo and it seems like you're installing the CLI via the webpack plugin via the NextJS SDK. The plugin in its latest version requires `^1.75.1` so afaict, npm should actually take `1.75.2`.
> 
> Have you tried cleaning caches/removing `node_modules` and reinstalling?

I checked the version in lock version file, it's 1.75.1 indeed. And when I update the repo, this version updated too, so it should be ok now. Thanks! 😄 

```
[root@localhost AFFiNE]# grep -n @sentry/cli yarn.lock 
6604:"@sentry/cli@npm:^1.74.6, @sentry/cli@npm:^1.75.1":
6606:  resolution: "@sentry/cli@npm:1.75.1"
6733:    "@sentry/cli": ^1.74.6
6743:    "@sentry/cli": ^1.75.1
[root@localhost AFFiNE]# git pull
remote: Enumerating objects: 549, done.
remote: Counting objects: 100% (543/543), done.
remote: Compressing objects: 100% (257/257), done.
remote: Total 549 (delta 304), reused 511 (delta 280), pack-reused 6
Receiving objects: 100% (549/549), 718.57 KiB | 609.00 KiB/s, done.
Resolving deltas: 100% (304/304), completed with 24 local objects.
From github.com:toeverything/AFFiNE
   648fad65..b036fe85  master                                  -> origin/master
   5f336715..0390b80b  0425/feat/create-workspace-from-db-file -> origin/0425/feat/create-workspace-from-db-file
 + a2a6fca1...15aaef5e m1911star/updater                       -> origin/m1911star/updater  (forced update)
 + 438c3673...c6f38432 refactor/all-page                       -> origin/refactor/all-page  (forced update)
 * [new tag]           v0.5.4-canary.20                        -> v0.5.4-canary.20
Updating 648fad65..b036fe85
Fast-forward
 .github/workflows/release-desktop-app.yml              |   21 +-
 apps/electron/layers/main/src/data/workspace.ts        |    6 +-
 apps/electron/package.json                             |    4 +-
 apps/electron/scripts/generate-yml.js                  |   63 ++++++
 apps/server/package.json                               |    6 +-
 apps/web/package.json                                  |   24 +--
 apps/web/src/pages/workspace/[workspaceId]/setting.tsx |   11 +-
 codecov.yml                                            |    5 +
 package.json                                           |   12 +-
 packages/cli/package.json                              |    2 +-
 packages/component/package.json                        |   16 +-
 packages/debug/package.json                            |    2 +-
 packages/env/package.json                              |    6 +-
 packages/graphql/package.json                          |    2 +-
 packages/hooks/package.json                            |    2 +-
 packages/i18n/package.json                             |    6 +-
 packages/i18n/src/resources/en.json                    |    3 +-
 packages/i18n/src/resources/zh-Hans.json               |    3 +-
 packages/jotai/package.json                            |   10 +-
 packages/octobase-node/package.json                    |    4 +-
 packages/templates/package.json                        |    2 +-
 packages/theme/package.json                            |    4 +-
 packages/workspace/package.json                        |    2 +-
 packages/y-indexeddb/package.json                      |    8 +-
 tests/fixtures/package.json                            |    2 +-
 tests/kit/package.json                                 |    2 +-
 tests/parallels/local-first-delete-workspace.spec.ts   |   59 +++++-
 yarn.lock                                              | 1265 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------
 28 files changed, 851 insertions(+), 701 deletions(-)
 create mode 100644 apps/electron/scripts/generate-yml.js
 create mode 100644 codecov.yml
[root@localhost AFFiNE]# grep -n @sentry/cli yarn.lock 
6560:"@sentry/cli@npm:^1.74.6, @sentry/cli@npm:^1.75.1":
6562:  resolution: "@sentry/cli@npm:1.75.2"
6689:    "@sentry/cli": ^1.74.6
6699:    "@sentry/cli": ^1.75.1
[root@localhost AFFiNE]#
```
