### ISSUE TITLE
Unexpected "no sourcemap ref" when uploading sourcemaps

### ISSUE THREAD

**Issue by adamesque** [getsentry/sentry-cli#160]
Hi, I'm using sentry-cli 1.24.1 and am seeing "no sourcemap ref" when uploading sourcemaps in a case where I believe sentry-cli should be able to infer the correct refs from the filename.

```
Source Map Upload Report
  Scripts
    ~/rsrcs/my-project/vendor.dev.js
  Minified Scripts
    ~/rsrcs/my-project/bundle.361685d6fc3fc73f5838.js (no sourcemap ref)
      - error: missing sourcemap!
    ~/rsrcs/my-project/common.ff65226063b039e5cb82.js (no sourcemap ref)
      - error: missing sourcemap!
    ~/rsrcs/my-project/manifest.19af5e4965b70d66c290.js (no sourcemap ref)
      - error: missing sourcemap!
  Source Maps
    ~/rsrcs/my-project/bundle.2782294d50665e8732695aa57996637f.css.map
    ~/rsrcs/my-project/bundle.361685d6fc3fc73f5838.js.map
    ~/rsrcs/my-project/common.28ea05dccadada3b93115ac5cce5a8b2.css.map
    ~/rsrcs/my-project/common.ff65226063b039e5cb82.js.map
    ~/rsrcs/my-project/manifest.19af5e4965b70d66c290.js.map
```

From this report, sentry-cli isn't inferring that `bundle.361685d6fc3fc73f5838.js -> bundle.361685d6fc3fc73f5838.js.map`.

In [`guess_sourcemap_reference`](https://github.com/getsentry/sentry-cli/blob/master/src/utils/sourcemaps.rs#L108-L137), I see a bunch of case comments that imply that we're always looking for source files with `.min` extensions, while ours (although minified) do _not_ have that. I'm not a rustacean, so I'm not entirely clear what the code is actually doing. Should it be able to guess the references?

I'm generating my sourcemaps with webpack using `devtool: hidden-source-map`, so there are no `sourceMapURL` comments in our `.js` files. I presumed this would work?

**Comment by adamesque** [comment]
@ndmanvar just looping you in!

**Comment by ndmanvar** [comment]
@adamesque Can you also add the complete `sentry-cli` command you are running?

**Comment by ndmanvar** [comment]
I tried to simulate your setup, but sentry-cli seems to find the correct sourcemap.
See:
```

**Comment by ndmanvar** [comment]
@mitsuhiko Seems like `sourcemap` header is not getting set properly in @adamesque 's example. Any ideas why, or is there any other pieces of information/code that can help assist in debugging here?

To me, it looks like Adam's example is not able to grab the sourcemap_ref from headers (maybe because it is not set?)

**Comment by ndmanvar** [comment]
Should the `path` be passed here (instead of `None`)? https://github.com/getsentry/sentry-cli/blob/master/src/utils/sourcemaps.rs#L117

**Comment by mitsuhiko** [comment]
Cannot reproduce so far. Any chance you can set us the unmodified output @adamesque? Maybe to armin@sentry.io. (I assuem 'my-project' is something you added and not the actual project name). I wonder if some characters there can confuse the matching process.

**Comment by mitsuhiko** [comment]
Is there any chance you are accidentally passing `--no-sourcemap-reference` to sentry-cli?
