### ISSUE TITLE
Sentry URL with more than two slashes is wrong

### ISSUE THREAD

**Issue by pavel-cw** [getsentry/sentry-cli#1612]
### Steps to Reproduce

**On-premise** sentry deployment is on URL https://something.something.com/sentry
it is impossible to deploy on different address - it must be in subfolder (/sentry)

### Expected/Actual Result

It is actually good URL, everything works just fine, but if i try to login via sentry-cli:
```
sentry-cli 
  --url https://something.something.com/sentry
  login 
  --auth-token xyzasdfasdf
  --log-level trace
```
error is shown:
`error: bad sentry url: not on URL root (https://something.something.com/sentry)`

### Problem

I see the main problem in [THIS file](https://github.com/getsentry/sentry-cli/blob/6895d153e93bddf8a8d52bf4ab04af885d8a3c26/src/config.rs#L166) Line 166,  it fails right there.

Thank you :)

**Comment by kamilogorek** [comment]
Sorry, however we dropped support for non-root urls years ago. Instead of hosting at `/sentry`, we recommend you host it at `https://sentry.something.something.com` instead.

See: https://develop.sentry.dev/config/

```
system.url-prefix
Declared in config.yaml

The URL prefix in which Sentry is accessible. This will be used both for referencing URLs in the UI, as well as in outbound notifications. This only works for scheme, hostname and port. In particular, it does not work for path (we supported this years ago, but it became too difficult to maintain). Sentry needs to be at the root of its own (sub)domain or IP address.
```
