### ISSUE TITLE
Installing npm sentry failing. 

### ISSUE THREAD

**Issue by Shpadoinkle** [getsentry/sentry-cli#162]
I am getting the same error here as listed in an older 'closed' bug. .

I have a fresh install of windows, latest node and latest npm.

npm always fails on install-sentry-cli

`

sentry-cli-binary@1.24.1 install C:\Users\Gibbs\Desktop\NewProject\nod
e_modules\sentry-cli-binary
node ./bin/install-sentry-cli
fetching sentry-cli-Windows-i686.exe ████████████████████ 100% 0.0s
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.24.1 install: node ./bin/install-sentry-cli
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Gibbs\AppData\Roaming\npm-cache_logs\2017-11-29T02_48_04_
761Z-debug.log
`

Followed the advice of other thread with adding add .dll file but havn't gotten any further.

**Comment by rulgf** [comment]
@Shpadoinkle Did you resolve this issue?
