### ISSUE TITLE
Sourcemaps upload return 413 error code seemingly overnight

### ISSUE THREAD

**Issue by geauser** [getsentry/sentry-cli#1623]
### Environment

sentry-cli _(installed with yarn)_: `v2.18.1` _(was using `v2.18.0` before, tried to update it to latest, but to no avail)_
OS: macOS 12.4 Monterey

### Steps to Reproduce

I ran

```sentry-cli sourcemaps upload --release=MY_RELEASE --url-prefix some/prefix ./sourcemaps/folder/path```

### Expected/Actual Result

Yesterday I had no problem uploading sourcemaps, but now I get this error: `error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)`. As an attempt to fix an issue with sourcemaps I had to do a lot of uploads yesterday. Maybe I hit a rate limit error that appears as a file too large error? Please note that nothing in my code as changed since yesterday.

### Logs

```
  INFO    2023-05-23 10:47:01.101065 +02:00 using 'gzip' compression for chunk upload
  DEBUG   2023-05-23 10:47:01.807907 +02:00 request POST https://sentry.io/api/0/organizations/guiderail/chunk-upload/
  DEBUG   2023-05-23 10:47:01.808067 +02:00 sending form data
  DEBUG   2023-05-23 10:47:01.808244 +02:00 using token authentication
  DEBUG   2023-05-23 10:47:01.808286 +02:00 retry number 0, max retries: 5
  DEBUG   2023-05-23 10:47:01.824615 +02:00 > POST /api/0/organizations/guiderail/chunk-upload/ HTTP/1.1
  DEBUG   2023-05-23 10:47:01.824675 +02:00 > Host: sentry.io
  DEBUG   2023-05-23 10:47:01.824812 +02:00 > Accept: */*
  DEBUG   2023-05-23 10:47:01.824942 +02:00 > Connection: TE
  DEBUG   2023-05-23 10:47:01.824975 +02:00 > TE: gzip
  DEBUG   2023-05-23 10:47:01.824993 +02:00 > User-Agent: sentry-cli/2.18.1
  DEBUG   2023-05-23 10:47:01.825436 +02:00 > Authorization: Bearer 985573f0***
  DEBUG   2023-05-23 10:47:01.825475 +02:00 > Content-Length: 23407433
  DEBUG   2023-05-23 10:47:01.825494 +02:00 > Content-Type: multipart/form-data; boundary=------------------------b173959287b99cea
  DEBUG   2023-05-23 10:47:01.984739 +02:00 < HTTP/1.1 413 Request Entity Too Large
  DEBUG   2023-05-23 10:47:01.984827 +02:00 < Server: nginx
  DEBUG   2023-05-23 10:47:01.984973 +02:00 < Date: Tue, 23 May 2023 08:47:01 GMT
  DEBUG   2023-05-23 10:47:01.985040 +02:00 < Content-Type: text/plain
  DEBUG   2023-05-23 10:47:01.985073 +02:00 < Content-Length: 15
  DEBUG   2023-05-23 10:47:01.985125 +02:00 < Connection: close
  DEBUG   2023-05-23 10:47:01.985169 +02:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2023-05-23 10:47:01.987066 +02:00 response status: 413
  DEBUG   2023-05-23 10:47:01.987112 +02:00 body: request timeout
```

This payload is about `23mb` so It should not be an issue right?

**Comment by minyushov** [comment]
We're observing the same issue when trying to upload iOS dSYMs and Android mappings.

**Comment by mym0404** [comment]
We have the same issue.

- Android Source map 18Mib (single file) -> OK
- iOS Source map 8.5Mib + 18.0Mib (two files) -> Failed with 413

**Comment by geauser** [comment]
@minyushov @mym0404 Just tried again and the problem seems gone, must have been a transient issue on their end.

**Comment by mym0404** [comment]
> @minyushov @mym0404 Just tried again and the problem seems gone, must have been a transient issue on their end.

Our CD also has been completed 👍🏻

**Comment by geauser** [comment]
> > @minyushov @mym0404 Just tried again and the problem seems gone, must have been a transient issue on their end.
> 
> Our CD also has been completed 👍🏻

Alright then! I'll close the issue. Have a nice day 😄

**Comment by kamilogorek** [comment]
Can confirm there was a small hiccup on our end. Should be fixed now - https://status.sentry.io/incidents/mdblw8vxzpl0
