### ISSUE TITLE
`debug-files find` should find debug files (any type) recursively without an `id`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cli#1627]
I wanna use the `find` cmd without an `id`, I wanna locate debug files in a folder tree, I don't know the debug ids beforehand.

If the `id` is mandatory, and its omitted, it should print out a log as well, right now doing `sentry-cli debug-files find -p=/` has no output which is technically wrong, feels like there were no debug files in there, but there were, you need an `id` though.

**Comment by szokeasaurusrex** [comment]
`debug-files find` is meant to be used to find debug files with a given ID. This is clearly stated in the help text for the command:

```
Locate debug information files for given debug identifiers
```
