### ISSUE TITLE
[Android] Support variable for version name and code in the build.gradle 

### ISSUE THREAD

**Issue by peteroid** [getsentry/sentry-cli#163]
I have declared the version code and name as something as follows.
```gradle
project.ext.versionName = '0.0.1'
project.ext.versionCode = 99
////
versionCode project.ext.versionCode
versionName project.ext.versionName
```

When I tried to upload the assets after the code pushing, cli would output `error: Could not parse app id from build.gradle` and the uploading process stopped. 

Could I explicitly specify the version name so that the cli can skip the detection? FYI, code push supports this kind of flag called `--targetBinaryVersion`.

Envrionment
- macOS: 10.13.1
- node: 8.9.1
- sentry-cli: 1.23.0

**Comment by mitsuhiko** [comment]
For which command is this. `react-native codepush`?

**Comment by peteroid** [comment]
This is a part of my script to push the assets to Sentry. So the idea is to generate the assets first, then let `sentry-cli` to upload the assets for me. This idea is copied from the [sentry guidelines](https://docs.sentry.io/clients/react-native/codepush/).

```bash
  echo "### [$PLATFORM] Generating build assets ###"
  react-native bundle \
    --dev false \
    --platform "$PLATFORM" \
    --entry-file "$PROJECT_DIR/index.$PLATFORM.js" \
    --bundle-output "$BUILD_DIR/main.jsbundle" \
    --sourcemap-output "$BUILD_DIR/main.jsbundle.map" \
    --assets-dest "$BUILD_DIR"

  echo "### [$PLATFORM] Pushing assets to Sentry ###"
  $PROJECT_DIR/node_modules/sentry-cli-binary/bin/sentry-cli \
    react-native codepush "$CODEPUSH_APP" "$PLATFORM" "$BUILD_DIR" \
    --deployment Production \
    --org my_org \
    --project my_project
```

**Comment by cpetzel** [comment]
Any update on this? 

Here is how my gradle is configured versionName is a function, which [This part](https://github.com/getsentry/sentry-cli/blob/2137eb2a29bcb198c7cbb7fc7379efb722b4acbc/src/utils/releases.rs#L71) of the sentry cli doesn't like...



```
def getVersionName = { ->
    def name = project.hasProperty('versionName') ? versionName : "0.0.0"
    println "VersionName is set to $name"
    return name
}

 defaultConfig {
        applicationId "my.app.id"
        versionCode getVersionCode()
        versionName getVersionName()
```

We need the ability to specify this similar to `--targetBinaryVersion` in codepush...

**Comment by peacechen** [comment]
`sentry-cli` is also failing here with `error: Could not parse app id from build.gradle`.  My build.gradle uses methods to fill in the version information (because who wants to manually edit the gradle file on every release?).
```
  versionCode Integer.parseInt(computeVersionName().replaceAll("[^\\d]", ""))
  versionName computeVersionName()
```

Any solution to passing the version as a parameter to sentry-cli ?

**Comment by peacechen** [comment]
@mitsuhiko   How should we request a feature to add the flag `--targetBinaryVersion` ?  To upload Android CodePush sourcemaps with `sentry-cli`, I have to manually edit build.gradle with hard-coded version numbers.

```
  versionCode 123
  versionName "1.2.3"
```

**Comment by peteroid** [comment]
@mitsuhiko For my case, it should be fixed by changing [this line](https://github.com/getsentry/sentry-cli/blob/master/src/utils/releases.rs#L55) to 
`static ref VERSION_NAME_RE: Regex = Regex::new(r#"versionName[\s=]+["']([^"']*)["']"#).unwrap();`

It just changes `\s+` to `[\s=]+` to handle the case for `project.ext.versionName = '0.0.1`

**Comment by peacechen** [comment]
@mitsuhiko  Does that allow computed a computed value for `versionName`?  In our case, the value isn't a string in the build.gradle, but a function call that extracts the version from the package.json.

**Comment by antonsivogrivov** [comment]
Have  the same issue, any updates?

**Comment by antonsivogrivov** [comment]
So, I think we should use --bundle-id option

**Comment by peacechen** [comment]
@antonsivogrivov   I don't see `bundle-id` in the documentation.  Would you post a link, or provide an example?

**Comment by peacechen** [comment]
Thanks @antonsivogrivov .  I had an older version of sentry-cli which didn't have that option.  Updated to 1.36 and it's there.

**Comment by ewendel** [comment]
We encountered this problem because we used the character "=" between `versionName` and its value:

```
versionCode = rootProject.ext.versionCode
versionName = rootProject.ext.versionName
```

This made the regex expression on [this line](https://github.com/getsentry/sentry-cli/blob/b1c27d1be0651f93cd96857f34e86cd856477ee7/src/utils/releases.rs#L59) fail.

Removing the unnecessary character fixed the problem:

```
versionCode rootProject.ext.versionCode
versionName rootProject.ext.versionName
```

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by martintreurnicht** [comment]
The solution is to use `--version-name` when using dynamic versions, same when using product flavors, specify `--bundle-id` manually
