### ISSUE TITLE
Sentry cli not installing in Angular project on Windows 11

### ISSUE THREAD

**Issue by BrunoElo** [getsentry/sentry-cli#1632]
### Environment
Windows
Angular project
What version of the CLI and what OS are you running?
Sentry CLI version: 2.9.0
OS version: 11
Angular version: 15
@sentry/angular-ivy version: 7.45.0

### Steps to Reproduce

What you did?
npm i --legacy-peer-deps
### Expected/Actual Result

What you thought would happen and what actually happened?
I thought all packages including sentry cli will install successfully however, I keep getting the error
```
npm ERR! code 1
npm ERR! path C:\b\p\ess\ess-app\frontend\node_modules\@sentry\cli
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./scripts/install.js
npm ERR! [sentry-cli] Using cached binary: C:\Users\<pcname>\AppData\Local\npm-cache\sentry-cli\cb5e1f-sentry-cli-Windows-x86-64.exe
npm ERR! Error: Command failed: C:\b\p\ess\ess-app\frontend\node_modules\@sentry\cli\sentry-cli.exe --version

```
### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

**Comment by kamilogorek** [comment]
Thanks WIndows, that log not helpful in the slightest 😅
Can you try to purge your npm cache and try again? `C:\Users\<pcname>\AppData\Local\npm-cache\sentry-cli` should be sufficient to remove. It's most likely somewhat with file permissions to the file we want to copy and use as the cli binary in the project locally.

**Comment by BrunoElo** [comment]
My bad about the logs.
You're probably right about file permissions being the issue. I tried your suggestion but I still got same issue. I did it on a another PC with similar environment and it works fine so I'll continue with that.
Thanks.

**Comment by kamilogorek** [comment]
Feel free to take a look at the cache path resolution code, it should be rather clear how one is chosen. There are 3 npm ones, 1 `AppData` (Windows, the one you use), and a fallback to `.npm` in the home dir.

https://github.com/getsentry/sentry-cli/blob/aba158c5dfa64042cbd7ce827311ae06e930df68/scripts/install.js#L125-L137

Setting an alternative npm cache directory and letting it through to `.npm` by unsetting `AppData` for the time of installation should do the trick as well.

Anway, from what I see you found a way around it, so I'll let myself close the issue :) Cheers!
