### ISSUE TITLE
Sending stored raw events when network is down should return error

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-cli#1635]
Submitting on behalf of a customer. 

> The issue here is if we rely on the `send-event` flow for uploading events we would need an response that can allow us to act when there are network issues, rate limited, Sentry.io outage, etc… as this would allow us to back off in the case of hitting a rate limit or pausing for a period of time when there are issues on with the network. Otherwise we are potentially going to lose events without even being aware of it.

Relevant PRs for reference:

- https://github.com/getsentry/sentry-cli/pull/1582
- https://github.com/getsentry/sentry-rust/pull/579 (opened to fix a bug that existed in which raw envelopes were never sent)

### Environment

CLI: `2.18.1`

### Steps to Reproduce

1. [updated sentry-cli to 2.18.1](https://docs.sentry.io/product/cli/installation/#updating-and-uninstalling).
2. Disconnect from network access on the machine
3. Ran the send-event command using the new `--raw` flag, for example `sentry-cli send-event --raw ./my-file.json`

### Expected/Actual Result

Expected result: `send-event` would return an **error state** to inform us the event failed to send.

Actual result: `send-event` returns with the event was successfully dispatched `“Event from file my-file.json dispatched: [event-id]”`

### Logs

```
// the many additional numbers in `items: Raw([...stuff...])` have been truncated for easier reading

DEBUG   2023-06-02 09:45:47.016766 +01:00 sentry-cli version: 2.18.1, platform: "darwin", architecture: "arm64"
INFO    2023-06-02 09:45:47.017596 +01:00 sentry-cli was invoked with the following command line: "sentry-cli" "send-event" "--raw" "dummy.json"
DEBUG   2023-06-02 09:45:47.019338 +01:00 Envelope { event_id: None, items: Raw([123, 34, 101, 118, 101, 110, 116, 95, 105, 100, 34, 58, 34, 56, 102, 48, 100, 48, 53, 48, 101, 45, 99, 98, 102, 102, 10, 125]) }
Event from file dummy.json dispatched: 8f0d050e-cbff-49da-b505-b5b8c4065df9
```

**Comment by loewenheim** [comment]
Are the sample events in question anything specific? I would like to try this with a local Sentry setup.

**Comment by cstavitsky** [comment]
@loewenheim chatting with the customer via email -- looks like I misunderstood the original problem and have gotten some new information.

I've overhauled the description to reflect the actual problem, which is around not being able to tell when sending an event with `send-event` has failed, for example if the network is down.

I suggest reviewing the revised description 🙇 Thanks!

**Comment by kamilogorek** [comment]
This is by design. SDKs and CLI are sending events via fire-and-forget mechanism, and we do not allow for awaiting on the server response.

See the discussion here https://github.com/getsentry/sentry-rust/issues/482 (CLI is using sentry-rust under the hood).

From the `sentry-cli send-event --help`:

```
Send a manual event/envelope to Sentry.

This command will validate input parameters and attempt to send an event to Sentry. Due to network
errors, rate limits or sampling the event is not guaranteed to actually arrive. Check debug output
for transmission errors by passing --log-level=debug or setting `SENTRY_LOG_LEVEL=debug`.
```
