### ISSUE TITLE
Failed to download @sentry/cli

### ISSUE THREAD

**Issue by tangchaoren1** [getsentry/sentry-cli#1636]
### Environment
![image](https://github.com/getsentry/sentry-cli/assets/19602189/e75795f6-b31e-4022-a8c1-c9cd08d7704b)

pnpm version: 7.29.1
node  version: 16.15.1
npm   version:  8.11.0

### Steps to Reproduce
1. pnpm install
2. @sentry/cli: Running install script, failed

### Expected/Actual Result
Error: Command failed  \node_modules\.pnpm\@sentry+cli@1.75.2\node_modules\@sentry\cli\sentry-cli.exe --version

**Comment by kamilogorek** [comment]
We had some reports of issues fetching binaries from CDN using Chinese networks. You can give GitHub instance a try instead as the first step:

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```
