### ISSUE TITLE
Uploading sourcemaps fails the first time

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1637]
The customer has to upload sourcemaps twice for it to go through. They have been advised to try the `no-dedupe` flag and get back to us with full logs if it doesn't resolve the problem.

**Comment by Yonben** [comment]
Same issue here. Ran our CI jobs as usual, we got the following:
```
ERROR in Sentry CLI Plugin: Command failed: /opt/<app-name>/node_modules/@sentry/cli/sentry-cli releases finalize <AppName>Release_ae4624f3
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 503)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
```

When rerunning the job, it was all fine.

**Comment by kamilogorek** [comment]
@Yonben please see https://status.sentry.io/incidents/g9zzh50g1nj0

**Comment by Yonben** [comment]
I saw it but it was already in the current step.. I reran the job and it worked...
But it failed our build step.

**Comment by ashwoods** [comment]
Staleboting this, please let us know if you run into this again.
