### ISSUE TITLE
You do not have permission to perform this action. (http status: 403)

### ISSUE THREAD

**Issue by RZ-Jyothsna** [getsentry/sentry-cli#1639]
Sentry has been integrated to frontend code of our application. Recently, while deploying, we are getting this api authorisation isue. Could you please help to resolve this.

![image](https://github.com/getsentry/sentry-cli/assets/117725492/ef26f871-2650-4e55-8c6c-86f177f0a189)

**Comment by kamilogorek** [comment]
Hey, did you actually verify the API keys used in your CI? Did you try to swap them for a new one?
If you used user bound token, maybe the person providing it left the org? Or someone changed permissions? It's not possible to tell right away from the logs.

**Comment by RZ-Jyothsna** [comment]
While building the webpack, it is throwing this api authorisation err. Could you specify what information you need.

**Comment by RZ-Jyothsna** [comment]
one more thing I did not understand is, if we redploy it in vercel, it is working well. This error is happening only when we deploy through gitlab by this command.
npx vercel --yes -t [MASKED] --scope rekstrarvorur --build-env ...........

**Comment by kamilogorek** [comment]
In vercel, assuming you have integration set, it uses configured ENV variables - https://docs.sentry.io/product/integrations/deployment/vercel/ which means that API token there is most likely different than the one you are using for your GitLab deployment. And this one may be simply incorrect.
