### ISSUE TITLE
Receiving "error: API request failed... unknown error (http status: 408)" when uploading source maps

### ISSUE THREAD

**Issue by martinbee** [getsentry/sentry-cli#1644]
```
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 408)
```

### Environment

Sentry CLI v2.18.1 running inside circle ci Ubuntu 20.04.5 LTS container.

### Steps to Reproduce

```
echo "Mobile Sentry Upload"
sentry-cli releases new -p $SENTRY_MOBILE_PROJECT $SENTRY_RELEASE
sentry-cli releases set-commits $SENTRY_RELEASE --auto --ignore-missing
sentry-cli releases files -p $SENTRY_MOBILE_PROJECT $SENTRY_RELEASE upload-sourcemaps ./public/build --dist $SENTRY_RELEASE
sentry-cli releases finalize $SENTRY_RELEASE
sentry-cli releases deploys $SENTRY_RELEASE new -e $NODE_ENV
```

### Expected/Actual Result
Source maps would upload successfully. Starting roughly 3-4 days ago we began to receive a 408 error from Sentry with no changes to our code:

![Screen Shot 2023-06-15 at 9 11 22 AM](https://github.com/getsentry/sentry-cli/assets/9852415/be61f5db-8650-4afa-b7a8-2a98981bb916)

**Comment by kamilogorek** [comment]
We had an issue yesterday that should be resolved by now - https://status.sentry.io/incidents/54x9ryv85xhl
Sorry for the inconvinience.
