### ISSUE TITLE
Source maps inject results in corrupt source map files

### ISSUE THREAD

**Issue by jskrepnek** [getsentry/sentry-cli#1646]
### Environment

What version of the CLI and what OS are you running?

- 2.19.0 and 2.19.1
- Linux

### Steps to Reproduce

What you did?

- sentry-cli sourcemaps inject www
- https://docs.sentry.io/platforms/javascript/guides/angular/sourcemaps/troubleshooting_js/#verify-your-source-maps-work-locally

### Expected/Actual Result

Expected the verification to work, but in resulted in output like:
```
{ source: null, line: null, column: null, name: null }
```

In Sentry, errors were being mapped to incorrect files.

What you thought would happen and what actually happened?

### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

**Comment by jskrepnek** [comment]
I forgot to mention that I was able to successfully use inject with 2.18.1.

**Comment by kamilogorek** [comment]
@jskrepnek is there a chance you could share successfully and unsuccessfully mapped error that used 2.18/2.19 respectively?

**Comment by jskrepnek** [comment]
> @jskrepnek is there a chance you could share successfully and unsuccessfully mapped error that used 2.18/2.19 respectively?

I have an open support request (88827) for this as well.  I shared an unsuccessfully mapped error there (using 2.19.X), and I'll also share a successfully mapped error (using 2.18.1).
