### ISSUE TITLE
Inject Debug IDs using Node wrapper

### ISSUE THREAD

**Issue by kitcat-dev** [getsentry/sentry-cli#1650]
It's already possible to inject Debug ID to source maps via `sentry-cli` ([source](https://github.com/getsentry/sentry-cli/blob/master/src/commands/sourcemaps/inject.rs)): 
```
sentry-cli sourcemaps inject /path/to/directory
```

I think it would be great to support this feature in Node wrapper.

**Comment by kitcat-dev** [comment]
Oh, I found the option `useArtifactBundle`. So, I guess I was too hasty with the creation of the Issue, and it can be closed.

**Comment by kitcat-dev** [comment]
Hi!
I discovered that `useArtifactBundle` does not inject debug ids so my feature request is still actual.

**Comment by kamilogorek** [comment]
Let's follow-up on this once https://github.com/getsentry/sentry-cli/issues/1670 and https://github.com/getsentry/sentry-cli/issues/1647 are resolved. We dont want to expose it even more just yet.

**Comment by szokeasaurusrex** [comment]
@kitcat-dev Just spotted this issue while combing through our backlog; since it is pretty old, just wanted to ask whether this is still a problem?

**Comment by kitcat-dev** [comment]
Yes, looks like it can be closed
