### ISSUE TITLE
Flutter Web crash logs are minified despite uploading source-maps

### ISSUE THREAD

**Issue by numerative** [getsentry/sentry-cli#1655]
### Environment
`sentry-cli 2.10.0 on MacOS Venture 13.4.1`

`sentry_flutter: ^7.2.0`

#### 1. Build
`flutter build web --source-maps`
#### 2. Upload source maps
`sentry-cli releases new "flutter_spa@0.0.1+1"`

`sentry-cli releases files "flutter_spa@0.0.1+1" upload-sourcemaps path_to_build_directory`

`sentry-cli releases finalize "flutter_spa@0.0.1+1"`

### Expected/Actual Result

Expected: Readable Crash logs from the Flutter Web

Actual: Minified Logs are reported 
![image](https://github.com/getsentry/sentry-cli/assets/28054527/f36c4863-2586-4649-9d64-27cb55bf5316)

**Output from `sentry-cli sourcemaps explain 1fe9ecb3757d4803a45b8d488b33af97`**
```
✔ Fetched data for event: 1fe9ecb3757d4803a45b8d488b33af97
✔ Event has release name: flutter_spa@0.0.1+1
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
⚠ Exception is already source mapped and first resolved frame points to:

        position: absolute;
        top: 50%;
        left: 0;
        margin-top: -100px;
      }
> break}case 1:return A.D(q,r)}})
    </style>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.10.0/lottie.min.js"></script>
  </head>
```

**Comment by kamilogorek** [comment]
It appears that source{map} files are correctly picked up, which may indicate that generated maps are incorrect in the first place.
You can use https://pub.dev/packages/source_maps to verify that your setup can produce/parse them.

**Comment by ashwoods** [comment]
Staleboting this. Please feel free to reopen if this issue reappears.
