### ISSUE TITLE
inject: Make sourcemap discovery more flexible

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1656]
Imagine the following setup, where minified source files and sourcemaps reside in different directories:

```
code/
    foo.js --> foo.js.map
    bar.js --> bar.js.map
sourcemaps/
    foo.js.map
    bar.js.map
```

Then `sentry-cli sourcemaps inject code/ sourcemaps/` should be able to find the sourcemaps referenced by the source files even if the exact paths aren't given.

The easiest way to do this would be to see if we have any file with the given name (say, `foo.js.map`). The obvious question then is whether this can lead to collisions, i.e., could we have several sourcemaps all called `foo.js.map`? If so, should we rank them somehow and pick the best match?

**Comment by Swatinem** [comment]
IMO, if multiple files are matching the name, we should just bail, as there is no way to tell which one is which. unless you can somehow match part of the directory structure. Though we are deep in heuristic territory here.

But consider this example, `index.js` is the equivalent to `mod.rs`:

```
code/
  index.js -> index.js.map
  child/
    index.js -> index.js.map
sourcemaps/
  index.js.map
  child/
    index.js.map
```

**Comment by loewenheim** [comment]
I was thinking in the direction of matching part of the directory structure as well. Taking `code/child/index.js` from your example, we would expect the sourcemap to be at `code/child/index.js.map`. We don't have such a file, but we _do_ have `*/child/index.js.map` and `*/index.js.map`. The former matches a longer suffix of the expected path, so that one should be picked.

**Comment by loewenheim** [comment]
See https://github.com/getsentry/sentry-cli/pull/1663 for an attempt at a solution.
