### ISSUE TITLE
Monitor for upload issues

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1665]
Recently there was an incident where users could not upload sourcemaps to Sentry, but this did not manifest as an upload error. Instead, the server replied that it already had all necessary data and nothing needed to be uploaded.

We should think of a way to monitor for uploads failing in such a seemingly-benign way.

**Comment by szokeasaurusrex** [comment]
@loewenheim, is this issue resolved by the sourcemaps upload `--strict` mode we introduced in #1829? If not, can you please clarify the problem that this issue intends to resolve?

**Comment by szokeasaurusrex** [comment]
> [@loewenheim](https://github.com/loewenheim), is this issue resolved by the sourcemaps upload `--strict` mode we introduced in [#1829](https://github.com/getsentry/sentry-cli/pull/1829)? If not, can you please clarify the problem that this issue intends to resolve?

I discussed with @loewenheim offline, we have decided that the functionality introduced in #1829 closes this issue
