### ISSUE TITLE
Sentry-Cli installing wrongly depending on method

### ISSUE THREAD

**Issue by CommanderRedYT** [getsentry/sentry-cli#1668]
### Environment

What version of the CLI and what OS are you running?

Linux 5.17.0-rc5-1-mainline GNU/Linux (archlinux)
NextJS **v13.4.3**

**package.json**:
```jsonc
{
  //...
  "dependencies": {
    //...
    "@sentry/cli": "^2.19.4"
  }
}
```

### Steps to Reproduce

1. `yarn add @sentry/cli`
2. `yarn sentry-cli -V` (Works)
3. `rm -rf node_modules`
4. `yarn sentry-cli -V` (Not found printed by yarn)
5. `yarn --frozen-lockfile --production --ignore-scripts`
6. `yarn sentry-cli -V` (See Logs below)

### Expected/Actual Result

No difference / cli working. For now, at least for CI/CD, i will just run the `yarn add @sentry/cli` command after yarn install as it is the only package causing issues.

### Logs

```sh
[foo@archlinux ~/somewhere] $ yarn sentry-cli -V
yarn run v1.22.19
$ /home/foo/somewhere/node_modules/.bin/sentry-cli -V
Error: spawn /home/foo/somewhere/node_modules/@sentry/cli/sentry-cli ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/foo/somewhere/node_modules/@sentry/cli/sentry-cli',
  path: '/home/foo/somewhere/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [ '-V' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also, when first making a copy of the `node_modules` folder to `node_modules.bak`, then running `yarn add @sentry/cli` and then diffing them, this is the result:

```sh
[foo@archlinux ~/somewhere] $ diff -qr node_modules node_modules.bak/
Files node_modules/.yarn-integrity and node_modules.bak/.yarn-integrity differ
Only in node_modules/@sentry/cli: sentry-cli
```

**Comment by kamilogorek** [comment]
CLI requires `postinstall` script to run in order to detect correct environment and fetch appropriate binary.
When you are using `--ignore-scripts`, you prevent it from being installed, making binary not present during runtime, effectively failing when it's executed.
