### ISSUE TITLE
Errors are printed to stdout instead of stderr?

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry-cli#168]
I need to run sentry in a situation where connection is often lost. I'm trying:

    sentry-cli send-event -m "Hello from Sentry" || echo sentry failed do something else

I purposely disconnect the device from the Internet so `sentry-cli` will fail. It outputs an error but it seems an error isn't triggered because my `echo` doesn't run.

**Comment by jan-auer** [comment]
Fix will be released with `1.26.0`
