### ISSUE TITLE
Sourcemaps explain always complains about abs_path not being a url with @sentry/node

### ISSUE THREAD

**Issue by tonttu** [getsentry/sentry-cli#1684]
### Environment

MacOS, sentry-cli 2.19.4

### Steps to Reproduce

I created a simple node-js typescript project:
```typescript
import * as Sentry from "@sentry/node";

Sentry.init({
  dsn: <dsn>
  release: "qwerty",
  tracesSampleRate: 1.0,
});

const transaction = Sentry.startTransaction({
  op: "test",
  name: "My First Test Transaction",
});

setTimeout(() => {
  try {
    const foo: any = undefined;
    foo.qwerty();
  } catch (e) {
    Sentry.captureException(e);
  } finally {
    transaction.finish();
  }
}, 99);
```
I compiled it with `tsc` using the following tsconfig:
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "inlineSources": true,
    "sourceRoot": "/",
    "outDir": "dist",
  }
}
```
Added debug ids and uploaded the source maps:
```sh
sentry-cli releases new qwerty
sentry-cli sourcemaps inject --release qwerty dist
sentry-cli sourcemaps upload --release qwerty dist
```
Finally I crashed the application and examined the result:
```
node dist/main.js
sentry-cli sourcemaps explain <id>
```
### Expected/Actual Result

Since this issue appears on the web UI correctly with the source maps applied, I would expect `sourcemaps explain` to pass without errors. However, it says:
```
✔ Fetched data for event: <id>
✔ Event has release name: qwerty
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Event exception stacktrace selected frame (0) has incorrect abs_path (valid url is required). Found /main.ts
```

This line of code assumes that `abs_path` is a valid URL: https://github.com/getsentry/sentry-cli/blob/master/src/commands/sourcemaps/explain.rs#L112, but, the JSON file uploaded to Sentry has file path instead of url in abs_path:
```json
            {
              "function": "Timeout._onTimeout",
              "module": "main",
              "filename": "/main.ts",
              "abs_path": "/main.ts",
```

It doesn't sound right that the abs_path should be a url when we are talking about node.js application here. The system seems to be working with it being just a file path, but this check prevents debugging other sourcemaps issues, since it always fails here.

**Comment by tonttu** [comment]
It seems that there is an integration [RewriteFrames](https://docs.sentry.io/platforms/node/configuration/integrations/pluggable-integrations/#rewriteframes) that seems to mangle the filenames before uploading to make `abs_path` a url. Enabling that fixes this particular error and the uploaded JSON now looks like:

```json
            {
              "function": "Timeout._onTimeout",
              "module": "main",
              "filename": "app:///main.js",
              "abs_path": "app:///main.js",
```

I guess this integration is just mandatory when using `@sentry/node`?

**Comment by kamilogorek** [comment]
It looks like a valid scenario, and effectively bug to me. Thanks for reporting.

**Comment by pietrodn** [comment]
The error is still there. I had to use the `RewriteFrames` integration, or Sentry would not accept the source maps.
```js
new RewriteFramesIntegration({ root: path.resolve("./dist") }),
```

**Comment by kamilogorek** [comment]
We are currently in the process of moving this whole logic directly to the UI and API endpoint, so the command itself might in some cases be misleading, I agree.
Once we move it there, the CLI will be modified to use the endpoint directly, so that both places give consistent results.

In the case of node, it's indeed a false-positive and we already updated that logic in the UI itself.

**Comment by klaa97** [comment]
@szokeasaurusrex Even though sourcemaps explain has been deprecated, it is still the suggested way of debugging source maps upload (https://docs.sentry.io/platforms/javascript/guides/node/sourcemaps/troubleshooting_js/). Is there a replacement?
