### ISSUE TITLE
sentry-cli inject angular 16.1.5 crash bundle

### ISSUE THREAD

**Issue by moczix** [getsentry/sentry-cli#1689]
### Environment

"@sentry/cli": "^2.19.4",
"@angular/core": "16.1.5",

os: ubuntu 23.04

### Steps to Reproduce

i upgraded my packages, to newest angular 16.1.5 and now when im running sentry-cli sourcemaps inject path it was crash my app, it inject JS code where it not suppose to.

Before:
![image](https://github.com/getsentry/sentry-cli/assets/37540008/26bf920a-3cd9-4eb2-be38-938ff5a2fbcb)
after:
![image](https://github.com/getsentry/sentry-cli/assets/37540008/a69055f4-4cc2-4ea7-9cc4-9df804673077)

### Expected/Actual Result

it should inject JS code at the end, like in previous ng version

![image](https://github.com/getsentry/sentry-cli/assets/37540008/14f98e79-598f-4193-bd2a-9ad9ba9f5a0f)

**Comment by kamilogorek** [comment]
Tracked in https://github.com/getsentry/sentry-cli/issues/1647
