### ISSUE TITLE
Sentry-cli sourcemaps explain gives error: "Exception is already source mapped and first resolved frame points to"

### ISSUE THREAD

**Issue by kasszz** [getsentry/sentry-cli#1694]
Hey, I'm using the Sentry/nextjs package for my project.
It's all working except for my sourcemaps. I set a `SENTRY_RELEASE`, the artifacts are uploaded:
![image](https://github.com/getsentry/sentry-cli/assets/13496198/8668083b-24c5-44d4-bafb-88686513f92e)
![image](https://github.com/getsentry/sentry-cli/assets/13496198/566d710a-b62e-4fd8-8a46-d680b0c3db4f)

But when I use this command `Sentry-cli sourcemaps explain <event id>` it will give me the following error: "Exception is already source mapped and first resolved frame points to".

I tried the steps in on the troubleshooting page but to be honest, I'm not sure what I have to do :P
When I download an artifact with the .map with it and run through the "Verify your source maps work locally" step gives back:
`{ source: null, line: null, column: null, name: null }` But I couldn't find what to do then.

Hopefully you can help me because I've been bashing my head against this problem for 10 hours now :'(

Thank you in advance!

**Comment by kasszz** [comment]
The plot thickens...
Apparently it uploads some files with hash and some not, maybe that is a clue?
![image](https://github.com/getsentry/sentry-cli/assets/13496198/e0bc41ec-de4a-4d68-bbc0-4b7ff2681288)

**Comment by kamilogorek** [comment]
Can you provide a shareable link to one of non-mapped events?

**Comment by mindrunner** [comment]
I am having a very similar issue. No `nextjs`, tho. Just a nodejs/typescript application.

How can we provide "sharable" links?

**Comment by stellaatsentry** [comment]
Will be assisting @mindrunner through [Zendesk](https://sentry.zendesk.com/agent/tickets/99309).

**Comment by mindrunner** [comment]
My ticket was closed before the issue got resolved :(

**Comment by stellaatsentry** [comment]
Hi @mindrunner, Zendesk automatically set the ticket as solved because we did not receive a reply within 96 hours. We apologize for the confusion this caused, and we are actively working on improving this experience. Happy to continue working towards a resolution on your ticket!

**Comment by mindrunner** [comment]
Lets talk public then! Other people seem to have issues as well.

**Comment by kamilogorek** [comment]
We are currently in the process of moving this whole logic directly to the UI and API endpoint, so the command itself might in some cases be misleading, I agree.
Once we move it there, the CLI will be modified to use the endpoint directly, so that both places give consistent results.

**Comment by loewenheim** [comment]
@Brendonovich Can you post the sourcemap in question? If you'd rather not post it publicly you can also email me at sebastian.zivota@sentry.io.

**Comment by Brendonovich** [comment]
@loewenheim here's the source + sourcemap
https://gist.github.com/Brendonovich/7be96da8b3bbca74464d396492f555c3

**Comment by loewenheim** [comment]
The sourcemap appears to work; running the following script
```javascript
var fs = require("fs"),
  path = require("path"),
  sourceMap = require("source-map");

// Path to file that is generated by your build tool (webpack, tsc, ...)
var GENERATED_FILE = path.join(".", "c11bf666-a9ce-4672-9cf5-83847c812b19-45.js.map");

// Line and column located in your generated file (for example, the source
// of the error from your minified file)
var GENERATED_LINE_AND_COLUMN = { line: 30, column: 8923 };

var rawSourceMap = fs.readFileSync(GENERATED_FILE).toString();
new sourceMap.SourceMapConsumer(rawSourceMap).then(function (smc) {
  var pos = smc.originalPositionFor(GENERATED_LINE_AND_COLUMN);

  // You should see something like:
  // { source: 'original.js', line: 57, column: 9, name: 'myfunc' }
  console.log(pos);
});
```
outputs
```
{
  source: '../../../node_modules/react-dom/cjs/react-dom.production.min.js',
  line: 142,
  column: 58,
  name: 't'
}
```
What line/column are you trying to look up? The example of 1:1000 from https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-your-source-maps-work-locally won't work—line 1 looks like it was added by a bundler plugin and doesn't map to anything in the original source.

**Comment by Brendonovich** [comment]
Oh interesting, I didn't try with a different line/column, just used the example. Thanks for checking that.
I did a lookup for `168:8442` since that's in a stacktrace from Sentry and it actually worked:
<img width="398" alt="image" src="https://github.com/getsentry/sentry-cli/assets/14191578/83c2f3f9-8390-435f-8a0d-af09afbd27a5">
```js
{
  source: '../../../interface/util/Platform.tsx',
  line: 40,
  column: 8,
  name: null
}
```
Given this I'm really unsure why the CLI says 'Release has no artifacts uploaded' and the Sentry UI is not recognising the sourcemaps

**Comment by loewenheim** [comment]
`sourcemaps explain` is unfortunately not in a good state right now :/

Do you have a link to an event that fails to be symbolicated correctly I could look at?

**Comment by Brendonovich** [comment]
Here's the one I showed above:
https://spacedriveapp.sentry.io/issues/4452578008/?project=4504053670412288

**Comment by Brendonovich** [comment]
I didn't even think to check the SDK version, works perfectly now. Thanks for the help!

**Comment by loewenheim** [comment]
My pleasure!
