### ISSUE TITLE
error: Found argument 'sourcemaps' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by jaketoolson** [getsentry/sentry-cli#1696]
### Environment

Docker Image: public.ecr.aws/docker/library/node:alpine
Docker file snippet: ``RUN npm install -g @sentry/cli`` (so latest version of CLI)
React, using Create React App

### Steps to Reproduce

This only happens from within a DOCKER environment, and NO ERROR happens within my local terminal using NPM global install or homebrow.

### Expected/Actual Result

I didn't expect to see any error, and instead for the sourcemaps to be id'd and uploaded.  
The following error is what occurs when this line from package.json is run 
``error: Found argument 'sourcemaps' which wasn't expected, or isn't valid in this context``

`package.json snippet:`
 ```
 "scripts": {
    "build:prod": "NODE_ENV=production GENERATE_SOURCEMAP=true env-cmd -f ./.env react-scripts build && yarn run sentry:sourcemaps",
    "sentry:sourcemaps": "sentry-cli sourcemaps inject --org xxxxxx --project react ./build && sentry-cli sourcemaps upload --org xxxxxxx --project react ./build "
  },
```

**Comment by kamilogorek** [comment]
It appears that for some reason, v1 of CLI is installed for you. Can you do one of the following:

```
RUN npm list @sentry/cli
```

or 

```
RUN ./node_modules/@sentry/cli/sentry-cli --version
```

If possible, can you attach your `Dockerfile` or preferably some repository that can be used to reproduce this issue?

**Comment by jaketoolson** [comment]
DOCKERFILE

```
FROM public.ecr.aws/docker/library/node:alpine as base

FROM base AS pruner
WORKDIR /app
COPY package.json yarn.lock ./
RUN npm install -g json @sentry/cli
RUN apk update && apk add curl
RUN yarn install --immutable --immutable-cache --check-cache --frozen-lockfile --production;
RUN curl -sf https://gobinaries.com/tj/node-prune | sh
RUN node-prune

FROM pruner as builder

ARG BUILD_COMMAND
ENV BUILD_COMMAND=${BUILD_COMMAND}

RUN echo "-> $BUILD_COMMAND"

WORKDIR /app

COPY . .
RUN n=11; output=$(tr -cd '[:alnum:]' < /dev/urandom | head -c$n) && json -I -f package.json -e "this.name=\"${output}\""

RUN yarn install --immutable --immutable-cache --check-cache --frozen-lockfile &&  \
    yarn cache clean &&  \
    yarn run ${BUILD_COMMAND}

FROM public.ecr.aws/nginx/nginx:1.23 as runner

COPY --from=pruner /app/node_modules ./node_modules
COPY --from=builder /app/package.json /app/yarn.lock ./
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
```

Where `{BUILD_COMMAND}` would be: `build:prod`

**Comment by kamilogorek** [comment]
There you have your answer :)

```
docker-name@0.1 /app
`-- @sentry/wizard@3.8.0
  `-- @sentry/cli@1.75.2
```

You have sentry-cli installed only as a transient dependency of `@sentry/wizard`, but never installed it yourself directly.
Either add `"@sentry/cli": "^2.20.1"` to your `package.json` or change:

```
RUN yarn install --immutable --immutable-cache --check-cache --frozen-lockfile &&  \
    yarn cache clean &&  \
    yarn run ${BUILD_COMMAND}
```

to

```
RUN yarn install --immutable --immutable-cache --check-cache --frozen-lockfile &&  \
    yarn add @sentry/cli@2 &&  \
    yarn cache clean &&  \
    yarn run ${BUILD_COMMAND}
```

**Comment by jaketoolson** [comment]
Interesting, because of runnning the version check above, it was immediately apparent to me that although I first install the latest version of the CLI, it's overridden later in my DOCKERFILE when my react app installs everything in package.json, which includes the sentry/wizard, which has a dependency of sentry/cli:1.75.2 and is installed, overridding the first one when things are moved via docker.

I removed the sentry/wizard from the package.json depedency (not sure why I left it there haha) and voila, we're up and running.

**Comment by jaketoolson** [comment]
Haha, sorry, didn't see the reply while I was writing my update! :) We both agree, thanks for your help!
