### ISSUE TITLE
Sometimes upload is very slow

### ISSUE THREAD

**Issue by mstawick** [getsentry/sentry-cli#17]
When uploading .js and sourcemap files (~15MB in total, 16 files), uploads seem to stall and take several minutes to complete. Other times same files upload in less then 30s.

**Comment by mitsuhiko** [comment]
Does this happen against sentry.io?

**Comment by mstawick** [comment]
@mitsuhiko Yes, it does. I'm having a conversation with @mattrobenolt about this as well.

**Comment by mitsuhiko** [comment]
I really cannot reproduce this at all. Do you have some additional information you can share?

**Comment by mstawick** [comment]
No. The other day it was happening on regular basis, along with random 413 errors. Since then I haven't seen it once. So maybe just close it. I've enabled logging (latest version with all the headers etc.), so if it happens again I'll be able to provide more info.

**Comment by mitsuhiko** [comment]
I'm going to close it for now. Keep me posted if it happens again.
