### ISSUE TITLE
2.20.2     404 - Not Found

### ISSUE THREAD

**Issue by pengfeir** [getsentry/sentry-cli#1702]
### Environment

What version of the CLI and what OS are you running?

### Steps to Reproduce

What you did?

### Expected/Actual Result

What you thought would happen and what actually happened?
https://cdn.npmmirror.com/binaries/sentry-cli/2.20.2/sentry-cli-Linux-x86_64
<img width="807" alt="image" src="https://github.com/getsentry/sentry-cli/assets/22837913/f7042c0f-f747-4b8a-ab1b-4a172ee02466">
### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

**Comment by kamilogorek** [comment]
Works for me. Maybe it was just a fluke?

<img width="713" alt="image" src="https://github.com/getsentry/sentry-cli/assets/1523305/56467254-c156-4d6f-94c1-37de104eec78">

**Comment by kamilogorek** [comment]
We had a small release hiccup, the latest release should be fixed.
