### ISSUE TITLE
Sentry `org:ci` scope does not allow sending commits with Release Creation

### ISSUE THREAD

**Issue by rvanlaak** [getsentry/sentry-cli#1707]
### Environment

Docker image `getsentry/sentry-cli` on Codefresh CI.

### Steps to Reproduce

Running the following script, with having an organization Auth Token set on `SENTRY_AUTH_TOKEN` does throw an exception on not having sufficient privileges to set release commits.

### Expected/Actual Result

The documentation on the Auth Tokens creation page is clear that "Organization auth tokens currently have a limited set of scopes.

We would expect everything that would fall under CLI releases "sub-namespace" to be possible with the `org:ci` scope.

An alternative could be that the release is not created yet, but in that situation an http status 404 would be expected on the command output (now is a 403) instead.

#### Temporary fix

We now fixed it temporarily by creating a user auth token.

### Logs

<img width="979" alt="image" src="https://github.com/getsentry/sentry-cli/assets/2707563/a525b41d-e170-49b8-a2db-c42e21c95730">

**Comment by mydea** [comment]
Hey there,

thanks for reporting this. Probably we missed a place to update to allow org auth token access - we'll check it out and update this to make sure access works as expected. We'll keep you posted!

**Comment by mydea** [comment]
So after checking, these are endpoints used, and their current acceptance of `org:ci` scope (=Org Auth Tokens):

* `/organizations/{org}/releases/{version}/` ✅ 
* `/projects/{org}/{project}/releases/{version}/` ✅ 
* `/projects/{org}/{project}/releases/` ✅ 
* `/organizations/{org}/releases/` ✅ 
* `/organizations/{org}/repos/` 🚫  --> updating this
* `/organizations/{org}/releases/{version}/previous-with-commits/` ✅

**Comment by rvanlaak** [comment]
Given the related PR is merged, will that automatically lead to a new `getsentry/sentry-cli` Docker image? Am eager to test running our pipeline through an organization token.

**Comment by mydea** [comment]
Hey, this is just a change in sentry, not in cli, so once the merged PR is deployed (hard to say how long that will take, max ~1 hour) this should "just work". Could you wait a bit and give it a try later today, and if it still doesn't work let us know - but hopefully your problem should be resolved :)
