### ISSUE TITLE
Add integrations tests that run against the sentry repository

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry-cli#1709]
This is an [INC-427](https://www.notion.so/sentry/INC-427-Source-Maps-missing-chunk-functionality-not-enabled-on-the-server-while-CLI-was-rolled-out-c6d063f4ff674852af7dcb38123d39fc) post mortem action item.

[INC-427]: https://getsentry.atlassian.net/browse/INC-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by loewenheim** [comment]
After discussion with @ashwoods, we're shelving this for now. It's hard to imagine a scenario where having these tests would have prevented the incident in question, where a current version of `sentry-cli` was incompatible with an older version of `sentry`.
