### ISSUE TITLE
Recent changes to inject debug id code are making the process take a very long time 

### ISSUE THREAD

**Issue by vitorlopez** [getsentry/sentry-cli#1710]
### Environment

What version of the CLI and what OS are you running?
2.20.4

### Steps to Reproduce

- We have an Angular app that's not that big but we have 157 js files generated in the final bundle. Some of them are kinda large.

What you did? 
- Upgraded package to latest version 2.20.4

### Expected/Actual Result

What you thought would happen and what actually happened?
Injecting debug ids to be super fast like usual

### Logs
```
Step #3: > Found 157 files
Step #3: > Analyzing 157 sources
Step #3: > Injecting debug ids

(....)

Step #3: Finalized release 2f98c493-b632-46e2-ab90-d47a0ba4c066
Step #3: Done in 637.26s.
```

For now I had to downgrade to version 2.20.3, because the new version it's taking ~10 minutes just to inject the ids. The same process takes 2 seconds on previous version.

**Comment by vitorlopez** [comment]
Related to this https://github.com/getsentry/sentry-cli/pull/1693

**Comment by kamilogorek** [comment]
Is this CI or your local machine? And what OS? Would you be able to provide a repro case in some way maybe?

I just verified it locally on the Sentry itself, and I cannot reproduce it nowhere close to those numbers:

```
time sentry-cli sourcemaps inject dist
> Searching dist
> Found 1620 files
> Analyzing 1620 sources
> Injecting debug ids
> ...
sentry-cli sourcemaps inject dist  1.77s user 0.24s system 71% cpu 2.790 total
```

**Comment by AlexGanzer** [comment]
We have same issue on CI with version of Sentry CLI 2.20.4

```
-> Analyzing 41 sources
-> Injecting debug ids

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
Sentry CLI  version 2.20.3 works correctly

**Comment by vitorlopez** [comment]
I tested on a CI environment running Linux with Node 18 and my local environment on Mac running Node 18. Same results for both.

**Comment by kamilogorek** [comment]
Do you think you'd be able to bisect your build files to find one that takes the longest? And then provide it (can be privately) for us to use as a repro case?

**Comment by kamilogorek** [comment]
Works for me, hit me up at kamil@sentry.io

**Comment by kamilogorek** [comment]
@vitorlopez got your file, but still cannot repro this locally for some reason. We will need to spend some more time investigating this.

```
➜  ~/Downloads time sentry-cli sourcemaps inject sentry-file.js
> Searching sentry-file.js
> Found 1 file
> Analyzing 1 sources
> Analyzing completed in 0.045s
> Injecting debug ids

Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    9af793d1-4b7d-5421-b284-9d6663720e1e - sentry-file.js

sentry-cli sourcemaps inject sentry-file.js  0.06s user 0.01s system 20% cpu 0.325 total
➜  ~/Downloads sentry-cli --version
sentry-cli 2.20.4
```

It's still useful, as the injection is not great there, so thanks for the repro!

**Comment by kamilogorek** [comment]
Even when trying to stress the cli with way more files, it doesnt budge:

```
➜  ~/repro ls -l tmp | wc -l
    2001
➜  ~/repro du -sh tmp
1.9G  tmp
➜  ~/Desktop time sentry-cli sourcemaps inject tmp
> Searching tmp
> Found 2000 files
> Analyzing 2000 sources
sentry-cli sourcemaps inject tmp  26.29s user 1.05s system 98% cpu 27.862 total
```

**Comment by vitorlopez** [comment]
If i delete all the other files and leave just this one, the process takes ~1 minutes (not 10 like I mentioned before, sorry for the confusion). But since I have several similar files the entire process takes 10 minutes. I have no idea what causes these files to take a lot longer than the others. The "Analyzing" step is really quick though:

```
> Found 157 files
> Analyzing 157 sources
> Analyzing completed in 0.065s
> Injecting debug ids
```

For now we'll keep using 2.20.3 where this process is incredibly fast.  I'm sure there were good reasons for this change but version 2.20.3 works really well for us. 

I hope you guys can find whatever is causing this issue. I'm pretty sure it'll happen for more angular apps using sentry-cli directly. Maybe it works with the webpack plugin, but since we're using esbuild for this app we can't really use the webpack plugin.

**Comment by mtariqsajid** [comment]
I test myself  2.20.3 is blazingly fast 2.20.4 is so slow it took around 320s to just make build before uploading to sentry

**Comment by wrongsahil** [comment]
We're also facing similar issue with 2.20.4. It almost took 1hr now for `sentry-cli sourcemaps inject ./build` to complete. Pinning it to `2.20.3` using `curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.20.3" sh` fixed the issue for now.

**Comment by ashbadger** [comment]
Just echo-ing what others have posted.

On `2.20.4`, I'm experiencing the `sourcemaps inject` command taking roughly 60m for one of my codebases. The command hangs and nothing is logged during this hanging when I set Sentry logging to info mode via `SENTRY_LOG_LEVEL=info`.

I pinned the version to `2.20.3` and the command completed in <1s.

**Comment by kamilogorek** [comment]
It has to be something build-specific. I just tried it out on 5k+ files of complex next.js app (3.2GB of build data in total) and the whole injection + upload took <10sec.
I tested this on an OSX arm build though, so will try to replicate this on linux image now.

**Comment by kamilogorek** [comment]
Still no luck. Tried 2 different OSs with 2 different architectures.

```
Darwin 14a462762ea4 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
Linux 07a361863ef4 6.4.7-orbstack-00058-g16f30394f179 #1 SMP Sun Jul 30 06:52:14 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
Linux cbab2a30bed5 6.4.7-orbstack-00058-g16f30394f179 #1 SMP Sun Jul 30 06:52:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kamilogorek** [comment]
Should be fixed in `2.20.5`. Please give it a go and let me know!

**Comment by vitorlopez** [comment]
it's 10000% faster now @kamilogorek . Great job!!!!

**Comment by mtariqsajid** [comment]
> it's 10000% faster now @kamilogorek . Great job!!!!

which version ```2.20.4``` ?

**Comment by kamilogorek** [comment]
`2.20.5`

**Comment by vitorlopez** [comment]
> 
@mtariqsajid 
I tested with 2.20.5 and it took just a few milliseconds to run.

Just for reference, previous version was taking 10 minutes.

**Comment by vitorlopez** [comment]
> > it's 10000% faster now @kamilogorek . Great job!!!!
> 
> which version `2.20.4` ?

I tested with 2.20.5 and it took just a few milliseconds to run.

Just for reference, previous version was taking 10 minutes.

**Comment by andrew-canvette** [comment]
I am running into this on `2.20.5` but not on `2.20.3`.

```
# 2.20.5

> Searching ./build/
> Found 4 files
> Analyzing 4 sources
> Analyzing completed in 0.023s
> Injecting debug ids

Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    fb57bf98-3bf0-5a04-9ced-1a5d17326bc9 - ./build/index.js
    6dfca1d2-1719-5484-a80b-cd8217f6c609 - ./build/server.js
  Modified: The following sourcemap files have been modified to have debug ids
    fb57bf98-3bf0-5a04-9ced-1a5d17326bc9 - ./build/index.js.map
    6dfca1d2-1719-5484-a80b-cd8217f6c609 - ./build/server.js.map


real    0m52.593s
user    0m8.632s
sys     0m43.897s

```

```
# 2.20.3

> Searching ./build/
> Found 4 files
> Analyzing 4 sources
> Analyzing completed in 0.022s
> Injecting debug ids

Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    202631ef-9fea-5c74-ba9f-b9612f569a8b - ./build/index.js
    1555969b-1e62-5cde-97be-c6e737569f12 - ./build/server.js
  Modified: The following sourcemap files have been modified to have debug ids
    202631ef-9fea-5c74-ba9f-b9612f569a8b - ./build/index.js.map
    1555969b-1e62-5cde-97be-c6e737569f12 - ./build/server.js.map


real    0m0.262s
user    0m0.226s
sys     0m0.036s
```

I'm using a couple google SDKs (`@google-cloud/tasks` and `@google-cloud/secret-manager`) which double my bundle size from 1.8mb to 3.6mb.

If I remove them for `2.20.5`, the speed increases, but still is not as fast as `2.20.3`.


```
# Without google SDKs

> Searching ./build/
> Found 4 files
> Analyzing 4 sources
> Analyzing completed in 0.011s
> Injecting debug ids

Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    2044e179-e503-5397-8da2-c744798423ba - ./build/index.js
    9d51c745-d6eb-5d55-89e7-f5d0d56298ba - ./build/server.js
  Modified: The following sourcemap files have been modified to have debug ids
    2044e179-e503-5397-8da2-c744798423ba - ./build/index.js.map
    9d51c745-d6eb-5d55-89e7-f5d0d56298ba - ./build/server.js.map


real    0m3.341s
user    0m0.779s
sys     0m2.560s
```

**Comment by kamilogorek** [comment]
cc @loewenheim

**Comment by loewenheim** [comment]
That 2.20.5 is slower than 2.20.3 is not in itself surprising—injection in 2.20.3 was implemented in a very fast, but incorrect way. The salient question is why those SDKs blow up the time so much. Do you have any example data you can share?

**Comment by loewenheim** [comment]
Thank you very much!
