### ISSUE TITLE
unsupported debug image type

### ISSUE THREAD

**Issue by tranan89** [getsentry/sentry-cli#1712]
### Environment

What version of the CLI and what OS are you running?

I use this command in our dockerfile: RUN curl -sL https://sentry.io/get-cli/ | bash

### Steps to Reproduce

We first do this in dockerfile

`RUN sentry-cli sourcemaps inject ${STATIC_FILES_PATH}`

Then in GH workflows we do

```
sentry-cli releases new $SENTRY_RELEASE --project flow-browser
sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps ./sentry-static-files/static --url-prefix '~/static' --dist $SENTRY_DIST --project flow-browser --ignore *date-fns_locale*
sentry-cli releases finalize $SENTRY_RELEASE --project flow-browser
```

### Expected/Actual Result

I'm not sure what is actually broken since I can see the sourcemaps, but I guess that is because it fallbacks to using the path instead of the debug id?
I have confirmed since before that the debug ids are inserted correctly into our artfiacts since latest release according to my previous reported issue that is now closed: https://github.com/getsentry/sentry-cli/issues/1681

I expect to get rid of the error in sentry ui

<img width="1197" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/cedbaf9e-38c1-488e-a328-b892eff9c6e8">

Js file contains:
`//# debugId=0fd40d70-4ce0-583a-8b47-32ce9e9e61cb`
Sourcemap contains:
`"debug_id":"0fd40d70-4ce0-583a-8b47-32ce9e9e61cb"`

**Comment by kamilogorek** [comment]
Is this SaaS or on-premise instance?

**Comment by tranan89** [comment]
> Is this SaaS or on-premise instance?

on-premise

**Comment by kamilogorek** [comment]
The minimum version of Sentry that supports artifact bundles is `[23.3.1](https://github.com/getsentry/sentry/releases/tag/23.3.1)`. Do you happen to host an older one by any chance?

**Comment by tranan89** [comment]
Alright, we have `23.1.1` so Ill get back once we have updated our servers then 👍

**Comment by tranan89** [comment]
This was resolved with latest version 👍

**Comment by jiereal** [comment]
Can't upgrade Sentry! Is there any other solution?
