### ISSUE TITLE
Invalid Absolute Path URL

### ISSUE THREAD

**Issue by tranan89** [getsentry/sentry-cli#1719]
### Environment

What version of the CLI and what OS are you running?

I use this command in our dockerfile: RUN curl -sL https://sentry.io/get-cli/ | bash

### Steps to Reproduce

We first do this in dockerfile

`RUN sentry-cli sourcemaps inject ${STATIC_FILES_PATH}`

Then in GH workflows we do

```
- name: Upload services static files to Sentry UK
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_PROD_UK }}
          SENTRY_URL: x
          SENTRY_PROJECT: flow-node
        run: |
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps ./sentry-static-files --dist $SENTRY_DIST
          sentry-cli releases finalize $SENTRY_RELEASE
```

### Expected/Actual Result

I'm not sure what is actually broken since I can see the sourcemaps, but I suspect that there is some kind of conflict with our different services/apps reusing the same `flow-node` project. But since `url-prefix` isn't set and we also have debug ids I thought it would be fine?

I expect to get rid of the error in sentry ui

<img width="1200" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/ecc1db07-019f-43bf-8353-5ca34b24ccd8">

We updated to latest sentry server a couple of weeks ago

**Comment by loewenheim** [comment]
Do you have a link to the event? IIRC we had cases where that warning showed up spuriously and the issue was in fact something else entirely.

**Comment by tranan89** [comment]
@loewenheim we are using sentry on premise so you won't have access to our event 😬

**Comment by loewenheim** [comment]
Can I have a look at the JSON?

**Comment by tranan89** [comment]
Sure, I will get back with the JSON in the beginning of next week. My vpn is currently down because we are changing office

**Comment by loewenheim** [comment]
Thanks!

**Comment by smeubank** [comment]
Fixed in https://github.com/getsentry/sentry/pull/54362 so upgrading to [23.8.0](https://github.com/getsentry/sentry/releases/tag/23.8.0) will make the error go away.

- Kamil
