### ISSUE TITLE
"releases files upload-sourcemaps" working, but "sourcemaps upload" not

### ISSUE THREAD

**Issue by JustDoItSascha** [getsentry/sentry-cli#1727]
### Environment

sentry-cli 2.20.5
sentry on premise 23.8.0

### Steps to Reproduce

I tried to upload sourcemaps with the commands in the docs: `sentry-cli sourcemaps upload`. The files are correctly uploaded, logs are looking all fine. But the files are not persisted and not copied to my s3 filestore.

Then I used `sentry-cli releases files upload-sourcemaps` which is working fine.

### Expected/Actual Result

I have no idea where the difference between these two commands is, but I thought they are the same. But the `sourcemaps upload` one is not working. At least I would have thought that I'm getting an error.

**Comment by loewenheim** [comment]
Hi, sorry it took me a while to get back to you. The two commands should indeed be aliases of each other. Can you check whether it works when you run `sentry-cli sourcemaps upload` twice?

**Comment by JustDoItSascha** [comment]
Ok, now it's getting weird:

1. I rebuild my project, so it has new files with other hash values, then I tried the command `sentry-cli sourcemaps upload --release test ./dist`.
2. This time the sourcemaps got indeed uploaded to my s3 space. 
3. Then I rerun the command, the files got uploaded to my s3 a second time.
4. After a couple of seconds they got deleted from my s3.
5. I retried step 1. I build my project and run the `sentry-cli sourcemaps upload --release test ./dist` command. 
6. This time they don't get uploaded.
7. I rerun `sentry-cli sourcemaps upload --release test ./dist`
8. Still no upload.
9. I delete the artifact bundle for my "test" release from ui and try it again. Still no upload.
10. I choose another release name "test2". Now something gets uploaded, but not all. All my other bundles consist of two files (1,8 MB and 8 MB). This newly updated artifact bundle has only the 1,8 MB file.

**Comment by loewenheim** [comment]
The issues with bundles not being uploaded even after you delete them remind me of these two PRs. https://github.com/getsentry/sentry-cli/pull/1726 https://github.com/getsentry/sentry/pull/55455 (they go hand in hand). The `sentry-cli` fix you can get by updating to 2.20.6 or 2.20.7, but the `sentry` fix isn't released yet.
