### ISSUE TITLE
Sourcemaps not working for server bundles

### ISSUE THREAD

**Issue by tranan89** [getsentry/sentry-cli#1728]
Hi

### Environment

What version of the CLI and what OS are you running?

I use this command in our dockerfile: `RUN curl -sL https://sentry.io/get-cli/ | bash`

### Steps to Reproduce

In dockerfile: `RUN sentry-cli sourcemaps inject ${STATIC_FILES_PATH}`

In GH Workflow:
```
sentry-cli releases new $SENTRY_RELEASE --project flow-node
sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps ./sentry-static-files/server --dist $SENTRY_DIST --project flow-node --ignore *date-fns_locale*
sentry-cli releases finalize $SENTRY_RELEASE --project flow-node
```

### Expected/Actual Result

We expect the sourcemaps to  work for our app server bundles (bundled with webpack).
They already work for our service files which aren't bundled.
They also work for our client bundles which have `--url-prefix` set though

### Logs

The bundle contains `//# sourceMappingURL=main.bef100.js.map` but no longer any `debugId`. DebugIds not being injected was sovled in a previous issue that I created but it has perhaps resurfaced in a different form? https://github.com/getsentry/sentry-cli/issues/1681

In the sourcemap `debugId` seems to have been replaced by `mappings`?
`"mappings":"yKAIA,MAAMA,GAA0BC,EAAAA,EAAAA,IAAS,CAADC,SAAA,GAAAC,YAAA,6BAAAC,QAAAC,GAAA,MAAAC,EAAA,KAAAC,QAAAF,GAAA,gBAAAH,SAAAI,MAAAE,EAAAA,EAAAF,EAAA,EAAAG,YACvCA,IACQ,wRACPC,aAAAL,GAAA,MAAAC,EAAA,KAAAC,QAAAF,GAAA,YAAAH,....`

**Comment by loewenheim** [comment]
Hi, thank you for the report.

> The bundle contains //# sourceMappingURL=main.bef100.js.map but no longer any debugId.

By this, do you mean that the source file contains a source mapping URL comment, but no debug id? Or is it the sourcemap that doesn't have a debug id?

**Comment by tranan89** [comment]
> Hi, thank you for the report.
> 
> > The bundle contains //# sourceMappingURL=main.bef100.js.map but no longer any debugId.
> 
> By this, do you mean that the source file contains a source mapping URL comment, but no debug id? Or is it the sourcemap that doesn't have a debug id?

The bundle contains only `sourceMappingURL` and the sourcemap only contains `mappings`.
So there is no `debugId` in either file

**Comment by tranan89** [comment]
@loewenheim any updates?

**Comment by loewenheim** [comment]
Sorry, nothing so far. Do you by any chance have a repo you can share that exhibits this behavior? The output of `sentry-cli sourcemaps inject` (which shows which source/sourcemap files had debug ids added) would also be helpful.

**Comment by tranan89** [comment]
@loewenheim Im the one that should be sorry, it seems like my colleague broke `cli sourcemaps inject` now that I'm looking into it. Do you want to close this issue now or wait until I got the fix out and have confirmed that it is working?

**Comment by loewenheim** [comment]
No worries :)

I'll close this issue once we have confirmation.

**Comment by tranan89** [comment]
@loewenheim The issue seems to persist even though have fixed the inject so `debugId` is properly added to both files again now.

Bundle:
//# sourceMappingURL=server.bundle.js.map
//# debugId=1281bf60-36aa-5658-9915-7d70521bd06c
Sourcemap:
"debug_id":"1281bf60-36aa-5658-9915-7d70521bd06c"

New issue without sourcemap from above release:
<img width="1584" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/0b7c77a4-2757-471f-9fbf-64fa4f5ab084">


Btw another unrelated ux thing, it would be nice if you could see this directly without hovering. But I guess it isn't on your team. 
<img width="543" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/480abfb9-8e4f-49d9-879a-cbe4e11e4af5">

**Comment by loewenheim** [comment]
Do you have a link to that event?

**Comment by tranan89** [comment]
> Do you have a link to that event?

We have on premise hosting so sadly not

**Comment by loewenheim** [comment]
That might make this hard to diagnose :/

Can you post the JSON for the event in your screenshot (or email it to me at sebastian.zivota@sentry.io)?

**Comment by tranan89** [comment]
@loewenheim I mailed you now 👍

**Comment by loewenheim** [comment]
How was that event generated? What SDK and version are you using? The event doesn't contain the `debug_meta/images` field, which is used to associate files with debug ids. This may indicate an old SDK.

**Comment by tranan89** [comment]
@loewenheim "@sentry/node": "7.49.0",

**Comment by loewenheim** [comment]
Can you try updating the SDK to a version ≥ 7.56 and report back?

**Comment by tranan89** [comment]
> Can you try updating the SDK to a version ≥ 7.56 and report back?

Sure 👍

**Comment by tranan89** [comment]
@loewenheim It still doesn't work after updating to "@sentry/node": "7.68.0"
I mailed you json again, replying on the latest mail

**Comment by tranan89** [comment]
@loewenheim have u been able to look into the json I sent before?

**Comment by loewenheim** [comment]
Sorry, it got lost in the shuffle a bit. I'll follow up.

**Comment by lforst** [comment]
@tranan89 Can you look at https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/ and verify all of the steps there? Thanks!

**Comment by tranan89** [comment]
@lforst I tried using the provided node snippet in `Verify your source maps work locally` but it didn't work, other than that yes.
But if the sourcemap was completely broken then we wouldn't see the stacktrace like u can see in the image.
`dist/server` is the bundle and then the `webpack:` part shows the correct path

<img width="1170" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/497335b1-e36e-4bc3-8661-7666d25d82e9">

**Comment by lforst** [comment]
@tranan89 Sorry yeah the `sentry-cli sourcemaps explain` command is a bit broken at the moment if you use debug IDs. Please follow the manual steps.

Additionally, the "you're not a computer..." modal is also broken on your self-hosted version. If you upgrade it should be gone.

**Comment by tranan89** [comment]
> @tranan89 Sorry yeah the sentry-cli sourcemaps explain command is a bit broken at the moment if you use debug IDs. Please follow the manual steps.

@lforst that is what I tried? 😅 

<img width="786" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/10d5da7a-6542-48dd-ae13-7f1539e95eb6">

> Additionally, the "you're not a computer..." modal is also broken on your self-hosted version. If you upgrade it should be gone.

We upgraded our servers not long ago due to exactly this, so we are on 23.8.
I think it is correct that it shows no though since the stacktrace isn't properly displayed? Only the paths

**Comment by lforst** [comment]
@tranan89 did you verify _all_ of the steps on that page?

**Comment by tranan89** [comment]
@lforst it doesn't feel like you are reading my comments... I already answered you here https://github.com/getsentry/sentry-cli/issues/1728#issuecomment-1750101797

**Comment by tranan89** [comment]
@lforst example stacktrace from production with working sourcemap that does not work display properly sentry

So for example this part is properly extracted form the sourcemap `/patient-app/src/app/utils/paths.js:16:9` but perhaps the part before `/var/app/applications/patient-app/dist/server/webpack:` confuses sentry or something? I'm not sure why webpack causes the stacktrace to be displayed in this way 🤔 

```
Error: Requested invalid URL: /d-logo.png, message: /d-logo.png doesn't contain mainOrg and subOrg
    at getOrgsFromPath (/var/app/applications/patient-app/dist/server/webpack:/patient-app/src/app/utils/paths.js:16:9)
    at index (/var/app/applications/patient-app/dist/server/webpack:/patient-app/src/server/serverSideRender.js:57:34)
    at exports.Manager.execute (/var/app/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
    at Object.internals.handler (/var/app/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/var/app/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/var/app/node_modules/@hapi/hapi/lib/request.js:370:68)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Request._execute (/var/app/node_modules/@hapi/hapi/lib/request.js:280:9)
```

**Comment by lforst** [comment]
If you can share an event payload JSON from Sentry we can look at this more in-depth.

**Comment by tranan89** [comment]
Sure, here is one example, not same error as above but the stacktrace and sentry behaves the same way

[sentry_event_payload.json](https://github.com/getsentry/sentry-cli/files/12916823/sentry_event_payload.json)

**Comment by tranan89** [comment]
@lforst we do run `sourcemaps inject`, otherwise we wouldn't have `//# debugId=a8518029-0a3d-5f45-a9b0-2769d468cf4b` in our bundle and `"debug_id":"a8518029-0a3d-5f45-a9b0-2769d468cf4b"` in our sourcemap (taken from same error as the payload you looked at).

Also remember that sentry works as it should for us on our app clients + our non webpack services and all of our apps/services runs the same `sentry-cli sourcemaps inject` pipeline. It is only on the app servers `with webpack` this isn't working so I strongly believe that it has something to do with `webpack+node`

> Also you seem to have the source-map-support package installed: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-you-arent-using-the-source-map-support-package

Ahaaa, that must be it then, thx for finding 👍 
I wasn't aware that we had this package so I missed this part, sorry about that. 
I will look into removing it and if it starts working without it I'll close this issue.

> You are not bundling your dependencies. You will have to upload source + source map for your dependencies if you want to have source maps for those.

Interesting, I will keep this in mind

**Comment by tranan89** [comment]
Removing `source-map-support` solved it 🎉 
Thx for the help!

**Comment by lforst** [comment]
@tranan89 Great! Glad you could solve it.
