### ISSUE TITLE
Correctly handle source mapping URLs with query strings &c.

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1733]
So apparently source mapping URLs (as given in `//# sourceMappingURL` comments in JS source files) can contain elements such as URL query strings. This obviously presents a problem when we look for the sourcemap files in the local file system. On the other hand, we can't just completely discard this stuff either—it might be relevant when scraping the sourcemap from the internet.

I think https://github.com/getsentry/sentry-cli/blob/9f634d48fa5b2dfe0c1d3298780019548634ebfe/src/utils/sourcemaps.rs#L306 should strip away everything from a source mapping URL that would prevent finding the file in the local filesystem. Since `add_sourcemap_references` is based on this function, this would also mean that the "cleaned up" URLs end up in the sourcemap bundle metadata, which is what we want.

**Comment by rodolfoBee** [comment]
Hi @loewenheim i can see that the issue was fixed in symbolic via [809](https://github.com/getsentry/symbolic/pull/809).

Would source maps work in sentry even when the debugID is not injected in the source map file (only on the minified file) and the debugID is present in the event? (the original issue encountered by a user)

**Comment by loewenheim** [comment]
> Would source maps work in sentry even when the debugID is not injected in the source map file (only on the minified file) and the debugID is present in the event? (the original issue encountered by a user)

It might work, in the same way that sourcemaps worked before we introduced debug ids, i.e. by matching on file names. But the debug id in the minified file and in the event would not be very useful in that case.

How come the user has debug ids in minified files, but not in sourcemaps?
