### ISSUE TITLE
Make install script also upgrade?

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry-cli#174]
In the install script here https://sentry.io/get-cli/

Would it be possible to allow for upgrades? 

Currently if you already have `sentry-cli` installed it just exits.

```
if [ -f "$INSTALL_PATH" ]; then
  echo "error: sentry-cli is already installed."
  exit 1
fi
```
Would removing that code block cause any kind of problem?

That way it will just overwrite whatever you have with the latest version.

**Comment by kirkins** [comment]
Or maybe something like:

```
if [ -f "$INSTALL_PATH" ]; then
  CURRENT=$($INSTALL_PATH --version | cut -d' ' -f2)
  if(( ${VERSION} > ${CURRENT} )); then
    echo "error: sentry-cli is already installed."
    exit 1
  fi
fi
```

**Comment by jan-auer** [comment]
That would be possible, but why not just use `sentry-cli update` command in that case?

**Comment by kirkins** [comment]
I did the realize there was an upgrade command

**Comment by kirkins** [comment]
Didnt^^
