### ISSUE TITLE
‘internal server error’ when uploading debug files

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry-cli#1742]
### Environment

What version of the CLI and what OS are you running?
2.20.7

### Steps to Reproduce

What you did?

uploading debug files

### Expected/Actual Result

What you thought would happen and what actually happened?

Expected: debug files uploaded successfully 

Actual: Users reported encountering an ‘internal server error’ when uploading debug files with CLI version 2.20.7. When downgrading to version 2.20.6, the error doesn’t occur. 
### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

https://github.com/connorjclark/ZeldaClassic/actions/runs/6149328555/job/16685005508#step:32:1

**Comment by loewenheim** [comment]
Thanks for the report.

**Comment by connorjclark** [comment]
I'll provide that later this evening. If I forget, please ping me!

**Comment by loewenheim** [comment]
Should be fixed as of https://github.com/getsentry/sentry-cli/pull/1749.
