### ISSUE TITLE
Debug files missing on building Flutter Android on ubuntu

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-cli#1747]
### Environment

What version of the CLI and what OS are you running?

downloads.sentry-cdn.com/sentry-cli/2.20.6/sentry-cli-Linux-x86_64
ubuntu-22.04

### Steps to Reproduce

- Check out `sentry-dart-plugin`
- Change directory to `integration-test`
- Run `flutter pub get`
- Run `flutter build apk`
- Run `flutter build web --source-maps`
- Run `scripts/test.ps1` in `pwsh`

What you did?

File `app.so` is missing in debug symbol upload.

### Expected/Actual Result

File `app.so` is included in debug symbol upload.

What you thought would happen and what actually happened?

We wrote a integration test local server that expects certain calls from `sentry-cli`. The last run that was working reported upload of three files `app.so` and three files `libapp.so`. The first failing run found the same number of debug files overall, but reported six files `libapp.so` as uploaded and none with the name `app.so`. The apk build did produce `app.so` files. See the issue over at `sentry-dart-plugin` for more information.

[Fix ubuntu integration tests #161](https://github.com/getsentry/sentry-dart-plugin/issues/161)

### Logs

[When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

Successful Run
https://github.com/getsentry/sentry-dart-plugin/actions/runs/6140635136/job/16659855989

Failing Run
https://github.com/getsentry/sentry-dart-plugin/actions/runs/6221053336/job/16882288167

**Comment by loewenheim** [comment]
Thank you for the report, we'll take a look as soon as possible.

**Comment by loewenheim** [comment]
Sorry, I finally had a look at this. To be honest I'm not entirely clear on what the problem is. Here is part of the result of me running the reproduction:
```
Server stdout:
HTTP server listening on http://127.0.0.1:8000
To stop the server, execute a GET request to http://127.0.0.1:8000/STOP
HTTP server stopping!
Upload stats:
  CMakeDetermineCompilerABI_C.bin: count=8
  CMakeDetermineCompilerABI_CXX.bin: count=8
  app.so: count=3
  libapp.so: count=3
  libflutter.so: count=6
  libhello_santry.so: count=12
  libhello_santry.so.sym: count=4
  sentry-cli: count=2

Checking symbol server output
Verifying debug symbol upload...
  libapp.so EXISTS
  libflutter.so EXISTS
  libhello_santry.so EXISTS
  libhello_santry.so.sym EXISTS
  app.so EXISTS
  Flutter MISSING
  Runner MISSING
  libswiftCore.dylib MISSING
  libswiftCoreAudio.dylib MISSING
  libswiftCoreFoundation.dylib MISSING
  libswiftCoreGraphics.dylib MISSING
  libswiftCoreImage.dylib MISSING
  libswiftCoreMedia.dylib MISSING
  libswiftDarwin.dylib MISSING
  libswiftDispatch.dylib MISSING
  libswiftFoundation.dylib MISSING
  libswiftMetal.dylib MISSING
  libswiftObjectiveC.dylib MISSING
  libswiftQuartzCore.dylib MISSING
  libswiftUIKit.dylib MISSING
  libswiftos.dylib MISSING
```

Is this what you are expecting to see? Do you get the same results when you run the test script?
