### ISSUE TITLE
Install script fails on embedded device

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry-cli#175]
I've had no problem using the install script on my desktop.

Now I'm getting ready to deploy `sentry-cli`on to a fleet of embedded devices but I get back an error:

    bash: line 22: !DOWNLOAD_URL_LOOKUP: unbound variable

I'm not sure why this is happening yet.

Are any ENV variables being assumed? Reading through it the first time I'm not seeing any assumed environment variables.

_Running on Ubuntu 14.04
GNU bash, version 4.3.11(1)-release (arm-unknown-linux-gnueabihf)_

**Comment by kirkins** [comment]
I think I see what is happening. `DOWNLOAD_URL_LOOKUP` gets set to `SENTRY_DOWNLOAD_Linux_armv7l`.

Then the line:

     DOWNLOAD_URL="${!DOWNLOAD_URL_LOOKUP}"

Tries to map the `DOWNLOAD_URL` based on the variables set at the start:

    SENTRY_DOWNLOAD_Darwin_x86_64="https://github.com/getsentry/sentry-cli/releases/download/1.26.0/sentry-cli-Darwin-x86_64"
    SENTRY_DOWNLOAD_Linux_i686="https://github.com/getsentry/sentry-cli/releases/download/1.26.0/sentry-cli-Linux-i686"
    SENTRY_DOWNLOAD_Linux_x86_64="https://github.com/getsentry/sentry-cli/releases/download/1.26.0/sentry-cli-Linux-x86_64"
    SENTRY_DOWNLOAD_Windows_i686="https://github.com/getsentry/sentry-cli/releases/download/1.26.0/sentry-cli-Windows-i686.exe"
    SENTRY_DOWNLOAD_Windows_x86_64="https://github.com/getsentry/sentry-cli/releases/download/1.26.0/sentry-cli-Windows-x86_64.exe"

As these don't include `SENTRY_DOWNLOAD_Linux_armv7l` the error is returned.

**Comment by kirkins** [comment]
It seems there is an error message meant for this situation but it doesn't trigger because of `set -u` which causes the program to exit when an unset variable is reference.

**Comment by tonyo** [comment]
We've updated the installation script, it should fail now with a human-readable error on unsupported platforms/architectures.
