### ISSUE TITLE
Mach-O executable Debug File not uploaded on first sentry-cli call

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-cli#1760]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a Mach-O executable and a Mach-O debug companion debug files in one folder
2. Upload them to Sentry through the following command:
```
sentry-cli upload-dif -o <org_slug> -p <proj_slug> --auth-token <auth_token> path/to/folder --log-level=debug
```

### Expected Result

Both files are uploaded at the same time.

### Actual Result

The terminal logs indicate that both files were uploaded.
![image](https://github.com/getsentry/sentry/assets/81985895/bad03e53-9e46-4362-b83f-b710c2db4019)
![image](https://github.com/getsentry/sentry/assets/81985895/bca9832c-344b-4737-b074-739d7ccd6ae6)

However, only the Mach-O debug companion is uploaded.

Upon running the same command, the terminal logs indicate that there is nothing to upload
![image](https://github.com/getsentry/sentry/assets/81985895/0b34dae0-39fd-4fef-a149-ccf94c2eeb6c)
![image](https://github.com/getsentry/sentry/assets/81985895/85f63a50-6fac-4941-bc12-e995ef358058)

And that is when the Mach-O executable is actually uploaded on Sentry.

I ran this command twice with a 1 hour difference between the execution of the two:
![Screenshot 2023-09-26 at 14 10 07](https://github.com/getsentry/sentry/assets/81985895/d0671c76-2465-4a95-b092-44484ec93b95)
![Screenshot 2023-09-26 at 14 10 16](https://github.com/getsentry/sentry/assets/81985895/0cacd185-03c4-444d-ab5a-c6b7fb4b8d70)

Adding the full debug logs from both command executions in the linked internal ticket.

### Product Area

Other

### Link

https://dragonfruit-dev.sentry.io/settings/projects/unity/debug-symbols/

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1948) by [Unito](https://www.unito.io)

**Comment by loewenheim** [comment]
Apologies for the late reply , this completely slipped through the cracks. I can't manage to reproduce this; when I upload MachO debug files, everything happens at once.

**Comment by InterstellarStella** [comment]
Hi @loewenheim , I ran the command twice and one hour apart again. The first time, only the `Mach-O debug companion (x86_64)` was uploaded, and the second time, the missing `Mach-O executable (x86_64)` was uploaded. You can find them [here](https://dragonfruit-dev.sentry.io/settings/projects/unreal/debug-symbols/).

**Comment by szokeasaurusrex** [comment]
Hi @InterstellarStella, I attempted to reproduce the issue with Sentry CLI `2.23.0`, and similar to @loewenheim, both files were uploaded simultaneously for me. Could you please confirm whether you are still observing this issue with the latest Sentry CLI version?

**Comment by szokeasaurusrex** [comment]
Closing this issue, since I was unable to reproduce it, and the issue has been inactive since I asked for more information on how to reproduce the issue.

@InterstellarStella, if you are still observing this bug, please reopen the issue.
