### ISSUE TITLE
Redesign the updater

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1761]
As reported in #1759, the updater always asks for elevated permissions on Windows because the check for writeability of the exe doesn't work there. We should rebuild the updater logic to make this sound, for example by using [`self-replace`](https://crates.io/crates/self-replace).

Moreover, I believe the updater should be feature-gated so that package managers like `brew` and `npm` (and `nix` …) can install a version without it, instead of the hacky checks whether `sentry-cli` was installed via a package manager.

Open question: what do we do about auto-sudo? Integrating it with `self-replace` would require some rigmarole.

**Comment by szokeasaurusrex** [comment]
Closing in favor of #1759 and #1996
