### ISSUE TITLE
Sentry CLI could use `--url` argument when org auth token has `url: null`

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-cli#1763]
Just from a product perspective, It is entirely possible that a Sentry instance is not aware of its own location/domain. This results in org auth tokens having `url: null`.

If that is the case we still need to be able to manually set the url. Right now the CLI will just fail with a "parsing error". We should probably accept null in this case and let `url` be set manually.

This is especially important in downstream tooling like the bundler plugins.

**Comment by dmitry-cherkas** [comment]
Hi @loewenheim , is there a way to override the URL via an environment variable? I'm facing #1765 , but since I'm relying on the Gradle Plugin (`io.sentry.jvm.gradle:3.13.0`) to invoke the CLI commands, I can't pass the `--url` parameter directly.

**Comment by loewenheim** [comment]
Hi, you can indeed override the URL with the  `SENTRY_URL` variable.

**Comment by dmitry-cherkas** [comment]
Thanks for a quick answer, I'm still seeing `Failed to parse org auth token {token}` error, probably `io.sentry.jvm.gradle:3.13.0` makes use of an older CLI version that doesn't include this fix?

**Comment by loewenheim** [comment]
Yeah, I would assume so.

**Comment by dmitry-cherkas** [comment]
Ok, thx, I'll create a separate ticket for that.
