### ISSUE TITLE
Error logs not printed

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [getsentry/sentry-cli#1764]
I was tracking down an issue with my source maps not being uploaded correctly but without any error messages being shown, so I starting debugging the CLI and I found that the script at some point exited/returned without printing the error log that was there along with the `return` statement. 

I might be doing something wrong or expecting something wrong of the CLI, but I created this [repro](https://github.com/jenskuhrjorgensen/sentry-test-logger/tree/main) and described it below and I hope something is wrong with the CLI or at least that someone can tell me what I'm doing wrong or why the `utils_1.logger.error` messages are not printed when the `utils_1.logger.info` messages are.

### Environment

@sentry/cli: 2.20.7
macOS: 13.5.2

### Steps to Reproduce

1. `npx react-native init SentryTestLogger`
2. `npx @sentry/wizard@latest -s -i reactNative`
3. Apply the patches found here https://github.com/jenskuhrjorgensen/sentry-test-logger/tree/main/patches. What they do is to set `map.sources = undefined` in the `ModulesCollector` to trigger an error and then duplicate all logs printed by `utils_1.logger` with a regular `console.log`:
```
diff --git a/node_modules/@sentry/react-native/dist/js/tools/ModulesCollector.js b/node_modules/@sentry/react-native/dist/js/tools/ModulesCollector.js
index 8a6e51c..b65593a 100644
--- a/node_modules/@sentry/react-native/dist/js/tools/ModulesCollector.js
+++ b/node_modules/@sentry/react-native/dist/js/tools/ModulesCollector.js
@@ -88,6 +88,7 @@ class ModulesCollector {
             }
         }
         const map = JSON.parse((0, fs_1.readFileSync)(sourceMapPath, 'utf8'));
+        map.sources = undefined
         if (!map.sources || !Array.isArray(map.sources)) {
             utils_1.logger.error(`Modules not collected. No sources found in the source map (${sourceMapPath})!`);
             return;
```
and 
```
diff --git a/node_modules/@sentry/utils/cjs/logger.js b/node_modules/@sentry/utils/cjs/logger.js
index 34f161d..7720afa 100644
--- a/node_modules/@sentry/utils/cjs/logger.js
+++ b/node_modules/@sentry/utils/cjs/logger.js
@@ -64,6 +64,7 @@ function makeLogger() {
       logger[name] = (...args) => {
         if (enabled) {
           consoleSandbox(() => {
+            console.log(`test: ${PREFIX}[${name}]:`, ...args);
             worldwide.GLOBAL_OBJ.console[name](`${PREFIX}[${name}]:`, ...args);
           });
         }
```
4. `SENTRY_LOG_LEVEL=debug npx react-native run-android --mode release` (I also tried with "info", since "debug" is not actually mentioned in the documentation (https://docs.sentry.io/product/cli/configuration/), but it was mentioned here in the issue template).

### Expected/Actual Result

I expect error logs to be always printed (and at least when running with `SENTRY_LOG_LEVEL=debug`) instead of the script just finishing in success even though something errored. 

### Logs

In below logs I print all logs twice (the ones starting with "test: " are the additional ones I added), but the original `Sentry Logger [info]` (without the "test: " prefix) is missing:

```
sentry-test-logger % SENTRY_LOG_LEVEL=debug npx react-native run-android --mode release
info JS server already running.
info Installing the app...

> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.sentrytestlogger@1.0+1_1
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release com.sentrytestlogger@1.0+1 distribution 1
> Bundled 2 files for upload
> Bundle ID: bb736e4d-0372-5211-a4fa-da76e6b975ad
> Nothing to upload, all files are on the server
> File processing complete
> Organization: test-32ecaf969
> Project: sentry-test
> Release: com.sentrytestlogger@1.0+1
> Dist: 1
> Upload type: artifact bundle

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map

> Task :app:createBundleReleaseJsAndAssets_SentryCollectModules_com.sentrytestlogger@1.0+1_1
test: Sentry Logger [info]: Reading source map from /Users/johndoe/Documents/repos/sentry-test-logger/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
Sentry Logger [info]: Reading source map from /Users/johndoe/Documents/repos/sentry-test-logger/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map

test: Sentry Logger [info]: Saving modules to /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json
Sentry Logger [info]: Saving modules to /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json

test: Sentry Logger [info]: Resolving modules from paths /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json
Sentry Logger [info]: Resolving modules from paths /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json

test: Sentry Logger [error]: Modules not collected. No sources found in the source map (/Users/johndoe/Documents/repos/sentry-test-logger/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map)!

> Task :app:installRelease
Installing APK 'app-release.apk' on '1Pixel_2_API_30(AVD) - 11' for :app:release
Installed on 1 device.

BUILD SUCCESSFUL in 23s
66 actionable tasks: 5 executed, 61 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.sentrytestlogger/.MainActivity }
```

**Comment by loewenheim** [comment]
If I understand you correctly, the problem is that the error message beginning with "Modules not collected. No sources found in the source map" doesn't show up in the logs unless you specifically log it yourself. Is that right?

**Comment by jenskuhrjorgensen** [comment]
Yes, that sounds correctly interpreted :)

**Comment by loewenheim** [comment]
Ok, in that case, this is probably not a `sentry-cli` issue. I'll pass it on to the JS team :)

**Comment by krystofwoldrich** [comment]
@jenskuhrjorgensen Thank you for the repro and detailed explanation,
from my testing, the error output is missing because the React Native CLI passes through only the `stdout` and not the `stderr`. 

When running Gradle without React Native CLI the error output shows correctly.
