### ISSUE TITLE
Failed to parse org auth token {token}

### ISSUE THREAD

**Issue by levani** [getsentry/sentry-cli#1765]
### Environment

cli version: 2.20.7
macOS 14.0

### Steps to Reproduce

I have created a self hosted version of sentry and trying to use it on my react native app. The auth token that sentry generates, has sntrys_XXXXX format. When I set this value in `sentry.properties`, in `auth.token` field and try to build the app I'm getting an error message that the token is not parsed properly.

> Failed to parse org auth token {token}

This error only goes away if I remove the underscore character, but then the auth token becomes invalid and source map files aren't uploaded!

This works fine for android but fails on ios for some reason.

### Expected/Actual Result

Source maps should be uploaded on self hosted version of sentry.

### Logs

`Failed to parse org auth token {token}` is the only error message I can see in logs.

**Comment by loewenheim** [comment]
Hi, thank you for the report. The root cause of this is likely the same as https://github.com/getsentry/sentry-cli/issues/1750.

**Comment by levani** [comment]
@loewenheim I see the related issue has already been marked as resolved 🎉 may I ask if I can already use it by updating the cli version or should I wait for the `@sentry/react-native` release?

**Comment by loewenheim** [comment]
If you use `sentry-cli` via `react-native` then you should probably wait for the SDK release.

**Comment by levani** [comment]
@loewenheim I have updated to latest cli version (2.21.2) but still getting the same error. The only thing that changed is that instead of `{token}` at the end of the error message, I'm seeing the actual token :))

**Comment by loewenheim** [comment]
Can you decode the part of the token between the `_`s with https://www.base64decode.org/ and post the output? You can redact the URL and org, it only matters if they're there or not.

**Comment by levani** [comment]
Tried to generate a new token and actually, there are two `_`s. I'll try to use this and update you if it works.
