### ISSUE TITLE
Unable to set commits with `--auto` when using complex Git flow

### ISSUE THREAD

**Issue by Wirone** [getsentry/sentry-cli#1772]
### Environment

`sentry-cli 2.21.2` run on Gitlab runner (Linux with kernel `5.15.0-46-generic`)

### Steps to Reproduce

We recently introduced process for release management in Sentry, but it does not work correctly for us.

It's too complex to reproduce it, I'll try to explain our flow "briefly". Some background: 

- we create releases in `our.app@v20231005.89cfe140` format (CalVer + short Git SHA, prefixed with "package" to match Sentry's expectation). Part after `@` represents Docker tag associated to the release, so it's easily matched. I believe it does not matter in this case, but it's in the logs, so I wanted to make it clear
- we have Git integration configured in Sentry, repository added and mapped to the project

Our process looks like:
- we clone the repo in Gitlab runner with `GIT_DEPTH=1` currently
- we run `sentry-cli releases new our.app@$APP_TAG` and `sentry-cli releases set-commits our.app@$APP_TAG --ignore-missing --auto` _before_ deploy starts
- we run `sentry-cli releases deploys our.app@$APP_TAG new -e prod` and `sentry-cli releases finalize our.app@$APP_TAG` _after_ deploy is finished

It works in general, but it seems like it always takes last 20 commits. Moreover, today I tested it with 20+ dummy commits applied straight between previous and new release just to verify it, and release was created, but again only 20 commits were bound, and these were NOT from the actual release.

I suspect that the problem is that we run deployment from `master` branch, while default branch for our repository is different (`develop`). Probably Sentry can't match `from` commit, because SHA of the commit the pipeline is run on is not present in the default branch (same as the commit from previous release).

### Expected/Actual Result

I would expect that `sentry-cli releases set-commits --auto` does something like:
- determines SHA of current commit (works OK now)
- determines SHA of previous commit (I am not sure if it works now, I see `"previousCommit":null` in the logs)
- uses configured Gitlab instance to get commits between releases, specifically `GET /projects/:id/repository/compare` [resource](https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits) using determined SHAs as from/to fields

The actual result is that commits are not determined correctly.

### Logs

```
$ sentry-cli releases set-commits our.app@$APP_TAG --ignore-missing --auto
  ...
  DEBUG   2023-10-05 12:27:44.057673649 +00:00 request POST https://sentry.io/api/0/projects/our/app/releases/
  DEBUG   2023-10-05 12:27:44.057713740 +00:00 using token authentication
  DEBUG   2023-10-05 12:27:44.057727682 +00:00 json body: {"version":"our.app@v20231005.11e2e9a7","projects":["app"]}
  ...
  DEBUG   2023-10-05 12:00:15.001576129 +00:00 response status: 201
  DEBUG   2023-10-05 12:27:44.436287845 +00:00 body: {"id":887149174,"version":"our.app@v20231005.11e2e9a7","status":"open","shortVersion":"our.app@v20231005.11e2e9a7","versionInfo":{"package":"our.app","version":{"raw":"v20231005.11e2e9a7"},"description":"our.app@v20231005.11e2e9a7","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2023-10-05T12:27:42.950702Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":6147345,"slug":"app","name":"our-app","newGroups":0,"platform":"php","platforms":["php"],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{},"userAgent":"sentry-cli/2.21.2"}

+-------------+--------------+
| Repository  | Revision     |
+-------------+--------------+
| our / app   | 11e2e9a7a6b9 |
+-------------+--------------+
  DEBUG   2023-10-05 12:27:44.436610313 +00:00 request PUT https://sentry.io/api/0/organizations/<org>/releases/our.app@v20231005.11e2e9a7/
  DEBUG   2023-10-05 12:27:44.436623514 +00:00 using token authentication
  DEBUG   2023-10-05 12:27:44.436633981 +00:00 json body: {"refs":[{"repository":"our / app","commit":"11e2e9a7a6b9de7104fc303a43e8249fe4c84f88","previousCommit":null}]}
  ...
  DEBUG   2023-10-05 12:27:48.352564809 +00:00 response status: 200
  DEBUG   2023-10-05 12:27:48.352579915 +00:00 body: {"id":887149174,"version":"our.app@v20231005.11e2e9a7","status":"open","shortVersion":"our.app@v20231005.11e2e9a7","versionInfo":{"package":"our.app","version":{"raw":"v20231005.11e2e9a7"},"description":"our.app@v20231005.11e2e9a7","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2023-10-05T12:27:42.950702Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":6147345,"slug":"app","name":"our-app","newGroups":0,"platform":"php","platforms":["php"],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{},"userAgent":"sentry-cli/2.21.2"}
```

**Comment by Wirone** [comment]
FYI: the problem also occurs when using `--commit project@[from..]to` approach - commits are not bound to the release if `from` and `to` are not part of default branch's Git tree. I had to create back-merge from `master` to `develop` and re-run the `sentry-cli` command, then commits were detected correctly. Without back-merge the command finds 0 commits, even though commit range is provided explicitly. Disappointing 😞.

It seems like cloning the repo and using `--local` is our last chance 🤷.

**Comment by Wirone** [comment]
Not much can be done on my side, but the issue remains, and would be great to see it improved.

**Comment by loewenheim** [comment]
Can you please post the full debug logs? Also, can you please try manually making a request to the Gitlab commit comparison API as detailed [here](https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits) with the commits you expect (i.e. the current HEAD and the last commit associated with the previous release) and post the output?

**Comment by loewenheim** [comment]
Closing this due to lack of response; if you need further help, please feel free to reopen.
