### ISSUE TITLE
Error: spawn /usr/src/app/node_modules/@sentry/cli/sentry-cli ENOENT in Docker (node:18.18.0-alpine)

### ISSUE THREAD

**Issue by tktres** [getsentry/sentry-cli#1776]
### Environment
I'm running a docker with Node 16 (tried also on 18) and I'm using sentry-cli (2.21.2) to upload source map on deployment.

### Steps to Reproduce

after building the project and running npm ci I'm trying to run `sentry-cli sourcemaps inject` and it fails inside the docker with the following error:
```
Error: spawn /usr/src/app/node_modules/@sentry/cli/sentry-cli ENOENT
     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
     at onErrorNT (node:internal/child_process:485:16)
     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   errno: -2,
   code: 'ENOENT',
   syscall: 'spawn /usr/src/app/node_modules/@sentry/cli/sentry-cli',
path: '/usr/src/app/node_modules/@sentry/cli/sentry-cli',

```

I tried also to run it with `npm config set unsafe-perm true` as per some advice, but it shows the same error

### Expected/Actual Result

Expected the source maps to be uploaded

### Logs

```[tasklist]
### Tasks
```

**Comment by loewenheim** [comment]
Hi, thank you for your report.

**Comment by ashwoods** [comment]
@tktres would you mind telling us which version was being installed? Thank you!

**Comment by tktres** [comment]
@ashwoods sure, it's "@sentry/cli": "^2.21.2" I'll update it also in the ticket

**Comment by tktres** [comment]
Another update I believe is important here, I'm using `node:18.18.0-alpine`

**Comment by loewenheim** [comment]
Have you tried the solutions in https://github.com/getsentry/sentry-cli/issues/1731?

**Comment by loewenheim** [comment]
Also, according to https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for, a `WORKDIR` needs to be defined, do you have that?

**Comment by tktres** [comment]
I had to remove the `--ignore-scripts` from `npm ci --ignore-scripts` and to downgrade python to 3.10
