### ISSUE TITLE
URL configuration is overridden and the Root URL of the hosted site is used directly

### ISSUE THREAD

**Issue by WilenChen** [getsentry/sentry-cli#1777]
Version: 2.21.2

.sentrylicrc
`
[defaults]
url=http://my1.com/
`

When I use `sentry-cli releases files upload-sourcemaps`, my URL configuration is overridden and the Root URL of the hosted site is used directly.
In version 1.74.3, the behavior is normal, and the CLI will use the URL I configured to complete the API calls.
In the logs, it can be seen that in version 2.x, the CLI appears to be fetching the API list from the hosted site, and the URL paths inside are absolute paths that use the root URL.

Can someone help me, please?

**Comment by loewenheim** [comment]
Hi, can you post the debug logs?

**Comment by WilenChen** [comment]
> Hi, can you post the debug logs?

@loewenheim ok, and thanks for your quick reply.

  DEBUG   2023-10-09 15:54:23.303354 +08:00 request GET http://sentry2.demo.com/api/0/projects/fee/qiye-edm-admin/releases/1.3.0-beta/files/?cursor=&checksum=1f393d1ecb201e298032b092fa3b1aa20d2f0e09&checksum=5bdec07ffc5c6e57319adb047a9c093152c035a3&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=cc7058fac3a5e7ce09bc666757de35990e3e9e45&checksum=fa72ba9a89905ad389e9cca26786166a605fd7a8
  DEBUG   2023-10-09 15:54:23.303371 +08:00 using token authentication
  DEBUG   2023-10-09 15:54:23.303375 +08:00 retry number 0, max retries: 0
  DEBUG   2023-10-09 15:54:23.355994 +08:00 > GET /api/0/projects/fee/admin/releases/1.3.0-beta/files/?cursor=&checksum=1f393d1ecb201e298032b092fa3b1aa20d2f0e09&checksum=5bdec07ffc5c6e57319adb047a9c093152c035a3&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=cc7058fac3a5e7ce09bc666757de35990e3e9e45&checksum=fa72ba9a89905ad389e9cca26786166a605fd7a8 HTTP/1.1
  DEBUG   2023-10-09 15:54:23.356016 +08:00 > Host: sentry2.demo.com
  DEBUG   2023-10-09 15:54:23.356019 +08:00 > Accept: */*
  DEBUG   2023-10-09 15:54:23.356022 +08:00 > Connection: TE
  DEBUG   2023-10-09 15:54:23.356025 +08:00 > TE: gzip
  DEBUG   2023-10-09 15:54:23.356027 +08:00 > User-Agent: sentry-cli/2.21.2
  DEBUG   2023-10-09 15:54:23.356046 +08:00 > Authorization: Bearer 1de16c10***
  DEBUG   2023-10-09 15:54:23.479954 +08:00 < HTTP/1.1 200 OK
  DEBUG   2023-10-09 15:54:23.479993 +08:00 < Server: nginx
  DEBUG   2023-10-09 15:54:23.480001 +08:00 < Date: Mon, 09 Oct 2023 07:54:23 GMT
  DEBUG   2023-10-09 15:54:23.480008 +08:00 < Content-Type: application/json
  DEBUG   2023-10-09 15:54:23.480015 +08:00 < Content-Length: 1705
  DEBUG   2023-10-09 15:54:23.480022 +08:00 < Connection: keep-alive
  DEBUG   2023-10-09 15:54:23.480028 +08:00 < Vary: Accept-Encoding
  DEBUG   2023-10-09 15:54:23.480038 +08:00 < Link: <https://sentry1.demo.com/api/0/projects/fee/admin/releases/1.3.0-beta/files/?checksum=1f393d1ecb201e298032b092fa3b1aa20d2f0e09&checksum=5bdec07ffc5c6e57319adb047a9c093152c035a3&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=cc7058fac3a5e7ce09bc666757de35990e3e9e45&checksum=fa72ba9a89905ad389e9cca26786166a605fd7a8&cursor=100:-1:1>; rel="previous"; results="false"; cursor="100:-1:1", <https://sentry1.demo.com/api/0/projects/fee/admin/releases/1.3.0-beta/files/?checksum=1f393d1ecb201e298032b092fa3b1aa20d2f0e09&checksum=5bdec07ffc5c6e57319adb047a9c093152c035a3&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=b8c17aa0ab2841df4857a039364bee0d267edd23&checksum=cc7058fac3a5e7ce09bc666757de35990e3e9e45&checksum=fa72ba9a89905ad389e9cca26786166a605fd7a8&cursor=100:1:0>; rel="next"; results="false"; cursor="100:1:0"
  DEBUG   2023-10-09 15:54:23.480174 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-10-09 15:54:23.480182 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-10-09 15:54:23.480205 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2023-10-09 15:54:23.480212 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-10-09 15:54:23.480224 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-10-09 15:54:23.480229 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-10-09 15:54:23.480235 +08:00 < Content-Language: en
  DEBUG   2023-10-09 15:54:23.480240 +08:00 < X-Frame-Options: deny
  DEBUG   2023-10-09 15:54:23.480246 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-10-09 15:54:23.480252 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-10-09 15:54:23.480258 +08:00 < X-Forwarded-Proto: http
  DEBUG   2023-10-09 15:54:23.480264 +08:00 < X-Remote-Port: 61745
  DEBUG   2023-10-09 15:54:23.481482 +08:00 response status: 200
  DEBUG   2023-10-09 15:54:23.483146 +08:00 body: []
> Bundling completed in 0.081s
> Bundled 1 file for upload
> Bundle ID: adfd53b9-85a1-557d-be02-1adf8fb9125b
> Optimizing completed in 0.002s
  INFO    2023-10-09 15:54:23.606528 +08:00 using 'gzip' compression for chunk upload
  DEBUG   2023-10-09 15:54:23.621063 +08:00 request POST https://sentry1.demo.com/api/0/organizations/fee/chunk-upload/
  DEBUG   2023-10-09 15:54:23.621341 +08:00 sending form data
  DEBUG   2023-10-09 15:54:23.621360 +08:00 using token authentication
  DEBUG   2023-10-09 15:54:23.621390 +08:00 retry number 0, max retries: 5
  DEBUG   2023-10-09 15:54:23.799621 +08:00 > POST /api/0/organizations/fee/chunk-upload/ HTTP/1.1
  DEBUG   2023-10-09 15:54:23.799682 +08:00 > Host: sentry1.demo.com
  DEBUG   2023-10-09 15:54:23.799767 +08:00 > Accept: */*
  DEBUG   2023-10-09 15:54:23.799798 +08:00 > Connection: TE
  DEBUG   2023-10-09 15:54:23.799867 +08:00 > TE: gzip
  DEBUG   2023-10-09 15:54:23.799886 +08:00 > User-Agent: sentry-cli/2.21.2
  DEBUG   2023-10-09 15:54:23.800239 +08:00 > Authorization: Bearer 1de16c10***
  DEBUG   2023-10-09 15:54:23.800259 +08:00 > Content-Length: 717468
  DEBUG   2023-10-09 15:54:23.800299 +08:00 > Content-Type: multipart/form-data; boundary=------------------------ef9b29a237fe9b60
  DEBUG   2023-10-09 15:54:23.852530 +08:00 < HTTP/1.1 400 Bad Request
  DEBUG   2023-10-09 15:54:23.852609 +08:00 < Server: openresty
  DEBUG   2023-10-09 15:54:23.852752 +08:00 < Date: Mon, 09 Oct 2023 07:54:23 GMT
  DEBUG   2023-10-09 15:54:23.852817 +08:00 < Content-Type: text/html
  DEBUG   2023-10-09 15:54:23.852934 +08:00 < Content-Length: 234
  DEBUG   2023-10-09 15:54:23.852960 +08:00 < Connection: close
  DEBUG   2023-10-09 15:54:23.853324 +08:00 response status: 400


The host I want to use is ·`sentry1.demo.com`. When getting the file list, the host is correct, but when using `chunk-upload`, the root URL is used.

**Comment by loewenheim** [comment]
> The host I want to use is ·sentry1.demo.com. When getting the file list, the host is correct, but when using chunk-upload, the root URL is used.

Sorry, I'm confused. According to this log line
```
 DEBUG 2023-10-09 15:54:23.621063 +08:00 request POST https://sentry1.demo.com/api/0/organizations/fee/chunk-upload/
```
that host seems to be used, is that not what you want?

**Comment by WilenChen** [comment]
> > The host I want to use is ·sentry1.demo.com. When getting the file list, the host is correct, but when using chunk-upload, the root URL is used.
> 
> Sorry, I'm confused. According to this log line
> 
> ```
>  DEBUG 2023-10-09 15:54:23.621063 +08:00 request POST https://sentry1.demo.com/api/0/organizations/fee/chunk-upload/
> ```
> 
> that host seems to be used, is that not what you want?

I'm sorry, what I meant was that I configured the URL as sentry1.demo.com in .sentryclirc, but when I executed 'upload-sourcemap', it used the root URL configured on my site (sentry2.demo.com).
What i want is always use the URL i configured in .sentryclirc rather than override by the root URL.

**Comment by loewenheim** [comment]
Can I ask why it matters if the root URL or the one in your `.sentryclirc` is used? I assume this is a situation where your configured URL redirects to the root URL somehow.

**Comment by WilenChen** [comment]
> Can I ask why it matters if the root URL or the one in your `.sentryclirc` is used? I assume this is a situation where your configured URL redirects to the root URL somehow.

Sorry, I forgot to reply. This is the case, we use the root URL as the URL for internal access to access the Sentry platform, and the url in `.sentryclirc `is the URL for external access. You can also understand that they are different nginx configurations.So when I use `sentrycli`, I want to use the external URL.

**Comment by loewenheim** [comment]
As per [my reply](https://github.com/getsentry/sentry-cli/issues/1784#issuecomment-1784868471) on #1784: what version of Sentry are you running? The fact that it worked with `sentry-cli` 1.74.3 indicates that this is probably the result of a bug that [was fixed](https://github.com/getsentry/sentry/pull/55350) in August, so upgrading to 23.9 or later should resolve this. Alternatively, you could set the `system.upload-url-prefix` option in your `config.yml` to `sentry1.demo.com`.

**Comment by WilenChen** [comment]
> As per [my reply](https://github.com/getsentry/sentry-cli/issues/1784#issuecomment-1784868471) on #1784: what version of Sentry are you running? The fact that it worked with `sentry-cli` 1.74.3 indicates that this is probably the result of a bug that [was fixed](https://github.com/getsentry/sentry/pull/55350) in August, so upgrading to 23.9 or later should resolve this. Alternatively, you could set the `system.upload-url-prefix` option in your `config.yml` to `sentry1.demo.com`.

Thank you very much! After upgrading my Sentry to version 23.10.1 and using the latest CLI version, it works!
