### ISSUE TITLE
cannot remove previously uploaded artifacts

### ISSUE THREAD

**Issue by lawxy** [getsentry/sentry-cli#1780]
Environment
node: v16.20.2
sentry-cli: 2.21.2
Self-hosted Sentry: 23.7.2
@sentry/webpack-plugin: ^2.8.0

Steps to Reproduce
![image](https://github.com/getsentry/sentry-cli/assets/23738528/5b9c0dfc-d049-45b8-a43d-100fbd00fb3a)
![image](https://github.com/getsentry/sentry-cli/assets/23738528/f27709b2-69d9-4281-88a7-bcbe2a6814fb)
Expected Result
The above two methods can delete previously uploaded files

Actual Result
![image](https://github.com/getsentry/sentry-cli/assets/23738528/749cd5b9-5021-439e-bc3b-67020b2a684f)
File still exists

**Comment by loewenheim** [comment]
Hi, thank you for your report. We'll look into it.

**Comment by loewenheim** [comment]
`release files delete` only deletes release bundles (the old format of sourcemap uploads). There is currently no way to delete artifact bundles from `sentry-cli`.
