### ISSUE TITLE
Add hashsums to release artifacts 

### ISSUE THREAD

**Issue by Lerentis** [getsentry/sentry-cli#1781]
Hello there,

it would be great if you could add hashsums or even better hashsums and sboms with signatures next to the release artefacts. that would enable users to validate the files consistency and detect if they were tempered with.

thanks 😃

**Comment by loewenheim** [comment]
Hi! Can you expand on what you mean by "next to the release artifacts"?

**Comment by loewenheim** [comment]
Ah, I see. Yes, that sounds like a very good idea.

**Comment by Lerentis** [comment]
@loewenheim could you maybe add the status backlog label here so the bot does not autoclose it?

**Comment by Lerentis** [comment]
@loewenheim is there any decision where the hashes should be? do you accept PRs for this?

**Comment by szokeasaurusrex** [comment]
Hi @Lerentis, I recently took over maintaining the Sentry CLI from @loewenheim.

I understand your request; however, I am unsure how useful it would be to add hash sums to the release artifacts we publish to GitHub. I believe the downloads from GitHub occur over an HTTPS connection, which should already provide protection against tampering during the download. 

Could you please explain the benefit of providing hash sums when the download already occurs over an encrypted connection?

**Comment by Lerentis** [comment]
Hi @szokeasaurusrex ,

this goes more in the direction of securing the supply chain. if TLS would be sufficient there would not be projects like [cosign](https://github.com/sigstore/cosign) or the [SLSA framework](https://slsa.dev/spec/v1.0/) :sweat_smile: 
here is one more practical example where hashsums would already be sufficient:

imagine a bad configured proxy in some environments that would claim the TCP stream to have finished but some packages are just lost, resulting in a corrupted file and lots of frustration. provided hash sums could help validate file integrity.

**Comment by szokeasaurusrex** [comment]
Okay, @Lerentis, thank you for explaining. 

In that case, I will keep this issue open on our backlog. It may take me some time to get around to implementing the change; however, we would gladly accept PRs from contributors.

The simplest way to implement this change would be by simply placing the SHA checksum of each file in the release into a single `checksums.txt` file, that we include with the GitHub release.

**Comment by szokeasaurusrex** [comment]
@Lerentis, so to be clear, you are able to work around this using the hash sums in the release registry? Adding the hash sums next to the artifacts would simply be more convenient, but you are not blocked by this, right?

**Comment by Lerentis** [comment]
@szokeasaurusrex i can confirm that i could make it work and this is not blocking. the improvement would be to use a standard format that is readable by the `sha256sum` binary instead of this json object. the location does not matter

**Comment by szokeasaurusrex** [comment]
I am closing this issue, since we already provide sha256 checksums via our release registry. We do not plan to change how we distribute SHA checksums.
