### ISSUE TITLE
Can't seem to upload .symbols (produced by `flutter build`) files to Sentry

### ISSUE THREAD

**Issue by btrautmann** [getsentry/sentry-cli#1786]
### Environment

**Sentry-cli version:** 2.21.2
**OS Version:** MacOS M1 Runner as well as locally (MacOS Ventura 13.6)

### Steps to Reproduce

1. Build Flutter application via `flutter build ipa` passing `--split-debug-info=path/to/symbols/directory`. A `.symbols` file is produced at the provided path.
2. Invoke `sentry_upload_dsym` passing `dsym_path` as the path provided in Step 1
3. See the following logs:
```console
2023-10-16T19:50:15.8691910Z [19:50:15]: > Found 0 debug information files
2023-10-16T19:50:15.8693460Z [19:50:15]: > No debug information files found
```

### Expected Result

Symbols files should be uploaded the same way native dSYMs are. In the case of our native dSYMs we see:
```console
023-10-16T19:50:16.9752320Z [19:50:16]: > Found 60 debug information files
2023-10-16T19:50:17.5732710Z [19:50:17]: > Prepared debug information files for upload
2023-10-16T19:50:21.4379140Z [19:50:21]: > Uploaded 59 missing debug information files
2023-10-16T19:50:22.1034060Z [19:50:22]: > File upload complete:
```

### Actual Result

See logs from Step 3 under **Steps to Reproduce**

### Logs

See logs from Step 3 under **Steps to Reproduce**. Application is closed source so providing all build logs isn't feasible, but happy to upload specific logs if requested!

### Additional context

I've previously opened an issue with the sentry fastlane plugin at https://github.com/getsentry/sentry-fastlane-plugin/issues/216.

You can see there that I've tried with several versions of Flutter, all producing the same output.

**Comment by loewenheim** [comment]
Hi, thank you for the report. Can you run `sentry-cli` with log level `debug` and post the output before `> Found 0 debug information files`?

**Comment by btrautmann** [comment]
> Hi, thank you for the report. Can you run `sentry-cli` with log level `debug` and post the output before `> Found 0 debug information files`?

Sure! Here we go:

```console
  DEBUG   2023-10-31 14:12:02.212745 -04:00 sentry-cli version: 2.21.2, platform: "darwin", architecture: "arm64"
  INFO    2023-10-31 14:12:02.213708 -04:00 sentry-cli was invoked with the following command line: "sentry-cli" "debug-files" "check" "--log-level=debug" "app.ios-arm64.symbols"
Debug Info File Check
  Type: elf debug companion
  Contained debug identifiers:
    > Debug ID: 00000000-0000-0000-0000-000000000000
      Arch:     arm64
  Contained debug information:
    > symtab, debug
  Usable: no (missing debug identifier, likely stripped)
  INFO    2023-10-31 14:12:02.224016 -04:00 Skipping update nagger update check
```

**Comment by loewenheim** [comment]
Ah, yeah, that'll do it. `sentry-cli` skips files with no/trivial debug id. I can't tell you why the symbol file produced by flutter is like that.

**Comment by btrautmann** [comment]
Thanks @loewenheim, I believe you're correct. I'm going to close this in favor of https://github.com/flutter/flutter/issues/138182.
