### ISSUE TITLE
Prints log message regarding SENTRY_PROPERTIES being loaded to STDERR ignoring `--log-level`

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-cli#1787]
### Environment

What version of the CLI and what OS are you running?
`master` branch, MacOS

### Steps to Reproduce

`SENTRY_AUTH_TOKEN=abc SENTRY_PROPERTIES=sentry.properties cargo run -- --log-level=error info`

### Expected/Actual Result

Prints:

```
  INFO    2023-10-30 10:42:09.096736 +01:00 Loaded file referenced by SENTRY_PROPERTIES (/Users/adinauer/repos/sentry-android-gradle-plugin/examples/android-gradle/sentry.properties)
Sentry Server: https://sentry.io
Default Organization: sentry-sdks
Default Project: sentry-android
```

Should not print the `INFO` log. This message contains a date + time which can mess with caches and up-to-date checking in e.g. Gradle. Looks like we've found a workaround ignoring STDERR for the current implementation but others might run into this as well.

### Logs

See above.

**Comment by loewenheim** [comment]
This happens because the `SENTRY_PROPERTIES` file gets read as part of loading the `sentry-cli` config, which happens before the log level gets set from the CLI args. We'll need to restructure this.
