### ISSUE TITLE
`sourcemaps explain` fails with "Failed to discover source map url"

### ISSUE THREAD

**Issue by olessavluk** [getsentry/sentry-cli#1792]
Hi 👋  

`sentry-cli sourcemaps explain <event>` return following error:
<details>
  <summary>raw logs</summary>

```
...
  DEBUG   2023-10-30 20:38:23.174435628 +00:00 response status: 200
  DEBUG   2023-10-30 20:38:23.174448845 +00:00 body: {"id":"39216","name":"~/index.android.bundle","dist":"8006180","headers":{"sourcemap":"index.android.bundle.map"},"size":0,"sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","dateCreated":"2023-09-29T15:25:39.501083Z"}
✔ Successfully fetched ~/index.android.bundle file metadata from the server.
  DEBUG   2023-10-30 20:38:23.174591533 +00:00 request GET https://<domain hidden>/api/0/projects/sentry/exchange-app/releases/2.22.1/files/39216/?download=1
  DEBUG   2023-10-30 20:38:23.174612087 +00:00 using token authentication
  DEBUG   2023-10-30 20:38:23.174625517 +00:00 follow redirects: true
  DEBUG   2023-10-30 20:38:23.174749445 +00:00 > GET /api/0/projects/sentry/exchange-app/releases/2.22.1/files/39216/?download=1 HTTP/1.1
  DEBUG   2023-10-30 20:38:23.174765169 +00:00 > Host: <domain hidden>
  DEBUG   2023-10-30 20:38:23.174779020 +00:00 > Accept: */*
  DEBUG   2023-10-30 20:38:23.174789652 +00:00 > Connection: TE
  DEBUG   2023-10-30 20:38:23.174800417 +00:00 > TE: gzip
  DEBUG   2023-10-30 20:38:23.174807676 +00:00 > User-Agent: sentry-cli/2.21.2
  DEBUG   2023-10-30 20:38:23.174825159 +00:00 > Authorization: Bearer e8e7d3e0***
  DEBUG   2023-10-30 20:38:23.251626066 +00:00 < HTTP/1.1 200 OK
  DEBUG   2023-10-30 20:38:23.251674645 +00:00 < Date: Mon, 30 Oct 2023 20:38:23 GMT
  DEBUG   2023-10-30 20:38:23.251695889 +00:00 < Content-Type: application/octet-stream
  DEBUG   2023-10-30 20:38:23.251716335 +00:00 < Content-Length: 0
  DEBUG   2023-10-30 20:38:23.251734760 +00:00 < Connection: keep-alive
  DEBUG   2023-10-30 20:38:23.251753227 +00:00 < Content-Disposition: attachment; filename="index.android.bundle"
  DEBUG   2023-10-30 20:38:23.251778317 +00:00 < Allow: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2023-10-30 20:38:23.251797293 +00:00 < Access-Control-Allow-Methods: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2023-10-30 20:38:23.251824136 +00:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2023-10-30 20:38:23.251848293 +00:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-10-30 20:38:23.251869831 +00:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-10-30 20:38:23.251892377 +00:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-10-30 20:38:23.251914206 +00:00 < Content-Language: en
  DEBUG   2023-10-30 20:38:23.251935493 +00:00 < X-Frame-Options: deny
  DEBUG   2023-10-30 20:38:23.251958447 +00:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-10-30 20:38:23.251983457 +00:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-10-30 20:38:23.252056096 +00:00 < Strict-Transport-Security: max-age=15724800; includeSubDomains
  DEBUG   2023-10-30 20:38:23.252131564 +00:00 response status: 200
✔ Successfully fetched ~/index.android.bundle file from the server.
✖ Failed to discover source map url
```
</details>

Supicious that this file have size 0, but same is true for Cloud Sentry, yet sourcemaps are matched just fine:
![image](https://github.com/getsentry/sentry-cli/assets/1577804/5ad9d60c-620b-4a7b-b899-0404a35c18bd)

Do you know what this error^ means? And in general why sourcemaps might have stopped working after updating hosted sentry?

**Comment by loewenheim** [comment]
Hi, unfortunately `sourcemaps explain` has drifted a lot from how things actually work and it might not be telling you the actual problem. In this case the problem probably isn't the missing sourcemap URL, because as you say, the sourcemap seems to be matched. Can you expand on how sourcemaps aren't working?

**Comment by olessavluk** [comment]
When I open exception it looks like this:

<details><summary>Event screenshot</summary>

![Screenshot 2023-10-31 at 21-01-49 Error throwPromise from Playground — sentry — sbk copy](https://github.com/getsentry/sentry-cli/assets/1577804/2b4c9efd-dac4-462d-827d-4ae34e937b05)

</details> 

Even through soucemaps seems to have been uploaded fine during build and release/dist matches with error:

<details><summary>Source maps screenshot</summary>
<img width="1294" alt="image" src="https://github.com/getsentry/sentry-cli/assets/1577804/40c0853e-4c24-44b6-b4b5-1635c26a31fb">
</details>

**Comment by loewenheim** [comment]
Can you send me the link to the event? My Sentry email address is sebastian.zivota@sentry.io.

**Comment by olessavluk** [comment]
not 100% sure as changed multiple things, but probably adding [symbolicator](https://getsentry.github.io/symbolicator/) copy into each container of self-hosted sentry helped

thanks for your help!

**Comment by sergeiprilepko** [comment]
> not 100% sure as changed multiple things

@olessavluk can you please say, what exactly you did in that multiple things? Maybe you rememeber

**Comment by olessavluk** [comment]
no, unfortunately I don't remember exactly

would suggest to run this command - https://github.com/getsentry/symbolicator/issues/1536#issuecomment-2419935308
was very helpful for diagnostic
