### ISSUE TITLE
Source maps options support

### ISSUE THREAD

**Issue by montogeek** [getsentry/sentry-cli#180]
Hi!

I am using `sentry-cli` binary to uploads my source maps using npm script, `"uploadMaps": "sentry-cli releases files ${VERSION} upload-sourcemaps ./dist --validate --url-prefix '~/path/path' && rm dist/*.map",`, it works but not the best solution.

I want to migrate it to Sentry Source maps webpack plugin, but I see the new (merge 2 days ago) JS interface does not support all the possible options you can pass when using `release` command, at this moment it is passing by default `--rewrite` option.

https://github.com/getsentry/sentry-cli/blob/master/js/index.js#L62-L68

Is there any plan to support it? Would you accept a PR to add it?

Thanks!

**Comment by jan-auer** [comment]
> Would you accept a PR to add it?

Absolutely!

**Comment by montogeek** [comment]
Implemented on #182
