### ISSUE TITLE
Problem with sending debug information to Sentry.

### ISSUE THREAD

**Issue by AnDevi** [getsentry/sentry-cli#1809]
I'm using MacOS and  `sentry-cli 2.21.2` and `wasm-split 23.10.1`

I'm trying to use Sentry with WebAssembly and c++ native code. I did everything like you said in tutorial.
- I have `.wasm` binary compiled with `emcc`
- I added build id to my binary and created file with debug info with `wasm-split`
```
wasm-split main.wasm -d main.debug.wasm --strip
```
- And finally I upload debug info to sentry:
```
sentry-cli debug-files upload -t wasm -o <org> -p <project> main.debug.wasm
```

Then I force my native code to invoke runtime error. I can see event is registered in my Sentry's project, I can see call stack but only with functions names. I believe that I should see also file names and line numbers etc in that call stack but I don't.
I far as I know I should also see section `Loaded Images` in my event, with id which was embedded with `wasm-split` but I also don't.

What I noticed and I think that may be an issue `wasm-split` displays ID added, but during uploading debug info to sentry with `sentry-cli` this ID is always modified with the same pattern. 

ID:                             `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
is transformed into  `10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
(adds prefix `10` and cuts last two signs).

I wonder if that is the issue why my event isn't connected with its debug info I uploaded?
Or if it's expected behaviour what else can be the problem?

Thanks a lot for any help!

![image](https://github.com/getsentry/sentry-cli/assets/12371589/4a193569-8bd7-497c-a2e7-fc9bd3b24873)

**Comment by loewenheim** [comment]
Sorry, this completely slipped by me. I'll have a look as soon as possible!

**Comment by AnDevi** [comment]
@loewenheim Hi, is there any progress in that issue ? ;)
