### ISSUE TITLE
hidden-source-map not working past version 2.20.6+

### ISSUE THREAD

**Issue by kennethtruong** [getsentry/sentry-cli#1816]
### Environment
@sentry/cli - 2.20.6
Mac

### Steps to Reproduce
Use webpack to generate the sourcemaps with devtool option `hidden-source-map` 
Upload sourcemaps via this script. Then trigger an error that goes to Sentry

```
sentry-cli login --auth-token $SENTRY_TOKEN

sentry-cli sourcemaps inject build/static/js

VERSION="$(git rev-parse HEAD)"

sentry-cli releases new "$VERSION"
sentry-cli releases set-commits "$VERSION" --auto

sentry-cli releases files "$VERSION" upload-sourcemaps build/static/js --url-prefix '~/static/js'

sentry-cli releases finalize "$VERSION"
```

### Expected/Actual Result

In version 2.18.1 the sourcemaps works. But whenever I try to update past 2.18.1 it maps the sourcemaps incorrectly. 

Example of a version using sourcemaps from sentry/cli - 2.21.3
https://sigma-computing.sentry.io/issues/4624915640/?project=157435&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

**Comment by loewenheim** [comment]
Hi, thank you for the report. Does the problem only occur when you use `hidden-source-map`? Can you run
```bash
sentry-cli sourcemaps resolve -l 4701 -c 1502222 main.504303e0.min.js.map
```
and
```bash
sentry-cli sourcemaps resolve -l 4699 -c 1502222 main.504303e0.min.js.map
```
on the non-injected sourcemap and check if the output matches what you expect? Alternatively, can you email the sources you're testing this with at sebastian.zivota@sentry.io?
