### ISSUE TITLE
Brew install failing for version 2.22.2-alpha.0

### ISSUE THREAD

**Issue by gcazangi** [getsentry/sentry-cli#1840]
### Environment

sentry-cli 2.22.2-alpha.0
osX 13.6.2

### Steps to Reproduce

`brew install getsentry/tools/sentry-cli`

### Expected/Actual Result

Expected: Brew installs the latest sentry-cli version successfully.
Actual: Install fails with `TypeError: no implicit conversion of nil into String`

### Logs

```
$ brew "install" "getsentry/tools/sentry-cli"
==> Tapping getsentry/tools
Cloning into '/opt/homebrew/Library/Taps/getsentry/homebrew-tools'...
Tapped 2 formulae (16 files, 175.5KB).
==> Fetching getsentry/tools/sentry-cli
==> Downloading https://downloads.sentry-cdn.com/sentry-cli/2.22.2-alpha.0/sentry-cli-Darwin-universal
==> Installing sentry-cli from getsentry/tools
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of nil into String
Can't install formulas:  exit status 1
```

Seems related to https://github.com/getsentry/craft/issues/391 and similar to https://github.com/getsentry/sentry-cli/issues/1177

**Comment by lforst** [comment]
Oof seems like we are publishing alpha releases as latest versions on brew, lemme shoot one more proper release out to get this fixed.

**Comment by lforst** [comment]
Sorry about that. New release is out if you want to try installing it again.
