### ISSUE TITLE
[vite] Couldn't resolve host name (Could not resolve host: sentry.io)

### ISSUE THREAD

**Issue by darthf1** [getsentry/sentry-cli#1843]
Hi!,

Whenever I update my deps in package.json, and build my Nuxt app, I get the following error:

```
error: API request failed  caused by: [6] Couldn't resolve host name (Could not resolve host: sentry.io)
```
This is happening for me since 2 or 3 weeks. Whenever I rollback the changes, everythings works again.

Not sure how to continue / how to debug this any further. 

### Environment

nodejs 21.2.0
pnpm 8.11.0

`package.json`
```json
{
    "@sentry/integrations": "7.81.1",
    "@sentry/types": "7.81.1",
    "@sentry/vite-plugin": "2.10.1",
    "@sentry/vue": "7.81.1",
    "nuxt": "3.8.2",
    "vue": "3.3.9",
}
```

`.nmprc`
```
audit=false
loglevel=error
fund=false
node-linker=hoisted
package-import-method=copy
progress=false
shamefully-hoist=true
strict-peer-dependencies=true
update-notifier=false
```

`nuxt.config.ts`
``` ts
import { sentryVitePlugin } from '@sentry/vite-plugin'
import { defineNuxtConfig } from 'nuxt/config'

export default defineNuxtConfig({
  ....
  vite: {
    plugins: [
      process.env.NUXT_PUBLIC_SENTRY_ENABLED === 'true'
        ? sentryVitePlugin({
            authToken: process.env.NUXT_PUBLIC_SENTRY_AUTH_TOKEN,
            debug: true,
            org: process.env.NUXT_PUBLIC_SENTRY_ORG,
            project: process.env.NUXT_PUBLIC_SENTRY_PROJECT,
            release: {
              name: process.env.NUXT_PUBLIC_SENTRY_RELEASE,
            },
            sourcemaps: {
              assets: ['./.nuxt/dist/client/**'],
              filesToDeleteAfterUpload: ['.nuxt/dist/**/*.js.map'],
            },
            telemetry: false,
          })
        : {},
    ],
  },
})
```

[Full build error log during Nuxt build](https://gist.github.com/darthf1/740737d4a905fe8bbbcc1812688275db)
[A lockfile from a week ago that errors (with less recent deps as stated above)](https://gist.github.com/darthf1/8fa22e169399957fe0e841f4bef6c484)

**Comment by yun548** [comment]
> Hi [@darthf1](https://github.com/darthf1)! Thank you for bringing this issue to our attention. Would you be able to provide a full reproduction (ideally as a GitHub repo) that I can clone/download and run locally to see if I obtain the same error?

Hi, I am encountering the issue when build on Github runners, reopening the issue and I'll try to propose a repository to reproduce. It's happening in an inconsistent manner as of now, about 50% of the time.

**Comment by tomas789** [comment]
We are experiencing this issue for our production CI pipeline for a few months now. I'm adding a few links that seem relevant

- https://community.cloudflare.com/t/1-1-1-1-intermittently-returning-empty-answer-section-for-a-query/568098
- https://www.reddit.com/r/PleX/comments/kddtrk/plex_server_crashing_12_times_a_day/

**Comment by wahidshadab** [comment]
+1
