### ISSUE TITLE
error: your platform and architecture (Linux-x86_64) is unsupported.

### ISSUE THREAD

**Issue by mona-mp** [getsentry/sentry-cli#1844]
**Issue Description:**
I am attempting to install sentry-cli using the provided script, but I encounter an error stating that my platform and architecture are unsupported. The command I used and the error message are as follows:

`curl -sL https://sentry.io/get-cli/ | bash
`

**Error Message:**
```

This script will automatically install sentry-cli (latest) for you.
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous.
         Instead, run it as a normal user. We will sudo as needed.
######################################################################## 100.0%
error: your platform and architecture (Linux-x86_64) is unsupported.
```

**Environment Details:**

Operating System: Debian 5.10.158-2 (2022-12-13)
Architecture: x86_64

**Comment by szokeasaurusrex** [comment]
Thank you for reporting this issue, @mona-mp. 

Are you able to install the latest version of the Sentry CLI using one of the [other documented methods](https://docs.sentry.io/product/cli/installation/?original_referrer=https%3A%2F%2Fwww.google.com%2F#manual-download), such as via a [manual download](https://docs.sentry.io/product/cli/installation/?original_referrer=https%3A%2F%2Fwww.google.com%2F#manual-download) or from [npm](https://docs.sentry.io/product/cli/installation/?original_referrer=https%3A%2F%2Fwww.google.com%2F#installation-via-npm)? If not, are you able to install Sentry CLI v2.22.2 (or another older CLI version) using the command below?
```bash
$ curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.22.2" sh
```

**Comment by codedge** [comment]
I got the same error running the install, also with your suggestion @szokeasaurusrex  
I tried to build this on Alpine Linux 3.18. `RUN curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.23.3" sh` 

It fails withs `your platform and architecture (Linux-x86_64) is unsupported.` 

![2023-12-05_121019](https://github.com/getsentry/sentry-cli/assets/4409904/f4c9529d-0fcd-430d-be3c-1ba475107c18)

**Comment by szokeasaurusrex** [comment]
Hi @codedge, can you please try again, specifically with version 2.22.2? We made some changes to how we package the CLI in version 2.22.3, and I would like to determine whether these changes are causing the error

**Comment by codedge** [comment]
@szokeasaurusrex With version `2.22.2` everything is fine.

```
/usr/src/app # curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.22.2" sh
This script will automatically install sentry-cli (2.22.2) for you.
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous. 
         Instead run it as normal user. We will sudo as needed.
######################################################################## 100.0%##O#-#                                         ######################################################################## 100.0%
Installed sentry-cli 2.22.2
Done!
```

**Comment by szokeasaurusrex** [comment]
Thanks for checking @codedge; this information is extremely helpful. 

One more question: are you able to install version 2.22.3 by manually downloading the appropriate binary from our [GitHub Releases page?](https://github.com/getsentry/sentry-cli/releases/)? Note that you may need to click the "See all 16 assets" button to reveal the Linux x86_64 binary.

**Comment by szokeasaurusrex** [comment]
@codedge and @mona-mp, I attempted to reproduce your issue on an x86_64 Linux VM. However, when I ran the command `curl -sL https://sentry.io/get-cli/ | sh`, I was able to successfully install the latest Sentry CLI version (currently 2.23.0). 

The system that I used to attempt to reproduce the issue produces the following `uname -a` output:
```
Linux danielszoke-test-cli-installation 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
```

If you are still experiencing the issue today, could you please provide me with the `uname -a` output from your systems and any other information that could help me to reproduce your exact setup?

**Comment by codedge** [comment]
My `uname -a` output

```
Linux dccb4f467be7 6.4.16-linuxkit #1 SMP PREEMPT Thu Nov 16 10:49:20 UTC 2023 aarch64 Linux
```

It is ARM... Apple M2.. I believe that is the issue.

.. and I guess this is also the problem in our CI pipeline, as we build multi-arch images.

**Comment by mona-mp** [comment]
The `uname -a` output for me is :
`Linux wroker-1 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux`

Also, with `2.22.2` I get the same error:

`curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.22.2" sh
This script will automatically install sentry-cli (2.22.2) for you.
Installation path: /usr/local/bin/sentry-cli
######################################################################## 100.0%
error: your platform and architecture (Linux-x86_64) is unsupported.`

**Comment by szokeasaurusrex** [comment]
@mona-mp Thanks for the information. Based on your `uname -a` output, it seems that we were both trying to install the CLI with similar systems (both x86_64 Debian 5.10, I am on a newer patch version, however), so I find it very strange that the installation succeeds for me. 

Have you ever been able to successfully install the Sentry CLI? And, are any of the [other installation methods](https://docs.sentry.io/product/cli/installation/) working for you?

**Comment by szokeasaurusrex** [comment]
@mona-mp and @codedge, after looking into the issue further, it seems that the issue could be completely unrelated to your platform and architecture, and might actually be occurring because of some other error while fetching the binary.

The error message you are seeing is generated on [this line](https://github.com/getsentry/getsentry/blob/7505b9213b4fa77097d3a48527f8bf82efa4fc5a/getsentry/web/cli.py#L79) of the install script whenever the `curl` command used to fetch the binary returns a non-200 status code. One possible cause of this issue is that your platform or architecture is unsupported, because in this case, no binary corresponding to the provided platform/architecture would be found on the server. But, there are also many other potential causes to receiving a non-200 status code, such as problems with the internet connection, so we will update this error message to make it clear to users going forward that your platform/architecture being unsupported is just one of the many potential causes of this error.

To help me diagnose your problem, would you be able to provide the output of the `curl` command below? This is the command that the install script runs internally (see [this line](https://github.com/getsentry/getsentry/blob/7505b9213b4fa77097d3a48527f8bf82efa4fc5a/getsentry/web/cli.py#L77)) to download the binary for your platform.
```bash
$ curl -SL --progress-bar "https://release-registry.services.sentry.io/apps/sentry-cli/2.23.0?response=download&arch=x86_64&platform=Linux&package=sentry-cli" --output sentry-cli --write-out "%{http_code}"
```

**Comment by janpapenbrock** [comment]
Got the same error in our CI yesterday and today, again. It fixed itself on the next runs, maybe it correlates to releases you're making?

Timestamps:
- `2024/07/01 14:18:52.592764 Running command curl -sL https://sentry.io/get-cli/ | bash`
- `2024/07/02 07:37:14.154085 Running command curl -sL https://sentry.io/get-cli/ | bash`

**Comment by AkashRajpurohit** [comment]
Dug deeper into this, the underlying issue seems to be this: https://github.com/getsentry/sentry-cli/issues/2586
