### ISSUE TITLE
bad trap

### ISSUE THREAD

**Issue by Luke-SF** [getsentry/sentry-cli#1848]
### Environment

Default on Ubuntu 20.04.6 LTS

### Steps to Reproduce
```
#!/bin/bash
export SENTRY_DSN=https://DSN...
eval "$(sentry-cli bash-hook)"
echo 'okay';

```
### Expected/Actual Result

Run the script, it does not run.

### Logs

Instead of running it returns - 

```
$ sh testbash.sh 
trap: ERR: bad trap
testbash.sh: 1: _sentry_exit_trap: not found

```

**Comment by szokeasaurusrex** [comment]
Per [the docs](https://docs.sentry.io/product/cli/send-event/?original_referrer=https%3A%2F%2Fwww.google.com%2F#bash-hook), `sentry-cli bash-hook` is designed specifically to work with `bash`. 

If you would like to see us add support for another shell, please feel free to open a new feature request issue, and we will gladly look into expanding support.

Either way, if you're able to run the script successfully in bash, that would imply that the current implementation is correct, so we can go ahead and close this issue.
