### ISSUE TITLE
EACCES error: `@sentry/cli-linux-x64/bin/sentry-cli` is not executable

### ISSUE THREAD

**Issue by dawnmist** [getsentry/sentry-cli#1851]
### Environment

- node v20.10.0
- yarn v4.0.2, with `pnpm` nodeLinker
- "@sentry/remix@npm:7.84.0"
- "@sentry/react@npm:7.84.0"
- "@sentry/node@npm:7.84.0"
- "@sentry/core@npm:7.84.0"
- "@sentry/cli@npm:2.21.3"
- "@sentry/cli-linux-x64@npm:2.22.3"

Minimal example reproduction available from https://github.com/dawnmist/test-sentry-cli-permissions

### Steps to Reproduce

- Check out the repo https://github.com/dawnmist/test-sentry-cli-permissions
- `yarn install`
- `ls -l node_modules/.store/@sentry-cli-x64-npm-2.22.3-81f995f8ee/package/bin`

Note that the permissions are `rw-r--r--` instead of `rwxr-xr-x`, which means that any attempt to execute the sentry-cli will fail and throw an `EACCES` error.

### Expected/Actual Result

I was using this to create a new sentry release for a remix project (via the `createRelease` script in `@sentry/remix/scripts/createRelease.js`), but the lack of execute permission for `sentry-cli` results in the error:
```sh
Failed to create a sentry release Error: spawn /home/username/project/node_modules/.store/@sentry-cli-linux-x64-npm-2.22.3-81f995f8ee/package/bin/sentry-cli EACCES
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/username/project/node_modules/.store/@sentry-cli-linux-x64-npm-2.22.3-81f995f8ee/package/bin/sentry-cli',
  path: '/home/username/project/node_modules/.store/@sentry-cli-linux-x64-npm-2.22.3-81f995f8ee/package/bin/sentry-cli',
  spawnargs: [ 'releases', 'new', '9de06f6330363c6aae9d0409ef3e9ca6025dec3c' ],
  cmd: '/home/username/project/node_modules/.store/@sentry-cli-linux-x64-npm-2.22.3-81f995f8ee/package/bin/sentry-cli releases new 9de06f6330363c6aae9d0409ef3e9ca6025dec3c'
}
```

Manually adding the missing execute permission to the `sentry-cli` binary allows the `createRelease` script to run properly.

**Comment by szokeasaurusrex** [comment]
Thank you for reporting! I was able to reproduce this issue on macOS as well. We will try to get this fixed as soon as possible!

**Comment by dawnmist** [comment]
@lforst - this is happening with yarn when using the yarn pnpm nodeLinker. I haven't tested it with pnpm itself.

**Comment by dawnmist** [comment]
It'd be the yarn folks that need to address it, as it's entirely within yarn.

**Comment by lforst** [comment]
Fair. I haven't narrowed down whether it is yarn or pnpm. From our POV we can't do more than make the binary executable, which we already do.
