### ISSUE TITLE
Switch from libgit2 to gix

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry-cli#1861]
@asottile-sentry described a bug I encountered using the CLI through Docker [here](https://github.com/libgit2/libgit2/issues/6663)

Swithing to [gix](https://crates.io/crates/gix) would resolve this problem and avoid having to add this hack to Docker to make the CLI be able to detect the current git sha:

```docker
ENV SUDO_UID=1001
```

**Comment by szokeasaurusrex** [comment]
Closed in favor of #1866
