### ISSUE TITLE
cannot upload sourcemaps 

### ISSUE THREAD

**Issue by yayapao** [getsentry/sentry-cli#1867]
### Environment

CLI: v1.17.4 or v2.22.3
Self_hosted_sentry: v21.6.3

### Steps to Reproduce
(v1.17.4)
1. config ~/.sentryclirc 
2. create new release `sentry-cli releases new v1215` successfully!
3. upload files `sentry-cli releases files v1215 upload-sourcemaps --url-prefix '~/assets/' ./dist/assets/`
4. commit `sentry-cli releases finalize v1215`

### Expected Result

Files should be uploaded to the platform.

### Actual Result

Debug logs say everything is ok and all request returns 200, but cannot  find artifacts in the Sentry.

### Logs

  INFO    2023-12-15 11:11:03.061593 +08:00 Loaded config from /Users/yaya/.sentryclirc
  DEBUG   2023-12-15 11:11:03.062282 +08:00 sentry-cli version: 1.74.5, platform: "darwin", architecture: "x86_64"
  INFO    2023-12-15 11:11:03.062288 +08:00 sentry-cli was invoked with the following command line: "/Users/yaya/.volta/tools/image/packages/@sentry/cli/lib/node_modules/@sentry/cli/sentry-cli" "releases" "new" "v1215"
  DEBUG   2023-12-15 11:11:03.062559 +08:00 request POST http://[domain].com/api/0/projects/yaya/sentry-vite-eg/releases/
  DEBUG   2023-12-15 11:11:03.062583 +08:00 using token authentication
  DEBUG   2023-12-15 11:11:03.062612 +08:00 json body: {"version":"v1215","projects":["sentry-vite-eg"],"dateStarted":"2023-12-15T03:11:03.062531Z"}
  DEBUG   2023-12-15 11:11:03.062655 +08:00 retry number 0, max retries: 0
  DEBUG   2023-12-15 11:11:03.137572 +08:00 > POST /api/0/projects/yaya/sentry-vite-eg/releases/ HTTP/1.1
  DEBUG   2023-12-15 11:11:03.137637 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:11:03.137659 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:11:03.137717 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:11:03.137739 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:11:03.137758 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:11:03.138620 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:11:03.138669 +08:00 > Content-Type: application/json
  DEBUG   2023-12-15 11:11:03.138687 +08:00 > Content-Length: 91
  DEBUG   2023-12-15 11:11:03.545320 +08:00 < HTTP/1.1 201 Created
  DEBUG   2023-12-15 11:11:03.545441 +08:00 < Content-Type: application/json
  DEBUG   2023-12-15 11:11:03.545495 +08:00 < Content-Length: 579
  DEBUG   2023-12-15 11:11:03.545522 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:11:03.545547 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:11:03.545576 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:11:03.545623 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:11:03.545656 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:11:03.545686 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:11:03.545715 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:11:03.545744 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:11:03.545771 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:11:03.545798 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:11:03.545824 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:11:03.545851 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:11:03.546137 +08:00 response status: 201
  DEBUG   2023-12-15 11:11:03.546225 +08:00 body: {"version":"v1215","status":"open","shortVersion":"v1215","versionInfo":{"package":null,"version":{"raw":"v1215"},"description":"v1215","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2023-12-15T03:11:05.398920Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":1068,"slug":"sentry-vite-eg","name":"sentry-vite-eg","newGroups":0,"platform":"javascript-react","platforms":["javascript"],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{}}
Created release v1215.
➜  sentry-vite-eg git:(master) ✗ sentry-cli releases files v1215 upload-sourcemaps --url-prefix '~/assets/' ./dist/assets/
  INFO    2023-12-15 11:13:23.898495 +08:00 Loaded config from /Users/yaya/.sentryclirc
  DEBUG   2023-12-15 11:13:23.899480 +08:00 sentry-cli version: 1.74.5, platform: "darwin", architecture: "x86_64"
  INFO    2023-12-15 11:13:23.899487 +08:00 sentry-cli was invoked with the following command line: "/Users/yaya/.volta/tools/image/packages/@sentry/cli/lib/node_modules/@sentry/cli/sentry-cli" "releases" "files" "v1215" "upload-sourcemaps" "--url-prefix" "~/assets/" "./dist/assets/"
  DEBUG   2023-12-15 11:13:23.906196 +08:00 built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 4 required extensions, 0 regexes  (from globset)
  DEBUG   2023-12-15 11:13:23.907080 +08:00 glob converted to regex: Glob { glob: "**/*~", re: "(?-u)^(?:/?|.*/)[^/]*\\~$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([RecursivePrefix, ZeroOrMore, Literal('~')]) }  (from globset)
  DEBUG   2023-12-15 11:13:23.907135 +08:00 built glob set; 0 literals, 1 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes  (from globset)
  DEBUG   2023-12-15 11:13:23.907831 +08:00 ignoring dist/assets/react-35ef61ed.svg: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
  DEBUG   2023-12-15 11:13:23.907895 +08:00 whitelisting dist/assets/index-4b4f7fc1.js.map: Whitelist(IgnoreMatch(Types(Glob(Matched { def: FileTypeDef { name: "map", globs: ["*.map"] }, which: 0, negated: false }))))  (from ignore)
  INFO    2023-12-15 11:13:23.907940 +08:00 found: dist/assets/index-4b4f7fc1.js.map (351399 bytes)
  DEBUG   2023-12-15 11:13:23.908840 +08:00 whitelisting dist/assets/index-4b4f7fc1.js: Whitelist(IgnoreMatch(Types(Glob(Matched { def: FileTypeDef { name: "js", globs: ["*.js"] }, which: 0, negated: false }))))  (from ignore)
  INFO    2023-12-15 11:13:23.908937 +08:00 found: dist/assets/index-4b4f7fc1.js (144140 bytes)
  DEBUG   2023-12-15 11:13:23.909604 +08:00 ignoring dist/assets/index-d526a0c5.css: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
> Found 2 release files
> Analyzing 2 sources
> Analyzing completed in 0.042s
> Rewriting sources
> Rewriting completed in 0.015s
> Adding source map references
  DEBUG   2023-12-15 11:13:23.969406 +08:00 request POST http://[domain].com/api/0/projects/yaya/sentry-vite-eg/releases/
  DEBUG   2023-12-15 11:13:23.969435 +08:00 using token authentication
  DEBUG   2023-12-15 11:13:23.969450 +08:00 json body: {"version":"v1215","projects":["sentry-vite-eg"]}
  DEBUG   2023-12-15 11:13:23.969476 +08:00 retry number 0, max retries: 0
  DEBUG   2023-12-15 11:13:24.031805 +08:00 > POST /api/0/projects/yaya/sentry-vite-eg/releases/ HTTP/1.1
  DEBUG   2023-12-15 11:13:24.031838 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:13:24.031847 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:13:24.031853 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:13:24.031860 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:13:24.031867 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:13:24.032250 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:13:24.032263 +08:00 > Content-Type: application/json
  DEBUG   2023-12-15 11:13:24.032271 +08:00 > Content-Length: 47
  DEBUG   2023-12-15 11:13:25.099130 +08:00 < HTTP/1.1 208 Already Reported
  DEBUG   2023-12-15 11:13:25.099203 +08:00 < Content-Type: application/json
  DEBUG   2023-12-15 11:13:25.099229 +08:00 < Content-Length: 579
  DEBUG   2023-12-15 11:13:25.099250 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:13:25.099272 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:13:25.099298 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:13:25.099339 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:13:25.099370 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:13:25.099397 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:13:25.099425 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:13:25.099449 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:13:25.099480 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:13:25.099511 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:13:25.099537 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:13:25.099643 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:13:25.100061 +08:00 response status: 208
  DEBUG   2023-12-15 11:13:25.100200 +08:00 body: {"version":"v1215","status":"open","shortVersion":"v1215","versionInfo":{"package":null,"version":{"raw":"v1215"},"description":"v1215","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2023-12-15T03:11:05.398920Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":1068,"slug":"sentry-vite-eg","name":"sentry-vite-eg","newGroups":0,"platform":"javascript-react","platforms":["javascript"],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{}}
  DEBUG   2023-12-15 11:13:25.101029 +08:00 request GET http://[domain].com/api/0/organizations/yaya/chunk-upload/
  DEBUG   2023-12-15 11:13:25.101077 +08:00 using token authentication
  DEBUG   2023-12-15 11:13:25.101105 +08:00 retry number 0, max retries: 0
  DEBUG   2023-12-15 11:13:25.144662 +08:00 > GET /api/0/organizations/yaya/chunk-upload/ HTTP/1.1
  DEBUG   2023-12-15 11:13:25.144717 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:13:25.144730 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:13:25.144837 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:13:25.144869 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:13:25.144895 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:13:25.144951 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:13:25.712200 +08:00 < HTTP/1.1 200 OK
  DEBUG   2023-12-15 11:13:25.712262 +08:00 < Content-Type: application/json
  DEBUG   2023-12-15 11:13:25.712279 +08:00 < Content-Length: 298
  DEBUG   2023-12-15 11:13:25.712297 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:13:25.712314 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:13:25.712334 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:13:25.712361 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:13:25.712382 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:13:25.712399 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:13:25.712418 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:13:25.712437 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:13:25.712455 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:13:25.712472 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:13:25.712491 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:13:25.712510 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:13:25.712723 +08:00 response status: 200
  DEBUG   2023-12-15 11:13:25.712762 +08:00 body: {"url":"https://[domain].com/api/0/organizations/yaya/chunk-upload/","chunkSize":8388608,"chunksPerRequest":64,"maxFileSize":2147483648,"maxRequestSize":33554432,"concurrency":8,"hashAlgorithm":"sha1","compression":["gzip"],"accept":["debug_files","release_files","pdbs","sources","bcsymbolmaps"]}
> Bundling files for upload... 
> Bundling completed in 0.037s
> Optimizing completed in 0s
  INFO    2023-12-15 11:13:25.751783 +08:00 using 'gzip' compression for chunk upload
  DEBUG   2023-12-15 11:13:25.756559 +08:00 request POST https://[domain].com/api/0/organizations/yaya/chunk-upload/
  DEBUG   2023-12-15 11:13:25.756652 +08:00 sending form data
  DEBUG   2023-12-15 11:13:25.757183 +08:00 using token authentication
  DEBUG   2023-12-15 11:13:25.757241 +08:00 retry number 0, max retries: 5
  DEBUG   2023-12-15 11:14:40.827185 +08:00 > POST /api/0/organizations/yaya/chunk-upload/ HTTP/1.1
  DEBUG   2023-12-15 11:14:40.827299 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:14:40.827558 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:14:40.827635 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:14:40.827692 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:14:40.827742 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:14:40.828470 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:14:40.828535 +08:00 > Content-Length: 143681
  DEBUG   2023-12-15 11:14:40.828716 +08:00 > Content-Type: multipart/form-data; boundary=------------------------bfd3c765ebdf3c66
  DEBUG   2023-12-15 11:14:41.086485 +08:00 < HTTP/1.1 200 OK
  DEBUG   2023-12-15 11:14:41.086590 +08:00 < Content-Length: 0
  DEBUG   2023-12-15 11:14:41.086805 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:14:41.086917 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:14:41.086945 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-12-15 11:14:41.086976 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:14:41.087013 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:14:41.087041 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:14:41.087108 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:14:41.087172 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:14:41.087251 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:14:41.087326 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:14:41.087384 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:14:41.087437 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:14:41.088028 +08:00 response status: 200
  DEBUG   2023-12-15 11:14:41.088077 +08:00 body: 
> Uploading completed in 75.335s
> Uploaded release files to Sentry
  DEBUG   2023-12-15 11:14:41.088428 +08:00 request POST http://[domain].com/api/0/organizations/yaya/releases/v1215/assemble/
  DEBUG   2023-12-15 11:14:41.088447 +08:00 using token authentication
  DEBUG   2023-12-15 11:14:41.088460 +08:00 json body: {"checksum":"a35b36138a9f5f077ff292783732b4aeae5c27e2","chunks":["a35b36138a9f5f077ff292783732b4aeae5c27e2"]}
  DEBUG   2023-12-15 11:14:41.088469 +08:00 retry number 0, max retries: 5
  DEBUG   2023-12-15 11:14:41.105737 +08:00 > POST /api/0/organizations/yaya/releases/v1215/assemble/ HTTP/1.1
  DEBUG   2023-12-15 11:14:41.105777 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:14:41.105786 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:14:41.105793 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:14:41.105826 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:14:41.105833 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:14:41.105848 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:14:41.105855 +08:00 > Content-Type: application/json
  DEBUG   2023-12-15 11:14:41.105947 +08:00 > Content-Length: 109
  DEBUG   2023-12-15 11:14:41.513569 +08:00 < HTTP/1.1 200 OK
  DEBUG   2023-12-15 11:14:41.513741 +08:00 < Content-Type: application/json
  DEBUG   2023-12-15 11:14:41.513800 +08:00 < Content-Length: 38
  DEBUG   2023-12-15 11:14:41.513841 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:14:41.513882 +08:00 < Allow: POST, OPTIONS
  DEBUG   2023-12-15 11:14:41.513924 +08:00 < Access-Control-Allow-Methods: POST, OPTIONS
  DEBUG   2023-12-15 11:14:41.513966 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:14:41.514004 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:14:41.514038 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:14:41.514075 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:14:41.514602 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:14:41.514702 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:14:41.514746 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:14:41.514784 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:14:41.514819 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:14:41.515066 +08:00 response status: 200
  DEBUG   2023-12-15 11:14:41.515131 +08:00 body: {"state":"created","missingChunks":[]}
> Processing completed in 0.426s
> File upload complete (processing pending on server)
> Organization: yaya
> Project: sentry-vite-eg
> Release: v1215
> Dist: None

Source Map Upload Report
  Minified Scripts
    ~/assets/index-4b4f7fc1.js (sourcemap at index-4b4f7fc1.js.map)
  Source Maps
    ~/assets/index-4b4f7fc1.js.map
➜  sentry-vite-eg git:(master) ✗ sentry-cli releases finalize v1215                                                       
  INFO    2023-12-15 11:20:14.100272 +08:00 Loaded config from /Users/yaya/.sentryclirc
  DEBUG   2023-12-15 11:20:14.101093 +08:00 sentry-cli version: 1.74.5, platform: "darwin", architecture: "x86_64"
  INFO    2023-12-15 11:20:14.101099 +08:00 sentry-cli was invoked with the following command line: "/Users/yaya/.volta/tools/image/packages/@sentry/cli/lib/node_modules/@sentry/cli/sentry-cli" "releases" "finalize" "v1215"
  DEBUG   2023-12-15 11:20:14.101409 +08:00 request PUT http://[domain].com/api/0/projects/yaya/sentry-vite-eg/releases/v1215/
  DEBUG   2023-12-15 11:20:14.101450 +08:00 using token authentication
  DEBUG   2023-12-15 11:20:14.101473 +08:00 json body: {"projects":["sentry-vite-eg"],"dateReleased":"2023-12-15T03:20:14.101377Z"}
  DEBUG   2023-12-15 11:20:14.101488 +08:00 retry number 0, max retries: 0
  DEBUG   2023-12-15 11:20:14.133969 +08:00 > PUT /api/0/projects/yaya/sentry-vite-eg/releases/v1215/ HTTP/1.1
  DEBUG   2023-12-15 11:20:14.134005 +08:00 > Host: [domain].com
  DEBUG   2023-12-15 11:20:14.134012 +08:00 > Accept: */*
  DEBUG   2023-12-15 11:20:14.134019 +08:00 > Connection: TE
  DEBUG   2023-12-15 11:20:14.134025 +08:00 > TE: gzip
  DEBUG   2023-12-15 11:20:14.134031 +08:00 > User-Agent: sentry-cli/1.74.5
  DEBUG   2023-12-15 11:20:14.134323 +08:00 > Authorization: Bearer 5e71fd1e***
  DEBUG   2023-12-15 11:20:14.134332 +08:00 > Content-Type: application/json
  DEBUG   2023-12-15 11:20:14.134339 +08:00 > Content-Length: 74
  DEBUG   2023-12-15 11:20:14.570032 +08:00 < HTTP/1.1 200 OK
  DEBUG   2023-12-15 11:20:14.570139 +08:00 < Content-Type: application/json
  DEBUG   2023-12-15 11:20:14.570174 +08:00 < Content-Length: 604
  DEBUG   2023-12-15 11:20:14.570203 +08:00 < Connection: keep-alive
  DEBUG   2023-12-15 11:20:14.570234 +08:00 < Allow: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2023-12-15 11:20:14.570277 +08:00 < Access-Control-Allow-Methods: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2023-12-15 11:20:14.570365 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-12-15 11:20:14.570408 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-12-15 11:20:14.570446 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2023-12-15 11:20:14.570720 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2023-12-15 11:20:14.570789 +08:00 < Content-Language: en
  DEBUG   2023-12-15 11:20:14.570817 +08:00 < X-Frame-Options: deny
  DEBUG   2023-12-15 11:20:14.570842 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2023-12-15 11:20:14.570868 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-12-15 11:20:14.570892 +08:00 < Server: APISIX/2.15.3
  DEBUG   2023-12-15 11:20:14.571206 +08:00 response status: 200
  DEBUG   2023-12-15 11:20:14.571271 +08:00 body: {"version":"v1215","status":"open","shortVersion":"v1215","versionInfo":{"package":null,"version":{"raw":"v1215"},"description":"v1215","buildHash":null},"ref":null,"url":null,"dateReleased":"2023-12-15T03:20:14.101377Z","dateCreated":"2023-12-15T03:11:05.398920Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":1068,"slug":"sentry-vite-eg","name":"sentry-vite-eg","newGroups":0,"platform":"javascript-react","platforms":["javascript"],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{}}
Finalized release v1215.

**Comment by yayapao** [comment]
i found sentry-vite-plugin or sentry-webpack-plugin will always pull latest sentry-cli and do something, so is sentry-cli ? which will always pull something to fetch requests?

**Comment by markushi** [comment]
Hi @yayapao thanks for reporting! Looks like this slipped through in https://github.com/getsentry/sentry-android-gradle-plugin/pull/587/files where we construct the arguments for the underlying `sentry-cli` in the wrong order when a custom URL is used. We'll have a look at this!

**Comment by szokeasaurusrex** [comment]
Hi @yayapao, I tried to reproduce your issue (using CLI version 2.23.0 and Sentry SaaS), but when I follow the commands you provided, the sourcemaps are being uploaded successfully. 

Could you please verify that you are uploading the sourcemaps to the correct organization and project? You can specifiy these with the `--org` and `--project` options, respectively. If you still are experiencing this same problem after verifying that you are uploading to the correct organization/project, please follow the steps listed on our [Troubleshooting Source Maps](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/) page rule out any other possible causes of this issue. 

Please let me know whether the steps I provided above solve your problem! Feel free to reach out if you have any questions.


> i found whether sentry-vite-plugin or sentry-webpack-plugin or their version will always pull latest sentry-cli and do some requests, so is sentry-cli ? which will always pull something to fetch requests?

I am unsure what you are asking here because your questions are worded somewhat vaguely. Can you please explain specifically what you are asking about?

**Comment by szokeasaurusrex** [comment]
> i found whether sentry-vite-plugin or sentry-webpack-plugin or their version will always pull latest sentry-cli and do some requests, so is sentry-cli ? which will always pull something to fetch requests?

I am unsure what you are asking here @yayapao because your questions are worded somewhat vaguely. Can you please explain specifically what you are asking about?

**Comment by yayapao** [comment]
yes, i upload sourceMap files with correct org and project, **besides that i use `--url=[self_hosted v21.6.3 url]` to make sure files are uploaded to target url**. Sentry-cli worked fine for the past few months and now it won't upload.

Maybe because of this change?

> Looks like this slipped through in https://github.com/getsentry/sentry-android-gradle-plugin/pull/587/files where we construct the arguments for the underlying sentry-cli in the wrong order when a custom URL is used

**Comment by yayapao** [comment]
I finally made it clear, we divide sentry server into  many mircoservices, like `sentry run web`, `sentry run worker -X default` and so on. We changed the task queue from Redis to RabbitMQ, and we updated all the services but web server. So the files were uploaded failed.
