### ISSUE TITLE
SENTRY_SKIP_DOWNLOAD flag makes error in `npm ci`

### ISSUE THREAD

**Issue by Jonir227** [getsentry/sentry-cli#1868]
### Environment

What version of the CLI and what OS are you running?

1.77.1

### Steps to Reproduce

`SENTRY_SKIP_DOWNLOAD=1 npm ci`

### Expected Result

install with no error.

https://github.com/getsentry/sentry-cli/pull/1817#discussion_r1432446927

this code makes error I think.

https://github.com/getsentry/sentry-cli/blob/1.77.1/scripts/install.js#L25-L31

`downloadBinary()` expects promise as return

### Actual Result

npm installaition error

### Logs

<img width="1103" alt="image" src="https://github.com/getsentry/sentry-cli/assets/21289079/ef2d9c73-6dde-47ff-ad82-bc17768985cd">

**Comment by diogokawamoto** [comment]
I'm facing the same issue, I tried to open a pull request to fix the return type, but there is no branch release/1.77.1 only the release/1.77.0 one

**Comment by adinauer** [comment]
Thanks for the report as well as the investigation and sorry for the troubles caused. It might take us a little longer to take a look as maintainers are out of office for the holidays.

**Comment by lforst** [comment]
Fixed with https://github.com/getsentry/sentry-cli/pull/1869

**Comment by Jonir227** [comment]
@lforst 

when it will be released? latest version is broken. it should be fixed :(

**Comment by lforst** [comment]
@Jonir227 sorry I completely forgot about releasing the fix. The latest v1 version of the SDK should include it.
