### ISSUE TITLE
attachment preview .log file

### ISSUE THREAD

**Issue by KloseLC** [getsentry/sentry-cli#1873]
### Environment

What version of the CLI and what OS are you running?

### Steps to Reproduce

What you did?

### Expected Result

What you thought would happen?

### Actual Result

What actually happened?

### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

**Comment by KloseLC** [comment]
![image](https://github.com/getsentry/sentry-cli/assets/12614765/81cfc1d3-3f87-4cd2-add6-3dfe4a8733c8)

**Comment by adinauer** [comment]
@KloseLC can you please fill out the sections in the initial post? It doesn't have to be in english if that helps.

**Comment by KloseLC** [comment]
我们上传的附件日志，是一个无法被preview状态的文件，需要修改SDK的上传MIME类型为text 才能实现，希望sentry SDK可以支持默认情况下的文本预览  如何修改的代码上面我已经上传  sentrySDK小组请了解一下

**Comment by KloseLC** [comment]
> @KloseLC您能填写最初帖子中的各个部分吗？如果有帮助的话，它不必是英文的。

默认0.5.0 SDK的附件内容无法被预览
