### ISSUE TITLE
Allow setting device family/model via env or conf

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry-cli#188]
For cli it would be nice if we could set the device family and model.

Could these be replaced with a small snippet that checks these values in the same way DSN is?

https://github.com/getsentry/sentry-cli/blob/master/src/utils/system.rs#L211-L219

**Comment by mitsuhiko** [comment]
Yeah. I think that makes sense to add. Also I kinda want to fill in some sensible defaults for non mac platforms.

**Comment by jan-auer** [comment]
This has been implemented and released in `sentry-cli 1.27.0`
