### ISSUE TITLE
Sentry-cli 2.24.0 login with auth token causes errors

### ISSUE THREAD

**Issue by PotatooSalad** [getsentry/sentry-cli#1888]
I used sentry-cli version 2.24.0 in bash command line.

I was deploying new release to sentry, with the same settings as always and after `sentry-cli` login --auth-token [...]` i got this error:
`thread 'main' panicked at 'Mismatch between definition and access of `auth_token`. Could not downcast to TypeId { t: 205527081075292425013923987422355844732 }, need to downcast to TypeId { t: 264673182028513726705440804281905241306 }
': C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap-4.1.6\src\parser\error.rs:30`

I tried with other tokens and I get the same message.

Yesterday everything was fine, issue started today after 2.24.0 release. I always use latest version to be up to date, but I guess I need to downgrade to 2.23.2 untill it's fixed.

**Comment by szokeasaurusrex** [comment]
Thank you for reporting this error; it appears related to a recent change that was released in version 2.24.0. We will immediately investigate what is happening here.
