### ISSUE TITLE
Failed to parse org auth token in Github actions

### ISSUE THREAD

**Issue by socketopp** [getsentry/sentry-cli#1891]
### Environment
"@sentry/vite-plugin": "^2.10.2",

### Steps to Reproduce

What you did?

Follow the source maps instructions
https://docs.sentry.io/platforms/javascript/sourcemaps/

Building with github actions:
Added   `SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}` to env. 

### Expected Result

What you thought would happen?
Build would not fail

### Actual Result

```
[vite-plugin-sveltekit-compile] Command failed: /home/runner/work/project/project/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases new 0aae7e8a066s4ff5c83321sfa5791fdb807502f4715
error: Failed to parse org auth token ***
***
***
  caused by: invalid base64 data
  caused by: invalid length at 144
```

### Logs

```
[vite-plugin-sveltekit-compile] Command failed: /home/runner/work/project/project/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases new 0aae7e8a0664ff5c83156df791fdb807502f4715
error: Failed to parse org auth token ***
***
***
  caused by: invalid base64 data
  caused by: invalid length at 144
```

**UPDATE**
Gonna try this:
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#storing-base64-binary-blobs-as-secrets

**Comment by szokeasaurusrex** [comment]
Hi @socketopp, thank you for reporting this issue; we will look into it as soon as possible. In the meantime, please make sure you are using the latest Sentry CLI version (`2.24.1`), since we reverted the change that was likely responsible for this error in that release due to another bug.

**Comment by socketopp** [comment]
Sorry for posting! It's was due to a classic copy and paste error from the terminal that lead to this error.

**Comment by szokeasaurusrex** [comment]
No worries, @socketopp! I actually got my previous comment completely flipped – the change we reverted in 2.24.1 eliminates the error message you observed and replaces it with a warning message that would have let you know that your auth token was formatted incorrectly and that you should check that you copied it correctly. We will be re-releasing this change soon, hopefully in the next CLI release, so going forward, the new message will likely help avoid this kind of confusion.
