### ISSUE TITLE
Update winget version

### ISSUE THREAD

**Issue by martinraiberfc** [getsentry/sentry-cli#1901]
You might want to update the version in winget. The current version panics during login.

**Comment by szokeasaurusrex** [comment]
Thank you for reporting, we will investigate this as soon as possible!

**Comment by szokeasaurusrex** [comment]
Hi @martinraiberfc, unfortunately, it appears that the `winget` package you are referring to is an unofficial package that is maintained by someone else, and so we cannot assist here.

To ensure you can always get the latest Sentry CLI version, I would recommend using one of our [official installation methods](https://docs.sentry.io/product/cli/installation/), instead.

**Comment by szokeasaurusrex** [comment]
Hi @martinraiberfc, I saw you left a 👎 on my previous comment.

Are you struggling to install via one of the [official installation methods](https://docs.sentry.io/product/cli/installation/)? I would be happy to assist you if you are 🙂
