### ISSUE TITLE
Add IP Address to User

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry-cli#191]
Our organization is used to seeing Sentry on a front-end application. For events they can always see the IP of the device under user:

![untitled](https://user-images.githubusercontent.com/9503662/34215769-7115368c-e574-11e7-8b1e-1b9a1eb050c5.png)

Where as `sentry-cli` doesn't track this. I was thinking to make a PR fixing this as I think it would be very similar to this line in `events.rs`:

    event.user.insert("username".into(), get_user_name().unwrap_or("unknown".into()));

The problem is all the methods I know of, require pinging (and thus relying on) an external server. For example `curl -s http://whatismyip.akamai.com/`.

The most efficient solution seems like it would be to have the server part of Sentry automatically append IP based on the location of the reporting device.

Does anyone have insights into whether the other Sentry projects record the external IP on the client or server?

**Comment by kirkins** [comment]
This crate might make the process easier if we want to add it on the client side:

https://github.com/equalsraf/whatsmyip

**Comment by jan-auer** [comment]
This has been released in 1.27.0
