### ISSUE TITLE
Xcode 15.2 --info-plist doesn't work

### ISSUE THREAD

**Issue by lionel-alves** [getsentry/sentry-cli#1925]
### Environment

What version of the CLI and what OS are you running?

2.27.0

### Steps to Reproduce

What you did?

run sentry-cli with `--info-plist` param

### Expected Result

What you thought would happen?
The plist is parsed correctly

### Actual Result

What actually happened?
Error parsing the plist. This is due to Xcode moving a lot of info from the plist to the pbxproj.

### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.
```
error: Could not parse Info.plist file
  caused by: Serde("missing field `CFBundleName`")
```

**Comment by szokeasaurusrex** [comment]
> run sentry-cli with `--info-plist` param

`sentry-cli --info-plist` is not a valid command.

So that I can reproduce your issue, what is the exact command you tried to run?

**Comment by adinauer** [comment]
@lionel-alves is this still an issue for you?
