### ISSUE TITLE
Could not parse Info.plist file  - caused by: Serde("invalid type: integer `32924`, expected a string")

### ISSUE THREAD

**Issue by kenyipp** [getsentry/sentry-cli#1936]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.18.0

**`react-native` version:** 0.70.13

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have the following issue:**

Since yesterday, I've been encountering the following error message when attempting to build the iOS app:

```
❌  error: Could not parse Info.plist file
    Run script build phase '[CP-User] Config codegen' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'react-native-config' from project 'Pods')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
Last lines of the Xcode's build log:
    export __IS_NOT_SIMULATOR_simulator\=NO
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Mylo-fcequrikxyqjreaosttkhtfkpnoi/Build/Intermediates.noindex/ArchiveIntermediates/Mylo/IntermediateBuildFilesPath/Mylo.build/Release-iphoneos/Mylo.build/Script-A31ED4BC5358436EB4C1FDEE.sh
  INFO    2024-02-09 00:33:23.878117 +00:00 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
error: Could not parse Info.plist file
  caused by: Serde("invalid type: integer `32924`, expected a string")
```
**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

Encountered an error when trying to build the app.

**Expected result:**

Successful build of the app without any issues.

**Comment by krystofwoldrich** [comment]
Alternatively, we should only parse `Info.plist` when we need it. Therefore only when `auto_release` read from plist is enabled.

https://github.com/getsentry/sentry-cli/blob/d902a76e7a65902da0722f022b7d425c5330df91/src/commands/react_native/xcode.rs#L360C15-L360C51

**Comment by kenyipp** [comment]
@krystofwoldrich  May I have your email so that I can send you my Info.plist? It's a bit urgent since all of the products in my company are using Sentry, and we are unable to release the apps now. Thanks!
