### ISSUE TITLE
Install of sentry node module fails (in proxy context)

### ISSUE THREAD

**Issue by passCulture-JL** [getsentry/sentry-cli#1944]
### Environment

What version of the CLI and what OS are you running?

macOS Sonoma 14.3.1 (M1 chip) with software proxy installed
LTS node version v20.11.1 (npm v10.2.4)
variable NODE_EXTRA_CA_CERTS='/.../xxxx.pem'
not connected as root
no setuid bit on node binary

### Steps to Reproduce

What you did?
```
yarn install
```
### Expected Result

What you thought would happen?
no error when downloading modules (works fine if we disable the software proxy)

### Actual Result

What actually happened?
the installation of sentry fails
If we try to test manually the command, detail is:
```...
% cd node_modules/@sentry/cli
% node ./scripts/install.js
[sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.19.4/sentry-cli-Darwin-universal
Error: connection interrupted
```

when we add logs, we saw that "totalBytes" is equal to "NaN" as if the "Content-Length" header was missing
is it possible in some cases ??

https://github.com/getsentry/sentry-cli/blob/c04070ab059afa7aad8b4fc4b739587538af6e92/scripts/install.js#L273C9-L273C20

### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.

```
[5/5] 🔨  Building fresh packages...
[1/16] ⢀ @sentry/cli
[13/16] ⢀ redacted
[11/16] ⢀ redacted
[9/16] ⢀ redacted
error /Users/redacted/AndroidStudioProjects/redacted/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments: 
Directory: /Users/redacted/AndroidStudioProjects/redacted/node_modules/@sentry/cli
```

**Comment by szokeasaurusrex** [comment]
@passCulture-JL What is/are the exact command(s) you are running to obtain the output shown in [your previous comment](https://github.com/getsentry/sentry-cli/issues/1944#issuecomment-1948296600)? Exactly how are you changing the code to obtain the above log entries?

If I install the Sentry CLI via `npm install @sentry/cli` or via `yarn add @sentry/cli`, the installation is successful, and I do not see the output referenced above. So, I will only be able to help you resolve your problem if you provide me the specific steps to reproduce your issue.

**Comment by szokeasaurusrex** [comment]
@passCulture-JL, what commands did you run to download the CLI (i.e. what command did you run to get the `@sentry/cli`  into your `node_modules` directory)? Could you also provide any log outputs of running the command?

You also should not need to run the `install.js` file explicitly; we call it automatically during the install process if needed.

**Comment by szokeasaurusrex** [comment]
Hi @passCulture-JL, okay, thank you for this information. Can you please provide the following information as well, to help me reproduce the issue?
  - The contents of your `yarn.lock` file (you can email this to me at daniel.szoke@sentry.io if you prefer not to share publicly on GitHub)
  - What "software proxy" are you using?

**Comment by szokeasaurusrex** [comment]
@passCulture-JL, okay, thank you for letting me know! In that case, I consider this issue resolved, and I will go ahead and close it. 

But, if you begin to experience the issue again, please reopen, and I will continue investigating using the information you have already provided me :)
