### ISSUE TITLE
`sourcemaps inject` does not support minified files with multi-line template literals and no `sourceMappingURL` comments

### ISSUE THREAD

**Issue by Zozman** [getsentry/sentry-cli#1955]
### Environment

`sentry-cli` version `2.28.6`; Mac OS X and Ubuntu

### Steps to Reproduce

Say you have a JavaScript file like the following that has a multi-line template literal:

### input.js
```javascript
var MyElement = class extends LitElement {
    constructor() {
      super(...arguments);
      this.isInitialized = true;
    }
    render() {
      return x`
        <div>
            <h1>My Element</h1>
        </div>
      `;
    }
  };

export {
   MyElement
};
```

Then suppose you compress this using something like `uglifyjs input.js -c -m --source-map "filename='bundle.js.map'" -o bundle.js`, producing a minified script file and a source map.  Importantly, you don't want to include a `sourceMappingURL` in the resulting JavaScript file because you do not plan to publish the map publicly and will only be uploading it to Sentry:

### bundle.js
```javascript
var MyElement=class extends LitElement{constructor(){super(...arguments),this.isInitialized=!0}render(){return x`
        <div>
            <h1>My Element</h1>
        </div>
      `}};export{MyElement};
```

### bundle.js.map
```
{"version":3,"file":"bundle.js.map","sources":["input.js"],"names":["MyElement","LitElement","constructor","super","arguments","this","isInitialized","render","x"],"mappings":"AAAA,IAAIA,wBAA0BC,WAC1BC,cACEC,MAAM,GAAGC,SAAS,EAClBC,KAAKC,cAAgB,CAAA,CACvB,CACAC,SACE,OAAOC;;;;OAKT,CACF,SAGCR,SACF"}
```

Assuming this is your minified code, you then want to run `sentry-cli sourcemaps inject .` to inject Debug Ids into both files to prepare them for upload to Sentry.

### Expected Result

The `sentry-cli` tool would identify `bundle.js` as minified code and `bundle.js.map` as the corresponding source map and add debug IDs to them.

### Actual Result

Neither of the files is identified as a target for adding IDs.  This is most likely because the [`is_likely_minified_js` function](https://github.com/getsentry/sentry-cli/blob/master/src/utils/sourcemaps.rs#L40) cannot rely on the existence of a `sourceMappingURL` comment and the `might_be_minified` library being used as a backup cannot handle a resulting minified file like this.

### Logs

```
sentry-cli sourcemaps inject ./dist --log-level=debug
  DEBUG   2024-02-21 20:21:09.563336 -08:00 sentry-cli version: 2.28.6, platform: "darwin", architecture: "arm64"
  INFO    2024-02-21 20:21:09.564783 -08:00 sentry-cli was invoked with the following command line: "sentry-cli" "sourcemaps" "inject" "./dist" "--log-level=debug"
> Searching ./dist
  DEBUG   2024-02-21 20:21:09.567314 -08:00 built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 4 required extensions, 0 regexes  (from globset)
  DEBUG   2024-02-21 20:21:09.568366 -08:00 glob converted to regex: Glob { glob: "**/*~", re: "(?-u)^(?:/?|.*/)[^/]*\\~$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([RecursivePrefix, ZeroOrMore, Literal('~')]) }  (from globset)
  DEBUG   2024-02-21 20:21:09.568405 -08:00 built glob set; 0 literals, 1 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes  (from globset)
  DEBUG   2024-02-21 20:21:09.568586 -08:00 whitelisting ./dist/bundle.js.map: Whitelist(IgnoreMatch(Types(Glob(Matched { def: FileTypeDef { name: "map", globs: ["*.map"] } }))))  (from ignore)
  INFO    2024-02-21 20:21:09.568615 -08:00 found: ./dist/bundle.js.map (296 bytes)
  DEBUG   2024-02-21 20:21:09.568826 -08:00 whitelisting ./dist/bundle.js: Whitelist(IgnoreMatch(Types(Glob(Matched { def: FileTypeDef { name: "js", globs: ["*.js"] } }))))  (from ignore)
  INFO    2024-02-21 20:21:09.568851 -08:00 found: ./dist/bundle.js (203 bytes)
> Found 2 files
> Analyzing 2 sources
> Analyzing completed in 0.012s
> Injecting debug ids
> Nothing to inject
  INFO    2024-02-21 20:21:09.582876 -08:00 Skipping update nagger update check
```

**Comment by Zozman** [comment]
As part of thinking about how you could solve this, put together #1956 as a possible idea.

**Comment by szokeasaurusrex** [comment]
Hey @Zozman, thank you for opening this issue and for creating #1956. 

However, after some initial investigation, I believe the problem you have identified may be more general than the scenario you have described. The CLI should likely be injecting Debug IDs into all JS files found in the directory the user passes to the CLI, regardless of whether they look like they are minified or not.

The `sourcemap inject` code also appears to be overcomplicated and difficult to understand, so it would probably benefit from a more comprehensive simplification and rewrite.

In the meantime, it appears that you can work around the issue by renaming the `bundle.js` and `bundle.js.map` files as `bundle.min.js` and `bundle.min.js.map`, respectively.

**Comment by Zozman** [comment]
> In the meantime, it appears that you can work around the issue by renaming the `bundle.js` and `bundle.js.map` files as `bundle.min.js` and `bundle.min.js.map`, respectively.

That does indeed work but I currently can't rename the files for deployment for _reasons_ unless I want to rename them, perform the injection, and then change the name back.  But then the name inside the `.map` file's `file` attribute won't match so the IDs won't link the source to the map in Sentry once uploaded, right?

It would be good if I could just tell sentry-cli "I know these are minified because I'm the human here" in some manor.

**Comment by adinauer** [comment]
Hey @szokeasaurusrex is currently out of office, he'll get back to you next week.

**Comment by szokeasaurusrex** [comment]
@Zozman, thank you for clarifying your situation!



> That does indeed work but I currently can't rename the files for deployment for _reasons_ unless I want to rename them, perform the injection, and then change the name back. But then the name inside the `.map` file's `file` attribute won't match so the IDs won't link the source to the map in Sentry once uploaded, right?

I _believe_ (although I am not 100% sure here) that it would actually be okay to rename the files, perform the injection, then rename the files back to the original, since we are using the debug ID to link the source file back to the sourcemap. So as long as the debug IDs in the source file and sourcemap still match, I believe the source mapping should work as expected.


> It would be good if I could just tell sentry-cli "I know these are minified because I'm the human here" in some manor.

To clarify my previous comment, the CLI should be injecting debug IDs into all JS source files in the path specified by the user when running `sourcemaps inject`, regardless of whether they appear to be minified or not. It is the user's responsibility to pass to the CLI the paths where they want the CLI to inject source files. 

That the CLI only injects debug IDs into files identified as "minified" is a bug. The CLI likely should not even be attempting to determine whether a JS file is minified or not during the `sourcemaps inject` command, since all JS files should be treated the same.

Therefore, the solution here is not to add an additional option like `--treat-source-as-minified`, but rather, the solution is essentially to treat all JS files the same way we are currently treating "minified" JS files.

Since the workaround I suggested does not work for you, I will prioritize getting a fix for this issue!
