### ISSUE TITLE
@sentry/bundler-plugin-core does not support macOs 11 version

### ISSUE THREAD

**Issue by luochentao-tal** [getsentry/sentry-cli#1978]
### Environment

What version are you running? Etc.

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by szokeasaurusrex** [comment]
Hi @luochentao-tal, please fill out the issue template with the following information:
  - **Environment**: Sentry CLI version and OS version
  - **Steps to reproduce**: What exactly did you do? Please list the exact commands you ran.
  - **Expected result**: What did you expect would happen?
  - **Actual result**: What actually happened?

I can only help you once you provide all of the above information.
