### ISSUE TITLE
Feature Request: Manage Project Keys with CLI

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-cli#2030]
Being able to manage project keys with the CLI will enable devs that are already using the CLI in their project release management workflow to programattically use a new DSN in production releases. This is an important part of some mobile dev workflows as it allows them to manage seperate releases' ingestion on the Sentry server more easily. 

See this comment for more details: https://github.com/getsentry/sentry/issues/68059#issuecomment-2034446539

cc @stephanie-anderson

**Comment by szokeasaurusrex** [comment]
@souredoutlook, to clarify, the feature you are requesting here is a new Sentry CLI command that would create a new DSN for a given project?

**Comment by bruno-garcia** [comment]
Important to note that outcome the customer wants to achieve: Disable old releases of their app. 
We're hoping to allow them to do this through a different tool: Remote Config. Though that might take a while so if maanging keys via CLI can help solve other use cases, might be worth considering it

**Comment by bruno-garcia** [comment]
> Hey @bruno-garcia , do you know if there's an ETA on the Remote Config tool? 😃

Not ETA at this time

**Comment by szokeasaurusrex** [comment]
Following an offline discussion with @souredoutlook and @bruno-garcia, we have decided not to implement this feature in Sentry CLI for now.

Users who wish to manage project keys programmatically can do so by [manually calling our API](https://docs.sentry.io/api/projects/create-a-new-client-key/).
