### ISSUE TITLE
[Question] sentry-cli releases set-commits --auto do not work in docker git context

### ISSUE THREAD

**Issue by r34son** [getsentry/sentry-cli#2031]
I am using @sentry/nextjs and build my app inside docker. Build fails when cli tries to resolve repository. [Logs](https://github.com/r34son/profile/actions/runs/8676176251/job/23790410125#step:7:1536)
Can i somehow associate commits to release using auto inside [docker git context](https://docs.docker.com/reference/cli/docker/image/build/#git-repositories)?

**Comment by szokeasaurusrex** [comment]
Hi @r34son, could you please try rerunning `sentry-cli releases set-commits` with `--log-level=debug`, then provide me with the output? I can assist you more easily with this information.

**Comment by r34son** [comment]
I quess i found [answer](https://docs.docker.com/reference/cli/docker/image/build/#git-repositories:~:text=The%20commit%20history%20isn%27t%20preserved) 
I dont want to create release while building app inside docker, because i need to init repo. That's why I've chosen github action, but there's another issue with that - release created twice https://github.com/getsentry/action-release/issues/189
