### ISSUE TITLE
Uploading the source map of the Electron project using sentry-cli has been successful, but the source code cannot be located

### ISSUE THREAD

**Issue by laotaipo** [getsentry/sentry-cli#2043]
### Environment

sentry-cli version 2.31.0 macos13.3.1 (22E261)

### Steps to Reproduce

I uploaded the sourceMap file for the Electron project using sentry-cli
<img width="1134" alt="image" src="https://github.com/getsentry/sentry-cli/assets/22850549/5ee9c395-4918-4ef8-b535-31870d520c1e">

### Expected Result

Hope to locate the project source code

### Actual Result

Unable to locate project source code
<img width="796" alt="image" src="https://github.com/getsentry/sentry-cli/assets/22850549/c7f976f8-1ed4-4aca-b557-315338ef3cbc">

**Comment by szokeasaurusrex** [comment]
Hi @laotaipo, I need more information to be able to help you. Please provide the following:

- The exact command or commands that you ran
- The output from the commands. Please run the commands with `--log-level=debug`, if possible
- Exact steps for me to be able to reproduce your bug. If your JavaScript source code is public, please provide a link to the source code so I can try to reproduce your issue against the same code you used.

I can only help you fix your problem once you have provided all of the above information. Let me know if you have trouble gathering this information.
