### ISSUE TITLE
send_envelope och send_event help msg change

### ISSUE THREAD

**Issue by elramen** [getsentry/sentry-cli#2049]
Remove "Check debug output for transmission errors by passing --log-level=debug" from send-envelope's and send-event's help message as this functionality does not seem to exist, e.g., turning off wifi does not give the user any error info. I believe this is a consequence of the actual transmission being handled in sentry-core which does not propagate errors back to sentry-cli.

**Comment by szokeasaurusrex** [comment]
Please see conversation on linked PR (#2048)
