### ISSUE TITLE
sentry-cli releases set-commits not able to find repo after 100 results

### ISSUE THREAD

**Issue by fallemand** [getsentry/sentry-cli#2055]
### CLI Version

2.31.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [x] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

Linux

### CLI Command
```
sentry-cli releases set-commits v109905.053264b --commit some-owner/traveler-frontend@053264b
```

### Exact Reproduction Steps

When we generate releases, we associate the commit with the following command.
```
sentry-cli releases set-commits v109905.053264b --commit some-owner/traveler-frontend@053264b
```
It was working fine till yesterday. Checking, we realized that now the repo `traveler-frontend` is in position 101, and we get the error: 
```
error: Unknown repo 'some-owner/traveler-frontend'
```

When we run 
```
sentry-cli repos list
```

Our repo is not showing up, since it's only showing till repo 100 (we notice it's going only till letter "s", and "t" is the next one ). 

### Expected Results

The repo should be found, even though more than 100 repos exists

### Actual Results

error: Unknown repo 'some-owner/traveler-frontend'

### Logs
```
  INFO    2024-05-02 10:21:55.732884270 +00:00 sentry-cli was invoked with the following command line: "/opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/@sentry/cli/node_modules/@sentry/cli-linux-x64/bin/sentry-cli" "releases" "set-commits" "traveler-frontend@v110137.a11539e" "--commit" "some-owner/traveler-frontend@a11539e"
error: Unknown repo 'some-owner/traveler-frontend'
```

**Comment by szokeasaurusrex** [comment]
In the meantime, you can use Sentry CLI version 2.31.0 as a workaround

**Comment by szokeasaurusrex** [comment]
@fallemand Can you please check whether this issue is fixed in version 2.31.2? The issue fixes a bug that might have also caused this issue. If it does, you can go ahead and close this issue

**Comment by niemisami** [comment]
2.31.2 started working for me  👍 Thank you for quick action!

**Comment by szokeasaurusrex** [comment]
@niemisami Great to hear, I am closing the issue in that case. Please reopen if anyone else encounters this issue again on 2.31.2.
