### ISSUE TITLE
Manual uploaded debug files are not shown on the website

### ISSUE THREAD

**Issue by hak-ioki** [getsentry/sentry-cli#2068]
### CLI Version

2.31.2

### Operating System and Architecture

- [X] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.4.1

### CLI Command

sentry-cli debug-files upload --auth-token MY_TOKEN \   --include-sources \   --org ioki-ez \   --project beiwagen \ ./DBFFM.app

### Exact Reproduction Steps

We had an [issue](https://github.com/getsentry/sentry/issues/71121) with uploading debug files with sentry-cli. For this reason, I tried to upload debug files manually via terminal, and the consol result said that it uploaded but in the website error remained. 

But, even after uploading these files, this error is still shown on the website:

<img width="873" alt="Screenshot 2024-05-17 at 16 17 18" src="https://github.com/getsentry/sentry-cli/assets/155530524/0318f4cc-80e1-414f-82c7-b5c197ac98cc">

### Expected Results

The error on the website should disappear.

### Actual Results

The error on the website still appears.

### Logs

I first uploaded dsym file directly:
```
sentry-cli debug-files upload --auth-token MY_TOKEN \
  --include-sources \
  --org ioki-ez \
  --project beiwagen \
> DBFFM
> Found 1 debug information file
> Resolved source code for 0 debug information files
> Prepared debug information file for upload
> Uploading completed in 0.411s
> Uploaded 1 missing debug information file
> File upload complete:

  UPLOADED fd7c4775-4d6b-3fa3-8095-642b4c1afc0d (DBFFM; arm64 executable)
```
But, after that, I couldn't see any changes on the website, so I uploaded the remaining parts here:

```
sentry-cli debug-files upload --auth-token MY_TOKEN \
  --include-sources \
  --org ioki-ez \
  --project beiwagen \
./DBFFM.app
> Found 26 debug information files
> Resolved source code for 0 debug information files
> Prepared debug information files for upload
> Uploading completed in 7.241s
> Uploaded 4 missing debug information files
> File upload complete:

  UPLOADED 974539b6-bfea-3801-8a7a-477a08536156 (Frameworks/PPRiskMagnes.framework/PPRiskMagnes; arm64 library)
  UPLOADED d92c5594-6e58-3566-bb50-65ee706d1ec7 (Frameworks/Common.framework/Common; arm64 library)
  UPLOADED c39a3874-3c35-31c4-b0e4-f490f7016c5a (PlugIns/BeiwagenTests.xctest/BeiwagenTests; arm64 library)
  UPLOADED ede288ae-d97b-3141-9e3d-af3e00f290cd (Frameworks/CommonAirship.framework/CommonAirship; arm64 library)
```

**Comment by szokeasaurusrex** [comment]
Let's keep the conversation in one place on https://github.com/getsentry/sentry/issues/71121
