### ISSUE TITLE
Download binary too slow

### ISSUE THREAD

**Issue by davidshimjs** [getsentry/sentry-cli#207]
Sentry-cli uses `install` npm script hook to download binary. but, downloading is so slow. When I execute `yarn`, `yarn add`, `yarn remove` commands, sentry-cli have tried install every time.

In my network situation, it takes more than 10 minutes.

I want to use only `@sentry/webpack-plugin` package. How can I solve this problem?

**Comment by t1ger-0527** [comment]
➕

**Comment by mitsuhiko** [comment]
We might want to mirror this on our own CDN. Github releases seems to be really slow for some countries.

**Comment by davidshimjs** [comment]
We solved the problem with our CDN. However, I forked the repository because it was not resolved with config defined in package.json.

**Comment by jan-auer** [comment]
Have you tried using `SENTRYCLI_CDNURL` environment variable? If set during installation time, it will use this URL to download the binary. Support for this was added back in version `1.27.1`

```sh
SENTRYCLI_CDNURL=https://mycdn.com yarn add @sentry/cli
# macOS will download: https://mycdn.com/sentry-cli-Darwin-x86_64
# Linux will download: https://mycdn.com/sentry-cli-Linux-x86_64
# Windows will download: https://mycdn.com/sentry-cli-Windows-x86_64.exe
```

**Comment by jan-auer** [comment]
For completeness, the other two options are to either install with

```sh
npm install --sentrycli_cdnurl=https://mycdn.com
```

or add an entry to your `.npmrc` file:

```rc
sentrycli_cdnurl=https://mycdn.com
```

I will add this to the docs, so it is more clear.

**Comment by jan-auer** [comment]
FWIW, I’m going to make a final change to this tomorrow and then add documentation.

**Comment by jan-auer** [comment]
Closing this, as there is not too much we can do. For now, we rely on GitHub release artifacts as CDN and while we might change this in the future, we will have to keep it that way for now. 

The [installation docs](https://docs.sentry.io/learn/cli/installation/#installation-via-npm) describe how to override the CDN, so you can set up your own mirror.

**Comment by dejan9393** [comment]
I'm still running into this issue constantly in our GitLab CI pipelines. There are days when they pass fine, and others where the pipeline comes to a grinding halt at `node scripts/install.js`:
<img width="535" alt="Screen Shot 2021-05-24 at 11 35 30 am" src="https://user-images.githubusercontent.com/13180986/119284915-307aef00-bc84-11eb-960f-79fb2ec2ba54.png">

This usually lasts until the job times out. For context, this is running on a Kubernetes executor.

I've updated to the latest version of @sentry/cli (1.64.2), but the problem persists. My current workaround is to pre-install @sentry/cli globally, then when `npm install` runs, it uses the cached binary, and that for whatever reason seems to work.

Here's the snippet from my Dockerfile:

```
# Hack to pre-download @sentry/cli to avoid issues with downloading the binary via scripts/install.js
# during the `npm install` command a little further down. There are several tickets regarding this issue in
# their tracker, none of which have an adequate solution. Most suggest using a different CDN, but instructions
# for setting up CDN are hard to come by.
RUN SENTRY_PACKAGE=`npm list @sentry/cli 2> /dev/null | awk 'NR!=1 && NF>1 {print $4}'` && \
 npm i -g $SENTRY_PACKAGE --unsafe-perm

RUN npm install
```

The hack isn't bulletproof as it basically reads the package.json/lock files to retrieve the required version of @sentry/cli, then installs it globally, but hoping that the workaround can shed some light on the problem. Could it be something to do with downloading the binary via a nested dependency? (we're requiring via @nuxtjs/sentry), or is it maybe related to the --unsafe-perms flag?

Any input would be appreciated

**Comment by kamilogorek** [comment]
> Most suggest using a different CDN, but instructions for setting up CDN are hard to come by. 

```sh
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```

This will use GitHubs release to fetch the binary. Can you give it a try?

**Comment by kamilogorek** [comment]
Thanks for the write-up, it will definitely come handy!
