### ISSUE TITLE
Author_email - Ensure this field has no more than 75 characters.

### ISSUE THREAD

**Issue by sakowicz** [getsentry/sentry-cli#2072]
### CLI Version

2.32.1

### Operating System and Architecture

- [X] macOS (arm64)
- [X] macOS (x86_64)
- [X] Linux (i686)
- [X] Linux (x86_64)
- [X] Linux (armv7)
- [X] Linux (aarch64)
- [X] Windows (i686)
- [X] Windows (x86_64)

### Operating System Version

macOS 14.5

### CLI Command

sentry-cli releases set-commits XXX --local -p YYY --ignore-missing

### Exact Reproduction Steps

1. Create a commit with commit author email longer than 75 chars.
2. Run `sentry-cli releases set-commits XXX --local -p YYY --ignore-missing`

### Expected Results

Remove `author_email` field if it does not require sentry-api expectations (it is [optional](https://github.com/getsentry/sentry/blob/master/src/sentry/api/serializers/rest_framework/commit.py#L28)).

### Actual Results

It doesn't send commits to sentry-api, because we get 400.

I wonder if we could remove `author_email` field if it does not require sentry-api expectations.

If not, can you help me solve the issue on my side? I've changed that email for future commits, but they will be in the history forever. I don't know how to push only newer commits.

### Logs

```
  DEBUG   2024-05-29 08:04:27.462029 +02:00 body: {"commits":{"author_email":["Ensure this field has no more than 75 characters."]}}
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object {"commits": Object {"author_email": Array [String("Ensure this field has no more than 75 characters.")]}}
```

**Comment by szokeasaurusrex** [comment]
Hi @sakowicz, thank you for reporting this issue. I am going to discuss this issue with the team responsible for maintaining the Sentry backend, since I think it might make more sense to increase the character limit and/or truncate excess characters on the backend, rather than making changes in the CLI.

**Comment by sakowicz** [comment]
Thank you @szokeasaurusrex , I wonder if you can suggest me something to fix the issue temporarily on my side?

**Comment by szokeasaurusrex** [comment]
@sakowicz, assuming this is your first release, you can use the `--initial-depth` flag to set the number of commits that should be included in the first release. Set this flag small enough so that only commits with the shorter email address are included.

Let me know whether that helps!

**Comment by sakowicz** [comment]
@szokeasaurusrex Unfo, this is not my first release.

**Comment by szokeasaurusrex** [comment]
@sakowicz, in that case, you might be able to use the `--commit` flag to manually specify which commits to include, instead of using the `--local` flag. You can pass `--commit` multiple times for each commit you wish to include in the release. 

Let me know whether that works!

**Comment by sakowicz** [comment]
@szokeasaurusrex It helped! Thank you ;-)

**Comment by szokeasaurusrex** [comment]
Glad to hear it! I will keep this issue open, since I am still working to determine whether we can increase the limit in the backend or whether we will need to implement some fix in the CLI
