### ISSUE TITLE
API refactor: Split data types into separate submodules

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-cli#2077]
Data types are types which exist primarily for serializing/deserializing request/response data. Examples include `User` and `ReleaseStatus`.

**Comment by szokeasaurusrex** [comment]
Or, perhaps it makes more sense to move this into `sentry-rust`

**Comment by stephanie-anderson** [comment]
Maybe get @Swatinem or @loewenheim's opinion on that

**Comment by Swatinem** [comment]
Also discussed with @elramen recently that IMO we shouldn’t bloat the SDK with types and definitions that are not directly useful for the SDK itself.

**Comment by szokeasaurusrex** [comment]
@Swatinem I was considering that we might implement this change as a new feature under `sentry-types`, so as not to increase binary size when not needed.

However, you have a fair point – the code would be, at least initially, only used in the CLI, so probably makes more sense to keep the code in the CLI. We can always reevaluate later

**Comment by szokeasaurusrex** [comment]
See comment on #2008
