### ISSUE TITLE
Source-map not work

### ISSUE THREAD

**Issue by wuweikd** [getsentry/sentry-cli#2082]
### CLI Version

2.23.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [X] Windows (x86_64)

### Operating System Version

windows 10

### CLI Command

sentry-cli releases files 1.0.0 upload-sourcemaps dist --url-prefix http://127.0.0.1:56021/appservice

### Exact Reproduction Steps

First, I use  `sentry-cli releases files 1.0.0 upload-sourcemaps dist --url-prefix http://127.0.0.1:56021/appservice` upload my source-maps.

And i can find it at my sentry platform：

![image](https://github.com/getsentry/sentry-cli/assets/34428646/c7e3c324-ee76-4007-90a7-addc0bfe811e)

But，I don't know what how to use `--url-prefix`. So , I upload other source-maps with  different `--url-prefix`:
![image](https://github.com/getsentry/sentry-cli/assets/34428646/fc4199d7-23e7-461e-9a16-8165dcf167fb)

![image](https://github.com/getsentry/sentry-cli/assets/34428646/6fb226dd-2150-4127-a269-824be76105bc)

When I throw an Error,I get it in my Sentry platform，but it can't use source-map.
![image](https://github.com/getsentry/sentry-cli/assets/34428646/0f87eedb-2831-4fbd-84f7-baa9fb9571bb)

### this is my  js:
![image](https://github.com/getsentry/sentry-cli/assets/34428646/17714eb3-3ea2-4e8e-85d4-49deba48ee4e)

### this is my map:
![image](https://github.com/getsentry/sentry-cli/assets/34428646/fe8ee55c-ce28-404b-9703-ea1f0210968e)

I don't know why it can't work。

----

So, I use  sentry.io  to try once time.

![image](https://github.com/getsentry/sentry-cli/assets/34428646/9d9c050d-21e4-4530-adfe-4aa52c96d14f)

![image](https://github.com/getsentry/sentry-cli/assets/34428646/62ab9b59-d8c1-4f1a-8d74-36788f72182a)

But, soucre-map doesn't work again,

 

### Expected Results

source-map work well

### Actual Results

source-map not work 

### Logs

 D:\wxworkspace\taroRN> sentry-cli releases files 1.0.0 upload-sourcemaps dist --url-prefix http://127.0.0.1:56021/appservice
> Found 27 files
> Analyzing 27 sources
> Analyzing completed in 0.006s
> Rewriting sources
> Rewriting completed in 0.036s
> Adding source map references
> Bundling completed in 0.087s
> Bundled 27 files for upload
> Bundle ID: 5c97fd4d-5866-57da-9826-6b43331940e5
> Optimizing completed in 0.004s                                                                                                                                                    
> Uploading completed in 0.245s
> Processing completed in 0.107s
> File upload complete (processing pending on server)
> Organization: sentry
> Project: huitian-mini-program
> Release: 1.0.0
> Dist: None
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    http://127.0.0.1:56021/appservice/app.js (sourcemap at app.js.map)
    http://127.0.0.1:56021/appservice/common.js (sourcemap at common.js.map)
    http://127.0.0.1:56021/appservice/comp.js (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for http://127.0.0.1:56021/appservice/comp.js)
    http://127.0.0.1:56021/appservice/pages/home/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/login/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/news/detail/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/news/list/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/pay/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/share/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/test/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/pages/webview/index.js (sourcemap at index.js.map)
    http://127.0.0.1:56021/appservice/runtime.js (sourcemap at runtime.js.map)
    http://127.0.0.1:56021/appservice/taro.js (sourcemap at taro.js.map)
    http://127.0.0.1:56021/appservice/pages/pay/index.js.map
    http://127.0.0.1:56021/appservice/pages/share/index.js.map
    http://127.0.0.1:56021/appservice/pages/test/index.js.map
    http://127.0.0.1:56021/appservice/pages/webview/index.js.map
    http://127.0.0.1:56021/appservice/runtime.js.map
    http://127.0.0.1:56021/appservice/taro.js.map
    http://127.0.0.1:56021/appservice/vendors.js.map
PS D:\wxworkspace\taroRN>

**Comment by szokeasaurusrex** [comment]
Hi @wuweikd, what happens if you run the command without the `--url-prefix` flag? It might not be needed here.

**Comment by wuweikd** [comment]
> Hi @wuweikd, what happens if you run the command without the `--url-prefix` flag? It might not be needed here.

If I don't use `--url-prefix` , it will be  ` ~/app-service.js.map` . It's same  as ` --url-prefix "~"`, and I had try ` --url-prefix "/"`.

![image](https://github.com/getsentry/sentry-cli/assets/34428646/f17a2117-a2d9-4260-b7bf-d2a125906b64)

![image](https://github.com/getsentry/sentry-cli/assets/34428646/03ce1c47-c0d7-4496-870a-e731ac22657d)

![image](https://github.com/getsentry/sentry-cli/assets/34428646/8fba6291-6b94-4339-a665-85168526dbca)


**May be the version `1.0.0` is wrong ? Where can I know what version I should set?**

**Comment by szokeasaurusrex** [comment]
Hey @wuweikd – it actually looks like your main problem is that you only uploaded the `~/app-service.js.map` source map file. In order for source maps to work, you also need to upload your JavaScript source code.

**Comment by wuweikd** [comment]
Okay, I got it. Maybe you know about the WeChat mini program. I can't access the `app-service.js` because it's very closed. Thank you very much for your answer.

**Comment by RG100-EMUX** [comment]
I have same problem, but i uploaded js files. I upload multiple artifacts (in console no warnings and errors while uploading sourcemaps)
<img width="1041" alt="Image" src="https://github.com/user-attachments/assets/8ffc08a2-6603-4bae-935d-d4588798429a" />
<img width="1034" alt="Image" src="https://github.com/user-attachments/assets/c5147ceb-9b1e-4c5c-84f1-7e12862d6f3a" />
<img width="1038" alt="Image" src="https://github.com/user-attachments/assets/286b712c-7b16-4fae-b3dc-9712eb84b42c" />
<img width="1043" alt="Image" src="https://github.com/user-attachments/assets/1c8758a9-156e-42f8-bd72-87d8ef6c81a4" />
<img width="1039" alt="Image" src="https://github.com/user-attachments/assets/44078c6f-58f9-4d03-ad8c-e533c65ca4c4" />
<img width="1040" alt="Image" src="https://github.com/user-attachments/assets/b807e4dc-55db-49d5-9ed1-52c92dac9e95" />
<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/48dcd60c-4f4b-473e-82bc-61f501a61bbb" />
<img width="1032" alt="Image" src="https://github.com/user-attachments/assets/4ab74de3-6e20-474e-a644-76818d22935f" />

And i still have a minified stack trace.
<img width="913" alt="Image" src="https://github.com/user-attachments/assets/8c6c426c-e226-4097-a18b-b0924c9656c9" />

It's self-hosted Sentry, and i have no idea how fix this.
