### ISSUE TITLE
Improve error message when previous release sha could not be found.

### ISSUE THREAD

**Issue by leonard84** [getsentry/sentry-cli#2093]
The error message is devoid of helpful information to diagnose this problem.

Please add the previous release and the hash that Sentry is trying to locate to the error message.
Even setting the log level to debug does not seem to log that information.

`error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.`

**Comment by szokeasaurusrex** [comment]
@leonard84, can you please provide the exact command that you tried to run, and also describe what you were trying to accomplish? And, do you have any suggestions for how we could improve the error message? From what I can tell, the current message seems to be providing some helpful tips on how to fix the problem, so could you please help me understand what you think is missing from the message?
