### ISSUE TITLE
github actions refuses to accept SENTRY_AUTH_TOKEN

### ISSUE THREAD

**Issue by trixobird** [getsentry/sentry-cli#2105]
### CLI Version

2.32.2

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [X] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

not sure, it is github action runner

### Link to reproduction repository

https://github.com/adsviewer/turboviewer

### CLI Command

sentry-cli --log-level=debug sourcemaps inject --org adsviewer --project server ./dist && sentry-cli sourcemaps upload --org adsviewer --project server ./dist

### Exact Reproduction Steps

1. trigger the CI from actions for branch `255-bring-back-sentry-in-the-be` 

Please note that the cli command succeeds if run locally with the same `SENTRY_AUTH_TOKEN` in .env

The repo is public. Things of note
sentry command: https://github.com/adsviewer/turboviewer/blob/c6ab0e4b0477158ab896cffe11a5d38e5d338e5f/apps/server/package.json#L19
ci pipeline: https://github.com/adsviewer/turboviewer/blob/c6ab0e4b0477158ab896cffe11a5d38e5d338e5f/.github/workflows/ci.yml#L1-L0

### Expected Results

CI should succeed

### Actual Results

CI fails with error: Auth token is required for this request. Please run `sentry-cli login` and try again!

### Logs

```
> server@1.0.0 sentry:sourcemaps /home/runner/work/turboviewer/turboviewer/apps/server
> sentry-cli --log-level=debug sourcemaps inject --org adsviewer --project server ./dist && sentry-cli sourcemaps upload --org adsviewer --project server ./dist

  DEBUG   2024-07-18 14:39:41.296011940 +00:00 sentry-cli version: 2.32.2, platform: "linux", architecture: "x86_64"
  INFO    2024-07-18 14:39:41.296074767 +00:00 sentry-cli was invoked with the following command line: "/home/runner/work/turboviewer/turboviewer/node_modules/.pnpm/@sentry+cli-linux-x64@2.32.2/node_modules/@sentry/cli-linux-x64/bin/sentry-cli" "--log-level=debug" "sourcemaps" "inject" "--org" "adsviewer" "--project" "server" "./dist"
> Searching ./dist
    02602aa3-82a0-50df-8a2c-517598f0e0aa - ./dist/contexts/user/user-invite.js.map
    f14d9a37-49b3-5ca4-beac-5553ee2e489c - ./dist/contexts/user/user-roles.js.map
    fdc404a6-3652-5bc1-983d-df5ed385f792 - ./dist/contexts/user/user.js.map
    f1fe3521-6c91-5cf4-84b2-0d6318ab6d65 - ./dist/email.js.map
    88703bf1-3092-56bb-8f29-5fad6ef659ec - ./dist/emailable-helper.js.map
    3229aee5-4557-5d57-a1f5-e86b8f2694f1 - ./dist/index.js.map
    38525bed-8657-5ce3-a369-b18f88c20fe5 - ./dist/instrument.js.map
    94a25351-0def-5b3e-a86f-735d044a9660 - ./dist/language.js.map
    f44f06a1-7513-54e3-8927-d84183f7a380 - ./dist/schema/builder.js.map
    cba48f70-22a6-53d5-a80f-dd56b57785d0 - ./dist/schema/codegen.js.map
    da09c8fc-6313-5a21-a316-04d0785281ee - ./dist/schema/errors.js.map
    74bd4070-d244-5945-8d62-f8fd3bdca50f - ./dist/schema/index.js.map
    f7589195-8191-5956-9d16-300acefd367b - ./dist/schema/integrations/insights-operations.js.map
    07756cde-f90c-557e-943d-ea8191c8e87e - ./dist/schema/integrations/integration-operations.js.map
    abeec986-215d-5d29-bd73-caed4a113bca - ./dist/schema/integrations/integration-types.js.map
    cb78bf81-d50b-5fd9-8502-[136](https://github.com/adsviewer/turboviewer/actions/runs/9993504356/job/27621259473#step:10:150)6e0a9829d - ./dist/schema/organization/org-types.js.map
    afec9cfd-f1c0-5cc7-937d-6853b9f1dc79 - ./dist/schema/organization/organization-operations.js.map
    517267f7-2398-5d07-a550-a4eb218f5615 - ./dist/schema/pubsub.js.map
    f2eaad33-3250-5aee-8011-9500fe3e81d2 - ./dist/schema/user/invite-operations.js.map
    675fca63-7d3b-5b5d-8036-f027d2fc3ba6 - ./dist/schema/user/social-login-operations.js.map
    287b24b1-a391-587a-ba3e-1f53b3536c6e - ./dist/schema/user/user-operations.js.map
    6dd45a21-bb89-58ed-b28e-959604663172 - ./dist/schema/user/user-types.js.map
    39988270-382e-58b7-88f0-cbffee9f92bc - ./dist/utils/data-object-utils.js.map
    09b23ee1-4c2a-519f-bed4-a6bc6bf7510a - ./dist/utils/error-utils.js.map
    05954723-9ae4-52f4-9405-4dcc5f7a3e5b - ./dist/utils/express-utils.js.map
    794609c5-7cd5-5f95-a468-a1f71716c6e9 - ./dist/utils/insights-query-builder.js.map
    241643d1-05fc-5f20-b0ba-9e8802a62c71 - ./dist/utils/lambda-utils.js.map
    5bb53d34-e2b9-562c-8bb2-28f292f[199](https://github.com/adsviewer/turboviewer/actions/runs/9993504356/job/27621259473#step:10:213)73 - ./dist/utils/rate-limiter.js.map
    9dbf5a33-0b4d-55ca-910c-b5fa7a64ec0c - ./dist/utils/sns-subscription-utils.js.map

  DEBUG   2024-07-18 14:39:41.367476460 +00:00 skipping update nagger because session is not attended
error: Auth token is required for this request. Please run `sentry-cli login` and try again!

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by szokeasaurusrex** [comment]
@trixobird Thank you for reporting this issue!

From what you have described, I highly suspect that this problem is caused by your CI being misconfigured. Most likely, what is happening is that the `SENTRY_AUTH_TOKEN` environment variable that you are setting in CI is not being passed to the [`sentry:sourcemaps` script](https://github.com/adsviewer/turboviewer/blob/6d48e1169bb3254388d53ae08058613ea3a6af7a/apps/server/package.json#L19), which from what I can tell, is where you have defined the sourcemaps uploading command.

As a sanity check, you could add another script next to the `sentry:sourcemaps` script which just does `echo $SENTRY_AUTH_TOKEN`, then you could try running this in your CI to see if anything gets output. If nothing gets output, this would confirm my suspicion that `sentry-cli` simply is not getting access to your auth token. If that is the case, as I suspect, then I cannot really provide much more assistance since the CLI would be behaving as expected – you would just need to figure out how to correct your CI configuration so that `sentry-cli` gets access to the `SENTRY_AUTH_TOKEN` environment variable, or you would need to pass the token in a different way (e.g. via the `--auth-token` command line flag).

**Comment by trixobird** [comment]
hi @szokeasaurusrex , thank you for your response. I have confirmed that my ci/cd has access, I passed it in plain text and echo'ed it just before executing the pnpm build command. I know that this is weird and shouldn't happend since as mentioned beofre locally it does work. Let me know if you have any other thoughts

**Comment by szokeasaurusrex** [comment]
@trixobird Maybe the scripts within the `pnpm build` command are not getting access to environment variables in CI for some reason. That is why I would suggest trying to `echo` the `SENTRY_AUTH_TOKEN` in a script that gets run _within the `pnpm build` command_. Only then can we know for sure whether this is a Sentry CLI bug, or a configuration problem.

**Comment by trixobird** [comment]
ah got it, I'll try and comment in a tiny bit. Thank you very much for the suggestion

**Comment by trixobird** [comment]
figure it out :) You were right the pnpm script didn't have access to the SENTRY_AUTH_TOKEN environment variable. The reason was turbo repo. In turborepo the root package does has access to all the environment variables, but if you wish the child packages (apps in my case) to have access to them, you need to list them on the `turbo.json` file that I have completed forgotted to do so. 

Again thank you for your thoughtfull comments and suggestion.

**Comment by szokeasaurusrex** [comment]
Cool, glad I could help you figure it out!

**Comment by alessandro-martino-triberunclub** [comment]
I've had a similar issue and managed to resolve it by passing the SENTRY_AUTH_TOKEN in the `docker build` command as an argument:

`docker build \
          --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .`

In the Dockerfile I've added the following:

`ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN`
