### ISSUE TITLE
Improve "release not found" error message

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-cli#2111]
> @szokeasaurusrex maybe we can improve the error message in Sentry CLI?
> 
> Suggestion: 
> error: Release not found. Verify that you have configured the right organization and project for this operation. 

 _Originally posted by @lforst in [#495](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/495#issuecomment-2262351854)_

**Comment by lforst** [comment]
@szokeasaurusrex lmk when this is released so we can bump the bundler plugins!
