### ISSUE TITLE
sentryCli.createRelease is not a function

### ISSUE THREAD

**Issue by montogeek** [getsentry/sentry-cli#213]
HI!
I am getting this error through the webpack plugin:
```
95% emitting/data/context/apps/facebook/node_modules/@sentry/webpack-plugin/src/index.js:34      
	.createRelease(release)

TypeError: sentryCli.createRelease is not a function
```

I am using `"@sentry/webpack-plugin": "1.1.2"` and webpack 3.6.0

I only get this error on Travis CI, can't reproduce it locally.

Any idea what could be causing it?

**Comment by samosad** [comment]
same error on local build
```
TypeError: sentryCli.createRelease is not a function
    at Compiler.<anonymous> (/Users/atabakman/Projects/web/node_modules/@sentry/webpack-plugin/src/index.js:34:8)
    at next (/Users/atabakman/Projects/ride-share/web/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/atabakman/Projects/web/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by jan-auer** [comment]
We have introduced a breaking change in the JavaScript API in `1.28.0` (see the release notes). Also note that as opposed to [`sentry-webpack-plugin`](https://github.com/getsentry/sentry-webpack-plugin), we still consider the JS API of Sentry CLI internal/unstable until we start to officially document it.

The new way to invoke this is now:
```js
sentryCli.releases.new(RELEASE_NAME);
```

Have a look at [this PR](https://github.com/getsentry/sentry-webpack-plugin/pull/18/files#diff-1fdf421c05c1140f6d71444ea2b27638R39) to see all the changes.

**Comment by jan-auer** [comment]
Oh, I missed that you are actually using the webpack plugin. For the future, please file issues related to the plugin in its own repository. Thank you 😄 

That being said, sorry about the inconvenience. For some reason the webpack plugin was not merged and released in time. You can track getsentry/sentry-webpack-plugin#18, if you are interested.
