### ISSUE TITLE
Using Sentry Electron / Sentry Cli when building will attempt to download a version of sentry-cli that doesn't exist

### ISSUE THREAD

**Issue by deathlyrage** [getsentry/sentry-cli#2142]
### CLI Version

2.24.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)
- [X] Windows (ARM64)

### Operating System Version

Windows 11 24H2

### Exact Reproduction Steps

When attempting to run Yarn build on a Windows Dev Kit 2023 (Arm for Windows) or Surface Pro 9 or 10 electron will fail to build using yarn build.

```
error C:\alderongames-launcher\node_modules\@sentry\cli: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments:
Directory: C:\alderongames-launcher\node_modules\@sentry\cli
Output:
[sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.18.1/sentry-cli-Windows-aarch64.exe
```

While I know you guys don't have a native version for windows on arm, i suggest updating the code to download the X64 version as it can run successfully without blocking the build from working.

If you know of any other workarounds to get this working let me know.

**Comment by deathlyrage** [comment]
The URL it tries to download from `https://downloads.sentry-cdn.com/sentry-cli/2.18.1/sentry-cli-Windows-aarch64.exe`  returns 403 Forbidden

**Comment by szokeasaurusrex** [comment]
@deathlyrage I noticed you listed your CLI version as `2.24.1`, which is a few months old at this point. Does this same problem occur if you try to use a newer version of Sentry CLI?

Also, to clarify, have you tried installing Sentry CLI using an installation method other than `npm`/`yarn`? You might be able to workaround the problem by installing Sentry CLI using one of the [other supported methods](https://docs.sentry.io/cli/installation/#manual-download), such as a manual download from our [releases page](https://github.com/getsentry/sentry-cli/releases/tag/2.34.1).

**Comment by deathlyrage** [comment]
2.34.1 is the latest version of the sentry cli published on NPM. It was published 8 days ago.
https://www.npmjs.com/package/@sentry/cli/v/2.34.1?activeTab=versions

im referring to the NPM package version not the sentry-cli exe version. 

I got the version number wrong on the OP.

Regardless I'll re-test and let ya know.

**Comment by deathlyrage** [comment]
Update: looks like one of my dependency chain was forcing it to run the older version, was able to force it and now appears to be fixed. Thanks!

**Comment by szokeasaurusrex** [comment]
Cool, glad to hear it! Please feel free to reach out again if you encounter any other issues, we are always happy to help 😃
