### ISSUE TITLE
Install script fails on fresh install of macOS

### ISSUE THREAD

**Issue by tomlokhorst** [getsentry/sentry-cli#2145]
On my newly installed macOS 15 (beta), the directory `/usr/local/bin` doesn't exist.

This causes the install script to fail, but the error message is a bit unclear:

```
> curl -sL https://sentry.io/get-cli/ | bash
This script will automatically install sentry-cli (latest) for you.
Installation path: /usr/local/bin/sentry-cli
######################################################################## 100.0%
Password:
mv: rename /var/folders/mc/bl2sqq8s1sv177f8nbq5ck100000gn/T//.sentrycli.vQtx55Ex to /usr/local/bin/sentry-cli: No such file or directory
```

Ideally, the script should create the directory, or show an error message.

(Obviously, now that I know what the problem is "No such file or directory" makes sense. But when I first saw the error, I assumed the input file was missing)

**Comment by szokeasaurusrex** [comment]
Hey @tomlokhorst, thank you for reporting this issue! Interesting that no one has spotted it yet. You should be able to work around the problem by manually creating the `/usr/local/bin` directory, and we will aim to get this fixed soon

**Comment by szokeasaurusrex** [comment]
I was able to reproduce this issue by setting a custom `INSTALL_PATH` environment variable, which overrides the default `/usr/local/bin`.

It appears that the install script is smart enough to create the install directory if its parent directory exists already.

For example, if we want to install to the default `/usr/local/bin`, the script will create `/usr/local/bin` as long as `/usr/local/bin` does not exist and `/usr/local` does exist and is a directory. But, if `/usr/local` does not exist, we get the error.

**Comment by szokeasaurusrex** [comment]
Hi @tomlokhorst, I just merged a fix. The install script lives in a different, private repository from the Sentry CLI code, which is why you likely will not be able to see the PR and commit which closes this issue. It might take several hours before the new script is live at https://sentry.io/get-cli/.
