### ISSUE TITLE
[cocoa] extra directory attribute for --include-sources

### ISSUE THREAD

**Issue by barisyild** [getsentry/sentry-cli#2153]
--include-sources doesn't find all source directories, it should be possible to add them manually.

**Comment by szokeasaurusrex** [comment]
Hi @barisyild, is this a bug report or a feature request?

If it's a bug report, please re-open the issue with our [bug report template](https://github.com/getsentry/sentry-cli/issues/new?template=BUG_REPORT.yml).

If it's a feature request, please explain in more detail how you would like this new feature to work and how exactly this feature will help you.

**Comment by barisyild** [comment]
> Hi [@barisyild](https://github.com/barisyild), is this a bug report or a feature request?
> 
> If it's a bug report, please re-open the issue with our [bug report template](https://github.com/getsentry/sentry-cli/issues/new?template=BUG_REPORT.yml).
> 
> If it's a feature request, please explain in more detail how you would like this new feature to work and how exactly this feature will help you.

I add the compiled code to the project as a static binary, so I think it is normal that include-sources cannot find the source code.
If we can add directories manually, there is no such problem.

**Comment by barisyild** [comment]
> Hi [@barisyild](https://github.com/barisyild), I am still missing context on what you are trying to do.
> 
> What is the exact command you are running? What are you trying to accomplish with Sentry CLI?

https://docs.sentry.io/platforms/apple/guides/ios/dsym/#xcode-build-phase

I run the cli command in the link above, but it only sends a small part of the source code, the part it does not send is linked as a static link.

**Comment by szokeasaurusrex** [comment]
@barisyild Are your stack traces not being symbolicated in Sentry because of this?

**Comment by szokeasaurusrex** [comment]
> It symbolizes but does not show the source code, because it is missing.

Got it. Have you tried using the [Creating Source Bundles](https://docs.sentry.io/cli/dif/#creating-source-bundles) to bundle your source files manually? This command allows you to manually specify the path to your debug files, and the command finds the source files based on the debug files.
