### ISSUE TITLE
Environments leaking across projects

### ISSUE THREAD

**Issue by jasondentler** [getsentry/sentry-cli#2156]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have 4 distinct web applications within a monorepo. Each application has a corresponding project in Sentry. 
We use git hashes as release ids. 
We also specify a dist because a commit can be built multiple times by our CI/CD pipeline. 
Our deploy ids use semantic versioning, and each app is versioned independently. (App A can be on v1.23.5 while App B is on v9.173.2)
When creating a deployment, we specify the deployment name (app's semantic version), project, release & environment. 

P.S. The documentation offers no guidance on Sentry best practices for common scenarios like a monorepo, so we're making it up as we go along.

Kobby Bawuah @ Sentry support recommended opening a bug here. You can refer to support issue #131315 for my details. 

### Expected Result

Despite being on a monorepo, I don't want any cross-talk between my projects. When I create a deployment for one project, I really do mean just that one project. If I deploy multiple projects, I'll create a deployment for each one. 

imo, each project should have independent releases, source maps, deployments, and environments. The only thing I want at the org level are user accounts, teams, and my billing info.

If I've only ever deployed App A to Environment X, then Environment X should **only** appear in the project for App A.

### Actual Result

However, when I look in Sentry, everything is a jumbled mess of data smeared across all my projects. 

- The environment I only specified for a deployment in App A now shows in all my projects.
- The deployment email says I've deployed all the apps that share that release, when I created the deploy for 1 specific project.
- I have no way to see the deploy name (semantic version) in the Sentry UI. I don't see the deployment entity represented in the Sentry UI anywhere.
- Releases only show the timestamp and environment of the most recent deployment. How can I tell what other environments may have been affected by a bug?

### Product Area

Releases

**Comment by jasondentler** [comment]
Thanks @ceorourke and @mifu67 for investigating!

**Comment by szokeasaurusrex** [comment]
Hi @jasondentler, thanks for opening the issue. I am attending a conference through this Wednesday, but will take a deeper look into this issue when I am back on Thursday.

**Comment by szokeasaurusrex** [comment]
@jasondentler, just merged a bugfix, which will ensure `sentry-cli deploys new` now respects the `--project` argument. I plan to release the changes early next week.
