### ISSUE TITLE
Installation/Upgrade fails under macOS Sequoia Due To SSL Issue

### ISSUE THREAD

**Issue by stherold** [getsentry/sentry-cli#2159]
### CLI Version

2.36.1

### Operating System and Architecture

- [x] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 15.0 (24A335)

### CLI Command

brew install getsentry/tools/sentry-cli AND curl -sL https://sentry.io/get-cli/ | bash

### Exact Reproduction Steps

Run `brew install getsentry/tools/sentry-cli`and get:

```shell
==> Fetching getsentry/tools/sentry-cli
==> Downloading https://downloads.sentry-cdn.com/sentry-cli/2.36.1/sentry-cli-Darwin-universal
curl: (7) Failed to connect to downloads.sentry-cdn.com port 443 after 1 ms: Couldn't connect to server

Error: sentry-cli: Failed to download resource "sentry-cli"
Download failed: https://downloads.sentry-cdn.com/sentry-cli/2.36.1/sentry-cli-Darwin-universal
```

Run `curl -L https://sentry.io/get-cli` and get:

```shell
curl: (7) Failed to connect to sentry.io port 443 after 11 ms: Couldn't connect to server

```

Run `ping sentry.io` and get:

```shell
PING sentry.io (0.0.0.0): 56 data bytes
ping: sendto: Socket is not connected
Request timeout for icmp_seq 0
ping: sendto: Socket is not connected
Request timeout for icmp_seq 1
ping: sendto: Socket is not connected
Request timeout for icmp_seq 2
ping: sendto: Socket is not connected
Request timeout for icmp_seq 3
ping: sendto: Socket is not connected
Request timeout for icmp_seq 4
ping: sendto: Socket is not connected
Request timeout for icmp_seq 5
ping: sendto: Socket is not connected
Request timeout for icmp_seq 6
ping: sendto: Socket is not connected
Request timeout for icmp_seq 7
ping: sendto: Socket is not connected
```

### Expected Results

It should just install the tool.

### Actual Results

See above in reproduction steps.

### Logs

See above in reproduction steps.

**Comment by szokeasaurusrex** [comment]
Hi @stherold, given that pinging `sentry.io` does not work, this seems like it is most likely some network configuration problem. Do you experience similar troubles when trying to access any other URLs?

**Comment by stherold** [comment]
Ooops, in my home network I have installed Adguard on an raspberry pi and use it as DNS server. Fun fact is that sentry.io is part of one blocklist I use (I had no idea) 😃 So I whitelisted it and now it works 🙏

**Comment by stherold** [comment]
> [!tip]
> Maybe you should think about separating the website domain from the API / tool domains so that not Sentrie's tracking business affects tool installation 🤔
