### ISSUE TITLE
started, finished, time

### ISSUE THREAD

**Issue by saiichihashimoto** [getsentry/sentry-cli#217]
What do these flags accomplish? They don't seem to surface on the website anywhere.

**Comment by jan-auer** [comment]
Do you mean these? (output stripped for readability)

```
 $ sentry-cli releases deploys new --help
Creates a new release deployment.

USAGE:
    sentry-cli releases deploys <VERSION> new --env <ENV>

OPTIONS:
        --started <TIMESTAMP>     Optional unix timestamp when the deployment started.
        --finished <TIMESTAMP>    Optional unix timestamp when the deployment finished.
    -t, --time <SECONDS>          Optional deployment duration in seconds.
                                  This can be specified alternatively to `--started` and
                                  `--finished`.
    [...]
```

**Comment by saiichihashimoto** [comment]
But sentry already sorts my releases by when they arrived anyways, so it doesn't seem to accomplish that? And if `--time` accomplishes the same thing as `--started` and `--finished` are supposed to, then it seems to just be about the duration of the deployment itself, but I don't see that surfaced anywhere.

Basically, I still don't get it. :-( Sorry.
