### ISSUE TITLE
sentry-cli fails debug info upload with 403 response

### ISSUE THREAD

**Issue by rksm** [getsentry/sentry-cli#2178]
Hello!

We are running a debug info upload in CI and see intermittent upload failures caused by a 403 response. The auth token with org:ci scope is correctly set. Looking at the sentry-cli retry behavior, it seems to only retry on 5xx errors which makes sense. I wonder though if this issue could be fixed?

We are using sentry-as-a-service.

```
 Found wasm debug info in /tmp/nix-shell.ElFEFV/tmp.U9jn8Mk2bN/.container/ee04ec23abce3aa59394df5a1eeda1acaacb378ff318cb1c4eefc5f1dfb53085/layer.tar
Uploading wasm debug info
  DEBUG   2024-10-06 23:03:42.396067828 +00:00 sentry-cli version: 2.33.1, platform: "linux", architecture: "x86_64"
  INFO    2024-10-06 23:03:42.396974273 +00:00 sentry-cli was invoked with the following command line: "sentry-cli" "debug-files" "upload" "--log-level" "debug" "--org" "***" "--project" "***" "--auth-token" "[REDACTED]" "hyper-app.debug.wasm"
  INFO    2024-10-06 23:03:42.397003768 +00:00 Issuing a command for Organization: *** Project: ***
  DEBUG   2024-10-06 23:03:42.398064781 +00:00 request GET https://sentry.io/api/0/organizations/***/chunk-upload/
  DEBUG   2024-10-06 23:03:42.398084076 +00:00 using token authentication
  DEBUG   2024-10-06 23:03:42.398790868 +00:00 retry number 0, max retries: 0
  DEBUG   2024-10-06 23:03:42.482566779 +00:00 > GET /api/0/organizations/***/chunk-upload/ HTTP/1.1
  DEBUG   2024-10-06 23:03:42.482600812 +00:00 > Host: sentry.io
  DEBUG   2024-10-06 23:03:42.482606533 +00:00 > Accept: */*
  DEBUG   2024-10-06 23:03:42.482611663 +00:00 > Connection: TE
  DEBUG   2024-10-06 23:03:42.482616562 +00:00 > TE: gzip
  DEBUG   2024-10-06 23:03:42.482621922 +00:00 > User-Agent: sentry-cli/2.33.1
  DEBUG   2024-10-06 23:03:42.483133147 +00:00 > Authorization: ***
  DEBUG   2024-10-06 23:03:42.584320052 +00:00 < HTTP/1.1 403 Forbidden
  DEBUG   2024-10-06 23:03:42.584369333 +00:00 < Content-Type: text/html; charset=UTF-8
  DEBUG   2024-10-06 23:03:42.584381686 +00:00 < Referrer-Policy: no-referrer
  DEBUG   2024-10-06 23:03:42.584393198 +00:00 < Content-Length: 339
  DEBUG   2024-10-06 23:03:42.584405170 +00:00 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2024-10-06 23:03:42.584416171 +00:00 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2024-10-06 23:03:42.584450445 +00:00 response status: 403
  DEBUG   2024-10-06 23:03:42.584462848 +00:00 body: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/0/organizations/***/chunk-upload/</code> from this server.</h2>
<h2></h2>
</body></html>

error: API request failed
  caused by: sentry reported an error: unknown error (http status: 403)
  DEBUG   2024-10-06 23:03:42.585222447 +00:00 skipping update nagger because session is not attended
```

A couple of closed issues mention 403 responses though the causes might have been different.

**Comment by rksm** [comment]
Just saw that we were on a version from August. Updated to 2.37.0 now, I'll report if the issue is still happening with that.

**Comment by rksm** [comment]
The same issue happens with v2.37.0.

**Comment by szokeasaurusrex** [comment]
Hi @rksm, are you running Sentry CLI from a Hetzner server? 

It is [known issue](https://github.com/getsentry/sentry/issues/74706) that certain Hetzner IP ranges are sanctioned by Google Cloud (where Sentry is hosted), and since Google blocks requests from these IPs before they reach our infrastructure, there is unfortunately nothing we can do to help if this is the case. You might be able to try rotating your IP address; this has worked for others in the past.

Another possible cause could be our [response to the current U.S. sanctions against Russia](https://sentry.zendesk.com/hc/en-us/articles/28038067843739-FAQ-Sentry-s-Response-to-U-S-Russia-Sanctions); these have required us to block access to Sentry from all Russian IP addresses. So, if your server is located in Russia, you will receive a 403 response code.

Do either of those apply to your situation? If not, please let me know, and I can investigate further.

**Comment by rksm** [comment]
Hi @szokeasaurusrex,

thank you for the explanation. Yes, we indeed host the CI runners on hetzner, that would explain that. We allocate them dynamically so that makes just assigning a "good" ip harder, we'll try to work around that.

I'll close this but maybe the [sentry-cli docs](https://docs.sentry.io/cli/dif/) could be updated with a note? Looks like we aren't the only ones who have spend time on this.

Thank you!
