### ISSUE TITLE
could not parse JSON response

### ISSUE THREAD

**Issue by JoseVov** [getsentry/sentry-cli#2188]
### CLI Version

2.37.0

### Operating System and Architecture

- [x] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

14.1.1

### CLI Command

sentry-cli organizations list

### Exact Reproduction Steps

Just call

`sentry-cli organizations list`

### Expected Results

```
[{"id":1,"name":"xxx","slug":"xxxx","dateCreated":"2024-06-02T09:06:19.205496Z","status":{"id":"active","name":"active"},"avatar":{"avatarType":"","avatarUuid":null},"isEarlyAdopter":false,"require2FA":false,"isAcceptingEvents":true}]
```

### Actual Results

```
error: could not parse JSON response
  caused by: invalid type: integer `1`, expected a string at line 1 column 9
```

### Logs

If I made the api request manually with CURL

```
curl -H "Authorization: Bearer xxxxxx" https://sentry.xxxx.xxx/api/0/organizations/
```

It works as expected

**Comment by szokeasaurusrex** [comment]
@JoseVov I am unable to reproduce this behavior with Sentry SaaS. Are you using a self-hosted version of Sentry? If yes, which version of self-hosted Sentry are you running? And, did you notice this command breaking from one version of Sentry CLI to the next?
