### ISSUE TITLE
Add convinient helper for react native projects

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cli#22]
- Clone `git@github.com:getsentry/sentry-react-native.git` > checkout `master` branch
- Install react-native https://facebook.github.io/react-native/docs/getting-started.html#content
- Create a new react-native project
```
react-native init AwesomeProject
cd AwesomeProject
```
- Change `package.json` add local file dependency in for `sentry-react-native`
```
"sentry-react-native": "file:../sentry-react-native"
```
- `npm install`
- `react-native link sentry-react-native`
- `open ios/AwesomeProject.xcodeproj`
- Do the stuff you see in the screenshots ... this will be the part that the `sentry-cli` should do

```
$(SRCROOT)/../node_modules/sentry-react-native/ios
```

<img width="1401" alt="screenshot 2016-11-30 16 15 48" src="https://cloud.githubusercontent.com/assets/363802/20758453/2711b378-b71a-11e6-924d-3a949cff7ed7.png">

<img width="1398" alt="screenshot 2016-11-30 16 16 47" src="https://cloud.githubusercontent.com/assets/363802/20758477/3953b4b4-b71a-11e6-8489-213672431d1f.png">

<img width="1401" alt="screenshot 2016-11-30 16 17 07" src="https://cloud.githubusercontent.com/assets/363802/20758488/40391544-b71a-11e6-8f61-a9ee396ba6ec.png">

<img width="1400" alt="awesomeproject_xcodeproj_and_sentryreactnative_xcodeproj" src="https://cloud.githubusercontent.com/assets/363802/20758493/43d3f26e-b71a-11e6-98ca-8f5c8f14985d.png">

- Open `index.ios.js`
```
import RNSentryClient from 'sentry-react-native';
```
- Add RNSentryClient `startWithDsnString` somewhere in the code e.g.:
```
...
export default class AwesomeProject extends Component {
  render() {
    RNSentryClient.startWithDsnString("YOUR DSN");
    return (
...
```
- Hit run in Xcode or run `react-native run-ios`
- Profit

**Comment by mitsuhiko** [comment]
On the way there. For now I added support for preprocessing react-native sourcemaps which will come in 0.20.0

**Comment by mitsuhiko** [comment]
At least for the uploading of the sourcemaps we have support now. I still don't quite know how to best make the actual xcode project updates work.

**Comment by HazAT** [comment]
We can close this ... we now include the source as a submodule which makes all this obsolete.
