### ISSUE TITLE
Include time that the source map upload took in output

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-cli#2206]
Would be cool to display

> Source Map upload took 31.24s

when source map uploads finish.

Time should basically just include the whole command or close to it as operation. It doesn't need to be sub ms accurate.

**Comment by lforst** [comment]
I guess because the CLI is sometimes used in isolation? otoh users could also just `time sentry-cli ....`

**Comment by szokeasaurusrex** [comment]
Yeah, unless it needs to be in the CLI (e.g. if we want to time a specific part of the upload), I think let's handle timing from the outside
