### ISSUE TITLE
1.28.2 Auth Credentials Not Provided

### ISSUE THREAD

**Issue by mikejk8s** [getsentry/sentry-cli#222]
About 40 minutes ago we started getting the following error on all Sentry releases, I don't see any major changes to .sentryclirc in this release so not sure what happened but we had to pin our builds to sentry 1.28.1 which caused builds to release successfully again. I haven't dug very far into this. If there's something with auth that changed please let me know. This is a brand new release so I wanted to make sure you guys don't get a ton of these if it is a bug on the client end.

The .sentryclirc file is created properly. Nothing has changed on our end and the last build we did was yesterday on client 1.28.1. Our first failed build was about 5 minutes after the 1.28.2 release. I tested cating the .sentryclirc file which was correct (for 1.28.1 at least). I forgot to attempt to run sentry-cli info or anything similar and I've already updated all of my repos at this point.

```
[defaults]
url=https://sentry.io/
org=$myorg
project=$myproject

[auth]
token=$mytoken
```

We're now using an install script I posted at https://storage.googleapis.com/sentry-test/get-cli (only modifications are 1.28.2 to 1.28.1). 

Thanks.

```$ curl -sL https://sentry.io/get-cli/ | bash
This script will automatically install sentry-cli 1.28.2 for you.
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous. 
         Instead run it as normal user. We will sudo as needed.

######################################################################## 100.0%
######################################################################## 100.0%
                                                                           0.3%
#                                                                          1.7%
###                                                                        4.6%
########                                                                  11.8%
###################                                                       27.6%
######################################                                    54.2%
###################################################################       94.0%
######################################################################## 100.0%
Done!
$ touch .sentryclirc
$ echo "[auth]" > .sentryclirc
$ echo "token=${SENTRY_TOKEN}" >> .sentryclirc
$ echo "[defaults]" >> .sentryclirc
$ echo "org=$myorg" >> .sentryclirc
$ echo "project=$myproject" >> .sentryclirc
$ cat .sentryclirc
[auth]
token=$mytoken
[defaults]
org=$myorg
project=$myproj
$ sentry-cli releases new $CI_PIPELINE_ID
error: http error: Authentication credentials were not provided. (401)
ERROR: Job failed: exit code 1```

**Comment by mitsuhiko** [comment]
For now please use 1.28.1. I pushed out a revert for the new config handling for now and that will go out n 1.28.3. Will investigate what happened.

**Comment by jan-auer** [comment]
Closing this for housekeeping as the fault has been rolled back. We can reopen once @mitsuhiko resumes work on the patch.
