### ISSUE TITLE
Read debug IDs from debugId field in sourcemaps

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#2220]
When uploading sourcemaps using `sentry-cli`, debug IDs should be read from the `"debugId"` field as well as the current `"debug_id"`.

The TC39 proposal is for `"debugId"` to become the actual name, see https://github.com/tc39/source-map/blob/8be0fe10ad042e13f4196d17b44ddedfd6a9df58/proposals/debug-id.md?plain=1#L100-L117. For now we can support it _in addition_ to `"debug_id"`.

This requires updates in `symbolic` and `rust-sourcemap`:

- [x] https://github.com/getsentry/symbolic/pull/874
- [x] https://github.com/getsentry/rust-sourcemap/pull/97

Once those are merged and released, a dependency update is all that's required.
- [ ] https://github.com/getsentry/sentry-cli/pull/2222

**Comment by evelant** [comment]
I think this may possibly have introduced a problem. On the latest @sentry/react-native 6.3.0 and @sentry/cli 2.39.0 android builds fail due to "bad json: duplicate field 'debug_id'"

```
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.whetware.taskhero@6.2.22+2000110742_2000110742 FAILED
[RUN_GRADLEW] Copy `debugId` from packager source map to Hermes source map...
[RUN_GRADLEW] Done.
[RUN_GRADLEW] Check generated source map for Debug ID: 0f7b9eb2-071f-45b4-946b-2035a8445ed5
[RUN_GRADLEW] Sentry Source Maps upload will include the release name and dist.
[RUN_GRADLEW] Sentry-CLI arguments: [/Users/imagio/dev/build_temp/android_11_25_03_40/build/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /Users/imagio/dev/build_temp/android_11_25_03_40/build/apps/taskhero/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle, --sourcemap, /Users/imagio/dev/build_temp/android_11_25_03_40/build/apps/taskhero/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map, --release, com.whetware.taskhero@6.2.22+2000110742, --dist, 2000110742]
[RUN_GRADLEW] Processing react-native sourcemaps for Sentry upload.
[RUN_GRADLEW] > Analyzing 2 sources
[RUN_GRADLEW] > Rewriting sources
[RUN_GRADLEW] INFO    2024-11-25 15:43:50.076376 -05:00 Loaded file referenced by SENTRY_PROPERTIES (/Users/imagio/dev/build_temp/android_11_25_03_40/build/apps/taskhero/android/sentry.properties)
[RUN_GRADLEW] error: bad json: duplicate field `debug_id` at line 1 column 51939092
```

**Comment by CallbackDan** [comment]
+1
