### ISSUE TITLE
codepush artifacts not uploaded

### ISSUE THREAD

**Issue by magus** [getsentry/sentry-cli#233]
https://docs.sentry.io/clients/react-native/codepush/

Running the commands exactly as described in the documentation with the path to my JS. The output of the command suggests the files are uploaded and the release is created on Sentry. However there are no items under the artifacts and all crashes cannot find sourcemaps (because there is nothing there).

The artifacts upload fine from Xcode.

```sh
⇨  $SENTRY_CLI react-native codepush appName ios ./fastlane/output/js
> Fetching latest code-push package info
> Processing react-native code-push sourcemaps
> Rewriting sources
> Adding source map references
> Uploading source maps for release com.app.bundle-1.0.6-codepush:v55

Source Map Upload Report
```

**Comment by jamsch** [comment]
Having this issue as well. Wasn't sure if it was an end user problem. The release script works fine on Android but code push releases don't show up with artifacts.

```
SENTRY_PROPERTIES=./android/sentry.properties code-push release-react appName android --outputDir build/android && sentry-cli react-native codepush AppName android ./build/android
```

**Comment by jamsch** [comment]
Issue occurs on latest sentry-cli@1.29.1. We haven't been able to debug any code push releases for a while and now are relying on binary releases which does upload the .js & .map files correctly.

**Comment by kylealwyn** [comment]
Having this same issue. Any updates?

<img width="577" alt="screen shot 2018-02-22 at 2 03 25 pm" src="https://user-images.githubusercontent.com/14184138/36566757-3a7edff0-17d9-11e8-808a-db23aa7af968.png">

![screen shot 2018-02-22 at 2 03 15 pm](https://user-images.githubusercontent.com/14184138/36566756-3a597e5e-17d9-11e8-9e57-b4abdbe5bcc9.png)

**Comment by kylealwyn** [comment]
@jamsch @magus happy to say I think I found what was up. For us, CodePush was writing bundle and map to a `CodePush` subdirectory under specified build dir.

![screen shot 2018-02-22 at 2 10 41 pm](https://user-images.githubusercontent.com/14184138/36567082-45d43160-17da-11e8-9057-81abd74f9efb.png)

Adding `/CodePush` to path for sentry-cli command then properly found artifacts.

Full command:
```
sentry-cli react-native codepush App ios ios/build/CodePush
```

**Comment by magus** [comment]
Great, that worked! Seems so obvious I wish I had investigated sooner, thanks!

**Comment by mattslight** [comment]
Since the latest sentry-cli 1.39.1 this command you must replace 'codepush' with 'appcenter', i.e.

`sentry-cli react-native codepush App ios ios/build/CodePush`
