### ISSUE TITLE
npm install v1.29 fails on Windows x86-64, ENOENT

### ISSUE THREAD

**Issue by laurence-myers** [getsentry/sentry-cli#238]
# Steps to reproduce

1. `mkdir sentrycli`
2. `cd sentrycli`
3. `npm init`
4. `npm install @sentry/cli@1.29 --save`

# Error

```
$ npm install @sentry/cli@1.29 --save

> @sentry/cli@1.29.0 install g:\code\sentrycli\node_modules\@sentry\cli
> node scripts/install.js

fetching sentry-cli-Windows-x86_64.exe ████████████████████ 100% 0.0s
Error: spawn g:\code\sentrycli\node_modules\@sentry\cli\bin\sentry-cli.exe ENOENT
```

The entire `@sentry/cli` directory exists while the exe file is downloading, but is missing after `npm install` finishes.

Installing v1.28.4 works fine.

Tested on Windows 8.1 x84-64.

**Comment by jan-auer** [comment]
Thanks for reporting, PR on its way.

**Comment by fatihkose** [comment]
Hello,
We still have the problem as follows 
"fetching sentry-cli-Windows-x86_64.exe ████████████████████ 100% 0.0s
Error: spawn EBUSY"

OS:Windows 7
SentryCli: 1.29.1

Thank you.

**Comment by jan-auer** [comment]
Hi

**Comment by fatihkose** [comment]
Thank you so much, it worked!

**Comment by laurence-myers** [comment]
I'm still unable to install v2.9.1.

```
$ npm install @sentry/cli@1.29 --save

> @sentry/cli@1.29.1 install C:\Users\Laurence\code\sentrycli\node_modules\@sentry\cli
> node scripts/install.js

Error: Command failed: C:\Users\Laurence\code\sentrycli\node_modules\@sentry\cli\bin\sentry-cli.exe --version

npm WARN sentrycli@1.0.0 No description
npm WARN sentrycli@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.29.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.29.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Laurence\AppData\Roaming\npm-cache\_logs\2018-02-16T06_57_48_317Z-debug.log
```
Here is the debug log.
[2018-02-16T06_57_48_317Z-debug.log](https://github.com/getsentry/sentry-cli/files/1730484/2018-02-16T06_57_48_317Z-debug.log)

I'm also unable to install v1.28.4 or v1.29.1 using Yarn in my main project.
```
$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
...
[2/4] Fetching packages...
...
[3/4] Linking dependencies...
...
[4/4] Building fresh packages...
[-/4] ⡀ waiting...
[-/4] ⡀ waiting...
[3/4] ⡀ @sentry/cli: Error: Command failed: C:\...\node_modules\@sent
[-/4] ⡀ waiting...
error C:\...\node_modules\@sentry\cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: C:\...\node_modules\@sentry\cli
Output:
fetching sentry-cli-Windows-x86_64.exe 1%
fetching sentry-cli-Windows-x86_64.exe 2%
fetching sentry-cli-Windows-x86_64.exe 3%
fetching sentry-cli-Windows-x86_64.exe 4%
... etc for every percentage value ...
fetching sentry-cli-Windows-x86_64.exe 97%
fetching sentry-cli-Windows-x86_64.exe 98%
fetching sentry-cli-Windows-x86_64.exe 99%
```

**Comment by jan-auer** [comment]
Not entirely sure, but might be related to #251 (PR #256)

**Comment by jan-auer** [comment]
@laurence-myers could you please check with version `1.30.0`? Thanks!

**Comment by laurence-myers** [comment]
v1.30.0 now gives a spawn EBUSY error. Tested in Git Bash and Windows Command Prompt. I haven't tried it in Yarn.

Interestingly, in Command Prompt I saw the download progress bar, but not in Bash (mintty).

{code}
$ npm install @sentry/cli@1.30.0

> @sentry/cli@1.30.0 install ***\sentrycli\node_modules\@sentry\cli
> node scripts/install.js

Error: spawn EBUSY
npm WARN sentrycli@1.0.0 No description
npm WARN sentrycli@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.30.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.30.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2018-02-22T23_00_22_731Z-debug.log
{code}

[2018-02-22T23_00_22_731Z-debug.log](https://github.com/getsentry/sentry-cli/files/1749877/2018-02-22T23_00_22_731Z-debug.log)

**Comment by mitsuhiko** [comment]
The EBUSY error in theory should be fixed now.

**Comment by laurence-myers** [comment]
I can confirm that installing v1.30.2 works for me now, in either npm or yarn. Thanks very much all for your help! 😄
