### ISSUE TITLE
Overriding the version when creating a release for React Native with Codepush

### ISSUE THREAD

**Issue by mtford90** [getsentry/sentry-cli#243]
Hello there,

My team's having a bit of an issue when using Sentry with version management for RN apps deployed to multiple platforms.

Codepush forces you to create two separate apps for each platform and unfortunately provides no utility to override the version labels. This means that the version codes vary per platform.

`sentry-cli` also does not seem to provide a way to override the release id which leaves us in an unfortunate situation whereby when we deploy both Android & iOS we end up with versions like the following appearing on sentry:

```
0.3.6-codepush:v119
0.3.6-codepush:v66
```

Where iOS is v119 and Android is v66. Not only is this confusing but we could also end up in the situation where the version codes are clashing. Ideally the release id would be rolled up into one (if codepush allowed syncing the version codes) or at least something like `0.3.6-codepush:iOS.v119` for example.

Is there perhaps something i'm missing? If not - are there any plans to add support to the CLI for overriding the release id?

Thanks!

**Comment by mitsuhiko** [comment]
That's weird. Normally the release name should be prefixed with your bundle ID. Does that not happen for you?
