### ISSUE TITLE
Error: spawn ETXTBSY during installation

### ISSUE THREAD

**Issue by richardowen** [getsentry/sentry-cli#252]
We're installing the Sentry CLI during our builds and sometimes get this error when running `npm install`:

```
> node scripts/install.js

Error: spawn ETXTBSY
```

The installation then fails, failing the build. From some searching online, it looks like this could be related to the download of the CLI executable? Possible similar issue at browserstack/browserstack-local-nodejs#19.

We're running on Ubuntu 16.04 with node v6.12.3 and npm v5.5.1.

Any ideas?

**Comment by sriseborough** [comment]
I'm also having similar issues with this, causing a real problem in our pipeline.

**Comment by HazAT** [comment]
This will be fixed with version `1.30.2` stay tuned.

**Comment by D3X** [comment]
@HazAT the [appveyor build](https://ci.appveyor.com/project/sentry/sentry-cli/build/job/keq2h1q7yc6402mq) has failed for this release. Could that be the reason it has not been released to npm by the bot yet?

**Comment by HazAT** [comment]
@D3X oh, thx
👀 looking what's going on

**Comment by HazAT** [comment]
Now it's released :)
