### ISSUE TITLE
malformed object file: bad magic

### ISSUE THREAD

**Issue by johan12345** [getsentry/sentry-cli#257]
I am trying to upload a few debug symbol files for an iOS app. When running this command, I get the following error:
```
$ sentry-cli --auth-token [token] upload-dsym --org ramiio --project vertretungsplan-ios .
[INFO] sentry_cli::commands::upload_dsym Scanning .
error: malformed object file: bad magic: 557605234
```

Any idea what that means and how I can fix it?

Also, when I look at the web interface, it seems that the same debug symbol UUIDs that are listed under "processing issues" are already there under "Debug Information Files", but still the processing issues do not go away. :(

**Comment by mitsuhiko** [comment]
@johan12345 can you mail me the debug file to armin@sentry.io? Sounds like we refuse to accept this file as a debug symbol.

**Comment by johan12345** [comment]
Okay, I sent the files to you now.

**Comment by mitsuhiko** [comment]
The next version of sentry-cli does not appear to fail on this file. Should be out today or tomorrow.

**Comment by johan12345** [comment]
Hmm, I can upload the dSYMs with sentry-cli now, but the problem in Sentry itself persists:

> Also, when I look at the web interface, it seems that the same debug symbol UUIDs that are listed under "processing issues" are already there under "Debug Information Files", but still the processing issues do not go away. :(

Also the "bad magic" message still appears when running the upload using the "curl ... | bash" command that sentry provides.

**Comment by mitsuhiko** [comment]
The bash command we will fix. I think it pulls in a cli version too old.

**Comment by mitsuhiko** [comment]
@johan12345 in case you have events stuck in reprocessing please reach out to support and we can have a look at this separately.

**Comment by mitsuhiko** [comment]
Closing this as within the next hour the version on sentry.io that is required by the reprocessing script will pull in 1.30

**Comment by mitsuhiko** [comment]
The associated PR: https://github.com/getsentry/sentry/pull/7383

**Comment by makenova** [comment]
@mitsuhiko Hi, I just got this error and I'm using the latest version of the cli (`sentry-cli 1.30.3`)

I tried both the `upload-dif` and the `upload-dsym` commands becasue the docs are not clear on which to use.

```
➜ SENTRY_AUTH_TOKEN=[token] SENTRY_ORG=[org] SENTRY_PROJECT=[project] sentry-cli upload-dif -t dsym .
error: malformed object file: bad magic: 557605234
```

```
➜  sentry-cli --auth-token [token] upload-dsym --org [org] --project [project] .
error: malformed object file: bad magic: 557605234
```

**Comment by ahti** [comment]
I also had this issue while trying to run the fixme curlsh for some dsyms. A workaround is to make sure you have all dsyms downloaded in the xcode organizer, then search (using find, ag, etc) for the dsym with the uuid given on the processing issues page (should be somewhere in `~/Library/Developer/Xcode/Archives/`), then give the dsym path to sentry-cli directly.

**Comment by sleimanji** [comment]
Hi @mitsuhiko, Sentry Team,

Any update on this issue? We have encountered it too.

**Comment by mitsuhiko** [comment]
@sleimanji latest version of sentry-cli?

**Comment by sleimanji** [comment]
@mitsuhiko thanks for the response. How do I check the version of my sentry-cli and how do I upgrade it?

**Comment by jan-auer** [comment]
You can check the version by running `sentry-cli --version` or `sentry-cli --help`. If you installed sentry-cli manually, simply run `sentry-cli update`. If you installed sentry-cli with a package manager such as NPM or Homebrew, use that package manager's update method to install the newest version.

**Comment by sleimanji** [comment]
Thanks @jan-auer! 

I am not clear on the sentry-cli issue. On our project's web-based Sentry page, there is this message at the top of the list of issues:
> There are 11 issues blocking event processing (last event from 5 days ago)

I then followed the suggestions on the page and executed: 
`curl -sL https://sentry.io/api/0/projects/xxxxxx/processingissues/fix?_=xxxxxxxxx | bash`

The messages I got are:
> Looking for 9 missing debug symbols:
>
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; armv7)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; armv7)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; armv7)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
>   xxxxxxxxx-xxxxxx-xxxxx-xxxxxxx (KungfuEnglishGenie; arm64)
> 
> > Fetched sentry-cli utility in 5s
> > Looking for debug symbols
> ⠒ Searching for debug symbol files...
> ⠠ Searching for debug symbol files...
> ⠠ Searching for debug symbol files...
> ⠤ Searching for debug symbol files...
> ⠦ Searching for debug symbol files...
> ⠦ Searching for debug symbol files...
> ⠖ Searching for debug symbol files...
> ⠖ Searching for debug symbol files...
> ⠒ Searching for debug symbol files...
> ⠐ Searching for debug symbol files...
> ⠐ Searching for debug symbol files...
> ⠐ Searching for debug symbol files...
> ⠒ Searching for debug symbol files...
> ⠒ Searching for debug symbol files...
> 
> sentry-cli update to 1.32.3 is available!
> run sentry-cli update to update
> error: malformed object file: bad magic: 557605234

The above doesn't show a message that flashed for a split second "fetching sentry-cli". Is the initial `curl` command I ran the right one? I can imagine it will download the latest sentry-cli.

**Comment by jan-auer** [comment]
The script is currently pinned to download version 1.30.0, but will prefer the installed version of sentry-cli if you have a newer one. At the bottom of your log, you can see instructions for how to upgrade: run `sentry-cli update`.

We are planning to update the reprocessing script to prefer the latest sentry-cli version instead and adding a couple of other features, but at the moment I'm afraid the only option is to update manually.

**Comment by sleimanji** [comment]
`$ sentry-cli update`
Tells me 'command not found'

I tried to install sentry-cli manually, following the suggestions on this page: https://docs.sentry.io/learn/cli/installation

I did: 
`$ curl -sL https://sentry.io/get-cli/ | bash`
`This script will automatically install sentry-cli 1.32.3 for you.`
`Installation path: /usr/local/bin/sentry-cli`
`######################################################################## 100.0%`
`Password:` (I entered admin password here)
`mv: rename /var/folders/zb/c2zbcqkx0zzclfv10p1phf5m0000gn/T//.sentrycli.7gWhIUGX to /usr/local/bin/sentry-cli: No such file or directory`

And I still don't have sentry-cli.

**Comment by jan-auer** [comment]
@sleimanji How did you install sentry-cli on your system in the first place?

**Comment by sleimanji** [comment]
@jan-auer I didn't install sentry-cli. I only downloaded the Sentry library and added it to the Xcode project. Then at a later stage ran the `curl -sL https://sentry.io/get-cli/ | bash` command and got the `/usr/local/bin/sentry-cli: No such file or directory` message.

**Comment by sleimanji** [comment]
We use the CocoaPods to integrate the Sentry.

**Comment by sleimanji** [comment]
I finally managed to install sentry-cli using Homebrew and I was able to run `curl -sL https://sentry.io/api/0/projects/xxxxxx/processingissues/fix?_=xxxxxxxxx | bash`

Unfortunately, I got the message that `No debug debug information files found` and that 11 dSym files are still missing.

Could I have deleted these dSym files? Should I manually look for them somewhere?

Thank you!

**Comment by sleimanji** [comment]
@jan-auer, I would appreciate your advice on my question. We're missing a lot of crash reports because of the missing 11 dSym files. Is there a workaround? Can I perhaps find them manually (sentry-cli had no luck)?

**Comment by jan-auer** [comment]
@sleimanji When you go the processing issues page in sentry, you will find the list of missing files. If you're able to locate them on your machine, you could you please try to run the following command instead of the reprocessing script:

```
sentry-cli upload-dif --type dsym /path/to/folder
```

Note that you can always also ask for help in our [community forums](https://forum.sentry.io) or as for paid [support](mailto:support@sentry.io) (included in all paid plans).
