### ISSUE TITLE
Remove most common path

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cli#26]
This change is primarily for `react-native` `electron` support ...
Right now it does not break anything, but we could remove the most common path in order to have better readability

<img width="987" alt="screenshot 2017-01-04 15 15 14" src="https://cloud.githubusercontent.com/assets/363802/21645014/a6c2254e-d290-11e6-94f8-aa7e9e959e4c.png">

So in this particular example we could safely strip away `/Users/haza/Projects/sentry-react-native/examples/ReactNativeExample` in the sourcemap file if using the cli with the `--rewrite` parameter.

**Comment by mitsuhiko** [comment]
This is supported with `--strip-common-prefix` on the latest development version. Not sure if it landed in 0.20 yet.

**Comment by mitsuhiko** [comment]
I need to verify though that it works correctly :)

**Comment by mitsuhiko** [comment]
This will be in the next release.
