### ISSUE TITLE
sentry-cli react-native codepush ... > "The system cannot find the file specified. (os error 2)"

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-cli#262]
* OS: Windows 10
* Using nvm-windows
* npm@3.10.10
* node@6.11.1
* sentry-cli@1.25.0
* Platform: Android
* Git Bash Running as Administrator
* Running from root project directory (contains the android folder)

Prints the following to the console before the error:

`> Fetching latest code-push package info`

It seems it does not matter what I pass for the other arguments; this error always occurs.

Nothing else prints to the console.

I have tried globally npm installing sentry-cli-binary and code-push.  I have also tried using ./node_modules/sentry-cli-binary/bin/sentry-cli, which is also on version 1.25.0.

I tried globally installing @sentry/cli as an administrator in order to try to use that instead but I kept getting a "spawn EBUSY" error.  I followed the steps here:

https://github.com/getsentry/sentry-cli#node

I am not able to use `sudo` in Git Bash.

**Comment by mitsuhiko** [comment]
I assume this is a duplicate of #218 as well?

**Comment by HAMPLENI** [comment]
That is correct.  I will add a comment to that issue describing the issue I am running into.
