### ISSUE TITLE
Cannot install via npm

### ISSUE THREAD

**Issue by danwoodbury** [getsentry/sentry-cli#271]
I cannot install the cli via npm. I am using sentry within my react native app and suddenly I cannot run `yarn install` or `npm install` as it fails when it gets the downloading @sentry/cli.

I have tried installing it globally and it also fails at the stage `fetching sentry-cli-Linux-x86_64`. It wont pass 0% and then throws out this error:

```
/home/danwoodbury/.nvm/versions/node/v8.3.0/bin/sentry-cli -> /home/danwoodbury/.nvm/versions/node/v8.3.0/lib/node_modules/@sentry/cli/bin/sentry-cli

> @sentry/cli@1.30.3 install /home/danwoodbury/.nvm/versions/node/v8.3.0/lib/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Linux-x86_64 ░░░░░░░░░░░░░░░░░░░░ 1% 29258.8sError: Command failed: /home/danwoodbury/.nvm/versions/node/v8.3.0/lib/node_modules/@sentry/cli/sentry-cli --version

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.30.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.30.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danwoodbury/.npm/_logs/2018-03-14T19_52_19_440Z-debug.log
```

Is there some sort of server outage or something? This was working fine earlier this afternoon but now it isnt. Its really impacting our productivity

**Comment by mitsuhiko** [comment]
Cannot reproduce this. sentry-cli is downloaded from github releases. So if github releases works for you, this *should* work. Can you share anything else with us that would help pinpointing this?

**Comment by danwoodbury** [comment]
this is the output from the logs:
```
121 verbose argv "/home/danwoodbury/.nvm/versions/node/v8.3.0/bin/node" "/home/danwoodbury/.nvm/versions/node/v8.3.0/bin/npm" "install" "-g" "@sentry/cli"
122 verbose node v8.3.0
123 verbose npm  v5.3.0
124 error code ELIFECYCLE
125 error errno 1
126 error @sentry/cli@1.30.3 install: `node scripts/install.js`
126 error Exit status 1
127 error Failed at the @sentry/cli@1.30.3 install script.
127 error This is probably not a problem with npm. There is likely additional logging output above.
128 verbose exit [ 1, true ]
```
Thats not alot more info I know but its all I can find. I can install any other package, it is literally just @sentry/cli.

**Comment by mitsuhiko** [comment]
As mentioned we distribute the sentry-cli release on github releases. Most other packages do not contain binary dependencies so it's likely that if you have connection issues to github releases it will not affect other packages.

**Comment by danwoodbury** [comment]
I shouldnt have connection issues, im on a 300mb line and everything else works fine. I have just found this issue https://github.com/getsentry/sentry-cli/issues/251 but it seems to have no resolution

**Comment by mitsuhiko** [comment]
@danwoodbury that is an unrelated issue. What happens if you download this link directly on the machine?

https://github.com/getsentry/sentry-cli/releases/download/1.30.3/sentry-cli-Linux-x86_64

**Comment by danwoodbury** [comment]
it downloaded within about 15 seconds flat

**Comment by mitsuhiko** [comment]
Are you using some sort of corporate firewall?

**Comment by mitsuhiko** [comment]
@jan-auer my only guess at this point is that the proxy code breaks for some people. Cannot reproduce this at all.

**Comment by danwoodbury** [comment]
no its just a standard line. It was working fine earlier, ive been using it all afternoon, then it just stopped randomly

**Comment by mitsuhiko** [comment]
That's why I assume it's an issue on your end because we did not change anything and the download infrastructure comes from github.

**Comment by danwoodbury** [comment]
Well thank you for looking into it but I have an update. Randomly it has just suddenly started working again. I must have tried it about 20 times in the last hour or so but now it has suddenly downloaded fine.

**Comment by bjornbjorn** [comment]
btw - just ran into this - turns out PiHole will block download of this package. I guess this goes for many DNS ad-blockers.
