### ISSUE TITLE
HTTP Error 414

### ISSUE THREAD

**Issue by ahti** [getsentry/sentry-cli#277]
I recently added some dependencies to my iOS project and tried to upload the dsyms for the new beta version to my self-hosted sentry instance. This failed with `414 Request-URI Too Large`, and indeed the URL it tried to load is quite large:

    /api/0/projects/2c/ios/files/dsyms/unknown/?checksums=e324b539b15dc2ac2a0815036d69703be27e6a15&checksums=0b0a3a798e5d90233eb1318e15d79b591de0c062&checksums=b792f98b408c8af04e78daa212a7c9274a11fe4a&checksums=07709f8229e4ce8d343ac364f66b97bffe934198&checksums=e7f63b6933471407dade7301f59997e83843bf75&checksums=6279d5faf79a987a85ffc1ab93f95a5570bacf7b&checksums=0557b0cc4c3c2d5c19f8a8fc4be12d347573ba66&checksums=5ad15631d985dec56d4dd4734dd9721ea9d562c0&checksums=0935cfffca006bbc0ccad3fbac973cf0abadae71&checksums=d948bdfa182a8b2e3bbe01d2f14233d19ce180e7&checksums=5099d90f43dac6998aa41b9747a0633485098e78&checksums=1a79512a87c9443a1fc3ffecff748fb8e29d9800&checksums=07406602c8b5e3f7d7115e88d02c0722d76872ad&checksums=15c890f99c3a959c2a78d03267197d1f4548f950&checksums=512da203c859af85fb7dfa577514324250346033&checksums=52aa33468af943daf0fbde844b5b733a42fd619d&checksums=2a1464a33b9d200cdd5f999736fe2df0060361e7&checksums=e3773017556f14753485082039fe9012d50832d0&checksums=dc65f540f83ded0ae7a5ea4f9c4d57efd4f381f5&checksums=426803b089040f48dda0386146da316391498519&checksums=a8303275be76034d403b8723bdcc0440092e6004&checksums=bc133884be4c2042108bc3a0b1e95c5319c0eb99&checksums=c7da0b2394bb9c0bf2afb489c33db8713b9e45f4&checksums=234bf9e8a7e1c6bece5f655c9af39d1d281047e7&checksums=88efac5f1dd2516fdde79f4f3a60d50a2f7630ab&checksums=a229cc593d70d94ebada8fbed8e5bf3b38938478&checksums=82c8195954a7023207f8174b462bf4184edef598&checksums=41a61e7cf9fe40829ed255c0cbb18e036300ca7f&checksums=7d259858e32da4ccdca18ff6e9cd8bc8b52d4db3&checksums=48f494311787ab30b45485982c6f1c160a6065ae&checksums=6e163b5be3bd3374f16c363843fb8d7b2984a734&checksums=d8da7066ba94f9c3765305ccad3dfa1175ba6518&checksums=11e3f6ee1629fece81b4f7662518defd994e3b80&checksums=4233f06fca97f485dc7aec498d5affd3bffce4ba&checksums=fd442f494722a3b62f941ff587e326f4c3ff4c55&checksums=47c99953e2e370b75584a272e7509b3d88895147&checksums=92c10d1106098ad225c7b5f8af10ea4a3dc1e27b&checksums=064a9d4a1276fc0c5c4b7fad8dcf3ee71cc0b856&checksums=e35df26e0b185168e0948d37f2e91965d4c32578&checksums=e4ccd6eda52aed68608601c102b6ba6ac3708d8c&checksums=4a0d5383db07defc9fdd8afc6e762588eae41cd3&checksums=58f6d990154bccd8f39c7657e4d5d81afbf06fdd&checksums=fc1cf438baadf3da4846c7b44f6198df67ecf676&checksums=27a70db880da42fac6f4ae2dae0d0dee41a957a7&checksums=a10ddcaf484aa3699f829314ba13120227565cf8&checksums=30e8462267c830c90ac6b175efa7d2a7dbdeff25&checksums=710c52c6a0c168361662708d516e6284c52cb8ff&checksums=bbff162118118440fe658dada0b26b9720f3de4c&checksums=699ee7192fd27d6f3bbc8ec33111616da4149eea&checksums=746ab8ffed88e41652679324f21b473f778528c9&checksums=8cc289503caf40487e70ac51a08a1d711b03fd50&checksums=c5f084c97ad29d5e18e4ec157082384f3741881f&checksums=e2b387f2ce51a8bf123102dee0adcbb545b6300b&checksums=952844b2ee85b278b561d3359a088f096c0b5814&checksums=9a06191bbfbc9066bbec30b2b00c7f56299bb87d&checksums=c7accac37380719f1d468211f74d7c02d4688198&checksums=773b84e7b60d15df20f35cef28fd2f18a15e3ea9&checksums=b34cd45b9ec2a66dc99dd49a6bcaca64016eba37&checksums=dd45ca3b884b6d1bd5d1b42801ae37b9c7827fed&checksums=802aba195459cfe58de3d56e77643c2decce260e&checksums=494c630de9d0ff7fb423092af86cda36ae21af63&checksums=1cc8c742b5ef571c95eec5433ca6a22c02fcd00b&checksums=1d8bc30a3172b8b90f0250895a8ca4ee3436a3cc&checksums=6e2f7c06945e7b00eb66d84d2eb66d45a112053a&checksums=112d060eaf227d4691105632a541cf66d0dae338&checksums=a14936a77881ec3b9eccd50c248b5e0e323c2f97&checksums=13d1af7cfebf717deae2a4c68fe2765a349a92c5&checksums=bc67392e767dfa75060aa8d220aed36312b10b5c&checksums=37476e14b79fff6b78a507e30b5bea0efcb3eaf9&checksums=658673bc591cd758c25d2e5f61971cc9dc8b6a4e&checksums=cb3285284421c37ad5790170a5f147132fd3c3b7&checksums=292067da0122bf626aa5ba33e1058c4aa206ab86&checksums=32ed0f562cfca4e004120fba22ec02906cee68fd&checksums=852dcb501e9a597b5f43bc12eabd466a87b0ab86&checksums=36cc1d0194934d8ee876f0929fb9f272af9d50f0&checksums=6f1512c43521ea050ec0506399a9f7669abfadd5&checksums=9e6090b8d1ad0c75026138e5592a75a00a988642&checksums=7d6496d17f3817388b64b7d29da809da2dc0e674&checksums=80bd69e448df3c2607125bf8832d5b0b073887be&checksums=6d08b9befb8776bc47418461fce75745faabf8e4&checksums=9cbc0d98dff09a7768a65e6c8fe434c9811d55d2&checksums=c4f3d7bb30d36b43b9913478eafacf26a8a8650b&checksums=d61efdfa377029c891c486855bddf62eca627dfe&checksums=c5a2d5499965e1ff57fec545324a33df3cacc0c0&checksums=90a367ce470caa7f1066805ea5d1dcffe1f9e8f8&checksums=b6176566ff2f218830580a201139dd98f8d2fb35&checksums=2d705fcfd8c4b43cf1ab61b1eb97cc1ef5b99611&checksums=c705d25d548bda11a5ab4310bc219862efcd212b&checksums=d8d187f3fa93ac3a3192c3bdb134ff4d3f71161a&checksums=a2434678691bd452d13a5ee1bb6b6fef66451cc8&checksums=291c7743ed74d33ab83ce2ac6a8e936b4a5df1cd&checksums=7957db0a2d773306591b1a1623871be693443cab&checksums=6d2ab7a280a4d1eb85dfbba9ac847685782b4421&checksums=5e74125585fb8d2c637d44436f19b00a77bb4fdb&checksums=4f316bf487f7a2a42f7095c71227abed521b0598&checksums=0925b9360c3a5e0e7d7dfd7c9522c3d32942412a&checksums=14c302695d075ea4ee7f42070bfe6e1bc0d93551&checksums=c214510cc31f5f2d1a6e01082040a17eae2c6a9a&checksums=90be5e5ee9c78f9c17f7a9c48b60d1fa4c20aeb9&checksums=9e40e8fe7d96c1b732c0013cb13c13aa986cee92&checksums=b51ac00c01401337701c1eaa1e15710edd62dce6&checksums=c1c6c72114d38d9fa9ccac70a19a60d5f17b17b5&checksums=55fae7edbf4da524af07e38864574bc59cc4a97f&checksums=3bca1e05c1adda2850d83109e8b00438be7bfe39&checksums=3782478e665a26a68c8ceae6d22775a7f3df6248&checksums=d260459ac822e423ed44089f29b06f62ec1ed8b2&checksums=0af8305ca76dd0c5a0a1cff8696b899b27fe5645&checksums=fade3a7db78e73c3ca0c655e17af163ce63ca8c4&checksums=400190fe156285d3bf6b75de450f517b61b10bef&checksums=87cf3a2e3f30d97f6b6a6775227d2a718d472676&checksums=ad073c70bd3e9802366f952881b95156af365096&checksums=e4af690df06b1664523bdba43c397b86a9448867&checksums=c190f5270ff3ff306ead92d7cbb1ab112c885069&checksums=741eafd063e31ca59ba4ee2eee912b76de1a5600&checksums=d3ba5180fc878e85126411b0c445d7aafa6982e8&checksums=021fa3d41c6443d96016fd4d1aa9cecb4b809fcf&checksums=c519616de065b4101aa6fe42ae63d075f7640150&checksums=37e426c119938af8f3e379e7e5272423240a10b0&checksums=15b2fc879dcf250283a36ee68cebd7e43ea8165b&checksums=cd9369e185eb8b48252557da6a3689bb1c1e466f&checksums=180a474c7a3531e0dedf1c87c5a126f59f0d3ffe&checksums=57b2f8fb8f63d460f18cf737a1f5e7e3b010bd97&checksums=bbbcc766feba043f55fad4ef2bac9d1748953978&checksums=4266da9e0403c5dcdda73b177cd91c1bd98eefea&checksums=2626e6f286b51ef1817a0bb2340eb5d167725fef&checksums=c2afea05d4576223d835e8faa674c965926070c6&checksums=a27aba5280bf7ba3ce54c605ca7533f9b5151d2a&checksums=7b872d3f4a9d723571600c3ae2568bb0fefca6fb&checksums=19e3243a8113d787a647ed3a453635674416ce61&checksums=d551c3cd7b46b700a6e75828643cebdcd7b776c5&checksums=986c61a21c6d6dec697db13a7b124594ac856b1d&checksums=cdf6fc146d7e6cba41478a67282cb86c85d1d76f&checksums=d1eaabf1272ddf8e8ef74f1723ddaec1d6358152&checksums=fb8dd7e84cd34772db1495b018104ce42054bf15&checksums=fbc3b9b25d5e7eeb2e8d3519667f5f2a6f9c132d&checksums=c788df34d8e08e8466ea977843bd3dc6e74d7917&checksums=ae1e93890e82d22b1370e169a0c19a36349ec090&checksums=2eeb30ed39eeb319e87dd88662f002f6ab3062ed&checksums=c293b319148566150afe3ace07305d601e3d70cd&checksums=27c9b1a70ff95b5f67bc57aa4f57a79e89d0467f&checksums=a801e14c990d9f167666482662589d28d92331c0&checksums=eef25b7ff5cd4a0b976bd89af54d3f558fc19e25&checksums=c9326d904cb3e0b0de2fda41b0fd9928b8e0dded&checksums=fda7b739bf7fe5d3bb0fca9066b7ed99479109e4&checksums=523d3794171ba4549df2f856dd0cfe6bd37ea03c&checksums=6484d20160173470d2f2978108e7bce1a9304ac8&checksums=1622a0cae4a202c69153b20de35876b72c046766&checksums=a93dd9a5c1ed3b8343affd3487f07ec9850b6c40&checksums=6637e30fba8a8d15b52f025580748450c331d23f&checksums=40d36b5add95d5a3cf7b1dae62cd09a22ec1a532&checksums=7a9cc6bf0537a64ed0c702b95cb2359885cc1d3a&checksums=ca1ea4af3825062cbd0de43c2ca0a4a7bacc9d2f&checksums=1cfa5f5a877d6f96ff1008c84565481b536e2934&checksums=d6700b602aacea8a2bcfabd5385c5d2b78dc73c5&checksums=281e66e651f52a03fd263a5a2e254e1189c20ca9&checksums=eb9d2e8b8b539f3fe939a847916ff441c19eee6b&checksums=418a5d5925491e2983b46a02ddd1ec20a0bd741a&checksums=1800d6cec1f25993e8d3e14b3006e17a42536993&checksums=48a850076b876aa8161a83434722cf83818b60d5&checksums=d6139d28d0718e59e269dcd64b56995fe27e5eff&checksums=1ef0fe484bdd1b80ac8ae2c13e57e2a61bc6c6a2&checksums=9f18bb70c04a0d703e2a8968d3434128d7bc5d23&checksums=ecef19ddfe1f2068a89570b0fd5f9b55290a2e18&checksums=f335ba99674a47040fecad5d8a789eb10003187b&checksums=24008d9f900d7b6e599ca84d4cb83cb4171b20d1&checksums=b60081231fc8f63e8092ae7cff9b726a1e4202d5&checksums=012164f36dfd0e942fc514f16beccb8d23efd7f5&checksums=b71123c14195bed55a202fc80d4cc773ad0b75c3&checksums=7d19dba9a87fe840380275d018ad0c01a23b8afa&checksums=225a03eb6ee3bf4a566b0001833a60a3caea6f18&checksums=4451acfbae8bc950825b538657f3fdfe7dbf2752&checksums=71e3ef8ee08c38495660ba392cfe8a53537442c3&checksums=dbad7d080168846d3b7183c8b8773c3824aa877d&checksums=c379accf5342545629f4cd089dbdcccc5a52608b&checksums=ded016aee6e3a498128643381600aedfe7faa318&checksums=d0d76ced98bc0db49761c4a258276da6f01dd406&checksums=305210f7bdfb4c92dba0a3aa94e1a1809c28edab&checksums=43f1737004d8bdc549f82df7b920d34672ad24aa&checksums=2f8ac95100639fcbe957c38ae63bbb310bb6efd4&checksums=2be2471a307b21f4b7dbc27ebe95aeb10ff7bd52&checksums=b475837c46ad0c6eff294c92abc296bee7417f0b&checksums=6f21167925205e4850dc81825c84c258e1476d60&checksums=b5bfe7ef139a1285650279c6ba16fa20fe962d53&checksums=694520ac2df576f1bfc2f10701e497a670e85371&checksums=96091ac88da73a2641f1b9947270c5ced9c6395c&checksums=8935a46f35d1cad2e7b6bee763a035df759e456e&checksums=0ce8498756894fa83e887998d4d922575432c534&checksums=a891fbc9144d4d05eff21249fd1cadfdf73eefe6&checksums=18e9071b4eed63e2b94062c673d2b1beb4783f38&checksums=5b27f224968a865e97a715651733aa2da9b9eb08&checksums=41fbb814fbcaf3e8ddf5415bff0352dfbbb24ca9&checksums=b5daec529130d6b759a02a17369957e6d096647f&checksums=1911d63624bfd76bc1c8d244f2b68a645990ce31&checksums=a8da4211eee08fa45c3b1fedeb9438eb78d66328&checksums=9a5a6a3f74d055b9f85f73444d4498db11d7c0d5&checksums=29aea6e44b2e78250199755ceb6849968c3caa39&checksums=5e2e4b8161b4a8a078f83755e47d12d14e89da09&checksums=f30a817158aff662ea76572fb935dd01c74e8437&checksums=4138305d79b7c278ba5a2f9c0cd5da7b8650f65a&checksums=e7819e110ba8b11e1895405bd0540f638b407c75&checksums=d484a3e87dc4acc5c158edc0b299ec49fe861f8c&checksums=a5a3cf44136821dac82bd92ebb167420d9620669&checksums=cf8901e95cc857193903b55280ee2f228e35d3a2&checksums=f35915fc2e9d84015c8c54537f9017302bf58173&checksums=9d8f8671c48f519ae6368cb29607aba518a7b649&checksums=0244d136fdbd24eac575599a62308e26e5da502a&checksums=6e4e4375a5f777d9825ada19550f2436198c9810&checksums=e8aaad05344cc58678627c811db20cd1a02e2ee0&checksums=9361752a1cca526471f7acbd1d173bbb2415a7f7&checksums=1c7f2dc66602ab49d837905de7ceb7374924c9ae&checksums=79cd03c715c34d0262b297f789a9cef8e12ae1c4&checksums=6a1201e1b64ba3e4fb76785394e9ec6bfaa16e84&checksums=d70c66c11139b1d6a464138ddcd1627b87280d0d&checksums=dcfc2638dd9c37fa39755e806d275b570d69e7c3&checksums=a45039ebe151daa689cc8fa0cdaca86662b137a4&checksums=0f86e506cc32317b323a5bb12ced976dbca39a7c&checksums=57dc73dad29b1f45709efa8325e1e33e21bda961&checksums=637af4dfe91d9ea4ec2ef2371014c40b52256ee2&checksums=dbbf3de10db1349274e46d9fe5955617d74a1959&checksums=ea0d49960664361408dc6c1a3eea31ffd4f2eca0&checksums=b191f072eee122d227326bb2b8255684a9fa98fe&checksums=73808237ee1c7eb163435591bde37fc5a2aff43d&checksums=3902dbc6a7b3ae7262d0081e0573ea36bd7e066f&checksums=be82c5f1913208fc52048b1cb5449cb73d86af40&checksums=92a0d26d81ea3bcf976875b99ab4f0ae06dda7eb&checksums=f166ed66aeb5c59617e6478bb4cc3d177e57887d&checksums=93d34f070e399427766a8cec2eefaf0122edc73b&checksums=13d40e21648c03d7cce8619c4f9be9751cc5271a&checksums=1ac708aeea6b82fbac8b4f4f2d518e984d6f3e48&checksums=1a3fb87d6a15035273941377c3ac90a1f4f17514&checksums=5882dc498499da1a8b1ea5a6af82f5aa17e14401&checksums=05f122265ecc7df9ed68a7795858afff61a62574&checksums=cc21d22062231de7431bb1174828a1613395cbe9&checksums=b389d8c26e74b43e9f06115fc27f8d2989d452c2&checksums=43613ccce870547f27b41daf2b8c8c922c0aa5bd&checksums=438578db7161ff7c8d60d376c1df635393b525dc&checksums=5ee7e20eee84d57412cc6dc7a457cc2f7f9c55a0&checksums=5a82f8308e539100eaff617e5b5d0a8b7dc06e2f&checksums=05f714173d31b0e38ade42e47cf4b74a2fb17027&checksums=06df74e39bafaceec91039f857cab3b8eb7802b8&checksums=a9a7e18f43f812f2f9389bd0e1f58e5e7347a0e4&checksums=b5528ad3171178a10441d7d864635e0f3fe6fc8c&checksums=9507cb27ff12a4efbbbc0dbd51a167f46aa6e24e&checksums=39ef5b82c3baf306aa1bfb3026cdf07ea05eacc7&checksums=3cf0e66ae3ddffdd466b8e91e9a2d7d95c2da149&checksums=0b8d1d1e1b08e27f6d93d295f8fa0f49d3542d4d&checksums=1c01e6d35b5a7cce9884e736c174adefa0d9bac9&checksums=bdc5bae3161c12d3ce39b0a83c5f12cb42331275&checksums=7c8563f52e3baaba979856ceb5bbf91e8c743fb4&checksums=829a893b28651fd8602d1f02b2c3542b057d7394&checksums=383b4f393fb3154012b1a63f9fef1c44c9e2b207&checksums=73eb2885c6626a03eb4ee41302c66fc5fdfa8f71&checksums=40c0590e71f9618d90d95ee21eebbb53e0e9976c&checksums=d5c9e8706a7f76776e0b6f6488d35879e0b9b52a&checksums=c48fe09d90ff989e9c6680dc7cf36acdb3af8d50&checksums=746298fc52b206ce3ec062d3e0db7e488abbce12&checksums=549cbcfb51a3c73deb9780ac202b9bcd382ec8fa&checksums=3b488e9d983e1e77c2e64fa8406c8898320dd35f&checksums=c434e76e6e52bd25e8876c2a3afd994832bd997c&checksums=1ba7f85d1838bb07995112365c20dd9055e01abb&checksums=bbff2bb819e1b498a1c02708b70ded7c8704f901&checksums=da1be18e5e13fac25b12d5cf11686d4c43f18fa0&checksums=9cbac16f740e29b529abb75b7077b7c0bd576c19&checksums=fe0db6f16e890e3b6525f98ea2174f57ea7a42d7&checksums=c54ea7408705656bec4494f69d1c15f0f21a156c&checksums=d72d8dbfc837f1728d2f98a4488cb716be9a82c7&checksums=93b29ce5cff516f34d4ed2f2213e0a1ee775bc96&checksums=7684666d2a832efff33d9a457f1cc9543e0c4efc&checksums=739cfabafad345d58e75d8230d98dfe4db356670&checksums=20d599b72c4184a232ccbb36fd764f067647b743&checksums=a34c980a6f1ebe9e1b6f36749dda77f16d738944&checksums=c9a74f4969820ec1cf4e971092138abb75fc6c87&checksums=46c4f058094dabc3416711f1f295ebfeebcdd928

Is this something I should address by changing my nginx proxy to allow for longer URLs, or should this be mitigated by changing sentry-cli to split the operation into multiple requests if there are too many for one URL?

**Comment by ahti** [comment]
I'm running my own Sentry instance behind an nginx proxy. Both Sentry and sentry-cli are updated to the newest versions.

**Comment by ahti** [comment]
Just in case someone comes across this when googling: You can work around this by unzipping the dsyms and splitting them up or otherwise uploading half of them, then the other half.

**Comment by jan-auer** [comment]
Thank you for posting this workaround @ahti. I can confirm this is a regression introduced in `1.30.0` when we have changed DIF upload.

The problematic code is the [check for unknown dsyms](https://github.com/getsentry/sentry-cli/blob/master/src/utils/dif_upload.rs#L1096-L1099) which needs to be batched.

**Comment by jan-auer** [comment]
This is now fixed in newer versions. We have a new upload mechanisms that no longer suffers this issue.
