### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by ndonald2** [getsentry/sentry-cli#28]
It would be great to have the ability to install `sentry-cli` via homebrew or any other widely-adopted package management system instead of a "curl to bash", which is [not safe](https://www.seancassidy.me/dont-pipe-to-your-shell.html). In addition, it would make updating the tool much easier and provide better support for dependency installation in CI systems.

**Comment by mattrobenolt** [comment]
We can do this relatively easily, but we'd have to run our own Homebrew repo. Not a big deal though, but might be worth setting up `getsentry/homebrew`? @mitsuhiko I do this [here](https://github.com/mattrobenolt/homebrew-stuff) and it's pretty trivial.

**Comment by mitsuhiko** [comment]
From a safety point of view curl to bash from our https domain is about as safe as a brew install from our own brew repo ;)

I'm open to the idea of putting it on brew though.

**Comment by ndonald2** [comment]
I suppose safety isn't necessarily the primary concern here vs convenience, but if you take a look at the link I originally posted, it's not really about the integrity/authenticity of the origin of the script, it's about what potentially happens when the connection drops. But regardless, homebrew support would be great! Thanks for considering.

**Comment by HazAT** [comment]
We are just waiting for the merge 🎉 
https://github.com/Homebrew/homebrew-core/pull/9937

**Comment by HazAT** [comment]
This works already
`brew install getsentry/tools/sentry-cli`
