### ISSUE TITLE
Unable to upload source maps (SSL cert error)

### ISSUE THREAD

**Issue by suchipi** [getsentry/sentry-cli#285]
Hello,

Three days ago, I started getting this error when trying to upload source maps (using the webpack plugin):
```
ERROR in Sentry CLI Plugin: Command failed: /Users/Shared/Jenkins/Home/workspace/deploy/node_modules/@sentry/cli/sentry-cli releases new 5.0.0-fff07acb
error: http error: [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: Invalid certificate chain)
```

Because of this error, I am unable to upload source maps.

I am using `@sentry/webpack-plugin@1.4.0` which is pulling in `@sentry/cli@1.30.3` on macOS.

**Comment by jan-auer** [comment]
Did you update sentry-cli at that time or perform changes to your environment? Usually, this error is caused by missing CA certificates. Alternatively, a proxy could be causing this - are you connecting through one? 

You can temporarily disable SSL certificate validation by adding this to your `sentry.properties`:
```properties
http.verify_ssl = false
```

**Comment by suchipi** [comment]
We didn't update `sentry-cli` or change our environment. I'm not connecting through a proxy, either, to my knowledge.

With that added to my `sentry.properties`, I get this:
```
ERROR in Sentry CLI Plugin: Command failed: /Users/suchipi/my-project/node_modules/@sentry/cli/sentry-cli releases new 5.0.0-eed50dbf
error: not a JSON response
```

Is there an easy way to see the response here in order to debug the issue?

**Comment by arnaud-git** [comment]
Hi there, we are facing the same issue here, we use react-native sentry and sentry cli fails uploading sourcemaps with this stack :

```
INFO: 2. Checking if file licence is default
INFO: 2.... Licence file already activated
INFO: 3. Checking imei and installationUID
INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
INFO: 3.... Imei and InstallationUID are good
INFO: 4. Checking if licence file is expired
INFO: 4.... Licence still valid
INFO: 6. Checking renewDate
INFO: 6.... Renew date not reached
2018-04-16 11:34:54.148701+0200 MyAwesomeProject[56679:191142] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2018-04-16 11:34:54.148997+0200 MyAwesomeProject[56679:191142] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
```

We've tried to add 

```
http.verify_ssl = false
```

to our sentry.properties but it didn't help

**Comment by jan-auer** [comment]
Alright, you can invoke sentry-cli with `--log-level debug` as argument (before the command) or set the `SENTRY_LOG_LEVEL` environment variable to `debug` in order to see request details. Beware that this will generate a lot of output, but it would be interesting to see what happens. Thank you!

**Comment by jan-auer** [comment]
Any update on this?

**Comment by suchipi** [comment]
It's working now, not sure what changed, but I'll close this

**Comment by Natteke** [comment]
this issue not solved and still exist, gentlemen's

**Comment by kreempuff** [comment]
I randomly get: 
```
error: API request failed
caused by: [35] SSL connect error (OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sentry.io:443 )
```
after running 
```
docker run -e SENTRY_AUTH_TOKEN -e SENTRY_ORG=<REDACTED> -v <REDACTED>:/work getsentry/sentry-cli releases set-commits --auto <REDACTED>
```

**Comment by ghost** [comment]
I always get this error on AWS CodeBuild, not sure why ...

**Comment by ghost** [comment]
I had to update `ca-certificates` on my docker image to fix it
