### ISSUE TITLE
Uploading debug symbol files error 413

### ISSUE THREAD

**Issue by sophy123** [getsentry/sentry-cli#287]
trying to upload debug symbol files using:
sentry-cli --auth-token xxx upload-dsym --org xxx --project xxx xxx
but got 
> Found 42 debug information files
> Prepared debug information files for upload

Batch 1
> Compressing 42 debug symbol files
> Uploading debug symbol files
error: http error: generic error (413)

i'm using sentry-cli 1.30.4

**Comment by plasticman** [comment]
Also having the same issue:
```
sentry-cli --auth-token [TOKEN] upload-dsym --org [org] --project [project] ~/Library/Developer/Xcode/Archives/2018-04-24/ 
> Found 96 debug information files
[WARN] goblin::mach::segment section #1 size 1919183 out of bounds
[WARN] goblin::mach::segment section #1 size 1915109 out of bounds
[WARN] goblin::mach::segment section #1 size 1548419 out of bounds
[WARN] goblin::mach::segment section #1 size 1519693 out of bounds
[WARN] goblin::mach::segment section #1 size 870623 out of bounds
[WARN] goblin::mach::segment section #1 size 854232 out of bounds
[WARN] goblin::mach::segment section #1 size 726149 out of bounds
[WARN] goblin::mach::segment section #1 size 726146 out of bounds
[WARN] goblin::mach::segment section #1 size 12095209 out of bounds
[WARN] goblin::mach::segment section #1 size 12119860 out of bounds
[WARN] goblin::mach::segment section #1 size 3595225 out of bounds
[WARN] goblin::mach::segment section #1 size 3599326 out of bounds
[WARN] goblin::mach::segment section #1 size 275643 out of bounds
[WARN] goblin::mach::segment section #1 size 259256 out of bounds
[WARN] goblin::mach::segment section #1 size 5264805 out of bounds
[WARN] goblin::mach::segment section #1 size 5313946 out of bounds
[WARN] goblin::mach::segment section #1 size 1804660 out of bounds
[WARN] goblin::mach::segment section #1 size 514312 out of bounds
[WARN] goblin::mach::segment section #1 size 1128808 out of bounds
[WARN] goblin::mach::segment section #1 size 1104248 out of bounds
[WARN] goblin::mach::segment section #1 size 4802599 out of bounds
[WARN] goblin::mach::segment section #1 size 4753398 out of bounds
[WARN] goblin::mach::segment section #1 size 2590802 out of bounds
[WARN] goblin::mach::segment section #1 size 2598988 out of bounds
> Prepared debug information files for upload

Batch 1
> Compressing 7 debug symbol files
> Uploading debug symbol files
error: http error: generic error (413)
```

**Comment by plasticman** [comment]
I see the issue has been discussed before in https://github.com/getsentry/sentry-cli/issues/86 and https://github.com/getsentry/sentry-cli/issues/241 but seems to be a regression?

**Comment by jan-auer** [comment]
I suppose you are all using Sentry On-Premise?

**Comment by plasticman** [comment]
Sorry for the late update - our organization is using on-premise. We solved the 'Entity Too Large' problem by increasing the max upload filesize in our nginx.conf. Unfortunately the uploaded dSYMs have since been stuck in 'reprocessing', but maybe the upload filesize solution might work for some others.

**Comment by jan-auer** [comment]
We have fixed a couple of issues with reprocessing, symbol uploading and symbolication since the release of Sentry 8.22.0. We are currently preparing a major release, which is why there haven't been any updates recently. You could try to deploy the latest `master` and test again. That should especially give you more information on why events might be stuck in reprocessing.

**Comment by lugehorsam** [comment]
I am also getting this issue:

`goblin::mach::segment section #1 size 146682342 out of bounds`

**Comment by jan-auer** [comment]
@lugehorsam You can safely ignore this warning.
