### ISSUE TITLE
Using upload-dsyms in Xcode does not find .dSYM files in subdirectories

### ISSUE THREAD

**Issue by ndonald2** [getsentry/sentry-cli#29]
As mentioned in [this thread](https://forum.sentry.io/t/cannot-upload-ios-dsym-file-error-413-entity-too-large/707/15), uploading dSYMs using the [`sentry-cli` script](https://docs.sentry.io/clients/cocoa/dsym/#dsym-without-bitcode) provided in the documentation for setting up a Cocoa project does not work correctly in some project configurations, including when using Cocoapods to build dynamic framework dependencies. 

The issue seems to be that the script does not recurse into subdirectories to find dSYM files in `DWARF_DSYM_FOLDER_PATH`. When using Cocoapods (and possibly in other project configurations), the build products, including dSYM files, for each library dependency will be located in subdirectories of the main build products directory.

```
MyApp.app.dSYM
MyInternalFramework.framework
MyInternalFramework.app.dSYM
Pods_MyApp_target.framework
PodDependency1/
    PodDependency1.framework
    PodDependency1.framework.dSYM
PodDependency2/
    PodDependency2.framework
    PodDependency2.framework.dSYM
```

**Comment by ndonald2** [comment]
Thanks for the fix! When can we expect a new release with the fix included?

**Comment by ndonald2** [comment]
Still waiting on a binary release for this. Please let me know when it's expected as it's holding up my company making the switch to Sentry. Thanks!

**Comment by HazAT** [comment]
@ndonald2 We will make a new release today, sorry for the delay.

**Comment by mitsuhiko** [comment]
This is out now.

**Comment by stancho-dynoden** [comment]
I am using the sentry-cli script and have cocoapods in my project, but on the project page on sentry there are no dsyms uploaded even though the script executes successfully, and therefore the crashlogs are not symbolicated 
This is valid as of 17/May/2018
