### ISSUE TITLE
Avoid confusion re: shortVersion and version

### ISSUE THREAD

**Issue by wluxion** [getsentry/sentry-cli#295]
sentry-cli returns the following table for `releases list`:
```
+--------------+-------------------+------------+---------------+
| Released     | Version           | New Events | Last Event    |
+--------------+-------------------+------------+---------------+
| (unreleased) | 1.0.0-codepush:v1 | 0          | -             |
+--------------+-------------------+------------+---------------+
```

Here, version is actually shortVersion (as returned by the api).

However, `releases finalize` expects the full version -- in my case (using react-native), it was {bundle_id}-1.0.0-codepush:v1. Since both the cli and the app show shortVersion, I had no idea why I was getting "release not found" errors until I tried the api.

Had the app or the cli showed both the short and full version, and/or if the error message been a bit more detailed, this would have been more intuitive.

Thanks!

**Comment by jan-auer** [comment]
You can pass the `--no-abbrev` argument to get the full version. I agree that we should emit a better error message if the version cannot be found.
