### ISSUE TITLE
rust error with indexed source maps?

### ISSUE THREAD

**Issue by lwhorton** [getsentry/sentry-cli#299]
After manually POSTing my source files + maps to a sentry release in _literally every path combination possible_ (and never getting a source map to work after throwing an errror), I started to wonder if maybe the sourcemap processor was failing and it wasn't an asset path problem on my end. 

I swapped to the sentry-cli and ran an upload using `--rewrite`, just to confirm that I wasn't doing something dumb with the paths. That gave me a rust panic error. I tried with the simpler `--validate` flag instead, and that provided a very helpful message which has led me here: 
```
> Analyzing 2 sources
> Adding source map references
> Validating sources
> Uploading source maps for release 18.05.06T00:13:24.050bf02

Source Map Upload Report
  Minified Scripts
    ~/js/compiled/main.C83CB62D552DC6C80D86D5C55D01EB4A.js (sourcemap at main.C83CB62D552DC6C80D86D5C55D01EB4A.js.map)
  Source Maps
    ~/js/compiled/main.C83CB62D552DC6C80D86D5C55D01EB4A.js.map
      - warning: encountered indexed sourcemap. We cannot validate those.
```

I'm unsure if that error message means sentry does not support indexed maps, or if it's just impossible to validate them with the cli. 

Either way, what are some solutions I could attempt here? Uploading the files via `--rewrite` gives a rust panic, which probably means they're outright not supported. Unfortunately I'm not so sure the clojurescript compiler (I'm using cljs, hence the need for source maps) supports spitting out the default specified format. Is there a tool for rewriting from indexed->default formats? Does sentry support this format and I'm missing some information?

**Comment by lwhorton** [comment]
After more investigation, it looks like https://github.com/getsentry/sentry/pull/3414 was added some time ago. I'm not sure what I'm really running into, but here's a rust panick dump when I try to run with `--rewrite`:
```
thread 'unnamed' panicked at 'index out of bounds: the len is 491 but the index is 4294967295': /Users/travis/build/rust-lang/rust/src/liballoc/vec.rs:1561

stack backtrace:
   0:        0x10cc0420e - backtrace::backtrace::trace::hf21ea92b3d52ebe5
   1:        0x10cc0258c - backtrace::capture::Backtrace::new::headf35fb42ce734e
   2:        0x10c75cf53 - sentry_cli::utils::system::init_backtrace::_$u7b$$u7b$closure$u7d$$u7d$::ha9fcfcbb73edf4f8
   3:        0x10c926b03 - sentry::integrations::panic::register_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h33c13041f1e55f35
   4:        0x10ccb8760 - std::panicking::rust_panic_with_hook::hfb431ab23831437f
   5:        0x10ccb857e - std::panicking::begin_panic::h083a5eed938a1a63
   6:        0x10ccb84d2 - std::panicking::begin_panic_fmt::h2d93f83eaf48dbcd
   7:        0x10ccb8432 - rust_begin_unwind
   8:        0x10ccf8f25 - core::panicking::panic_fmt::he42c3e63824a6609
   9:        0x10ccf8ea3 - core::panicking::panic_bounds_check::h7f62bff34c2a9d6b
  10:        0x10c90f447 - sourcemap::builder::SourceMapBuilder::set_source_contents::h299cd978659d66f7
  11:        0x10c90ab71 - sourcemap::types::SourceMapIndex::flatten::h32e8bcee08d679c2
  12:        0x10c90af36 - sourcemap::types::SourceMapIndex::flatten_and_rewrite::h5075ec4337bda7cc
  13:        0x10c88566e - sentry_cli::utils::sourcemaps::SourceMapProcessor::rewrite::h4dc138a26c8d3090
  14:        0x10c7c6f4b - sentry_cli::commands::releases::execute_files_upload_sourcemaps::h194d6a93384a2f05
  15:        0x10c7cab48 - sentry_cli::commands::releases::execute::hde51ea0522c74405
  16:        0x10c81cb9d - sentry_cli::commands::execute::h7d2f215555615122 (.llvm.5761699313501965138)
  17:        0x10c820a33 - sentry_cli::commands::main::hb985e5cc3c2e840c
  18:        0x10c82bd4e - std::sys_common::backtrace::__rust_begin_short_backtrace::hf3688a37a10fde7b
  19:        0x10cccae5e - __rust_maybe_catch_panic
  20:        0x10c752a5d - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::had6ac88fa91f5cf0
  21:        0x10ccc029b - std::sys::unix::thread::Thread::new::thread_start::h2f926488e05dc513
```

**Comment by lwhorton** [comment]
Can I get some confirmation on why / how this was fixed? I tried pulling the latest sentry-cli from the git hash of the latest "fixed" commit, and I'm still getting the same issue.

**Comment by lwhorton** [comment]
Is there an easy way to download the binaries at a particular commit? It seems currently I have to wait for the next release for this to take effect.

**Comment by jan-auer** [comment]
@lwhorton Which platform do you need?

**Comment by lwhorton** [comment]
The browser environment... but there's a few pieces:

1) I was hoping to just `npm install git+ssh:....#the-commit` locally to validate that `--validate` and `--rewrite` work properly on upload.
2) I think I still have to wait until a release regardless. I'm uploading maps to `sentry.io` (non hosted) and presumably the older source map parser has to be updated on your end. That is, unless uploading with `--rewrite` means that the parser is never re-invoked since the maps are already parsed/validated?

**Comment by lwhorton** [comment]
If I can't have the sentry.io app working, there's really no point passing around binaries. We can wait until the next release. That is, unless you want me to validate your fix (I didn't see any tests in the commits to sentry-cli/source-map which address this issue :P).
