### ISSUE TITLE
Specify path to .env

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-cli#302]
My app uses [dotenv](https://github.com/motdotla/dotenv) and has files for:
* env.development (local only, not in repo)
* env.production (in repo)
* env.example (in repo, basis for creating env.development)

Is there a way I can tell sentry-cli the location of my .env file?

What I tried:

#### 1. Hoping there was an argument I could pass to sentry-cli
```
Sequence!ben:/Users/ben/code/tesla$ ./node_modules/.bin/sentry-cli --config env.development
error: Found argument '--config' which wasn't expected, or isn't valid in this context
	Did you mean to put '--config-status-json' after the subcommand 'info'?

USAGE:
    sentry-cli <SUBCOMMAND>

For more information try --help
```

#### 2. Using dotenv's command line loader, but the syntax is off with sentry-cli requiring a space argument
```
Sequence!ben:/Users/ben/code/tesla$ node -r dotenv/config ./node_modules/.bin/sentry-cli info dotenv_config_path=env.development
error: Found argument 'dotenv_config_path=env.development' which wasn't expected, or isn't valid in this context

USAGE:
    sentry-cli info [OPTIONS]

For more information try --help
```

**Comment by kolorfilm** [comment]
How can I define this new option in sentry-cli? `SENTRY_LOAD_DOTENV` can specify the env file itself, for example like .env.dev? How can I use that option? Does someone has an example? Thanks!

**Comment by kamilogorek** [comment]
You are correct, `SENTRY_DOTENV_PATH` controls the path `.env` file will be loaded from.

```sh
$ export SENTRY_DOTENV_PATH=/path/to/dotenvfile 
// every call in this shell session now will use that path
$ sentry-cli info
```

`SENTRY_DOTENV_PATH=/path/to/dotenvfile sentry-cli info` as a one-off call.
Or update your local machine config/CI to include that env variable.
