### ISSUE TITLE
MacOS @sentry/cli@1.31.1 install failed

### ISSUE THREAD

**Issue by ericleearticle** [getsentry/sentry-cli#307]
Hi all, this issue seems pretty popular but haven't got this until now with the latest release of CLI
```
> @sentry/cli@1.31.1 install /Users/article/workspace/article/project/public-src/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Darwin-x86_64 ████████████████████ 100% 0.0s
Error: Command failed: /Users/article/workspace/article/project/public-src/node_modules/@sentry/cli/sentry-cli --version

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.31.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.31.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
The error shown in npm log:
```
298 verbose stack Error: @sentry/cli@1.31.1 install: `node scripts/install.js`
298 verbose stack Exit status 1
298 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
298 verbose stack     at EventEmitter.emit (events.js:182:13)
298 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
298 verbose stack     at ChildProcess.emit (events.js:182:13)
298 verbose stack     at maybeClose (internal/child_process.js:957:16)
298 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
```

Tried on Node 8, 10 with NPM 5.6.0
Would appreciate if I can get this out of the way or if there's workaround.

**Comment by maggialejandro** [comment]
Same here.
I was using node 8.11.1 with npm 5.6.0
I've upgraded to node 10.1.0 and npm 6.0.1 and the error persist.

Mac OS 10.13.4

**Comment by sginn** [comment]
We worked around it by force installing 1.31.0.

npm i @sentry/cli@1.31.0
npm install 

the second install is what pulls down react-native-sentry for us.

**Comment by mitsuhiko** [comment]
The guess is that an update to LLVM triggered a bug in older xcode versions that we used to build this so we support down to macos 10.10: https://github.com/rustwasm/wasm-bindgen/issues/186#issuecomment-388373254

It was not caught because the build is only verified on macos 10.10. We're going to push out a build targeting newer macos versions now as this seems to be the most sensible fix.

**Comment by gucomecan** [comment]
It is all about credentials. Start npm install from cmd started as admin/root

**Comment by woltsu** [comment]
If you have Docker, then you can try this in the project folder:
```bash
docker run -v "$(pwd):/tmp" --rm node:14.2.0-stretch npm i @sentry/cli --prefix ./tmp
```

**Comment by Artyom-Ganev** [comment]
> It is all about credentials. Start npm install from cmd started as admin/root

Why root is required? I'm not installing package globally.
