### ISSUE TITLE
Support custom headers

### ISSUE THREAD

**Issue by idolize** [getsentry/sentry-cli#308]
We are trying to authenticate with a self-hosted Sentry instance behind a custom proxy server that uses a different header for additional authentication.

We could easily support this scenario if the `sentry-cli` allowed us to specify additional custom headers in the requests, but right now there does not seem to be any config option to do so.

Would it be possible to add such an option for additional headers? Thank you!

**Comment by mitsuhiko** [comment]
@idolize is this a proxy header or a header in the normal api request?

**Comment by idolize** [comment]
Just a normal header in the API request. Unfortunately the system we are using right now does not allow for a lot of customization on this front, so we would need the client to attach a specific header to it's requests.

**Comment by worenga** [comment]
we have the same issue using cloudflare access, can we have an option of adding extra headers?

**Comment by StudioSpindle** [comment]
It seems as if sentry would allow it: https://github.com/getsentry/sentry-javascript/blob/b7baedd9/packages/types/src/transport.ts#L30

Something like:
```
Sentry.init({
  dsn: 'sentry-dsn',
  headers: {
    Authorization: `Bearer ${idToken}`,
  },
});
```

**Comment by StudioSpindle** [comment]
@worenga @idolize Could you re-check with the comment above to see if this works for you as well?

**Comment by kamilogorek** [comment]
This thread is about `sentry-cli`, not `@sentry/node\browser` package 😅

**Comment by mashail** [comment]
We have the same issue too. We need it as we are using cloudflare access

**Comment by mathew-cf** [comment]
Just wanted to articulate here that #970 unfortunately does not allow use of Cloudflare Access since it requires two custom headers, not just one
