### ISSUE TITLE
Slow sourcemap upload

### ISSUE THREAD

**Issue by elwynelwyn** [getsentry/sentry-cli#309]
I'm having issues with the upload time to sentry.io.

Our sourcemaps are ~30mb, and it takes over 5 minutes to upload them. As we do this as part of CI it slows our build times down.

Unlike https://github.com/getsentry/sentry-cli/issues/17 the upload is consistently slow.

The upload is happening from our corporate network (very fast internet), so it seems unlikely it is related to our connection. (e.g. uploading the same sourcemaps to other cloud providers takes just seconds)

Our build script calls this (after first verifying if a release exists, and creating one if not):

```
sentry-cli releases -p OUR_PROJECT files OUR_REVISION upload-sourcemaps ./path/to/built/code
```

There is a `~/.sentryclirc` which specifies some defaults (our org, auth token, log level etc)

Can anyone suggest ways to speed this up / further investigate why it's slow?

I've run the upload with log level trace but didn't see anything illuminating in the log.

EDIT: one thing I just noticed is for some files it first requests a DELETE for that file before doing the POST. I'm not sure why it would do this as I'm creating a new release each time before uploading, so there should be no existing files associated with the release.

**Comment by jan-auer** [comment]
I can confirm, this is because we do not properly gzip before uploading symbols.

**Comment by TareqElMasri** [comment]
Is there any update with this?

**Comment by ex3ndr** [comment]
Any updates? It takes 8 minutes in our case.

**Comment by ebuchmann** [comment]
Also seem to run into these problems, the time seems to vary, but it does take longer than I would expect. Project is also fairly large.

SMP  ⏱
General output time took 3 mins, 55.11 secs

 SMP  ⏱  Plugins
SentryCliPlugin took 2 mins, 53.42 secs

**Comment by diegofaria** [comment]
Same problem here, it triples the time of the build when using the sentry webpack plugin when building.

**Comment by sheerun** [comment]
Yes, sourcemap uploading or discovering is extremely slow..

**Comment by sheerun** [comment]
As noticed in now-closed #405 probably the main reason of slow upload isn't lack of compression, but rather uploading of tenths or hundreds of files separately instead archiving them and uploading as one. I hope this issue will be closed only when both improvements are applied or #405 is reopened.

**Comment by oderby** [comment]
@jan-auer any updates? This is causing intermittent flakiness in our CI/CD process. Are there any suggested workarounds? Anything I can do to help debug this more?

**Comment by eltonio450** [comment]
Hello,

Any update on this ? Source upload is now 20% of our build time :(

**Comment by balramkhichar** [comment]
Any update here? It's taking a major chunk of deployment time.

**Comment by mruckli** [comment]
We are also loosing a lot of time because of that. Is there any update? As stated in #405 there is a fix planned and on the roadmap. Would you mind sharing a timeline?

**Comment by rafalmaciejewski** [comment]
Uploading with [webpack-sentry-plugin](https://github.com/40thieves/webpack-sentry-plugin) is much faster because it makes concurrent requests to sentry api. My big project was uploaded in seconds compared to over 30 minutes (!!!) i get from with `@sentry/webpack-plugin@1.6.2`

**Comment by mitsuhiko** [comment]
We are actively working on this at the moment. I will try to share more concrete timelines soon.

**Comment by wppd** [comment]
any updates? it's taking forever to upload the sourcemaps....

**Comment by mitsuhiko** [comment]
@wppd this should no longer happen with recent versions of sentry-cli against up to date sentry servers. Are you getting slow uploads on recent versions against sentry.io?

**Comment by mitsuhiko** [comment]
The most recent updates added parallel upload support as well as compression which reduced the upload times from minutes to seconds for our test cases.

**Comment by jan-auer** [comment]
This has been resolved as of `sentry-cli v1.44.0`. It requires sentry.io, or for on-premise a recent installation of `master`. The Sentry 10 release will also include the server-side changes.

**Comment by wppd** [comment]
@jan-auer Our team really need this. It takes looooong time to deploy.. I tried sentry 10  today and I failed mostly because of snuba... I am using self-hosted sentry 9.1.2 (non docker). Will you make a 9.x release to include the faster sourcemap feature?? thanks!

**Comment by jan-auer** [comment]
@BYK might be able to chime in. AFAIK, there is no more 9.x feature release planned but let's wait for a definitive answer.

**Comment by BYK** [comment]
Sorry, there won't be a 9.2 release and this seems like a large change for an unlikely 9.1.3. That said v10 shouldn't be too far away 😉

**Comment by rickihastings** [comment]
Has this been resolved for everyone else? We're using sentry.io and this takes our builds from 40s to 4 minutes on a very basic NextJs app using `@sentry/nextjs`. There are over 300 files being uploaded.

**Comment by andersoncardoso** [comment]
I'm having a lot of trouble with this too. It's a sveltekit app, and after adding sentry, our builds went from ~2min to 25min!

**Comment by csvan** [comment]
Was this added to on-prem in the end?

**Comment by sunapi386** [comment]
Is there any progress on this? After adding Sentry to my Next.js app, the built time went 10x, from 42s to 480s. That's really really poor. 

I want to switch out of using Sentry now.

**Comment by softmarshmallow** [comment]
min spiked from ~5min -> ~30min
(sometimes even exceeds the 45min limit - build fails)
