### ISSUE TITLE
On Windows "sentry-cli react-native codepush ..." fails with error "error: Codepush not found. Is it installed and configured on the PATH?"

### ISSUE THREAD

**Issue by jay1337** [getsentry/sentry-cli#319]
On Windows these lines:
```
static CODEPUSH_BIN_PATH: &'static str = "code-push";
static CODEPUSH_NPM_PATH: &'static str = "node_modules/.bin/code-push";
```
Here : https://github.com/getsentry/sentry-cli/blob/f95417f3d58b354d54b8243c9c464168d35a97ce/src/utils/codepush.rs#L15

must be replaced by these:
```
static CODEPUSH_BIN_PATH: &'static str = "code-push.cmd";
static CODEPUSH_NPM_PATH: &'static str = "node_modules/.bin/code-push.cmd";
```
Otherwise we'll get "error: Codepush not found. Is it installed and configured on the PATH?" when trying to use `sentry-cli react-native codepush ...`.

**Comment by jay1337** [comment]
It should be the origin of this issue : https://github.com/getsentry/sentry-cli/issues/244

**Comment by jan-auer** [comment]
We've changed to AppCenter CLI now, but this issue will persist on Windows.
