### ISSUE TITLE
Which scopes are needed for sentry-cli

### ISSUE THREAD

**Issue by TimonVS** [getsentry/sentry-cli#323]
I've created an auth token which only has the `project:releases` scope enabled. When I try to run `sentry-cli releases new v1.0.0` I'm getting the following response: 

```
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
```

So my question is, which scopes are needed for `sentry-cli` to run properly?

**Comment by jan-auer** [comment]
Hi @TimonVS, in addition to the `project:releases` scope, you also have to enable `project:read`.
