### ISSUE TITLE
Debug symbol upload failed (React Native)

### ISSUE THREAD

**Issue by EskelCz** [getsentry/sentry-cli#329]
I've used the run script from this page for xcode build process:
[https://docs.sentry.io/clients/cocoa/dsym/#upload-symbols-with-sentry-cli](https://docs.sentry.io/clients/cocoa/dsym/#upload-symbols-with-sentry-cli)

I'm running the latest version of Sentry-CLI (1.32.3) and getting this error:

```
Found 3 debug information files
[WARN] goblin::mach::segment section #1 size 1473300 out of bounds
Prepared debug information files for upload
error: could not parse JSON response
caused by: invalid value: string "detail", expected SHA-1 hash at line 1 column 10
```

Is it a bug, or some problem in my setup? Thank you.

**Comment by EskelCz** [comment]
Strange, I tried updating react-native-sentry to the latest version as well and the error changed to this:
```
Analyzing 2 sources
Rewriting sources
Adding source map references
error: project not found
caused by: project was renamed to 'duel'
```
My app is named *duel* everywhere. And it seems the upload worked anyway, according to the website.

**Comment by jan-auer** [comment]
Have a look in your `sentry.properties` or `.sentryclirc` files. Have you configured your project slug as "duel" there or did you use an old name?

**Comment by EskelCz** [comment]
That was it, default name in sentry.properties. Thank you!
