### ISSUE TITLE
.sym file not supported

### ISSUE THREAD

**Issue by shaan7** [getsentry/sentry-cli#332]
I am following https://docs.sentry.io/learn/cli/pdb/ and this happens-

```
PS C:\Downloads\breakpad-tools-windows\dump_syms.exe CrashpadTest.pdb > CrashpadTest.sym

PS C:\Downloads\sentry-cli-Windows-x86_64.exe --auth-token token upload-dif --no-bin --org orgname --project projname CrashpadTest.sym
> Found 0 debug information files
> No debug debug information files found

PS C:\Downloads\sentry-cli-Windows-x86_64.exe --auth-token token difutil check CrashpadTest.sym
error: Unsupported file
```

The `sym` file has lot of stuff and this as the first line-

`MODULE windows x86_64 7CA200CF319E457BA5D7C1C0B7598EC914 CrashpadTest.pdb`

That UUID matches the one under `Processing issues` in my Sentry project (`A required debug information file was missing`).

I'm using `sentry-cli 1.33.0`

**Comment by jan-auer** [comment]
Hi @shaan7, this should definitely work. It also seems that you are using a reasonably recent sentry-cli release, but could you just let me know if you're on the latest version (or which, exactly)?

Sentry-cli should be able to process breakpad symbol files regardless of their file ending or encoding. I just created a file with the header you posted and ran `sentry-cli difutil check` on it with the following result:

```
Debug Info File Check
  Type: breakpad
  Contained debug identifiers:
    > 7ca200cf-319e-457b-a5d7-c1c0b7598ec9-14 (x86_64)
  Usable: yes
```

The only thing I can think of is that your file might contain a BOM (byte order mark) in the beginning?

**Comment by shaan7** [comment]
Thanks @jan-auer , that analysis was spot on! `dump_syms.exe CrashpadTest.pdb > CrashpadTest.sym` generated a `UTF-16 LE` file for some reason. Saved it as `UTF-8` and all is good.

**Comment by jan-auer** [comment]
So much for "regardless of encoding". 😄 However, I'm pretty sure that breakpad also does not support reading _UTF-16 LE_ encoded files...

If this becomes a more common case we could work around that. Also, since BOM-less UTF-8 should be the default encoding on PowerShell now, it will probably be enough to add a section to the docs for this.
