### ISSUE TITLE
Unable to get Sentry to use AppCenter CodePush assets

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-cli#335]
Since the following doesn't work on [Windows](https://github.com/getsentry/sentry-cli/issues/319#issuecomment-399454766), I tried it on macOS.

Commands:

`appcenter codepush release-react -a [Redacted]/[Redacted] -d Dev -m -o .`
`export SENTRY_PROPERTIES=./ios/sentry.properties`

Then (@ sentry/cli@1.33.0):

`sentry-cli react-native appcenter --deployment Dev [Redacted]/[Redacted] ios .`

Output:

\> Fetching latest AppCenter deployment info
\> Processing react-native AppCenter sourcemaps
\> Rewriting sources
\> Adding source map references
\> Uploading source maps for release [Redacted]-1.7-codepush:v20

Source Map Upload Report

The last command makes it past where I got an error on Windows.

The problem is when I cause a Sentry error on that particular CodePush release right after running that command, for iOS, both the symbolicated and unsymbolicated tabs for the error on the Sentry web app do not show the line that the error really occurred on.  It would need the new assets for the CodePush release to show the correct line.  When I do the same test for Android, I don't even get the Symbolicated or Unsymbolicated tabs for the error in the Sentry web app.

I also notice on the error in the Sentry web app that it says "1.7" for the release rather than "1.7-codepush:v20" despite the fact that when I debug the code, it calls `Sentry.setVersion` passing it "1.7-codepush:v20".  Also, when I generate a similar Sentry error on Android, it shows a "-codepush:" release for the error in the Sentry web app so it seems like it might be an iOS only issue.  We are using react-native-sentry@0.31.0.

It seems as though the asset upload to Sentry did not work properly and/or `Sentry.setVersion` is not working properly for iOS.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
