### ISSUE TITLE
How to specify multiple AndroidManifest when splitApk used

### ISSUE THREAD

**Issue by yusufiga** [getsentry/sentry-cli#338]
Hi, we are using splitApk command while assembling the release therefore it generates AndroidManifest file per ABI but I couldn't find any option to specify multiple AndroidManifest files. Currently what I do is to call `sentry-cli upload-proguard` command for each ABI so it can associate. Is there any other way to specify multiple AndroidManifest files for split apk without calling `sentry-cli upload-proguard` multiple times? Thanks.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
