### ISSUE TITLE
Sourcemap not found: http 404

### ISSUE THREAD

**Issue by ochedru** [getsentry/sentry-cli#339]
Environment: Sentry 9.0.0 on-premise.

I upload `js` and `js.map` files using the dockerized `sentry-cli` tool: 
```bash
SENTRY_CLI_VERSION=1.33.0
docker run -v $DIR:/root getsentry/sentry-cli:$SENTRY_CLI_VERSION sentry-cli releases new $VERSION

# upload sourcemaps for this new release
# see https://github.com/getsentry/sentry-cli/blob/master/docs/releases.rst
docker run -v $DIR:/root -v $(realpath $DIR/dist):/assets getsentry/sentry-cli:$SENTRY_CLI_VERSION sentry-cli releases files $VERSION upload-sourcemaps /assets --rewrite --ignore "*.css.*"

docker run -v $DIR:/root getsentry/sentry-cli:$SENTRY_CLI_VERSION sentry-cli releases finalize $VERSION
```

So far so good, the artifacts do show up in the releases/artifact page (snip;  there are other artifacts):

![image](https://user-images.githubusercontent.com/2545624/42464582-c81513ca-83a9-11e8-8307-920059eefa2c.png)

However, when an event is being processed by sentry, its callstack is obfuscated and it has a red maker "there was 1 error encountered while processing this event".

![image](https://user-images.githubusercontent.com/2545624/42464425-4d58085e-83a9-11e8-9e82-e7695cda79eb.png)

Why is sentry trying to download the `.map` file from our website?
Thank you for your help.

**Comment by jerguslejko** [comment]
experiencing the same issue

**Comment by haoza** [comment]
experiencing the same issue

**Comment by Weiyu-Chen** [comment]
same here

**Comment by youngpayters** [comment]
I believe that the working directory for sentry's docker image is at `/home` have you tried using this location?

**Comment by jan-auer** [comment]
This seems more like an issue with Sentry than with sentry-cli. Have you verified that the SDK is configured correctly to include the same release: `26.1.5`? 

If all information matches and it seems like a server bug, please open an issue on https://github.com/getsentry/sentry/issues/

Thanks!
