### ISSUE TITLE
Travis CI 'appcenter' not a valid context

### ISSUE THREAD

**Issue by Sam-Hoult** [getsentry/sentry-cli#340]
I can run my commands locally on my mac:
```
appcenter codepush release-react -a Organization/App -t $TARGET_VERSION --token $API_SECRET -m --description $TRAVIS_COMMIT --sourcemap-output --output-dir "."
sentry-cli react-native appcenter Organization/App -o org -p org-app ios ./CodePush --deployment Staging
```
The appcenter codepush code is fine and creates the `./CodePush` directory. The issue is with the sentry-cli command which fails:
`error: Found argument 'appcenter' which wasn't expected, or isn't valid in this context`

**Comment by jan-auer** [comment]
This looks like sentry-cli wasn't updated. Does `sentry-cli react-native --help` show the `appcenter` subcommand?
