### ISSUE TITLE
Choosing a custom uniqueID for CodePush React Native releases

### ISSUE THREAD

**Issue by jay1337** [getsentry/sentry-cli#341]
CodePush promotion of releases from staging to production (the recommended way to use CodePush) is currently not working with Sentry.
Sentry CLI uses staging version number to identify a release, but this number is not accessible from the app after promotion.

I think the best solution is to use release hash as the uniqueID, which is easily accessible after releasing to CodePush and also from React Native app code.

At least, it should be possible to choose with Sentry CLI the uniqueID of a release uploaded to Sentry (so that a user can choose a uniqueID that won't be linked to the CodePush environment staging/production).

This is discussed here: https://forum.sentry.io/t/managing-sentry-releases-for-react-native-codepush-updates-that-use-semantic-version/2793/3

**Comment by alexpareto** [comment]
@jay1337 did you find a work around?

**Comment by jay1337** [comment]
Changing CLI code and making a custom build :(

Le dim. 22 juil. 2018 07:06, Alex Pareto <notifications@github.com> a
écrit :

**Comment by enthal** [comment]
@jay1337 do you have a PR for your CLI change?  I have the same problem. This is a flaw in sentry.  If I have time I'll do my own PR

**Comment by jay1337** [comment]
Thanks @alexpareto ! It seems to work !

The package hash is no longer available with appcenter cli (through deployment list) :/
So I switched to CodePush package staging label. I change CodePush package description to this so that I can access to it after promoting the package to production.

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-cli/issues/341
