### ISSUE TITLE
Sentry-cli does not exit after upload-dif windows 7.

### ISSUE THREAD

**Issue by LazyDodo** [getsentry/sentry-cli#349]
The upload goes fine, but once completed the process doesn't exit. ctrl-break doesn't work and i have to shoot the process down using the task manager. Which is ok when i do run it manually, less ok when used in a CI environment. 

 I'm running  1.34.0 which should have #342 but it is still happening on windows 7. 

```
sentry-cli-Windows-x86_64.exe  -V

sentry-cli 1.34.0

sentry-cli-Windows-x86_64.exe upload-dif blender.sym

> Found 1 debug information file
> Prepared debug information file for upload
> Uploaded 1 missing debug information file
> File processing complete:

     OK ded88886-b111-4e91-b072-d239390f2c3c-39 (Generic; x86_64)

```

**Comment by jan-auer** [comment]
This should be fixed by #353. We'll run a release on Monday.

**Comment by wrmbaron** [comment]
It's Friday by now and the latest release is still 1.34.0. What happened? I am desperately waiting for this release as well.

**Comment by wrmbaron** [comment]
Thanks mitsuhiko, you made me really happy with your release this morning!

**Comment by LazyDodo** [comment]
Can confirm issue is solved.
