### ISSUE TITLE
CLI reports that an event is sent even if it isn't

### ISSUE THREAD

**Issue by LaurentGoderre** [getsentry/sentry-cli#350]
I disabled my network connection and used `sentry-cli --log-level TRACE send-event -m "Something happened"` and still received `Event sent: 2e85b39d-dc3b-4c30-b89d-0c0e7ca7b623`

I have been trying to debug why events are being sent but no error is reported, not even in `TRACE`

**Comment by jan-auer** [comment]
Seems like a bug in our Rust SDK.

**Comment by hmeerlo** [comment]
@jan-auer Do I understand it correctly that this isn't fixed, the code has just changed to always output an event ID, even if it fails to send it? At least that is what I see in the merged PR.

**Comment by kamilogorek** [comment]
Correct, it's fire and forget.
