### ISSUE TITLE
Failed to get codepush deployments

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-cli#351]
When executing command: `sentry-cli react-native codepush wescreen-android android ./build --deployment Production` with sentry properties exposed as `set SENTRY_PROPERTIES=./android/sentry.properties`, the following error occurs:

```
> Fetching latest code-push package info
error: Failed to get codepush deployments
  caused by: Unknown Error
```

p.s. I have found that it has something to do with this file: https://github.com/getsentry/sentry-cli/blob/f4b524e91c959761674387d4c9a57b1e41e7e06c/src/utils/codepush.rs but cannot figure out the problem.

Any help would be appreciated!!!!!!

**Comment by Nikhil-Curefit** [comment]
+1

**Comment by fzyzcjy** [comment]
For those who fail into this problem, I finally used a workaround:

0. Use this command to see codepush version num: `code-push deployment ls wescreen-android
`
1. Use this to upload "artifacts" in sentry. Note that the 【3.99.99】is the "android version code", and the 【v12345】 is what you see in last step: `sentry-cli releases files com.something-【3.99.99】-codepush:【v12345】 upload-sourcemaps ./build/CodePush --validate --rewrite --strip-common-prefix`

@Nikhil-Curefit  @mrmurazza

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
