### ISSUE TITLE
Fix docs after Docker entrypoint update

### ISSUE THREAD

**Issue by vojtechsoban** [getsentry/sentry-cli#365]
Todays release broke the docs:

> docker run --rm -it -v $(pwd):/work getsentry/sentry-cli sentry-cli  --help

should be fixed to

> docker run --rm -it -v $(pwd):/work getsentry/sentry-cli --help

in README.md

**Comment by tonyo** [comment]
@vojtechsoban thanks for catching this, fixed 👍
