### ISSUE TITLE
25.0 sentry-cli-Linux-x86_64 distribution is missing

### ISSUE THREAD

**Issue by jensenharris** [getsentry/sentry-cli#38]
Hi, unfortunately, you've broken our build.

Your 25.0 release for sentry-cli-Linux-x86_64 is missing. When you call `curl -sL https://sentry.io/get-cli/ | bash` from that flavor of machine, you get an error.

You can also duplicate this just by clicking the link to that distribution from your Releases page.

**Comment by mattrobenolt** [comment]
Hmm, is this still currently happening? This seems to be ok for me on a Linux system and I see the correct file here: https://github.com/getsentry/sentry-cli/releases/tag/0.25.0

**Comment by mattrobenolt** [comment]
Ohh, nevermind. I see. It just downloads the 404 from GitHub and then only errors when trying to run it.

We'll try and get this fixed up, though it oddly seems to be an issue from GitHub?

**Comment by jensenharris** [comment]
From what we debugged the it is able to get the downloader script, but the actual S3 path is borked.

**Comment by mitsuhiko** [comment]
I triggered a new build and the problem fixed itself. Not sure if github encountered an issue there originally. The build log said the asset already existed when it tried to upload it.
