### ISSUE TITLE
error: Could not determine any commits to be associated automatically. You will have to explicitly provide commits on the command line.

### ISSUE THREAD

**Issue by tjg37** [getsentry/sentry-cli#385]
I created issue https://github.com/getsentry/sentry-cli/issues/371 to address the error `error: For non git repositories explicit revisions are required`. That issue was addressed very quickly and is now closed. Thanks so much for the quick turn around. 

However, after running the command which gave the original error `sentry-cli releases set-commits --auto $VERSION`, I now get a new error: 

`error: Could not determine any commits to be associated automatically. You will have to explicitly provide commits on the command line.`

Is this the expected behaviour? 

Everything is the same as in issue https://github.com/getsentry/sentry-cli/issues/371, including the fact that `sentry-cli releases set-commits $VERSION --commit "$REPO@$VERSION"` still works, with the only differences listed below:

```
sentry-cli --version
sentry-cli 1.35.6
```

```
sentry-cli repos list

error: An organization slug is required (provide with --org)
```

```
sentry-cli repos --org slide-3e list

+----------------------------------+----------+-----------------------------------------------------+
| Name                             | Provider | URL                                                 |
+----------------------------------+----------+-----------------------------------------------------+
| getslideapp/slide-django-adaptor | GitHub   | https://github.com/getslideapp/slide-django-adaptor |
+----------------------------------+----------+-----------------------------------------------------+

**Comment by jan-auer** [comment]
The root problem might not have been fixed here. Also see this comment: https://github.com/getsentry/sentry-cli/issues/371#issuecomment-423318362

**Comment by mitsuhiko** [comment]
Nevermind I see my answer now in the original issue: yes aliases are not supported. Sadly libgit2 does not give us the ability to resolve ssh aliases in a way where we could see where they point. Not sure there is anything we can do about this.

**Comment by tjg37** [comment]
@mitsuhiko Thanks for taking a look and letting me know.

**Comment by mitsuhiko** [comment]
I am going to close this. We cannot support this as we are using libgit2 which uses libssh which does not support host aliases.
