### ISSUE TITLE
How to install under windows

### ISSUE THREAD

**Issue by BioPhoton** [getsentry/sentry-cli#39]
Hi awesome sentry team!

if found a version for windows in your repo. I installed the .exe file but nothing works and also in the docs is no information provided for installation on windows.

Please give me a rough step by step descriptions for windows (10)

THX!

**Comment by BioPhoton** [comment]
I managed it! :-)

1. Download windows version from (releases)[https://github.com/getsentry/sentry-cli/releases]
2. Open you shell (i.e. Powershell or git bash) 
3. Path/to/your/file.exe [COMMAND] ( i.e. ./sentry-cli-Windows-i686.exe --info )

**Comment by xufeipyxis** [comment]
or you can just run `npm install -g @sentry/cli` on a Windows machine.

**Comment by winterz** [comment]
a package for chocolatey (https://chocolatey.org/) would be very nice.
