### ISSUE TITLE
Getting 504 when attempting to upload sourcemaps

### ISSUE THREAD

**Issue by codeadict** [getsentry/sentry-cli#395]
While running the `upload-sourcemaps`, sentry is responding with:

```
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 504)
```

**Command:** `$ sentry-cli releases files HASH upload-sourcemaps ./dist --rewrite`

**Comment by jan-auer** [comment]
Closing in favor of https://github.com/getsentry/sentry-cli/issues/309, as this is likely related to slow uploads by sentry-cli, or just a temporary issue.

**Comment by weotch** [comment]
Experiencing this as well during Netlify-based build/deploy process
