### ISSUE TITLE
API request failed - unknown error (http status: 403)

### ISSUE THREAD

**Issue by miriyalee** [getsentry/sentry-cli#401]
![image](https://user-images.githubusercontent.com/35829622/46334532-6d22f380-c65f-11e8-939d-aa579ff2c914.png)

`sentry-cli releases files 9a52e2d upload-sourcemaps ./static/dist --rewrite`

When I tries to upload my source maps, this error occurs.

**Comment by miriyalee** [comment]
I removed Sentry codes from webpack due to this problem.
Can I get some progress about this?

**Comment by jan-auer** [comment]
@miriyalee Thanks for providing the detailed information. Could you please set `SENTRY_LOG_LEVEL=debug` and run these commands again to see which request creates this error?

**Comment by miriyalee** [comment]
interesting, now it is working perfect.
I think it is due to your side temporal server problem.

**Comment by miriyalee** [comment]
Hi, I was continuously experiencing this problem.

But I figured out this problem was caused by my side.

Company network blocked post to Sentry.io (by Zscaler)

I added .sentry.io to SSL certification allowed list, problem was gone.

**Comment by jan-auer** [comment]
Alright, thanks for the update!
