### ISSUE TITLE
Error: bundling failed `index.ios.js` was not found 

### ISSUE THREAD

**Issue by IronTony** [getsentry/sentry-cli#402]
Hi,

when I compile the react-native app with Xcode, I saw on the terminal window this message:
`error: bundling failed: Error: The resource '/Users/yoss/Repo/Project/index.ios.js' was not found.`

Indeed is correct, because I have only `index.js`.
The build with Xcode will run correctly, but I don't know why after the installation of `sentry/sentry-cli/sentry-wizard` I can see this error on the terminal.

Is there a way to fix this?
Thank you

**Comment by jan-auer** [comment]
This seems like a problem with project bootstrapping, and not sentry-cli. From what I can see, this error is also raised by react-native and not by sentry-cli. A quick search yields https://github.com/facebook/react-native/issues/16738. 

Closing this here, therefore. If you believe this is a misconfiguration by sentry-wizard, please open an issue there.

**Comment by jan-auer** [comment]
Which command is giving you this output? How is your app set up, and what are you trying to do there? Without more context it is impossible to figure out your actual problem.

**Comment by IronTony** [comment]
I run: `react-native start --reset-cache`
Then from Xcode I press the button "Build and then run the current scheme", the "Play" button.
When the app is compiled, during the `BUNDLE [ios, dev]` time, I can see the error above:
`[ios, dev] ./index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.`
and after that:
`[ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1180/1180), done.` 

I am using RN 0.57, react-native-sentry 0.39.0, sentry-cli 1.36.1

**Comment by paulmesa** [comment]
@IronTony Were you ever able to resolve this issue? I am experiencing the same problem and haven't found a solution yet.

**Comment by lukewlms** [comment]
For reference: looks like "a custom build script" is [the way to go](https://github.com/getsentry/sentry-cli/issues/81#issuecomment-309139462)

> 1. make a file named mybuild.sh
> 2. add these contents:
>   `../node_modules/react-native/packager/react-native-xcode.sh ./path/to/my/entry/file.js`
> 3. then use sentry-cli react-native-excode mybuild.sh

**Comment by lukewlms** [comment]
We just turned off the build step.  It turns out this build step shouldn't even be active for most iOS projects anyway, because it's incompatible with Bitcode (which is on by default in iOS).

https://docs.sentry.io/platforms/react-native/#ios-specifics
