### ISSUE TITLE
Sourcemaps not uploaded from directories starting with dot

### ISSUE THREAD

**Issue by sheerun** [getsentry/sentry-cli#406]
I'm using Next.js https://github.com/zeit/next.js/ which builds most of its server-side files into `.next` directory (but not all). So when uploading sourcemaps I'd like to upload all .map files from `.next` directory but also all `.js` files outside of this directory that are references.

It turns out for some reason sentry by default ignores map files in directories that start with a dot, so following command: `sentry-cli releases files test upload-sourcemaps .` doesn't upload anything from `.next` folder, just some source files from my repository.

Could you stop not including files from dot directories and introduce a flag that allows to include them? e.g. `sentry-cli releases files test upload-sourcemaps . --include .next`

by the way `sentry-cli releases files test upload-sourcemaps .next` doesn't fulfill my needs as it skips files outside of .next directory even they are references by maps in `.next` dir.

**Comment by jan-auer** [comment]
This was supposed to work by passing `--ignore "!.next"`. However, this seems to no longer work after an upgrade of an internal dependency. We'll fix this and add a paragraph to the documentation regarding hidden files.

**Comment by fazo96** [comment]
We are running into the same problem. @jan-auer @sheerun did you find any solution or workaround? We are using the official sentry webpack plugin to handle source map uploading, but it skips the .next folder.

**Comment by sheerun** [comment]
no, it's still a bug

**Comment by kamilogorek** [comment]
@fazo96 create an ignore file, put a `!.next` in it and tell the cli to use it. It'll work just fine.

```terminal
sentry-cli releases files test upload-sourcemaps . --ignore-file=.sentrycliignore
```

**Comment by fazo96** [comment]
I tried passing `['.next', 'app']` to the `include` option of the webpack plugin. I'll see what happens in the next prod deployment and report back

**Comment by kamilogorek** [comment]
Just verified it locally using webpack-plugin and everything seems to work just fine. Let me know if it's still an issue and I'll work on it if provided more details or a repro case.

![image](https://user-images.githubusercontent.com/1523305/76217687-29002f00-6213-11ea-8c4c-5529c25ad723.png)
