### ISSUE TITLE
Getting 502 generic error back every time after batch of uploads

### ISSUE THREAD

**Issue by jensenharris** [getsentry/sentry-cli#41]
Our build has been seeing intermittent errors caused by `sentry-cli` but now we are seeing them every push.

```
...
 -> ~/sources/node_modules/redux/node_modules/lodash/fp/every.js [script]
  0499e846512778b49de2da8574e81f21dbd3ca40  (155 bytes)
 -> ~/sources/node_modules/redux/node_modules/lodash/fp/maxBy.js [script]
  9a5c1f5cbbb6375b8f314d5c3508854a76541613  (155 bytes)
 -> ~/sources/node_modules/@textio/editor/src/TextioEditor/plugins/disableConsecutiveSpacesPlugin/index.js [script]
error: http error: generic error (502)

devops/upload_to_sentry.sh returned exit code 1
```

It does not happen always on the same file... builds of the exact same SHA `sentry-cli` will error out on a different file.

**Comment by mitsuhiko** [comment]
Can you run it with debug logging enabled and share what it spits out?

**Comment by jensenharris** [comment]
Is there a better way than setting `SENTRY_LOG_LEVEL` to `info`? Didn't see anything else in the docs.

**Comment by mitsuhiko** [comment]
I think it's `sentry-cli --log-level=debug` before the command. It only says in `--help` at the moment.

**Comment by mitsuhiko** [comment]
We are looking into this issue on the server side now. Will keep you updated.

**Comment by jensenharris** [comment]
Ok, with more logging on I just get this:

```
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/textio/frontend/releases/15546/files/
$<2>[INFO] sentry_cli::api using key based authentication
$<2>[INFO] sentry_cli::api sending form data
$<2>[INFO] sentry_cli::api response: 201
$<2>  d6097a89a80e106e5e5ea02e5eae7aee88a660ca  (9534 bytes)
 -> ~/sources/node_modules/react-dom/lib/ReactDOM.js [script]
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/textio/frontend/releases/15546/files/
$<2>[INFO] sentry_cli::api using key based authentication
$<2>[INFO] sentry_cli::api sending form data
$<2>[INFO] sentry_cli::api response: 201
$<2>  9a68d91780f413e1f57098474120e0e329ee0fa1  (5140 bytes)
 -> ~/sources/node_modules/redux/node_modules/lodash/_getData.js [script]
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/textio/frontend/releases/15546/files/
$<2>[INFO] sentry_cli::api using key based authentication
$<2>[INFO] sentry_cli::api sending form data
$<2>[INFO] sentry_cli::api response: 201
$<2>  2fea3c244fa4625b978cea63124835c16aefe660  (325 bytes)
 -> ~/sources/node_modules/redux/node_modules/lodash/fp/drop.js [script]
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/textio/frontend/releases/15546/files/
$<2>[INFO] sentry_cli::api using key based authentication
$<2>[INFO] sentry_cli::api sending form data
$<2>[INFO] sentry_cli::api response: 502
$<2>error: http error: generic error (502)

devops/upload_to_sentry.sh returned exit code 1
```

**Comment by mitsuhiko** [comment]
Definitely somethig wrong on the server. Investigating this now and will update you. Keeping this ticket open for now.

**Comment by mitsuhiko** [comment]
We believe this issue is solved now and we will continue to monitor it.

**Comment by andrejbaran** [comment]
@mitsuhiko Would you share what caused those 502s? We are hitting this issue on a self-hosted instance. Thanks!

**Comment by acidoxee** [comment]
We are also getting this regularly when using GitLab-CI to perform operations on our self-hosted instance of Sentry.

**Comment by jan-auer** [comment]
On self-hosted, this can range from issues with connection keepalives to errors in the file store backend. Have you consulted the server logs?

Beware that we changed and accelerated release file uploads recently. Since this required server changes, the improved upload will be available with the next release of Sentry.
