### ISSUE TITLE
allow specification of git remote in "sentry-cli releases set-commits"

### ISSUE THREAD

**Issue by zsalzbank** [getsentry/sentry-cli#410]
When setting the commits for a release, it would be helpful to be able to select the git remote being used instead of just relying on `origin` being the correct thing.

**Comment by DWSR** [comment]
I just got bit by this. I had multiple remotes on the repository, one of which was the one registered in Sentry, but Sentry kept complaining until I made the registered one `origin`.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/637
