### ISSUE TITLE
Internal Error reported by sentry-cli

### ISSUE THREAD

**Issue by dancrumb** [getsentry/sentry-cli#411]
On running this command:

`sentry-cli releases -p ${my_project} files ${VERSION} upload-sourcemaps ./dist`

The CLI responds with:

```
error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object({"detail": String("Internal Error"), "errorId": String("8f2e577dd9e54c779da60c60c0026108")})
```

Since the error is opaque, there's nothing I can do about it. Can you help?

**Comment by jan-auer** [comment]
Can you please retry? One of our services timed out internally, it should now work again for you.

**Comment by mitsuhiko** [comment]
Going to close this is likely resolved. If it happens again please open another issue.
