### ISSUE TITLE
Ability to specify project when running commands related to organization

### ISSUE THREAD

**Issue by Wirone** [getsentry/sentry-cli#413]
I found it weird how `sentry-cli` works now.

`sentry-cli releases list` lists releases from all projects within organization and `--org` must be provided. But it lists exact versions from different projects like they have common issues:
```
/work # sentry-cli releases --org prod list
+---------------+-----------+------------+----------------+
| Released      | Version   | New Events | Last Event     |
+---------------+-----------+------------+----------------+
| 2 seconds ago | 1.15.3    | 54         | 9 hours ago    |
| (unreleased)  | 1.9.0-RC3 | 0          | -              |
| (unreleased)  | 1.3.1     | 1          | 50 minutes ago |
| (unreleased)  | 1.9.0-RC2 | 0          | -              |
| (unreleased)  | 1.3.0     | 12         | 36 minutes ago |
| (unreleased)  | 1.3.0     | 12         | 36 minutes ago |
| (unreleased)  | 1.2.1     | 0          | 959 hours ago  |
| (unreleased)  | 1.2.0     | 14         | 1178 hours ago |
| (unreleased)  | 1.2.0     | 14         | 1178 hours ago |
| (unreleased)  | 1.9.0-RC1 | 0          | -              |
| (unreleased)  | 1.1.5     | 29         | 1633 hours ago |
| (unreleased)  | 1.1.1     | 1          | 1633 hours ago |
| (unreleased)  | 1.1.0     | 9          | 2107 hours ago |
| (unreleased)  | 1.1.4     | 0          | 2107 hours ago |
| (unreleased)  | 1.1.3     | 46         | 2159 hours ago |
| (unreleased)  | 1.1.2     | 3          | 2301 hours ago |
| (unreleased)  | 86c8ba66  | 0          | 2302 hours ago |
| (unreleased)  | 4ee8043b  | 10         | 2327 hours ago |
+---------------+-----------+------------+----------------+
```
these are, for example, `1.2.0` versions from 2 projects. In UI both versions looks OK, have issues only related to project. But issue count and last issue time is totally different for those versions in UI, so I don't get why it looks like this in CLI.

Also how would `sentry-cli releases delete 1.2.0` behave if there are 2 versions and project can't be specified when running command?

I thought it can be specified like `organization/project`, but it does not work:

```
/work # sentry-cli releases --org prod/foo list
error: Invalid value for '--org <ORG>': invalid value for organization. Use the URL slug and not the name!
```

I think it should be possible to manage releases per project (list, add, delete) and project's name should be displayed in the output table. Since we have multiple projects within the same organization and all the projects are versioned separately, IMO it does not make sense to handle it as it's done now.

```
/work # sentry-cli -V
sentry-cli 1.36.1
```

**Comment by Wirone** [comment]
Today I was testing how deploy tracking works and unfortunately it does not make sense, too.

In organization we have many projects. Each project has releases in `X.Y.Z` format. When I added deploy like:

```
sentry-cli releases --org prod deploys 1.4.2 new --env example.com --finished 1543405980 --url https://example.com --name "Example 1.4.2"
```

Since `1.4.2` version is defined in multiple projects, the same deploy is linked to them however they're different apps deployed on different machines (environments), under different domains.

Specifing project when managing releases and deploys is a must have. Without it, it's useless.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
