### ISSUE TITLE
Release with this version (11.0.0-codepush:v4) does not exist.

### ISSUE THREAD

**Issue by badaz** [getsentry/sentry-cli#427]
Hello, first thanks for the cli, it is really helpful.

I'm having a problem with version 1.36.4 (I also tried 1.35.6 and encountered the same problem)
I've been messing with uploading versions of my code-push sourcemaps to our sentry-server and now I want to do some cleanup. Problem is, sentry-cli does not seem to find versions with names formatted in a certain way.

I managed to delete releases named with simple semver names like 11.0.1 for example
I managed to delete releases named like this codepush:v4
But I am unable to delete versions with name pattern like 11.0.0-codepush:v4 ({semver}-{name}:v{x})
I get this error : Release with this version (11.0.0-codepush:v4) does not exist.

I saw in the code that rust does something like ```let version = matches.value_of("version").unwrap();``` but I'm not familiar with rust so I can't really find where the problem is.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
