### ISSUE TITLE
Got Unidentify Error

### ISSUE THREAD

**Issue by prakasa1904** [getsentry/sentry-cli#430]
Just install sentry-cli and got this error bellow when try to running `lerna bootstrap` | `yarn` | etc

version: `sentry-cli@0.0.4`

but when try using sentry-cli its working normal, assest uploaded.
```
error ./Project/node_modules/sentry-cli: Command failed.
Exit code: 1
Command: node tasks/download.js
Arguments:
Directory: ./Projects/node_modules/sentry-cli
Output:
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
```

have any idea about this error ?

**Comment by techprimate-phil** [comment]
I think I stumbled upon the same issue.
Did you try to install it using `yarn add sentry-cli` because that is a different package. Try `yarn add @sentry/cli`

**Comment by kamilogorek** [comment]
Correct, this package is registered as `@sentry/cli`.
