### ISSUE TITLE
–-strip-prefix does not seem to work

### ISSUE THREAD

**Issue by coder-guy22296** [getsentry/sentry-cli#436]
`–-strip-prefix` seems to have no effect whatsoever

artifacts are being uploaded as:
`~/dist/10.a5b01fab658e826851b0.map`
I want them to be uploaded as:
`~/10.a5b01fab658e826851b0.map`

I assumed that `--strip-prefix ~/dist/` would solve this issue. I have not found anything in the docs to indicate this is wrong.

I have even taken a peek at the sentry-cli source code: https://github.com/getsentry/sentry-cli/blob/master/src/commands/releases.rs#L762

I also posted on the sentry forum: https://forum.sentry.io/t/sentry-cli-strip-prefix-does-not-seem-to-work/5373
can anybody offer some suggestions?
`sentry-cli v1.37.0`

**Comment by coder-guy22296** [comment]
`sentry-cli releases files testCLIRelease upload-sourcemaps . --ext map --ignore node_modules --strip-prefix '~/dist/' --rewrite`

**Comment by cloetensbrecht** [comment]
I have the same issue.

**Comment by coder-guy22296** [comment]
a workaround that worked for me is to use `include: './dist/'`, I only needed to upload items from dist
```
new SentryWebpackPlugin({
  include: './dist/',
  ignoreFile: '.sentrycliignore',
  ignore: ['node_modules', 'webpack.config.js'],
  configFile: 'sentry.properties',
  release: "test-project@0.0.3",
  rewrite: true,
})
```

**Comment by gabrieleantonini** [comment]
Definitely it looks like a bug in the `--strip-prefix` implementation.
I'm not a rust guy but this function could be the culprit: https://github.com/getsentry/sentry-cli/blob/7741826c59f5ad8c14def29e4756019a5c4825d6/src/utils/sourcemaps.rs#L416

It would be nice to have some support from Sentry as we're paying for it.

**Comment by skewis6** [comment]
Is anyone going to look into this? Would be nice to get some input from sentry.. it's been open for 10 months with absolutely no response

**Comment by gitzhaochen** [comment]
Is anyone going to look into this? I have the same issue. Would be nice to get some input from sentry.. it's been open for 13 months with absolutely no response
