### ISSUE TITLE
413  caused by: sentry reported an error: unknown error (http status: 413)

### ISSUE THREAD

**Issue by liuaaaddxiaoer** [getsentry/sentry-cli#439]
413

**Comment by markstory** [comment]
Could you provide more detail on what you did, what you were expecting to happen and what happened instead?

**Comment by seadog0331** [comment]
https://forum.sentry.io/t/413-error-when-uploading-bundle-js-map/297/29

**Comment by siredmar** [comment]
Indeed, the information you give is very limited. Maybe i can help you. I just fixed an issue where two of three uploads of debug symbols worked with sentry-cli. The non working got a error 413 -> Payload too large.
I run a self hosted instance of sentry with nginx in front for https. 
In my case nginx was the one who threw the 413. To fix that, just increase the setting `client_max_body_size` in your nginx.conf in the http section to e.g. 100m
Hope this help someone.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been resolved. 
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by PrantikMondal** [comment]
> nginx.conf

I have the same issue. Where did i find this  nginx.conf file?

**Comment by kamilogorek** [comment]
nginx configuration is used in our onpremise instances - https://github.com/getsentry/onpremise/blob/master/nginx/nginx.conf
