### ISSUE TITLE
Including commits in a release?

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry-cli#445]
(a repost of https://github.com/getsentry/sentry-php/issues/725)

We've been integrating the sentry-cli into our deployments and trying to register our releases and commits.

But this doesn't seem to work? In our deployment we use the sentry_cli docker image as per the documentation:
```shell
VERSION="get the git hash"
echo "Create a new release (${VERSION}) in sentry";
# Create a release
${SENTRY_CLI} releases new -p ${APPLICATION_NAME} ${VERSION}
echo "Associating commits with the release (${VERSION})";
# Associate commits with the release
${SENTRY_CLI} releases set-commits --auto ${VERSION}
```
This outputs the following:
```shell
Create a new release (406f9f1) in sentry
Created release 406f9f1.
Associating commits with the release (406f9f1)
+----------------+--------------+
| Repository     | Revision     |
+----------------+--------------+
| [the name of our repo] | ccc905d1448c |
+----------------+--------------+
```

But if we check the releases for the project in https://sentry.io/[org/project]/releases/ we can see releases as they are used in the issue reporting, but for all releases the actual commits are empty ? 

I'm probably doing it wrong... ? but where?

**Comment by naoisegolden** [comment]
Same happens when using the `@sentry/cli` js module.

**Comment by fruitl00p** [comment]
@naoisegolden so i'm not the only one not seeing commits when using this method?

**Comment by naoisegolden** [comment]
@fruitl00p I am still looking into this matter but I can see that `@sentry/cli` does not implement an API endpoint to set commits. 

I am exploring connecting the repo through the Dashboard, which is not done yet, and see if that automatically matches the commits. I'll keep you updated.

**Comment by naoisegolden** [comment]
`$ sentry-cli releases set-commits --commit "my-repo@from..to" $VERSION` doesn't seem to be working for me, although it doesn't show any errors in the output. On the contrary, shows the table:
```sh
+-----------------------------+------------------------------+
| Repository                  | Revision                     |
+-----------------------------+------------------------------+
| repo                             | from -> to                 |
+-----------------------------+------------------------------+
```

**Comment by matmunn** [comment]
I'm having this problem as well

**Comment by fruitl00p** [comment]
I too see a table, but a different one from your example:
```
+----------------+--------------+
| Repository     | Revision     |
+----------------+--------------+
| account/repo   | aeb593c16466 |
+----------------+--------------+
```

**Comment by fruitl00p** [comment]
Anyone from Sentry willing to comment how it *should* work? :)

**Comment by markstory** [comment]
@fruitl00p You *should* see the range of commits output by sentry-cli associated with the release in sentry.

If you enable `--log-level=DEBUG` you will see all the API requests and responses that sentry-cli is making which should help in figuring out what is going wrong.

**Comment by fruitl00p** [comment]
@markstory this does give me *alot* of output indeed... and it doesnt seem to show any error... But after checking again, i do see releases *and* related commits for the project... ? strange... (we didn't change anything... or not that a i know of?)

Anyway, seems to work for me now :)

**Comment by rnbwspctrm** [comment]
I am having this issue currently. Output table shows repo name and recent revision, nothing more. No associated commits in sentry. 

Debug logs show a 208 response from Sentry after github 'found matching revision' and sent that to sentry with the project name. Should there be commits being sent from github here?  Any ideas on how I can move forward here? 

It would be nice if there was some way to output this information. If --auto is flagged and no commits are identified, perhaps it should at least warn you?

**Comment by rnbwspctrm** [comment]
It seems it is a permissions issue. I am beyond frustrated trying to debug the connection between sentry and github, it's been multiple days now. Please consider including more information about this in the UI and the output of these commands, as I am seeing lots of people having problems with these issues and we could all use a little more information being provided up front.

**Comment by kamilogorek** [comment]
@rnbwspctrm could you provide a list of information that you'd like to see in the output?
Is it just after the command is issued, or you'd also like to include it in something like `sentry-cli release info <release-name>`?

**Comment by alubina** [comment]
For the sake of privacy I masked repository name with `organization/application` and
 have similar issue. I associate commits 'by hand' with
`sentry-cli releases set-commits --commit "organization/application@3.135.0..3.136.0" 3.136.0 --log-level=DEBUG`
The output looks as follows:
`
| organization/application | f5028540c840 -> 91d80fcc9935 |
` 
Commit hashes are real, but the commits list remains empty. Any hints?

**Comment by kamilogorek** [comment]
Can you provide your org/project where you configured it? And preferably `--log-level=debug` output as well.

**Comment by alubina** [comment]
There was an issue with repository permissions. Sorry for the noise I made

**Comment by vinicius-ronconi** [comment]
@alubina , can you elaborate on what was the permission missing? I'm facing a similar issue and maybe it can solve my problem!

**Comment by michalper** [comment]
@vinicius-ronconi we have to re-authorize every repository in Sentry (https://docs.sentry.io/workflow/releases/?platform=php#install-repo-integration) and then everything started working fine.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by image72** [comment]
```js
import { $ } from 'zx';

const { version, name, org } = require('./package.json');

const SOURCEMAPS_PATH = './build/static/js';
const URL_PREFIX = '~/static/js/';

await $`date`;
const rev = await $`sentry-cli releases propose-version`; // current version
const prevVersion = await $`git rev-parse HEAD^`; // prev version
// Created release version.
await $`sentry-cli releases new ${version}`;

await $`sentry-cli releases files ${version} upload-sourcemaps ${SOURCEMAPS_PATH} --url-prefix ${URL_PREFIX}`;
await $`sentry-cli releases set-commits --commit '${org} / ${name}@${prevVersion}..${rev}' ${rev}`;
await $`sentry-cli releases finalize ${version}`;

```
