### ISSUE TITLE
403

### ISSUE THREAD

**Issue by joaomilho** [getsentry/sentry-cli#446]
I'm trying to install react-native-sentry (or @sentry/cli for that matter). I'm aware this is already discussed in other issues (like #401 ) but since it's closed there I think it's worth reopening, 'cause even if this is a "temporal" problem, it's a problem. Here's my log:

```
> yarn add react-native-sentry@0.40.2 --verbose
...
lots of output
...
verbose 97.996 Error: /.../node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /.../node_modules/@sentry/cli
Output:
Error: Received 403: Forbidden
    at ProcessTermError.ExtendableBuiltin (/.../bin/.yarn/cli.js:237:66)
    at ProcessTermError.MessageError (/.../bin/.yarn/cli.js:266:123)
    at new ProcessTermError (/.../bin/.yarn/cli.js:306:113)
    at ChildProcess.<anonymous> (/.../.yarn/cli.js:30317:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error /.../node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:



```

**Comment by tonyo** [comment]
@joaomilho Could you provide your versions of Yarn (`yarn --version`), Node (`node --version`), and your OS information (e.g. `uname -a` on Linux/Mac)?
Also, does it work if you just do `yarn add @sentry/cli` ?

**Comment by joaomilho** [comment]
Mac. Darwin ... 17.7.0 Darwin Kernel Version 17.7.0.
```
> node --version
v8.11.3
> yarn --version
1.6.0
```

If I go to the folder and run `node scripts/install.js` it actually works.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by karna41317** [comment]
I do have same issue 

 node --version
v12.16.1

**Comment by kamilogorek** [comment]
@karna41317 it looks like you have some connection issues with our CDN that stores the binary.
You may try to point it to a different mirror, eg. `SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ yarn add react-native-sentry@0.40.2`

**Comment by gplcn** [comment]
> 

me too

**Comment by Ramanan-Raguraman** [comment]
Facing same issue 
Node version v8.11.2

**Comment by bruno-garcia** [comment]
Reopened since this seems to continue to happen: https://github.com/getsentry/sentry-react-native/issues/4077

**Comment by bruno-garcia** [comment]
If you're encountering this problem. Please share with us:

1. Sentry CLI version
2. Time when this happened (A timestamp with timezone from CI for example)
3. Org slug (so we can look at logs in Sentry)

Please create a new ticket. I'll close this back since last report was over 2 years ago.
