### ISSUE TITLE
unknown error (http status: 502)

### ISSUE THREAD

**Issue by miriyalee** [getsentry/sentry-cli#449]
![image](https://user-images.githubusercontent.com/35829622/49853887-e98a3d80-fe2b-11e8-95c6-040ad33149bd.png)

Sentry CLI 'randomly' fails to API request with 502 error.

so it breaks whole deploy process.

Our team has lost trust on Sentry and my supervisor wants to replace Sentry with other solution.

I know Sentry is best solution from 4 years ago with my carrier.

Would you please take a look at this problem?

**Comment by miriyalee** [comment]
It is very random, so I should put that code all the time.
Could you track server side errors on your side?

**Comment by mitsuhiko** [comment]
Newer sentry-cli versions will retry 502. If this still happens please reopen.

**Comment by adnan1naeem** [comment]
I am facing this issue in sentry .Please help me in fixing this

**Comment by ryan1336** [comment]
Also facing this issue.
