### ISSUE TITLE
The revocation function was unable to c heck revocation for the certificate

### ISSUE THREAD

**Issue by SDohle** [getsentry/sentry-cli#45]
Version: sentry-cli 0.27.1 and older
OS: Windows 7

Exception:
error: http error: [35] SSL connect error (schannel: next InitializeSecurityCont
ext failed: Unknown error (0x80092012) - The revocation function was unable to c
heck revocation for the certificate.)

I get this error since we updated the certificate on our on premise sentry. It seems to something with rust/cargo/curl under windows: https://github.com/rust-lang/cargo/issues/2464

Our certificat and CA does not contain a revocation!

**Comment by mitsuhiko** [comment]
Sadly there is nothing we can do about it. This is something that happens in curl itself. It seems like you are using a company with SSL interception proxy that is misconfigured to not provide revocation information. In that case you would have to either fix that issue or configure a group policy to not require revocation checks.

This is something that comes from the depths of schannel (the Windows SSL stack).

**Comment by mitsuhiko** [comment]
Actually looks like there might be a way to force this check of in curl. Will investigate.

**Comment by SDohle** [comment]
I just tried it out and it fixes the issue. Great work!
Thank you very much!
