### ISSUE TITLE
Could not automatically determine release name

### ISSUE THREAD

**Issue by emptydriptray** [getsentry/sentry-cli#452]
I've setup sentry-cli following [the docs](https://docs.sentry.io/cli/configuration/).  Whenever i run ` sentry-cli releases propose-version` , I end up with the following error: 

```
$ sentry-cli releases propose-version ---log-level=debug            
 INFO    2018-12-13 11:11:16.517500200 +01:00 Loaded config from C:\Users\<path>\.sentryclirc
  INFO    2018-12-13 11:11:16.519500 +01:00 sentry-cli was invoked with the following command line: "C:\\Users\\<username>\\node\\node_modules\\@sentry\\cli\\bin\\sentry-cli.exe" "releases" "propose-version" "---log-level=debug"
error: Could not automatically determine release name
  DEBUG   2018-12-13 11:11:16.529499 +01:00 client close; no transport to shut down  (from sentry)
```

My .sentryclirc contains the following 
```
[defaults]
org=<myorgname>
project=<myprojectslugname>

[auth]
token=<my-generated-token>

```

`sentry-cli repos list` correctly lists my added (GitHub) repo. 

What am I missing here?

**Comment by markstory** [comment]
Are you running `propose` inside a directory that contains a git repository?

**Comment by frankoostrum** [comment]
> Are you running `propose` inside a directory that contains a git repository?

Yes

**Comment by batjko** [comment]
I have the same issue running my app inside a docker container (therefore without a git repo), and also indirectly via the webpack plugin.
How do I tell the sentry cli what version to use (I am thinking of constructing it from the package.json)?

**Comment by markstory** [comment]
@batjko If you don't have a git directory and want to give your own version, you can do so when calling `sentry-cli releases new`

**Comment by batjko** [comment]
@markstory I appreciate that, but there is no point where I am explicitly calling any sentry-cli command (I just added the webpack plugin, so it can pick up my source maps for my exceptions in Sentry).

I guess I need to read up on the release process...

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
