### ISSUE TITLE
SENTRY_PROPERTIES environment variable ignored

### ISSUE THREAD

**Issue by cecchi** [getsentry/sentry-cli#458]
We have a project built with Webpack that has multiple targets (deployed as distinct Sentry projects), so we need to have multiple Sentry config files in our repo. The Webpack plugin supports a `configFile` option, which sets the `SENTRY_PROPERTIES` environment variable, but it appears to be ignored.

Using the CLI directly, I can see that the CLI does not load the specified config (not that `/Users/cecchi/.sentrycli` is not even a real file):

```
$ export SENTRY_PROPERTIES=/Users/cecchi/Code/deal/consumer-app/sentry.properties 
$ sentry-cli info --log-level=TRACE
  INFO    2019-01-07 10:17:06.873400 -08:00 Loaded config from /Users/cecchi/.sentryclirc
  DEBUG   2019-01-07 10:17:06.873914 -08:00 sentry-cli version: 1.37.2, platform: "darwin", architecture: "x86_64"
  INFO    2019-01-07 10:17:06.873929 -08:00 sentry-cli was invoked with the following command line: "/Users/cecchi/.config/yarn/global/node_modules/@sentry/cli/sentry-cli" "info" "--log-level=TRACE"
  DEBUG   2019-01-07 10:17:06.877602 -08:00 request GET https://sentry.io/api/0/
  DEBUG   2019-01-07 10:17:06.877950 -08:00 retry number 0, max retries: 0
  DEBUG   2019-01-07 10:17:07.075007 -08:00 > GET /api/0/ HTTP/1.1
  DEBUG   2019-01-07 10:17:07.075035 -08:00 > Host: sentry.io
  DEBUG   2019-01-07 10:17:07.075043 -08:00 > Accept: */*
  DEBUG   2019-01-07 10:17:07.075049 -08:00 > Connection: TE
  DEBUG   2019-01-07 10:17:07.075055 -08:00 > TE: gzip
  DEBUG   2019-01-07 10:17:07.075061 -08:00 > User-Agent: sentry-cli/1.37.2
  DEBUG   2019-01-07 10:17:07.115588 -08:00 < HTTP/1.1 200 OK
  DEBUG   2019-01-07 10:17:07.115625 -08:00 < Server: nginx
  DEBUG   2019-01-07 10:17:07.115638 -08:00 < Date: Mon, 07 Jan 2019 18:17:09 GMT
  DEBUG   2019-01-07 10:17:07.115648 -08:00 < Content-Type: application/json
  DEBUG   2019-01-07 10:17:07.115657 -08:00 < Content-Length: 44
  DEBUG   2019-01-07 10:17:07.115666 -08:00 < Connection: keep-alive
  DEBUG   2019-01-07 10:17:07.115674 -08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-01-07 10:17:07.115682 -08:00 < Content-Language: en
  DEBUG   2019-01-07 10:17:07.115690 -08:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-01-07 10:17:07.115699 -08:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-01-07 10:17:07.115709 -08:00 < Allow: GET, HEAD, OPTIONS
  DEBUG   2019-01-07 10:17:07.115718 -08:00 < X-Frame-Options: deny
  DEBUG   2019-01-07 10:17:07.115726 -08:00 < X-Served-By: web-c9683d4c
  DEBUG   2019-01-07 10:17:07.115735 -08:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-01-07 10:17:07.115804 -08:00 response status: 200
  DEBUG   2019-01-07 10:17:07.115822 -08:00 body: {"version": "0", "user": null, "auth": null}
Sentry Server: https://sentry.io
Default Organization: -
Default Project: -
  DEBUG   2019-01-07 10:17:07.117585 -08:00 error: running update nagger
```

If I change the config filename to `.sentryclirc` it works as expected, and my organization/project is outputted.

**Comment by thisjustin** [comment]
Seeing a similar issue but on v1.37.2 and Sentry cli is not picking up vars in our .env like it used to. Seems like this stopped working ~1 month ago. It can't find our org or project name despite them having been set in .env file and the sentry cli script had been using them without issue for quite some time before this.

**Comment by skizzo** [comment]
Did anybody solve this? I'm still getting `error: running update nagger` when trying to use Sentry and CodePush, which renders Sentry pretty much unusable at that point.. :/

**Comment by NRamirezCR** [comment]
@skizzo I had the same issue, maybe no related to the main one. I fixed it by using the correct path to `react-native-xcode.sh`. For some reason I had this:
```../node_modules/react-native/packager/react-native-xcode.sh```
Instead of this:
```../node_modules/react-native/scripts/react-native-xcode.sh```
After fixing that, I was able to build with no errors. I'm still not able to read SENTRY_PROPERTIES tho.

**Comment by kamilogorek** [comment]
I wasn't able to reproduce the original issue. Feel free to ping me if someone is able to provide a repro case.

![image](https://user-images.githubusercontent.com/1523305/76200588-31943d80-61f2-11ea-8059-f33cb37a4a93.png)

Also regarding incorrect config file logging, there's already a PR - https://github.com/getsentry/sentry-cli/pull/677
