### ISSUE TITLE
error: http error: (404)

### ISSUE THREAD

**Issue by xwartz** [getsentry/sentry-cli#46]
Version:  sentry-cli 0.27.1

sentry-cli info

![image](https://cloud.githubusercontent.com/assets/4149827/24142653/273eb6c6-0e62-11e7-8bff-a07394b4ddb2.png)

**Comment by xwartz** [comment]
The same issue here https://forum.sentry.io/t/sentry-cli-releases-new-get-404/961

**Comment by mitsuhiko** [comment]
This comes back if the project does not exist. Check the spelling of the slugs. They need to be the ones you see in the URL in sentry and not the display names.

**Comment by xwartz** [comment]
@mitsuhiko   Thinks, it's worked!
