### ISSUE TITLE
upload-sourcemaps unable to locate typescript source files

### ISSUE THREAD

**Issue by ramirezd42** [getsentry/sentry-cli#463]
I'm using sentry-cli to upload sourcemaps for a release of a typescript node.js project and I'm getting the following error for reach of my files with the --validate flag enabled:

```
...
warning: missing sourcecode (../../../src/shared/[FILENAME].ts)
    ~/shared/[FILENAME].js.map
...
```
Where [FILENAME] is the name of the source file.

The relative path to the **.ts** file (../../../src/shared/[FILENAME].ts) is a valid file from the directory that the **.js.map** file is located in:

```
> cd lib/shared
> ls ../../src/shared/[FILENAME].ts
../../src/shared/[FILENAME].ts
```

So I'm not sure why its unable to find the source file.

The command I'm running is

```
sentry-cli  --url http://localhost:9000 --auth-token=[...] releases --org=[...] --project=[...] files [RELEASE_NAME] upload-sourcemaps ./lib --rewrite --ext js --ext map --ext ts --validate
```

And here is an example source map file (lib/shared/foo.js.map)

```
{"version":3,"file":"foo.js","sourceRoot":"","sources":["../../src/shared/foo.ts"],"names":[],"mappings":"..."}
```

My project is structed so that source code files go into a **src** folder at the root of the project and the compiled and source map files go into a **lib** folder at the root of the project

```
project_dir/
|-- lib/
|    |-- [All compiled .js and .js.map files] 
+-- src/
    |-- [All source .ts files]
```

I'd really appreciate any pointers in troubleshooting this issue

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by irfan798** [comment]
I'm having the same issue this time with a monorepo setup.
 
> The relative path to the .ts file (../../../src/shared/[FILENAME].ts) is a valid file from the directory that the .js.map file is located in:

But it says missing sourcecode for every file that has been compiled from typescript.

@ramirezd42 Did you by change found a solution?
