### ISSUE TITLE
Add CI option to install script

### ISSUE THREAD

**Issue by florianmutter** [getsentry/sentry-cli#464]
When using the install script in an CI environment it us not useful to output a curl progress bar on stderr. This does clutter up the build log. This is an example from codeship:

    (image: com.example/my-project) (service: testapp) Step 15/22 : RUN curl -sL https://sentry.io/get-cli/ | bash
    (image: com.example/my-project) (service: testapp) 
    (image: com.example/my-project) (service: testapp)  ---> Running in e33884679777
    (image: com.example/my-project) (service: testapp) This script will automatically install sentry-cli 1.37.2 for you.
    Installation path: /usr/local/bin/sentry-cli
    (image: com.example/my-project) (service: testapp) Warning: this script is currently running as root.    This is dangerous. 
         Instead run it as normal user. We will sudo as needed.
    #                                                                          1.6%
    ##                                                                         3.6%
    ####                                                                       5.6%
    #####                                                                      7.5%
    (image: com.example/my-project) (service: testapp) 
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) #   
    (image: com.example/my-project) (service: testapp)   
    (image: com.example/my-project) (service: testapp)              
    (image: com.example/my-project) (service: testapp)  
    (image: com.example/my-project) (service: testapp)  
    (image: com.example/my-project) (service: testapp)  
    (image: com.example/my-project) (service: testapp)                                                9.8%
    (image: com.example/my-project) (service: testapp) 
    (image: com.example/my-project) (service: testapp) #
    (image: com.example/my-project) (service: testapp) ####### 
    (image: com.example/my-project) (service: testapp)                
    (image: com.example/my-project) (service: testapp)     

I think it would be nice to have an ci option that is script friendly. Maybe skip the root user warning and do not output a progress bar.

**Comment by florianmutter** [comment]
One workaround ist calling the install script like this: `curl -sL https://sentry.io/get-cli/ | sed -e "s/curl -SL --progress-bar/curl -sL/g" | bash`

**Comment by mitsuhiko** [comment]
If you pipe through `cat` or something it will stop doing that. Going to close this as I think this should be good enough as a workaround.
