### ISSUE TITLE
(upload-dif) Skipping invalid debug file warning should display a file name

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-cli#466]
Howdy,

I'm trying to upload some existing .sym files but I'm hitting a bunch of errors, and it's unclear which files are problematic.

```
file
  WARN    2019-01-15 20:29:01.658025805 +00:00 Skipping invalid debug file: failed to read object file
⠐ Searching for debug symbol files...
⠒ Searching for debug symbol files...
  found 90 633F3E7727143A2184F79A660F5A81DE0/foo.sym
```

It would be quite helpful to display a file name so we know which file is causing problems.

**Comment by bsergean** [comment]
For the record all the files that are causing trouble seem to be iOS arm32 bits. I peeked at 2 of them and they start with:

```
MODULE mac armv7 B8C3832869C5302F8E9F29E4BE7ED02B0 <app_name>
```

**Comment by bsergean** [comment]
BTW, passing --log-level DEBUG let me show the file that failed to be processed, which is sufficient but maybe not ideal from a UI pov.

**Comment by jan-auer** [comment]
@bsergean How did you create this symbol file? `armv7` is not a valid Breakpad symbol architecture constant in the version we're using (and also not in the current master, from what I could tell).

**Comment by bsergean** [comment]
I can't remember how I got this file, it might have been part of an old unittest. At some point I tried to download system symbols (.so) from Android devices using the Android debugger (adb), and make .sym files out of those. It might have come from there.

**Comment by bsergean** [comment]
Thanks !
