### ISSUE TITLE
For non git repositories explicit revisions are required

### ISSUE THREAD

**Issue by ndasim** [getsentry/sentry-cli#469]
Hi, I'm trying to associate commits with versions in my Android project. In my first try I accidently associate commits with wrong version number, I removed that release with `sentry-cli releases remove` and re-tried associating commits but I'm getting error now, I didn't found any coverage over internet about that issue.

I'm sharing info messages of `sentry-cli releases set-commits --auto 5.1.0.12`

Info message:
```
  INFO    2019-01-18 17:17:35.456694300 +03:00 Loaded config from C:\Users\***\.sentryclirc
  INFO    2019-01-18 17:17:35.460683100 +03:00 sentry-cli was invoked with the following command line: "sentry-cli" "releases" "set-commits" "--auto" "5.1.0.12" "--log-level=info"
  INFO    2019-01-18 17:17:36.247094500 +03:00 Resolving HEAD (***/***@HEAD)
  INFO    2019-01-18 17:17:36.301946500 +03:00   -> no matching revision found
  INFO    2019-01-18 17:17:36.302943700 +03:00 Resolving HEAD (***/***@HEAD)
  INFO    2019-01-18 17:17:36.336850700 +03:00   -> no matching revision found
  INFO    2019-01-18 17:17:36.337849700 +03:00 Resolving HEAD (***/***@HEAD)
  INFO    2019-01-18 17:17:36.340839900 +03:00 Skipping update nagger update check
error: For non git repositories explicit revisions are required   
```

I checked git repo and tried resetting HEAD but nothing happened

**Comment by markstory** [comment]
Have you added your repository to sentry via one of our SCM integrations?

**Comment by ndasim** [comment]
Yes, as I said, I successfully associated commits in my first attempt but I realized that I set wrong version number and I delete that version via sentry-cli.

Now, I'm not able to re-associate those commits. I'm getting that error

**Comment by markstory** [comment]
It looks like sentry-cli cannot determine the repository head. Are you in a detached head state in your git clone?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
