### ISSUE TITLE
Release Commit Management

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-cli#47]
We want a new command like this:

    sentry-cli releases VERSION set-commits --repo-id github:foo/bar --git-repo /path/to/git/repo --rev 1234deadbeef

That sets the commits based on the latest release commit and the provided revision in the given repo. Alternative things we probably want:

* `--tag` to specify a tag instead
* `--branch` to specify a branch instead
* `--repo` should probably be either a local checkout or a remote repository of url?

**Comment by brettmcintosh** [comment]
I'm interested in helping out with this feature, but I don't quite get what you're asking for.  When you say 

> sets the commits based on ...

what commits are you talking about?

**Comment by mitsuhiko** [comment]
We're adding an API to sentry where you can specify some commits that will show up with the release feature. This API has changed since this ticket was made so now instead of providing all the commits only the HEAD commit is added and the server does the rest.
