### ISSUE TITLE
caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

### ISSUE THREAD

**Issue by yongjing** [getsentry/sentry-cli#470]
I am try to upload dsym files, I find the sentry-cli command not work anymore.
sentry-cli 1.37.4 installed.
the details:
➜  ios release git:(staging) ✗ sudo sentry-cli --auth-token xxxxxxxxxxxxxxx upload-dsym --org xxx-xxx --project appli-ios-dev --info-plist ./Environment/Beta/InfoBeta.plist ./ --log-level=debug
Password:
  INFO    2019-01-24 12:15:07.584756 +01:00 Loaded config from /Users/xxxx/.sentryclirc
  DEBUG   2019-01-24 12:15:07.585405 +01:00 sentry-cli version: 1.37.4, platform: "darwin", architecture: "x86_64"
  INFO    2019-01-24 12:15:07.585449 +01:00 sentry-cli was invoked with the following command line: "sentry-cli" "--auth-token" "xxxxxxxxxxxxxxxxxxx" "upload-dsym" "--org" "xxx-xxx" "--project" "appli-ios-dev" "--info-plist" "./Environment/Beta/InfoBeta.plist" "./" "--log-level=debug"
  DEBUG   2019-01-24 12:15:07.587482 +01:00 request GET https://sentry.io/api/0/organizations/xxx-xxx/chunk-upload/
  DEBUG   2019-01-24 12:15:07.587523 +01:00 using token authentication
  DEBUG   2019-01-24 12:15:07.587541 +01:00 retry number 0, max retries: 0
  DEBUG   2019-01-24 12:15:07.939320 +01:00 > GET /api/0/organizations/xxx-xxx/chunk-upload/ HTTP/1.1
  DEBUG   2019-01-24 12:15:07.939352 +01:00 > Host: sentry.io
  DEBUG   2019-01-24 12:15:07.939362 +01:00 > Accept: */*
  DEBUG   2019-01-24 12:15:07.939370 +01:00 > Connection: TE
  DEBUG   2019-01-24 12:15:07.939378 +01:00 > TE: gzip
  DEBUG   2019-01-24 12:15:07.939386 +01:00 > User-Agent: sentry-cli/1.37.4
  DEBUG   2019-01-24 12:15:07.939815 +01:00 > Authorization: Bearer 320e5d1b***
  DEBUG   2019-01-24 12:15:08.155087 +01:00 < HTTP/1.1 403 FORBIDDEN
  DEBUG   2019-01-24 12:15:08.155167 +01:00 < Server: nginx
  DEBUG   2019-01-24 12:15:08.155196 +01:00 < Date: Thu, 24 Jan 2019 11:15:08 GMT
  DEBUG   2019-01-24 12:15:08.155222 +01:00 < Content-Type: application/json
  DEBUG   2019-01-24 12:15:08.155246 +01:00 < Content-Length: 64
  DEBUG   2019-01-24 12:15:08.155266 +01:00 < Connection: keep-alive
  DEBUG   2019-01-24 12:15:08.155285 +01:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-01-24 12:15:08.155316 +01:00 < Content-Language: en
  DEBUG   2019-01-24 12:15:08.155347 +01:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-01-24 12:15:08.155381 +01:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-01-24 12:15:08.155409 +01:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2019-01-24 12:15:08.155430 +01:00 < X-Frame-Options: deny
  DEBUG   2019-01-24 12:15:08.155448 +01:00 < X-Served-By: web-c401c6a4
  DEBUG   2019-01-24 12:15:08.155467 +01:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-01-24 12:15:08.155530 +01:00 response status: 403
  DEBUG   2019-01-24 12:15:08.155572 +01:00 body: {"detail": "You do not have permission to perform this action."}
  DEBUG   2019-01-24 12:15:08.155752 +01:00 error: running update nagger
  INFO    2019-01-24 12:15:08.156075 +01:00 Skipping update nagger update check
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
  DEBUG   2019-01-24 12:15:08.158524 +01:00 client close; no transport to shut down  (from sentry)

**Comment by tonyo** [comment]
@yongjing could you check that the API token you're using has `project:write` permissions?
Here's the relevant page: https://sentry.io/settings/account/api/auth-tokens/

**Comment by yongjing** [comment]
thank you @tonyo I found the pb, the token is not valid (the account with the auth token was deleted recently)

**Comment by DominicTobias** [comment]
I get this error with a valid token I just created just trying to run `sentry-cli sourcemaps explain <hash>` which I assume is readonly

**Comment by SamuelHathcock** [comment]
in the most recent sentry version, at least on the free plan, when creating a new token or modifying an existing token, their is no option to change the scope.
