### ISSUE TITLE
Documentation missing for appcenter and react native to generate sourcemaps

### ISSUE THREAD

**Issue by fungilation** [getsentry/sentry-cli#479]
On https://docs.sentry.io/clients/react-native/codepush/ and related to #476 on my migration from code-push-cli to appcenter-cli.

`appcenter` cli, unlike `code-push` before, do not generate sourcemaps by default. `appcenter help codepush release-react` lists a `-s|--sourcemap-output <arg>`, as it also says "if omitted, a sourcemap will not be generated."

If sentry-cli only uploads minified script and source maps from what appcenter generates, then documentation should be updated for the missing `-s` param.

**Comment by s1mon-w** [comment]
+1 Any updates on this one?

**Comment by mieszko4** [comment]
Also this doc is wrong https://docs.sentry.io/clients/react-native/codepush/
It says to use `./build/codePush` but codepush generates files at `CodePush`

**Comment by matt-dalton** [comment]
Thanks @mieszko4 - took me far too long to realise `./build/codePush` -> `./build/CodePush`!

Would definitely be good to get those docs updated

**Comment by kamilogorek** [comment]
Updated https://github.com/getsentry/sentry-docs/pull/1534/files
