### ISSUE TITLE
Partial upload of files

### ISSUE THREAD

**Issue by belemaire** [getsentry/sentry-cli#483]
Hi,

I am currently evaluating Sentry for our company needs for React Native projects.

It seems like I am facing an issue when using `releases` / `upload-source-maps` where only some files get uploaded to the server. 

It seems like 9989 files need to be uploaded, but when running the command only a few hundreds get uploaded then the cli terminates without error (I activated debug log level and nothing alarming gets logged either). 

I tried running the command multiple times and the number of files uploaded vary from run to run, but never more than a few hundreds. Looks like there is a timeout of some sort or I don't know.

Here is the command I am using :

```
SENTRY_AUTH_TOKEN=******* SENTRY_PROJECT=evaluation-react-native node_modules/@sentry/cli/bin/sentry-cli releases --org benoit-lemaire files com.walmartlabs.ern-1.0 upload-sourcemaps --dist 1 --strip-prefix /Users/blemair/evaluation-sentry --rewrite /Users/blemair/evaluation-sentry
```

And here is a sample log of one of the run (308 files out of 9989 where properly uploaded for this one)

```
> Analyzing 9989 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release com.walmartlabs.ern-1.0
> ~/node_modules/create-react-class/node_modules/core-js/modules/library/es6.function.name.js
███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 308/9989
```

Any idea what is going on ?

Thanks !

**Comment by belemaire** [comment]
Closing issue for now while I'm trying to figure things on my own and make sure I'm doing things correctly. Will reopen if needed.

**Comment by Jakst3r** [comment]
Did you figure this one out? I'm having a similar issue.

**Comment by belemaire** [comment]
@Jakst3r 
No I haven't been able to figure it out, seems like a bug in their CLI or server.
But in the end I realized that uploading all files was not needed in my use case, only the JS source map and the bundle needed to be uploaded, so I just closed this issue.

**Comment by Jakst3r** [comment]
Turns out I was having 2 issues.

1) Uploading an empty file caused it to fail #501

2) `Timeout reading 65536 bytes. Content-Length: 6265927 consumed: 0 left: 6265927`
I'm running Sentry in docker, The `sentry.conf.py` file wasn't mapped to the docker container, I added that as a volume
Then I had to modify it like so to fix this error

```
File: sentry.conf.py

<SNIP>

SENTRY_WEB_OPTIONS = {
    'workers': 10,
    'socket-timeout': 300, # This fixed the issue
}

<SNIP>
```

```
File: docker-compose.yml

<SNIP>

 web:
    <<: *defaults
    ports:
      - '9000:9000'
    container_name: sentry_web_01
    volumes:
      - /home/sentry/onpremise/sentry.conf.py:/etc/sentry/sentry.conf.py

<SNIP>
```


The command I'm using to upload the source maps is: 
```./node_modules/.bin/sentry-cli releases files "$sentryVERSION" upload-sourcemaps --rewrite --url-prefix "~/assets" ./dist/test/assets```

**Comment by MartinLoeper** [comment]
I observe the same issue! Sometimes the upload is interrupted after a few files being uploaded.
