### ISSUE TITLE
sentry-cli releases failed

### ISSUE THREAD

**Issue by Moirafu** [getsentry/sentry-cli#492]
i try to upload source-map to sentry. i use:
sentry-cli releases --org xxxx -p xxxx files staging@1.0.1 upload-sourcemaps './dist' --url-prefix '~'.
my .map files in dist. and my online js files in 'xxxxxx(ip)/' (i try to monitor my local server).And sentry-cli did not respond. it only gives help tips as follow:

sentry-cli-releases
Manage releases on Sentry.

USAGE:
    sentry-cli releases <SUBCOMMAND>

OPTIONS:
    -h, --help                     Prints help information
        --log-level <LOG_LEVEL>
            Set the log output verbosity.
            [valid levels: TRACE, DEBUG, INFO, WARN, ERROR]
    -o, --org <ORG>                The organization slug

SUBCOMMANDS:
    delete             Delete a release.
    deploys            Manage release deployments.
    files              Manage release artifacts.
    finalize
            Mark a release as finalized and released.

    help
            Prints this message or the help of the given
            subcommand(s)
    info               Print information about a release.
    list               List the most recent releases.
    new                Create a new release.
    propose-version
            Propose a version name for a new release.

    set-commits        Set commits of a release.

 how can i upload source-map?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
