### ISSUE TITLE
getsentry/sentry-cli Docker image shows a warning

### ISSUE THREAD

**Issue by ianjamieson** [getsentry/sentry-cli#493]
Relating to: https://github.com/getsentry/sentry-cli/pull/368

I am running:

```
docker run --rm \
-e VERSION=1.2.2 \
-v $(pwd):/work \
getsentry/sentry-cli sh \
-c "echo $VERSION"
```

But I get the warning:

```
======================================================================
=== WARNING: Entrypoint of this Docker image has changed. ============
=== Future versions of the image might not work correctly for you. ===
=== More details: https://github.com/getsentry/sentry-cli#docker =====
======================================================================
```

Which I can see is as expected in by:

https://github.com/getsentry/sentry-cli/blob/3fb080e9f10be0d8d171fc38f58f4b27f800143a/docker-entrypoint.sh#L17

**Expected Outcome**
Not to show the warning

**Comment by tonyo** [comment]
It's expected. The warning is there mainly for people who use the image on GitLab CI and other systems that override entrypoints, see https://github.com/getsentry/sentry-cli/issues/366 for more details.
If you're curious why your VERSION ("1.2.2") is not in the output: your shell most likely performs the substitution even before the container is started. If you use "bash", you can e.g. use single quotes:
```
docker run --rm -e VERSION=1.2.2 -v $(pwd):/work getsentry/sentry-cli sh -c 'echo $VERSION'
```
