### ISSUE TITLE
Ignoring files with negation pattern

### ISSUE THREAD

**Issue by niksy** [getsentry/sentry-cli#498]
It seems like ignoring files doesn’t work with negation patterns. For example, if I ignore file !core*, I would expect that all files not containing core in their name should be published. This is contradictory to statement that `--ignore-file` could point to file in the same format as .gitignore, but standard Git ignore file supports negation patterns. Am I doing something wrong?

**Comment by kamilogorek** [comment]
Just verified it locally and everything seems to work just fine now (checked with `ba*` vs. `!bar*` as well).

![image](https://user-images.githubusercontent.com/1523305/76215927-fd2f7a00-620f-11ea-944b-7ef82e7abbdb.png)
