### ISSUE TITLE
Wrong release naming for appcenter codepush

### ISSUE THREAD

**Issue by pvinis** [getsentry/sentry-cli#500]
Using the following
```
appcenter codepush release-react --deployment-name Alpha --target-binary-version 0.20000.1 --description "a test" --mandatory --development false --output-dir . --disable-duplicate-release-error
```
to do a codepush release and then using
```
SENTRY_PROPERTIES=./ios/sentry.properties ./node_modules/@sentry/cli/sentry-cli react-native appcenter TheAppName ios ./CodePush --deployment Alpha --bundle-id the.app.name
```
to upload the sourcemaps and make the sentry release, we get releases like
![Screenshot 2019-03-20 at 16 16 51](https://user-images.githubusercontent.com/100233/54696151-99f29680-4b2b-11e9-9998-f7317b23ef2b.png)

This is a bit of a problem because if we do `Sentry.setVersion(${update.appVersion}-codepush:${update.label})` then sentry creates a new release with the correct name like
![Screenshot 2019-03-20 at 16 18 50](https://user-images.githubusercontent.com/100233/54696316-e4741300-4b2b-11e9-80fe-f4136826d314.png)
but no assets. The assets are in the `codepush:v48` release.

Can we fix that with an arg on the command? Is it required for you to fix it?

Thanks.

**Comment by tangnv** [comment]
@pvinis let try my PR for temporary:
https://github.com/getsentry/sentry-cli/pull/506

**Comment by pvinis** [comment]
I'll try it, thanks.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue. 
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
