### ISSUE TITLE
Segfault when uploading blank artifact

### ISSUE THREAD

**Issue by rma-stripe** [getsentry/sentry-cli#501]
Attempting to upload a js file that is blank results in a segfault as shown:

```
> Uploading source maps for release 63978de
  DEBUG   2019-03-21 13:24:42.343448 -07:00 request POST https://sentry.io/api/0/projects/randall-ma/test-node/releases/63978de/files/
  DEBUG   2019-03-21 13:24:42.343786 -07:00 using token authentication
  DEBUG   2019-03-21 13:24:42.344097 -07:00 sending form data
  DEBUG   2019-03-21 13:24:42.344414 -07:00 retry number 0, max retries: 5
> ~/empty.js
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/1
[1]    73760 segmentation fault  SENTRY_ORG=randall-ma SENTRY_AUTH_TOKEN= SENTRY_DISABLE_UPDATE_CHECK=1 =
```

This is using sentry-cli built from the latest version available on GitHub, with the following params:

`sentry-cli releases files VERSION upload-sourcemaps FOLDER --no-rewrite --log-level=trace`

To reproduce, `mkdir FOLDER && touch empty.js`.

**Comment by kylethielk** [comment]
I'm also able to reproduce this on my end with version 1.41.0

We include quite a few node modules that seem to have a large number of empty files making this essentially impossible on our end.

**Comment by Jakst3r** [comment]
I have the same issue with version 1.43.0

**Comment by mitsuhiko** [comment]
Fixed in latest release.
