### ISSUE TITLE
How use release version as git tag

### ISSUE THREAD

**Issue by kolesoffac** [getsentry/sentry-cli#503]
I have git tags(etc v1.0.0).
Command
`sentry-cli releases propose-version`
get SHA from git.

I want to get tag from git HEAD.

It's realy?

**Comment by jan-auer** [comment]
You don't need to use `propose-version` and are free to set the release to a custom name instead by whatever means you prefer. However, keep in mind:
 - Release names must be unique in your entire organization across projects. `v1.0.0` will therefore likely not be sufficient, rather something like `mystuff-v1.0.0`.
 - Make sure that the release name used to upload artifacts matches the one built into your product (for configuring the Sentry SDK). For example, when using our webpack plugin, you can manually set this release name in the options, which takes care of both.

`propose-version` is written in a way where it generates reproducible, unique release names. In most cases it uses the git SHA, with special logic in some other cases.
