### ISSUE TITLE
Support different bundle names other than main.jsbundle

### ISSUE THREAD

**Issue by junkinthetrunk** [getsentry/sentry-cli#505]
I currently have a React Native CocoaPod that has a different naming convention than the standard main.jsbundle. The bundle files are under Pod/Assets/```podname```.js. 

Using the ```sentry-cli react-native xcode \
  ../node_modules/react-native/scripts/react-native-xcode.sh``` does not upload the correct files when the bundle name has been set to the correct one.   If I upload the ```podname```.js file and source map manually to  a release, the crashes do not show any SourceMap information.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
