### ISSUE TITLE
Can't upload Electron 4.1.4 darwin symbols using sentry-cli

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-cli#509]
This might be more of a sentry-cli issue, but it's specifically Electron's symbol files so I figured it was more appropriate to ask here.

We upgraded from Electron 3->4 and I'm trying to upload Electron symbols to Sentry for native crash reporting. I'm using the "manual" instructions [here](https://docs.sentry.io/platforms/javascript/electron/native/#uploading-debug-information).

```
$ export SENTRY_LOG_LEVEL=debug
$ ./node_modules/.bin/sentry-cli upload-dif -t dsym ~/Downloads/electron-v4.1.4-darwin-x64-dsym.zip --org=my-org --project=my-project
```

It seems to make progress for a while then it hangs here, for at least 15+ minutes:

![image](https://user-images.githubusercontent.com/107841/55778348-8914b100-5a57-11e9-9265-e81e2ef7c215.png)

It goes from "found 1", to "found 2", etc. but when it gets to "found 4" it just seems to search forever.

Any ideas?

**Comment by jan-auer** [comment]
Thanks, @aguynamedben. Moved this to the sentry-cli repository since this is in fact an issue with sentry-cli, potentially even [`symbolic`](https://github.com/getsentry/symbolic). We've made a couple of internal changes to the DIF upload recently and this might be related.

**Comment by aguynamedben** [comment]
@jan-auer Cool, thanks for the quick response. Feel free to close here.

**Comment by jan-auer** [comment]
Turns out, `sentry-cli` is getting very slow when extracting large files from ZIP archives. As a workaround, I would suggest to extract the ZIP archive and invoke `sentry-cli upload-dif` on the folder instead.

**Comment by jan-auer** [comment]
One more thing, `Electron Framework.dSYM` is approaching 2GB, which is Sentry's hard limit for debug files. There will be no way to upload files that are larger. We're currently considering new approaches to allow debugging with files this big, but for now there is no workaround.

At least on Linux, we support zlib compressed debug sections. This helps to reduce the file size. I'm open to inputs if compression of debug information is a thing on other platforms. Note that compressing the entire file is not an option, though.

**Comment by jan-auer** [comment]
Slow uploads should be fixed with [1.41.2](https://github.com/getsentry/sentry-cli/releases/tag/1.41.2) now.

**Comment by aguynamedben** [comment]
Another win for @jan-auer. Seemed to work! Thank you. 🙏

Re: the 2GB file size limit in the future... (warning: I'm not an expert at native crash debugging), here's a product idea:
* We're not custom building Electron, and I'd be surprised if a lot of Electron users are custom building. The fact that I'm required to upload these debug files for a stock version of Electron was a little unexpected.
* Could Sentry attain all the .dSYM for the published versions of Electron?
* Could Sentry then cross-reference the already-reported `runtime` value of `Electron 4.1.4` with symbols from `electron-v4.1.4-darwin-x64-dsym.zip` to provide "built-in" native crash reporting for Electron without users having to upload symbols?

Maybe this is something for down the road when you have more Electron customers. I'm not sure if the 2GB limit is a file transfer issue for Sentry or if it's actually a performance that occurs during the actual analysis of a crash.

Thanks again!

**Comment by jan-auer** [comment]
All the praise to @mitsuhiko, who provided the fix this time :)

The good news are: We are building [infrastructure](https://github.com/getsentry/symbolicator) at the moment that will allow us to do exactly that (you got ahead of us here). For major common frameworks and platforms - Electron being one example - we might start to pull debug files automatically. It will still take us some time to get to Electron, however.

The 2GB file size limit is rooted in how Sentry currently stores debug files internally. Once the new infrastructure is in place, we will start offering options to ingest larger files.

Thanks for the suggestions, such feedback is always much appreciated 👍

**Comment by aguynamedben** [comment]
Rad.

**Comment by jan-auer** [comment]
For future travellers, you can activate the "Electron Symbol Server" in _Project Settings > Debug Files_ and don't have to upload Electron's native debug information anymore:

![Electron Symbol Server](https://images.ctfassets.net/em6l9zw4tzag/5zQC3pIekvjL5tzVPgHKRI/8dfaab137a6c4ae860379c845987d6be/debug-information.png)

**Comment by aguynamedben** [comment]
@jan-auer Awesome! We're about to upgrade from Electron 4->5 so we'll try this instead of uploading manually.

**Comment by aguynamedben** [comment]
Ah, we already did it when the symbols for Electron went above 2GB, an everything works well. Thanks @jan-auer for this feature. 🙏

**Comment by jeremyspiegel** [comment]
@jan-auer I'm using a custom Electron build, any update on when it will be possible to upload debug files larger than 2GB? Or do you happen to have steps or an example for setting up a custom repository from my Electron build?

**Comment by vivekpd15** [comment]
> For future travellers, you can activate the "Electron Symbol Server" in _Project Settings > Debug Files_ and don't have to upload Electron's native debug information anymore:
> 
> ![Electron Symbol Server](https://camo.githubusercontent.com/9441ff4afdeeb1c1203661e3ebd2e26e5f4c19a8/68747470733a2f2f696d616765732e6374666173736574732e6e65742f656d366c397a7734747a61672f357a5143337049656b766a4c35747a565067484b52492f38646661616231333761366334616538363033373963383435393837643662652f64656275672d696e666f726d6174696f6e2e706e67)

I am using the on premise version of sentry 9.1.2

This feature isn't available there. Any workarounds?

**Comment by jan-auer** [comment]
The workaround for Sentry 9.1.2 is to use the `Electron Framework.sym` file.
For custom Electron builds with files larger than 2GB, the only way is to push the files to your own symbol server which is supported in Sentry 10. See [this page](https://docs.sentry.io/workflow/debug-files/#custom-repositories) for docs.
