### ISSUE TITLE
caused by: [55] Failed sending data to the peer

### ISSUE THREAD

**Issue by ERICJUNJIE** [getsentry/sentry-cli#514]
DEBUG   2019-04-18 14:12:47.481118 +08:00 request GET https://sentry.io/api/0/organizations/ecool/chunk-upload/
  DEBUG   2019-04-18 14:12:47.483781 +08:00 using token authentication
  DEBUG   2019-04-18 14:12:47.483933 +08:00 retry number 0, max retries: 0
  DEBUG   2019-04-18 14:12:49.402644 +08:00 > GET /api/0/organizations/ecool/chunk-upload/ HTTP/1.1
  DEBUG   2019-04-18 14:12:49.402795 +08:00 > Host: sentry.io
  DEBUG   2019-04-18 14:12:49.402881 +08:00 > Accept: */*
  DEBUG   2019-04-18 14:12:49.402964 +08:00 > Connection: TE
  DEBUG   2019-04-18 14:12:49.403046 +08:00 > TE: gzip
  DEBUG   2019-04-18 14:12:49.403128 +08:00 > User-Agent: sentry-cli/1.41.0
  DEBUG   2019-04-18 14:12:49.403846 +08:00 > Authorization: Bearer 04c75886***
  DEBUG   2019-04-18 14:12:49.848977 +08:00 < HTTP/1.1 200 OK
  DEBUG   2019-04-18 14:12:49.849147 +08:00 < Server: nginx
  DEBUG   2019-04-18 14:12:49.849246 +08:00 < Date: Thu, 18 Apr 2019 06:12:49 GMT
  DEBUG   2019-04-18 14:12:49.849341 +08:00 < Content-Type: application/json
  DEBUG   2019-04-18 14:12:49.849433 +08:00 < Content-Length: 237
  DEBUG   2019-04-18 14:12:49.849525 +08:00 < Connection: keep-alive
  DEBUG   2019-04-18 14:12:49.849614 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-04-18 14:12:49.849704 +08:00 < Content-Language: en
  DEBUG   2019-04-18 14:12:49.849793 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-04-18 14:12:49.849886 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-04-18 14:12:49.849977 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2019-04-18 14:12:49.850067 +08:00 < X-Frame-Options: deny
  DEBUG   2019-04-18 14:12:49.850158 +08:00 < X-Served-By: web-c401c6a4
  DEBUG   2019-04-18 14:12:49.850246 +08:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-04-18 14:12:49.850365 +08:00 response status: 200
  DEBUG   2019-04-18 14:12:49.850459 +08:00 body: {"maxFileSize": 2147483648, "hashAlgorithm": "sha1", "concurrency": 4, "chunkSize": 8388608, "maxRequestSize": 33554432, "url": "https://sentry.io/api/0/organizations/ecool/chunk-upload/", "chunksPerRequest": 64, "compression": ["gzip"]}
> Found 11 debug information files
> Prepared debug information files for upload
  DEBUG   2019-04-18 14:12:53.107277 +08:00 request POST https://sentry.io/api/0/projects/ecool/react-native/files/difs/assemble/
  DEBUG   2019-04-18 14:12:53.107417 +08:00 using token authentication
  DEBUG   2019-04-18 14:12:53.107695 +08:00 json body: {"2c72c98766668a0989308b435d9e3265936167ca":{"name":"RxBluetoothKit","chunks":["2c72c98766668a0989308b435d9e3265936167ca"]},"55dd83c45cbd358e52b9847512708e3b3d6ff708":{"name":"SwiftyJSON","chunks":["55dd83c45cbd358e52b9847512708e3b3d6ff708"]},"11578871e328b36f7d045b4c65a3892757341161":{"name":"SwiftyJSON","chunks":["11578871e328b36f7d045b4c65a3892757341161"]},"55c4397fbade2c17f2a73de897db6334f19754c3":{"name":"ShopDiary","chunks":["8a74b33bff3a9cec9e68d18017a7d5812c0efb46","3e90a2f8e6d004a9f257e4660ec63ab16dfe37bc","e9ed081fe792b8f91cbaddc86106184d238d5b70","133f17952b6ff2907c197476dfd8cbadd3f4f2df","8b9014337d6b1e337df9acd4ccfec0d2402d6fb7","4cebdbf21606fa9c631321ddf3731d21a0157418","bd35e36dc79b67632f382b6858c909955e1d4b4c","ed374f55a22e54a9961ca98a2c61eabf817d6c42","da97efacef2ce3c2679bf65ebdcfc30cb82daf74","55743350cf1625669daa23d0ed38be2eec758253","e32e35916abed2ec1e71ead4654df5596474d16a","6db44ae4750ff2fc37668c4dda3d657811f947e4"]},"586275fb76e033d57b0077da1c28cb40da0521df":{"name":"BleClientManager","chunks":["586275fb76e033d57b0077da1c28cb40da0521df"]},"5d3cc708a365ab8545dc6e581adaf720cde0ffa2":{"name":"Charts","chunks":["5d3cc708a365ab8545dc6e581adaf720cde0ffa2"]},"7da2a6946e8d7a82a3c95fa4d484b6bffce5695b":{"name":"RxSwift","chunks":["7da2a6946e8d7a82a3c95fa4d484b6bffce5695b"]},"b72c34e30a5b1b267a602044b9a597e30c313755":{"name":"RxBluetoothKit","chunks":["b72c34e30a5b1b267a602044b9a597e30c313755"]},"948e6f4f1785077067117b5b6deb0c9731573042":{"name":"Charts","chunks":["948e6f4f1785077067117b5b6deb0c9731573042"]},"53508a3f3094066eb0199ab01084b8a866ee903c":{"name":"BleClientManager","chunks":["53508a3f3094066eb0199ab01084b8a866ee903c"]},"87cf18ab6784e2f608bd200dca474fc37da0d9d6":{"name":"RxSwift","chunks":["87cf18ab6784e2f608bd200dca474fc37da0d9d6"]}}
  DEBUG   2019-04-18 14:12:53.108007 +08:00 retry number 0, max retries: 5
  DEBUG   2019-04-18 14:12:53.108341 +08:00 > POST /api/0/projects/ecool/react-native/files/difs/assemble/ HTTP/1.1
  DEBUG   2019-04-18 14:12:53.108592 +08:00 > Host: sentry.io
  DEBUG   2019-04-18 14:12:53.108786 +08:00 > Accept: */*
  DEBUG   2019-04-18 14:12:53.108982 +08:00 > Connection: TE
  DEBUG   2019-04-18 14:12:53.109206 +08:00 > TE: gzip
  DEBUG   2019-04-18 14:12:53.109299 +08:00 > User-Agent: sentry-cli/1.41.0
  DEBUG   2019-04-18 14:12:53.109420 +08:00 > Authorization: Bearer 04c75886***
  DEBUG   2019-04-18 14:12:53.109641 +08:00 > Content-Type: application/json
  DEBUG   2019-04-18 14:12:53.109741 +08:00 > Content-Length: 1788
  DEBUG   2019-04-18 14:12:55.427175 +08:00 < HTTP/1.1 200 OK
  DEBUG   2019-04-18 14:12:55.427483 +08:00 < Server: nginx
  DEBUG   2019-04-18 14:12:55.427600 +08:00 < Date: Thu, 18 Apr 2019 06:12:53 GMT
  DEBUG   2019-04-18 14:12:55.427690 +08:00 < Content-Type: application/json
  DEBUG   2019-04-18 14:12:55.427779 +08:00 < Content-Length: 6362
  DEBUG   2019-04-18 14:12:55.427864 +08:00 < Connection: keep-alive
  DEBUG   2019-04-18 14:12:55.427947 +08:00 < Vary: Accept-Encoding
  DEBUG   2019-04-18 14:12:55.428032 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-04-18 14:12:55.428115 +08:00 < Content-Language: en
  DEBUG   2019-04-18 14:12:55.428213 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-04-18 14:12:55.428298 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-04-18 14:12:55.428380 +08:00 < Allow: POST, OPTIONS
  DEBUG   2019-04-18 14:12:55.428466 +08:00 < X-Frame-Options: deny
  DEBUG   2019-04-18 14:12:55.428549 +08:00 < X-Served-By: web-c401c6a4
  DEBUG   2019-04-18 14:12:55.428632 +08:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-04-18 14:12:55.428739 +08:00 response status: 200
  DEBUG   2019-04-18 14:12:55.428827 +08:00 body: {"7da2a6946e8d7a82a3c95fa4d484b6bffce5695b": {"state": "ok", "missingChunks": [], "dif": {"objectName": "RxSwift", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.660Z", "debugId": "7542810c-7513-3945-8c18-873292b2f9d4", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203025", "size": 4278084, "sha1": "7da2a6946e8d7a82a3c95fa4d484b6bffce5695b", "uuid": "7542810c-7513-3945-8c18-873292b2f9d4", "cpuName": "x86", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "7542810c751339458c18873292b2f9d4"}, "detail": null}, "87cf18ab6784e2f608bd200dca474fc37da0d9d6": {"state": "ok", "missingChunks": [], "dif": {"objectName": "RxSwift", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.653Z", "debugId": "f0dc06b7-8a25-368a-8680-2a6e6a625868", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203021", "size": 4712301, "sha1": "87cf18ab6784e2f608bd200dca474fc37da0d9d6", "uuid": "f0dc06b7-8a25-368a-8680-2a6e6a625868", "cpuName": "x86_64", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "f0dc06b78a25368a86802a6e6a625868"}, "detail": null}, "53508a3f3094066eb0199ab01084b8a866ee903c": {"state": "ok", "missingChunks": [], "dif": {"objectName": "BleClientManager", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.687Z", "debugId": "4287d4ee-6fa7-33a2-8009-066437e3762f", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203024", "size": 735893, "sha1": "53508a3f3094066eb0199ab01084b8a866ee903c", "uuid": "4287d4ee-6fa7-33a2-8009-066437e3762f", "cpuName": "x86_64", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "4287d4ee6fa733a28009066437e3762f"}, "detail": null}, "11578871e328b36f7d045b4c65a3892757341161": {"state": "ok", "missingChunks": [], "dif": {"objectName": "SwiftyJSON", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.673Z", "debugId": "da6803b7-1ab9-3c5f-abd6-12510110217a", "data": {"type": "dbg", "features": ["debug", "symtab"]}, "id": "30203022", "size": 681088, "sha1": "11578871e328b36f7d045b4c65a3892757341161", "uuid": "da6803b7-1ab9-3c5f-abd6-12510110217a", "cpuName": "x86", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "da6803b71ab93c5fabd612510110217a"}, "detail": null}, "b72c34e30a5b1b267a602044b9a597e30c313755": {"state": "ok", "missingChunks": [], "dif": {"objectName": "RxBluetoothKit", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.681Z", "debugId": "5b206468-783f-3b78-b497-7602eeb703bc", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203023", "size": 1072123, "sha1": "b72c34e30a5b1b267a602044b9a597e30c313755", "uuid": "5b206468-783f-3b78-b497-7602eeb703bc", "cpuName": "x86", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "5b206468783f3b78b4977602eeb703bc"}, "detail": null}, "2c72c98766668a0989308b435d9e3265936167ca": {"state": "ok", "missingChunks": [], "dif": {"objectName": "RxBluetoothKit", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.666Z", "debugId": "62ff8392-a951-3edf-86bf-6c63e176fb38", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203020", "size": 1186707, "sha1": "2c72c98766668a0989308b435d9e3265936167ca", "uuid": "62ff8392-a951-3edf-86bf-6c63e176fb38", "cpuName": "x86_64", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "62ff8392a9513edf86bf6c63e176fb38"}, "detail": null}, "948e6f4f1785077067117b5b6deb0c9731573042": {"state": "ok", "missingChunks": [], "dif": {"objectName": "Charts", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.694Z", "debugId": "1799a3a2-3da7-3cf5-b699-504874dc918a", "data": {"type": "dbg", "features": ["debug", "symtab"]}, "id": "30203026", "size": 6555969, "sha1": "948e6f4f1785077067117b5b6deb0c9731573042", "uuid": "1799a3a2-3da7-3cf5-b699-504874dc918a", "cpuName": "x86", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "1799a3a23da73cf5b699504874dc918a"}, "detail": null}, "5d3cc708a365ab8545dc6e581adaf720cde0ffa2": {"state": "ok", "missingChunks": [], "dif": {"objectName": "Charts", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.701Z", "debugId": "948cf52a-a369-3835-b5a0-caa42cddddf3", "data": {"type": "dbg", "features": ["debug", "symtab"]}, "id": "30203027", "size": 7577844, "sha1": "5d3cc708a365ab8545dc6e581adaf720cde0ffa2", "uuid": "948cf52a-a369-3835-b5a0-caa42cddddf3", "cpuName": "x86_64", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "948cf52aa3693835b5a0caa42cddddf3"}, "detail": null}, "586275fb76e033d57b0077da1c28cb40da0521df": {"state": "ok", "missingChunks": [], "dif": {"objectName": "BleClientManager", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.827Z", "debugId": "0a1d14d5-11e0-3da4-bf76-54aba08ff04e", "data": {"type": "dbg", "features": ["debug", "unwind", "symtab"]}, "id": "30203029", "size": 671952, "sha1": "586275fb76e033d57b0077da1c28cb40da0521df", "uuid": "0a1d14d5-11e0-3da4-bf76-54aba08ff04e", "cpuName": "x86", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "0a1d14d511e03da4bf7654aba08ff04e"}, "detail": null}, "55c4397fbade2c17f2a73de897db6334f19754c3": {"state": "not_found", "missingChunks": ["133f17952b6ff2907c197476dfd8cbadd3f4f2df", "55743350cf1625669daa23d0ed38be2eec758253", "ed374f55a22e54a9961ca98a2c61eabf817d6c42", "da97efacef2ce3c2679bf65ebdcfc30cb82daf74", "8b9014337d6b1e337df9acd4ccfec0d2402d6fb7", "3e90a2f8e6d004a9f257e4660ec63ab16dfe37bc", "8a74b33bff3a9cec9e68d18017a7d5812c0efb46", "bd35e36dc79b67632f382b6858c909955e1d4b4c", "6db44ae4750ff2fc37668c4dda3d657811f947e4", "e32e35916abed2ec1e71ead4654df5596474d16a", "4cebdbf21606fa9c631321ddf3731d21a0157418", "e9ed081fe792b8f91cbaddc86106184d238d5b70"]}, "55dd83c45cbd358e52b9847512708e3b3d6ff708": {"state": "ok", "missingChunks": [], "dif": {"objectName": "SwiftyJSON", "symbolType": "macho", "dateCreated": "2019-04-15T07:55:50.792Z", "debugId": "c49c1679-9223-3931-9180-305147da315b", "data": {"type": "dbg", "features": ["debug", "symtab"]}, "id": "30203028", "size": 758096, "sha1": "55dd83c45cbd358e52b9847512708e3b3d6ff708", "uuid": "c49c1679-9223-3931-9180-305147da315b", "cpuName": "x86_64", "headers": {"Content-Type": "application/x-mach-binary"}, "codeId": "c49c1679922339319180305147da315b"}, "detail": null}}
error: API request failed
  caused by: [55] Failed sending data to the peer

**Comment by jan-auer** [comment]
Is this happening deterministically?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by yordis** [comment]
@jan-auer deterministically for us even with `http.keepalive=false` setup

**Comment by yordis** [comment]
It since that we had some misconfiguration in deployment of Sentry: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-workers-are-sharing-the-same-volume-as-web-if-running-self-hosted-sentry-via-docker


> **Verify workers are sharing the same volume as web (if running self-hosted Sentry via Docker)**
> Sentry does source map calculation in its workers. This means the workers need access to the files uploaded through the front end. Double check that the cron workers and web workers can read/write files from the same disk.

Will see if that fixes the issue.
