### ISSUE TITLE
 bundling failed: Error: The resource `index.js` was not found

### ISSUE THREAD

**Issue by codeshaker** [getsentry/sentry-cli#516]
Hi I am new to React-Native. I tried to create project using commands in sequences

1. expo-cli (to start project)
2. npm start
3. npm run eject (to create android and ios folder)
4. npm run android (to run app natively)

However not at any stage of development i got to see file "RootDirectory/Index.js" and "index.android.js" or "index.ios.js" ??

I have seen other issue but mostly people have worked around these file which i never saw on my repo.

Folder Structure
![image](https://user-images.githubusercontent.com/10116398/56437060-a66d3900-62fb-11e9-9be4-3dcd622051bb.png)

**Comment by kamilogorek** [comment]
Docs reference `app.js` which is in the repo, so it should work just fine - https://docs.sentry.io/platforms/react-native/expo/
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by Aakash359** [comment]
Hi i am trying to create the build from android studio in React native with typescript project but it is giving error like this 
The resource `/Users/mcl-0048/Desktop/Conexus/index.js
<img width="1440" alt="Screenshot 2022-09-28 at 6 22 40 PM" src="https://user-images.githubusercontent.com/54428958/192783326-74a463a6-5e19-4b2c-ac28-034f19b09632.png">
` was not found.
you can refer my screenshot i don't know why it is showing, please let me know the solution of this problem if anyone knows, i am stuck in it
