### ISSUE TITLE
Understanding .env

### ISSUE THREAD

**Issue by am17torres** [getsentry/sentry-cli#520]
From the [docs](https://docs.sentry.io/cli/configuration/) I am lead to believe that the `sentry-cli` should automatically load the contents of the _.env_ file before attempting to execute the cli command

> .env file loading
>
> By default sentry-cli loads .env files. On versions of sentry-cli 1.24 and newer you can disable this by exporting an environment variable SENTRY_LOAD_DOTENV=0.

Now, I'm not sure if I'm doing something wrong, but in my project's root directory I have a _.env_ file. 

In that file, among some other environment variables is the following:

```ini
SENTRY_ORG=my_org
SENTRY_PROJECT=my_project
```

If I try and run `sentry-cli releases list` I get the following error:
```
$ sentry-cli releases list
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
``` 

```
$ sentry-cli --version
sentry-cli 1.41.2
```

Lastly when checking the projects info:
```
$ sentry-cli info
Sentry Server: https://sentry.io
Default Organization: -
Default Project: -

Authentication Info:
  Method: Auth Token
  User: email@gmail.com
  Scopes:
    - org:read
    - project:read
    - project:releases
```

Just to be sure I have the right variables names, I ran this variant of the `info` command which set the project and org as I expected:
```
SENTRY_ORG=my_org SENTRY_PROJECT=my_project sentry-cli info
Sentry Server: https://sentry.io
Default Organization: my_org
Default Project: my_project

Authentication Info:
  Method: Auth Token
  User: email@gmail.com
  Scopes:
    - org:read
    - project:read
    - project:releases
```

Please let me know if I'm misunderstanding how `sentry-cli` loads environment variables from the .env file. 

Thanks ☮️

**Comment by felixjb** [comment]
I'm having the same problem

**Comment by kamilogorek** [comment]
I just verified it (v1.51.1) and couldn't reproduce the issue.

```sh
❯ sentry-cli info
Sentry Server: https://sentry.io
Default Organization: kamil-test
Default Project: test

Authentication Info:
  Method: Auth Token
  User: kamil@sentry.io
  Scopes:
    - event:admin
    - event:read
    - member:read
    - org:read
    - project:read
    - project:releases
    - team:read

~/Projects/sentry/repros/sentry-cli-playground                                                                                                                                                        
❯ echo "SENTRY_ORG=my_org\nSENTRY_PROJECT=my_project" > .env

~/Projects/sentry/repros/sentry-cli-playground                                                                                                                                                        
❯ sentry-cli info
Sentry Server: https://sentry.io
Default Organization: my_org
Default Project: my_project

Authentication Info:
  Method: Auth Token
  User: kamil@sentry.io
  Scopes:
    - event:admin
    - event:read
    - member:read
    - org:read
    - project:read
    - project:releases
    - team:read
```

Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it if there'll be a viable reproduction.
