### ISSUE TITLE
Can't upload source maps (error 400: Release already exists)

### ISSUE THREAD

**Issue by michalkvasnicak** [getsentry/sentry-cli#53]
Recently we've updated our docker image after a while and our releases our not working.

Versions:

* sentry-cli 1.4.0

Using this bash script:

```
#!/usr/bin/env bash

set -x # echo every command

sentry-cli releases list | grep "$GIT_SHA1" &> /dev/null

if [ $? == 0 ]; then
   echo "Release is already created, skipping"
   exit 0
fi

set -e # exit on any command returning non 0 return code

sentry-cli releases new "$GIT_SHA1"
sentry-cli releases files "$GIT_SHA1" upload-sourcemaps ./build/static/js --verbose

```

We get the error during source maps upload:

```
error: http error: Release with version already exists (400)
```

I tried `sentry-cli releases new "$GIT_SHA1" --finalize` but it does not work either.

**Comment by michalkvasnicak** [comment]
Running only this command `sentry-cli releases files "$GIT_SHA1" upload-sourcemaps ./build/static/js --verbose` everything seems to work.

**Comment by mitsuhiko** [comment]
@michalkvasnicak that's most likely becaues the releases list command now truncates the output of the sha hashes. So you will never see the release to exist. We should probably add a command to check if a release exists.

**Comment by michalkvasnicak** [comment]
@mitsuhiko I tried to use commands on my local machine. Precisely these:

```
sentry-cli release new "random-identifier-which-is-unique"
sentry-cli releases files "random-identifier-which-is-unique" upload-sourcemaps ./build/static/js --verbose
```

And I get the 400 again for `upload-sourcemaps`.

For now I am using only `upload-sourcemaps` which creates a release for me.

**Comment by mitsuhiko** [comment]
@michalkvasnicak that is very possible that new release creation fails if a release already exists. We could make a parameter to ignore it.

**Comment by michalkvasnicak** [comment]
In previous version of `sentry-cli` (but I don't know which one) we could upload source maps after release has been created using `release new`. I think that parameter to skip creating a release during file upload should to the trick.

**Comment by mitsuhiko** [comment]
I don't think that ever worked. What did work was that we returnes the release names unabbreviated so your grep did something.

**Comment by michalkvasnicak** [comment]
Weird, we had source maps uploaded to sentry and release created just fine using the commands from first comment. Grep was only used to prevent of creating the same release again (sometimes our build failed to deploy but release was already created during docker build on CI).

Ok so I fixed our failing build by using only `sentry-cli releases files "$GIT_SHA1" upload-sourcemaps ....`

I think that this issue can be closed if this is not a bug but intended behaviour.

**Comment by mitsuhiko** [comment]
Yeah. But that grep used to work and that broke. If you found the sha you did not create and that prevented it from erroring. 

I will leave it open becausr atm there is no way to see if a release exists.

**Comment by mitsuhiko** [comment]
Oddly enough I can't reproduce this locally. I wonder if this is a change on the server API. I will talk back to others to see what might have changed.

**Comment by michalkvasnicak** [comment]
If it could help our sentry server is currently running 8.7.0.

**Comment by mitsuhiko** [comment]
The server for quite some time has permitted to post to already existing releases. I suppose your server is too old and an upgrade will solve this.

**Comment by mitsuhiko** [comment]
Independently you can now run this to check for releases:

```
sentry-cli releases info VERSION -q
```

Exit code will tell you if a release exists.
