### ISSUE TITLE
Repository Names limited to 64 chars

### ISSUE THREAD

**Issue by DanielSchwiperich** [getsentry/sentry-cli#532]
This can be a problem for example in Gitlab projects where the parent groups also used for the repository name. 

<img width="808" alt="Screenshot 2019-05-22 at 16 08 41" src="https://user-images.githubusercontent.com/2045722/58181944-ff3e4180-7cac-11e9-8129-7b2afd26034a.png">

**Comment by Nepoxx** [comment]
`sentry-cli repos list` does report repositories with names longer than 64 characters, but there are no ways to use them with set-commits.

**Comment by Nepoxx** [comment]
This is not an issue with sentry-cli, using curl gives the same error, hence this is an issue with the API.

**Comment by markstory** [comment]
Related to sentry/sentry#13487
