### ISSUE TITLE
owner/repo slug is case sensitive for set-commits command

### ISSUE THREAD

**Issue by bdrelling** [getsentry/sentry-cli#538]
Version: 1.44.1

This is possibly the case for other commands as well, but `set-commits` is the one I was using.

If I try `spothero/spothero-ios`, it fails. If I instead try `spothero/SpotHero-iOS`, it works. GitHub isn't case sensitive here, so Sentry CLI shouldn't be either.

**Comment by kamilogorek** [comment]
Not according to their own documentation, nor w3c standards, so I prefer to leave it as is.

https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors

> The repository you're trying to fetch must exist on GitHub, and the URL is case-sensitive.

https://www.w3.org/TR/WD-html40-970708/htmlweb.html

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. /u
