### ISSUE TITLE
Homebrew release

### ISSUE THREAD

**Issue by soffes** [getsentry/sentry-cli#54]
It would be great if you could simply `brew install sentry-cli`

**Comment by messense** [comment]
https://docs.sentry.io/learn/cli/installation/#installation-via-homebrew

```bash
$ brew install getsentry/tools/sentry-cli
```

**Comment by mitsuhiko** [comment]
We can't go into main homebrew without compiling by default which is silly because that also compiles rust from scratch. So the default install path would take 30 minutes :)

**Comment by soffes** [comment]
Could you do a bottle or something?

Sam
