### ISSUE TITLE
Source map upload (v1.44.2) error: relative URL without a base 

### ISSUE THREAD

**Issue by ramyma** [getsentry/sentry-cli#543]
Since the upgrade to sentry-cli v1.44.2 I have been getting an error (**error: relative URL without a base**) when using `upload-sourcemaps`.

It used to work just fine in v1.44.1 with the argument: `--url-prefix '/home/ubuntu/server'` which maps the source map to the node file on server.

Is there some way to make it work again in v1.44.2 with `--url-prefix '/home/ubuntu/server'` as it's blocking our CI/CD cycle?

**Comment by jan-auer** [comment]
Thanks for reporting, we likely regressed as 1.44.2 included a change in how we validate sourcemap URLs. Will investigate.

**Comment by neilbo** [comment]
This is also blocking our CI/CD

is there another url we can use ttps://sentry.io/get-cli/ to use 1.44.1 instead of the latest?

**Comment by neilbo** [comment]
Workaround for now:

1. create [sentry-install.sh](https://gist.github.com/neilbo/ebfde367443108e4cdef7a63f96f9957) (v1.44.1)
2. Replace install command in your CI/CD steps:

Replace install command
`wget -O - https://sentry.io/get-cli/ | bash`or `curl -sL https://sentry.io/get-cli/ | bash`
with
`sentry-install.sh`

**Comment by jan-auer** [comment]
Fix released as `v1.44.3`

**Comment by ramyma** [comment]
I can confirm that it works with `v1.44.3`

Thanks for the quick fix!

**Comment by irfan798** [comment]
I'm reviving this old issue, but this happens again.

Given `--url-prefix '/home/ubuntu/server'` it fails with  
`- error: failed to process: relative URL without a base`

So absolute paths are not working with version **2.0.4**

**Comment by kamilogorek** [comment]
I cannot reproduce this issue locally. Can you provide a repro-case?

```
…/playgrounds/sentry-cli/ master* ❯ sentry-cli sourcemaps upload dist --url-prefix /home/ubuntu/server --release foo                                                                               13:02:24
> Found 2 release files
> Analyzing 2 sources
> Analyzing completed in 0s
> Rewriting sources
> Rewriting completed in 0.001s
> Adding source map references
> Bundling files for upload...
> Bundling completed in 0.006s
> Optimizing completed in 0s
> Uploading completed in 0.318s
> Uploaded release files to Sentry
> Processing completed in 0.167s
> File upload complete (processing pending on server)
> Organization: kamil-test
> Project: test-1
> Release: foo
> Dist: None

Source Map Upload Report
  Minified Scripts
    /home/ubuntu/server/index.min.js (sourcemap at index.min.js.map)
  Source Maps
    /home/ubuntu/server/index.min.js.map
```

**Comment by rynop** [comment]
> I cannot reproduce this issue locally. Can you provide a repro-case?

That is because you are missing the `--validate` flag.

This happens on v2.9.0 as well
