### ISSUE TITLE
Estou tendo um erro de XML, que aponta para a pasta app do projeto ERROR: Failed to parse XML in G:\Arranjo_de_Onibus\app\src\main\AndroidManifest.xml ParseError at [row,col]:[14,9] Message: expected start or end tag Affected Modules: app

### ISSUE THREAD

**Issue by iruytj** [getsentry/sentry-cli#562]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.teocracia.arranjo_de_onibus"
        minSdkVersion 18
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
}

**Comment by bruno-garcia** [comment]
@iruytj Could you please provide a repro? At a minimum the `AndroidManifest.xml` that failed to be parsed so we can take a look?

Also, is this error message coming from `sentry-cli`?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
