### ISSUE TITLE
Timestamp parsing fails

### ISSUE THREAD

**Issue by tonyt73** [getsentry/sentry-cli#565]
Tried several formats, but always the same result.

When creating a log file for ```send-event``` to use. ```sentry-cli``` fails to parse the timestamp correctly and uses the failback timestamp.

![Annotation 2019-07-18 142729](https://user-images.githubusercontent.com/21229341/61429073-35740680-a968-11e9-9ab6-60b6a9b6b1b0.png)

**Comment by tonyt73** [comment]
![Annotation 2019-07-18 142729](https://user-images.githubusercontent.com/21229341/61429177-956aad00-a968-11e9-9594-725cb12b8fba.png)

**Comment by tonyt73** [comment]
Got it working

**Comment by tonyt73** [comment]
![image](https://user-images.githubusercontent.com/21229341/61433501-cf42b000-a976-11e9-87e4-2fc4c09ce5c6.png)

**Comment by kamilogorek** [comment]
Cannot reproduce it locally. Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it. Cheers!
