### ISSUE TITLE
Can't send codepush (error: EOF while parsing a value at line 1 column 0)

### ISSUE THREAD

**Issue by bgold0** [getsentry/sentry-cli#567]
bryan:mobile-app [bugfix/worksite-bug !]$ sentry-cli react-native appcenter App/App-Mobile ios ./build/ios/codePush --log-level=debug
	INFO    2019-07-18 20:44:31.411470 -04:00 Loaded config from /Users/bryan/Documents/mobile-app/.sentryclirc
	DEBUG   2019-07-18 20:44:31.412806 -04:00 sentry-cli version: 1.46.0, platform: "darwin", architecture: "x86_64"
	INFO    2019-07-18 20:44:31.413037 -04:00 sentry-cli was invoked with the following command line: "sentry-cli" "react-native" "appcenter" "App/App-Mobile" "ios" "./build/ios/codePush" "--log-level=debug"
	> Fetching latest AppCenter deployment info
	DEBUG   2019-07-18 20:44:33.906735 -04:00 error: running update nagger
	INFO    2019-07-18 20:44:33.908172 -04:00 Skipping update nagger update check
	error: EOF while parsing a value at line 1 column 0
	DEBUG   2019-07-18 20:44:33.913959 -04:00 client close; no transport to shut down  (from sentry)

Does anyone know why this would be happening? I've successfully ran `sentry-cli login` and have successfully previous pushed to codePush. So not sure what to do at this point.

**Comment by m-pol** [comment]
May not be your issue, but when I run CodePush with "appcenter codepush release-react ... --output-dir ./build/ios", it generates a folder at ./build/ios/**CodePush**, not ./build/ios/**codePush**. Sentry docs have the lowercase one. May matter or not depending on your filesystem.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-docs/pull/1534
