### ISSUE TITLE
Add set-commits to JS API

### ISSUE THREAD

**Issue by naoisegolden** [getsentry/sentry-cli#568]
Is adding `set-commits` to the JS module in the roadmap? Something along the lines of this would be really useful:

```js
  await cli.releases.new(VERSION);
  await cli.releases.setCommits(VERSION, { auto: true });
  await cli.releases.finalize(VERSION);
```

**Comment by kamilogorek** [comment]
Already implemented: https://github.com/getsentry/sentry-cli/blob/39da2f7f8102f7f9b5ddf83b0de89344d9016789/js/releases/index.js#L61-L82
