### ISSUE TITLE
'Found 0 debug information files' when try to upload pdb files

### ISSUE THREAD

**Issue by danielhe** [getsentry/sentry-cli#571]
Use 'upload-dif' command:
```
C:\Users\admin\Desktop\crash_test>sentry-cli upload-dif -t pdb -t pe .
> Found 0 debug information files
> No debug debug information files found
```
'difutil' command:
```
C:\Users\admin\Desktop\crash_test>sentry-cli difutil check crashtest.pdb
Debug Info File Check
  Type: pdb debug companion
  Contained debug identifiers:
    > b6d7ebfb-b077-4578-b688-ab0744a0b3a6-12 (x86)
  Contained debug information:
    > symtab, debug, unwind
  Usable: yes
```
[crash_test.zip](https://github.com/getsentry/sentry-cli/files/3422140/crash_test.zip)

**Comment by jan-auer** [comment]
Are you trying to upload to on premise Sentry? If so, you will have to update to the latest master to get PDBs to upload. This feature will be included alongside many more improvements in Sentry 10.

**Comment by renatofilho** [comment]
Got the same error. With version 1.47.1 or building from master.

**Comment by jan-auer** [comment]
> or building from master

You will have to use the latest development version of Sentry 10 for this to work. Sentry 9 does not support PDB and PE upload yet.
