### ISSUE TITLE
sentry-cli binaries for 1.47 gone?

### ISSUE THREAD

**Issue by fringd** [getsentry/sentry-cli#575]
https://github.com/getsentry/sentry-cli/releases/download/1.47.0/sentry-cli-Linux-x86_64 used to exist, what happened!?

**Comment by fringd** [comment]
the old releases have 7 artifacts, the latest release now only has 2

**Comment by tonyo** [comment]
:|
Sorry, this happened after some updates to our release tool.
Reuploaded.

**Comment by fringd** [comment]
thanks for the quick fix!
