### ISSUE TITLE
Sourcemaps for server-side files

### ISSUE THREAD

**Issue by activatedgeek** [getsentry/sentry-cli#58]
I have a build setup based in Node where I write code in ES6 and transpile it via Webpack into a set of files and chunks.

For my client side files, I simply upload the sources and sourcemap as follows:

```
sentry-cli releases files $RELEASE_VERSION upload-sourcemaps build/client --url-prefix "~/$RELEASE_VERSION"
```
 which works.

But I am unable to understand how to map sources with their maps on the Server-side files.

**Comment by mitsuhiko** [comment]
This is not currently supported by Sentry server. See https://github.com/getsentry/sentry/issues/2632
