### ISSUE TITLE
Loading .env contents, debug shows that /home/dev/.sentryclirc loaded

### ISSUE THREAD

**Issue by gander** [getsentry/sentry-cli#582]
The data is loaded from `.env` where I set:
```ini
SENTRY_LOG_LEVEL=debug
```
while the logs show:
```
  INFO    2019-08-16 21:43:16.691401016 +00:00 Loaded config from /home/dev/.sentryclirc
```
File `/home/dev/.sentryclirc` does not exist. The location of the `.env` file should be on this line.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/677
Unfortunately we won't log an info about `.env` being logged, as it'd skip `--log-level` setup, due to loading order.
