### ISSUE TITLE
npm install --save-dev @sentry/webpack-plugin fails, FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.47.1/sentry-cli-Windows-x86_64.exe failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by TDola** [getsentry/sentry-cli#585]
```
npm install --save-dev @sentry/webpack-plugin

> @sentry/cli@1.47.1 install C:\workspace\github\appname\node_modules\@sentry\cli
> node scripts/install.js

FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.47.1/sentry-cli-Windows-x86_64.exe failed, reason: self signed certificate in certificate chain

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.47.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.47.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Downloading the exe manually works, but if I run it nothing happens.

What can I do?

**Comment by tonyo** [comment]
> reason: self signed certificate in certificate chain

Doesn't look like a certificate issue, cannot reproduce on Mac or Linux. Do you have any kind of proxy set up in your environment? Also, please check this issue, perhaps it has some answers for you: https://github.com/npm/npm/issues/7519

> Downloading the exe manually works, but if I run it nothing happens.

It's meant to be run behind the scenes as part of @sentry/webpack-plugin operations. It's also a command-line tool that just prints the help message and exits if no arguments are provided.

**Comment by TDola** [comment]
Yep fortinet corporate firewall messes up everything it touches.  I have the cer file if there is a place I can put it to make npm happy.

**Comment by nicky132** [comment]
> Yep fortinet corporate firewall messes up everything it touches. I have the cer file if there is a place I can put it to make npm happy.
> 
> Got it solved, I got the sentry CDN excluded by the firewall. Good enough I think. Thanks for the help.

i gotta exactly what you problem,Node@v16.16.0, Yarn@1.22.19,when i yarn add @sentry/webpack-plugin --dev,bingo,the error message show up, so how did you fix it up if you wanna to tell the detail?

**Comment by nicky132** [comment]
>

> He already said that in previous comment :)
> 
> > I got the sentry CDN excluded by the firewall.
> 
> You can also use github mirror if that's allowed in your env:
> 
> ```
> SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
> ```

![1668070251459_04719D8F-3CF2-44d4-84CB-728235ED9E7E](https://user-images.githubusercontent.com/34881461/201044462-cda7f790-c6b2-4037-b089-7d1549df3b41.png)
i had already installed it with the way he said, but i still gotta that error

**Comment by nicky132** [comment]
how can i do that yarn add @sentry/webpack-plugin --dev successfuly :(

**Comment by kamilogorek** [comment]
Read your screenshot again and read what I wrote above. You have wrong `SENTRYCLI_CDNURL`.

**Comment by nicky132** [comment]
> Read your screenshot again and read what I wrote above. You have wrong `SENTRYCLI_CDNURL`.

ok,i wrote the sentrycli_cdnurl in .npmrc,success,but i found other problem :(
![1668071883550_B7B4A4AA-ABAF-465f-9670-E140DDE0205C](https://user-images.githubusercontent.com/34881461/201050540-3c777e00-3b6e-431e-a902-941db72841af.png)

**Comment by kamilogorek** [comment]
Either

```js
const SentryPlugin = require('@sentry/webpack-plugin');
```

or

```js
import { default as SentryPlugin } from '@sentry/webpack-plugin';
```

Sorry, but this is not JS support channel, and this is language, not a package issue.

**Comment by nicky132** [comment]
> 

yes！！！，it worked :)

**Comment by nicky132** [comment]
why i got this wrong again,
which did't happen on centos system with the very same .npmrc and node version and yarn version?
![1669101095165_0DD27898-3651-4c17-8587-45E00C70FCAB](https://user-images.githubusercontent.com/34881461/203249249-e8f1f02c-c322-45d1-bf14-1411fab2b751.png)
![1669101122010_55F9A15B-C7F2-426b-98DE-AE3B8D04210B](https://user-images.githubusercontent.com/34881461/203249274-ec8b337e-24f8-49f0-bc86-4ab1e52fa964.png)

**Comment by nicky132** [comment]
> Why i got this wrong again, which did't happen on centos system with the very same .npmrc and node version and yarn version. Btw,node 16.17.0,yarn 1.22.19. I want download all of this dependency one time,by yarn with no error How can i get that？ ![1669101095165_0DD27898-3651-4c17-8587-45E00C70FCAB](https://user-images.githubusercontent.com/34881461/203249249-e8f1f02c-c322-45d1-bf14-1411fab2b751.png) ![1669101122010_55F9A15B-C7F2-426b-98DE-AE3B8D04210B](https://user-images.githubusercontent.com/34881461/203249274-ec8b337e-24f8-49f0-bc86-4ab1e52fa964.png)

Problem solved,
Beacause , i saw this,https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170,and installed it already,then,successed
