### ISSUE TITLE
upload-sourcemaps dosn't find files in a Symbolic linked dir

### ISSUE THREAD

**Issue by puggan** [getsentry/sentry-cli#588]
in my project root, all published javascript end up in the folder public/build/

in the build folder there is a link src, pointing to ../../resources/assets/

in the build folder there is a map-file app.js.map

in the map file it have many sources, one is 'src/ts/footer.ts'.

The file public/build/src/ts/footer.ts exists.

When running `sentry-cli releases <org,project> files <release> upload-sourcemaps --ext js --ext ts --ext map --validate --rewrite <path>/public/build/`

I get the error:
```
  Source Maps
    ~/app.js.map
      - warning: missing sourcecode (src/ts/footer.ts)
```
(and many more)

And under Scripts there is neither js or ts files from the src folder.

**Comment by kamilogorek** [comment]
Just verified it locally and everything seems to work just fine now.

![image](https://user-images.githubusercontent.com/1523305/76215154-657d5c00-620e-11ea-998d-1966b79da9fd.png)
