### ISSUE TITLE
sentry use sourcemaps in my server instead of the uploaded sourcemaps in Sentry Release Artifacts

### ISSUE THREAD

**Issue by chj-damon** [getsentry/sentry-cli#590]
![image](https://user-images.githubusercontent.com/4902684/64107976-44930480-cdae-11e9-9849-cc4582c557df.png)
![image](https://user-images.githubusercontent.com/4902684/64108005-5379b700-cdae-11e9-98a6-f4de77b90682.png)

As you can see, I've uploaded all js files and js.map files to sentry. But I'm confused why the issue still looks for sourcemaps in my server instead of sentry itself. Because in production mode, webpack recommends that sourcemaps should not be hosted in the server.
Is there something I need to do if I want the issue to look sourcemaps from the sentry itself?

**Comment by chj-damon** [comment]
Also, I've checked the `sourceMappingURL` in js files and it matches the name of sourcemap in the artifacts.

**Comment by chj-damon** [comment]
I solved this problem because it turns out that some configuration was wrong in the docker environment.

**Comment by Edwardsj** [comment]
Could you leave more message about this? I think i got the same problem.

**Comment by chj-damon** [comment]
@Edwardsj https://forum.sentry.io/t/offline-sourcemaps-not-used/548/5
