### ISSUE TITLE
Docker image shows a warning

### ISSUE THREAD

**Issue by shpikat** [getsentry/sentry-cli#600]
I can see a warning still shown for version 1.47.1, even though it was planned for removal after 1.37:
https://github.com/getsentry/sentry-cli/blob/daf7abd03b6db30799889e1652a65c49a85b9033/docker-entrypoint.sh#L13

Should I go with the PR to remove that, or is it still necessary?

**Comment by tonyo** [comment]
If you see the warning, then you're using the legacy (non-documented) way of starting the container :) 
The recommended way is provided here: https://github.com/getsentry/sentry-cli#docker (i.e., sentry-cli arguments are passed directly to the entrypoint).
The idea was to remove both the warning and the whole custom entrypoint at some point, but I'm not that certain about this anymore. We'll consider just removing the warning and leaving the rest as-is.

**Comment by shpikat** [comment]
Oh, you're right, I'm running it as part of my GitLab CI -- I didn't know it's a legacy way :) I understand it's different from the documented way of starting the container, but that's the GitLab convenient way for describing the pipeline stage: use the image and define a script to run inside it. Is it one of the reasons you want to leave the rest as-is?

**Comment by tonyo** [comment]
GitLab assumes that it can run "sh" inside containers, and one of the solutions to this was to provide an explicit entrypoint, as mentioned here: https://github.com/getsentry/sentry-cli/issues/366#issuecomment-417615179 
But yeah, to avoid any further confusion we might just leave it as it is now.

**Comment by tonyo** [comment]
Removed the warning here: https://github.com/getsentry/sentry-cli/commit/33eab06bf4522a01b529e0013b6439abae592cdf
Will be gone in the next version.
Thanks for reminding @shpikat !

**Comment by shpikat** [comment]
Got it! Thanks, Anton, for the explanation and quick actions 👍
