### ISSUE TITLE
sentry-cli: command not found in GitLab CI

### ISSUE THREAD

**Issue by beeing** [getsentry/sentry-cli#614]
Hi, I've followed the steps in this [article](https://medium.com/angular-athens/make-angulars-source-code-available-to-sentry-with-gitlab-ci-b3020bd60ae6) which uses GitLab CI and the docker image of sentry-cli.

However, I encountered an error below:
```
$ export SENTRY_URL=$SENTRY_BASE_URL
$ export SENTRY_AUTH_TOKEN=$SENTRY_BASE_TOKEN
$ export SENTRY_ORG=$SENTRY_BASE_ORGANIZATION
$ export SENTRY_PROJECT=$SENTRY_BASE_PROJECT
$ sentry-cli releases new $CI_COMMIT_SHA

bash: line 108: sentry-cli: command not found
ERROR: Job failed: exit status 1
```

**Comment by tonyo** [comment]
Make sure that your commands are run inside the container, and that your $PATH is set to something sane.
Also, perhaps this thread will help you: https://github.com/getsentry/sentry-cli/issues/366#issuecomment-417615179
