### ISSUE TITLE
Getting "Stream error in the HTTP/2 framing layer" when uploading symbols

### ISSUE THREAD

**Issue by phillipCouto** [getsentry/sentry-cli#615]
Here is the snippet from the console when running the `sentry-symbols.js` file from the `sentry-wizard` utility.

```
  INFO    2019-10-31 17:25:51.340551 -04:00 Loaded config from /Users/pcouto/.sentryclirc
  INFO    2019-10-31 17:25:51.341195 -04:00 sentry-cli was invoked with the following command line: "/Users/pcouto/Projects/node/espace-app/node_modules/@sentry/cli/sentry-cli" "upload-dif" "-t" "breakpad" ".electron-symbols/electron-v6.1.2-win32-ia32-symbols.zip"
> Found 3 debug information files
> Prepared debug information files for upload
  INFO    2019-10-31 17:25:54.149206 -04:00 using 'gzip' compression for chunk upload
error: API request failed
  caused by: [92] Stream error in the HTTP/2 framing layer
* Closing connection 0
```

This is a on-premise installation running version 9.1.2. Let me know what other information I can provide to help resolve this issue.

**Comment by nbolender** [comment]
@phillipCouto Any luck with this?

**Comment by sertony** [comment]
Try upgrading `curl`? It seems to help.

**Comment by sertony** [comment]
It's rather connected to macOS Catalina, since we don't have this issue on Mojave. 
What OS do you use?

**Comment by phillipCouto** [comment]
I am on macOS Catalina, `10.15.1 (19B88)` to be exact. 

I was going to try running the source code directly on my machine and debug it from that. Just haven't had a chance yet as I moved off to other tasks.

**Comment by nbolender** [comment]
@sertony I'm suspecting as much as well, since it occurred after upgrading to Catalina (10.15.1). The system curl version is `curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2`.

I am not sure how to upgrade curl and get sentry-cli to use it without replacing the system version. Any thoughts?

For now, I have disabled http2 on my sentry server.

**Comment by phillipCouto** [comment]
@nbolender I was trying to do the same but since Sentry is behind a reverse proxy I was having a hard time disabling HTTP2 only for sentry. 

I have more evidence that it is a macOS issue. I have a CI job that runs in a docker container and it is uploading fine. Just curious couldn't a rust HTTP client that supports http2 be used inside of linking to curl?

**Comment by nbolender** [comment]
@sertony Homebrew specifically does not replace the system version at `/usr/bin/curl` since many things may rely on it, so I'm not sure that sentry-cli will use the homebrew version.

**Comment by sertony** [comment]
@nbolender yep, you are right. That's why I added `export PATH="/usr/local/opt/curl/bin:$PATH"` to my bash_profile, but apparently it didn't help.

**Comment by phillipCouto** [comment]
@sertony you need to recompile the cli to link to your custom location for the curl library not the executable.

**Comment by ChrisBountalis** [comment]
I also met this issue, while using the latest gradle sentry android plugin(io.sentry.android.gradle 1.7.28). Any workarounds for this?

**Comment by jan-auer** [comment]
Could you try again with `sentry-cli v 1.51.1`? We started to link libcurl statically.
cc @kamilogorek

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by notjosh** [comment]
fwiw, for anyone stumbling on this later, updating (from `1.49.0` to `1.52.1` in my case) fixed the issue on Catalina

**Comment by spidey** [comment]
I'm not using the `sentry-cli` but rather sending requests directly through `curl` on Mac, and also getting a similar error: `curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)`.

Workaround was to force HTTP/1.1 on `curl` with option `--http1.1`. Not an option on `sentry-cli` I imagine.
