### ISSUE TITLE
using docker image in azure pipeline

### ISSUE THREAD

**Issue by x20mar** [getsentry/sentry-cli#621]
Sorry, I may seem a bit of an idiot here but I've been trying to figure this out for half a day now with no luck.

I have a typescript application which I want to publish the source maps to sentry as a pipeline step but I can't figure out how to use the docker image for that.

I don't want to install sentry-CLI NPM package into the application as I feel that will just bloat the app.

Does anyone have suggestions on how to this?

Many Thanks

**Comment by kamilogorek** [comment]
I'm not sure exactly what you want to achieve. Using docker sounds like an overkill here. You can use `getsentry/sentry-cli` docker container, sure, but it'd also require mapping filesystem to be able to read all the bundles.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers
