### ISSUE TITLE
Source code was not found 

### ISSUE THREAD

**Issue by bruscantini** [getsentry/sentry-cli#622]
I've been trying for days to get the sourcemaps in my production releases to get properly associated to sentry issues, with no luck :(
(see https://sentry.io/organizations/ember-fund-llc/issues/1310819568/?project=1324787&query=is%3Aunresolved+release%3Acom.emberfund.ember-2.3-codepush%3Av29&statsPeriod=14d). 

The sourcemaps for development builds appear to work fine.
(see https://sentry.io/organizations/ember-fund-llc/issues/1328370127/?project=1324787&query=is%3Aunresolved&statsPeriod=14d)

I followed the instructions outlined here: https://docs.sentry.io/clients/react-native/codepush/

Package.json:
`"@sentry/react-native": "^1.0.9",
"react-native-code-push": "^5.7.0"`

For dev builds I run:
`appcenter codepush release-react --app APPNAME \
--output-dir ./build/android/Staging/ \
--private-key-path ~/app/privateKey.pem \
--mandatory \
--description "JS version 1.2.3" \
--deployment-name Staging; \
export SENTRY_PROPERTIES=./android/sentry.properties; \
./node_modules/@sentry/cli/sentry-cli react-native appcenter \
APPNAME android ./build/android/Staging/CodePush \
--deployment Staging`

For prod builds, I just change the deployment-name:
`appcenter codepush release-react --app APPNAME \
--output-dir ./build/android/Production/ \
--private-key-path ~/app/privateKey.pem \
--mandatory \
--description "JS version 1.2.3" \
--deployment-name Production; \
export SENTRY_PROPERTIES=./android/sentry.properties; \
./node_modules/@sentry/cli/sentry-cli react-native appcenter \
APPNAME android ./build/android/Production/CodePush \
--deployment Production`

I feel I've tried all the solutions proposed on here for this issue. Our Sentry account is useless if this doesn't work, so we're looking to cancel if we have no other options. Please, any help here ?! Would love to make this work :) Let me know if you need more info!

**Comment by lobsterkatie** [comment]
A little background information, in case others come across this issue.

In broad strokes, what our system does when processing each frame of a JS event is:

1) Notice the filename (the full URL of the bundle file) on the frame, and the `dist` and `release` tags on the event

2) Look at the associated `Release` object from your org, and check its uploaded artifacts to see if there's one whose name matches* the frame's filename and whose `Distribution` value matches the event's `dist` tag

    \* "matches" can mean either exact match or match with `~` substituted in for the scheme and hostname 

    2a. If it can't find a match, attempt to download the file from its URL. If it can't download it, error out.

3) If it's found a matching bundle file, either in our database or by downloading it, check for a `sourcemap` or an `x-sourcemap` header, or a `sourceMappingURL` comment at the bottom of the file, and take note of the URL there

4) Repeat steps 2 and 2a, but for the source map this time, using the URL found in the previous step

5) Assuming it now has all of the files it needs, do the demangling.

Now, @bruscantini, in your case...

If you look at your two events, dev and prod, you'll see that in both cases the file throwing the error is `app:///index.android.bundle`, and in both cases the event has a `dist` value. Moving over to the corresponding release artifacts, you can see that though the names are a match (`app://` in the frame filename becomes `~` in your artifact names), in both cases the artifacts have null `Distribution` values. This makes step 2 fail. The fact that `app:///index.android.bundle` obviously isn't a real URL makes step 2a fail. And so then you land exactly where you did with your prod event: `Source code was not found: app:///index.android.bundle`.

(But then what about your dev event? Seems like the `dist`/`Distribution` mismatch should break that sourcemapping process, too... and it would, if we weren't [symbolicating](https://github.com/getsentry/sentry-react-native/blob/9369c4fa3ef7a2bcbc800d6dc3f781100f2c823d/src/js/sdk.ts#L46) _on the device itself_, before the event is sent, using [RN's own tool](https://github.com/getsentry/sentry-react-native/blob/9369c4fa3ef7a2bcbc800d6dc3f781100f2c823d/src/js/integrations/debugsymbolicator.ts#L59-L60).)

In any case, given that you [can't currently specify a `dist` value for your artifacts](https://github.com/getsentry/sentry-cli/blob/4d3fce12e12ce4466a53022ae746631ff8d0b7c0/src/commands/react_native_appcenter.rs#L146), the solution here is to strip the value from your events before they're sent, using `beforeSend`:

```
Sentry.init({
  dsn: 'YOUR DSN',
  beforeSend: (event, hint) => {
    delete event.dist;
    return event;
  },
});
```
