### ISSUE TITLE
The deployment Production does not exist. (cannot push release)

### ISSUE THREAD

**Issue by felixchan** [getsentry/sentry-cli#626]
In the past, (like, yesterday), I was able to push to Sentry using this command:

`sentry-cli react-native appcenter user.com/user-ios ios ./build/codePush --deployment Production`

Now, when I run the same command, I'm not able to push it. 

```
$ pushsentry
> Fetching latest AppCenter deployment info
error: Failed to load AppCenter deployment history
  caused by: The deployment Production does not exist.
```

AppCenter receives my push.
I've updated to 1.49.0, but bug persists.

**Comment by kamilogorek** [comment]
It should be `CodePush`, docs fix pending https://github.com/getsentry/sentry-docs/pull/1534
