### ISSUE TITLE
Asks me for org, then yells at me when I give it an org

### ISSUE THREAD

**Issue by shayneo** [getsentry/sentry-cli#631]
I run
`sentry-cli releases list`

and get the following error message
`error: An organization slug is required (provide with --org)`

Then I run `sentry-cli releases list --org myorgname` and get
`error: Found argument '--org' which wasn't expected, or isn't valid in this context`

**Comment by kamilogorek** [comment]
It has to be written as `sentry-cli releases --org myorgname list`

There's an issue to track progress on changing this behavior https://github.com/getsentry/sentry-cli/issues/179

**Comment by nolman** [comment]
I just ran into this over a year later and had to google this solution - the existing messages are very unclear and confusing, this should likely be improved $0.02
