### ISSUE TITLE
npm install v1.49 fails on Windows x86-64

### ISSUE THREAD

**Issue by mariot** [getsentry/sentry-cli#635]
Steps to reproduce

    mkdir sentrycli
    cd sentrycli
    npm init
    npm install @sentry/cli@1.49 --save

Error

$ npm install @sentry/cli@1.49 --save

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.49.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.49.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Installing v1.48 works fine.
I stumbled upon this problem while installing expo-sentry, which requires it.

Tested on Windows 10 x84-64.

**Comment by kamilogorek** [comment]
I tried to reproduce the issue with no luck. Let me know if it's still relevant.

![image](https://user-images.githubusercontent.com/1523305/73750828-29159680-475e-11ea-822f-fb1e3bf0b351.png)

**Comment by schumannd** [comment]
same issue here on osx. It happened after integrating expo-av and unimodules. Still debugging...
