### ISSUE TITLE
Crashes with "No such file or directory" when automatically uploading sourcemaps

### ISSUE THREAD

**Issue by martrik** [getsentry/sentry-cli#643]
I'm trying to make iOS React Native export sourcemaps so that Sentry CLI picks them up and uploads them automatically. 

This is my `Bundle React Native code and images` script:
```sh
#!/bin/sh
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY="node"

# Addition to the script
export EXTRA_PACKAGER_ARGS="--sourcemap-output sourcemap.ios.js"

../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh --log-level=de
```

However, the script fails with the error: `error: No such file or directory (os error 2)`. I've added the `--log-level=debug` flag but it doesn't provide any additional information about the crash. 

I've tried all proposed solutions from https://github.com/getsentry/sentry-react-native/issues/484 but none work.

I can reproduce this issue in my local machine (Node 8 installed via `nvm`) and in GitHub Actions (Node 8).

**Comment by kamilogorek** [comment]
Can you provide some kind of repro case to showcase this behavior?

**Comment by martrik** [comment]
I fixed the issue by passing a complete path as the sourcemap output argument:
```sh
DEST=$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DEST/main.bundle.map.js";
```

**Comment by khuongphp** [comment]
related [#2067](https://github.com/getsentry/sentry-react-native/issues/2067) and [#484](https://github.com/getsentry/sentry-react-native/issues/2067) (sentry-react-native package)

version:
"react-native": "0.70.5",
"@sentry/react-native": "^4.9.0",

i found the problem when i run this command:
`
npx @sentry/wizard -i reactNative -p ios android
`
this command update the shell of "Bundle React Native code and images", like this:
```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```
but it should be:
```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

../node_modules/@sentry/cli/bin/sentry-cli react-native xcode
/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```
I can build my project after change this.

**Comment by benoitvallon** [comment]
For those who are not using the default `node_modules` install like in a monorepo for exemple the build script should be almost like @khuongphp said except that the build script needs to be passed to sentry-cli
```
export SENTRY_PROPERTIES=../sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

WITH_ENVIRONMENT="../../../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../../../node_modules/react-native/scripts/react-native-xcode.sh"

../../../node_modules/@sentry/cli/bin/sentry-cli react-native xcode "$REACT_NATIVE_XCODE"
/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

**Comment by SamuelScheit** [comment]
I had the same problem. It was caused by spaces in the name of the scheme in xcode. After removing it everything worked
