### ISSUE TITLE
Unable to use --ext `js.map`

### ISSUE THREAD

**Issue by vitalets** [getsentry/sentry-cli#644]
I'm trying to keep only `js` and `js.map` file extensions while uploading source-maps (exclude `css.map`). And getting error:
```
npx sentry-cli releases files "test-1.0" upload-sourcemaps "./dist/" --no-rewrite --url-prefix="~/s3/app" --ext js --ext js.map
error: invalid definition (format is type:glob, e.g., html:*.html)
```
when I remove `--ext js.map` everything works.
I've tried to escape dot in `js.map` and played with quotes `--ext='js.map'` but no luck.
How can I do it?
```
sentry-cli 1.49.0
```

**Comment by kamilogorek** [comment]
Extensions are always defined with a single string prefixed with a dot. In order to include one, but ignore the rest, use `--ignore`, eg.

```terminal
sentry-cli releases files test upload-sourcemaps ./foo --ext .js --ext .map --ignore "*css.map"
```

Cheers!

**Comment by vitalets** [comment]
> Extensions are always defined with a single string prefixed with a dot.

Ок, thanks! It would be great to mention in [cli docs](https://docs.sentry.io/cli/releases/#sentry-cli-sourcemaps).
