### ISSUE TITLE
project not found uploading sourcemaps

### ISSUE THREAD

**Issue by fvhockney** [getsentry/sentry-cli#655]
attempting to upload sourcemaps via the cli, It fails with `error: project not found`. May be related to #649 

# What I have done
Run with config and ENV variables set
confirmed that I can login and view release info with the cli
confirmed I can create releases with the cli
confirmed that I can upload a single file with the cli to the release in question
confirmed that it still doesn't work with a full-access auth token

# Helpful(?) debug info
Every thing seems to run alright until it tries to upload a chunk and changes (for whatever reason) to appending the port to the base url. (No idea if that has anything to do with it). It then returns a 302 and reports
```
...
DEBUG <Date-Time-Info> error: running update nagger
error: project not found
DEBUG <Date-Time-Info> client close; no transport to shut down (from sentry)
```

Incidentally, I came to discover that this is a problem within the CLI/API only because I was having problems uploading the sourcemaps via the webpack-plugin and saw that it is a wrapper for the cli.

**Comment by fvhockney** [comment]
After a bit more investigation, I am fairly sure that this issue is caused by the (recent) 302 check implemented. I think that when the port number is (automatically) appended to the base path, this causes a 302 (I think) which would fail with this message.

**Comment by fvhockney** [comment]
for what it's worth, downgrading to npms @sentry/cli@1.49.0 removes the problem, so this gives some credence to the general manner that 301 and 302's are now handled.

**Comment by kamilogorek** [comment]
@fvhockney can you provide a whole debug log (can be sanitized) please?

**Comment by fvhockney** [comment]
yup. sure will. I have to make sure it actually uploads the artifacts with 1.49.0 (didn't have any .map files last night). I'll include logs for both versions.

**Comment by fvhockney** [comment]
Logs uploaded as text files. I can confirm that the 1.49.0 version doesn't return any errors, but it also doesn't upload the artifacts (at least not where I can see them in the ui) ... Also, this is a self hosted (docker) instance.

[upload_1_49_0.txt](https://github.com/getsentry/sentry-cli/files/4190814/upload_1_49_0.txt)
[upload_1_50_0.txt](https://github.com/getsentry/sentry-cli/files/4190815/upload_1_50_0.txt)

**Comment by kamilogorek** [comment]
@fvhockney can you first try to configure your endpoint to include the port?

Go to Menu > Admin and change this setting:

![image](https://user-images.githubusercontent.com/1523305/74668342-4eb28f00-51a5-11ea-8511-0100932100b1.png)


Once this is set, the upload endpoint will include the port.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
