### ISSUE TITLE
Should support SENTRY_DSN for no-hassle setup

### ISSUE THREAD

**Issue by Nowaker** [getsentry/sentry-cli#664]
`sentry-cli` uses different environment variable names than the client. Or requires a manually written config (which is not convenient for disposable CI environments). Moreover, user tokens `sentry-cli` uses are not suitable for CI environments as they're bound to the user and not the project. We don't want a CI server to "impersonate" one of the developers when adding a release. We don't want a CI server to stop tracking releases when a developer's account is disabled. **Just let us use `SENTRY_DSN`, like we use in clients.**

Organization name and project name should be inferred from the server side based on successful authentication and as such, CLI doesn't need to know what the org and project are.

**Comment by kamilogorek** [comment]
It's not possible to just use DSN, as it's not able to authenticate the user/machine. We're working on org-wide tokens. Closing this in favor or https://github.com/getsentry/sentry-cli/issues/581
