### ISSUE TITLE
sentry release command not respecting -p flag?

### ISSUE THREAD

**Issue by alexeightsix** [getsentry/sentry-cli#669]
When using the command I get this output:

Create new release...
  INFO    2020-03-02 17:06:50.737738472 +00:00 Loaded config from /root/.sentryclirc
  INFO    2020-03-02 17:06:50.738024361 +00:00 sentry-cli was invoked with the following command line: "/usr/local/lib/node_modules/@sentry/cli/sentry-cli" "releases" "new" "-p" "axxf-xx-xx-app" "1583168359"

  INFO    2020-03-02 17:06:52.115321494 +00:00 Resolving HEAD (xxx/af-xxx-app@HEAD)
  INFO    2020-03-02 17:06:52.116153451 +00:00 Resolving HEAD (xxx/aow-xxx-xxx-app@HEAD)
  INFO    2020-03-02 17:06:52.117234340 +00:00 Resolving HEAD (xxx/aow-xxx-xx-app@HEAD)
  INFO    2020-03-02 17:06:52.117908059 +00:00 Resolving HEAD (xxx/aow-xxx-xxx@HEAD)

It outputs ALL my sentry projects instead of just the one project i specified in the -p param? what am i doing wrong?

I also have the SENTRY_PROJECT= ENV variable set on the host machine.

**Comment by kamilogorek** [comment]
I cannot reproduce this behavior locally. Can you paste whole debug log?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers
