### ISSUE TITLE
sentry-cli-binary installation fails with yarn

### ISSUE THREAD

**Issue by ishitatsuyuki** [getsentry/sentry-cli#67]
"bin" referencing nonexistent binary won't work in yarn, even if you download it at preinstall (since yarn does everything after writing files). Yarn refuses to symlink nonexistent files.

Instead, we should write a shim script to execute it.

**Comment by mitsuhiko** [comment]
I wonder if we can just ship a dummy file to work around this.

**Comment by ishitatsuyuki** [comment]
@mitsuhiko I don't like to workaround if there's a viable solution.

**Comment by mitsuhiko** [comment]
@ishitatsuyuki I am just not sure what the viable solution is.

**Comment by ishitatsuyuki** [comment]
A shim script will do that. That is also used by npm on Windows to create instead of symlinks, although the context is a little different here.

**Comment by mitsuhiko** [comment]
@ishitatsuyuki if by "shim script" you mean a bash/bat script that will forward arguments I really do not like this for a variety of reasons. In particular on windows it will break a bunch of stuff that tries to shell out without handling `PATHEXT` and it causes a lot more complexity (for instance because bat has problems forwarding all arguments) and requires platform specific special handling.

**Comment by ishitatsuyuki** [comment]
Remember, we're talking Java*Script* :P

**Comment by mitsuhiko** [comment]
This is not a JavaScript project.

**Comment by ishitatsuyuki** [comment]
sentry-cli-binary is.

**Comment by mitsuhiko** [comment]
The only thing that is JavaScript in that context is the post install script.

**Comment by ishitatsuyuki** [comment]
... and we can add a shim to proxy the executable too, as long as it's for NPM.

**Comment by mitsuhiko** [comment]
I am not happy with the downsides a proxy executable brings and will look for alternatives.

**Comment by ishitatsuyuki** [comment]
... you know, this is the [industry standard](https://github.com/Medium/phantomjs/blob/master/bin/phantomjs). Node itself is quite fast and should pose no visible overhead on doing such things.

**Comment by mitsuhiko** [comment]
As I said I am not confident with maintaining a wrapper and will look at alternative solutions. Your concerns have been heard however and I will make sure to fix this with the next release in one way or another.

**Comment by ishitatsuyuki** [comment]
I believe that wrapper is the best way to deal with this problem, and there should be no maintenance needed (the script I mentioned has been working for 3 years without changes). Other hacks may expire faster, since hacks are relying on internal details of the package manager.

**Comment by mitsuhiko** [comment]
I filed an issue against yarn in any case: https://github.com/yarnpkg/yarn/issues/3421 — this does not just affect us.

**Comment by ishitatsuyuki** [comment]
Yes only you - vscode-ripgrep doesn't have a bin entry at all. Please also note that a patch in yarn will take a few years to propogate to LTS distros.

**Comment by mitsuhiko** [comment]
A dummy script was added which works around this yarn bug.

**Comment by ishitatsuyuki** [comment]
Although I don't like such hacky approach, this looks fine. Would you mind publishing a new release to npm?

**Comment by mitsuhiko** [comment]
1.10.0 is up on npm with this in.
