### ISSUE TITLE
Cannot run "releases files" with release name starting with "list..."

### ISSUE THREAD

**Issue by ValentinH** [getsentry/sentry-cli#686]
I've noticed that when I run the following command:

```sh
sentry-cli releases files VERSION upload-sourcemaps /path/to/sourcemaps
```

with `VERSION=listing-form@123`,

I get the following error:

```
error: The subcommand 'listing@123' wasn't recognized
	Did you mean 'list'
```

I guess that this is because my VERSION string starts with "list".

**Comment by kamilogorek** [comment]
Thanks! Can confirm that it's an issue with parsing args by `clap`. We'll get it fixed soon.

**Comment by kamilogorek** [comment]
Reported directly to `clap-rs` repo: https://github.com/clap-rs/clap/issues/1750

**Comment by kamilogorek** [comment]
Related https://github.com/clap-rs/clap/issues/2001

**Comment by ValentinH** [comment]
This is this relevant.

**Comment by kamilogorek** [comment]
I have this update scheduled for this quarter, so fingers crossed it will be fixed soon :)

**Comment by kamilogorek** [comment]
@ValentinH I can confirm it's fixed in Clap v3 and will be part of our v2 release coming soon™️

![image](https://user-images.githubusercontent.com/1523305/158160651-80eea15b-c412-4182-b17e-38637bd691fa.png)

**Comment by kamilogorek** [comment]
`2.0.0-beta.0` has been released, give it a try and let me know if your issue has been resolved 🎉
