### ISSUE TITLE
Windows 10 C++ Store App - how to upload PDB files?

### ISSUE THREAD

**Issue by sseyod** [getsentry/sentry-cli#691]
Thanks to your help, I now have my Windows 10 Store C++19 app built with Sentry Native linked-in, and I am able to send basic information to sentry.io., where I can use the website to verify that the Sentry connection is basically working. Thank you!

However, I cannot figure-out how to upload the app's pdb files. Can anybody advise?

Note that if I can't complete this step, then the sentry native API will remain unusable for crash reporting, even though we now have gone through all the effort to get it building and running...

I can't see how to do this via a web browser (I'd have thought I could just drag-in the PDB file, but can't see how to do that); so am trying sentry-cli but the documentation and error messages are not clear to me :)

I've tried a couple of different command lines:

```
sentry-cli-Windows-x86_64.exe --log-level=info upload-dif .
> Found 0 debug information files
> No debug information files found
> Server does not support reprocessing.

entry-cli-Windows-x86_64.exe --log-level=info upload-dif -t pdb .
  WARN    2020-03-20 08:42:07.533553100 +00:00 PDBs and PEs are not supported by the configured Sentry server
> Found 0 debug information files
> No debug information files found
> Server does not support reprocessing.
```

**Comment by jan-auer** [comment]
This is strange. Usually, this line indicates that your Sentry server does not support PDBs, which is the case for older Sentry on-premise installations:

>   WARN    2020-03-20 08:42:07.533553100 +00:00 PDBs and PEs are not supported by the configured Sentry server

Could you please add `--log-level=debug` and paste the output?

**Comment by sseyod** [comment]
Hi @jan-auer,

I've just mailed you the log (via your GitHub contact mail). Please let me know if it doesn't get through!

With best wishes,

Pete

**Comment by jan-auer** [comment]
@sseyod Thanks for sending the log. I see the issue now :) 

Please configure your organization _slug_, not the organization _name_. In your case, this is the same, except the slug is all lowercase. This should fix your issue. This slug leads to a 404, which in your specific case makes sentry-cli believe that it's talking to an old Sentry instance.

@kamilogorek how would you feel about adding a few sanity-checks to verify that the organization and project slug only contain valid characters (iirc only lowercase and dash). Also, by default we could do a preflight on the `info` endpoint before running any command that requires server interaction, just to verify that there is no typo in the config and auth?

**Comment by sseyod** [comment]
Hi @jan-auer,

Wow - I'm amazed by how responsive you are. A great experience - makes me even more happy to help you out with this :)

Thanks for explaining the meaning of "slug" is. For anybody else reading this, that is the "Name" field (a lowercase string) in the web console for Organisation details - I was using the Display name, which was the same string but with a different case (and hence it didn't work!).

I think that points to something where the documentation, or error messages, might benefit from clarification?

FWIW, I had a similar problem when trying to figure-out the project id to put in the . sentryclirc file... the warning I had was (I think) related to missing product slug, which didn't make much sense so I had to guess that meant the project id.

Anyhow, thanks to your clarification, that means I no longer get the 404 - looks like the file is uploaded!

I have one question: how can I specify the project for which I'm uploading the .pdb file ... at the moment I have this in .sentryclirc, but I have more than project I'd like to upload. It isn't clear how to specify the project in the command line, or even if this is possible?

Best wishes,

Pete

**Comment by sseyod** [comment]
Hi @jan-auer,

If I might submit a feature request - it would be great if I could upload a pdb file via the browser; in a similar way to how debug symbols can be loaded in App Center (or, indeed, binaries are uploaded to the Microsoft Store). That would be a more convenient way for me; but I appreciate of course that others will much prefer the command line tool route (especially if they're rely on Jenkins etc. to make the builds).

Best wishes,

Pete

**Comment by jan-auer** [comment]
Noted, thanks. We're looking into improving the experience around debug files again and can consider this. As you mentioned, this is definitely not the regular case, but I can totally see how this makes it easier to test out smaller builds.

**Comment by jan-auer** [comment]
Sorry, I missed your prior question:

> how can I specify the project for which I'm uploading the .pdb file

You can can specify the project like this:

```bash
sentry-cli upload-dif --project <project_slug> /path/to/files
# or, shorter:
sentry-cli upload-dif -p <project_slug> /path/to/files
```

The same goes for the organization slug with `--org|-o`. See `sentry-cli upload-dif --help` for a description of these parameters.

**Comment by sseyod** [comment]
@jan-auer Thank you!

My remaining problem now is that I'm not seeing any crashes reported in the Browser.

I must admit that I'm not sure where to look to resolve this...

NB I'm provoking a crash in response to a menu item within the app, which calls this code:

```
      // Force crash report for sentry.io
      int* crashPtr = nullptr;
      *std::launder(crashPtr) = 0;
```

The app does indeed crash as expected, but for the avoidance of doubt, I see no report about this on the sentry.io website.

Best wishes,

Pete

**Comment by jan-auer** [comment]
Since I moved this ticket to `sentry-cli` since this was originally about uploading symbols -- would you mind to open a new issue in `sentry-native` again, so we can start tracking this there? Also, you can enable debug logs in the SDK using `sentry_options_set_debug`, which might give us a hint at what's going on. Thanks!

**Comment by sseyod** [comment]
OK, thanks, will do! Pete

**Comment by sseyod** [comment]
@jan-auer have done! Pete
