### ISSUE TITLE
Add a send-envelope command

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cli#703]
Very similar to `send-event`, but for envelopes.
As we move slowly towards envelopes, it'd be nice to be able to send envelopes through sentry-cli.

Also, it'd be very useful if we could read and send raw events from a file/dir. (See #702)

**Comment by jan-auer** [comment]
Would that be by sending an envelope file, or generate one on the fly? For comparison, `send-event` doesn't send an existing JSON file, but composes it from command line arguments.

**Comment by marandaneto** [comment]
@jan-auer I see that as being able to send a raw envelope and not generating one on the fly, the reason would be the same as #702

I'd say that being able to generate an envelope on the fly is also a feature request, as we might want to send eg a session, that can't be done by any other command through.

We could extend the description of this issue or create a new one :)

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-rust/pull/456
