### ISSUE TITLE
Systemwide .sentryrc file

### ISSUE THREAD

**Issue by azmeuk** [getsentry/sentry-cli#707]
Hi.
This would be very useful in some cases to have a systemwide `.sentryclirc` file. Maybe `/etc/sentryclirc`?
This way, all users can share a configuration. Plus this makes it a lot easier to configure sentrycli dynamically with tools like ansible.

What do you think?

**Comment by maniator** [comment]
if you have it in your home directory it is considered sys wide I believe

**Comment by kamilogorek** [comment]
That's correct. We already look for `$HOME/.sentryclirc` if it's not present in the root of the project.
