### ISSUE TITLE
Manage organizations with sentry-cli

### ISSUE THREAD

**Issue by azmeuk** [getsentry/sentry-cli#708]
This bug report is similar to #424 
When deploying sentry programatically (with ansible for instance), it would be really nice to be able to manage organizations.
Here is a scenario where I could have used such a feature.
- deploy sentry with ansible
- rename the default organization with sentry-cli
- install [sentry-auth-ldap](https://github.com/Banno/getsentry-ldap-auth) and configure the `AUTH_LDAP_DEFAULT_SENTRY_ORGANIZATION` variable with your new organization name

What do you think?

**Comment by szokeasaurusrex** [comment]
@azmeuk We do not plan to add such a feature to Sentry CLI, since the ability to manage organizations is not available in [our API](https://docs.sentry.io/api/). As far as I am aware, the only way to manage organizations is via the web interface, and there are no plans to change this.
