### ISSUE TITLE
react-native-sentry npm install fails

### ISSUE THREAD

**Issue by atom-r** [getsentry/sentry-cli#71]
To reproduce:

initialize a new react-native project with 

> react-native init [Project]

cd into the project, run 

> npm install --save react-native-sentry

You will get an error:

> Cannot read property 'tick' of null.

Originating from:

> sentry-cli-binary@1.10.0 install /Users/adamrichard/Desktop/newProj/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

Looks like it might be related to Issue #67

**Comment by mylan** [comment]
https://github.com/getsentry/sentry-cli/commit/3bec45300087d26e9e37572f6b0630fb9456abb0  introduce this error by changing the initialization of the progress bar. It is no longer being set.
@mitsuhiko

**Comment by aesmon** [comment]
Same error, unable to update react-native-sentry to 0.9.0

**Comment by mylan** [comment]
As a hackaround until this gets fixed, I installed shelljs and ran the npm install in a script using that shell, bypassing the entire progressbar. i.e.

npm install shelljs -g

foo.js contains 
var shell = require('shelljs')
shell.exec('sudo npm install react-native-sentry --save', function(code, out, err) {
    console.log('exit code::',code);
    console.log('stdout: ' , out);
    console.log('err:' , err);
});

then run 
shjs foo.js

which bypasses all of the progress bar failings.

**Comment by mitsuhiko** [comment]
This should be fixed in a few minutes. Sadly the osx build of sentry-cli is stuck in travis which is why it's not there yet. You can also install it via yarn which will not go into that section of the code temporarily.

**Comment by mitsuhiko** [comment]
This is fixed with 10.0.1. Sorry for this.

**Comment by atom-r** [comment]
No worries. Thanks for the help.
