### ISSUE TITLE
Can't upload files in linked directories.

### ISSUE THREAD

**Issue by Shottakon** [getsentry/sentry-cli#711]
I tried to install this, and deploy.

I wrote to `webpack.config.js` like below.
```
new SentryPlugin({
  include: ['./public'],
  ignore: ['node_modules', 'webpack.config.js'],
})
```
And budled files are under `./public/packs/`.

On local env, it works correctly.

But on production env, where `./public/packs` is linked to `shared/public/packs`, it doesn't work.
How should I do to work it?

**Comment by kamilogorek** [comment]
```js
const fs = require('fs');

new SentryPlugin({
  include: ['./public'],
  ignore: ['node_modules', 'webpack.config.js'],
})
fs.realpathSync('./public')
