### ISSUE TITLE
Weird display of version name

### ISSUE THREAD

**Issue by Mathieu-Castets** [getsentry/sentry-cli#712]
Hi,

I have been using `sentry-cli` to release versions since a few months. Our release name has always been of format `project@version` where `version` looks like`major.minor.patch.build`.

We've started experiencing a weird bug since our minor version number started to be made up of 2 digits (but it might not be related).

For instance, on the Releases menu, version is no longer correct: `2.37.0.1` is displayed instead of `2.3.0-7.0.1`

See also this screenshot from release details page:
<img width="374" alt="Capture d’écran 2020-04-09 à 17 12 48" src="https://user-images.githubusercontent.com/4427447/78910722-a5da2f00-7a85-11ea-9cf4-b05daaacfbc5.png">

**Comment by kamilogorek** [comment]
Hey @Mathieu-Castets, can you provide a link to an example event? It'll definitely be helpful here.

**Comment by Mathieu-Castets** [comment]
Sure.
https://sentry.io/organizations/izivia/issues/1604644497

**Comment by kamilogorek** [comment]
@Mathieu-Castets we recently introduced a unified release parsing mechanism, which can be found in detail here: https://github.com/getsentry/sentry-release-parser
In your case, the format should be `major.minor.patch+build` to be displayed in human-readable format (it still works fine from technical standpoint right now).

**Comment by Mathieu-Castets** [comment]
OK thanks for the feedback. I'll give it a try in the next release.

**Comment by Mathieu-Castets** [comment]
I can confirm using the format `major.minor.patch+build` resolved this issue.
