### ISSUE TITLE
Feature: Add Node.js API for creating a deployment

### ISSUE THREAD

**Issue by tclindner** [getsentry/sentry-cli#713]
First, thank you for all of your hard work on this library 🎉 

I’m currently leveraging `@sentry/cli` to create [`sentry-releases-action`](https://github.com/tclindner/sentry-releases-action). I can do everything via the Node.js API except creating a deployment. To do that I’m leveraging the [cli binary](https://github.com/tclindner/sentry-releases-action/blob/master/src/create-release.js#L34). It would be really nice to have a Node.js API exposed for this action too. What do you think about adding that capability?

**Comment by kamilogorek** [comment]
Hey @tclindner, that's definitely possible. Although, I don't have enough free time to implement it right now. I'm more than happy to help ship a PR for this though, so feel free to reach out.

Ref webpack plugin: https://github.com/getsentry/sentry-webpack-plugin/issues/184

**Comment by julien1619** [comment]
Hey! I would be interested to use it in the webpack plugin too, so I can try to do it.

**Comment by kamilogorek** [comment]
Added and released as `1.53.0` :)
