### ISSUE TITLE
uploading sourcemaps throws error: `thread 'unnamed' panicked at 'index out of bounds'`

### ISSUE THREAD

**Issue by Shivang-Bhandari** [getsentry/sentry-cli#716]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account (not an event-based issue)

## Package + Version

- [x] `@sentry/browser` 
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:

```
5.15.4
```

## Description

when uploading source maps, sentry fails and throws a weird error of a thread panic, attaching a screenshot for the same. using `yarn build` to build my react project.
<img width="1440" alt="Screenshot 2020-04-14 at 5 54 40 PM" src="https://user-images.githubusercontent.com/16368588/79225007-b6214e00-7e79-11ea-88ea-58d2d4190022.png">

**Comment by axelander** [comment]
I get this too trying to upload sourcemaps using the `sentry-cli react-native appcenter ..` command. Any progress?

**Comment by gauravahuja-unthinkable** [comment]
I had to downgrade from version 1.55.2 to 1.55.1 to get it working

**Comment by kamilogorek** [comment]
But there was no changes to the upload process between `1.55.1` and `1.55.2` 🤔

**Comment by Legi0n1138** [comment]
CI builds with latest cli (`npm install -g @sentry/cli`) started failing, specifying `1.55.1` solved the issue.

**Comment by axelander** [comment]
Alright, thanks! I tested downgrading to 1.54.0 and that also worked.

**Comment by Shivang-Bhandari** [comment]
will try to downgrade and see if this works for me! thanks @kAworu @Legi0n1138

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
