### ISSUE TITLE
Failure on CI after 1.52.2 was released

### ISSUE THREAD

**Issue by tbergq** [getsentry/sentry-cli#717]
Hi 👋 

We started receiving errors on our CI after the `1.52.2` version was released. Setting version to `1.51.1` and it works.

<img width="853" alt="Screenshot 2020-04-22 at 10 55 11" src="https://user-images.githubusercontent.com/7705041/79962178-099e2800-8488-11ea-8e8d-2a591a328b5c.png">

**Comment by kamilogorek** [comment]
@tbergq aw snap. I'll fix this asap. Should be patched in ~20min.

**Comment by kamilogorek** [comment]
Fixed and released as `1.52.3`. Sorry for the inconvenience.

**Comment by tbergq** [comment]
> Fixed and released as `1.52.3`. Sorry for the inconvenience.

No worries, thanks for the quick fix 🙂
