### ISSUE TITLE
react-native ram-bundle with metro preloadedModules Source code was not found

### ISSUE THREAD

**Issue by nsyujian** [getsentry/sentry-cli#719]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.59.8

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:
ram-bundle with  preloadedModules metro config file  cause source code can not found
https://sentry.io/share/issue/0d65bd40851643648f2cd0752f76cf20/

metro config file:
```js
// metro.config.js
const resolve = require('path').resolve
const fs = require('fs')

// Update the following line if the root folder of your app is somewhere else.
const ROOT_FOLDER = resolve(__dirname, '.')

const config = {
  transformer: {
    getTransformOptions: (_, { platform }) => {
      let modulePaths = []
      const moduleMap = {}

      if (platform === 'android') {
        modulePaths = require('./packager/modules.android')
      } else {
        modulePaths = require('./packager/modules.ios')
      }

      modulePaths.forEach(path => {
        if (fs.existsSync(path)) {
          moduleMap[resolve(path)] = true
        }
      })

      return {
        preloadedModules: moduleMap,
        transform: { inlineRequires: { blacklist: moduleMap } }
      }
    }
  },
  projectRoot: ROOT_FOLDER
}
console.log(`root_folder: ${ROOT_FOLDER}`)

module.exports = config

```

delete metro.confog.js ,  event resolve normal
https://sentry.io/share/issue/b2921cb65f5740a5a658c8457a83c671/

**Steps to reproduce:**
1. use ram-bundle
2. add metro.config.js as above 
3.  
```js
// app.js
setTimeout(() => {
  throw new Error('My first Sentry error!')
}, 5000)
```
4. 
```js
// packager/module.ios.js
module.exports = [
  'App.js',
  ...other files
]
```

[react-native ram-bundle perf optimize](https://reactnative.dev/docs/ram-bundles-inline-requires#configure-preloading-and-inline-requires)

**Actual result:**
https://sentry.io/share/issue/0d65bd40851643648f2cd0752f76cf20/

**Expected result:**
https://sentry.io/share/issue/b2921cb65f5740a5a658c8457a83c671/

**Comment by kamilogorek** [comment]
@GaoYuJian I reviewed both of the events that you provided, and in the first one, all the artifacts necessary to resolve the source maps are missing (558.js, 119.js, 32.js), where the second event has them all. Please note that they both have different releases configured, which creates the discrepency.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
