### ISSUE TITLE
Crash or hang on empty .map file

### ISSUE THREAD

**Issue by khell** [getsentry/sentry-cli#72]
When following the instructions [here](https://docs.sentry.io/clients/javascript/sourcemaps/#upload-sourcemaps-with-cli) to upload sourcemaps to Sentry, and an empty .map file is encountered:

- On Windows, sentry-cli.exe crashes.
- On Linux, sentry-cli hangs.

**Comment by whmountains** [comment]
`sentry-cli` also hangs on my computer when it encounters an empty `.js` file.

I'm using Mac OS Sierra.
