### ISSUE TITLE
Uploading dSYM through fastlane succeed but no dSYM files are shown in the debug files section

### ISSUE THREAD

**Issue by ARamy23** [getsentry/sentry-cli#722]
We're using a self-hosted sentry instance and we use it to report issues on a native iOS project
some of these reports come with redacted reports and not showing anything useful
so I tried to upload the dSYM files through Fastlane by using the following lane
```ruby
lane :upload_symbols do
      download_dsyms(min_version: "MINIMUM_VERSION")
      ENV["SENTRY_URL"] = "SELF_HOSTED_URL"
      sentry_upload_dsym(
        auth_token: 'AUTH_TOKEN',
        org_slug: 'ORG_SLUG',
        project_slug: 'PROJECT_SLUG',
      )
      clean_build_artifacts
    end
```

it uploads successfully but when I go to Project>Settings>Debug Files I can't see the files there

**Comment by mitsuhiko** [comment]
This might be a misconfiguration on the server side. Caches are essential for debug file upload. Can you verify they are configured?

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
