### ISSUE TITLE
`releases` requiring `--org`, but fails when argument is passed

### ISSUE THREAD

**Issue by someguynamedmatt** [getsentry/sentry-cli#723]
`sentry-cli`: `1.52.3`
`MacOS`: `10.14.6`

I'm following the [documentation](https://docs.sentry.io/workflow/releases/?platform=javascript#create-release) to create releases, but it won't accept the args I'm passing. Specifically, it's complaining that I'm not passing an `org`, so I try that with (as suggested) `--org`. It will then throw an error saying it doesn't recognize the option:

> without org being passed
```bash
$ sentry-cli releases new $VERSION --project my-project

error: An organization slug is required (provide with --org)
```

> with org being passed
```bash
$ sentry-cli releases new $VERSION --project my-project --org my-organization

error: Found argument '--org' which wasn't expected, or isn't valid in this context
```

**Comment by jan-auer** [comment]
This is because the argument is given in the wrong place. It should be:

```
sentry-cli releases --org my-org new $VERSION --project my-project
```

**Comment by someguynamedmatt** [comment]
Ah, okay. That does seem to work for me. However, I'm confused because [in config.rs](https://github.com/getsentry/sentry-cli/blob/121f1b75e468f21378b2993e369b762f2c05ddf1/src/config.rs#L274) it appears that it should be reading it from the `env` var `SENTRY_ORG`, which is set in my case.

Can the documentation to be made more clear to help future users out? 

Thanks for taking the time clarify!

**Comment by jan-auer** [comment]
> it appears that it should be reading it from the `env` var `SENTRY_ORG`

That's right. For me it also does work, at least when I invoke like this:

```
SENTRY_ORG=foobar sentry-cli releases list
```

To test this, I've removed the `org=` key from my `.sentryclirc` to ensure there's nothing configured. Even without removing, the environment takes precedence. Does this not work in your case?

> Can the documentation to be made more clear to help future users out?

Definitely. What part of the documentation can we extend, or where would you expect this? We have the [Working with Projects](https://docs.sentry.io/cli/configuration/#sentry-cli-working-with-projects) section, but that's indeed a bit hard to find.

**Comment by someguynamedmatt** [comment]
@jan-auer Okay. I figured out why my env var wasn't being picked (TL;DR: I didn't `export` the var in my shell). 

As for the documentation, at the very least a link to that [Working with Projects](https://docs.sentry.io/cli/configuration/#sentry-cli-working-with-projects) page would be immensely helpful somewhere on the [Releases](https://docs.sentry.io/workflow/releases/?platform=javascript#create-release) page. Ideally near:

> Then we’re creating a release tagged VERSION for the organization my-org for projects project1 and project2.

since that's where that arg is first referenced. Again, thank you for the asssistance.
