### ISSUE TITLE
Suppressing npm install fetch progress output

### ISSUE THREAD

**Issue by Snack-X** [getsentry/sentry-cli#726]
Though it can be suppressed with npm's `--loglevel silent` flag(#530), I don't want it to be completely silent.

Among the [level of logs in npm](https://docs.npmjs.com/misc/config#loglevel), it is definitely not an error nor a warning. It could be at a notice level.

Maybe `SENTRY_NO_PROGRESS_BAR` flag?

**Comment by OldrichDlouhy** [comment]
To add my two cents, Cypress.io uses `CI` environment variable indicating run in continuous integration environment to suppress the download progress messages - see https://github.com/cypress-io/cypress/issues/1243. Would be nice if sentry could use the same variable.

**Comment by kamilogorek** [comment]
I'm not sure what would be the use-case here? Are you talking about the CI as @OldrichDlouhy mentioned?

**Comment by Snack-X** [comment]
That's correct. We don't need 100 lines of `fetching sentry-cli-Linux-x86_64 xx%` every time we update our dependencies.

**Comment by kamilogorek** [comment]
@Snack-X I'll patch it this week then
