### ISSUE TITLE
Error: unexpected end of file when fetching sentry-cli-Linux-x86 on Jenkins via npm

### ISSUE THREAD

**Issue by SimonGolms** [getsentry/sentry-cli#727]
From time to time our CI builds via Jenkins fail because sentry-cli cannot be unpacked correctly.

- Node: v12.16.2
- npm: 6.14.4

Have I forgotten anything or is there a possibility of a more detailed error description?

```json
# package.json
...
  "devDependencies": {
    "@sentry/cli": "1.52.3",
  }
```

```txt
# Log from Jenkins
$ npm install
...

> @sentry/cli@1.52.3 install /tmp/workspace/ntcs-cd/ntcs-cd-frontend-feature-reduce-bundle-size/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Linux-x86_64 1%
fetching sentry-cli-Linux-x86_64 2%
fetching sentry-cli-Linux-x86_64 3%
...
fetching sentry-cli-Linux-x86_64 95%
fetching sentry-cli-Linux-x86_64 96%
fetching sentry-cli-Linux-x86_64 97%
fetching sentry-cli-Linux-x86_64 98%
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Emitted 'error' event on Gunzip instance at:
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.52.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.52.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2020-05-07T13_18_16_814Z-debug.log
```

**Comment by SimonGolms** [comment]
I close the issue again, as it looks like it relates to the network configuration (firewall, VPN, proxy, etc.) and is gone now.

**Comment by kamilogorek** [comment]
Thanks for getting back to let me know!

**Comment by chriscasola** [comment]
We are seeing this issue too and I'm not sure where to start on how to debug this.

Node: 12.15.0
Yarn: 1.22.4

**Comment by kamilogorek** [comment]
@chriscasola you can try to change CDN URL and see if that makes any difference for you, eg.

`SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli`

**Comment by chriscasola** [comment]
@kamilogorek using that alternate URL does fix the issue.

I did some debugging, and it seems like the default CDN url occasionally returns the correct content length for the binary, but does not actually send all the bytes before terminating the connection. I don't know if you want to follow up on the CDN or potentially add retry logic in the install script.

In the cases where the response containing the binary was cutoff, it seemed to be missing about 80% of the bytes. The bytes that were received were correct though.

My reproducer was in a heroku-like container just running the install.js script in a loop.

**Comment by kamilogorek** [comment]
Thanks for letting us know. We didn't find any abnormalities in our CDN, but it's good to be aware that it can happen.

**Comment by microJ** [comment]
如果是国内用户，可以使用命令

```bash
export sentrycli_cdnurl=https://npm.taobao.org/mirrors/sentry-cli/
npm install
```

或者

```bash
npm config set sentrycli_cdnurl https://npm.taobao.org/mirrors/sentry-cli/
npm install
```

**Comment by kaiyoma** [comment]
What exactly is the resolution here? We recently added sentry-cli to our project and we started seeing these errors pretty much immediately in our CI.

**Comment by kamilogorek** [comment]
@kaiyoma if you env. has troubles connecting to our CDN, you can point it to GitHub releases instead

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```

(you can use it as a fallback in your shell script for example)

**Comment by kaiyoma** [comment]
I appreciate the workaround, but why is this necessary at all? We're seeing errors when running a simple `yarn install`. It's pretty annoying that our other 1,000+ packages install just fine via the normal mechanisms, but this one insists on doing things differently, and now we have to opt-out of that behavior. Why not follow what the rest of the community does?

**Comment by kamilogorek** [comment]
> this one insists on doing things differently, and now we have to opt-out of that behavior. Why not follow what the rest of the community does?

sentry-cli is a program written in Rust, that's compiled separately to different architectures. It's not possible to provide it via regular npm package, but it has to be detected what env should be used first, and then it has to be pulled down from the 3rd party server, in this case, our CDN. It's not as straightforward as "just put it in the npm registry". Whenever this error happens, it's in majority of cases caused by the connection issue between the server that wants to fetch it and our CDN, not the installation process itself.

**Comment by wanyukang** [comment]
> 如果是国内用户，可以使用命令
> 
> ```shell
> export sentrycli_cdnurl=https://npm.taobao.org/mirrors/sentry-cli/
> npm install
> ```
> 
> 或者
> 
> ```shell
> npm config set sentrycli_cdnurl https://npm.taobao.org/mirrors/sentry-cli/
> npm install
> ```

给你磕头了老哥，你拯救了我的Friday Night
