### ISSUE TITLE
Feature: Token based auth for appcenter cli

### ISSUE THREAD

**Issue by zanechua** [getsentry/sentry-cli#728]
Would like the Ability to add token to the appcenter command to retrieve sourcemaps from appcenter and publish them onto sentry.

Right now the sentry cli is dependent on the appcenter cli having logged in. However this doesn't work well in build runners especially shared ones because they can share an environment. Ideally we pass the tokens into the sentry cli and every single part of it will be scriptable.

e.g.
`sentry-cli react-native appcenter --token appcentertoken app/app android build/android --deployment development --bundle-id bundleid`

**Comment by kamilogorek** [comment]
This is definitely doable to implement, however, it should be already possible to authenticate yourself using `APPCENTER_ACCESS_TOKEN` env variable instead, without the need to pass `--token` flag directly.

**Comment by zanechua** [comment]
Ah. Setting the `APPCENTER_ACCESS_TOKEN` sounds like a good work around for now.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
