### ISSUE TITLE
error: Could not find plist

### ISSUE THREAD

**Issue by zanechua** [getsentry/sentry-cli#729]
```
> Fetching latest AppCenter deployment info
error: Could not find plist
```

Getting this for the latest release.

**Comment by kamilogorek** [comment]
How are you calling the CLI command? Here's the part responsible for finding `plist` file: https://github.com/getsentry/sentry-cli/blob/ad4b654e6d555f4096c64ad07694122e5af669d8/src/utils/appcenter.rs#L152-L184

**Comment by zanechua** [comment]
The command I was running was:

`node_modules/.bin/sentry-cli react-native appcenter app/ios ios build/ios --deployment development --bundle-id com.blah.app`

Was running it from the root directory of the react native project and wasn't able to get it to work. I was logged into appcenter cli at the time.

**Comment by kamilogorek** [comment]
Would it be possible to rerun it with debug logging level? `LOG_LEVEL=debug` or `--log-level=debug`?

**Comment by zanechua** [comment]
Got the following:
![image](https://user-images.githubusercontent.com/4265429/81683453-bcaae180-9488-11ea-8636-0a720916e8d6.png)

**Comment by kamilogorek** [comment]
@zanechua sorry for the late response was kinda swamped.

If you get this error, this means that we did not find the `plist` file using the glob pattern we configured, which is `ios/*.xcodeproj`.

However, if your project structure is different than the standard one, you can still get the valid release name in 2 ways.

Either by providing `--bundle_id` and `--version_name` flags, or just `--release_name` itself. It'll override automatic search and perform the release.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
