### ISSUE TITLE
Bitbucket Server HTTPS and SSH git urls not being matched

### ISSUE THREAD

**Issue by tm1000** [getsentry/sentry-cli#732]
This is very similar to #550 except with Bitbucket server now. Recently #694 was addressed which allows one to use bitbucket server however the urls don't match so you can't use --auto

```
  INFO    2020-05-11 16:56:53.932789044 -04:00 Resolving HEAD (INFRA/docker-userfrosting@HEAD)
  DEBUG   2020-05-11 16:56:53.935206591 -04:00   Got reference URL for repo KEY/project: https://bitbucketserver.example.com/projects/KEY/repos/project/browse
  DEBUG   2020-05-11 16:56:53.935238650 -04:00   Looking for reference URL https://git.clearlyip.com/projects/KEY/repos/project/browse
  DEBUG   2020-05-11 16:56:53.938239927 -04:00   not a match: ssh://git@bitbucketserver.example.com/key/project.git != https://git.clearlyip.com/projects/KEY/repos/project/browse
```

**Comment by kamilogorek** [comment]
`ssh://git@bitbucketserver.example.com/key/project.git` is correctly parsed down to:

```
provider: "bitbucketserver.example.com",
id: "key/project"
```

However, `https://git.clearlyip.com/projects/KEY/repos/project/browse` is not.

The problem here is that Bitbucket Server has no one unified way to expose the repository through https afaik, and it can be freely configured. Because of that, we are not able to automatically determine what's the org/project url pattern.

**Comment by jan-auer** [comment]
@kamilogorek this looks like there are known prefixes, like `projects/` which we could detect. Would that be possible?

**Comment by tm1000** [comment]
I’ve gotten it to work with using —commits which was slightly painful to figure out. Is there maybe a chance we could add —repo= and use it alongside —auto. That way we could tell sentry cli what the project/key is and it can do the auto magic from there.

**Comment by kamilogorek** [comment]
@tm1000 aren't this what you are looking for (from `set-commits` docs)?

> The value can be provided as `REPO` in which case sentry-cli will auto-discover the commit based on reachable repositories. Alternatively it can be provided as `REPO#PATH` in which case the current commit of the repository at the given PATH is assumed.  To override the revision `@REV` can be appended which will force the revision to a certain value.

`REPO` itself would do something similar to `--repo --auto`.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/775
