### ISSUE TITLE
Add support for external repositories?

### ISSUE THREAD

**Issue by Jake-Shadle** [getsentry/sentry-cli#742]
Sentry helpfully supports using [Custom repositories](https://docs.sentry.io/workflow/debug-files/#symbol-servers) for debug symbols, but sentry-cli itself doesn't support uploading to them. 

Before I implemented our own uploader for GCS which would be basically redoing a lot of work that sentry-cli already does, I thought I would ask if such a feature would be interesting to add to sentry-cli itself, either as an additional argument to `upload-dif` or as a separate subcommand.

I would be up for doing the work and making a PR if this seems reasonable?

**Comment by mitsuhiko** [comment]
There is definitely interest but we so far thought about doing this as part of the [symsorter](https://github.com/getsentry/symbolicator/tree/master/symsorter) tool. So probably opening up a PR there would be the better path forward.

We're currently not distributing binaries for that but would be happy to start doing it if that tool becomes more useful.

**Comment by Jake-Shadle** [comment]
Ahh nice, wasn't aware of that tool, I'll do the change there then, thanks!
