### ISSUE TITLE
sentry-cli: cannot execute binary file

### ISSUE THREAD

**Issue by vkulov** [getsentry/sentry-cli#747]
I'm working on an AWS Lambda function that does some deployments. As the final part of the deployment we need to upload the source maps to sentry. 

I don't seem to find a way to do that in NodeJS. I'm using sentry-cli and something similar to thins:
`    
const sentryCli = new SentryCli();
    sentryCli
        .releases.new(buildNum)
        .then(() => {
            return sentryCli.releases.uploadSourceMaps(buildNum, options);
        })
        .then(() => {
            return sentryCli.releases.finalize(buildNum);
        });
`

However I'm running into error. It tries to execute a binary:
Error: Command failed: /var/task/node_modules/@sentry/cli/sentry-cli releases new 123456\n/var/task/node_modules/@sentry/cli/sentry-cli: /var/task/node_modules/@sentry/cli/sentry-cli: cannot execute binary file\n

**Comment by kamilogorek** [comment]
The call itself looks good, however, there seems to be a problem with AWS filesystem permissions, where installed binary has incorrect chmod set. This is not the cli issue itself, but rather environment problem. See:

https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html
https://aws.amazon.com/premiumsupport/knowledge-center/lambda-deployment-package-errors/
