### ISSUE TITLE
Update alpine image to avoid SSL certificate problem

### ISSUE THREAD

**Issue by biagimarco** [getsentry/sentry-cli#751]
You are currently using `alpine:3.7` in your docker file:
`https://github.com/getsentry/sentry-cli/blob/master/Dockerfile#L22`
Starting from 30/05/2020, this is causing the following SSL problem when accessing some Sentry instances:
`curl: (60) SSL certificate problem: certificate has expired`
Updating to alpine:3.12 solves the problem.

This is related to the following:
`https://thesslonline.com/blog/sectigo-addtrust-external-ca-root-expiring-may-30-2020`
Alpine 3.7 refers to the expired certificate, while Alpine 3.12 correctly refers to the new one.
Sentry CLI does not seem to support an option to ignore ssl problems (like curl `--insecure`), thus I think that the only possible solution is to update the image.

**Comment by tonyo** [comment]
Thanks for the report! 
It will be fixed in the next image version.
