### ISSUE TITLE
Sentry handles hang?

### ISSUE THREAD

**Issue by Prachiagrawal1** [getsentry/sentry-cli#766]
Does sentry handles or tell about hang or os crashes....or it does tell about application crashes?

**Comment by kamilogorek** [comment]
Sorry, but I'm not sure if I understand the question.

**Comment by Prachiagrawal1** [comment]
I mean if I used sentry with my app and released it, will it also notify me if there is any hang issue with my app while user is using?or it catches only exceptions?

**Comment by Prachiagrawal1** [comment]
I wanted to try the demo. But I am unable to configure it with my cpp app. Can you help me with it?

**Comment by kamilogorek** [comment]
This is repository for `sentry-cli`, which is a tool to upload sourcemaps and debug symbols to Sentry.
For the cpp SDK itself, please see https://github.com/getsentry/sentry-native
And direct your questions on our SDK forum https://forum.sentry.io/c/sdks or Discord channel https://discord.com/invite/Ww9hbqr

Cheers!
