### ISSUE TITLE
Yarn installation keeps downloading binary

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-cli#77]
Originally reported here: https://github.com/getsentry/react-native-sentry/issues/74

**Comment by mitsuhiko** [comment]
This in theory is fixed now with the next release.

**Comment by smmoosavi** [comment]
I checked and problem exist yet.
after I run `yarn add some-package` or `yarn remove some-package` It download sentry-cli-Linux-x86_64 again

```
yarn --version
0.23.4

npm ls --depth 1| grep sentry
├─┬ react-native-sentry@0.11.6
│ └── sentry-cli-binary@1.13.0
```

**Comment by mitsuhiko** [comment]
I will have another look at this.

**Comment by smmoosavi** [comment]
nice
