### ISSUE TITLE
Installing the latest 1.54.0 package on Windows fails

### ISSUE THREAD

**Issue by georgiosd** [getsentry/sentry-cli#777]
From admin powershell prompt:
```
C:\Windows\system32> npm install -g @sentry/cli
C:\Users\georgiosd\AppData\Roaming\npm\sentry-cli -> C:\Users\georgiosd\AppData\Roaming\npm\node_modules\@sentry\cli\bin\sentry-cli

> @sentry/cli@1.54.0 install C:\Users\georgiosd\AppData\Roaming\npm\node_modules\@sentry\cli
> node scripts/install.js

Error: Command failed: C:\Users\georgiosd\AppData\Roaming\npm\node_modules\@sentry\cli\sentry-cli.exe --version

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.54.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.54.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\georgiosd\AppData\Roaming\npm-cache\_logs\2020-06-28T18_38_17_562Z-debug.log
```

**Comment by alex-adestech** [comment]
@georgiosd this solved the issue for me. https://github.com/getsentry/sentry-cli/issues/744#issuecomment-632664646

**Comment by georgiosd** [comment]
@alex-adestech thanks, but I am already working with 12.x

**Comment by kamilogorek** [comment]
Can you provide a log mentioned in the original post? Or is it the same thing you already pasted?

**Comment by georgiosd** [comment]
@kamilogorek log above is with node 12.x, yes. Is that what you meant?

**Comment by kamilogorek** [comment]
I was wondering if `C:\Users\georgiosd\AppData\Roaming\npm-cache\_logs\2020-06-28T18_38_17_562Z-debug.log` contains anything more than what you already provided.

**Comment by kamilogorek** [comment]
It's hard to tell what went wrong, as node doesn't give enough context for the failure.
I'd start with the lowest hanging fruits first:

`npm cache clean --force`, delete `C:\Users\georgiosd\AppData\Roaming\npm\node_modules` (or more specific @sentry directory) and then try to create the directory yourself and give it executable permissions. Sometimes doing just that fixes npm issues.

**Comment by georgiosd** [comment]
Not sure but it's not happening any more. Thanks.
