### ISSUE TITLE
404 Error when Uploading Symbol file from CLI

### ISSUE THREAD

**Issue by cguess** [getsentry/sentry-cli#782]
Platform: MacOS 10.15.6
Sentry CLI: `sentry-cli 1.55.0`

When trying to upload a zip of iOS dSYM's I get
```
error: API request failed
  caused by: sentry reported an error: The requested resource does not exist (http status: 404)
```

The command I'm trying is the following:
```
sentry-cli --auth-token *AUTH TOKEN* upload-dif --org *org_name* --project *project_name* '/path/to/Xcode/dSYMs/Archive.zip' --log-level=debug
```

Specifically it's the second request that is failing, the debug looks like this:
```
DEBUG   2020-07-06 13:52:55.554366 -04:00 > GET /api/0/projects/org/project/files/dsyms/unknown/?checksums=1e988386bb131678a1a0c429551c649f19dbb28f.....
```

The difference is that the first request starts with `https://sentry.io/api/0/projects/`, this missing host on the second request seems to be the issue.

Thanks for any help y'all can provide!

**Comment by kamilogorek** [comment]
Could you provide a whole debug log please? thanks!

**Comment by cguess** [comment]
This should do it (i've removed my auth keys for obvious reasons)

[sentry-output.log](https://github.com/getsentry/sentry-cli/files/4880935/sentry-output.log)

**Comment by nturpin** [comment]
@kamilogorek same error here, when I tried this after our original script stopped working. Any way we could provide you some logs without posting them publicly here?

**Comment by kamilogorek** [comment]
@nturpin feel free to reach me out kamil@sentry.io Thanks for the patience, it's quite a busy time recently.

**Comment by nturpin** [comment]
An update from our side: I do not get this error anymore, our scripts are working again. Currently using sentry-cli 1.55.1 

Thank you @kamilogorek! I will send you more info or logs if we find this issue again.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by bardonadam** [comment]
Having the same issue on `sentry-cli/1.74.2`

**Comment by hannojg** [comment]
@kamilogorek Sorry for the resurrection of this old bug but I just ran into the same problem. However, it doesn't seem to be missing base url, but I think just the /unknown in the path?

Should I open a new ticket for it?

**Comment by loewenheim** [comment]
Yes, please do.
