### ISSUE TITLE
[featurerequest] sentry-cli send-event --json-logfile

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/sentry-cli#787]
Some programs can output structured json log files. It would be nice if sentry-cli could send those so that the structured information could be used by sentry on the other side to display clearer breadcrumbs and extract the error information only for example. 

The context for this, is using sentry-cli to report errors in a gatsby-build, see issue https://github.com/gatsbyjs/gatsby/issues/25789 for more context.

**Comment by kamilogorek** [comment]
Sounds good! Although it's not on our roadmap anytime soon, I'd be more than happy to help with implementing this.

**Comment by kamilogorek** [comment]
This has been implemented in #1058 and released as a part of `1.71.0`.
