### ISSUE TITLE
FetchError: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by breminnyi** [getsentry/sentry-cli#796]
Hi! Npm fails to install @sentry/cli package and produces the following error:

FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.55.1/sentry-cli-Windows-x86_64.exe failed, reason: self signed certificate in certificate chain
npm WARN helloworld@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.55.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.55.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Also it means I'm unable to install all dependent packages like @sentry/wizard, sentry-cordova plugin etc.

**Comment by kamilogorek** [comment]
This is an environment configuration issue and has to be resolved there. You can most likely fix this using `ca-certificates`. See https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce for more details.
