### ISSUE TITLE
Upload dsyms fails with EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by nturpin** [getsentry/sentry-cli#797]
Related to this closed issue: https://github.com/getsentry/sentry-cli/issues/374

Our sentry script started failing very recently on the upload step, without changes on our side that I am aware of.
We are getting this error (even after upgrading plugins and retrying):

$ bundle exec fastlane upload_dsyms_to_sentry
[✔] 🚀 
+------------------------+---------+--------------------------+
|                        Used plugins                         |
+------------------------+---------+--------------------------+
| Plugin                 | Version | Action                   |
+------------------------+---------+--------------------------+
| fastlane-plugin-sentry | 1.6.0   | sentry_upload_dsym       |
|                        |         | sentry_set_commits       |
|                        |         | sentry_upload_sourcemap  |
|                        |         | sentry_finalize_release  |
|                        |         | sentry_upload_file       |
|                        |         | sentry_upload_proguard   |
|                        |         | sentry_create_release    |
+------------------------+---------+--------------------------+

[15:22:50]: Driving the lane 'upload_dsyms_to_sentry' 🚀
[15:22:50]: --------------------------------
[15:22:50]: --- Step: sentry_upload_dsym ---
[15:22:50]: --------------------------------
[15:22:50]: sentry-cli 1.49.0 installed!
[15:22:50]: Starting sentry-cli...
[15:22:51]: error: EOF while parsing a value at line 1 column 0

**Comment by kamilogorek** [comment]
@nturpin would you be able to provide a full debug log for the failure?

```
SENTRY_LOG_LEVEL=debug
```

Thanks!

**Comment by dannyhertz** [comment]
I'm also having this issue (using via fastlane sentry_upload_dsym) Any help would be greatly appreciated!

**Comment by dannyhertz** [comment]
@nturpin were you able to resolve this?

**Comment by nturpin** [comment]
Sorry for late answer! It was somehow resolved, either an update or something else solved it. I have not seen the issue anymore, lately.

**Comment by dannyhertz** [comment]
@nturpin fascinating! Would you mind letting me know which version of fastlane and sentry-cli you are using? Thanks!

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by kamilogorek** [comment]
I suggest upgrading to `1.64.0` which has a more descriptive error message and should make debugging easier. Cheers!
