### ISSUE TITLE
[featurerequest] option to manually upload dsym files to Sentry, if sentry-cli fails

### ISSUE THREAD

**Issue by nturpin** [getsentry/sentry-cli#798]
Whenever scripts or utilities fail, it is always good to have a backup solution. 

Are you considering implementing such a solution? Or perhaps it exists already and I am not able to find it?

**Comment by kamilogorek** [comment]
It's not possible and we are not planning on changing this anytime soon.
If something is not working, it should be fixed in sentry-cli directly.
Cheers!
