### ISSUE TITLE
host name resolution on private dns

### ISSUE THREAD

**Issue by skeggse** [getsentry/sentry-cli#799]
I don't quite have the rust skillset to figure this out - I'm trying to use the cli to inspect releases, and getting an error related to the host name. Just to rule things out, I'm able to run `curl` against the displayed URL and getting a big 'ol json blob as expected.

```sh
$ SENTRY_AUTH_TOKEN='{redacted}' SENTRY_LOG_LEVEL=debug SENTRY_ORG='{redacted}' SENTRY_URL='https://{redacted}' npx @sentry.cli releases list
  DEBUG   2020-08-07 17:16:29.962171948 -07:00 sentry-cli version: 1.55.1, platform: "linux", architecture: "x86_64"
  INFO    2020-08-07 17:16:29.962221573 -07:00 sentry-cli was invoked with the following command line: "/home/{redacted}/node_modules/@sentry/cli/sentry-cli" "releases" "list"
  DEBUG   2020-08-07 17:16:29.962862175 -07:00 request GET https://{redacted}/api/0/organizations/{redacted}/releases/
  DEBUG   2020-08-07 17:16:29.962881327 -07:00 using token authentication
  DEBUG   2020-08-07 17:16:29.962891426 -07:00 retry number 0, max retries: 0
error: API request failed
  caused by: [6] Couldn't resolve host name
  DEBUG   2020-08-07 17:16:29.964016284 -07:00 client close; no transport to shut down  (from sentry)
```

The DNS name in question isn't available publicly - I'm able to query it manually by hitting a specific IP from my machine, and my local resolver (`/etc/resolv.conf`) is configured to locate it. Maybe this is a limitation of however rust or the applicable library is resolving the name?

A workaround for this if it's difficult to address would be to let me manually resolve an IP and pass it in alongside the hostname/SNI to send.

**Comment by kamilogorek** [comment]
Closing the issue as since it was originally opened, plenty of things changed and deps were updated. There's a large chance that is has been fixed in the meantime. Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
