### ISSUE TITLE
Add tasks to Azure Dev Ops to allow for easy integration of Sentry releases

### ISSUE THREAD

**Issue by ajbeaven** [getsentry/sentry-cli#801]
It'd be great to have a Azure Dev Ops task in the marketplace that would allow for easy integration with the Sentry releases stuff. Manual integration is currently difficult because [the bash install script is broken on windows](https://github.com/getsentry/sentry-cli/issues/800), and Powershell has been a bit of a nightmare to use for this purpose.

**Comment by kamilogorek** [comment]
Have you seen our Azure integration by any chance? It's available in your organizations settings and it may be already just what you are looking for.

![image](https://user-images.githubusercontent.com/1523305/89885767-d664dd80-dbcb-11ea-8125-b4c593d877f3.png)

**Comment by ajbeaven** [comment]
Yes, I've installed that, however it only relates to work items in Azure DevOps (which we don't use anyway). I'm after pipeline integrations, so for instance, when creating a new build, I can notify Sentry of a new release and easily integrate with the new(?) releases functionality. 

Presumably this would be in the form of a pipeline task that you could install from the Azure DevOps marketplace.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like there is a working solution due to fixing #800 mentioned in the original issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by ajbeaven** [comment]
Kind of. I still think there's a bit of scope to add a marketplace plugin to interface with Sentry that would make integration much easier. If you don't see this ever happening then feel free to close.
