### ISSUE TITLE
bug: false negative on invalid email

### ISSUE THREAD

**Issue by jef** [getsentry/sentry-cli#803]
### Description

Using `sentry-cli 1.55.1`

```
Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.
Could not find the previous commit. Creating a release with 20 commits.
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object({"commits": Object({"author_email": Array([String("Enter a valid email address.")])})})

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

When I run a `git log`, I have an output of regular addresses and even anonymous email addresses. But I believe this is the culprit for given me the above error:

`49699333+dependabot[bot]@users.noreply.github.com`

Any email address like this I believe will also throw errors:

`29139614+renovate[bot]@users.noreply.github.com`

Probably because of the square brackets.

Maybe the email should either be ignored or have an option to ignore commits by certain names?

**Comment by kamilogorek** [comment]
Hey, thanks for opening the issue. Verified it locally and this is indeed the case. However, the problem lies on the server-side, not the CLI itself. We'll discuss internally where to fix it though, as this change has some broader implications to the whole "suspected-commits" system. Cheers!

**Comment by jbinto** [comment]
Also see https://github.com/getsentry/sentry/issues/20085

**Comment by ianks** [comment]
Is there a temporary fix in the meantine?

**Comment by kamilogorek** [comment]
Upstream fix PR: https://github.com/getsentry/sentry/pull/20342

**Comment by silent1mezzo** [comment]
This has been merged and deployed.
