### ISSUE TITLE
Can't add more than 50 commits to a release with sentry-cli

### ISSUE THREAD

**Issue by bartek-wesolowski** [getsentry/sentry-cli#806]
I created a first release with sentry-cli and added some commits to it. Now, I'm creating a second release and setting its commits with:
`sentry-cli releases set-commits pl.allegro@6.43.0+64300 --auto`
There are 76 commits to be added. Unfortunately, I can only see the oldest 26 commits on sentry.io.
When I run the command with `--log-level=debug` then I see two requests like this:
`PUT https://sentry.io/api/0/organizations/allegro-mobile-cloud/releases/pl.allegro@6.43.0+64300`
The first one contains 50 commits and the second one 26 commits. The problem is probably that the second request overwrites the first one.

**Comment by kamilogorek** [comment]
That was indeed the bug on our side. Will release a new version and ping you soon.
