### ISSUE TITLE
Could not automatically determine release name through github action

### ISSUE THREAD

**Issue by ljosberinn** [getsentry/sentry-cli#810]
```sh
Command failed: /action-release/dist/sentry-cli releases propose-version
  DEBUG   2020-08-26 23:04:46.392798280 +00:00 sentry-cli version: 1.55.0, platform: "linux", architecture: "x86_64"
  INFO    2020-08-26 23:04:46.392870783 +00:00 sentry-cli was invoked with the following command line: "/action-release/dist/sentry-cli" "releases" "propose-version"
  DEBUG   2020-08-26 23:04:46.393017390 +00:00 error: running update nagger
  DEBUG   2020-08-26 23:04:46.393029291 +00:00 skipping update nagger because session is not attended
error: Could not automatically determine release name
  DEBUG   2020-08-26 23:04:46.393415409 +00:00 client close; no transport to shut down  (from sentry)
```
https://github.com/ljosberinn/personal-react-boilerplate/runs/1033927999?check_suite_focus=true

```yml
  sentry-release:
    name: Create Sentry Release
    runs-on: ubuntu-latest
    needs: deploy-prod
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_LOG_LEVEL: debug
    steps:
      - uses: getsentry/action-release@v1.0.1
        with:
          environment: production
          sourcemaps: './_next'
```

fwiw, I've had the same exact error previously with the webpack plugin, so I'll fallback to that and live without suspected commits then... but would be at least find out why this occurs

**Comment by kamilogorek** [comment]
I see you are using `getsentry/action-release` for this. Let me ping @mgaeta who knows more about it than me.

**Comment by mgaeta** [comment]
Hi I found what's causing the problem. In your example, the action tries to pick a version name based on the current `HEAD`. You need to check out your repo in order to use git:
```
steps:
  - uses: actions/checkout@v2
  - uses: getsentry/action-release@v1
    with:
      environment: production
      sourcemaps: './_next'	
```
I'll update the documentation to reflect this.

**Comment by ljosberinn** [comment]
Thanks, that did it! Ironically that made me discover a flaw in the whole concept of using the action in my situation, as I don't build the site via actions and then deploy those artifacts, but just initiate a build remotely.
