### ISSUE TITLE
HTTP 504 when trying to set commits to a release

### ISSUE THREAD

**Issue by bartek-wesolowski** [getsentry/sentry-cli#814]
I'm using setnry-cli  1.55.2. I'm running the following command:
`sentry-cli releases set-commits <my version here> --auto`

I'm getting this result:
```
error: API request failed
  caused by: sentry reported an error: gateway timeout (http status: 504)
```

This is probably because the number of commits I'm trying to send is quite large (hundreds).

I filed another issue recently in which only 50 commits were attached to a release even if there were more of them. After fixing this, perhaps the server can't handle such big commit numbers.

**Comment by alacoste** [comment]
We are seeing the issue as well. Our CI sometimes fails on the first sentry command, but even if it succeeds it always fails on the second.

First:
```
sentry-cli releases new -p <project> <release>
error: API request failed
  caused by: sentry reported an error: gateway timeout (http status: 504)
```

Second:
```
+ sentry-cli releases set-commits --auto <release>
+--------------+--------------+
| Repository   | Revision     |
+--------------+--------------+
| xxxxxxxxxxx | <xxxxxxxxxxx> |
+--------------+--------------+
error: API request failed
  caused by: sentry reported an error: gateway timeout (http status: 504)
```

**Comment by cleptric** [comment]
This still seems to be an issue, a user on Discoed reported that they run into this problem with a release containing 1200+ commits.

**Comment by Neirda24** [comment]
Hi. I am the use on discord 😅 . Yes I'd like to create the first release of the project with 1200+ commits. I am getting the 504 :/. Available if need more details of course.

**Comment by szokeasaurusrex** [comment]
@Neirda24, thank you for reaching out to us!

#2026 appears to be related (possibly a duplicate?), but @ankitghosh, the user who opened #2026, was reporting an error with HTTP status 413. 

Regardless of whether #2026 is a duplicate, it seems the fix for both issues will be the same: we likely need to introduce an option to limit the number of commits included in a release.

Since both issues could be resolved with such a fix, we can make this a priority!

**Comment by adrienroches-sensio** [comment]
I retried this morning and it worked. all 1284 commits were pushed to sentry. Don't know why it failed yesterday.

**Comment by Neirda24** [comment]
I retried this morning and it worked. all 1284 commits were pushed to sentry. Don't know why it failed yesterday.

**Comment by szokeasaurusrex** [comment]
Hmm, strange, glad it worked out for you though, @Neirda24!
