### ISSUE TITLE
Allow to set timestamp when sending events

### ISSUE THREAD

**Issue by GeryEmreis** [getsentry/sentry-cli#819]
Hi, I use sentry-cli to send events to Sentry.  I would like to be able to set event timestamp through CLI because I read events from log file of my application and date of the event can be in the past

**Comment by kamilogorek** [comment]
That sounds like a good addition and it should be trivial to add, although I don't have much time recently, so it'll have to wait few days. PR is more than welcome though, and I'm happy to help if you have any questions :)
