### ISSUE TITLE
Since Jun 9, sentry-cli has been seg faulting in our build

### ISSUE THREAD

**Issue by jensenharris** [getsentry/sentry-cli#82]
Since last Friday, June 9, sentry-cli has been segmentation faulting midway through upload. (The actual place it crashes seems different each build.)

devops/upload_to_sentry.sh: line 13: 28674 Segmentation fault      (core dumped) sentry-cli releases files $CIRCLE_BUILD_NUM upload-sourcemaps -u '~/sources' swamp/sources/

devops/upload_to_sentry.sh returned exit code 139

**Comment by mitsuhiko** [comment]
@jensenharris is there any chance you could tell us which linux distribution / glibc version / architecture you use? It's unlikely sentry-cli itself segfaults, it's more likely that we are linking against a library that you have an incompatible version of.

We currently link against this:

```
$ ldd `which sentry-cli`
	linux-vdso.so.1 =>  (0x00007fff961c4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc71c379000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc71d0ce000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc71c160000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc71bf5b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc71bd53000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc71bb35000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc71b91e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc71b618000)
```

**Comment by mitsuhiko** [comment]
I'm going to close this due to inactivity and inability to reproduce. If it still happens please let us know which linux distribution, cpu architecture and glibc version you are using.
