### ISSUE TITLE
Badly worded error message "Couldn’t not find the SHA"

### ISSUE THREAD

**Issue by davidsneighbour** [getsentry/sentry-cli#823]
On sending 

```
./node_modules/.bin/sentry-cli releases new "$VERSION"
./node_modules/.bin/sentry-cli releases finalize "$VERSION" --started "$TIMESTAMP"
./node_modules/.bin/sentry-cli releases set-commits --auto "$VERSION"
```

I receive

`error: Couldn’t not find the SHA of the previous release in the git history. Increase your git clone depth.`

"Couldn't not" would mean it could find the SHA ;) Either couldn't or could not appears appropriate here.

This appears related to this line: https://github.com/getsentry/sentry-cli/blob/4aed5a5c8969bd4df6fd939f1489c7ca4594e721/src/utils/vcs.rs#L489

I would, in general, advise against couldn't, wouldn't, shouldn't and similar shortenings in such error messages to be very clear.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-cli/pull/822
Cheers!
