### ISSUE TITLE
install script unable to find Windows 32-bit binary (403)

### ISSUE THREAD

**Issue by AxelTerizaki** [getsentry/sentry-cli#825]
Hello.

We're still using Windows 32 bits workstations (not for too much longer) and @sentry/cli fails the install phase with a 403 error.

I tried looking around and found out that node was reporting a "ia32" arch for this particular architecture and not "i686" as I've seen in the install.js file. When trying out different URLs, I realized that https://downloads.sentry-cdn.com/sentry-cli/1.56.1/sentry-cli-Windows-ia32.exe didn't exist, but https://downloads.sentry-cdn.com/sentry-cli/1.56.1/sentry-cli-Windows-i686.exe did.

Note that this was working about 2 weeks ago or so, from what I remember when I last tried a npm install of the project on that machine.

The machine is a Core i3-4100M CPU so I guess the ia32 arch is normal in this case ?

Hope that helps and a fix can be made soon :)

**Comment by kamilogorek** [comment]
Hey @AxelTerizaki, the fix was merged exactly 34 minutes ago :)
https://github.com/getsentry/sentry-cli/pull/824

**Comment by AxelTerizaki** [comment]
Haha nice :) I'll have to wait for the npm release then.

Thanks a lot !

**Comment by kamilogorek** [comment]
Released as `1.57.0`. Cheers!
