### ISSUE TITLE
Avoid downloading file

### ISSUE THREAD

**Issue by connorjburton** [getsentry/sentry-cli#827]
Hi,

We are behind a fairly strict corporate proxy, the current installer doesn't work as our certificate and user agent does not get passed  to `node-fetch`. I have modified the installer myself to use `axios` and the current settings which does correctly get to the proxy now however the CDN that the installer file is hosted on has a high threat level and is blocked.

As you can tell I don't have many other options, I can see there is an option to supply another CDN which would work but I am not sure we have a corporate CDN of that kind.

I was wondering if it is possible to skip the download and use a pre-downloaded installer file that I can point to with a env variable possibly?

Thanks!

**Comment by kamilogorek** [comment]
Hey, if your configuration allows it, you can give github a try:

```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```

If that still doesn't work for you, you can skip running install script with `npm install @sentry/cli --ignore-scripts` or `yarn add @sentry/cli --ignore-scripts` and then manually place your binary in the root directory of `node_modules/@sentry/cli`. It'll work just fine that way as well.

Cheers!

**Comment by connorjburton** [comment]
We have found the hard way github release download URL's don't work as they generate an S3 link and 403 you there, our proxy doesn't like following redirects.

The `ignore-scripts` method is interesting but as `@sentry/cli` is already in our `package.json` we would have to run `yarn --ignore-scripts` which would ignore all scripts for all packages which isn't an option for us.

If I were to install the application manually and remove/stop the install script on my forked repo would that work? 

The only other option I can think is to create a local CDN server and serve it from there, but that is my last option.

**Comment by connorjburton** [comment]
Or as you said, I could remove the install script on my forked repo and manually place the binary in the `node_modules/@sentry/cli` folder and it would work?

**Comment by kamilogorek** [comment]
Other than creating some bootstrapping script, I'd say it's your best bet.

A script could be as simple as:
```sh
#!/bin/bash
set -e

yarn
yarn add @sentry/cli
cp ../your-local-copy/sentry-cli node_modules/@sentry/cli/
ln -s node_modules/@sentry/cli/sentry-cli node_modules/.bin # this is not necessary, but replicates how npm/yarn links binaries
git checkout -- package.json # yarn adds the package, but we don't want it there, so revert the change
```

**Comment by connorjburton** [comment]
Okay that is really helpful, thanks. And thanks for replying so quickly.
