### ISSUE TITLE
Fullness error info

### ISSUE THREAD

**Issue by xesjkeee** [getsentry/sentry-cli#832]
Hey, Sentry team 👋

When I got error like `Error: Received 404: Not Found`, I guess I'm a little numb

https://github.com/getsentry/sentry-cli/blob/ca892f71fd75c7f3c9ae1d96e89beab823160ca5/scripts/install.js#L212

I would like if you add some more detailed information, please 🙌 

In the error when I cant download binary, I expect what I get something like this:  
`Error: Received 404: Not Found: Can't download the file: ${releasesUrl}-Linux-${archString}`

**Comment by evilrussian** [comment]
Life situatuion - if SENTRYCLI_CDNURL incorrect or there is not file there you will got an error:
```
error /builds/test/frontend/node_modules/@sentry/cli: Command failed.
 Exit code: 1
 Command: node scripts/install.js
 Arguments: 
 Directory: /builds/test/frontend/node_modules/@sentry/cli
 Output:
 Error: Received 404: Not Found
 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
it can confuse you
