### ISSUE TITLE
install script doesn't check if cli has been installed to local user

### ISSUE THREAD

**Issue by njbmartin** [getsentry/sentry-cli#835]
Running `curl -sL https://sentry.io/get-cli/ | bash` on this Docker image `mcr.microsoft.com/vscode/devcontainers/javascript-node` installs it here:

```
/usr/local/bin/sentry-cli
```

That's fine, and can use it directly, but when I do clean install of the npm modules, `@sentry/webpack-plugin` fails as `sentry-cli` tries to create a directory here: `/root/.npm/sentry-cli` rather than checking if it is already installed.

I saw that `npm config set unsafe-perm true` would solve the issue of installing it as root, but it should at least check if the binary exists first.

**Comment by kamilogorek** [comment]
Afair `/root/.npm` is our cache location, you should be able to modify it with any of the env variables below:

```
env.npm_config_cache
env.npm_config_yarn_offline_mirror
env.APPDATA
```

**Comment by njbmartin** [comment]
Thanks, @kamilogorek. The problem isn't that the NPM module fails to install, it's the fact there already exists a CLI binary, but the NPM package ignores it.

I also don't want to mess with environment variables for npm.

**Comment by kamilogorek** [comment]
Related https://github.com/getsentry/sentry-cli/issues/307#issuecomment-1022321353

**Comment by kamilogorek** [comment]
@njbmartin this will be possible in the next release :)
