### ISSUE TITLE
Force overwrite when uploading symbol files

### ISSUE THREAD

**Issue by winstondu** [getsentry/sentry-cli#837]
Is there a way for the `upload-dif` to not check if the files already exist on the server, but instead straight up overwrite them?

I need this because the `sentry_upload_dsyms` lane does not seem to use my bcsymbolmaps to unobfuscate, so I need to unobsufcated myself locally on my machine, and then force upload up those files to sentry (without sentry refusing to accept them)

**Comment by kamilogorek** [comment]
There's no such option at the moment. As for the issue with obfuscation, cc @jan-auer

**Comment by jan-auer** [comment]
Sentry deduplicates debug files by their contents. If you deobfuscate, then the contents change and so sentry-cli should accept them for uploading. 

I'm a little surprised that BCSymbolMaps are not being applied in your case, however. Usually, `sentry-cli` can do this using [`--symbol-maps`](https://docs.sentry.io/product/cli/dif/#symbol-maps). 

Are you using the [`sentry-fastlane-plugin`](https://github.com/getsentry/sentry-fastlane-plugin)? It does attempt to [include symbol maps](https://github.com/getsentry/sentry-fastlane-plugin/blob/0cae14ecf749abc80d2dc544cc24805790691a67/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb#L20), but potentially something is preventing that in your environment.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by antonpodolsky** [comment]
@kamilogorek In my case this is needed to be able to upload same files but with different names. Each name includes a different version, but the content is the same.

**Comment by kamilogorek** [comment]
@antonpodolsky source maps and other js artifacts are handled differently by the cli. And we do provide deduplication skipping there :) `sentry-cli sourcemaps upload <path> --no-dedupe`

**Comment by antonpodolsky** [comment]
@kamilogorek Great, thank you!
