### ISSUE TITLE
Add an option to disable xcode notifications

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-cli#84]
Currently the build notification popups always come up in xcode if building in background. There should be an option to disable it.

**Comment by jeffbowen** [comment]
Did you change your mind on this @mitsuhiko or did you find a way to disable notifications?

**Comment by reepush** [comment]
@jeffbowen Adding this to _ios/sentry.properties_ hides notifications:
```
ui.show_notifications=false
```

**Comment by jeffbowen** [comment]
Thanks @reepush! Now I see. Glad to have those silenced.
