### ISSUE TITLE
Partial releases and source maps

### ISSUE THREAD

**Issue by seroy** [getsentry/sentry-cli#841]
We have typical Django project with backend and frontend codebase. Often we have a situation when only python code is changed and need to release it. So we don't run "full" deploy with building javascript/source maps. This problem that release don't have source maps files in this case.
Is there any way to "say" Sentry to take source maps from the previous release? Or what is the best way to solve this problem?

**Comment by kamilogorek** [comment]
There's no way to achieve this. When your release ID changes, you need to upload recompiled sources as well.  The important part here is that release inside your `Sentry.init` call has to match the release that contains sources.

**Comment by seroy** [comment]
I am understand that right now is no way to achieve this, but i am pretty sure that our release cycle is not unique and it would be nice to have a solution out of the box. The first idea is that if Sentry would have API for downloading the source maps from previous release then it will be possible with shell scripts/ansible/etc (as part of deploy) to download and re-upload for new release. The second possible (and much better) solution to add in sentry-cli command to "say" Sentry API to take source maps from previous release (pros: no download/upload -> faster deploy, in theory less space usage on sentry servers, great and friendly DX)
Is there any chance of seeing this feature in the near future?

**Comment by kamilogorek** [comment]
We do have an API for that - https://docs.sentry.io/api/releases/
As for the second option, you'd have to ask at getsentry/sentry repo, but as far as I know, t's not on our roadmap anytime soon.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
