### ISSUE TITLE
Always get Invalid token (http status: 401) for self-hosted Sentry

### ISSUE THREAD

**Issue by phatNfqAsia** [getsentry/sentry-cli#844]
**Expected:**
I can run command `sentry-cli releases --org xxx --project xxx  new fixed-release` after logging in by admin user (using generated auth token)

**Current behaviour:**
I constantly get this error
`error: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)`

**Environment:**
My .sentryclirc look like this:
[defaults]
url=$SELF_HOSTED_DOMAIN_NAME
org=$MY_ORG
project=$MY_PROJECT

[auth]
token=$AUTH_TOKEN

Any idea what I am missing here? Thanks in advance

**Comment by issaclam926** [comment]
same issues I got . want some help.

**Comment by radomeit** [comment]
I had the same issue. In my case it was cause my Sentry CLI always tried to connect to the sentry.io server instead of my self-hosted sentry server.
Please enter `sentry-cli info`. If it shows sentry.io as server instead of your local server, than that's the problem.
I fixed it by adding 
```
[defaults]
url=##yourlocalserver##
```
 in .sentryclirc.

**Comment by phatNfqAsia** [comment]
Update: it was due to connection issue in my machine, I tested the command on another device and it worked fine

**Comment by alexandervlpl** [comment]
This seems like a bug to me. If I logged into my own server using `--url`, the default behaviour should be to place that URL in `.sentryclirc` along with the auth token.

**Comment by YuraVolchak** [comment]
check the url you are using. In my case  I have Cloud based Sentry, so the url should be https://sentry.<xxx company>.com. in SAAS variant it has default value https://sentry.io.   so in your next.config. you should just add url:https://sentry.<xxx company>.com in sentry config section
