### ISSUE TITLE
Error in building for linux

### ISSUE THREAD

**Issue by maniskasyap** [getsentry/sentry-cli#854]
OS - macos mojave 10.14.6
make - GNU Make 3.81
cmake - cmake version 3.19.0-rc2
cc - Apple LLVM version 10.0.1 (clang-1001.0.46.4)
rustc - rustc 1.47.0 (18bf6b4f0 2020-10-07)
cargo - cargo 1.47.0 (f3c7e066a 2020-08-28)

When trying to build for target linux, with below command -

`cargo build --release --bins --target x86_64-unknown-linux-gnu`

I am getting an error related to libgit2

**error: failed to run custom build command for `libgit2-sys v0.12.7+1.0.0`**

**Comment by kamilogorek** [comment]
Can you provide full error message? You should be able to compile it with `x86_64-unknown-linux-musl` with no issues though.

**Comment by maniskasyap** [comment]
changing the target to `...-musl` worked
faced standard missing tools error, but [this](https://www.andrew-thorburn.com/cross-compiling-a-simple-rust-web-app/) article helped

thanks for your help
