### ISSUE TITLE
`sentry-cli releases list` command suddenly broken, returns empty

### ISSUE THREAD

**Issue by vdh** [getsentry/sentry-cli#855]
The `sentry-cli releases list` command has suddenly changed recently to return nothing, specifically the underlying `https://sentry.io/api/0/projects/{organization_slug}/{project_slug}/releases/` endpoint it uses now returns an empty array.

I can't find any information why this endpoint suddenly changed.

**Comment by untitaker** [comment]
Thanks @vdh for reporting, this is a regression on the server that we will fix today.
