### ISSUE TITLE
Binary caching does not respect cache setting

### ISSUE THREAD

**Issue by NickWer** [getsentry/sentry-cli#856]
Hi, 
I'm currently working on tuning our CI performance but I've run into an issue where sentry's `install` script is always downloading the binary to `~/.npm/` rather than the directory configured in my `.npmrc` or the directory specified when running `npm ci --cache myProjectCacheFolder`.  Because it's not installing to the correct cache folder, our runners can't pick it up, which means it gets redownloaded for each job (🙁)

I don't have this issue with any other package, as`~/.npm/` **only** has the `sentry-cli` folder (everything else is in my project's cache folder). I also added a little script to my package.json

```json
  scripts: {
    "print-env-vars": "printenv | grep npm_config_cache"
  }
```

and running the command outputs 

```
npm_config_cache=myProjectCacheFolder
```

Which means the setting is definitely correct at the "top leve", but perhaps not carried through into the install script's environment. If you have any ideas at all for how to resolve this, I'd be really appreciative, as I've been scratching my head on this one all day

**Comment by kamilogorek** [comment]
What CI are you using? Different services handle caches differently. I just verified it locally, and both scenarios (config option and --cache) work just fine - fetch first, use cached on 2nd run.

![image](https://user-images.githubusercontent.com/1523305/99246712-114b6280-2806-11eb-89fc-6c67a721d667.png)

![image](https://user-images.githubusercontent.com/1523305/99246703-0c86ae80-2806-11eb-83a8-a5bfb57446d2.png)

**Comment by NickWer** [comment]
We're using gitlab, but I'm able to reproduce the issue just on my mac with npm v6.10.3 and node v12.10.0
<img width="698" alt="Screen Shot 2020-11-16 at 9 28 32 AM" src="https://user-images.githubusercontent.com/3439382/99264260-3a5ff900-27ee-11eb-9970-aa4df13e3d1f.png">

At the end of this screenshot you can see that even though the npm cache has been placed inside the project directory (consistent with the env setting), sentry-cli's cache for the binary has been placed at `~/.npm/sentry-cli`

If we run `npm ci` again, it uses the cache and never fetches the binary. This is good, ‼but‼ if we delete `~/.npm`, which is **not** where the cache has been configured, it has to fetch the binary again to install, again indicating the binary  is saved where it shouldn't be.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/3439382/99264407-6a0f0100-27ee-11eb-86c4-386a340cdbef.png">

I would assume this behavior is because of [this line](https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js#L94) in the setup script, but I don't understand why `process.env.npm_config_cache` is unset at that point.

**Comment by NickWer** [comment]
Turns out it was an issue with `npm ci` dropping certain config settings from the environment. Upgrading npm to the latest version solved the issue :) You can read more [here](https://github.com/npm/cli/issues/1451#issuecomment-732427861)

**Comment by kamilogorek** [comment]
Good to know, thanks!
