### ISSUE TITLE
releases delete: not allowed on some releases

### ISSUE THREAD

**Issue by csonuryilmaz** [getsentry/sentry-cli#861]
Hi, when I try to delete a release I get "This release has health data and cannot be removed" error message.

Same release is also not allowed from UI. (_You can only delete releases if they have no issues or health data._)

Release has no issue but I think has health data no background. (?)

<img width="400" alt="release detail on Sentry UI" src="https://user-images.githubusercontent.com/7355362/99948417-7e24a680-2d8a-11eb-873c-7b7e8daec21f.png">

How can I delete these dummy releases from Sentry server? They have no value and are confusing on releases page.

Sentry Server Version: `20.10.1 78833d9`
Sentry CLI Version: `1.58.0`

**Comment by kamilogorek** [comment]
@csonuryilmaz can you mail me your organization and project name at kamil@sentry.io
I'll see what's going on and verify whether it's CLI issue or something else.

**Comment by csonuryilmaz** [comment]
@kamilogorek Although we're using on-premise version of Sentry (w/ docker), I've added you to our organization and project. 😊  Hope to hear good news... 🙏

**Comment by kamilogorek** [comment]
@csonuryilmaz so release removal is not possible once it's associated with any queryable data, however, if you bump the version to `20.11.x`, you'll be able to archive all dummy releases and they won't be seen in any queries or CLI commands. Cheers!

**Comment by csonuryilmaz** [comment]
> .. you'll be able to archive all dummy releases and they won't be seen in any queries or CLI commands.

👍 This behaviour solves my requirements, version bump seems good to me. Thanks.
