### ISSUE TITLE
my sourcemaps are not coming through! 

### ISSUE THREAD

**Issue by export-mike** [getsentry/sentry-cli#864]
This is really really hard to debug issues! we want our lovely sourcemaps back!

we are using react-native

our deps look like:

```
└─ react-native@0.63.2
└─ @sentry/react-native@1.3.9
└─ react-native-code-push@6.3.0
```

I have a theory that this is being broken by our nodejs-assets directory? which is a nodejs plugin
https://github.com/janeasystems/nodejs-mobile-react-native

```
├── android
├── android_splash
├── assets
├── bin
├── custom-icon-font
├── design
├── design-files
├── docs
├── e2e
├── ios
├── node_modules
├── nodejs-assets
├── patches
├── scripts
└── src
```

our index.js looks like:
```js
if (process.env.NODE_ENV === 'production') {
  Sentry.init({
    dsn:
      '1231312312',
    enableAutoSessionTracking: true,
    environment: Config.ENVIRONMENT,
  });

  Sentry.configureScope(scope => {
    scope.setContext({
      git_sha: Config.GIT_SHA,
    });
  });
  codePush
    .getUpdateMetadata()
    .then(update => {
      if (update) {
        const version = `${update.appVersion}-codepush:${update.label}`;
        Sentry.setRelease(version);
        crashlytics().setAttribute('version', version);
        Intercom.updateUser({
          custom_attributes: {
            appVersion: version,
          },
        });
      }
    })
    .catch(e => {
      Sentry.captureException(e);
    });
}
```

any ideas? anything else I can share that's useful?

**Comment by export-mike** [comment]
@tomWritesCode

**Comment by kamilogorek** [comment]
> any ideas? anything else I can share that's useful?

CLI debug output (`SENTRY_LOG_LEVEL=debug` and some explanation of how you upload the source maps in the first place would be great for sure. And a shareable link to any event that should be mapped but is not.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
