### ISSUE TITLE
Environment Variables not being picked up

### ISSUE THREAD

**Issue by danielbecker** [getsentry/sentry-cli#871]
I am trying to notify sentry of new releases in our build pipeline. However, it keeps failing with the error message `A project slug is required ` even though all variables necessary are present:

```
$ echo ${SENTRY_ORG}
sentry
$ sentry-cli releases new ${CI_COMMIT_TAG}
  DEBUG   2020-12-03 10:28:56.531199003 +00:00 sentry-cli version: 1.60.1, platform: "linux", architecture: "x86_64"
  INFO    2020-12-03 10:28:56.531314469 +00:00 sentry-cli was invoked with the following command line: "sentry-cli" "releases" "new" "sentryTest9"
error: A project slug is required
  DEBUG   2020-12-03 10:28:56.536028886 +00:00 client close; no transport to shut down  (from sentry)
```

**Comment by kamilogorek** [comment]
The error is asking for `SENTRY_PROJECT`, `--project` or `[defaults] project` to be present, which your logs indicate it is not. You can use `sentry-cli info` to see what values are used.

ref: https://docs.sentry.io/product/cli/configuration/#configuration-values

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
