### ISSUE TITLE
set-commits with local repository always includes 20 commits

### ISSUE THREAD

**Issue by akondas** [getsentry/sentry-cli#875]
Hi, when using sentry-cli on local repository (with `--auto` or `--local` flag) I always have 20 last commits included:
```
➜  my-app git:(master) sentry-cli releases set-commits $VERSION --local                                           
Could not find the previous commit. Creating a release with 20 commits.
Success! Set commits for release b729b247478320763aea7a49f1f49c5c5afcf1d3.
```

![Screenshot from 2020-12-16 10-31-16](https://user-images.githubusercontent.com/8239917/102334509-0879b800-3f8f-11eb-8075-726df1ffcad3.png)

Why is the previous commit never detected?
I tried to use the `--commit` flag but it does not work for local repositories (I have env vars with the current and previous commit).

**Comment by akondas** [comment]
While debugging I found such a call: 
```
  DEBUG   2020-12-16 11:14:37.104049449 +01:00 > GET /api/0/organizations/sentry/releases/09b31136d1bee4d52af979031cf97933c1c72573/previous-with-commits/ HTTP/1.1
  DEBUG   2020-12-16 11:14:37.231966323 +01:00 response status: 404
Could not find the previous commit. Creating a release with 20 commits.
```

But this release exist and previous also exist:
![Screenshot from 2020-12-16 11-17-50](https://user-images.githubusercontent.com/8239917/102335534-580cb380-3f90-11eb-8c1e-320a66f33e2e.png)

**Comment by akondas** [comment]
Ok, I suspect it's our sentry instance fault. We are currently using version `9.1.2` which did not have this endpoint implemented yet. I will do the upgrade and let me know if it helped.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
