### ISSUE TITLE
sentry-cli react-native appcenter: "Failed to load AppCenter deployment history"

### ISSUE THREAD

**Issue by Rafatcb** [getsentry/sentry-cli#881]
I'm following the [docs](https://docs.sentry.io/platforms/react-native/codepush/#making-releases) to upload the source maps after creating a release for React Native with CodePush but it never works.

Creating a release on CodePush:

```
appcenter codepush release-react -a org/app -d Production --sourcemap-output --output-dir ./build
```

Trying to upload source maps:

```
yarn run v1.22.4
$ cross-env SENTRY_PROPERTIES=./android/sentry.properties SENTRY_LOG_LEVEL=debug sentry-cli react-native appcenter org/app android ./build/CodePush --deployment Production --dist v6
  DEBUG   2020-12-30 11:46:11.875803300 -03:00 sentry-cli version: 1.61.0, platform: "windows", architecture: "x86_64"
  INFO    2020-12-30 11:46:11.876085900 -03:00 sentry-cli was invoked with the following command line: "C:\\Users\\rafae\\...\\node_modules\\@sentry\\cli\\sentry-cli.exe" "react-native" "appcenter" "org/app" "android" "./build/CodePush" "--deployment" "Production" "--dist" "v6"
  INFO    2020-12-30 11:46:11.876902600 -03:00 Issuing a command for Organization: sentryorg Project: sentryproject
> Fetching latest AppCenter deployment info
error: Failed to load AppCenter deployment history
  caused by:
  DEBUG   2020-12-30 11:46:12.001823200 -03:00 client close; no transport to shut down  (from sentry)
error Command failed with exit code 1.
```

Content of `./android/sentry.properties`:

```
defaults.url=https://sentry.io/
defaults.org=sentryorg
defaults.project=sentryproject
auth.token=token
```

My auth token has the following scopes, [as suggested here](https://docs.sentry.io/product/cli/configuration/):

- org:read
- project:read
- project:releases

I did see the issue #415, but it didn't help me because I'm already specifying the deployment with `--deployment`. What am I doing wrong?

PS: The release has been created in Sentry and I can confirm that there are no source maps.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by kopax-polyconseil** [comment]
@icecapp did you solve this error ?

**Comment by kamilogorek** [comment]
@kopax-polyconseil since `2.1.0` you should see the actual detailed error from AppCenter
