### ISSUE TITLE
Upload dsyms fails with EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by cannc4** [getsentry/sentry-cli#901]
Already a few issues about this. They are closed by some reason but we've been hitting this error on and off which feels kinda unstable. 

Any thoughts or plans to fix it for good? 

Thanks

**Comment by kamilogorek** [comment]
Ref: https://github.com/getsentry/sentry-cli/issues/374

**Comment by SergejLogis** [comment]
Today I have noticed that the most recent dSYM in Sentry is dated 2 months ago 😱 (we have only had a few releases yet).
Nothing has changed in the project setup or in the dSYMs upload script, and it was working just fine before. But currently, I always get a dreaded `EOF while parsing a value at line 1 column 0` error, no matter what I do or how I run the script. Note that the same error issues even when dSYMs folder parameter is missing...
Any suggestions or workaround? There is **no** other way to upload dSYMs to Sentry, and without dSYMs Sentry is pretty much useless to us 😞
Please help 🙏 
![sentry-cli-error](https://user-images.githubusercontent.com/32644729/108476214-747fe180-729a-11eb-9e35-23fcf12e935e.png)

**Comment by Tommecpe** [comment]
@kamilogorek still no news ?
I've got the same problem, and as said by @SergejLogis :
> There is no other way to upload dSYMs to Sentry, and without dSYMs Sentry is pretty much useless to us

**Comment by SergejLogis** [comment]
Uploads started to work few days after we first hit the issue, without any changes from our side. However, today we have released a new version and the issue resurfaced. 😕 Again, without any changes from our side...

**Comment by akshitzaveri** [comment]
The upload worked when I did "cd DSYM_FOLDER" and then used "./" in the sentry-cli command instead of the full path.

**Comment by arbitur** [comment]
Same problem and nothing works.

**Comment by kamilogorek** [comment]
I suggest upgrading to `1.64.0` which has a more descriptive error message and should make debugging easier. Cheers!
