### ISSUE TITLE
Sentry-cli inside docker

### ISSUE THREAD

**Issue by weidonglian** [getsentry/sentry-cli#902]
I am using the following command to install sentry-cli inside docker build. 
`curl -sL https://sentry.io/get-cli/ | bash && which sentry-cli && sentry-cli --version`. 
however, it complains that `sudo command not found`. 

I do not think it is a good pattern to put `sudo` command inside https://sentry.io/get-cli/ bash script. It is not portable, there is no guarantee the target platform has a sudo support.

**Comment by dubreuia** [comment]
Same issue, I've done this:

```
curl -SL --progress-bar https://downloads.sentry-cdn.com/sentry-cli/1.62.0/sentry-cli-Linux-x86_64 > sentry-cli
chmod u+x sentry-cli
./sentry-cli ...
```

**Comment by markthomas93** [comment]
@weidonglian - agreed. i've been using `npx` to run one off commands inside of a docker container
