### ISSUE TITLE
Docker + sentry-cli releases propose-version

### ISSUE THREAD

**Issue by leepowelldev** [getsentry/sentry-cli#907]
### Environment

How do you use Sentry?
Local development with docker
@sentry/webpack-plugin 1.14.0
@sentry/cli 1.62.0

### Steps to Reproduce

In my webpack build process I am using @sentry/webpack-plugin and have omitted the `version` property in my config to allow it to be fetched from HEAD. This works as expected when run on my local machine directly - however when this is executed inside a docker container I can an odd error.

Webpack config:
```
new SentryWebpackPlugin({
  include: './public/javascript',
  ignore: ['.gitignore'],
  dryRun: process.env.DEPLOY_ENV !== 'production',
}),
```

I can replicate this by attaching to the container and running the command manually via `./node_modules/.bin/sentry-cli releases propose-version`

### Expected Result

Returns HEAD id

### Actual Result

root@22f1c4ed8fd3:/home/node/app# ./node_modules/.bin/sentry-cli releases propose-version
/home/node/app/node_modules/@sentry/cli/sentry-cli: 1: /home/node/app/node_modules/@sentry/cli/sentry-cli: �������0
         �@�������0: not found
/home/node/app/node_modules/@sentry/cli/sentry-cli: 1: /home/node/app/node_modules/@sentry/cli/sentry-cli: Syntax error: word unexpected (expecting ")")

I've replicated this in a stand alone repo - it just needs bringing up and connecting to the container, then running the command

https://github.com/leepowelldev/sentry-docker

**Comment by skokalin** [comment]
I have the same issue

**Comment by kamilogorek** [comment]
```
�������0
�@�������0: not found
```

This is 99% issue with docker using a binary installed for different architecture than it's meant to use.
By mounting your local volume in docker container, it'll reuse same `node_modules/@sentry/cli/bin/sentry-cli` file. However, this file is different on different on different environments, see: https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js

To fix this, you need to perform `npm install`/`yarn` directly in the container, which will then fetch a correct binary for this environment.

Cheers!

**Comment by leepowelldev** [comment]
@kamilogorek - makes sense. Thanks for clarifying.
