### ISSUE TITLE
Add docs for how to use `sentry-cli` with `yarn dlx`

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-cli#909]
I was trying to get this work with `yarn dlx` (yarn2/berry), but I was using the outdated package name (`sentry-cli`). In order to work, you have to do this:

```
yarn dlx -p @sentry/cli sentry-cli <...>
```

**Comment by kamilogorek** [comment]
We got an access to https://www.npmjs.com/package/sentry-cli since then which should point people to right direction.
