### ISSUE TITLE
Did nothing. Release with this version (c27ecaf) does not exist.

### ISSUE THREAD

**Issue by wangh1998** [getsentry/sentry-cli#910]
sentry-cli releases -o orz -p pro delete 「c27ecaf」，version (c27ecaf) does not exist。 Vue Project。
![image](https://user-images.githubusercontent.com/46313540/108799086-64ce0900-75ca-11eb-912a-4366cdd35824.png)

**Comment by kamilogorek** [comment]
Is this issue still relevant?
