### ISSUE TITLE
Deploy options `started` and `finished` type inconsistency

### ISSUE THREAD

**Issue by andreiho** [getsentry/sentry-cli#912]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
JavaScript, @sentry/webpack-plugin@1.14.0

### Steps to Reproduce

1. Create a deploy with `started` and `finished` UNIX timestamps

### Expected Result

The docs specify UNIX timestamp for `started` and `finished`.

### Actual Result

It doesn't work with UNIX timestamp, but it works with ISO date string. This is the error:

```
ERROR in Sentry CLI Plugin: Command failed: /home/jenkins/workspace/face_feature_sentry-do-not-track/node_modules/@sentry/cli/sentry-cli releases deploys dev:feature-sentry-do-not-track new --env development --started 1614179954415 --finished 1614179954415
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object({"dateFinished": Array([String("Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].")]), "dateStarted": Array([String("Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].")])})
```

**Comment by kamilogorek** [comment]
It does work with unix timestamps, but it's using seconds, not milliseconds (which JS produces by default). See: https://github.com/getsentry/sentry-cli/pull/984#issuecomment-877432147
