### ISSUE TITLE
npm install Fails in AWS Graviton2

### ISSUE THREAD

**Issue by omaraltayyan** [getsentry/sentry-cli#913]
there's an issue when installing the latest sentry cli on ARM with a linux OS, the npm installation generates a malformed URL for downloading the sentry cli binary causing a 403 error

### Environment

Sentry Cli: 1.63.0

### Steps to Reproduce

1. install sentry_cli on aws graviton 2 using npm

### Expected Result

installs successfully using this URL for downloading the CLI

```
https://downloads.sentry-cdn.com/sentry-cli/1.63.0/sentry-cli-Linux-aarch64
```

### Actual Result

the npm installation uses a malformed URL, due to the architecture build not having the same name as the CLI's binary.

```
https://downloads.sentry-cdn.com/sentry-cli/1.63.0/sentry-cli-Linux-arm64
```

**Comment by kamilogorek** [comment]
Should be fixed with https://github.com/getsentry/sentry-cli/commit/11c0a6559bfa41bfa95d838d15b7701d2f3d6409
