### ISSUE TITLE
Security: don't use an install script to download the binary

### ISSUE THREAD

**Issue by mjroeleveld** [getsentry/sentry-cli#915]
The usage of an install script is [a vulnerability issue](https://www.nerdycode.com/prevent-npm-executing-scripts-security/).  It downloads an unsigned binary to the executing machine, which opens the way for potentially malicious code to be unintendedly downloaded. The NPM package should contain the binary such that it's there when installed and the install script can be omitted. This will make sure that an install of a locked version of the package will always result in the same artifact, which also helps with caching.

**Comment by kaiyoma** [comment]
We've also run into issues with the install script. The binary fails to download sometimes, which either causes our CI to fail during `yarn install` or causes our webpack build to fail with this:

```
ERROR in Sentry CLI Plugin: spawn .../node_modules/@sentry/cli/sentry-cli ENOENT
```

(It's a bit troubling how many npm packages connect to a non-npm URL directly and download mysterious things during package installation.)

**Comment by kaiyoma** [comment]
Another issue, if I'm reading `scripts/install.js` correctly, is that the download is not verified against a checksum. Why this is important: we're dealing with some network issues that are potentially causing corrupted/truncated downloads, but this sentry-cli install script isn't properly detecting those situations, leading to the error above (a missing file that should be there).

**Comment by sehcheese** [comment]
@kaiyoma We're having a similar issue with our CI where we get intermittent errors of

> ERROR in Sentry CLI Plugin: spawn .../node_modules/@sentry/cli/sentry-cli ENOENT

It does seem that the ideal would be a prebuilt binary, both from a security and convenience standpoint. In the meantime, how have you worked around the CI error?

**Comment by kaiyoma** [comment]
@sehcheese We ended up creating a local binary/library cache on one of our internal file servers and populating it with the versions that we use. Sentry provides a mechanism to specify a custom URL to the sentry-cli binary:

https://docs.sentry.io/product/cli/installation/#downloading-from-a-custom-source

In our CI, our package installation looks like this now:

```
SENTRYCLI_CDNURL="http://cache/sentry-cli" yarn install --frozen-lockfile
```

(where `cache` is the network name of our file server)

**Comment by lobsterkatie** [comment]
I've been looking into this, and I believe the reason we've gone for the download-in-postinstall-script approach is in order to be able to match the installed binary to the architecture on which it's running. 

It turns out `esbuild` had [the exact same problem](https://github.com/evanw/esbuild/issues/789), which they ended up solving using optional dependencies. If you read that whole thread, you'll see that there are pros and cons to this approach. The biggest one of those cons ([yarn](https://github.com/yarnpkg/berry/issues/3317) and [npm](https://github.com/npm/cli/issues/2707) both downloading every binary, for every platform) has been fixed in the latest versions of both (see [yarn's fix](https://github.com/yarnpkg/berry/pull/3575) and [npm's fix](https://github.com/npm/arborist/pull/231)), and so I think it's a worthwhile strategy to for us to think about pursuing.

(That said, in the interests of full disclosure, with the holidays coming up it's unlikely this will come up for consideration before the new year.)

**Comment by mjroeleveld** [comment]
This issue should remain open.

**Comment by kamilogorek** [comment]
Agree, just added the bot, so it went through everything :)

**Comment by kamilogorek** [comment]
I went through all the linked issues of other repositories, and I believe there is indeed not a single perfect solution for this problem.

The main issue is that this CLI is used across various other projects indirectly, be it Android, Xcode, Fastlane, Maven, Gradle to name a few. And only recent versions of npm/yarn are doing everything correctly, no noisy logs, no fetching of unnecessary platforms data etc.

Also migrating to `optionalDependencies` solution is making the whole releasing process quite more complex.
We'd need to release N packages (for every platform, 9 of them currently, more to come) every single time, update all GH actions, transform this rust repo into js monorepo, so on and so forth. And our internal registry would need to keep track of these additional releases, which is not ideal.

For now, I'd opt for adding checksum validation (security measure) and upgrading our install script to allow for a better and faster diagnosis of what went wrong and how to possibly fix the given problem (ux measure).

Checksum verification has been already added in the lastest version - https://github.com/getsentry/sentry-cli/pull/1123
And I'll work on adding more diagnostics for the install script next.

I'm as always open for feedback :)

**Comment by kamilogorek** [comment]
After adding https://github.com/getsentry/sentry-cli/pull/1129 it's now also possible to use the local binary, which is installed in any way users choose to. This, and checksum validation should be enough of an upgrade, for now, so I'm going to close this issue.
Again, if anyone has any feedback and ideas around improving this, feel free to ping me.
