### ISSUE TITLE
Windows "npm install sentry-cli-binary" Fails

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-cli#92]
OS: Windows 7 64-bit
npm Version: 4.6.1
sentry-cli-binary Version: 1.16.0

\> sentry-cli-binary@1.16.0 install ...\node_modules\sentry-cli-binary
\> node ./bin/install-sentry-cli

fetching sentry-cli-Windows-i686.exe ████████████████████ 100% 0.0s
Something went wrong!
{ Error: Command failed: ...\node_modules\sentry-cli-binary\bin\sentry-cli.exe --version

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 3221225595,
  signal: null,
  cmd: '...\\node_modules\\sentry-cli-binary\\bin\\sentry-cli.exe --version' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.16.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2017-06-29T22_00_47_627Z-debug.log

**Comment by mitsuhiko** [comment]
Any chance that there are spaces in the path?

**Comment by mitsuhiko** [comment]
In *theory* this is fixed? Closing until someone reopens it.

**Comment by HAMPLENI** [comment]
Thank you for your response!  :)

There are no spaces in the path that I am running the command from.

Here is the new error output:

OS: Windows 7 64-bit
npm Version: 4.6.1
sentry-cli-binary Version: 1.17.0

\> sentry-cli-binary@1.17.0 install ...\node_modules\sentry-cli-binary
\> node ./bin/install-sentry-cli

fetching sentry-cli-Windows-i686.exe ████████████████████ 100% 0.0s
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.17.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.17.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2017-07-17T17_20_11_503Z-debug.log

**Comment by mitsuhiko** [comment]
I will try this again on my windows machine now.

**Comment by StefanoCremona** [comment]
I've the same problem on my windows 10. If you run directly the sentry-cli-Windows-i686.exe you get the error:
The program can't start because VCRUNTIME140.dll is missing from your computer...
But it's actually on my computer, under c:\windows\system32

<img width="346" alt="sentry-cli" src="https://user-images.githubusercontent.com/12048577/28501217-327e089c-6fcf-11e7-8c67-6153e91dc515.png">

It seems a windows problem.

**Comment by mitsuhiko** [comment]
@StefanoCremona that is most likely because you do not have the 32bit bit version of that DLL on your machine.

**Comment by StefanoCremona** [comment]
@mitsuhiko thank you very much. Now everything works fine!!!

**Comment by HAMPLENI** [comment]
This issue is now resolved for me.  Thanks!  :)

**Comment by Shpadoinkle** [comment]
I am getting the same error here.  

I have a fresh install of windows, latest node and latest npm. 

`
> sentry-cli-binary@1.24.1 install C:\Users\Gibbs\Desktop\NewProject\nod
e_modules\sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Windows-i686.exe ████████████████████ 100% 0.0s
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.24.1 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gibbs\AppData\Roaming\npm-cache\_logs\2017-11-29T02_48_04_
761Z-debug.log
`

**Comment by BlindDespair** [comment]
> I've the same problem on my windows 10. If you run directly the sentry-cli-Windows-i686.exe you get the error: The program can't start because VCRUNTIME140.dll is missing from your computer... But it's actually on my computer, under c:\windows\system32
> 
> <img alt="sentry-cli" width="346" src="https://user-images.githubusercontent.com/12048577/28501217-327e089c-6fcf-11e7-8c67-6153e91dc515.png">
> 
> It seems a windows problem.

My colleague had the same. She had to install Visual Studio 2015 Package to resolve this problem. Now everything is working.
