### ISSUE TITLE
Information about --level does not list different options

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-cli#923]
I had to figure out if it was "warn" vs "warning" by trial and error. The documentation does have any info.

What are the valid values? I can submit a PR.

[Link to code](https://github.com/getsentry/sentry-cli/blob/762ff34376a380789b3de731764836d50c7e0106/src/commands/send_event.rs#L26-L32)

**Comment by kamilogorek** [comment]
I think that's it: https://github.com/getsentry/relay/blob/457062d3ed71f1dd00af253ff7b8b2bb8ea19b42/relay-general/src/protocol/types.rs#L635-L639
