### ISSUE TITLE
Hide env variables

### ISSUE THREAD

**Issue by jeffochoa** [getsentry/sentry-cli#924]
Is it possible to hide environment variables when using the `sentry-cli send-event` command?

I'm trying to send some events from a production environment but I don't want to expose some of the environment variables I have in there.

**Comment by kamilogorek** [comment]
```sh
--no-environ
    Do not send environment variables along
```

**Comment by jeffochoa** [comment]
Thanks @kamilogorek that was very helpful 👏

**Comment by montanaflynn** [comment]
This should be the default, when following the relay setup guide:

`sentry-cli send-event -m 'A test event'`

Then when checking sentry I was really surprised to see it had sent all my environment variables to sentry!
