### ISSUE TITLE
Error on block-scoped-declaration 'let x = y'

### ISSUE THREAD

**Issue by mikelambert** [getsentry/sentry-cli#93]
I recently integrated Sentry into my iOS build. I believe it's worked correctly sometimes, but recently I've been getting an error when building:
```
    /bin/sh -c /path/my-project-dindgfismjopvgeevyvzshhpqwia/Build/Intermediates/my-project.build/Debug-iphonesimulator/my-project.build/Script-00DD1BFF1BD5951E006B06BC.sh

/path/my-project/node_modules/sentry-cli-binary/index.js:5
let path = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/path/my-project/node_modules/sentry-cli-binary/bin/sentry-cli:5:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
Command /bin/sh failed with exit code 1
```

Running with node v7.10.0, not sure if that's relevant.

Changing s/let/var/ seems to fix the problem for me.

**Comment by buesing** [comment]
Same problem here, running node v7.5.0. It seems to be using the wrong node version (have multiple installed with nvm but 7 is the default setting). I don't really want to change anything in node_modules. Any other ideas?

**Comment by mitsuhiko** [comment]
This should be fixed in the next release. We made it ES5 compatible.

**Comment by mblair** [comment]
@mitsuhiko I'm still hitting this issue with 1.18.0, and [https://github.com/getsentry/sentry-cli/blob/master/index.js#L5](this) still says `let`. Is there something I'm missing?

**Comment by mitsuhiko** [comment]
You are right. Wonder why this was not fixed now. Will fix this in the next release.
