### ISSUE TITLE
sentry-cli always fails by returning code 1

### ISSUE THREAD

**Issue by mateuszkwiecinski** [getsentry/sentry-cli#930]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Saas

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
linux version installed via `curl -sL https://sentry.io/get-cli/ | bash` + macos version installed via brew

### Steps to Reproduce

1. What
2. you
3. did.

Run `sentry-cli` or `sentry-cli info` on a authorized client or `sentry-cli --auth-token (...) info` on non authorized.

### Expected Result
To have a successful command result 

### Actual Result
each mentioned command fails, returns code 1, despite each one does what is is expected. `sentry-cli` prints help and fails, `sentry-cli info` prints info about token and its access
![image](https://user-images.githubusercontent.com/36954793/112511533-cb457300-8d92-11eb-8e36-9043d73a22f1.png)

There is no error message, so I assume I did something wrong and I still have `sentry-cli` missconfigured. Did I do anything wrong?

**Comment by kamilogorek** [comment]
`sentry-cli help` always returns `0` from what I just checked. `sentry-cli info` will return `0` only if all the necessary data to perform a request is in place. Namely project, organization, and valid token. Otherwise, it'll produce non-zero exit codel

![image](https://user-images.githubusercontent.com/1523305/114012578-c985b000-9866-11eb-8fe4-f09ab9e4fd07.png)

Cheers!

**Comment by lwasyl** [comment]
I'm slightly confused about how the authentication works, then. I have a valid auth token that I can use to upload deobfuscation mappings. How can I verify that it's valid, using sentry-cli?

<img width="363" alt="image" src="https://user-images.githubusercontent.com/3951580/114014822-50d42300-9869-11eb-9d35-8f70f59145a7.png">

**Comment by kamilogorek** [comment]
That's actually a valid question. There's no specific command to do that, but you can fake org/proj easily with env vars.

```
SENTRY_ORG="" SENTRY_PROJECT="" sentry-cli --auth-token <my-token> info
```

This will produce `0` only if the token is valid.
