### ISSUE TITLE
sentry-cli  asks to update sentry-cli despite using the most recent version

### ISSUE THREAD

**Issue by mateuszkwiecinski** [getsentry/sentry-cli#931]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Saas

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
The one installed via brew on MacOS

### Steps to Reproduce

1. What
2. you
3. did.

Run any `sentry-cli` command not resulting in showing help message

### Expected Result

I'd expect not to see update warning when using most recent version.

### Actual Result
I do see: `run brew upgrade sentry-cli to update` 
![image](https://user-images.githubusercontent.com/36954793/112512693-e4025880-8d93-11eb-86af-a210c3ed18c8.png)

According to Github 1.63.1 is the most recent version: https://github.com/getsentry/sentry-cli/releases/tag/1.63.1

**Comment by kamilogorek** [comment]
Already fixed in https://github.com/getsentry/sentry-cli/commit/74e347ccc7576793cbb4ad8124d7480b48da2ec4 awaiting a release. Cheers!
