### ISSUE TITLE
Cannot run "releases files" with release name starting with "upload..."

### ISSUE THREAD

**Issue by jonpinto25** [getsentry/sentry-cli#935]
### Environment

How do you use Sentry?
sentry-cli

Which SDK and version?
1.63.2

### Steps to Reproduce

run `sentry-cli releases files VERSION upload-sourcemaps /path/to/sourcemaps` with `VERSION == "upload-test"`

### Expected Result

All should work as expected

### Actual Result

The following error appeared:
```
error: The subcommand 'upload-test' wasn't recognized
        Did you mean 'upload'?

If you believe you received this message in error, try re-running with 'sentry-cli releases files -- upload-test'

USAGE:
    sentry-cli releases files <VERSION> <SUBCOMMAND>
```

**Comment by kamilogorek** [comment]
Unfortunately, it's a known issue that's blocked by a `clap` crate. Should be fixed in v3, which we still await for, as it's currently in beta.
I'll close this one to not duplicate the issues - https://github.com/getsentry/sentry-cli/issues/686
