### ISSUE TITLE
error: project not found 

### ISSUE THREAD

**Issue by coder-dongjiayi** [getsentry/sentry-cli#936]
sentry-cli version:1.63.1
setp1: 
sentry-cli  --url https://sentry.blingabc.com  --log-level trace --auth-token mytoken upload-dif --org sentry --project student_app_native /Users/djy/Desktop/main.dSYM

execute result as shown in the following figure
image1. [https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406171830.jpg](https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406171830.jpg)
image2. [https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/2021040617211222.jpg](https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/2021040617211222.jpg)
image3. [https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406172313.jpg](https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406172313.jpg)

so . why https changed http in image3? service response 301 error: project not found

**Comment by coder-dongjiayi** [comment]
My request [https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406183253.jpg](url)
why https://xxxxx changed http://xxxxxx

**Comment by coder-dongjiayi** [comment]
My request [https://github.com/coder-dongjiayi/ABCMediaPlay/blob/main/20210406183253.jpg](url)
why https://xxxxx changed http://xxxxxx

**Comment by coder-dongjiayi** [comment]
@kamilogorek  thank you very much，I think it can help me solve the problem。but why not use location field request upload interface when service response  301 or 302.

**Comment by kamilogorek** [comment]
It could be one option, however it'd mask the original configuration issue, which may be fine now, but detrimental in the future when we introduce new features.
