### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by xingxinglail** [getsentry/sentry-cli#939]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

npm install 
### Expected Result

What you thought would happen.

### Actual Result
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.64.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.64.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kamilogorek** [comment]
Please create a reasonable issue.
