### ISSUE TITLE
Error: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by nerdmed** [getsentry/sentry-cli#94]
Dear Team,

i am having a lot of trouble using sentry with code-push in react-native. I keep on getting the following log:

```
sentry-cli --auth-token 1231231*****131231 react-native codepush my-app ios build/ios \
    --deployment Staging \
    --org myOrg \
    --project myProject

> Fetching latest code-push package info
error: EOF while parsing a value at line 1 column 0
```

I have tried to pass `--log-level=debug` nothing logged.
`sentry-cli info` looks good and also prints out the debug log like this:

```
[INFO] sentry_cli::api request GET https://sentry.io/api/0/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api > GET /api/0/ HTTP/1.1
[INFO] sentry_cli::api > Host: sentry.io
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.16.0
[INFO] sentry_cli::api > Authorization: Bearer  *******
[INFO] sentry_cli::api < HTTP/1.1 200 OK
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Wed, 05 Jul 2017 17:39:49 GMT
[INFO] sentry_cli::api < Content-Type: application/json
[INFO] sentry_cli::api < Content-Length: 825
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: GET, HEAD, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-d6992418
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 200
```

Any idea whats going wrong?

**Comment by nerdmed** [comment]
@mitsuhiko please help. We are paying for this product but we cant use it because of this issue. Or is there someone else i should contact?

**Comment by mitsuhiko** [comment]
@nerdmed can you verify that your project name and organization name matches the slug? (the parts in the url). If your project is called "FoO Bar" the slug is most likely `foo-bar`.

**Comment by mitsuhiko** [comment]
Actually looking at this more, it might be that the request to codepush is failing. Can you run this command and paste the output?

```
code-push deployment ls my-app --format json
```

**Comment by csyo** [comment]
I have the same issue but I'm not using `codepush`. The same error message shows only when I'm doing a Release build on CI machine. (It works fine on my own machine...)

**Comment by mitsuhiko** [comment]
@csyo can you run it with debug logging and share the log output? This is most likely a different issue.

**Comment by nerdmed** [comment]
ironically i just used the exact same command on the exact same machine and the error disappeared some days ago. So i can not further debug this issue. Maybe you guys fixed something server-side?

**Comment by mitsuhiko** [comment]
@nerdmed i'm in discussions with @mattrobenolt about an issue we currently have where large uploads cause server errors. See #89 for a bit of that conversation.

However my guess in this case is that we fail parsing the output of the `code-push` command instead which would be an unrelated issue. I'm keeping this issue open for now because there is a good chance we are not resilient enough for code-push failures.

In particular I know that if code-push fails for some reason it produces non json output we fail to parse.

**Comment by mitsuhiko** [comment]
Actually linked against the wrong issue. #86 is the one I was referring to.

**Comment by mitsuhiko** [comment]
Totally not closed. Wrong commit message.

**Comment by patrikqvarnstrom** [comment]
I'm having this same issue with this command: 

```Batch 1 - Found 41 debug symbol files. Checking for missing symbols on server ```
```error: bad json: EOF while parsing a value at line 1 column 0```

**Comment by mitsuhiko** [comment]
@patrikqvarnstrom please run the command with `--log-level=debug` and paste the output.

**Comment by patrikqvarnstrom** [comment]
```
[INFO] sentry_cli::api > Host: myurl.com
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.18.0
[INFO] sentry_cli::api > Authorization: Bearer ******
[INFO] sentry_cli::api < HTTP/1.1 302 FOUND
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Thu, 17 Aug 2017 10:26:49 GMT
[INFO] sentry_cli::api < Content-Type: text/html; charset=utf-8
[INFO] sentry_cli::api < Content-Length: 0
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Location: https://myurl.com/auth/login/
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < Set-Cookie: sentrysid="***"; expires=Thu, 31-Aug-2017 10:26:49 GMT; httponly; Max-Age=1209600; Path=/
[INFO] sentry_cli::api response: 302
[INFO] sentry_cli::api body:
```

**Comment by mitsuhiko** [comment]
@patrikqvarnstrom is this for self hosted sentry?

**Comment by patrikqvarnstrom** [comment]
Yes precisely, I ran the ```export SENTRY_URL=https://myurl.com``` command.

**Comment by mitsuhiko** [comment]
This looks to be a different issue. Most likely your version of sentry does not support cocoa. Are you running latest?

**Comment by patrikqvarnstrom** [comment]
Im using 3.4.3, and was following this documentation: https://docs.sentry.io/clients/cocoa/dsym/#dsym-without-bitcode

**Comment by mitsuhiko** [comment]
Since you are exporting `SENTRY_URL` i assume you are not using sentry.io. So then the question is the version of your sentry installation. Most likely it is too old.

**Comment by patrikqvarnstrom** [comment]
Thanks for your help, much appreciated.

**Comment by mitsuhiko** [comment]
I'm closing this because I cannot reproduce this. If it still happens for people please let me know and file a new issue.

**Comment by mikemliu** [comment]
I'm getting this error consistently using subcommand upload-dsym. Came here because fastlane plugin wasn't working throwing the above EOF error. ...help

--log-level TRACE outputs nothing

```
sentry-cli --log-level TRACE  --auth-token *** upload-dsym --org *** --project *** ./fastlane/bcsymbols/***.dSYM.zip
```

with fastlane
```
[16:55:32]: Login successful
[16:55:32]: Looking for latest version...
[16:55:35]: Looking for dSYM files for ***
[16:55:37]: 🔑  Successfully downloaded dSYM file for *** to './fastlane/bcsymbols/***.dSYM.zip'
[16:55:37]: --------------------------------
[16:55:37]: --- Step: sentry_upload_dsym ---
[16:55:37]: --------------------------------
[16:55:37]: sentry-cli 1.35.4 installed!
[16:55:37]: Starting sentry-cli...
[16:55:37]: error: EOF while parsing a value at line 1 column 0
+------------------+--------------------------------------+
|                      Lane Context                       |
+------------------+--------------------------------------+
| DEFAULT_PLATFORM | ios                                  |
| PLATFORM_NAME    | ios                                  |
| LANE_NAME        | ios upload_symbols                   |
| DSYM_PATHS       | ["/Users/***.dSYM.zip  |
|                  | "]                                   |
+------------------+--------------------------------------+
[16:55:37]: Error while calling Sentry CLI

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | download_dsyms     | 11          |
| 💥   | sentry_upload_dsym | 0           |
+------+--------------------+-------------+

[16:55:37]: fastlane finished with errors

[!] Error while calling Sentry CLI
```

**Comment by skizzo** [comment]
I'm getting this exact same error, been trying for a week to solve it, without success. Please see https://github.com/getsentry/react-native-sentry/issues/79#issuecomment-493004423

**Comment by developersHomefriend** [comment]
downgrade to react-native-sentry 0.39.1 solved my issue
