### ISSUE TITLE
Try to remove https://www.npmjs.com/package/sentry-cli

### ISSUE THREAD

**Issue by twogood** [getsentry/sentry-cli#943]
Hi,

I was a bit sloppy and did an `npm install sentry-cli` instead of `npm install @sentry/cli`. Since the sentry-cli npm package is 4 years old and does not even have a github link, maybe it would be OK for the author to remove it from npm and prevent others from doing my mistake?

**Comment by kamilogorek** [comment]
Hey, I reached out to the author, let's see :)
