### ISSUE TITLE
set-commits fails with "error: A project slug is required"

### ISSUE THREAD

**Issue by paulcbetts** [getsentry/sentry-cli#95]
Using sentry-cli 1.16.0 on Windows 10 CU, any variant of set-commits seems to fail:

```sh
sentry-cli releases set-commits --commit "paulcbetts/PeachApp@0.2.0" 0.2.0.0
error: A project slug is required
```

```sh
sentry-cli releases set-commits --auto 0.2.0.0
error: A project slug is required
```

**Comment by dcramer** [comment]
Not at a computer right now to check the docs but this would mean you're not configuring the project(s) for a release. Does the CLI provide any usable usage help for that command?

**Comment by paulcbetts** [comment]
There's no parameter to set the project, no

**Comment by mitsuhiko** [comment]
Currently you need to add the project slug to `set-commits` but that was not intended. I fixed that now. Now you only need to provide the project to `set-commits` in case a release has not been created before. This will go out in the next release.
