### ISSUE TITLE
release set-commits: does not resolve abbreviated Git hash properly

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry-cli#953]
When providing an abbreviated commit hash ("b314d65") it will be padded with zeros, instead of using the resolved/non-abbreviated commit hash:

```
 % sentry-cli releases set-commits project@a5ff2c3984e4831c05a77b7627ad53c07d6da47c --log-level debug --commit 'org/project@b314d65'
  DEBUG   2021-04-30 12:59:17.399546702 +02:00 sentry-cli version: 1.64.1, platform: "linux", architecture: "x86_64"
…
  INFO    2021-04-30 12:59:18.282480785 +02:00 Resolving b314d65000000000000000000000000000000000 (org/project@b314d65)
  INFO    2021-04-30 12:59:18.282524599 +02:00   -> found matching revision b314d65000000000000000000000000000000000
+-------------------+--------------+
| Repository        | Revision     |
+-------------------+--------------+
| org/project | b314d6500000 |
+-------------------+--------------+
  DEBUG   2021-04-30 12:59:18.283679475 +02:00 request PUT https://sentry.io/api/0/organizations/org-XX/releases/project@a5ff2c3984e4831c05a77b7627ad53c07d6da47c/
  DEBUG   2021-04-30 12:59:18.283734491 +02:00 using token authentication
  DEBUG   2021-04-30 12:59:18.283773052 +02:00 json body: {"refs":[{"repository":"org/project","commit":"b314d65000000000000000000000000000000000","previousCommit":null}]}
```

While the call itself is successful then, it will not update the commits for the release apparently - likely because it notices that something is off in the backend then only!  (note that it cannot be listed through sentry-cli apparently: https://github.com/getsentry/sentry-cli/issues/954)

(I've noticed this when trying to assign commits manually to a release while investigating into https://github.com/getsentry/action-release/issues/54)

**Comment by kamilogorek** [comment]
This is currently expected behavior per https://docs.sentry.io/product/cli/releases/#sentry-cli-commit-integration

> Note that you need to refer to releases you need to use the actual full commit SHA. If you want to refer to tags or references (like HEAD), the repository needs to be checked out and reachable from the path where you invoke sentry-cli.

---

Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
