### ISSUE TITLE
List commits for a release

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry-cli#954]
You cannot list the commits set via `sentry-cli releases set-commits` using `sentry-cli`, but they are available on the REST API, e.g. https://sentry.io/api/0/projects/org-XX/project/releases/project%40a5ff2c3984e4831c05a77b7627ad53c07d6da47c/commits/?project=XXX&per_page=40&repo_name=org%2Fproject

**Comment by imsamurai** [comment]
Yes, i think there is issue https://github.com/getsentry/sentry-cli/blob/master/src/api.rs#L879 no such route previous-with-commits (even in api docs, only https://docs.sentry.io/api/releases/list-an-organization-releases-commits/)

**Comment by blueyed** [comment]
@imsamurai 
Great find.  (permalink: https://github.com/getsentry/sentry-cli/blob/0426c5ceb6e66c84b7fce0da6541c07f3fe6c210/src/api.rs#L879)

Have you tried the API endpoint though?  (it might be just not documented maybe)

**Comment by imsamurai** [comment]
Yes, 404

**Comment by blueyed** [comment]
Just for reference, the permalink to the possibly broken `get_previous_release_with_commits` method: https://github.com/getsentry/sentry-cli/blob/0426c5ceb6e66c84b7fce0da6541c07f3fe6c210/src/api.rs#L879

I do not think it is really relevant to the original issue, which is about the missing feature of getting commits of a release, where the endpoint would be `"/organizations/{}/releases/{}/commits/"` then.

Maybe it is worth investigating/fixing the issue @imsamurai found, but that should be done in a separate issue then probably.
