### ISSUE TITLE
Command should succeed in case previous release commit was not found

### ISSUE THREAD

**Issue by rreckonerr** [getsentry/sentry-cli#956]
### Environment

I'm using an ember deployment addon that uses JS @senty/cli v1.41.0 under the hood and I've noticed that [if the previous release commit wasn't found](https://github.com/Exelord/ember-cli-deploy-sentry-cli/issues/10) the build pipeline fails with
```zsh
Error: Command failed: node_modules/.bin/sentry-cli  --auth-token XXX releases --org XXX --project XXX set-commits --auto XXX@XXX+XXX
error: Could not find the SHA of the previous release in the git history. Increase your git clone depth.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

Looking through your repo I've noticed that other users are facing the same issues but there's no viable solution to the problem.

- Archiving releases that contain non-existing commits is not an option, since in some cases releases are gradually delivered to the users.
- `"my-repo@from..to"` makes no sense if the release commit is gone for good.

### Steps to Reproduce

1. Add a fixup commit
2. Deploy
3. Squash
4. Deploy

### Expected Result

I expect the command to succeed even in the case of missing the previous commit.

### Actual Result

An error is thrown

### Linked issues
- https://github.com/getsentry/sentry-cli/issues/792
- https://github.com/getsentry/sentry-cli/issues/945
- https://github.com/Exelord/ember-cli-deploy-sentry-cli/issues/10

**Comment by drjayvee** [comment]
Our CD is also broken by this issue I believe. It would be nice if there were some way to "restart" the change list, or of course `--ignore-previous` or similar.

**Comment by drjayvee** [comment]
To add insult to injury, I can't seem to manually set of clear commits for past releases.

For example:
```
$ sentry-cli releases set-commits --clear 493899324
Clearing commits for release.
```
And yet when I Ctrl-F5 that release's web page, it's still showing releases.

Maybe I should create a separate issue for this, but then maybe it's not working because of this issue.

**Comment by kamilogorek** [comment]
@drjayvee thanks for letting us know regarding `--clear` issue. Someone will take care of it, and I'll let you know once it's fixed.

**Comment by rreckonerr** [comment]
Hi @kamilogorek!
And what about the issue itself?

**Comment by rreckonerr** [comment]
Thanks a lot!

**Comment by drummerjolev** [comment]
Can someone help with https://github.com/getsentry/action-release/issues/59 and https://github.com/getsentry/action-release/issues/41 ?
