### ISSUE TITLE
xcode env node issue

### ISSUE THREAD

**Issue by balajivenkatesh** [getsentry/sentry-cli#96]
../node_modules/sentry-cli-binary/bin/sentry-cli react-native xcode - which is part of Bundle React Native Code And Images fails with "env: node: No such file or directory". This is because my node is at a different location than the usual /usr/bin location?
Is there a way to specify my node location through a variable which the sentry-cli script will pick up and use?
Thanks!

**Comment by mitsuhiko** [comment]
Yes. We do the same thing as react-native here and let you override the node env path. Just export `NODE_BINARY=/path/to/node` before.
