### ISSUE TITLE
Second argument for `set-commits` is treated as release version (even if it's a flag)

### ISSUE THREAD

**Issue by rreckonerr** [getsentry/sentry-cli#964]
Since @sentry/cli v1.65.0 support for `--ignore-missing` flag was added for `set-commits` but it doesn't seem to work the way I expect it to.

### Examples

Flags passed **before** release name will create a release called `"--ignore-missing"`
```zsh
sentry-cli  --auth-token XXX releases --org XXX --project XXX set-commits --auto --ignore-missing XXX@XXX+XXX
```

-----

Flags passed **after** release name will create a proper release version
```zsh
sentry-cli  --auth-token XXX releases --org XXX --project XXX set-commits XXX@XXX+XXX --auto --ignore-missing
```

### Expected behavior
It should be possible to pass any number of flags before the release version while using `set-commits`

Introduced in https://github.com/getsentry/sentry-cli/pull/963

**Comment by kamilogorek** [comment]
Thanks for the report, it was a mistake on my side. Fixed in https://github.com/getsentry/sentry-cli/pull/965
