### ISSUE TITLE
OpenSSL error when release files with Docker image  getsentry/sentry-cli

### ISSUE THREAD

**Issue by kongkx** [getsentry/sentry-cli#969]
### Environment

Sentry SaaS (sentry.io)

Which SDK and version?

Docker image `getsentry/sentry-cli@sha256:12c2fec854f2eee9cc9640d0b9ca138a8cb01b46ab67884826ec6e26b87a8117`

### Steps to Reproduce

gitlab ci task upload assets

```
 sentry-cli releases files ...
```

### Actual Result

```
error: API request failed
  caused by: [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to sentry.io:443 )
```

**Comment by kamilogorek** [comment]
It seems like a something that happens inside the curl itself, and there's most likely not much we can do here.
You can first verify if disabling SSL check will actually make a difference and then think about the next step. See `http.verify_ssl` and `http.check_ssl_revoke` options: https://docs.sentry.io/product/cli/configuration/

**Comment by xiyangjianltianxia** [comment]
我也遇到了这个问题，请问解决了吗 @空心

**Comment by kongkx** [comment]
It seems that sentry.io has been blocked in chia mainland. A proxy is required.

**Comment by kamilogorek** [comment]
Thanks for letting us know. Proxy can be configured using common proxy env variables, or using properties file - https://docs.sentry.io/product/cli/configuration/
I'll let myself close this issue to keep it clean.
