### ISSUE TITLE
Cannot upgrade CLI to latest version (1.65.0)

### ISSUE THREAD

**Issue by drjayvee** [getsentry/sentry-cli#972]
I'm using Sentry 1.64.* and wish to upgrade to 1.65.0, which came out more than a week ago.

### Steps to Reproduce

1. `sentry-cli update`

### Actual Result
`1.64.2` is seen as latest version.

### Additional info

If I `sentry-cli update --log-level debug`, I can see the CLI making a request to https://release-registry.services.sentry.io/apps/sentry-cli/latest, which does indeed list 1.64.2 as the latest.

**Comment by kamilogorek** [comment]
Sorry about that. Fixed in `1.66.0`.
