### ISSUE TITLE
Invalid token: API request failed

### ISSUE THREAD

**Issue by xiyangjianltianxia** [getsentry/sentry-cli#977]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
JavaScript 5.11.0

### Steps to Reproduce

1. sentry-cli login
2. enter your token: afd532d75fb549feb5a9a38bee72381cc0154322f00e443db35c7211xxxxxx

### Expected Result
login success

What you thought would happen.

### Actual Result
Invalid token: API request failed

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by xiyangjianltianxia** [comment]
-> center git:(test-xhl060802) ✗ sentry-cli releases new 'center-2.0.0' --log-level=DEBUG
  INFO    2021-06-08 18:11:05.929712 +08:00 Loaded config from /Users/xiaohl/Documents/Project/center/.sentryclirc
  DEBUG   2021-06-08 18:11:05.930427 +08:00 sentry-cli version: 1.66.0, platform: "darwin", architecture: "x86_64"
  INFO    2021-06-08 18:11:05.930444 +08:00 sentry-cli was invoked with the following command line: "/Users/xiaohl/.nvm/versions/node/v14.15.0/lib/node_modules/@sentry/cli/sentry-cli" "releases" "new" "center-2.0.0" "--log-level=DEBUG"
  DEBUG   2021-06-08 18:11:05.930899 +08:00 request POST https://sentry.io/api/0/projects/ivydad/center/releases/
  DEBUG   2021-06-08 18:11:05.930926 +08:00 using token authentication
  DEBUG   2021-06-08 18:11:05.930952 +08:00 json body: {"version":"center-2.0.0","projects":["center"],"dateStarted":"2021-06-08T10:11:05.930875Z"}
  DEBUG   2021-06-08 18:11:05.930964 +08:00 retry number 0, max retries: 0
error: API request failed
  caused by: [35] SSL connect error (Server aborted the SSL handshake)
  DEBUG   2021-06-08 18:11:08.036451 +08:00 client close; no transport to shut down  (from sentry)




and 
.sentryclirc
[log]
level=debug

[auth]
token=xxxxx

[http]
verify_ssl=false
check_ssl_revoke=false

[defaults]
url=https://sentry.io
project=center
org=ivydad

**Comment by kamilogorek** [comment]
See: https://github.com/getsentry/sentry-cli/issues/969#issuecomment-857562749

**Comment by St-coder** [comment]
兄弟，国内 能上传sourcemap 吗？
