### ISSUE TITLE
upload-dif should error in case a path is provided and doesn't exist

### ISSUE THREAD

**Issue by danra** [getsentry/sentry-cli#978]
My Windows CI runs `sentry-cli upload-dif`, and it silently broke recently when one of the two `.pdb` files I was trying to upload was moved to a a different location; the missing file was silently ignored, and only the other file was uploaded.

I suggest `upload-dif` errors out in case a non-existing path is provided to it. Probably best behind a flag.

**Comment by kamilogorek** [comment]
`upload-dif` accept paths as directories to recursively search for debug files or inside found zip archives. If a direct path is provided, it will automatically go up to the parent directory.

If you want to verify that a specific debug file is present and usable, you can use `sentry-cli difutil check <path>` which will exit with `0` if file was found and is valid, or `1` if not.
