### ISSUE TITLE
On `finalize` project slug required, unable to pass as argument

### ISSUE THREAD

**Issue by reganjohnson** [getsentry/sentry-cli#98]
Latest version on Brew.

I do not have a project=projectname in my `.sentryclirc` file. When placing a project name in this file, the following scenario works. I am working with multiple projects which share a deploy and codebase, so I need to create separate releases for them.

For this sequence...
```
sentry-cli releases new "${PROJECT}" -p "projectname"
sentry-cli releases set-commits "${PROJECT}" --auto
sentry-cli releases finalize "${PROJECT}"
sentry-cli releases deploys "${PROJECT}" new -e "Production"
```

I receive the error `error: A project slug is required` on the `finalize` command.

When I adjust the command to include `-p "projectname"`... `sentry-cli releases finalize "${PROJECT}" -p "projectname"`... I receive the error `error: Found argument '-p' which wasn't expected, or isn't valid in this context`.

**Comment by mitsuhiko** [comment]
Thanks for the report. Will be fixed in the next release.
