### ISSUE TITLE
Permission issue with sentry-cli on docker

### ISSUE THREAD

**Issue by mercs600** [getsentry/sentry-cli#983]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
both

Which SDK and version?
```json
 "@sentry/browser": "^6.2.5",    "@sentry/integrations": "^6.2.5",    "@sentry/node": "^6.2.5",    "@sentry/webpack-plugin": "^1.15.0",
```

### Steps to Reproduce

Just install these packages by yarn on docker. 
One of these install sentry-cli.
Error occurred in scripts/install.js 

We have tried to install it as global package, but no luck. 

### Expected Result

Any errors with permission.
Why do you want to install in root directory ? Why not on current user level ? 

### Actual Result

```bash
error /app/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /app/node_modules/@sentry/cli
Output:
info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.66.0/sentry-cli-Linux-x86_64
Error: EACCES: permission denied, mkdir '/.npm'
```

**Comment by kamilogorek** [comment]
Installation directory is chosen based on npm configuration and fallbacks to homedir if necessary. You can change this with `npm_config_cache` env variable - https://github.com/getsentry/sentry-cli/blob/master/scripts/install.js#L93-L100

**Comment by mercs600** [comment]
@kamilogorek I see, but
```bash
docker run -e npm_config_cache="/yarn" ${CONTAINER_BUILD} yarn --pure-lockfile --prefer-offline --cache-folder="/yarn"
```

why can't we use one parameter specific for yarn `--cache-folder` - I supposed it should be equivalent

**Comment by kamilogorek** [comment]
Yarn supports env variables as well, and I'm more than happy to accept a PR that will add it as one of options :)
https://classic.yarnpkg.com/en/docs/cli/cache/#toc-change-the-cache-path-for-yarn
