### ISSUE TITLE
error: http error: generic error (400)

### ISSUE THREAD

**Issue by luckydonald** [getsentry/sentry-cli#99]
For some reason it doesn't work.

Command: 
```sh
$ sentry-cli releases new -p my-project
error: http error: generic error (400)
```

Mac OSX, `10.9.5`
sentry-cli `1.17.0`

**Comment by mitsuhiko** [comment]
Can you run this with debug output? (`--log-level=debug`) This is otherwise impossible to debug.

**Comment by mitsuhiko** [comment]
I'm going to close this for inactivity.

**Comment by ishitatsuyuki** [comment]
Hmm, also got it in CI. Let me leave debug on for a while and see if it happens it again.

**Comment by skizzo** [comment]
How did you solve this issue? Happens to me too.

**Comment by mitsuhiko** [comment]
@skizzo please open another issue for this with debug output shown.
