### ISSUE TITLE
Always prefixes with ~/public/

### ISSUE THREAD

**Issue by senky** [getsentry/sentry-cli#991]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

1. Create a directory (let's name it `assets`) and then subdirectory `build`
2. Add CSS/JS files into `build` folder (or subfolders).
3. Run this (we run in in CI):
```
cd assets
export SENTRY_AUTH_TOKEN=...
export SENTRY_ORG=...
curl -sL https://sentry.io/get-cli/ | bash
sentry-cli releases new -p xxx 1.0.0
sentry-cli releases -p xxx files 1.0.0 upload-sourcemaps .
sentry-cli releases -p xxx finalize 1.0.0
```

### Expected Result

Script output:
```
...
Source Map Upload Report
  Minified Scripts
   ...
    ~/build/js/108-9b9ae4878114352e2a62.js (sourcemap at 108-9b9ae4878114352e2a62.js.map)
   ...
  Source Maps
   ...
    ~/build/js/108-9b9ae4878114352e2a62.js.map
   ...
```

### Actual Result

Script output:
```
...
Source Map Upload Report
  Minified Scripts
   ...
    ~/public/build/js/108-9b9ae4878114352e2a62.js (sourcemap at 108-9b9ae4878114352e2a62.js.map)
   ...
  Source Maps
   ...
    ~/public/build/js/108-9b9ae4878114352e2a62.js.map
   ...
```
Notice `public` being added out of blue. I tried to use `--url-prefix '~/'` - didn't help. I also tried `--strip-prefix '~/public'`, no change as well. I don't even understand how Sentry came with `public` name...

I hope you can help me understand the issue, thanks!

**Comment by kamilogorek** [comment]
>  I don't even understand how Sentry came with public name...

That's new to me as well. There's no `public` const used in the entire `sentry-cli` codebase as well as in https://github.com/getsentry/rust-sourcemap which we use for source maps.

Can you provide logs in their entirety and set `SENTRY_LOG_LEVEL=debug` to run all the commands?

**Comment by senky** [comment]
🤦  my bad, I didn't `ls` to see that the `cp` I used also copied parent directory named `public`. Sorry for the alarm.
