### ISSUE TITLE
Is it possible to run sentry-cli only for rewriting sourcemap in JS environement?

### ISSUE THREAD

**Issue by saint777** [getsentry/sentry-cli#996]
I know the core is written in Rust, i need only --rewrite sourcemaps without uploading

**Comment by kamilogorek** [comment]
Unfortunately, we don't have this feature. You'll need to use our core package directly:

https://github.com/getsentry/rust-sourcemap
https://getsentry.github.io/rust-sourcemap/sourcemap/

**Comment by saint777** [comment]
@kamilogorek okay, i'll wait for this feature.
