### ISSUE TITLE
add binaries cache for yarn

### ISSUE THREAD

**Issue by begoat** [getsentry/sentry-cli#997]
npm use [npm_config_cache](https://docs.npmjs.com/cli/v6/using-npm/config#cache)
while
yarn use [npm_config_cache_folder](https://classic.yarnpkg.com/en/docs/cli/cache/#toc-change-the-cache-path-for-yarn)

but according to https://github.com/getsentry/sentry-cli/blob/fd32a498568ded3ff1606190d50a2044a5b3c083/scripts/install.js#L96

`sentry>script>install.js` can only read npm_cache_cache which is used by npm

**Comment by kamilogorek** [comment]
Thanks!
